### ISSUE TITLE
CronArchive module: refactor, add tests, clean code

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10032]
Our CronArchive module is a key component of Piwik platform. The goal of this issue is to improve the codebase of the CronArchive, especially:
- Refactor the class into smaller classes, for readability and maintainability.
- Write tests for most parts, since most parts are critical.
- At the end it should be easy to understand and well tested.

(there are several interesting CronArchive open issues: https://github.com/piwik/piwik/issues/10031 #9753  #8261 #7856 #6754 #6055  #9849 #9113 #315) 

issue created from a major undiscovered-for-four-years bug found in the module: https://github.com/piwik/piwik/issues/9468

**Comment by ihatehandles** [comment]
Interesting. Last week I spent a good 3+ hours going over the source passively for CronArchive looking at places I could clean up and tests to write, opened Sublime and it's the file I left open. Happy to join whoever's going to take this on (if anyone is) since I'm now quite familiar with the source.

**Comment by mattab** [comment]
Thanks for creating this issue! We appreciate your input. This issue covers a lot of ground, and it's a bit too broad for us to tackle effectively as is. So, we're going to close it for now.

But don't let this stop you! If you've got specific ideas or improvements related to this topic, feel free to open new issues for each one. That way, we can dive into them in more detail.

**Comment by gausam** [comment]
@mattab well, you created this issue! 😁
