### ISSUE TITLE
add some "events" to demo

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#10054]
Add some "events" to demo, on https://demo.piwik.org/
to show demonstrate how event reports look like
and prevent empty sites

one simple idea would be to track opening of
- website selector menu
- period selector menu
- segment selector menu

Otherwise it looks like this:
![2016-04-14_15h28_37](https://cloud.githubusercontent.com/assets/5681880/14529727/379b4c14-0256-11e6-94fc-0defbb6fcce1.png)

**Comment by tsteur** [comment]
This is done here btw: https://demo-anonymous.piwik.org/index.php?module=CoreHome&action=index&idSite=1&period=year&date=today#?module=Events&action=index&idSite=1&period=year&date=today

It would be nice to demo more features though. Would need to add some events in forum or so

**Comment by hpvd** [comment]
@tsteur: since piwik is not doing selftracking here, of course these has to be added to forum-website - sorry
Thanks for pointing to other demo!

**Comment by Findus23** [comment]
demo.matomo.org now shows events:
https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=day&date=yesterday#?idSite=62&period=day&date=yesterday&category=General_Actions&subcategory=Events_Events
