### ISSUE TITLE
Behaviour of "Apply to all websites" in User permission management

### ISSUE THREAD

**Issue by mgonera** [matomo-org/matomo#10056]
Option of "Apply to all websites" populates chosen setting (none/view/admin) only for all sites **existing at moment the applying is done**.

Case that customer brings is that after using "Apply to all websites" one expects that it will be always the case, that this user will forever always have access to all websites.

Maybe we could use some other option just for that?

ping @mattab

**Comment by tsteur** [comment]
I guess it always depends where the site selector is used. I'm not sure if one expects in the users management to also get access to new sites as well as it could also be a problem for some. Maybe should rename in users management "Apply to all existing websites". Even more correct would be probably "Give access to all websites I currently have access to". I think if a user with admin access selects this, the user wouldn't get access to actually all websites.

**Comment by mgonera** [comment]
@tsteur do you think we could also use another option "give access to all sites in the future"? :)

**Comment by tsteur** [comment]
Pretty much everything is possible hehe. Just a matter of effort :) It would require a schema change and a bit more complex logic for sure. Might be doable in 1-2 days.

**Comment by mgonera** [comment]
@tsteur @mattab can we mark it as an improvement to the roadmap?

**Comment by tsteur** [comment]
Sure. I think there are 2 steps for this:

1) Change translation to "Apply to all current websites" or "Give access to all websites I currently have access to"
2) Add another list item to also apply this to new websites. We would still need option 1) as not everyone wants actually this behaviour to give them access to newly created websites as well

**Comment by mattab** [comment]
Should be fixed
