### ISSUE TITLE
When embedding full Piwik in another application via iframe, "View detailed visitor log" link does not work 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10079]
## Reproduce
- Embed Piwik Dashboard via iframe
- In widget "Real time visitors" click on the footer link "View detailed visitor log" 
- Got: the page becomes white (see screenshot)
- Expected instead: the visitor log should load and replace the dashboard.

Screenshot

![empty](https://cloud.githubusercontent.com/assets/466765/14673395/d3858efa-0751-11e6-94a1-2295f0dc872a.png)

Reproduce on demo: https://demo.piwik.org/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=1&period=week&date=yesterday

Reported in forums: https://forum.piwik.org/t/piwik-and-iframe/18726/7

**Comment by sgiehl** [comment]
Wouldn't it be a cleaner solution to remove those links in Widgetize mode?
If someone widgetizes the dashboard or any other site, I don't think the intention is to let the user switch between the pages. If we would make those links working there wouldn't be a way back to the previous "page".

**Comment by mattab** [comment]
sounds good to remove those links in widgetized mode :+1:
