### ISSUE TITLE
 On email reports the conversion rate is zero always

### ISSUE THREAD

**Issue by faridnasiri** [matomo-org/matomo#10109]
Hi
after receiving daily reports , on "all referrer " part , the last column is always zero 

![3845fb3bb1b1dc333ff83500ba6579557fb31830_1_690x183](https://cloud.githubusercontent.com/assets/18749865/14940884/4294cf06-0f9d-11e6-8ec1-88fc9d295007.png)

**Comment by sgiehl** [comment]
Did you have any goal / eCommerce conversions for the reports date range?

**Comment by faridnasiri** [comment]
yes the conversion rate is  visible on eCommerce area  but not on daily report  as seen on below images.
thanks

![11](https://cloud.githubusercontent.com/assets/18749865/14949083/3ca1753a-105c-11e6-989a-105cc9481f73.PNG)
![22](https://cloud.githubusercontent.com/assets/18749865/14949084/411e0f74-105c-11e6-8879-cb58ca958bc7.PNG)
