### ISSUE TITLE
Feature request: User accounts view pagination

### ISSUE THREAD

**Issue by rick-pri** [matomo-org/matomo#10129]
With over 31000 piwik user accounts, and growing, we're finding that the user management page isn't really scaling very well for us.

**Comment by tsteur** [comment]
Thank you for creating the issue. I can imagine this is not usable. We hope to improve the user manager usability in https://github.com/piwik/piwik/issues/8119 and https://github.com/piwik/piwik/issues/6187 . I will leave this issue open so we don't forget it when working on #6187 or maybe we can work on this sooner.

**Comment by Findus23** [comment]
From https://forum.matomo.org/t/neuen-benutzer-hinzufuegen-am-anfang-der-seite/26866

A quick improvement would be adding a "add user button" at the top of the list, so one doesn't need to scroll down.
