### ISSUE TITLE
Is it maybe possible to optimize count(distinct) SQL queries?

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10188]
As I was reading this very interesting article: https://www.periscopedata.com/blog/use-subqueries-to-count-distinct-50x-faster.html I am wondering whether these findings could be applied to our SQL queries in Piwik? 

We have had performance issues with processing `COUNT( DISTINCT field )` on our very large datasets... maybe there is actually a possibility to improve archiving performance. Help is most welcome!

**Comment by tsteur** [comment]
I'm pretty sure I tried this when I had a look at this last time but definitely worth having a look again at some point

**Comment by andristeiner** [comment]
Today, i stumbled upon this as well while debugging slow reports when using custom date ranges. I was able to identify the `count(distinct)` queries as the culprit, then found this article: https://www.sisense.com/blog/use-subqueries-to-count-distinct-50x-faster/, and finally this existing ticket.

Let me know when we can assist you with some testing.

**Comment by mattab** [comment]
The team would re-create issue later if needed
