### ISSUE TITLE
Tracking Affiliates Referrals with Piwik (attributing a contact form submit to the correct original referrer) 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10190]
Piwik could be used as the backend of an affiliate platform technology, to help attribute to the correct Source (Affiliate / Website) a new given Lead (or Client / Customer / Contact Form submit / Email newsletter subscription / Sale / etc.). 

Because Piwik knows which referrer has been used by the user (and [this info](http://piwik.org/faq/general/faq_18254/) is [stored in a first party cookie](https://piwik.org/faq/general/faq_146/)) , Piwik would simply let you fetch (in JavaScript for example) the URL / Referrer that was used by the new client to find the website and convert.

The referrer/ attribution information could then be copied into your CRM tool, into the Email message sent to your Sales team, etc.

Todo:
- Write a FAQ or User Guide or blog post to explain this use case, 
- Ideally giving a real world  example

If you use Piwik for attribution and affiliate marketing, please leave a comment!

**Comment by silverark** [comment]
@mattab I would be very interested in this. I was thinking that I can create affiliate ID's add add them as campaigns, then am I right in thinking that Piwik would do that hard work of tracking everything else that user does, including conversion under the right campaign (i.e. affiliate)?

**Comment by mattab** [comment]
@silverark Yes it should work, let us know how you go? note: you will want to credit the first referrer by default: http://piwik.org/faq/general/faq_106/

**Comment by silverark** [comment]
@mattab I've now implemented this, it works brilliantly. I didn't realise campaign codes and keywords were dynamic so it was really easy to set up. I just created an campaign name (affiliate ID) using the users User_id from another system then I could dynamically generate them a link. They can even track their own campaigns using the sub-campaign keywords. Thanks for the tip on the first referrer.

**Comment by mattab** [comment]
Also see: [ How do I create a simple affiliates system and track new customers and new revenue for each affiliate?](https://matomo.org/faq/how-to/faq_25974/)
