### ISSUE TITLE
when --force-idsegments is specified, Piwik will archive "all visits" for the day period before archiving the segment(s), but is it necessary?

### ISSUE THREAD

**Issue by quba** [matomo-org/matomo#10234]
When specifying the `--force-idsegments` parameter, Piwik archives the day period for "all visits" and then for the specified list of segments. When archiving the week (and others) period, Piwik skips standard "all visits" archiving and archives only the specified list of segments. 

It's not needed to perform the standard archiving while forcing segments to be archived. 

In addition, it also seems to not work fully with the `--concurrent-requests-per-website`. For the day period, it starts with "all visits" and then proceeds with segments. For other periods, it starts immediately with "all visits" and first X segments.

**Comment by tsteur** [comment]
I think the first one is a feature request to not archive the regular one when `force-idsegments` is given while the `concurrent-requests-per-website` sound more like a bug.

**Comment by mattab** [comment]
> It's not needed to perform the standard archiving while forcing segments to be archived. 

I think it's needed at the moment to process the archive without segment, so that Piwik knows that there is data for the day and actually trigger the archiving. If there is no data for the day for 'all visits' then Piwik knows there is no data for segment neither, which improves performance significantly when it was implemented. 

> In addition, it also seems to not work fully with the --concurrent-requests-per-website.

different issue, please let's keep one issue per ticket :+1:

**Comment by quba** [comment]
> I think it's needed at the moment to process the archive without segment, so that Piwik knows that there is data for the day and actually trigger the archiving. If there is no data for the day for 'all visits' then Piwik knows there is no data for segment neither, which improves performance significantly when it was implemented.

Such check should be done for both "all visits" and segmented data. Then daily archiving for "all visits" could be skipped when forcing a specific segment. This would also speed up archiving when a heavy segment which returns no data is defined.
