### ISSUE TITLE
Allow users with permission 'admin' to add users with 'view' permission on their own website only

### ISSUE THREAD

**Issue by twanmeijerink** [matomo-org/matomo#10275]
Allow users with role admin to add users with view rights of there own website only.
Change of rule :http://piwik.org/faq/general/faq_69/#faq_69.

In large installations user management becomes time consuming. Giving admin these specific rights makes maintainability way more efficient.

**Comment by mattab** [comment]
Thank you for the suggestion!

**Comment by sgiehl** [comment]
This is already possible. A user can manage access for all websites he has admin access to.

**Comment by mattab** [comment]
@sgiehl Admin userdigital@etf.coms cannot yet Add new users though, which would make sense to offer as a feature.

For example a new setting such as "Allow users with 'admin' permission to create new users in Piwik [x] No (default) [ ] Yes"

**Comment by sgiehl** [comment]
Ah ok. It's about creating new users not giving any user a view access..

**Comment by sgiehl** [comment]
closing in favor of #20487
