### ISSUE TITLE
New Segment filtering for "Search Engine Rank" 

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#10314]
Would be great to make it possible to filter visits by search engine rank 

![2016-07-15_16h52_23](https://cloud.githubusercontent.com/assets/5681880/16878367/91b470d8-4aac-11e6-8cc1-1a5101b9d973.png)

could use same relation like e.g. "number of actions" do:
![2016-07-15_16h55_20](https://cloud.githubusercontent.com/assets/5681880/16878489/0b4747e0-4aad-11e6-9fbb-ef50532683dc.png)

**Comment by sgiehl** [comment]
Does this issue still make sense? Google doesn't provide a keyword at all in almost all cases. Neither do many search engines provide a keyword rank, so might be useless to segment by it.

**Comment by tsteur** [comment]
Yep 👍
