### ISSUE TITLE
Ecommerce/Products: allow variable width of columns: Product SKU /..name /..category

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#10316]
Ecommerce/Products: allow variable width of each first column
- Product SKU
- Product name
- Product category

to benefit from large screen-sizes
when dealing with long SKUs, Names, Categories...

-> Simply the same way it's greatly done on other places like
actions/Pages column of "page url"

![2016-07-15_17h54_01](https://cloud.githubusercontent.com/assets/5681880/16880432/7dab45f4-4ab5-11e6-88ba-e5bfb4dbd296.png)

**Comment by tsteur** [comment]
Just FYI: I think it is partially implemented / improved in Piwik 3 but not 100% fixed yet.

**Comment by mattab** [comment]
Hi @hpvd - does it maybe look a bit better in Piwik 3?

**Comment by hpvd** [comment]
yes it's a little better but still lots of unused space...
![2016-11-11_10h43_43](https://cloud.githubusercontent.com/assets/5681880/20211040/e4496526-a7fc-11e6-94d5-927fc1e4882a.png)

**Comment by mattab** [comment]
Thank you for the report :+1:  To likely fix the issue, could you upgrade to the latest Matomo version?
see https://matomo.org/docs/update/ 

if you still experience this issue afterwards, please re-open this and post a comment. Thanks!
