### ISSUE TITLE
All links within Matomo app that link to matomo.org/* should include campaign tracking parameters

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10336]
The Matomo application user interface often links to Matomo.org webpages to help users, for example by linking to the relevant user guide or FAQs. These links to `matomo.org/*` have a `rel=noreferrer` attribute, which results in that the requests from our users to Matomo.org do not have a referrer set. This protects the privacy of our users as we cannot track their Matomo Server URL using the referrer header (this was done in https://github.com/matomo-org/matomo/issues/3147)

## Goal

We want to know, whether a given visitor of [Matomo.org](https://matomo.org/) (or the [marketplace](http://plugins.matomo.org/), the [developer guides](http://developer.matomo.org/), has clicked to our website(s) from a link within the Matomo application.

## Proposal

- Remove all existing campaign parameters from all links in Matomo. There are various links that have various inconsistent URL parameters. I'd suggest it's easier to remove them all to start from scratch.
- Implement a new system that automatically adds campaign parameters to all links with this format (reading $module/$action from the URL):
  `&mtm_campaign=Matomo_App&mtm_source=Matomo_App_$instanceType&mtm_medium=App.$Module.$action`
 - this should apply to ideally all links visible in the UI 
 - $instanceType is either `OnPremise` or `Cloud`
 
So for example
-  for a link on the no-data page, on premise, the format would be `&mtm_campaign=Matomo_App&mtm_source=Matomo_App_OnPremise&mtm_medium=App.CoreHome.index`
- For a link on the Account Security page, on cloud, the format would be  `&mtm_campaign=Matomo_App&mtm_source=Matomo_App_Cloud&mtm_medium=App.UsersManager.userSecurity`

As a result, team members who have access to the analytics reports will be able to see how many visits are coming from the Matomo App, and how these users behave on the website.

**Comment by michalkleiner** [comment]
WIP PR — #21375
