### ISSUE TITLE
Incompatible plugin notification only names one plugin

### ISSUE THREAD

**Issue by Croydon** [matomo-org/matomo#10351]
If Piwik detects incompatible plugins it displays a warning message.
However, even the message itself is written in plural form only one plugin is randomly(?) named, even there are serveral plugins incompatible as one can see on the manage plugins site.

Just a minor bug, but it should still list all incompatible plugins.

![piwikplugins](https://cloud.githubusercontent.com/assets/1593194/17264457/535e13ca-55e7-11e6-989a-307e4946d04e.PNG)

Piwik 2.16.1, PHP 7

**Comment by tsteur** [comment]
It should list all incompatible plugins. Can you post a screen of the "manage plugins" page where it lists more invalid plugins? Or which plugins is it reporting as invalid?

Maybe we are missing a call to `isManifestFileFound` here: https://github.com/piwik/piwik/blob/2.16.1/core/Plugin/Manager.php#L1049

**Comment by Croydon** [comment]
@tsteur Incompatible are: ExampleFeedburner, SecurityInfo (which is in the message) and VisitorGenerator.

**Comment by tsteur** [comment]
For `ExampleFeedburner` it could be indeed the missing manifest file while there should be one provided for VisitorGenerator unless it is a very old version. Thanks for getting back so quickly

**Comment by Croydon** [comment]
I personally no longer use Matomo and could not reproduce this anyway.

The issue was also not a major one

And I would assume that missing manifest files in plugins might be a legacy thing, which only happens with (in the meantime) very, very old plugins.

Closing
