### ISSUE TITLE
html tags are not properly encoded in an error message during update

### ISSUE THREAD

**Issue by auchri** [matomo-org/matomo#10369]
While updating from Piwik 2.16.1 to 2.16.2 I got the following error message:
![image](https://cloud.githubusercontent.com/assets/5092164/17378989/91c1e1d2-59c0-11e6-8101-3c2d96a1b585.png)

As you can see, the html tags are not properly encoded.

**Comment by tsteur** [comment]
Thx for creating the issue, that's a bug.

**Comment by mattab** [comment]
Thank you for the report :+1:  To likely fix the issue, could you upgrade to the latest Matomo version?
see https://matomo.org/docs/update/ 

if you still experience this issue afterwards, please re-open this and post a comment. Thanks!
