### ISSUE TITLE
GeoIPCity Only showing region

### ISSUE THREAD

**Issue by wblaircox** [matomo-org/matomo#10386]
Hi folks,

Just wonder if anyone else has come across the issue that after a clean install, followed everything to the letter, installed PHP and PECL versions - it still does not show the city. Just the IP and the region (country).  I first noticed this several months ago on a client install and chalked it up to being an error with the installation. Spent all day on this, done everything I can think of, even trying other DB's I could find (with exception of purchasing the full version).

My first thought is that the legacy lite db is now past it's best before and this is the best you can get. Thoughts? Cheers!

**Comment by gaumondp** [comment]
Did you rename the file ? The Admin=> Geolocation page is your friend.

Watch also your phph.ini setting for 'geoip.custom_directory' just in case.

**Comment by wblaircox** [comment]
@gaumondp Checked the file, looks good. Deleted it several times and retried via the Admin +> Geolocation page. PHP.ini is setup correctly, according to the documentation instruction. Would there potentially be something blocked in mod_sec? I find that thing is root cause of many issues.

**Comment by hpvd** [comment]
at which place are you looking? in visitor log?
If so it maybe related to this:
https://github.com/piwik/piwik/issues/9705

**Comment by wblaircox** [comment]
Shows the same on Visitor Log, Real-Time Map, the Geo config page to the right where you can test it. I followed the thread you posted a bit, but I'm not seeing a solution, seems to be a rabbit hole of more threads. Since this appeared on my server in early spring for another site, I'll check mod_sec to see if something is being blocked.

**Comment by wblaircox** [comment]
@gaumondp @hpvd Mod_sec has been checked - no issues. Tried changing php.ini to;

;added for use with Piwik analytics
extension=geoip.so
geoip.custom_directory = "/home/~~~/public_html/~~~/misc"

Just ended up installing IP2Location. Not sure if the two can work together.

**Comment by tsteur** [comment]
In PrivacyManager do you maybe have IP Anonymization enabled and disabled to use the IP for enriched reports? You can check in Administration => Privacy Manager

**Comment by wblaircox** [comment]
I have it set to no.

**Comment by mattab** [comment]
@wblaircox is it correct that your GeoIP PECL setup is marked as "installed" in the geolocation admin, but does not actually detect any country or cities of any of your visitors?
