### ISSUE TITLE
Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by alexbarta** [matomo-org/matomo#10391]
Hi,

I report the following problem: when connecting to Visitor Log menu on some heavy queries chrome 52.0 tab crashes with  a net::ERR_INCOMPLETE_CHUNKED_ENCODING error and "Oops… there was a problem during the request" page . I tried to reproduce the problem on Firefox and IE but with those browsers it works fine. 
Also with my current setup Piwik is not able to generate any application log even on DEBUG level.

Here my specs:
OS RHEL 6.7
Piwik 2.16.0
php 5.5
httpd 2.4 (no php-fpm)
mysql 5.5
php memory_limit =2048M and max exec time at 120

Any help is appreciated.

Regards

Alex

**Comment by tsteur** [comment]
Maybe have a look at https://github.com/piwik/piwik/issues/9825 and https://github.com/piwik/piwik/issues/5081

Is maybe pagespeed or modspeed activated on your server?

**Comment by alexbarta** [comment]
Well modspeed is deactivated as it appears on system check page... any idea on which parameters on apache can tuned to avoid incomplete chunked responses?

Regards

**Comment by mattab** [comment]
@alexbarta if you generate a phpinfo() for your server, and search the output, does it mention "speed" anywhere ?

**Comment by mattab** [comment]
@alexbarta do you have a chance to try the previous comment?

**Comment by sgiehl** [comment]
Closing, as there hadn't been any further feedback.
