### ISSUE TITLE
Tag to identify messages belonging to the same archiving run

### ISSUE THREAD

**Issue by ghost** [matomo-org/matomo#10390]
Hello,

In the Piwik 2.9.1 archive output there was a tag “[xxxx]” to identify all messages belonging to the same run. as you can see on the example below:

www-data@front-1:/srv/piwik$ ./console core:archive --url=example.com
INFO CoreConsole[2016-08-10 13:29:06] **[14e52]** ---------------------------
INFO CoreConsole[2016-08-10 13:29:06] **[14e52]** INIT
INFO CoreConsole[2016-08-10 13:29:06] **[14e52]** Piwik is installed at: http://example.com/index.php
INFO CoreConsole[2016-08-10 13:29:06] **[14e52]** Running Piwik 2.9.1 as Super User
INFO CoreConsole[2016-08-10 13:29:07] **[14e52]** ---------------------------

The tag is really useful to distinguish different jobs when (and this is a very common occurrence especially running month or week archive ) they are running together at the same time.

Unfortunately, this tag has been removed in the meantime and 2.16.1 archiving output is missing it.
Is it possible to re-establish this tag into the archiving output?

Many thanks in advance,
Tomasz

**Comment by tsteur** [comment]
I'm not quite sure where it was removed and how "trivial" it is to bring it back but be nice to have it back 👍

**Comment by mattab** [comment]
:+1: it's a regression. The code is still in the repo: https://github.com/piwik/piwik/blob/master/plugins/Monolog/Processor/RequestIdProcessor.php but somehow not used/active.

**Comment by sgiehl** [comment]
This has been meanwhile fixed and should be working correctly again.
