### ISSUE TITLE
when embedding reports, iframe to resize automatically to fit 

### ISSUE THREAD

**Issue by mejiasd3v** [matomo-org/matomo#10460]
Hi,

Is there a way I could edit the iframe template? I'd like to include [iFrameResizer](https://github.com/davidjbradshaw/iframe-resizer) but I don't want to touch the source code. I was thinking in something like a plugin I could develop if you point me in the right direction (still didn't found something in the docs).

Thanks.

**Comment by mattab** [comment]
Hi @josemejiasji 

I assume you are referring to the "Opt-out iframe"? or do you refer to some other [iframes like when embedding analytics reports](http://piwik.org/docs/embed-piwik-report/) in your backoffice / application?

**Comment by josemejiasji** [comment]
Hi @mattab 

The second one. I refer the embedding analytics' iframe.

**Comment by mattab** [comment]
@josemejiasji I think in this case it would be great if you test it, and if it works well, then we could 
* document this feature directly in the guide:  http://piwik.org/docs/embed-piwik-report/
* and optionally edit the Iframe embed code, within the Piwik application, to extend it with this iframe resizer code

What do you think?

**Comment by josemejiasji** [comment]
@mattab perfect!

I'll try it and then open a PR. Thanks!

**Comment by mattab** [comment]
@josemejiasji FYI we're adding the iframe-resizer javascript project, into Piwik core in the PR: https://github.com/piwik/piwik/pull/10737 (for another reason). so it would be great to add your feature into core directly, and we now have the library you need(I think) already

**Comment by mattab** [comment]
Hi @josemejiasji did you have a chance to already look at iframe resizer?

**Comment by tsteur** [comment]
@Riegerman thanks for suggestion, I'll create an issue to see if we can add this to the default recommended iframe markup

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
