### ISSUE TITLE
Can't reuse/migrate DB from other hosting

### ISSUE THREAD

**Issue by lkrnac** [matomo-org/matomo#10474]
I am seeing exactly the same behavior as described here: https://github.com/piwik/piwik/issues/4562.

DB is on version 2.16.1. I tries to install 2.16.2 and 2.16.1, but option to "Reuse the tables" is not present. 
Environment:
Hosting: DreamHost with CloudFlare CDN
PHP version     7.0.9
Installation System Check passed with no warning or error

**Comment by sgiehl** [comment]
Closing this one, as we didn't receive any new reports on this one in that last years. If anyone has a similar problem, feel free to create a new one.
