### ISSUE TITLE
New system check diagnostic for allow_url_include=on

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10471]
> I found out why plugins/marketplace times out for me. I have allow_url_include set to off in php.ini. You should add this to system file check page and let users know why they need it.

from https://forum.piwik.org/t/cron-archive-doesnt-work-plugins-timeout/20578/2

-> we could add a new system check to help users connect their Pwik server to the Internet and use the Marketplace.

**Comment by tsteur** [comment]
👍

**Comment by mattab** [comment]
@sgiehl could you take a look at this one?

**Comment by sgiehl** [comment]
Are you sure `allow_url_include` is required? Should `allow_url_fopen` not be enough?
Would need to do some testing if we really use `include()` or `require()` for external files.

Btw. default value for `allow_url_include` is `0`, so guess it would fail on many systems then.

**Comment by mattab** [comment]
Yes you're probably right! I'll let you check :+1:

**Comment by sgiehl** [comment]
As far as I've seen `allow_url_include` should not be required. Even `allow_url_fopen` shouldn't be required as long as curl or something else is available. 
I'm not sure if such a check should be added. We already have a check for "open url", which should be enough for the marketplace, I guess?

**Comment by mattab** [comment]
The goal of this ticket is to make sure that, when an Internet connection is not possible, we explain in the System check how to configure PHP so that users will know how to enable internet connections. This is important for the marketplace connections and keeping users updated with the latest piwik release :+1:

**Comment by Findus23** [comment]
I'm pretty sure `allow_url_include` is not required by Matomo and should even be disabled for security reasons.

The explanation is already in https://matomo.org/faq/troubleshooting/faq_16646/ and adding a system check for failed API requests is tracked in #17308
