### ISSUE TITLE
path disclosure in http://demo3.piwik.org/libs/

### ISSUE THREAD

**Issue by karthickumar42** [matomo-org/matomo#10506]
go to http://demo3.piwik.org/libs/ in google chrome browser

path disclosure is displayed in http://demo3.piwik.org/libs/

fix : do not disclose path disclosure in browser

**Comment by mattab** [comment]
reverting #10931   because on some apache servers, `Options -Indexes` does not work and create 500 error and I couldn't find a solution. It's no big deal to have path disclosure in piwik folders IMHO

**Comment by randy-innocraft** [comment]
Thanks for your patience with this issue. We believe it has been resolved in the recent updates of Matomo. To ensure you have the fix, please [update](https://matomo.org/docs/update/) to the latest version of Matomo.  If the issue persists after the update, feel free to reopen this issue and let us know. Cheers!
