### ISSUE TITLE
Referrers: When Graph value is selected, it is redirecting to blank page.

### ISSUE THREAD

**Issue by ghost** [matomo-org/matomo#10535]
Referrers: When Graph value is selected, it is redirecting to blank page 

Please refer: https://youtu.be/bxNofrG7vVU

**Comment by mattab** [comment]
Hello, on your video I don't see a blank page. What do you mean exactly? it looks like it's working for me

**Comment by srinivasskc** [comment]
Blank Page means : Blank Screen, It does not show the graph, 

Can you explain the functionality when i progress on the graph, why it displays Blank Graph Screen?

**Comment by srinivasskc** [comment]
Check the video length: 0.25-0.30

**Comment by mattab** [comment]
Can you reproduce this error on demo.piwik.org as well ?

**Comment by srinivasskc** [comment]
Yes. I can do it on both demo.piwik.org also

**Comment by mattab** [comment]
Can you reproduce with Chrome or Firefox ? somehow I cannot reproduce such issue that the page becomes white...

**Comment by sgiehl** [comment]
Closing as this report is quite old, and the problem should be fixed meanwhile anyway.
