### ISSUE TITLE
Add field lastSeen in the API for the UsersManager

### ISSUE THREAD

**Issue by mwarmoeskerken** [matomo-org/matomo#10550]
In order to better manage user-accounts for Piwik it would be great if the lastSeen variable was added as a new column that is returned with the API method UsersManager.getUsers. We currently use these API-calls to export the list of users and manage access to Piwik via an external tool.

**Comment by mattab** [comment]
Sounds good, feel free to submit a pull request!

**Comment by Morerice** [comment]
@mwarmoeskerken  Is this still open?

**Comment by mattab** [comment]
yes as you can see here
![yes as you can see here](https://user-images.githubusercontent.com/466765/30687932-e23b914e-9f10-11e7-8b3f-e88f840704ae.png)

**Comment by Morerice** [comment]
@mattab Just to confirm. Does the **$userName** argument in **LastSeenTimeLogger::getLastSeenTimeForUser** refer to the user login?

`    /**
     * Returns the time a user was last seen or `false` if the user has never logged in. */

    public static function getLastSeenTimeForUser($userName)
    {
        $optionName = self::OPTION_PREFIX . $userName;
        return Option::get($optionName);
    }`

**Comment by mattab** [comment]
Hi @Morerice if you will create a pull request you need to make sure you understand this and test it. Yes, it is the user login.

**Comment by Morerice** [comment]
Thanks @mattab. That is exactly the reason why I asked the question. All UserManager tests are still correct and here is the xml received when I requested the updated **getUsers** function:

```
<result>
	<row>
		<login>anonymous</login>
		<password />
		<alias>anonymous</alias>
		<email>anonymous@example.org</email>
		<superuser_access>0</superuser_access>
		<date_registered>2017-09-21 07:04:42</date_registered>
	</row>
	<row>
		<login>super_piwik</login>
		<password>XXXXXXXXX</password>
		<alias>super_piwik</alias>
		<email>XXXXXXXXXX</email>
		<superuser_access>1</superuser_access>
		<date_registered>2017-09-21 07:06:22</date_registered>
		<last_seen>1506156455</last_seen>
	</row>
</result>

**Comment by mattab** [comment]
Hi @Morerice 
To keep it consistent let's name it `date_last_seen` and make it a date time field like `date_registered`

**Comment by ewuramaminka** [comment]
@mattab 
pls were you aable to review these updates ?
