### ISSUE TITLE
Display the "oops" red error message, only when there was an error, do not show it when user clicks away to load another menu or page

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10578]
### Reproduce
- In Piwik 3, open the dahsboard
- while the dashboard is loading, click on a top menu link
- the dashboard cancels loading the widget, as expected... However
  - Got: a red error notification message
  - Expected instead: no red notification message, as I just clicked away and this is not an error
### screenshot

![oops not needed](https://cloud.githubusercontent.com/assets/466765/18857741/e475e270-84c2-11e6-99fb-2be297d8f830.png)

Regression from 2.x

**Comment by mattab** [comment]
Note: the same problem occurs on other places which should be fixed as well:
* All websites dashboard
* the new General Settings/Admin dashboard

**Comment by tsteur** [comment]
I can't reproduce this one on Mac Chrome / FF. Also not sure how we could fix it, only thing I can think of would be to register an unload event listener and then remove all notifications again but it depends which event happens first. showing the notification or unload

**Comment by mattab** [comment]
We can only reproduce this in Firefox so far, on both Linux and Windows. Tried to find a solution to this problem but really couldn't. Maybe someone else knows how to fix this issue?

**Comment by sgiehl** [comment]
I'm not even able to reproduce that with latest Firefox on Windows. 
Note: Error messages should not be shown if a request gets aborted (see https://github.com/piwik/piwik/blob/3.x-dev/plugins/CoreHome/javascripts/broadcast.js#L565-L568)

**Comment by mattab** [comment]
fyi Still occurs with Firefox 54 on linux.

**Comment by gramakri** [comment]
Ah, I have been trying to figure out the root cause of this issue in our Cloudron installation for a while now. I can confirm that these error messages happen in Firefox 72.0.1 but not in Chrome. I am on linux.

**Comment by imc67** [comment]
Also occurs in Safari 13.0.5 (MacOS)
