### ISSUE TITLE
When an evolution graph plots two metrics at once, the right Y axis will overflow the widget container

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10602]
- In an evolution graph 
- on the dashboard
- add the metric `Bounce rate`
- Got: the right axis is partially displayed outside the container:
# screenshot Report

![right axis overflows the card](https://cloud.githubusercontent.com/assets/466765/18979344/8f7f296e-8726-11e6-8997-2f05e77bb858.png)
# screenshot widget

![widget overflow](https://cloud.githubusercontent.com/assets/466765/18979352/9f72db90-8726-11e6-99df-c147dea6f78b.png)

**Comment by tsteur** [comment]
I know that it sometimes overlaps the widgets in the dashboard and couldn't fix it. Seems some problem with jqplot which should be eventually replaced with d3 or so. I couldn't reproduce it on the Visitors Overview page. Do you have an idea why I don't get to see the 0%, 100% etc at all?

**Comment by tsteur** [comment]
If you can see the 0%, 100%, can we maybe even remove it? I think it is not super useful as it's shown on the left the correct scale and that it's 0%, 50%, 100% is kind of obvious

**Comment by mattab** [comment]
This was fixed in the meantime :clap:
