### ISSUE TITLE
Datatable footer search field sometimes ends up very small width

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10606]
sometimes (actually:rarely) the search fields is displayed with a small width instead of the normal width.

![search field is tiny sometimes](https://cloud.githubusercontent.com/assets/466765/18979560/8a909008-8728-11e6-9112-9ade6a77b515.png)

It is hard to reproduce and likely we don't need to fix it (since it's so hard to reproduce / edge case) but I thought i'd report it in case it's easy to fix.

**Comment by tsteur** [comment]
Not easy to fix :)

**Comment by mattab** [comment]
Moving back to 3.0.0
