### ISSUE TITLE
Make capitalisation consistent for "Add new XYZ" links

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10638]
The links for adding websites/ users/ scheduled reports/ alerts/ etc. should use consistent capitalisation. Currently some links are in capital letters while others are not. 

Not sure which one we should go for, but maybe `Add new Xyz` is better than `ADD NEW XYZ`

**Comment by guangjie** [comment]
Hi @mattab, is this issue still up for grabs? I know it's a little late into the last few days of Hacktoberfest.

**Comment by mattab** [comment]
@guangjie Yes, all opened issues are :+1:

**Comment by guangjie** [comment]
Great! Can I request a screenshot to where exactly you are referring to? Because, I'm a not 100% sure if I know where this problem is occurring on.

**Comment by mattab** [comment]
Hi @guangjie you'll have to search all the "Add new XYZ" text and check in the UI, as this is the purpose of this ticket :-)
