### ISSUE TITLE
Automatically merge 3.x-dev branch into master whenever the 3.x-dev branch automated tests build is green

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10677]
The goal of this issue is to implement  automatic merging of 3.x-dev branch into master branch, whenever the development branch (3.x-dev) automated tests build is green.
#### Implementation

Hopefully it is quite easy to implement using:
- Travis CI webhooks
- Define an end point with a script that has git repo push access
- Run the few git commands to merge the develop branch into master and push
#### As a result we will
- always have a green master branch
- we can release Piwik 3.X releases regularly and painlessly.

**Comment by sgiehl** [comment]
Closing this one, as we are not using the master branch for anything anymore.
