### ISSUE TITLE
3.0b1: show evolution as number on all overview sites

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#10716]
Would be handy to see evolution as number (xxx%) on all overview sites
(like it's already on referres)

![2016-10-07_18h03_40](https://cloud.githubusercontent.com/assets/5681880/19197146/a03f01ba-8cb8-11e6-80f6-54b06c08e1d8.png)

**Comment by tsteur** [comment]
If we can enable this using some generic solution that we can reuse and already exists in core then we enable this feature also on other Overview sparkline reports such as `Visitors -> Overview` and `Goals -> Overview` and `Ecommerce -> Overview`.

If it takes more than 8 hours to complete this we stop working on it.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/widget-difference-in-percents-for-traffic-with-yesterday/46832/3
