### ISSUE TITLE
Concurrent requests are not working as one can assume 

### ISSUE THREAD

**Issue by marucha** [matomo-org/matomo#10728]
We have one site with 16 segments, when we will run archiving process with concurrent-requests-per-website=8 then archiving will run 8 threads.
But when 6 threads will finish job after 10 minutes we will have only 2 threads active because archiving process will wait until all threads doesn't finish job and then run another 8 threads.
It should run new thread when one will finish job, this way you have always 8 threads running at a time.

**Comment by filippog** [comment]
FWIW I agree it would be nice to have no idle threads. To make sure I've understood: in the case above it would mean constantly feeding the threads with archival requests to make, IOW keep working on jobs if there are idle threads?

**Comment by mattab** [comment]
This should be fixed now I believe, if not please reopen
