### ISSUE TITLE
Show which user created a Goal

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10736]
It would be useful to know, which users has created a given goal. This could be displayed on hover on the Goal name in the submenu, and maybe shown in the "Edit goal" screen as a read-only field.

**Comment by hpvd** [comment]
yes this would be fine!
Since this is e.g. usefull when doing some cleaning/optimizing of things set up within piwik, it would be also very handy to show the date of creation.
-> what do you think?

**Comment by hpvd** [comment]
when use this cleaning setup or similar would be handy to not only show both on hover but directly in manage goal table => so one could easily check if goals set up 2 years ago are still usefull/needed/functional...

**Comment by hpvd** [comment]
would be also useful for "segments"...

**Comment by hpvd** [comment]
date should not contain "created" only but "created/lastmodified" (latest date)

**Comment by mattab** [comment]
Thank you for creating the issue, very appreciated :raised_hands: 
As it aligns with Issue https://github.com/matomo-org/matomo/issues/18434, I'll close this one. It would be great to have your perspective there.
