### ISSUE TITLE
Implement regional changes of France in geoipregionvars.php

### ISSUE THREAD

**Issue by Fensterbank** [matomo-org/matomo#10749]
Since 2016 some regions changed in France, e.g. [Grand Est](https://en.wikipedia.org/wiki/Grand_Est) is a new region merged from Alsace, Champagne-Ardenne and Lorraine.
These changes should be implemented in `geoipregionvars.php` and in the region map of france.

**Comment by mattab** [comment]
Thanks for the suggestion @Fensterbank  - maybe you are able to make a pull request? would be great!

**Comment by Fensterbank** [comment]
I don't think it can be done by me easily. The map has to be updated and what's happening with old visits referenced to old regions?
Just updating `geoipregionvars.php` would screw everything up.

Unfortunately I don't have the free time to dig deep into this topic, just noticed the issue.

**Comment by mattab** [comment]
Geoip2 is using the new french regions correctly :+1: 
next we would need to update the Map to show the regions correctly (currently regions are only shown correctly in the normal reports, tables/graphs and not in the country map)
