### ISSUE TITLE
Real time Traffic Sources like in Google Analytics

### ISSUE THREAD

**Issue by lipis** [matomo-org/matomo#10743]
It would be great if we had something similar here.. where we could see the the active sources and the last 30min (or one hour)..

<img width="777" alt="screen shot 2016-10-16 at 18 02 24" src="https://cloud.githubusercontent.com/assets/125676/19418745/c55de5d8-93ca-11e6-841a-031de07854b6.png">

**Comment by atom-box** [comment]
Main conversation about this is here: https://github.com/matomo-org/matomo/issues/19134

**Comment by mattab** [comment]
Thank you for creating the issue!

Closing to include in the broader issue in https://github.com/matomo-org/matomo/issues/19134
