### ISSUE TITLE
Document config setting multi_server_environment=1 for when Piwik is deployed on multiple servers

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#10777]
New config setting `multi_server_environment=0` was introduced in https://github.com/piwik/piwik/pull/10737 - this config setting should be set to  1 when you're using more than one server for your Piwik installation. For example if you are using Piwik in a load balanced environment, if you have configured failover or if you're just using multiple servers in general. By enabling this flag we will for example not allow the installation of a plugin via the UI as a plugin would be only installed on one server, or a config file change would be only made on one server instead of all servers.

-> we should test a bit more this setting, and then document it in a FAQ, as well as mention/link in the [load balanced FAQ ](http://piwik.org/faq/new-to-piwik/faq_134/) etc.

**Comment by madsem** [comment]
never happened with adding that to documentation eh :) hard for new users like me to follow the whole set up process of load balancing.

Not meaning to sound like an ass, I really appreciate all your hard work. ;)

**Comment by mattab** [comment]
Added the doc for this setting in: https://matomo.org/faq/new-to-piwik/faq_134/

> in your config.ini.php, below the section [General], add the following line: multi_server_environment=1. This setting lets Matomo know you’re using multiple servers and for example it will then not allow the installation of a plugin via the UI (or the plugin would be only installed on one server), or it will not allow config file changes from the UI (as the config file would be updated on one server only).
