### ISSUE TITLE
Exception "Referrer type '' is not valid" when consulting transitions between pages

### ISSUE THREAD

**Issue by S2E-RSD** [matomo-org/matomo#10894]
Hi !

We have the following exception when we want to consult transitions between pages
`"Referrer type '' is not valid" `

Could you please help us finding a solution?

We have just installed the last stable version (2.17) but the problem is still there.
 

Thanks a lot for your help.

Regards,
Eric

**Comment by mattab** [comment]
Hi @S2E-RSD 
we haven't seem this error before. A few questions:

What was the URL when you get this error (without your hostname) ?
Could you post a screenshot?
do you use any custom plugin?

**Comment by S2E-RSD** [comment]
Hi Aubry,

Thanks for your reply.

The URL is /piwik/index.php?module=CoreHome&action=index&idSite=3&period=day&date=2016-07-13#
Or /piwik/index.php?module=CoreHome&action=index&idSite=3&period=day&date=2016-07-06#?module=Actions&action=menuGetExitPageUrls&idSite=3&period=day&date=2016-07-06

Screenshot :
[cid:image001.png@01D24FAA.0EC6A620]

Regards,
Eric GAMBARDELLA

De : Matthieu Aubry [mailto:notifications@github.com]
Envoyé : mardi 6 décembre 2016 05:58
À : piwik/piwik
Cc : Ese INFOCENTRE; Mention
Objet : Re: [piwik/piwik] Exception "Referrer type '' is not valid" when consulting transitions between pages (#10894)


Hi @S2E-RSD<https://github.com/S2E-RSD>
we haven't seem this error before. A few questions:

What was the URL when you get this error (without your hostname) ?
Could you post a screenshot?
do you use any custom plugin?

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
