### ISSUE TITLE
Read Environment variables into Matomo config 

### ISSUE THREAD

**Issue by pierreozoux** [matomo-org/matomo#10914]
Modern web application read their config from env variables.

https://12factor.net/config

it would be a really nice to have :)

**Comment by tsteur** [comment]
This would be useful for passwords etc. For other config there is some "danger" that config is not the same on all servers which causes Piwik to not work properly etc but for passwords it would be useful for sure

**Comment by SonOfBytes** [comment]
Yes 12 factor support (environment var injection) for all the variables that happen at config would be really useful.  That would allow us  to run dev/staging piwik containers on the same hosts pointing to separate DBs etc.

**Comment by webwurst** [comment]
For configuration `env` variables are great, but it is discouraged to use them for secrets: https://github.com/docker/docker/pull/9176#issuecomment-99542089

**Comment by SonOfBytes** [comment]
Secrets are not a clear definition, because the domain of trust needs to be known.  Often secrets contained to the environment is good enough so trying to protect processes from each other is overkill.  Other times not leaking to the underlying system is critical.  The solution and the controls it offers needs to be assessed with the risk and against relevant attack trees.

So for example using something like credstash in the container runtime to inject sensitive vars is good enough for many use cases as it is separating the management of the app from the management of the environment it is running in.

**Comment by butzopower** [comment]
This would specifically be useful for deploying Piwik on cloud-based platforms with ephemeral filesystems that don't persist file changes across deploys / restarts, such as Cloud Foundry or Heroku.

**Comment by vfbsilva** [comment]
Any advance regarding this?

**Comment by mattab** [comment]
No

**Comment by mattab** [comment]
Hi @pierreozoux @vfbsilva @SonOfBytes 
We are considering implementing this feature in a plugin. 
Could you maybe confirm if reading ENV variables was for database information (host, name, password,...) only if if you had other use cases of ENV variables for Matomo?

**Comment by bbodenmiller** [comment]
I think it could be useful for pretty much all settings. Take Grafana for instnace... all settings can be set by env variable: http://docs.grafana.org/installation/configuration/#using-environment-variables

**Comment by tsteur** [comment]
FYI: I've implemented to read database config from environment variables optionally during installation see https://github.com/matomo-org/matomo/pull/13676

To read any other variables during runtime basically I suggest someone could work on a plugin. I might quickly have a look if that plugin can be easily developed.

**Comment by pierreozoux** [comment]
Wow :) amazing ;)

Https://12factor.net ftw!

**Comment by mattab** [comment]
Hi @pierreozoux  
Did you maybe have a chance to test the new plugin at https://github.com/matomo-org/plugin-EnvironmentVariables ?

I'm closing this as done as AFAIK @baywet is using it for a private project and it was working :tada:

**Comment by toredash** [comment]
@ZuSe 
I've got the same issue, https://github.com/matomo-org/plugin-EnvironmentVariables/issues/1

**Comment by mingfang** [comment]
we need matomo to support env variables natively, not using another plugin.
