### ISSUE TITLE
ERROR: Failed to get data from API: The Super User has disabled the Segmentation feature

### ISSUE THREAD

**Issue by eldk** [matomo-org/matomo#10918]
Hello,

Piwik 3.0.0-b3

When stats are public using anonymous user, and segmentation is disabled for public page, one error message is displayed "sometime" on first access : 

`ERROR: Failed to get data from API: The Super User has disabled the Segmentation feature. `
`#0 /way/to/piwik/core/Archive.php(225): Piwik\Segment-&gt;__construct('visitorType%3D%...', Array)`
`#1 /way/to/piwik/plugins/VisitsSummary/API.php(29): Piwik\Archive::build('5', 'day', 'last7', 'visitorType%3D%...')`
`#2 [internal function]: Piwik\Plugins\VisitsSummary\API-&gt;get('5', 'day', 'last7', 'visitorType%3D%...', 'nb_visits,nb_ac...')`
` #3 /way/to/piwik/core/API/Proxy.php(219): call_user_func_array(Array, Array)`
` #4 /way/to/piwik/core/API/Request.php(236): Piwik\API\Proxy-&gt;call('\Piwik\Plugins\...', 'get', Array)`
`#5 /way/to/piwik/core/API/Request.php(398): Piwik\API\Request-&gt;process()`
` #6 /way/to/piwik/plugins/VisitFrequency/API.php(51): Piwik\API\Request::processRequest('VisitsSummary.g...', Array)`
` #7 [internal function]: Piwik\Plugins\VisitFrequency\API-&gt;get('5', 'day', 'last7', false, 'nb_visits_retur...')`
` #8 /way/to/piwik/core/API/Proxy.php(219): call_user_func_array(Array, Array)`
` #9 /way/to/piwik/plugins/API/API.php(388): Piwik\API\Proxy-&gt;call('\Piwik\Plugins\...', 'get', Array) `
`#10 [internal function]: Piwik\Plugins\API\API-&gt;get('5', 'day', 'last7', false, false)`
` #11 /way/to/piwik/core/API/Proxy.php(219): call_user_func_array(Array, Array)`
` #12 /way/to/piwik/core/Plugin/Visualization.php(264): Piwik\API\Proxy-&gt;call('\Piwik\Plugins\...', 'get', Array)`
` #13 /way/to/piwik/core/Plugin/Visualization.php(181): Piwik\Plugin\Visualization-&gt;loadDataTableFromAPI()`
` #14 /way/to/piwik/core/Plugin/Controller.php(249): Piwik\Plugin\Visualization-&gt;render()`
` #15 /way/to/piwik/plugins/VisitsSummary/Controller.php(121): Piwik\Plugin\Controller-&gt;renderView(Object(Piwik\Plugins\CoreVisualizations\Visualizations\JqplotGraph\Evolution))`
` #16 [internal function]: Piwik\Plugins\VisitsSummary\Controller-&gt;getEvolutionGraph()`
` #17 /way/to/piwik/core/FrontController.php(518): call_user_func_array(Array, Array)`
` #18 /way/to/piwik/core/FrontController.php(122): Piwik\FrontController-&gt;doDispatch(NULL, NULL, NULL)`
` #19 /way/to/piwik/core/dispatch.php(34): Piwik\FrontController-&gt;dispatch()`
` #20 /way/to/piwik/index.php(27): require_once('/way/to/p...')`
`#21 {main}`

Thanks,

Eric

**Comment by eldk** [comment]
Thanks

**Comment by eldk** [comment]
Hello,

It's happened for login users too not only for anonymous.

Thanks.

**Comment by michalkleiner** [comment]
We don't think this is an issue anymore since the code related to this has been refactored. If you think this is still a problem please open a new issue. Thank you for your understanding.
