### ISSUE TITLE
pivacy settings per website

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#11009]
When using piwik as multisite tracking tool, privacy settings (like ip anonymization, delete reports, respectation of do not track) should be possible per website not per complete piwik installation.

Reason:
there may be different requirements for each website:
- testing or live
- different kinds of business
- different kinds of user-groups
- active in different countries 
-...

**Comment by tsteur** [comment]
Definitely, I'm missing this feature as well. Be good to have 👍

**Comment by es86de** [comment]
I miss that feature too.

**Comment by tsteur** [comment]
closing this issue as a duplicate of https://github.com/matomo-org/matomo/issues/11009
