### ISSUE TITLE
Add refresh / reload button to visualizations (eg tables, pie, bar chart, ...)

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#11047]
It would be sometimes really useful when the mouse is already in the visualization to be able to reload only one widget / visualization / report within a page instead of having to move the mouse to the menu item and reload the whole page which may take longer to load than just one widget.

**Comment by tsteur** [comment]
This would be awesome to have and is easy to develop.

We could show it left to the Zen Mode icon

![image](https://user-images.githubusercontent.com/273120/50496074-4162ae80-0a92-11e9-8dde-5a21ac130484.png)

I'm finding it always annoying having to click on the left menu again to reload an entire page (wouldn't implement reloading a single report only to keep things simple and to not having two different refresh possibilities as you would always also need to be able to reload the entire page.

It is especially annoying when you want to reload a page within a dropdown, eg you have to click on goal selector again, search through the long list of goals and select the same goal again

![image](https://user-images.githubusercontent.com/273120/50496129-8dadee80-0a92-11e9-9839-762faa5b37af.png)

There is of course the browser refresh, but it takes much longer to reload the entire page than just a single report.

**Comment by sgiehl** [comment]
was fixes with https://github.com/matomo-org/matomo/pull/19261
