### ISSUE TITLE
Visits overview (with graph) rows to display not preserved

### ISSUE THREAD

**Issue by Dehumanizer77** [matomo-org/matomo#11046]
After recent upgrade to 3.0.0 I have noticed that the dashboard widget "Visits overivew (with graph)" is not preserving the number of rows (days) to display. If I change it to anything else than 30, it gets reset back to 30 after reload. In previous versions, this has been preserved over reloads. It would be great if the preserving of this setting could be brought back.

**Comment by justinvelluppillai** [comment]
This appears to be fixed now.
