### ISSUE TITLE
Display alias instead of username next to annotations

### ISSUE THREAD

**Issue by fvdm** [matomo-org/matomo#11062]
When I created my first Piwik account it felt like a good idea to use a random username, like I do nearly everywhere, but I didn't know you can not change that later. All throughout Piwik the user alias is displayed except with Annotations.

On a Dashboard widget (Visits Over Time) a long username is using way too much space and for other users the alias would be more meaningful too.

![piwik3_annotation_username](https://cloud.githubusercontent.com/assets/93784/21404643/8275f324-c7c2-11e6-99cc-c60dd86de967.png)

**Comment by mattab** [comment]
Thanks for the report @fvdm 

It's a good idea and feel free to issue a pull request :+1: 

> All throughout Piwik the user alias is displayed except with Annotations.

Where did you notice we display the alias instead of username?

I'm wondering whether we should display both username and alias (one of them maybe as tooltip or so)...

**Comment by CheweyZ** [comment]
In the annotations DB the only variable handed in is the users name string there is no reference to the alias in the user session so this cannot be done without sending a request to user DB

**Comment by tsteur** [comment]
The user alias was removed so this issue should be no longer needed.
