### ISSUE TITLE
Error in Piwik (tracker): Error query: SQLSTATE[HY000]: General error: 1366 Incorrect string value: 

### ISSUE THREAD

**Issue by tehseenkn** [matomo-org/matomo#11136]
Mysql 5.6.16-Log
piwik 2.11.2

Http Link:

http://localhost/pwk2112/piwik.php?action_name=&idsite=1&rec=1&r=713679&h=12&m=43&s=27&url=http%3A%2F%2Fcategory%2F%C3%90_%C3%90%C2%BA%C3%91_%C3%90%C2%B5%C3%91_%C3%91_%C3%91%C6%92%C3%90%C2%B0%C3%91%E2%82%AC%C3%91%E2%80%B9%2Fcid-90409%2F%26%26page_yxm%3D18&_id=231bc7088d3af7ec&_idts=1483421432&_idvc=2&_idn=0&_refts=0&_viewts=1483429407&send_image=0&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1600x900&gt_ms=1776
action_name=&idsite=1&rec=1&r=713679&h=12&m=43&s=27&url=http%3A%2F%2F%2Fcategory%2F%C3%90_%C3%90%C2%BA%C3%91_%C3%90%C2%B5%C3%91_%C3%91_%C3%91%C6%92%C3%90%C2%B0%C3%91%E2%82%AC%C3%91%E2%80%B9%2Fcid-90409%2F%26%26page_yxm%3D18&_id=231bc7088d3af7ec&_idts=1483421432&_idvc=2&_idn=0&_refts=0&_viewts=1483429407&send_image=0&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=0&gears=0&ag=0&cookie=1&res=1600x900&gt_ms=1776

when i visit this link on local machine the above error occur.

Error in Piwik (tracker): Error query: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xC3__\xC3_\xC2...' for column 'name' at row 1                                 In query: INSERT INTO piwik_log_action (name, hash, type, url_prefix) VALUES (?,CRC32(?),?,?)

**Comment by mattab** [comment]
Hi @tehseenkn 
This seems to not trigger any error in Piwik 3. although the Page URL report doesn't maybe look correct:

![russian](https://cloud.githubusercontent.com/assets/466765/21619181/6c5e8538-d253-11e6-8039-700505e854a9.png)

 Could you please ugprade to Piwik 3 and report whether it works well or not?

**Comment by mattab** [comment]
Upgrade ASAP to Piwik 3!!

There are many security issues in 2.11.2 so you are very unsafe

**Comment by tehseenkn** [comment]
I have upgraded piwik 3.0.3 and php 7.0.16 x64 nts, but still same type of error is coming in php error file.

**Comment by tehseenkn** [comment]
I am putting the link may be this helps you to clear the actual problem.
http://stackoverflow.com/questions/8291184/mysql-general-error-1366-incorrect-string-value

**Comment by tehseenkn** [comment]
In piwik_log_action successfully store the url and Dashboard is displaying url completely but error occurs in php error file.

**Comment by mattab** [comment]
@tehseenkn What is the full piwik.php string that you can reproduce this error?

**Comment by MERamadan** [comment]
Hello,
We are facing the same issue with Matomo 3.9.1. 

The full url is

http://localhost/piwik.php?idsite=1&rec=1&apiv=1&r=420739&uid=devdc%5ccr01&_idts=1556699326&_idvc=0&_id=c59b493d1cf02142&url=http%3a%2f%2f10.50.158.200%3a4040%2fec_followup%2f1645ac8d-19f3-e811-813d-005056bb148b%2fFollowUp%2fFollowUp%2f%D8%AA%D9%81%D8%A7%D8%B5%D9%8A%D9%84+%D8%A7%D9%84%D9%85%D8%AA%D8%A7%D8%A8%D8%B9%D8%A9+-+2018%2f6%2f014%2f08.html&dimension1=2b725006-bf1c-e611-80d2-0050568e7fa1&dimension2=Internal&dimension3=1645ac8d-19f3-e811-813d-005056bb148b&dimension4=ec_followup&action_name=Task%2fec_followup%2f1645ac8d-19f3-e811-813d-005056bb148b

Can you please advise?

Thanks,

**Comment by MERamadan** [comment]
Here the full Matomo error page 

<div class="box">

	<div class="header">
		<h1>An error occurred</h1>
	</div>

	<div class="content"><p>Error query: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD9_\xD8\xA7\xD8\xB5...' for column 'name' at row 1 In query: INSERT INTO ec_log_action (name, hash, type, url_prefix) VALUES (?,CRC32(?),?,?) Parameters: array (
  0 => '10.50.158.200:4040/ec_followup/1645ac8d-19f3-e811-813d-005056bb148b/FollowUp/FollowUp/ت�_اصيل المتابعة - 2018/6/014/08.html',
  1 => '10.50.158.200:4040/ec_followup/1645ac8d-19f3-e811-813d-005056bb148b/FollowUp/FollowUp/ت�_اصيل المتابعة - 2018/6/014/08.html',
  2 => 1,
  3 => 0,
)</p><span style="color: #888888">Backtrace:<br /><pre>#0 D:\matomo-latest\matomo\core\Tracker\Model.php(182): Piwik\Tracker\Db\Pdo\Mysql->query('INSERT INTO ec_...', Array)
#1 D:\matomo-latest\matomo\core\Tracker\Model.php(163): Piwik\Tracker\Model->insertNewAction('10.50.158.200:4...', 1, 0)
#2 D:\matomo-latest\matomo\core\Tracker\TableLogAction.php(101): Piwik\Tracker\Model->createNewIdAction('10.50.158.200:4...', 1, 0)
#3 D:\matomo-latest\matomo\core\Tracker\TableLogAction.php(49): Piwik\Tracker\TableLogAction::insertNewIdsAction(Array, Array)
#4 D:\matomo-latest\matomo\core\Tracker\Action.php(345): Piwik\Tracker\TableLogAction::loadIdsAction(Array)
#5 D:\matomo-latest\matomo\plugins\Actions\Tracker\ActionsRequestProcessor.php(70): Piwik\Tracker\Action->loadIdsFromLogActionTable()
#6 D:\matomo-latest\matomo\core\Tracker\Visit.php(152): Piwik\Plugins\Actions\Tracker\ActionsRequestProcessor->afterRequestProcessed(Object(Piwik\Tracker\Visit\VisitProperties), Object(Piwik\Tracker\Request))
#7 D:\matomo-latest\matomo\core\Tracker.php(138): Piwik\Tracker\Visit->handle()
#8 D:\matomo-latest\matomo\core\Tracker\Handler.php(49): Piwik\Tracker->trackRequest(Object(Piwik\Tracker\Request))
#9 D:\matomo-latest\matomo\core\Tracker.php(120): Piwik\Tracker\Handler->process(Object(Piwik\Tracker), Object(Piwik\Tracker\RequestSet))
#10 D:\matomo-latest\matomo\core\Tracker.php(97): Piwik\Tracker->track(Object(Piwik\Tracker\Handler), Object(Piwik\Tracker\RequestSet))
#11 D:\matomo-latest\matomo\piwik.php(76): Piwik\Tracker->main(Object(Piwik\Tracker\Handler), Object(Piwik\Tracker\RequestSet))
#12 {main}</pre></span>    </div>

    <div class="footer">
        <a href="index.php">&laquo; Back to Matomo</a>
    </div>

</div>

**Comment by tsteur** [comment]
I reckon this refs https://github.com/matomo-org/matomo/issues/9785 ?

**Comment by sgiehl** [comment]
We have meanwhile introduced support for UTF8mb4, which should have fixed issues like this one.
