### ISSUE TITLE
'Users'  tab no data: explain how to populate Users report data

### ISSUE THREAD

**Issue by ResonHou** [matomo-org/matomo#11175]
I just used Piwik as the analytics system and it works well, but the data in 'Users' is null.
I assume that the data in 'Users' shoud be the users registered in website, is that correct ? and why there's no data ?
thanks a lot.
![piwik-users](https://cloud.githubusercontent.com/assets/9674322/21831579/b46dff0c-d7df-11e6-8ff2-56739c927fc2.png)

**Comment by AmirIqbal1** [comment]
Seems to be an field which you can put custom queries in it. Even the demo on their site has no data. 

Here is a link; 

https://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday#?idSite=3&period=day&date=yesterday&category=General_Visitors&subcategory=UserId_UserReportTitle

**Comment by mattab** [comment]
Please see the documentation for this feature here: https://piwik.org/docs/user-id/

I think the best way to "solve" this issue would be that, when there is no data in the Users report, display a notification / help message explaining to users what this feature is, and how to populate data in the report. A link to the user guide would be very useful :+1:
