### ISSUE TITLE
Event tracking with trackEvent: a value of 0 (zero) is not recorded

### ISSUE THREAD

**Issue by aj-justo** [matomo-org/matomo#11204]
I am manually tracking events with this code:
`_paq.push(['trackEvent', 'docs', 'feedback', document.title, 0]);`

The last argument, value, is either 1 or 0. Anything > 0 gets recorded correctly, for instance, 0.1, but 0 is not. I get a "-" in the table of events.

Related to this, I tried passing string values instead ("yes", "no"), and they do not get recorded at all (I always see a "-" in the events table).

I cannot find any details on the supported types/ranges for the value argument, can anybody please give me a clue as to how this exactly works or point me to the documentation about it?

**Comment by mattab** [comment]
Thanks for the bug report @ajweb

**Comment by tsteur** [comment]
this was fixed in #13537
