### ISSUE TITLE
Ukraine on the map

### ISSUE THREAD

**Issue by twixi** [matomo-org/matomo#11266]
Ukraine on map not correctly reflects one region!
[Map in PIWIK (not separate regions!) ](https://s29.postimg.org/4a8gn3vjb/image.jpg)
[Really country map](https://s29.postimg.org/g0me4hobr/image.jpg)

**Comment by Globulopolis** [comment]
@twixi you mean that this region not an Ukrainian region anymore and piwik map should be corrected accordingly?

**Comment by twixi** [comment]
This region is only Ukrainian!
But his show not correctly on piwik map, in piwik showed one region "Crimea", but Ukraine have region Kherson and Crimea, in piwik showing like one!

**Comment by Globulopolis** [comment]
This is disputable region. Anyway... No more politics.
See https://github.com/piwik/piwik/issues/9719 (about build script)

**Comment by twixi** [comment]
Kherson is not politics! His not show on map only!
[https://en.wikipedia.org/wiki/Kherson_Oblast](https://en.wikipedia.org/wiki/Kherson_Oblast)

**Comment by sgiehl** [comment]
As @Globulopolis mentioned. We won't be able to work soon on that. We currently have no free capacities to work on fixes for the map. Maybe there is a volunteer who is keen on building a new one or fixing the current. If so, feel free to get in touch with us: hello@piwik.org

**Comment by sgiehl** [comment]
closing in favor of https://github.com/matomo-org/matomo/issues/11929
