### ISSUE TITLE
Lost archived segments data after 3.0.1 update

### ISSUE THREAD

**Issue by benoitpointet** [matomo-org/matomo#11394]
Since the update to Piwik 3.0.1, our Piwik no longer displays data for archived segments. 

Ad-hoc computed segments, on the other hand, display data normally (even archived segments if their archiving is switched off).

Deleting and rebuilding the archive data did not help.

**Comment by mattab** [comment]
Thanks for the report. Does anyone else experience this issue? we haven't been able to reproduce this so far.

**Comment by sgiehl** [comment]
This should have been improved / fixed meanwhile.
