### ISSUE TITLE
The contradiction of Piwik's analysis

### ISSUE THREAD

**Issue by ChrisR1993** [matomo-org/matomo#11393]
Hello everyone,
I have a question about the result of analysis.
For example, the number of a PDF unic download is 59, and I search the same PDF link with customer segment, then the number turned to 127...

why is this happened? was this got to do with that "others" thing?

**Comment by mattab** [comment]
Hi @ChrisR1993 

This should not happen. Could you please post a screenshot of both reports that show the problem?

**Comment by sgiehl** [comment]
Closing as there hadn't been any further feedback.
