### ISSUE TITLE
Daily Evolution graph tooltips should always show the year

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#11452]
When viewing evolution graphs for example for the last 500 days, the tooltip is missing the Year and this creates confusion as some of the context is lacking. tooltiplooks like this:

![missing year](https://cloud.githubusercontent.com/assets/466765/23527693/43b8da18-ff97-11e6-99f4-60e5257cf7f6.png)

-> Let's add the year in the date format in the tooltip

**Comment by mattab** [comment]
Note: weekly / monthly evolution graphs tooltips show the year as expected, so issue really only occurs for daily graphs

**Comment by sgiehl** [comment]
We currently have no date format in Piwik we could use for that. The shown date format is the short day format, which does not include a year. The long format would, but it would also include the full day and month names. We could replace this format to contain the year, but that would affect all days shown in short format. I'll prepare a short PR, to use the UI tests to check what else would change

**Comment by sgiehl** [comment]
@mattab this won't be easy to change for the tooltips only. Guess we would need to change a bit more to make that possible. Shall we postpone this issue to after 3.0.3?

**Comment by mattab** [comment]
Any idea of the effort for this change?

Moving it out of 3.0.3

**Comment by mattab** [comment]
This was fixed in the meantime
