### ISSUE TITLE
Cookie warning pops up in IE11 ShowModalDialog

### ISSUE THREAD

**Issue by oldcookie** [matomo-org/matomo#11507]
When the tracker is being initialized, configCookiesDisabled is set to true by default.  When `hasCookies()` is called by `detectBroweserFeatures()` during initialization, this causes a cookie warning dialog to popup twice(each time `navigatorAlias.cookieEnabled`) is accessed.  This occurs every time the modal dialog is opened.

```            
           function hasCookies() {
                if (configCookiesDisabled) {
                    return '0';
                }
                if (!isDefined(navigatorAlias.cookieEnabled)) {
                    var testCookieName = getCookieName('testcookie');
                    setCookie(testCookieName, '1');
                    return getCookie(testCookieName) === '1' ? '1' : '0';
                }
                return navigatorAlias.cookieEnabled ? '1' : '0';
            }
```

**Comment by mattab** [comment]
On IE11 and Win7 I'm not seeing a popup or warning on https://piwik.org

![blog](https://cloud.githubusercontent.com/assets/466765/24171489/fb168934-0e84-11e7-875a-bf4f9e8dd3d8.png)


@oldcookie 
* do you use the default JavaScript tracker code on your website or have you customised it in any way?  
* What website URL do you see this warning on IE11? 
* can you see this warning / popup on piwik.org?

**Comment by oldcookie** [comment]
1. Yes, default tracker code.
2. It's an proprietary webapp that uses a lot of modal dialogs.
3. I can get it to happen on piwik.org if I open up the console and call window.showModalDialog("http://piwik.org")

**Comment by mattab** [comment]
Ok thanks for the report. Do you maybe know how to fix this problem?

**Comment by oldcookie** [comment]
@mattab We break this down into two problems:
1. Cookie is required: don't think this is fixable without IE changing it's behavior.
2. Cookie is disabled: Since cookie is enabled by default and detection of cookie occurs during initialization—before disableCookie can be called—there is currently no way to get around these modals.  

To fix #2, may be can can delay the cookie detection until the call to trackPageView?

**Comment by siva538** [comment]
@mattab , we are planning to modify this in the following way, so we can validate this every time consistently.

FYI - we also got the same issue popped up with IE and showmodal dialog combination.

`     
function hasCookies() {
                if (configCookiesDisabled) {
                    return '0';
                }

				var testCookieName = getCookieName('testcookie');
				setCookie(testCookieName, '1');

				return getCookie(testCookieName) === '1' ? '1' : '0';
            }
`

Let us know if you see any concerns with this approach. Thanks in advance.

**Comment by mattab** [comment]
@siva538 could you please open a pull request and not there what issue / use case does it help with? Thanks

**Comment by siva538** [comment]
Sure @mattab . Will do. We ran into an issue with this when there were repeated popup messages as mentioned in screenshot on 3/22/17 above, and browser was asking to insert a cookie. 

However the reality was "navigatorAlias.cookieEnabled" is not supported in IE browser during "Show Modal Dialog".

Reason for weightage is that there are still huge number of users across the globe using IE and this fix would help avoid the unnecessary popup's when Modal is used.

Thank you.
