### ISSUE TITLE
Email reports not sending

### ISSUE THREAD

**Issue by JHKLaren** [matomo-org/matomo#11534]
After numerus re-installs and cleaning all Piwik files on my server, email reports still won't send (as off 15 dec 2016). Only way at this moment is to check-in and activate the mail manually. Before the 15th of december everything was working as it should work. There is no schedule for sending email and I didn't activate the cron as advised for large databases.
Clean installs preformed after 15th december 2016 had all this issue and I can't get a grip on it. At the server side nothing changed. Also tried with a downgrade in the PHP version, but that didn't work either.

What is the big change in the Piwik install/update as of the 16th of last december???

![screen shot 03-27-17 at 02 53 pm](https://cloud.githubusercontent.com/assets/26544136/24357360/b77be070-12fd-11e7-87d4-5b7e51fb6d95.JPG)
![screen shot 03-27-17 at 02 56 pm](https://cloud.githubusercontent.com/assets/26544136/24357359/b7768b7a-12fd-11e7-8acf-d124c74bf225.JPG)

**Comment by mattab** [comment]
In the [TasksTimetable](http://plugins.piwik.org/TasksTimetable) page, you should see entries for each of the scheduled reports to be sent out. For example `Piwik\Plugins\ScheduledReports\API.sendReport_2` for id report = 2.

**Comment by JHKLaren** [comment]
Hi Matt,

 

In the screenshots (see attachments) you can see the scheduled reports and the entries in the TaskTimetable. 

 

Hartelijke groet,

 

Jan Herm Klaren

+31644991306

 <mailto:janherm@tenderproductions.nl> janherm@tenderproductions.nl

 <http://www.tenderproductions.nl/> www.tenderproductions.nl

 



 

 

 <https://tender.productions/> Eerste hulp bij aanbesteden

JH Klaren (Interim) Tender Management en Advies

H/O Tender Productions en Contractveilingen kvk 53054059 BTWnr. NL139012734B01

Kempen 5  2036 EJ  Haarlem

BIC: INGBNL2A  IBAN: NL70INGB0005173613

 <http://www.tender.productions/algemene-voorwaarden> Algemene voorwaarden

 

Van: Matthieu Aubry [mailto:notifications@github.com] 
Verzonden: maandag 8 mei 2017 21:30
Aan: piwik/piwik <piwik@noreply.github.com>
CC: JHKlaren <jh@tenderproductions.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [piwik/piwik] Email reports not sending (#11534)

 

In the TasksTimetable <http://plugins.piwik.org/TasksTimetable>  page, you should see entries for each of the scheduled reports to be sent out. For example Piwik\Plugins\ScheduledReports\API.sendReport_2 for id report = 2.

**Comment by mattab** [comment]
Hello,
We have created a FAQ to help about this issue: https://matomo.org/faq/troubleshooting/faq_34856/

Hopefully it will help people get their emails working. if you have any issue with receiving emails from Matomo please follow the FAQ and let us know how it goes (by following the "Contact support" link in the FAQ). Have a great day!
