### ISSUE TITLE
we have no "time on url": Piwik handels events as leaving page (at least in visitor log)

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#11546]
we have no "time on url": Piwik handels events as leaving page (at least in visitor log)
how is it handled on other places within piwik?

.. and some other thoughts derived from this https://github.com/piwik/piwik/issues/11546#issuecomment-289736115

![2017-03-28_12h36_23](https://cloud.githubusercontent.com/assets/5681880/24401587/457a2e1a-13b5-11e7-99f2-ef192b5e60dc.png)

**what is the consequence?**

Example:

Different "Only one page visitors" visits two different pages
with both containing:
- text
- images
- large version of images in lightbox
- lightbox usages is tracked via event (open LB, next image etc...)

The difference:
page 1:
great long text + many good images (starting explaining content of the text)

page 2:
great long text + many awesome images (colorfull, well structured, explaining content of the text, great captions)

**what happens?**

on page 1:
people coming to the site
will read the text and
after some time,
some will look at 
a part of the large versions of the images (they know the content because of reading the text)
(open light box = event)

on page 2:
people coming to the site
will directly look at the large versions of the images (open light box = event)
look at the details,
read their captions
etc
after that some will read the first part of the text
(they know the content because of looking at images and reading their captions)

**Results shown in Piwik (visitor log):**
Page 1: 6 minute [avarage] (+ some short events)
Page 2: 1 minute [avarage] (+ many long events)

so what do I gather from this as website owner?
Page 1 is far better
page 2 needs optimization

with this
=> **I have no chance to notice that full visit time maybe even longer on page 2.**

**Comment by hpvd** [comment]
what would one need:
1) a possibility to know "full time on page" (including all events, some kind of "time on url")
imho this should be the base for all metrics, shouldn't it??

2) a possibility to measure "time directly on page"  for cases where there are events open a new "layer" on same url: for this one need some kind of marker within an event (open new layer + close layer)

with this:
"time directly on page" = "full time on page"- "time between event with marker opening a new layer and event with marker closing new layer"

**Comment by mattab** [comment]
Hi @hpvd

I may be wrong, but it sounds like the solution is simply to use the Heat beat timer. please find more information here: https://developer.piwik.org/guides/tracking-javascript-guide#accurately-measure-the-time-spent-on-each-page

**Comment by hpvd** [comment]
hmmm- heart-beat timer is in use.
One can easily proof this, because also very short one page visits show a duration in visitorlog

**Comment by hpvd** [comment]
so there is no solution yet,

**Comment by mattab** [comment]
If heartbeat timer is in use, then the time on page should be accurate. unless the feature does not work for some reason?

**Comment by hpvd** [comment]
as described, time on page is only fine in the headline (sum) of a visit in vistor log, but not for the single url within the visit.

**Comment by mattab** [comment]
@hpvd Do you mind reporting a simple list of steps to reproduce the issue? Ie. track page view, track event, track event, wait 1 min, Expected to see XYZ, Got instead: ABC. Would be very helpful and we'll take a look.

**Comment by hpvd** [comment]
1. have a visit with only one page view,
2. some events (triggered at this page)
3. leave.

=> time in headline of the visit (summary) in visitor log is fine.
=> time shown on hover on page is time until first event happen.

=> imho: would expect to see on hover on a page the total / full time on page until this page is left. No matter if there are any events during page view or not.

**Comment by hpvd** [comment]
imho: events shoud be a "child" or "subpart" of the time on a page

**Comment by hpvd** [comment]
2) in https://github.com/piwik/piwik/issues/11546#issuecomment-289736115
is a new "special variant"

**Comment by hpvd** [comment]
with this:
Tracking of events, shorten the measured time on page.

**Comment by jarrodldavis** [comment]
I think I'm having the same issue as @hpvd – if a page view has subsequent events, the page view time is only measured as the time between the initial page view and the first event. Essentially, every event is counted as a separate "page" rather than sub-events of the page they occurred on.

**Comment by hpvd** [comment]
Possibly there is a strong relationship to: https://github.com/piwik/piwik/issues/9198

**Comment by sgiehl** [comment]
This behavior should be meanwhile improved with https://github.com/matomo-org/matomo/pull/18294
Everything else should be covered in  of https://github.com/matomo-org/matomo/issues/9198
