### ISSUE TITLE
Document adding Custom JS to tracker via tracker.js / tracker.min.js

### ISSUE THREAD

**Issue by loki495** [matomo-org/matomo#11572]
Is there a way for a plugin to add custom JS to tracker response and have the piwik.js parse/execute it? 
https://forum.piwik.org/t/returning-json-jsonp-from-tracker/23657

**Comment by tsteur** [comment]
It is technically possible but as @mattab mentioned there are no docs which actually is missing because it is not really a public API and neither supported right now. Basically you can create a `tracker.js` file or `tracker.min.js` file in your plugin and it will be copied into the piwik.js

**Comment by mattab** [comment]
@tsteur maybe we could make this public API in Piwik 4? (moving tentatively)

**Comment by tsteur** [comment]
could maybe make it but maybe lets see again when we get to it. Would require a bit more work and especially documentation. Not having a big opinion on it but would need to think more about it also for long term how this should work

**Comment by johsin18** [comment]
What is also undocumented is that the plugin class needs to override the method isTrackerPlugin like so

``
    public function isTrackerPlugin()                                                                      
    {                                                                                                      
        // declare that this plugin's tracker(.min).js should be included in the JavaScript tracker code   
        return true;                                                                                       
    }                                                                                                      
``

My plugin broke with Matomo 3.13 due to lacking this code, I had to make a bugfix release.
https://plugins.matomo.org/DevicePixelRatio/changelog

**Comment by tsteur** [comment]
@johsin18 fixed the `isTrackerPlugin` regression in https://github.com/matomo-org/matomo/pull/15954 and documented the tracker in https://github.com/matomo-org/developer-documentation/pull/345 which now only needs a review.

**Comment by tsteur** [comment]
@loki495 things are now documented in https://developer.matomo.org/guides/enrich-js-tracker
