### ISSUE TITLE
Piwik 3.0.2: Geolocation from server misses some city and ISP data

### ISSUE THREAD

**Issue by iprok** [matomo-org/matomo#11582]
I have nginx with geoip module. I've set it up using https://piwik.org/faq/how-to/#faq_166 . I see that it's working in Admin Page -> Geolocation. I use commercial MaxMind databases with ISP. It shows me correct information about my Country, City, ISP, Organization in Admin Page -> Geolocation . I've surely turned on GeoIP (server module) and saved my settings.

The problem is that in live users widgets it sometimes miss City information (all IPv6 and some IPv4) (I get IP of missed users and check in the maxmind DB that I have - it surely exist there: both IPv6 and IPv4) and I have no ISP information at all!

**Comment by iprok** [comment]
I have turned off "hide visitor IP" setting.

**Comment by mattab** [comment]
For the ISP information please see: https://piwik.org/faq/how-to/faq_180/

Could you paste here example of IPs and how they got geo located wrong and what exist in the maxmind db?

**Comment by iprok** [comment]
faq_180 has link to https://piwik.org/faq/how-to/#faq_166

For now I have only problem with ISP information. I have correctly set this $_SERVER variables:

    GEOIP_ADDR
    GEOIP_COUNTRY_CODE
    GEOIP_COUNTRY_NAME
    GEOIP_CITY
    GEOIP_ORGANIZATION
    GEOIP_ISP

For example: I got from Admin Page -> Geolocation:
Org: Hurricane Electric
ISP: Hurricane Electric

But in all statistics I just got russian (I have russian locale) word "Провайдер" (meaning "ISP") instead of correct ISP name.

**Comment by samuelliu** [comment]
die genaue parameterbezeichnung: 
       'MM_COUNTRY_CODE',
        'MM_COUNTRY_NAME',
        'MM_REGION_CODE',
         'MM_REGION_NAME',
        'MM_LATITUDE',
         'MM_LONGITUDE',
         'MM_POSTAL_CODE',
       'MM_CITY_NAME',
        'MM_ISP',
         'MM_ORG',

**Comment by sgiehl** [comment]
closing this. We now have a working GeoIP2 implementation and GeoIP (Legacy) is deprecated
