### ISSUE TITLE
EU is called "Unknown" in the country overview

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#11588]
![screenshot_20170404_175326](https://cloud.githubusercontent.com/assets/6266037/24666350/5f226e26-1960-11e7-9b94-37fa97408354.png)

It seems like the same thing happens to "ap" (Asia/Pacific Region) on demo.piwik.org so there are three "unknown" sections. (ap is also missing a flag)

![screenshot_20170404_180310](https://cloud.githubusercontent.com/assets/6266037/24666563/fd41d3da-1960-11e7-9e97-dd9a80ee7f00.png)

**Comment by mattab** [comment]
Thanks for the report. Since Europe, Asia/Pacific are not countries, we shouldn't detect them as countries. we could just detect them as Europe / Asia in the "Continent" report.

**Comment by mattab** [comment]
Thanks for the report. Since Europe, Asia/Pacific are not countries, we shouldn't detect them as countries. we could just detect them as Europe / Asia in the "Continent" report.

**Comment by Findus23** [comment]
@sgiehl 
This should be solved with the GeoIP2 migration as there are no more EU and AP countries in GeoIP2.

**Comment by sgiehl** [comment]
Right. This won't happen for new reports after the migration...

**Comment by Findus23** [comment]
This should be fixed now with GeoIP2.
