### ISSUE TITLE
Piwik JavaScript Tracker: Add possibility to set URL parameters to ignore

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#11627]
For a Piwik website or globally, it is already possible to exclude / ignore URL parameters. However, because the default request method is `GET`, ignored URL parameters would be still visible in the access log of the Piwik server.

Instead it would be great to be able to have a method in the JS tracker to ignore URL parameters like `_paq.push(['setIgnoreUrlParams', 'sid', 'cid']);`. Not sure what a good method name would be.

Because Piwik knows server side which parameters to ignore, we could also re-use this information in the JavaScript tracking code generator and automatically set this parameter.

In the tracker itself we already have a method `removeUrlParameter()` to remove a URL parameter so it should be not too hard to develop.  We would add this probably to the method `purify(url)` where we already modify the URL based on configuration.

**Comment by sijezi** [comment]
@tsteur is this still open? If it is, I would like some guidance as it is going to be my first `pr`. 

Thanks.

**Comment by mattab** [comment]
Hi @wehelie Yes, the issue is still opened. A pull request would be great :+1:
