### ISSUE TITLE
Better adblock detection during setup

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#11660]
In my opinion #5094 is still an issue. The warning introduced in #8949 is appended at the end of the page, so depending on the page one needs to scroll a lot to see it (which many people won't do if they think it's broken)

But the bigger issue is that it isn't added to the setup page. As a result, people may think something is broken with their install.

e.g: https://forum.piwik.org/t/fresh-piwik-installation-is-missing-any-design/24037
![screenshot_20170429_192906](https://cloud.githubusercontent.com/assets/6266037/25557482/7e7576d6-2d12-11e7-8203-50a78f6e3ade.png)

An additional idea would be adding a block informing the user that the CSS files can't be loaded and hiding it via CSS (and add accessibility tags to don't annoy screen reader users) so it is only visible if the CSS file doesn't load

**Comment by sgiehl** [comment]
> An additional idea would be adding a block informing the user that the CSS files can't be loaded and hiding it via CSS (and add accessibility tags to don't annoy screen reader users) so it is only visible if the CSS file doesn't load

Guess that makes sense. We could also do the same for javascript. Having a block that gets hidden as soon as javascript is loaded
