### ISSUE TITLE
“Available metrics” not visible in “Evolution of multiple rows”

### ISSUE THREAD

**Issue by ferfebles** [matomo-org/matomo#11735]
As created by finner in the piwik forum: https://forum.piwik.org/t/available-metrics-not-visible-in-evolution-of-multiple-rows/23276

> In Actions > Pages > Evolution on multiple rows, the usual dropdown with the options Pageviews, Unique Pageviews, Avg. time on page, Bounce Rate, Exit rate, Avg. generation time does not show up.

> But I can see the heading "Available metrics" and I can see the dropdown in the code:

```
  <div class="metric-selectbox">
        <h2>Available metrics</h2>
        <select name="metric" class="multirowevoltion-metric">
                                <option value="nb_hits" selected="selected">
                    Pageviews
                </option>
                                <option value="nb_visits">
                    Unique Pageviews
                </option>
                                <option value="avg_time_on_page">
                    Avg. time on page
                </option>
                                <option value="bounce_rate">
                    Bounce Rate
                </option>
                                <option value="exit_rate">
                    Exit rate
                </option>
                                <option value="avg_time_generation">
                    Avg. generation time
                </option>
                        </select>
     </div>

```
Piwik: 3.0.1
Chrome: 56.0.2924.76 (64-bit)
Firefox: 51.0.1 (64-bit)
Arch Linux 4.9.6-1 ARCH
Cinnamon 3.2.8

**Comment by ferfebles** [comment]
I've experienced the same error:

Server
Piwik version: 3.0.1
MySQL version: 5.5.5
PHP version: 7.1.4

Client
Windows 10
Firefox 47.0.2
Chrome 58.0.3029.96

**Comment by sgiehl** [comment]
This seems to be fixed meanwhile.
