### ISSUE TITLE
System Check: "Missing file: /usr/share/piwik//etc/apt/trusted.gpg.d/piwik-keyring-automatic.gpg" when using APT repository

### ISSUE THREAD

**Issue by theraser** [matomo-org/matomo#11743]
Hello,

using Piwik 3.0.4 with Debian 8 you get the following error when calling the "System Status" page:
> Errors below may be due to a partial or failed upload of Piwik files.
> --> Try to reupload all the Piwik files in BINARY mode. <--
> 
> Missing file: /usr/share/piwik//etc/apt/trusted.gpg.d/piwik-keyring-automatic.gpg

I don't think that this is a critical issue but it may confuse beginners ;-) The path after "/usr/share/piwik/" seems to be a little odd.

Here's the repository configuration:
```
deb http://debian.piwik.org/ piwik main
deb-src http://debian.piwik.org/ piwik main
```

This error was also mentioned [here](https://forum.piwik.org/t/file-integrity-error-after-update-to-3-0-2/23447) in March '17 using Piwik 3.0.2.

**Comment by jrblevin** [comment]
For what it's worth, I'm seeing exactly the same thing. Like you, I am running Debian 8 and Piwik 3.0.4.

It seems the `/usr/share/piwik/` prefix is added erroneously when checking for the file, because the file does exist under `/etc/apt/...`.

**Comment by mattab** [comment]
Hi @jrblevin @theraser 
Could you please try the patch in https://github.com/piwik/piwik/pull/12022 and let us know if it helps at all?

**Comment by jrblevin** [comment]
I patched my FileIntegrity.php in place. Of course, now I see a file integrity error about FileIntegrity.php (so I know the check ran again), but unfortunately the error about piwik-keyring-automatic.gpg is still showing up as well.

**Comment by jrblevin** [comment]
I’m not sure if this is useful, but in my config/manifest.inc.php, there is a hash entry for  "/etc/apt/trusted.gpg.d/piwik-keyring-automatic.gpg". Other files have only relative paths listed there.

**Comment by mattab** [comment]
Hi @aureq 
It seems that our [Debian package](https://debian.piwik.org/) has an extra line in the file integrity array in `config/manifest.inc.php` 

Do you know how we could remove this line from the manifest?  thanks!

**Comment by aureq** [comment]
Looking into it...

**Comment by Findus23** [comment]
As no one reported this issue since, I assume this fix worked for everyone and this can be closed.
