### ISSUE TITLE
Make possible to report since midnight rather than lasts 24 hours

### ISSUE THREAD

**Issue by Glisse1** [matomo-org/matomo#11785]
Hello,
i`m a long time user of piwik and i want to make this feature request if possible: make it possible to select between "today" and "last 24 hours" in some sort of setting. 

I said it several times in the past years, in forums and others places, google s (and virtually every other analytics platform out there that i know) that considers "today" as "today starting from midnight" is the only one making sense rather than piwik s approach with last 24 hours. Forum post were ignored.

I ll say it again, i  dont want to see monday at 4 pm in the live dashboards statistics for the last 24 hours since sunday at 4. 

I want TODAY  to see the statistics of TODAY ONLY, starting with midnight, just like in google analytics. Maybe that`s why i use just 2-3 widgets out of all the possibilities. 

If this choice of yours is such a strong design requirement, absolutely ok, no problem, but give an option somewhere to switch to a more "classic" approach.. Just like u did in the end with the 24 hour time, instead of enforced 12 with am/pm. I am sure that many, many others are not voicing their frustration but would also want to have the option of choice. 

In the past 6-7 months i refused to update piwik to new versions because i simply grew tired to modify core files everytime, like refactoring "last 24h" in plugins/live/control.php, and a few others... So I just let it be the way it is since december.

**Comment by justinvelluppillai** [comment]
Closing this as we now have #19652
