### ISSUE TITLE
Go through old branches and finish & get them reviewed or delete them

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#11813]
Goal of this issue is to have less opened branches on `piwik/piwik`. Each Piwik developer with an active branch shall go through each branch in https://github.com/piwik/piwik/branches/yours and either:

* delete any branch which is not needed / won't get merged, 
* or open a pull request and tag it as `WIP` when it is useful/ should get merged eventually.

**Comment by tsteur** [comment]
I just looked and there actually aren't that many left. Closed some branches that I had myself. 

@sgiehl @diosmosis @Findus23 Be great to have a look if there are any old branches that can be deleted. Be good to limit it to say 15 minutes. We wouldn't really create any PRs for still open branches though as we wouldn't work on them any time soon anyway.

So be good if everyone could have a quick look and then we can close this issue.

**Comment by diosmosis** [comment]
looked through mine and closed most

**Comment by mattab** [comment]
also closed my few branches

**Comment by tsteur** [comment]
closing this issue. @sgiehl @Findus23 feel free to check your branches as well. It's otherwise not too important.
