### ISSUE TITLE
Release a last Piwik 2.18.0 version to announce end of LTS for Piwik 2

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#11810]
As we are approaching the end of Long Term Support for Piwik 2, it will be useful to release one last Piwik 2.X package.

In this placeholder issue we keep track of what to change in this last Piwik 2.X version.

*  add an admin home page to Piwik 2, stating Piwik 2 will no longer be supported by End 2017 and that upgrade to Piwik 3 is recommended. 

* mention advantages of Piwik 3 like faster, more secure, and the availability of all the premium plugins (could mention them all). 

* Then could also mention migration to Piwik cloud possible

* also show the notification inviting users to upgrade at the top of Reporting UI

**Comment by mddvul22** [comment]
Hi Matthieu,

We are running 2.17.1 LTS in our environment.  When this final LTS release appears (either 2.18.0 or 2.17.2), will there be a Piwik 3 LTS version?

Thanks!

**Comment by sgiehl** [comment]
@mattab  guess we should work on that somewhen soon...

**Comment by mattab** [comment]
@sgiehl :+1: I suggest we do it once 3.3.1 is out and all issues currently in the milestone are fixed.

**Comment by mddvul22** [comment]
Will there eventually be a Matomo 3 LTS branch?

**Comment by mattab** [comment]
At the moment, we only support the latest version of Matomo 3.
Once we start working on Matomo 4, then Matomo 3 will be frozen and there will be a Matomo 3 LTS version for some time. Learn more about our process in this wiki page: https://github.com/matomo-org/matomo/wiki/New-major-releases

**Comment by mddvul22** [comment]
Great! Thanks for the link!

**Comment by tsteur** [comment]
@mattab  instead of adding an admin home page I might only show a notification or something. Might be easier. Just to clarify: View user wouldn't see any of those messages right? I'll probably also add a config setting to disable this info.

**Comment by mattab** [comment]
@tsteur we want to get as many people as possible to upgrade to the latest before matomo 4 Dev will start. And considering the release is out of support, from a view user point of view their data isn't stored safely and securely. So i would show the notification to all users probably, and invite them to contact their admin users to look at the new release. and let them close the reporting notification

**Comment by tsteur** [comment]
@mattab this is done, you'll need to create a release for it.

**Comment by mattab** [comment]
2.18.0 has been released. This is the last 2.X release and it now has a nice explanation page warning people about the upgrade and explaining why it's important to do so (#13448).  Users who are using the "2.x stable release channel" will be prompted to update (local test of the upgrade worked). Kuddos @tsteur for moving this forward!
