### ISSUE TITLE
E-Mail Report: Page URL Links shifted after "Others"

### ISSUE THREAD

**Issue by andristeiner** [matomo-org/matomo#11825]
Version: Piwik 3.0.4

In E-Mail Reports, Page URLs are linked to their appropriate destination. If there is a generic record for "Others" present, it will take the link destination of the following record, and the link of all records after is shifted by one.

![screenshot from 2017-06-28 13-14-39](https://user-images.githubusercontent.com/249843/27634519-c6a5bb76-5c03-11e7-9ab6-660abae45b11.png)

* first 2 records are linked correctly
* 3rd record "blog/List/Post/ - Others" is linked to "blog/List/Post.aspx?ID=102" which is the 4th record
* 4th record is linked to the 5h record destination and so on

**Comment by mibto** [comment]
Any updates on this bug? I have the same problem. Thanks for having a look at this!

**Comment by mritzmann** [comment]
The problem only occurs if a subdirectory (in the screenshot of andristeiner: "blog/Lists/Posts") is merged to "others". If summarize directly below /, the problem does not occur.

**Comment by kkrebs** [comment]
Same problem here. This is an annoying bug!

**Comment by StiftungAusNachlass** [comment]
we have exactly the same problem here with the PDF-Reports... It affects also other languages: "andere" (german) instead of "others"
