### ISSUE TITLE
GpsCoordinate Parameter in GeoIP 

### ISSUE THREAD

**Issue by Sobhika2** [matomo-org/matomo#11838]
Hi All,

I have a requirement to add a GpsCoordinate parameter to GeoIP plugin for tracking mobile device locations in Piwik.

Could anyone please tell how can we achieve this.

Regards,
Sobhika

**Comment by mattab** [comment]
Hi @Sobhika2 
Piwik already should track the latitude/longitude as given by Maxmind. There are also parameters `lat` and `long` you can use: https://developer.piwik.org/api-reference/tracking-api#other-parameters-require-authentication-via-token_auth
but they require token_auth which is not suitable in a mobile app (as the token would be leaked in the app package). 

What are you trying to achieve?

**Comment by sgiehl** [comment]
@Sobhika2 Closing this issue now, as we didn't get any feedback.
