### ISSUE TITLE
Feature Request: Tracking currency with eCommerce order

### ISSUE THREAD

**Issue by Slowlearneruk** [matomo-org/matomo#11854]
We have a fairly pressing need to be able to track the currency with an eCommerce order. We receive purchases in many currencies on the site and at the moment they are all recorded in the Piwik site currency which causes large discrepancies with the actual value of the orders. I appreciate that to reconcile the different currencies would require some kind of an exchange rate but this should at least be exposed for development of a plugin if not in the core Piwik code.

**Comment by mattab** [comment]
Yes it would be great to support multi currency in Piwik. If you have a budget feel free to contact the team @ https://piwik.org/development/

**Comment by mattab** [comment]
Thanks for the report. duplicates https://github.com/matomo-org/matomo/issues/3812
