### ISSUE TITLE
When segmenting by page URL, Events/Downloads/Outlinks/Site search reports always show no data

### ISSUE THREAD

**Issue by alfonso-romero** [matomo-org/matomo#11900]
Hi

I'm currently starting to use the events feature, and right now I'm able to track and store some test data including event categories, event actions and event names. 

The problem is on the report, when I go to Dashboard -> Actions -> Events, all 3 tabs show that "there is no data for this report". I checked the database and I can see the data correctly stored on log_link_visit_action and log_action tables with my events, but reports just won't display anything, even when I can see visitor logs correctly, the issue is only with events reports.

Of course I made sure to pick the correct site and date for the events activity I'm tracking, but reports are just not showing up.

Am I missing some setting to enable this reports somewhere else? or is there any other method or data I should implement/track to be able to see the reports?

Thanks in advance

**Edited**:

-> More experimentation has revealed that this issue only occurs when a page URL or action URL based segment is used. In a certain way this makes sense because the events themselves don't have any URL.

**Comment by GitFr33** [comment]
Are you using a segment? 

I have encountered a similar difficulty ( https://forum.piwik.org/t/piwik-events-showing-in-visitor-log-but-not-in-events-view/25409/2 ) and discovered that it only occurs when a segment other then ALL VISITS is used.

**Comment by GitFr33** [comment]
![](https://forum.piwik.org/uploads/db1181/original/2X/6/64ddacf715a3ef7fd853df4264ccf4f1ace9cbbe.png)

Can anyone else reproduce this issue?
1. Piwik installation that does not use cron
2. Piwik version 3.0.4
3. Event tracked using `_paq.push(['trackEvent', 'category', 'action', 'value']);`
4. URL based segment

I tried to reproduce this issue on the [Piwik demo](http://demo.piwik.org/index.php) and it did not occur but I was was not able to confirm conditions 1-3

**Comment by mattab** [comment]
@GitFr33 do you still experience this issue?

**Comment by GitFr33** [comment]
@mattab Yes. (using v 3.1.0)

**Comment by hpvd** [comment]
in our installation everything is working fine (3.1.1b2)
there are events shown in events widgets and also in events reports.
example:
![2017-09-18_21h32_25](https://user-images.githubusercontent.com/5681880/30560708-05608c38-9cb9-11e7-951d-48c3c2c90d5e.png)

**Comment by GitFr33** [comment]
@hpvd in the screenshot it doesn't look like you are using a segment. What happens when you select something other then All Visits in the segment dropdown?

**Comment by hpvd** [comment]
it's also working as expected. e.g. segment: device is desktop (please see attachment)

![2017-09-18_22h00_36](https://user-images.githubusercontent.com/5681880/30561935-0cfe2faa-9cbd-11e7-96e1-22827fcfe698.png)

**Comment by GitFr33** [comment]
Interesting! How did you get version 3.1.1b2? 
My instillation says it's up to date, but the version number is 3.1.0.

**Comment by Findus23** [comment]
@GitFr33 
As it is a beta release you’ll need to enable them in the settings first.

**Comment by GitFr33** [comment]
I see. Probably not a good idea for a production instillation?

**Comment by GitFr33** [comment]
Thanks for your continued assistance
I updated to 3.1.1b2 and the problem persisted. 

More experimentation has revealed that this issue only occurs when a page URL or action URL based segment is used. In a certain way this makes sense because the events themselves don't have any URL. 

Is this a bug or a feature? It certainly has had me puzzled...

**Comment by hpvd** [comment]
Just checked your named details in our installation.
Your are right!
![2017-09-20_07h15_16](https://user-images.githubusercontent.com/5681880/30627955-c5b5e9ae-9dd3-11e7-96cb-8a912beca46c.png)

@mattab : I could reproduce this problem also in 3.1.1b3 - seems to be a bug.

**Comment by hpvd** [comment]
problem seems to occur in event reports and event widgets.

**Comment by mattab** [comment]
Maybe it's similar to the issue here: https://github.com/piwik/piwik/issues/11992
which describes the "Downloads" report as not showing data for Segments Page URL contains. 
Could you please try if Downloads show data? if so, we'd mark the issue as duplicate and consolidate both issues into one.

**Comment by hpvd** [comment]
Just tested:
if segment is url the following reports are empty:
- events
- download
- sitesearch
- outlinks

=> so it's a general and with this major problem.
Should one open a new issue for it?

btw: one can easily test this if one put "page url" -contains- domain of the page.

**Comment by mattab** [comment]
Thanks @hpvd for confirming. 

>  Should one open a new issue for it?
No this issue is fine, just renamed it to broaden scope

**Comment by mattab** [comment]
This seems related:  Inform users why there is no data in some actions report when action/event segment is applied #9796

**Comment by hpvd** [comment]
Is this maybe somehow related to https://github.com/piwik/piwik/issues/11806 ?

**Comment by mattab** [comment]
@hpvd It does not look like they are related

**Comment by ChristianLuxem** [comment]
@mattab any idea in which milestone this could be fixed? I don't see it planned for a milestone yet...

**Comment by obliqueshock** [comment]
The same issue shows up even using the 'Page Name' segment. Any smart workarounds to filter on specific pages?

**Comment by metalocator** [comment]
Is there any way we can sponsor some movement on this issue?  It's a constant problem in our reporting.  We leverage events and segments and not being able to combine them is crippling.

**Comment by fabiobuda** [comment]
Dear community members,
dear @ChristianLuxem @obliqueshock @metalocator 

I'm able to reproduce the issue and I'm also able to mitigate the issue without any patch.

To get the event list when you need visitors segmented through a specific URL you have to prefer "Action URL" as URL filter. You should AVOID "Page URL".

This way you will get the same "logical" result with the advantage to make "Events UI" work.

I feel that it would be an issue related to some DB query or a serious "DB schema" issue.

I hope someone from the official team would investigate this issue.

**Comment by metalocator** [comment]
The action URL does not work for us.  The action URL is auto-completed in the segment definition, but the events report still comes up empty.

**Comment by fabiobuda** [comment]
@metalocator do you have installed the latest Matomo 3.3.0? My segment has 3 filters. Two of them are "URL action" and one is "Visit duration"... and I'm able to get events list work.

P.s.
Is your filter configured by specific URL or generic wildcard "mysection/*" ?
Is your filter configured to use one of "equals / not equal / contains / not contains" operator?

**Comment by metalocator** [comment]
Using the Action URL works in our 3.2.1 test bed, though not in 2.16.5, which is in production.  

Do we lose other stats that don't have an Action URL defined? What is Action URL exactly?

**Comment by websirnik** [comment]
I can confirm that Segments via Action URL does work for Events in Matomo 3.3.0. Though Segment for Downloads & Outlinks still does not work.

**Comment by huang0808** [comment]
I  Add "Clicked URL" Segment can not work, use matomo 3.4.0

**Comment by mattab** [comment]
In a forum thread, several users reported this breaks how they use Matomo, so i explained there how to use Custom Dimensions of action scope to still be able to set "Page categories" and segment based on these categories (a common use case/need): https://forum.matomo.org/t/filter-page-urls-by-segments/34859/9
