### ISSUE TITLE
Missing customVariables in actionDetails

### ISSUE THREAD

**Issue by Sobhika2** [matomo-org/matomo#11960]
Dear team,
Beginning from July 15, when using the Piwik Reporting API, we started observing certain actions of one of the web site (idSite 36) with a missing customVariables property. This is a new behavior not observed before that date, when every action had this property. 

Here is an example Piwik visit with two actions, the first of them doesn't have any customVariables at all:

 
  {
    "idSite": "36",
    "idVisit": "32491827",
    "visitIp": "********",
    "visitorId": "ca92f31498bd27ce",
    "actionDetails": [
      {
        "type": "action",
        "url": "https://abc.com",
        "pageTitle": "abc.com\/abc",
        "pageIdAction": "687880",
        "serverTimePretty": "Jul 15, 2017 21:10:45",
        "pageId": "138588375",
        "generationTime": "1.95s",
        "timeSpent": "1",
        "timeSpentPretty": "1s",
        "icon": null,
        "timestamp": 1500153045
      },
      {
        "type": "action",
         "url": "https://abc.com",
        "pageTitle": "abc.com\/abc",
       "pageIdAction": "687880",
        "serverTimePretty": "Jul 15, 2017 21:10:46",
        "pageId": "138588378",
        "customVariables": {
          "1": {
            "customVariablePageName1": "ServiceName",
            "customVariablePageValue1": "Global Share Participation Plan (GSPP)"
          },
          "2": {
            "customVariablePageName2": "Location",
            "customVariablePageValue2": "Zurich"
          }

The issue still persists. Could you please check and let us know the issue here.

Regards

**Comment by sgiehl** [comment]
@Sobhika2 What exactly is the problem here? If the custom variable is set in action scope and only for one of those actions, it's correct that it's only available for that action.

**Comment by Sobhika2** [comment]
The behavior reported is that there are scenarios where custom variables are not being captured at all. But for the same URL a fraction of seconds later the custom variables are available.

**Comment by sgiehl** [comment]
It seems you are setting those variables per page. That means you need to set them before each `trackPageView()` in order to have them available for each action. Is that the case?
