### ISSUE TITLE
Error in Piwik: Invalid MySQL Version

### ISSUE THREAD

**Issue by sprhawk** [matomo-org/matomo#12002]
I got many error messages from my installation:

> [error] 13191#13191: *1102 FastCGI sent in stderr: "PHP message: Error in Piwik: Invalid MySQL Version" while reading response header from upstream, client: *****, server: localhost, request: "GET /index.php?module=Marketplace&action=getPremiumFeatures&widget=undefined&idSite=1&period=day&date=today&showtitle=1&random=239 HTTP/1.1"

Piwik version: 3.0.4

I installed piwik on Azure cloud service, using MySQL on Azure service, MySQL version: 5.7

system: ubuntu 16.04 LTS
php: PHP Version 7.0.22-0ubuntu0.16.04.1
php-mysql: Client API library version | mysqlnd 5.0.12-dev - 20150407

**Comment by mattab** [comment]
Can you issue a SELECT @@version; query on the MySQL instance and report the result back?

**Comment by matfax** [comment]
Having the same issue with 3.2.0, Azure MySql reports the wrong version.

**Comment by hvcgi** [comment]
I have same issue. Result for SELECT @@version is 5.7.18.

**Comment by kiwi-x** [comment]
Hello. I'm in the same trouble now. 
Using like most here a Azure SQL Database. 

MySQL [***]> select @@version;
+-----------+
| @@version |
+-----------+
| 5.7.18    |
+-----------+

but on system summary on the settings page you see

Piwik-Version: 3.2.0
MySQL-Version: 5.6.26.0
PHP-Version: 7.0.22-0ubuntu0.16.04.1 

which is the same database version, which is shown when running the status command after connecting to the database:

MySQL [***]> status
--------------
mysql  Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Connection id:          65385
Current database:       ***
Current user:           ***@***
SSL:                    Cipher in use is AES256-SHA
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MySQL
Server version:         5.6.26.0 MySQL Community Server (GPL)
Protocol version:       10
Connection:             ***.mysql.database.azure.com via TCP/IP
Server characterset:    latin1
Db     characterset:    latin1
Client characterset:    utf8mb4
Conn.  characterset:    utf8mb4
--------------
