### ISSUE TITLE
Visitor log should display country/city information without having to hover on the country flag

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#12015]
3.1.0 RC1: visitor log: no more information about country/city visible
e.g. : flag, country, city

was nicely optimized not that long ago: https://github.com/piwik/piwik/issues/9705

![2017-09-08_15h45_43](https://user-images.githubusercontent.com/5681880/30214647-7f9580b2-94ad-11e7-9681-c486911830d8.png)

**Comment by hpvd** [comment]
ah know a found the flag: it has moved to other symbols and is hide between them ;-)
Optimization regarding showing city has gone (https://github.com/piwik/piwik/issues/9705)

**Comment by RobsImpSS** [comment]
I noticed that with the latest update of 3.1.0 the city/state/flag information that was normally above the IP address is missing on the Visitor Log page.   This location was perfect as it did not require users to hover the mouse over the flag icon to see which city/state they were from.

Would love to see this restored back to the way it previously was.

**Comment by mattab** [comment]
Thanks for the report

**Comment by RobsImpSS** [comment]
Installed 3.1.1 update today but noticed that this issue was not included in update.  Will this be fixed and updated in the future?

**Comment by hpvd** [comment]
seems to be planned to be part of 3.2  (see above https://github.com/piwik/piwik/issues/12015#event-1252703037
)

**Comment by RobsImpSS** [comment]
Just installed the new update and for the 2nd time, this issue has not been fixed.  Will city/state/region name be restored to the location where it used to be in addition to the flag that is already there?

**Comment by mattab** [comment]
@RobsImpSS The issue is still opened, which means it wasn't fixed. But yes, we plan to fix it again sometime

**Comment by RobsImpSS** [comment]
Mattab,

Will this issue ever be restored?
