### ISSUE TITLE
Unable to test if mod_pagespeed is enabled via CLI

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#12024]
While testing https://github.com/piwik/piwik/pull/12019 I noticed I get the error

> INFO [2017-09-08 12:16:39] Unable to test if mod_pagespeed is enabled: the request to http://unknown/./console?module=Installation&action=getEmptyPageForSystemCheck failed

when executing `./console diagnostics:run` 

I searched for similar issues but they seem different. Seems like `Url::getCurrentUrlWithoutQueryString()` does not return a URL.

**Comment by alexhass** [comment]
Bug still exists in 4.5

**Comment by joan31** [comment]
I confirm, bug still exist on Matomo 4.5

![image](https://user-images.githubusercontent.com/12939441/136973202-044cabd5-8aab-4f47-b42e-b95df9076cb3.png)

**Comment by asheroto** [comment]
Bug exists still

**Comment by tsteur** [comment]
Let's use `SettingsPiwik::getPiwikUrl()` and if we don't get a URL from this method then we just skip this test.

**Comment by larsen0815** [comment]
Still exists in 4.10.1
