### ISSUE TITLE
Piwik check mysql 5.7 as mysql 5.5

### ISSUE THREAD

**Issue by sprhawk** [matomo-org/matomo#12030]
I use piwik on Azure, and use MySQL on Azure service with version 5.7

But piwik check the version as MySQL 5.5.

Why and how to fix it ?

**Comment by mneudert** [comment]
Can you issue a `SELECT @@version;` query on the MySQL instance and report the result back?

I would not expect it but perhaps they messed with the version string and the current detection cannot cope with that.

**Comment by mattab** [comment]
see also https://github.com/piwik/piwik/issues/12002

**Comment by fengkaijia** [comment]
Check [this MSDN issue](https://social.msdn.microsoft.com/Forums/security/en-US/795cb2be-dce7-4805-b324-a67e83697580/azure-database-for-mysql-reports-incorrect-version), maybe it's because of Azure reporting a 5.5 server_version in handshake (not sure, never use Azure before).

**Comment by kiwi-x** [comment]
Hello. I'm in the same trouble now. (I also posted this info at #12002 )
Using like most here a Azure SQL Database. 

MySQL [* * *]> select @@version;
+-----------+
| @@version |
+-----------+
| 5.7.18    |
+-----------+

but on system summary on the settings page you see

Piwik-Version: 3.2.0
MySQL-Version: 5.6.26.0
PHP-Version: 7.0.22-0ubuntu0.16.04.1 

which is the same database version, which is shown when running the status command after connecting to the database:

MySQL [***]> status
--------------
mysql  Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Connection id:          65385
Current database:       * * *
Current user:           * * *@* * *
SSL:                    Cipher in use is AES256-SHA
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MySQL
Server version:         5.6.26.0 MySQL Community Server (GPL)
Protocol version:       10
Connection:             * * *.mysql.database.azure.com via TCP/IP
Server characterset:    latin1
Db     characterset:    latin1
Client characterset:    utf8mb4
Conn.  characterset:    utf8mb4
--------------

**Comment by sgiehl** [comment]
Closing this one as there hadn't been any further reports in the last years. If anyone experiences a similar problem, feel free to create a new issue.
