### ISSUE TITLE
Data from Visitor Summary via API ?

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#12049]
Would be pretty handy to have an easy possibility to fetch the data shown in "visitor summary" (within visitor profile) directly via API.

e.g. these values:

![2017-09-13_18h36_58](https://user-images.githubusercontent.com/5681880/30389577-8209e464-98b3-11e7-9d6a-8b52624760b7.png)

**Comment by hpvd** [comment]
or is this already available? couldn't find it in docu...

**Comment by hpvd** [comment]
when making information of summary accessible via API, one should notice that not all informations belonging to summary are positioned below the headline "summary" ;-)
Other items also belonging to summary, could be find here: https://github.com/piwik/piwik/issues/9507

**Comment by mattab** [comment]
Hi @hpvd 
Hope you are still enjoying Matomo :)
Btw yes this data is already available via the visitor profile API.
You can export it by clicking on the export button, see https://matomo.org/docs/user-profile/#exporting-visitor-profile-data
Please reopen if any data is missing in the API
