### ISSUE TITLE
Site Search tracking should not use Custom Variables

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12072]
Currently, our Site Search feature uses Custom Variables in the backend to track site searches and site search categories. We need to rewrite this feature without using Custom Variables (see https://github.com/piwik/piwik/issues/11524) so that we can deprecate Custom Variables in the future.

Since it would likely require new fields in the database, assigning to Piwik 4.

**Comment by Chardonneaur** [comment]
Hi there, I confirmed you that this issue is still active and that it populates custom variables within the database which are in fact not called within the UI, here is a video showing it all https://www.youtube.com/watch?v=2vO3VBOYAHA&feature=youtu.be

**Comment by tsteur** [comment]
@Chardonneaur we've already started working on this as part of Matomo 4 👍
