### ISSUE TITLE
Update Documentation for Hardware-Requirements

### ISSUE THREAD

**Issue by stephanfriedrich** [matomo-org/matomo#12084]
Hi i am using piwik on my raspberypi-2 and it is really slow. 
Would be nice if you can get some minimal Hardware Requirements in your Doc.

BTW, really thx for these awesome analytics tool.

**Comment by Findus23** [comment]
Hi,

The hardware requirements really depend on the use case and the number of visitors.

But if you can live with slightly delayed reports, then you can speed piwik up by disabling report generation in the browser and setting up a cronjob.

**Comment by mattab** [comment]
We've published new recommendations on minimum recommended server specs, please see: https://matomo.org/docs/requirements/#tracking-100000-pageviews-per-month-or-less

here is what it looks like now: 
![Screenshot from 2019-06-18 17-06-31](https://user-images.githubusercontent.com/466765/59654695-7bb03b80-91eb-11e9-8318-f55a1399098a.png)
