### ISSUE TITLE
Autoupdate does not work!

### ISSUE THREAD

**Issue by ghost** [matomo-org/matomo#12096]
I have the version 3.1.0 installed and it says there is a new update (3.1.1).

I clicked automatic update and after a few seconds it says it was successfully updated.
But when I return to the dashboard it still says I have version 3.1.0 and there is a new update.

I tried it a few times and it just doesn't update my piwik... I had this problem before (don't remember which version) and I had to update it manually.

I'm running this on Windows Server 2008 SP1 Standard, a few weeks ago it worked fine. I can't see any error. Also the logfiles don't report any errors

**Comment by mattab** [comment]
I have experienced this issue before, I think it's due to a caching issue. Could you try again today, whether now it works? @modsfabio

**Comment by stunna** [comment]
same here, should give write permissions:

`Error while creating/copying file to &lt;code&gt;/var/www/vhosts/xxx.com/sub.xxx.com/vendor/leafo/lessphp/plessc&lt;/code&gt;. &lt;br /&gt;Please check that the web server has enough permission to write to these files/directories:&lt;br /&gt;For example, on a GNU/Linux server if your Apache httpd user is xxx, you can try to execute:&lt;br /&gt; &lt;code&gt;chown -R xxx:psacln /var/www/vhosts/xxx.com/sub.xxx.com&lt;/code&gt;&lt;br /&gt;&lt;code&gt;chmod -R 0755 /var/www/vhosts/xxx.com/sub.xxx.com&lt;/code&gt;&lt;br /&gt;`

**Comment by sgiehl** [comment]
Closing as this looks quite outdated. We meanwhile improved a lot around permission management.
