### ISSUE TITLE
Rename `log_link_visit_action.interaction_position` to eg `pageview_position`

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#12124]
As it is incremented only on pageviews but not eg on events. At the same time we may want to think about adding a new column `interaction_position` that is also incremented on events etc but not needed for now.

**Comment by mattab** [comment]
## API

* should we also rename the `interactionPosition` in the Live API outputs to `pageviewPosition` ?

**Comment by tsteur** [comment]
yes definitely

**Comment by sgiehl** [comment]
@tsteur I've created a follow-up issue where we can implement a new `interaction_position` column. Feel free to put #15816 in a milestone where we should add it, if needed.
