### ISSUE TITLE
Expanded Datatable Report

### ISSUE THREAD

**Issue by eramirezprotec** [matomo-org/matomo#12139]
Hi! I'm trying to get the Campaigns report to load with the datatable already expanded (showing the keywords for every campaign), but I can't make it work. I've tried modifying the API of the Referrers plugin setting the "expanded" attribute to 1 in the getCampaigns method, but nothing. Using the getDataTableExpanded method does not do the trick either. Nothing seems to work. I just want the Campaigns report to be expanded automatically when it loads.

Thank you for your attention.

**Comment by RMastop** [comment]
Hi @eramirezprotec,

Try the &flat=1 URL parameter. I think it does what you need.

**Comment by eramirezprotec** [comment]
Hi, @RMastop. Thank you for answering my question.

The "flat" parameter does almost what I want, but unfortunatelly it is not an option to me because I lose the Row evolution option for the keyword (see the example image). Is there any chance to preserve the evolution row for every keyword?

![campaigns](https://user-images.githubusercontent.com/32161884/31080828-2f987b4c-a78a-11e7-8bed-957a4cd3859d.png)

Thank you.

**Comment by RMastop** [comment]
Ah, I see.

You could check marketplace for the campaign plugin.
It shows you a separate report for campaign keyword, among other reports.

![image](https://user-images.githubusercontent.com/7987117/31081419-22cc7a4c-a78c-11e7-9b3a-42d96b9fd9b5.png)

**Comment by eramirezprotec** [comment]
@RMastop. I would love to install that plugin, but it is not possible because of the Piwik version I am working with (3.0.4). And for the moment updating is not an option. Thank you for your helpful replies. There must be a way to expand the Campaigns report maintaining the evolution row option. But it is not as easy as one would think.

**Comment by mattab** [comment]
You may also get what you need with the Custom reports plugin: https://matomo.org/docs/custom-reports/
