### ISSUE TITLE
Manage Websites Blank

### ISSUE THREAD

**Issue by uxbod** [matomo-org/matomo#12142]
Have upgraded to the latest Piwik release:

Piwik version: 3.1.1
MySQL version: 5.5.5
PHP version: 7.1.9

but when I visit the manage websites page it shows zero sites even though 13 are available.  I have checked the NGINX error log on the server and it is showing:

2017/10/03 16:10:19 [alert] 7641#0: worker process 7676 exited on signal 6
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::basic_string

If I inspect the page I see an empty response from:

plugins/SitesManager/templates/sites-list/site-fields.html?cb=f16815f1c3671d2ccb5c11e010fdfe23 net::ERR_EMPTY_RESPONSE

**Comment by mattab** [comment]
Hi there,

It's hard to say, but maybe a bug in PHP or so? Could you try another PHP version maybe?

**Comment by mneudert** [comment]
I don't think this has anything to do with PHP. The error hints at `std::out_of_range` and that is some C++ stuff so probably something on the NGINX side.

Can you check if you have a module like `ngx_pagespeed` active? If so, could you check if deactivating it solves your problem?

**Comment by sgiehl** [comment]
@uxbod  any feedback on this

**Comment by uxbod** [comment]
Apologies have been on vacation.  Indeed ngx_pagespeed is installed but I have switched it off for the Piwik site :( Have even tried disabling it across all sites to no avail.

**Comment by mneudert** [comment]
That seems odd.

Can you give me some more details about your nginx version and plugins you are using? Like the output of `nginx -V` and a list of dynamic modules (if any).

**Comment by uxbod** [comment]
nginx version: nginx/1.11.8 
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013 
TLS SNI support enabled 
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --add-module=./ngx_pagespeed-1.11.33.4-beta --add-module=./ModSecurity-nginx --add-module=./ngx_cache_purge --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-mail --with-mail_ssl_module --with-file-aio --with-ipv6 --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic'

**Comment by sgiehl** [comment]
Closing as there hadn't been any further related reports in the last years. Assuming this doesn't seem to be a problem anymore.
