### ISSUE TITLE
Submit Matomo to Google Tag Manager Community Template Galleries

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12165]
To help people who use GTM (Google Tag  Manager) it was suggested that we should enroll to the Tag Manager program:

- https://developers.google.com/tag-manager/program/#enrollment-process
- https://docs.google.com/a/google.com/forms/d/e/1FAIpQLSep4QO3j5KtzRWZ-knzNOww0rl887HEIVnaCKEwFmW5ngBAuA/viewform

We'll need to answer questions such as:

> Please describe the tags that you would like to include as part of the Google Tag Manager Vendor Tag Template Program:

### Notes

We'd want to offer several kinds of tags/tracking such as:

- pageview
- event
- goal
- site search
- link

Some of these fields/parameters (and more) could be used/defined:

- "fields to set" ( = liste de set methods non catégorisées)
- domains
- cookies
- user ID
- custom variable
- custom dim
- ecommerce
+ options :
- cross domain
- download and outlink tracking
- content tracking
- multiple trackers

**Comment by tsteur** [comment]
FYI: Google Tag Manager has a new feature called "Galleries" see https://tagmanager.google.com/gallery/#/tags?page=1 It can be submitted through https://tagmanager.google.com/gallery/getting-started and there are docs available here: https://developers.google.com/tag-manager/templates/gallery

**Comment by bozerkins** [comment]
Has anyone started on this issue? I'm currently looking at the GTM - Matomo integration options for non-technical end users. GTM template could be very useful for such cases

**Comment by justinvelluppillai** [comment]
There is this: https://tagmanager.google.com/gallery/#/owners/trackify-info/templates/GoogleTagManager-WebTemplate-Matomo

**Comment by mattab** [comment]
@justinvelluppillai have we tested this one works as expected? i have not heard about it yet. looking at the code im wondering if it works as expected, for example with the way they set the JS URL which may not be flexible for the community&cloud https://github.com/trackify-info/GoogleTagManager-WebTemplate-Matomo/blob/main/template.tpl#L861-L866 ?

**Comment by justinvelluppillai** [comment]
@mattab I haven't tested it yet but we will be looking at it closely this quarter. Just noting for now here that this exists.

**Comment by mattab** [comment]
This was completed partially, see: https://tagmanager.google.com/gallery/#/owners/matomo-org/templates/google-tag-manager-matomo-template

Also: https://matomo.org/faq/new-to-piwik/how-do-i-use-matomo-analytics-within-gtm-google-tag-manager/

A GTM entry was created for Matomo Cloud users as unfortunately we couldn't do it in a generic way. 
On-premise template is covered in https://github.com/matomo-org/matomo/issues/18907
