### ISSUE TITLE
Date in page title not actual

### ISSUE THREAD

**Issue by wurzelmolch** [matomo-org/matomo#12162]
Hallo,

I have been playing with Piwik for a two weeks and it's really amazing! However I found bug: date in page title (browser tab) is not actual after changing date in Piwik. You can see it on attached screenshot: ![piwik - datum](https://user-images.githubusercontent.com/32622473/31321216-8f57cfcc-ac82-11e7-9db6-6eae56c75248.png)

**Comment by mattab** [comment]
Thanks for the report @wurzelmolch

**Comment by spacenate** [comment]
Hello @mattab, will you assign this issue to me? I would be happy to create a PR for it

**Comment by Findus23** [comment]
Hi @spacenate,

Great that you have a fix for this issue.
Unfortunately github doesn't allow assigning non-team-members to issue. 
So just commenting here should be enough.

Just in case you haven't seen it: We are participating in the Github/Digital Ocean Hacktoberfest.

If you register here https://hacktoberfest.digitalocean.com/ and create three more pull requests in October (on any Github Repository, even though we always appreciate help 😄 ) you'll get a T-Shirt.

**Comment by sgiehl** [comment]
@sunsplat  No. The PR for fixing this is still open

**Comment by spacenate** [comment]
Hey @sunsplat and @sgiehl  -- I did complete the most recent changes requested by @tsteur in #12222, so there should be nothing remaining (pending further comments). I added a comment to the PR to this effect, I apologize if my communication there was unclear.
