### ISSUE TITLE
Page Overylay Information boxes under menus and divs

### ISSUE THREAD

**Issue by dwightk2** [matomo-org/matomo#12168]
When viewing page overlay on websites using the wordpress template DIVI by elegantthemes.com , the information bubbles and boxes are beneath the menu items and page divs making them difficult or impossible to see.
![2017-10-11 15_05_01-drwalesnd com - october 2017 - web analytics reports - piwik](https://user-images.githubusercontent.com/32719664/31466778-a413a5ac-ae95-11e7-83e5-be4610ec17c7.png)
![2017-10-11 15_06_37-drwalesnd com - october 2017 - web analytics reports - piwik](https://user-images.githubusercontent.com/32719664/31466873-f7884f12-ae95-11e7-945a-2aed2474a851.png)

**Comment by mattab** [comment]
Hi @dwightk2 
What is the z-index value of the green menu? our bubbles are displayed below likely because of the z-index value

**Comment by dwightk2** [comment]
z-index: 9999. Can I set the z-index of the overlay to 99999 somewhere?

**Comment by mattab** [comment]
Yes @dwightk2 it is probably needed to update the 4 z-index you can find in https://github.com/piwik/piwik/blob/95c6665ac00d1836305c5606816c5d49a3ca8d63/plugins/Overlay/client/client.css#L40

Pull request welcome :+1:
