### ISSUE TITLE
GeoIP and Cookie not working

### ISSUE THREAD

**Issue by aski71** [matomo-org/matomo#12196]
Hi,
I've been using GeoIP location tracking for quite a while and it seemed to work quite well.
And I also excluded myself by using the browser cookie. This also worked quite well.

For a few days now I realised that it's not working correctly anymore.

a) My visits show up despite the browser cookie is active (it says so in the admin interface).
b) My visits show as coming from Hamburg, even though I'm in Munich.

I'm using the default for geo tracking: http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz

Can anyone help, please?

**Comment by sgiehl** [comment]
Sorry for the long delay. Meanwhile you can use GeoIP2 for a bit more accurate geo location. Also Maxmind itself publishes some data about the accuracy - and the lite version is not that accurate on city level. If you need more accurate data, you may need to purchase their database.

If you are still having trouble with one of those topics in latest release, maybe try to get some help on the forum. Or if you think it's a "real" bug, feel free to recreate an issue here.
