### ISSUE TITLE
Theme: @theme-color-header-background not working on login page

### ISSUE THREAD

**Issue by chrisschauer** [matomo-org/matomo#12202]
Hi,

i use the latest version 3.2.0 and wrote a own theme which changes the header-background color with
`@theme-color-header-background`

It's working perfect except the login page. 

Steps to reproduce:
 * Add/Activate a simple theme and overwrite the background color
 * The background works if the user is logged in
 * Log out
 * On the login-page the header has a different color (not the color defined in the theme)

Excpectation 
The defined color in the theme is also shown on login page

Thx

**Comment by Findus23** [comment]
I think this has been fixed by #13138 
Please reopen if the issue still occurs.
