### ISSUE TITLE
Bad filesystem detection (NFS)

### ISSUE THREAD

**Issue by odlan** [matomo-org/matomo#12217]
Piwik 3.2.0

This is the system where Piwik run
` df -T`

![shell](https://user-images.githubusercontent.com/10322746/31888588-0a2be2f8-b7fd-11e7-8c40-c2117b0820eb.JPG)

I have no NFS system, but Piwik think so

![piwik_nfs_error](https://user-images.githubusercontent.com/10322746/31888528-b8d99cb0-b7fc-11e7-822a-e542f26e2f80.JPG)

**Comment by Findus23** [comment]
Hi, 

Can you check the following:
- `df -T  -t nfs ` 
 It should return `df: no file systems processed` or something similar
- If you are allowing the `exec` function in PHP
- If you are allowing the `shell_exec` function in PHP

The only thing I can think of is that this check fails
https://github.com/piwik/piwik/blob/3.x-dev/core/Filesystem.php#L147
because the locale is not English and for whatever reason returns more than one line.

**Comment by odlan** [comment]
Hi
`user@diskstation:~# df -T -t nfs`
`df: no file systems processed`

` df -T -t nfs /volume1/web/piwik/tmp/sessions 2>&1`
`Filesystem     Type  1K-blocks      Used  Available Use% Mounted on`
`-              -    3732213600 857454592 2874759008  23% /volume1/web`

**Comment by Findus23** [comment]
> df -T -t nfs /volume1/web/piwik/tmp/sessions 2>&1
>Filesystem Type 1K-blocks Used Available Use% Mounted on
>\- \- 3732213600 857454592 2874759008 23% /volume1/web

That's odd. Can you try if any parameter causes df to not show that filesystem when filtering for nfs.

Which df are you using? The GNU one or something else?

What does `df --version` return

**Comment by odlan** [comment]
`df --version`
df (GNU coreutils) 8.24
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjörn Granlund, David MacKenzie, and Paul Eggert.

**Comment by odlan** [comment]
maybe [https://bugs.launchpad.net/ubuntu/+source/coreutils/+bug/1644038](url)

**Comment by robocoder** [comment]
Sounds like a bug with `df`.

What does `df -T` show?

**Comment by Seb35** [comment]
I also experience this issue: the directory `tmp` is a btrfs subvolume and it confuses `df`. The linked bug on Lauchpad is also [reported upstream](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=17676), it seems complicated.

Is it possible to add a supplementary condition in Matomo in the NFS check, something like `&& strpos( ' nfs ', implode("\n", $output) ) !== false` to work around this issue? I can prepare the patch.

**Comment by diosmosis** [comment]
Hi @Seb35, a change like that could work, and we'd welcome a pull request.

**Comment by diosmosis** [comment]
Fixed by  #17695
