### ISSUE TITLE
Add segment for event value

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#12213]
It would be very useful to have this segment.

For example you track eg the number of users that logged in during the day as an event. Then you want to have the possibility to filter out all events, where event value = 0 as sometimes you might track `action = loggedin, value = 0`, and sometimes `action = loggedin, value = 5`.

**Comment by mattab** [comment]
this may be done already in https://github.com/matomo-org/matomo/pull/13090

**Comment by diosmosis** [comment]
Already there: 
![image](https://user-images.githubusercontent.com/125140/46503687-666fba00-c7e0-11e8-989e-888ff3fb16bc.png)

Closing.
