### ISSUE TITLE
Exception on visitor profile popup

### ISSUE THREAD

**Issue by efedorov** [matomo-org/matomo#12215]
Exception is only reproduced on Roll-Up view.

"A fatal error occurred

The following error just broke Piwik (v3.2.0):

Key "1" does not exist as the array is empty.
in
.../plugins/Live/templates/_profileSummary.twig line 24"

**Comment by sgiehl** [comment]
Did you maybe remove a goal after some conversions were tracked?

**Comment by efedorov** [comment]
No, we did not change a goal. I just checked: the goals did not change more than a week, but the visitor was registered today.

**Comment by sgiehl** [comment]
Does the error always occur?

**Comment by efedorov** [comment]
Yes, the error appears every time. Restarting a web server and disabling plugins does not help.

**Comment by sgiehl** [comment]
@efedorov  I'm not sure how this problem occurs. Could you check if applying following changes fixes the problem for you: https://github.com/piwik/piwik/compare/fixgoalvp#diff-e968bd8d9abc8cf8161a4c09567ddc52

**Comment by sgiehl** [comment]
@efedorov  did you have time to check it? Would love to include a fix in next release if we can figure out the exact problem.

**Comment by mattab** [comment]
let's merge the fix if it's appropriate and could prevent an error in edge case? (as long as it doesn't hide a real issue...)
