### ISSUE TITLE
Bitcoin address issue 

### ISSUE THREAD

**Issue by cpoliticas** [matomo-org/matomo#12232]
Hi, I'm working with the Devcoin project. I wrote to you because I was looking at https://piwik.org/donate/ donation page and I see that your bitcoin donations are managed by a third party service like Coinbase.

The Devcoin project sends donations to several open source software (look here: https://en.bitcoin.it/wiki/Donation-accepting_organizations_and_projects#Open_source) and they have you listed in there, and they decided they want to fund more those OS Projects (please look here: https://bitcointalk.org/index.php?topic=233997.msg22703497#msg22703497), but some people argue in the bitcointalk forums (https://bitcointalk.org/index.php?topic=233997.msg22846637#msg22846637) that said addresses doesn't belong to those projects, and it's preferable for us that said addresses would be managed by someone inside the project team and not by services like the one is managing your funds.

Could you please direct me to an additional bitcoin address managed by the people in charge of your project? If you don't happen to have one, it would be possible for you or someone in there to set up a separate wallet?

I appreciate for your time reading this and thank you very much in advance for all your help!

**Comment by mattab** [comment]
Hi @cpoliticas 
Thanks for your interest. Currently have one wallet managed by coinbase. Is this not good enough, if so could you please tell us more why the coinbase solution is not suitable? as it is linked from our official page at: piwik.org/donate/ we guarantee that the bitcoin address listed there will be valid and come to the Piwik project. 

Looking forward to your feedback!

**Comment by cpoliticas** [comment]
Hello Mr. Aubrey.

The thing is we will send you devcoins and they must be extracted and sent with a devcoin wallet. The bitcoin address is just for receivers who do not have a devcoin wallet yet, this way we can send you devcoins now and then can pick them up later once you get a devcoin wallet. You will be able to see that devcoins are going to their address in a devcoin block explorer, but you will only be able to extract and send them after you import your private bitcoin key into a devcoin wallet. The problem with services like Coinbase or Bitpay, for mention only two of those, you can't have control of your wallet's private keys.

You wouldn't have to go through the private key transfer if you had a devcoin wallet, but since your project did not have one, we have to go through this roundabout procedure.

Thank you very much for your time reading this.

--------------------------------------------
On Mon, 11/6/17, Matthieu Aubry <notifications@github.com> wrote:

 Subject: Re: [piwik/piwik] Bitcoin address issue (#12232)
 To: "piwik/piwik" <piwik@noreply.github.com>
 Cc: "cpoliticas" <cpoliticas2005@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Monday, November 6, 2017, 9:02 PM
 
 Hi @cpoliticas
 
 Thanks for your interest. Currently have one wallet managed
 by coinbase. Is this not good enough, if so could you please
 tell us more why the coinbase solution is not suitable? as
 it is linked from our official page at: piwik.org/donate/ we
 guarantee that the bitcoin address listed there will be
 valid and come to the Piwik project.
 Looking forward to your feedback!
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by mattab** [comment]
Hi there, Sorry I'm not too familiar with this, and at this time we only have the coinbase wallet. Is it possible for you to send the donations there? Thanks,

**Comment by cpoliticas** [comment]
Unfortunately not, because if we send your devcoins there, you couldn't retrieve them, they would be lost, that's why the community was worried about.  

Another solution would be to download a devcoin wallet (http://devcoin.org/), and we will send your devcoins there, if you kindly do so. 

I'm so sorry we can give you another workable solution besides that.

**Comment by Findus23** [comment]
@cpoliticas 

I don't really understand what the devcoin wallet needs the private bitcoin key for. After all the use of a private key is to not share it with third parties (or other software).

**Comment by cpoliticas** [comment]
Mr. Winkler, I think there is a misunderstanding.

Neither me or the devcoin project need your project's private keys for anything.  

We can use a bitcoin address to deposit devcoins, similar to what happened with Bitcoin Cash, but our blockchain is much older.  

As the service you use manages the private keys of your wallet, we still can send them in there, but there's no way you can retrieve them later, that's our concern as a community, as you read in the above links in the bitcoin talk forums that I already provided.

If you don't want to receive the devcoins in that address, that's fine, that's why I suggested to download directly a devcoin wallet instead.

If you have further questions or you feel I wasn't clear enough (unfortunately that happens to me a lot these days), I would suggest to use our FAQ in here: http://devcoin.org/devcoin-faqs.html or contact us in the bitcoin talk forums.

I apologize if I gave you a wrong impression or upset you in any way.

Thank you very much for your time reading this.

Cheers


--------------------------------------------
On Thu, 11/9/17, Lukas Winkler <notifications@github.com> wrote:

 Subject: Re: [piwik/piwik] Bitcoin address issue (#12232)
 To: "piwik/piwik" <piwik@noreply.github.com>
 Cc: "cpoliticas" <cpoliticas2005@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Thursday, November 9, 2017, 3:50 AM
 
 @cpoliticas
 I don't really understand what the devcoin wallet
 needs the private bitcoin key for. After all the use of a
 private key is to not share it with third parties (or other
 software).
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by Findus23** [comment]
@cpoliticas, you are right, I completely misunderstood what you meant. (And sorry if it sounded a bit rude, I was on the phone and kept the message short)
I hope I am now correct:
A group of people is together mining (rebranded) bitcoins, which will then (minus a bit for the miners) democratically donated to creators and developers.
And the issue with coinbase isn’t a technical one, but rather because online wallets are against the spirit of cryptocurrencies (after all one wants to solely one ones money/private keys). 

So if the piwik core team creates a regular (offline and secure) bitcoin wallet and shares its address, they’ll be able to recieve Devcoins (in the form of „regular“ bitcoins that were mined by the Devcoin project) and of course also donations of regular piwik users who prefer transferring bitcoins. 

If I understand the idea correctly, I really like your project and hope it’ll get more traction as I haven’t heard of it before.

**Comment by cpoliticas** [comment]
Don't worry Mr. Winkler, I understand you were busy, there's no need to apologize, I felt that you were more concerned than anything else.

Well, I think you are correct with the whole idea.  But, just for a matter of clarification, please be aware that the project will donate devcoins to said address, and those can be retrieved with a devcoin wallet, however, you are correct, if a user wanted to send bitcoins to that address, you could manage it with any bitcoin wallet of your preference.

In the case of Coinbase, I understood it more as a technical issue than a philosophical one, because they are on their own right to support any cryptocurrency they want, and usually projects like ours don't have any say on that, unfortunately. If they supported devcoin, I think it wouldn't be a problem at all, but that's not the case.  Then, if we sent devcoins to those addresses, the most likely is those projects that we will donate, would never reach those coins. May be there is a philosophical problem after all. However, please note that not all online wallets behave like Coinbase or Bitpay. Blockchain.info for example, let their users to manage their own wallet's private keys.

Thank you very much for the best wishes to the devcoin project, we are now trying to push it a little bit harder and encouraging the community to donate even more to open source projects.

If you have further questions or would like to set up an address, in which we can deposit your devcoins, please feel free to contact us.

Thank you very much for your time and patience and I hope we can stay in contact.

Cheers

--------------------------------------------
On Thu, 11/9/17, Lukas Winkler <notifications@github.com> wrote:

 Subject: Re: [piwik/piwik] Bitcoin address issue (#12232)
 To: "piwik/piwik" <piwik@noreply.github.com>
 Cc: "cpoliticas" <cpoliticas2005@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Thursday, November 9, 2017, 12:20 PM
 
 @cpoliticas, you are
 right, I completely misunderstood what you meant. (And sorry
 if it sounded a bit rude, I was on the phone and kept the
 message short)
 
 I hope I am now correct:
 
 A group of people is together mining (rebranded) bitcoins,
 which will then (minus a bit for the miners) democratically
 donated to creators and developers.
 
 And the issue with coinbase isn’t a technical one, but
 rather because online wallets are against the spirit of
 cryptocurrencies (after all one wants to solely one ones
 money/private keys).
 So if the piwik core team creates a regular (offline and
 secure) bitcoin wallet and shares its address, they’ll be
 able to recieve Devcoins (in the form of „regular“
 bitcoins that were mined by the Devcoin project) and of
 course also donations of regular piwik users who prefer
 transferring bitcoins.
 If I understand the idea correctly, I really like your
 project and hope it’ll get more traction as I haven’t
 heard of it before.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by mattab** [comment]
Thank you for your interest and willingness to donate to open source!

As we're not currently setup with an address we can share here, we have a special request - would it be possible to donate any funds to MSF a really great not-for-profit with impact? They have crypto donation options here: https://msf.org.au/donate/crypto

Thank you :pray:
