### ISSUE TITLE
The modal "Segment '%s' not applied" should display when browser_archiving_disabled_enforce=1 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12253]
Regressed the feature introduced in https://github.com/piwik/piwik/issues/4569

## The following modal should display when the segment is set to "processed in real time" and `browser_archiving_disabled_enforce=1` 

![segment not applied](https://user-images.githubusercontent.com/466765/32470494-0226a432-c3bd-11e7-8a7d-4c117ad942f3.png)

Text reads: 

> Segment 'has site searched' not applied
> You are requesting data for the Custom Segment 'has site searched', this Piwik Enterprise Enterprise configuration currently prevents real time processing of reports for performance reasons. 
Your segmented analytics reports will be available later. We apologize for the inconvenience. 
> Alternatively you may change the setting in the config file (browser_archiving_disabled_enforce), or edit this Segment and choose 'segmented reports are pre-processed (faster, requires cron)'.

I think this was regressed with the new segment editor changes, as now the `&segment=` parameter is not found in the URL anymore, and the logic displaying this modal currently requires the `segment` to be in the URL.

## Steps

* Fix the regression (Maybe we should move this logic to JavaScript so we can use the segment value from the #Hash and call an API to know whether the modal should be displayed?)
* Add a UI test showing the modal so it won't regress in the future

**Comment by Stan-vw** [comment]
Closing because I understand that this modal doesn't exist anymore
