### ISSUE TITLE
FOSSA // piwik Sponsorship

### ISSUE THREAD

**Issue by cjcross** [matomo-org/matomo#12258]
Hello all, 

I'm Caleb - with FOSSA. We'd like to sponsor the piwik project by offering free use of our platform. 

FOSSA provides a popular license scanning service that helps open source projects prevent license violations with their dependencies. You may have already seen our badge on OSS projects like Webpack and Terraform -- this is an important factor for big companies that want to use, modify or contribute back to projects like piwik.

If there's enough interest among the community, we'd be happy to work with you all!

Thanks, 

Caleb

**Comment by sgiehl** [comment]
@cjcross I'm closing this issue now. If you are still interested to work with us, please get in touch with  support@matomo.org
