### ISSUE TITLE
Marketplace Widget - slow UI page loads when no internet connectivity

### ISSUE THREAD

**Issue by samurai926** [matomo-org/matomo#12277]
Hi Piwik team,
As the title suggest, when the marketplace widget is active in our commercial environment (which is not allowed to connect outward to the internet) we are experiencing major delays (often exceeding 300 seconds and timing out) loading Piwik web pages.  It doesn't seem to matter what pages be it dashboard, admin, plugins, reports etc and it only seems to be an issue after logging into the UI.

Some details from our config.ini.php:
```
[General]
session_save_handler = "dbtable"
enable_trusted_host_check = 0
proxy_client_headers[] = "HTTP_X_FORWARDED_FOR"
proxy_host_headers[] = "HTTP_X_FORWARDED_HOST"
salt = "mysalt"
trusted_hosts[] = "localhost:8088"
enable_plugin_upload = 1
enable_internet_features = 0
enable_auto_update = 0
```

When I disable the Marketplace widget, performance bounces back to normal.  We are running:

Piwik-3.2.0
Php-7.1.5
Apache-2.2.34
Linux-Redhat 6

The reason I need this plugin to be active is because it is the only place where we can upload a plugin zip file.  Please let me know if I can provide any further details.

Thanks
Jeffrey

**Comment by sgiehl** [comment]
Thanks for the report. The `enable_internet_features` feature is not yet finished. See #6324

**Comment by Findus23** [comment]
As #6324 is solved, this should also be solved.
