### ISSUE TITLE
[Design / UI] Request to improve UI.

### ISSUE THREAD

**Issue by ceiphr** [matomo-org/matomo#12285]
I love the service, but it could do a better job of following Google's material design. When I compare the UI of Google Analytics and PIWIK, IMO Google does a better job of applying their design language. I'd like to request that the side nav, graphs, icons, and search bar be updated to look similar to what I've found [here](https://pixinvent.com/materialize-material-design-admin-template/html/collapsible-menu/). Thanks for reading my request.

**Comment by fdellwing** [comment]
May contain own opinion: Oh god, please no!

**Comment by Findus23** [comment]
As design is always a bit subjective it should be possible to develop an alternative (more material design) theme (see https://developer.piwik.org/guides/theming) and publish it on the marketplace so everyone can choose.

**Comment by tsteur** [comment]
Can you maybe suggest some concrete improvements ideally with screenshots of what it should look like? This will make it easier to improve it. Otherwise we might need to close it.

**Comment by ceiphr** [comment]
Hi,
I forgot about this. I'll definitely give theming a shot like @Findus23 said and I do understand what @fdellwing is getting at. The example I gave was a bit over kill, I meant a UI similar to Google Analytics. For now, I'll close this but thank you all for your input.
