### ISSUE TITLE
Twig Filesystem Warning

### ISSUE THREAD

**Issue by mrmonday** [matomo-org/matomo#12280]
When viewing:

https://siteurl/index.php?module=CoreHome&action=index&idSite=23&period=range&date=previous7&updated=1#?idSite=23&period=range&date=previous7&category=Dashboard_Dashboard&subcategory=1

I get the warning message:

```
WARNING: /var/www/siteurl/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(35): Warning - realpath(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/var/www/siteurl) - Piwik 3.2.0
```

Looking at where `Twig_Loader_Filesystem` is used, the `$rootPath` parameter is not passed to the constructor, so it falls back to the current working directory (which happens to be outside of the basedir for the PHP installation).

PHP Version: 7.0.19-1
Piwik Version: 3.2.0

I can provide more information if needed.

**Comment by sgiehl** [comment]
could you check if this changes fixes your problem:
https://github.com/piwik/piwik/compare/twigroot

**Comment by mattab** [comment]
Hi @mrmonday have you had a chance to test the patch from https://github.com/piwik/piwik/compare/twigroot and does it help remove the warning?

**Comment by mrmonday** [comment]
Unfortunately this issue happens sporadically (it only happened for certain sites/date ranges), and I cannot currently reproduce it.

If it happens again, I will try the patch.

**Comment by mrmonday** [comment]
This issue releated after upgrading to 3.3.0. Applying the patch appears to have resolved the issue.
