### ISSUE TITLE
Is the Transitions API module broken?

### ISSUE THREAD

**Issue by derwaldgeist** [matomo-org/matomo#12305]
I am scratching my head how to get the Transitions API module working as documented. My primary use-case would be to get all links that have been visited after a specific event was fired.

First, I tried Transitions.getTransitionsForAction and expected that I could use this for "event" actions. Unfortunately, there was no real documentation what the actionType and actionNames should be, and the database schema description I found on the web did not answer my question either. So I looked into the source code to find that quite obviously only URLs and titles are supported at the moment. First bummer.

Then I tried getTransitionsForUrl and getTransitionsForTitle. The URL seemed to work (at least in the demo provided in the docs), but it was unclear to me how the URL should look like and what parts of the URL are really relevant. Also, I noticed that no data was returned as soon as I tried to use segmentation.

My next try was getTransitionsForTitle. This yielded results, but they were exactly the same no matter what pageTitle I handed over. I could even provide an arbitrary string and got the very same result back. Segmentation didn't work either.

Is there any documentation about how the Transition package can be used to get "useful" reports back, and is there any change to get the pages the user visited after a specific event fired or at least after visiting a page with a certain title?!

**Comment by utrautmann** [comment]
For instance when segmentation is for PageURL or ActionURL then no results returned for transitions.
If the segmentation is for campaigns or visitor properties instead, data is returned.

However, the [documentation ](https://developer.matomo.org/api-reference/reporting-api#Transitions) doesn't mention this.

Works: 
https://demo.matomo.org/index.php?segment=visitorType==returning&date=yesterday&actionType=url&actionName=https://divezone.net/jobs&expanded=1&format=JSON&module=API&method=Transitions.getTransitionsForAction&filter_limit=-1&idSite=62&period=day

No data:
https://demo.matomo.org/index.php?segment=actionURL==https%3A%2F%2Fdivezone.net%2Fjobs&date=yesterday&actionType=url&actionName=https://divezone.net/jobs&expanded=1&format=JSON&module=API&method=Transitions.getTransitionsForAction&filter_limit=-1&idSite=62&period=day

See JSON Response in this case:
Segment 'actionURL' is not a supported segment.

**Comment by sgiehl** [comment]
@utrautmann the name of the segment is `actionUrl`. e.g. https://demo.matomo.org/index.php?segment=actionUrl==https%3A%2F%2Fdivezone.net%2Fjobs&date=yesterday&actionType=url&actionName=https://divezone.net/jobs&expanded=1&format=JSON&module=API&method=Transitions.getTransitionsForAction&filter_limit=-1&idSite=62&period=day

**Comment by utrautmann** [comment]
@sgiehl Thank you for clarification
