### ISSUE TITLE
Move all icons next to text to the left

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#12301]
![image](https://user-images.githubusercontent.com/273120/33243454-76612d52-d34b-11e7-9e6b-37d7f9cda1dd.png)

Sometimes icons in Piwik are on the right and sometimes on the left. I reckon it may be actually more useful, better skimmable, and looks better on the left (see picture). Be great to start maybe with the toolbar icons, then apply this also in order places where needed. 

Ideally, we also check the Android & iOS mobile app to have a consistent look / feel throughout Piwik. I'll create an issue.

**Comment by tsteur** [comment]
Moving this to Piwik 4, be nice to work on it earlier as it makes UI nicer. cc @mattab

**Comment by sgiehl** [comment]
@tsteur do you know any icons that still need to be realigned? Roughly looked through the ui, but couldn't find any...

**Comment by tsteur** [comment]
Looks good 👍
