### ISSUE TITLE
it's this supports stat on mobile?

### ISSUE THREAD

**Issue by meyer-net** [matomo-org/matomo#12302]
like title, some times we should stat some flow from mobile app, and stat the errors how to raise on, like the countly on github. i'dont know how to compare it, i can't find it.

**Comment by meyer-net** [comment]
how can i know the app client was crash?which platform , ios or android and else? why crash? this is the else data, which i care...

**Comment by tsteur** [comment]
Sorry but I don't quite understand what you mean. Could you describe it again?

**Comment by sgiehl** [comment]
Closing for now. @meyer-net If you still have any issues, feel free to create a new issue with a more detailed problem description
