### ISSUE TITLE
Piwik 3.2.1 Right Sidebar Menu issue

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#12334]
Hi, after automated update to 3.2.1 from 3.2.0 right sidebar in Chrome browser (both desktop and mobile) **does not show*** the usual admin items as before (e.g. in 3.2.0). Clearing browser's cache and/or cookies and signing in again does not help.

Please check screenshots:

3.2.0
![piwik 3 2 0 right sidebar](https://user-images.githubusercontent.com/5383059/33651530-73f35924-da66-11e7-8ea6-59d5063fb5f2.png)

3.2.1
![piwik 3 2 1 right sidebar](https://user-images.githubusercontent.com/5383059/33651546-8d0b4d18-da66-11e7-834b-930a7781522e.png)

After checking on desktop, I see that items are still there actually, just not visible until mouse hover (and even then hard to see):

![piwik 3 2 1 right sidebar accessibility issue](https://user-images.githubusercontent.com/5383059/33651676-023290f6-da67-11e7-9ff6-2d369278a2e0.png)

**Comment by sgiehl** [comment]
That seems to be a regression of https://github.com/piwik/piwik/commit/80214a868e174808ff3b34640add33bd5d4f089a#diff-afe8dd6f32f2190b26e768c6d588d25dR50

**Comment by dev-101** [comment]
Thanks!
Correct, that change in css overlooked this menu :)

**Comment by sgiehl** [comment]
Note: When fixing that regression we should add a new screenshot test for those mobile menus to avoid new regressions in the future
