### ISSUE TITLE
Page title with slash fails at PDF report

### ISSUE THREAD

**Issue by mihadd** [matomo-org/matomo#12331]
Hey Piwik-Team,

some of our CMS editors use slashes at main title which is also used for page title i.e. "Cultural programme in winter term 2017/18". As you can see at screenshot the report actions -> pages titles piwik interprets the title as path and shows this page as two entries. 

![piwik_page_title_with_slash](https://user-images.githubusercontent.com/25606657/33595629-16d98b14-d999-11e7-8190-0a725cf47303.png)

But the PDF report rendering fails with these titles and only one letter will be left.

![piwik_page_title_with_slash_pdf_report](https://user-images.githubusercontent.com/25606657/33596189-3101966a-d99b-11e7-8042-1949112954b9.png)

Can you correct this bug please. Thanks

Best regards.
Mike

Piwik-Version: 3.2.0
MySQL-Version: 5.5.58
PHP-Version: 5.6.30-0+deb8u1

**Comment by sgiehl** [comment]
To avoid the breaking of such titles you can change the config value for `action_title_category_delimiter`

Regarding the PDF failure. Are you still able to reproduce that with the latest version?

**Comment by mihadd** [comment]
Ah ok! Thank you for this hint. But as I can see at [Matomo FAQ](https://matomo.org/faq/how-to/faq_62/) there is only one parameter for URL and title splitting right?! So if i set the parameter to a character that is not used in our site titles, then i see all the pages at the same level under Actions -> Pages?

PDF failure: Yes i can reproduce this failure with latest version.
Piwik-Version: 3.3.0
MySQL-Version: 5.5.59
PHP-Version: 5.6.33-0+deb8u1

**Comment by sgiehl** [comment]
No. There is `action_title_category_delimiter` and `action_url_category_delimiter`. If you do not want a splitting of titles at all, set `action_title_category_delimiter` to a char that isn't used in your titles

**Comment by mihadd** [comment]
OK. I set `action_title_category_delimiter = ##` and it works fine. Thank you.
