### ISSUE TITLE
Integrity check in Piwik-3.2.1 shows essential core directories/files as 'deletable'...

### ISSUE THREAD

**Issue by mygithuber** [matomo-org/matomo#12344]
Pls refer to:
https://forum.piwik.org/t/unerwartete-verzeichnisse-bitte-loschen/25982 

After updating Piwik-3.1.1 >> 3.2.1 system integrity check shows several essential core directories and files as 'deletable'. Further investigation shows the imperative need of marked files for Piwik functionality, so they must not be deleted!
There must be something wrong with the integrity check and resulting recommendations.

Test system:
Windows 7prof (64)
XAMPP for Windows 5.6.21
Piwik-Version: 3.2.1
MySQL-Version: 5.5.5
PHP-Version: 5.6.21

**Comment by fdellwing** [comment]
This should have been fixxed with 2ba9409967d8716484c12aa23ad81c6097e62695

**Comment by mattab** [comment]
Thanks for the report @mygithuber  - is there any chance we could get some temporary access to your server (ideally SSH) to troubleshoot this further?

Does anyone else experience the issue?

**Comment by mygithuber** [comment]
Access to Test system:
Windows 7prof (64)
XAMPP for Windows 5.6.21
Piwik-Version: 3.2.1
MySQL-Version: 5.5.5
PHP-Version: 5.6.21

would be possible by TeamViewer only.

**Comment by fdellwing** [comment]
#12362 suggest that it is a problem with directory seperator implemented in 2ba9409967d8716484c12aa23ad81c6097e62695

There could be need for a special case for windows systems

**Comment by sgiehl** [comment]
@mygithuber @fdellwing  could you check if the problem is fixed if you change this: https://github.com/piwik/piwik/compare/integrityfix

**Comment by mygithuber** [comment]
Sorry, : https://github.com/piwik/piwik/compare/integrityfix didn't fix the issue, it extends deletable files, it seems to be all Piwik files listed...

`Es wurden unerwartete Dateien in deiner Piwik-Installation gefunden.
--> Bitte lösche diese Dateien, um Fehler zu vermeiden. <--

Zu löschende Datei: /CHANGELOG.md
Zu löschende Datei: /CONTRIBUTING.md
Zu löschende Datei: /LEGALNOTICE
Zu löschende Datei: /LICENSE
Zu löschende Datei: /PRIVACY.md
Zu löschende Datei: /PULL_REQUEST_TEMPLATE
Zu löschende Datei: /README.md
Zu löschende Datei: /SECURITY.md
Zu löschende Datei: /bower.json
Zu löschende Datei: /composer.json
Zu löschende Datei: /composer.lock
...
Zu löschende Datei: /.phpstorm.meta.php
Zu löschende Datei: /libs/bower_components/materialize/.npmignore
Zu löschende Datei: /vendor/php-di/php-di/.phpstorm.meta.php
Zu löschende Datei: /vendor/twig/twig/.php_cs.dist


Um alle diese Dateien auf einmal zu löschen, kannst du folgenden Befehl ausführen:
del "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
...
del "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
del "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""


Die nachfolgenden Fehler könnten durch einen teilweise oder gänzlich fehlgeschlagenen Upload der Piwik-Dateien entstanden sein.
--> Versuche die Piwik-Dateien im BINARY-Modus neu hochzuladen. <--

Unterschiedliche Dateigröße: D:\xampp\htdocs\script\piwik/core/FileIntegrity.php (erwartete Größe: 16101, gefunden: 16136)`

**Comment by sgiehl** [comment]
@mygithuber ah sorry. forgot to change that in both places. please check the update branch.

**Comment by mygithuber** [comment]
Ahh, ohh, it works for me on this systems:

**Apache-Windows7prof/XAMPP-Testsystem:**
Piwik-Version: 3.2.1
MySQL-Version: 5.5.5
PHP-Version: 5.6.21 

**Apache-Linux/HostEurope:**
Piwik-Version: 3.2.1
MySQL-Version: 5.6.37
PHP-Version: 5.6.32-he.0 

I did change both provided code rows, only individualized files had been shown (as expected!):

`Es wurden unerwartete Dateien in deiner Piwik-Installation gefunden.
--> Bitte lösche diese Dateien, um Fehler zu vermeiden. <--

Zu löschende Datei: piwik.js.gz
Zu löschende Datei: core/FileIntegrity.ph_org
Zu löschende Datei: plugins/CoreAdminHome/templates/optOut_neu321.twig
Zu löschende Datei: plugins/CoreAdminHome/templates/optOut_org321.twig


Um alle diese Dateien auf einmal zu löschen, kannst du folgenden Befehl ausführen:
rm "/is/htdocs/wp---/www/script/piwik/piwik.js.gz" "/is/htdocs/wp---/www/script/piwik/core/FileIntegrity.ph_org" "/is/htdocs/wp---/www/script/piwik/plugins/CoreAdminHome/templates/optOut_neu321.twig" "/is/htdocs/wp---/www/script/piwik/plugins/CoreAdminHome/templates/optOut_org321.twig"


Die nachfolgenden Fehler könnten durch einen teilweise oder gänzlich fehlgeschlagenen Upload der Piwik-Dateien entstanden sein.
--> Versuche die Piwik-Dateien im BINARY-Modus neu hochzuladen. <--

Unterschiedliche Dateigröße: /is/htdocs/wp---/www/script/piwik/core/FileIntegrity.php (erwartete Größe: 16101, gefunden: 16170)
Unterschiedliche Dateigröße: /is/htdocs/wp---/www/script/piwik/plugins/CoreAdminHome/templates/optOut.twig (erwartete Größe: 3380, gefunden: 4218)`

**Comment by sgiehl** [comment]
> I did change both provided code rows, only individualized files had been shown (as expected!). Modified FileIntegrity.php has NOT been marked.

Actually it is marked:
```Unterschiedliche Dateigröße: /is/htdocs/wp---/www/script/piwik/core/FileIntegrity.php (erwartete Größe: 16101, gefunden: 16170)```

But thanks for confirming it works. Should then be fixed with next release :+1:

**Comment by mygithuber** [comment]
You are right, sorry, my fault...

**Comment by TheChroniX** [comment]
Hi all,

i have the same issue on my system, so if more information should be required, do not hesitate to ask:

System:

Windows  Server 2012 R2 Standard
IIS 10.0 Express 10.0.1736
MySQL Server 5.7
PHP 7.0.12
Piwik 3.2.1

Check results:

Der Datei-Integritätscheck ist fehlgeschlagen und hat ein paar Fehler gemeldet. Du solltest die Probleme beheben und diese Seite neuladen, bis sie keine Fehler mehr anzeigt.

Es wurden unerwartete Verzeichnisse in deiner Piwik-Installation gefunden.
--> Bitte lösche diese Verzeichnisse, um Fehler zu vermeiden. <--

Zu löschendes Verzeichnis: /config
Zu löschendes Verzeichnis: /core
Zu löschendes Verzeichnis: /libs
Zu löschendes Verzeichnis: /misc
Zu löschendes Verzeichnis: /plugins
Zu löschendes Verzeichnis: /tmp
Zu löschendes Verzeichnis: /vendor


Um alle diese Verzeichnisse auf einmal zu löschen, kannst du folgenden Befehl ausführen:
rmdir /s /q       


Es wurden unerwartete Dateien in deiner Piwik-Installation gefunden.
--> Bitte lösche diese Dateien, um Fehler zu vermeiden. <--

Zu löschende Datei: /CHANGELOG.md
Zu löschende Datei: /CONTRIBUTING.md
Zu löschende Datei: /LEGALNOTICE
Zu löschende Datei: /LICENSE
Zu löschende Datei: /PRIVACY.md
Zu löschende Datei: /PULL_REQUEST_TEMPLATE
Zu löschende Datei: /README.md
Zu löschende Datei: /SECURITY.md
Zu löschende Datei: /bower.json
Zu löschende Datei: /composer.json
Zu löschende Datei: /composer.lock
Zu löschende Datei: /console
Zu löschende Datei: /favicon.ico
Zu löschende Datei: /index.php
Zu löschende Datei: /piwik.js
Zu löschende Datei: /piwik.php
Zu löschende Datei: /robots.txt
Zu löschende Datei: /js/LICENSE.txt
Zu löschende Datei: /js/README.md
Zu löschende Datei: /js/index.php
Zu löschende Datei: /js/piwik.js
Zu löschende Datei: /js/piwik.min.js
Zu löschende Datei: /js/tracker.php
Zu löschende Datei: /lang/README.md
Zu löschende Datei: /lang/am.json
Zu löschende Datei: /lang/ar.json
Zu löschende Datei: /lang/be.json
Zu löschende Datei: /lang/bg.json
Zu löschende Datei: /lang/bn.json
Zu löschende Datei: /lang/bs.json
Zu löschende Datei: /lang/ca.json
Zu löschende Datei: /lang/cs.json
Zu löschende Datei: /lang/cy.json
Zu löschende Datei: /lang/da.json
Zu löschende Datei: /lang/de.json
Zu löschende Datei: /lang/dev.json
Zu löschende Datei: /lang/el.json
Zu löschende Datei: /lang/en.json
Zu löschende Datei: /lang/es.json
Zu löschende Datei: /lang/et.json
Zu löschende Datei: /lang/eu.json
Zu löschende Datei: /lang/fa.json
Zu löschende Datei: /lang/fi.json
Zu löschende Datei: /lang/fr.json
Zu löschende Datei: /lang/gl.json
Zu löschende Datei: /lang/he.json
Zu löschende Datei: /lang/hi.json
Zu löschende Datei: /lang/hr.json
Zu löschende Datei: /lang/hu.json
Zu löschende Datei: /lang/id.json
Zu löschende Datei: /lang/is.json
Zu löschende Datei: /lang/it.json
Zu löschende Datei: /lang/ja.json
Zu löschende Datei: /lang/ka.json
Zu löschende Datei: /lang/ko.json
Zu löschende Datei: /lang/lt.json
Zu löschende Datei: /lang/lv.json
Zu löschende Datei: /lang/nb.json
Zu löschende Datei: /lang/nl.json
Zu löschende Datei: /lang/nn.json
Zu löschende Datei: /lang/pl.json
Zu löschende Datei: /lang/pt-br.json
Zu löschende Datei: /lang/pt.json
Zu löschende Datei: /lang/ro.json
Zu löschende Datei: /lang/ru.json
Zu löschende Datei: /lang/sk.json
Zu löschende Datei: /lang/sl.json
Zu löschende Datei: /lang/sq.json
Zu löschende Datei: /lang/sr.json
Zu löschende Datei: /lang/sv.json
Zu löschende Datei: /lang/ta.json
Zu löschende Datei: /lang/te.json
Zu löschende Datei: /lang/th.json
Zu löschende Datei: /lang/tl.json
Zu löschende Datei: /lang/tr.json
Zu löschende Datei: /lang/uk.json
Zu löschende Datei: /lang/vi.json
Zu löschende Datei: /lang/zh-cn.json
Zu löschende Datei: /lang/zh-tw.json
Zu löschende Datei: /tests/README.md


Um alle diese Dateien auf einmal zu löschen, kannst du folgenden Befehl ausführen:
del "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
del "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""

**Comment by Findus23** [comment]
@TheChroniX have you tired to apply this path?
https://github.com/piwik/piwik/pull/12383/files
Dies it fix the issue for you?

**Comment by TheChroniX** [comment]
Yes, if i apply the change according to the link (https://github.com/piwik/piwik/compare/integrityfix) it works, of course now reporting the modified "FileIntegrity.php":

Die nachfolgenden Fehler könnten durch einen teilweise oder gänzlich fehlgeschlagenen Upload der Piwik-Dateien entstanden sein.
--> Versuche die Piwik-Dateien im BINARY-Modus neu hochzuladen. <--

Unterschiedliche Dateigröße: C:\PHP\piwik\piwik/core/FileIntegrity.php (erwartete Größe: 16101, gefunden: 16073)

Sorry for forgetting to add this essential info!

**Comment by Findus23** [comment]
@TheChroniX 
So I guess when it will get merged for the 3.3.0 release this issue will be fixed for all Windows users.
