### ISSUE TITLE
Multiple conditions for goal with AND/OR seperation

### ISSUE THREAD

**Issue by mikhailnov** [matomo-org/matomo#12346]
I would like to set the goal to be reached only when multiple conditions are met, and I'd like to set if the goal will be reached if all of them (logical AND) or any of them (logical AND) are reached.
And it would be great to be able to set AND and OR for different events.
Yandex.Metrica has something like this.
![deepinscreenshot_select-area_20171210214958](https://user-images.githubusercontent.com/15802528/33808240-15e3f8d4-ddf4-11e7-8a8c-0a7f5cee1259.png)

I've seen https://github.com/piwik/piwik/issues/10791 but am not sure, is this a duplicate?

**Comment by mattab** [comment]
Thanks for the report @mikhailnov 

the use case for `AND` is clear and covered in: https://github.com/matomo-org/matomo/issues/10791
We probably won't implement the `OR` operator as it should be good enough to use the AND operator only (the ~ 10 people i heard from who need this, always needed AND operator).
