### ISSUE TITLE
Incorrect country flags shown on embeddable Static Image Graphs for apiAction=getCountry

### ISSUE THREAD

**Issue by digihiveinc** [matomo-org/matomo#12353]
Hello

When generating static images to embed (e.g.: index.php?module=API&method=ImageGraph.get&apiModule=UserCountry&apiAction=getCountry&token_auth=anonymous&graphType=horizontalBar&period=month&date=today&aliasedGraph=1&segment=countryCode!=RU;countryCode!=UZ;countryCode!=UA;countryCode!=LK&fontSize=14&textColor=333333&backgroundColor=ffffff&gridColor=e7ecf1&colors=e1e1e1&width=513&height=137 )

and using segmentation to exclude certain countries the flags assignment sometimes is all messed up:

here are few screenshots:
http://take.ms/G3Mzm
http://take.ms/yDBF0

It ussually appears to reuse the 1st country on the list for the following country(ies)

**Comment by sgiehl** [comment]
That seems to work with latest version. See for example: https://demo.matomo.org/index.php?module=API&method=ImageGraph.get&apiModule=UserCountry&apiAction=getCountry&token_auth=anonymous&graphType=horizontalBar&period=month&date=today&aliasedGraph=1&segment=countryCode!=RU;countryCode!=UZ;countryCode!=UA;countryCode!=LK&fontSize=14&textColor=333333&backgroundColor=ffffff&gridColor=e7ecf1&colors=e1e1e1&width=513&height=137&idSite=7

**Comment by msphn** [comment]
I can reproduce this issue on the current version I've installed yesterday. System thinks I'm from the USA but I'm from Germany.

**Comment by Findus23** [comment]
@msphn Are you sure the wrong flag is shown or is the Geolocation incorrect (So is it also shown incorrectly in the countrymap?
If the latter, maybe try to check the GeoIP settings.

**Comment by msphn** [comment]
It is. I just switched from default to geoip and had the same issue. The geoinformation is just incorrect as you said. It's not an issue of matomo.
