### ISSUE TITLE
Rename metrics that start with "Total" and remove the word Total

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12359]
For compability with Custom Reports, which prepends the word "Total" to metrics in some cases, we would like to remove the word "Total" that is sometimes prepended to our metric names. Here are the metrics that have the word Total and that we should rename (several plugins are affected).

![total metrics](https://user-images.githubusercontent.com/466765/34019005-8210c0f0-e191-11e7-87fe-91de4ea218da.png)

### Notes / exceptions

* `Total value` should be renamed to `Event value`
* Also rename `Maximum value` to `Maximum Event value`
* Also rename `Minimum value` to `Minimum Event value`

**Comment by tsteur** [comment]
The media analytics metrics are renamed (no new version released yet)

**Comment by mattab** [comment]
Fixed in https://github.com/matomo-org/matomo/pull/12460
