### ISSUE TITLE
Why is this counted as two visitors?

### ISSUE THREAD

**Issue by whiteonion** [matomo-org/matomo#12367]
I've got two absolutelly same visitors, that piwik counts as two, but, I think it's one, with two visits.

Any ideas how to fix this, or is it a bug?

note that I have changed the IP for privacy reasons, but it's the same IP

<img width="1172" alt="screen shot 2017-12-17 at 4 15 48 pm" src="https://user-images.githubusercontent.com/34626294/34080986-f085e25c-e346-11e7-9cc6-1c43dea0d6c8.png">
<img width="1182" alt="screen shot 2017-12-17 at 4 15 58 pm" src="https://user-images.githubusercontent.com/34626294/34080987-f0a2d2f4-e346-11e7-8e90-6390dde38eec.png">

**Comment by sgiehl** [comment]
did you maybe change the config value for `create_new_visit_when_website_referrer_changes`? If it's set to `1`, it would be counted as new visit as the referrer changed.
