### ISSUE TITLE
Browser widget bug with pagination

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#12369]
I found a problem with the browser widget:

We have 11 browsers with 51 different versions.

Way to break it:

1. Click on "browser version" to get the 51 rows.
2. Click on "next page".
3. Click on "browser" to get the 11 rows. -> Widget still says it has 51 rows!
4. Click on "next page" -> You get an "no data available", because you have only 2 sites of rows
5. You need to reload the site (strg+f5) to get you widget data back.

**Comment by sgiehl** [comment]
thanks for the report. I'm able to reproduce it.
