### ISSUE TITLE
Visitor Profile "First visit" does not always show the very first visit

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12373]
As reported in https://github.com/piwik/piwik/issues/11996#issuecomment-352869747 by @blynch11p 

>  I've been tinkering with v3.2 and I have many users that top 100 visits. The Visit count is starting at #100 (not a big deal, really) but the secondary issue is that the "First Visit" date is (in my case) whatever the date for Visit #91 is in the Visitor Profile window (ie: the date for the oldest of the 10 visits that load initially. This does not update when I click 'Load more visits'). So if the user visits a site every day, visit #91 / First Visit is only 10 days back, rather than >100 days or > 3 years or whatever. I believe in prior Piwik versions (I'm coming from 3.0.4) "First Visit" only ever showed the text Visit #100 for these use cases, but now "First Visit" is less accurate.

## Current behavior 

Currently "First visit" will only be the 10th oldest visit, but there could have been 50 visits or more. 

## Expected behavior

* The `First visit` panel in the Visitor Profile should refer the very first visit of the user. 
  * ideally it's possible to query this very first visit very quickly in Mysql,
   * but if not we can always use the first visit in the `live_visitor_profile_max_visits_to_aggregate` limit (100 by default) which would restore the previous behavior before we recently regressed

**Comment by sgiehl** [comment]
Showing the very first visit would be possible, but I won't change it that way, as it would make the visitor profile inconsistent. All data would be calculated based in the last 100 visits. Why should the first visit should show something different. But I will add a small text in the beginning of the summary showing a notice that the profile shows only X of Y visits (if there are more visits than defined in config)

**Comment by blynch11p** [comment]
Matt, thanks for creating the issue ticket.

To put a screenshot to it, the info on the left (First Visit) is my primary concern.  Since First Visit is not actually the FIRST, but the 10th most recent.  For this user, their true First Visit was March 8, 2017, not November 22, 2017.

The info on the right (showing Visit 100, rather than some number greater than 100), while not entirely correct, isn't my concern here.

![screenshot from 2017-12-20 12-13-29](https://user-images.githubusercontent.com/21367387/34207555-fcc8613e-e558-11e7-8e7e-fcb0bd45aa05.png)

**Comment by mattab** [comment]
>  All data would be calculated based in the last 100 visits. Why should the first visit should show something different. 

@sgiehl in that case we want to implement a "First" visit reporting, as in, showing the very first visit. This is because how user found the website in the first place is very valuable info, and often there is only a single channel used during 100+ visits. The first visit is where the only referrer may be found...  Also, knowing the time of the first visit is interesting and the info only found in this visit.  
so ideally we still write "First visit" and load the very first visit summary there.

**Comment by mattab** [comment]
This great little improvement has been made! :tada:
