### ISSUE TITLE
Not able login

### ISSUE THREAD

**Issue by amoljore751986** [matomo-org/matomo#12397]
Hi, I am trying to configure the PIWIK for one of our Websites. 

Point 1:
When I am trying to access it using http://<piwik-sever-ip>/piwik, then it is working fine and I am able to login and see the dashboards etc

Point 2:
But when I am trying to access it from APACHE2 server using https://www.radixhealth.org/piwik, then it is not allowing me to login.

Here is my server config in config.ini.php file
[database]
host = "127.0.0.1"
username = "root"
password = "mypassword"
dbname = "piwik_db"
tables_prefix = "piwik_"

[General]
force_ssl=1
assume_secure_protocol = 1
proxy_uri_header = 1
salt = "1934b4cd41f49bcfb15d76fbb4"
trusted_hosts[] = "11.111.111.123"
trusted_hosts[] = "www.mydomain.org"
cors_domains[] = *
proxy_client_headers[] = HTTP_CLIENT_IP
proxy_client_headers[] = HTTP_X_FORWARDED_FOR

**Comment by fdellwing** [comment]
Not able to look at it, because it throws an 404.

**Comment by sgiehl** [comment]
@amoljore751986 Hope you managed to solve your problem. If not maybe try to get some help on our fourm.
