### ISSUE TITLE
New dimensions "Website ID" and "Website name"

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12409]
It would be useful to introduce two new dimensions:

1. Website ID  (or measurable)
2. Website name (or measurable)

Then [Custom Reports](http://piwik.org/docs/custom-reports/) could leverage these new dimensions and allow creating custom reports on [Roll-Ups](https://piwik.org/docs/roll-up-reporting/) broken down by Website id or website name.

For these dimensions I reckon we don't need to create new segments. Although having segments for website id/name could be possibly useful to segment a roll-up and filter out some sites, it hasn't been requested yet. 

The dimensions should be available when used in the "Top level" of the report (ie. the first dimension added), and also when the dimension eg. "Website name" is added below, for example "Country > Product sold > Website name" should list, for any given country and product comparison, all of the website that sold this product.

### Testing

To check this new feature works as expected, we should create a Custom Report on a Roll-up, where the custom report includes the Website name and/or Website ID. The generated custom report should let us drill down into any particular website.

**Comment by diosmosis** [comment]
@mattab couple questions:

1. Is this the kind of report you're expecting?

![image](https://user-images.githubusercontent.com/125140/37986612-c3ce4c28-31b0-11e8-82a2-2858404c9cab.png)

2. Is there value in having both website ID & website name dimensions? If yes, for website ID, should the report display the ID or the website name? If both dimensions display website name, then what's the use of having both of them?

3. Would it be better to just have the website name as the label or would `Website Name [ID = 3]` be more useful? I think the latter would be more useful, but maybe it's just clutter...

**Comment by diosmosis** [comment]
4. Any other places dimension metadata is used? Will need to test those places too.

**Comment by mattab** [comment]
1) yes
2) yes, displaying website ID only sounds good
3) only website name
4) not that I know, but tests should tell us otherwise, hopefully

**Comment by diosmosis** [comment]
@mattab FYI, there is already an IdSite dimension that uses the site name column. Do you have a problem w/ using that instead of two dimensions? https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/CoreHome/Columns/IdSite.php

Note: this is what is being used in the screenshot (I had to modify it a bit first).

**Comment by mattab** [comment]
it is needed to have the website ID as its own dimension, as well as the website name as its own

**Comment by diosmosis** [comment]
@mattab could you elaborate on why? I don't have a problem w/ trying to do this, but I feel like there's a reason for why the IdSite dimension uses the idsite column & selects the name for the value. I want to make sure I understand the situation completely.
