### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by otykarol** [matomo-org/matomo#12417]
Hi,

I have just updated Piwik from 2.X to 3.2.1 and I encountered major problems.

Firstly, when I try to view my webpage statistics I get error "You can't access this resource as it requires 'view' access for the website id = 1." Everything except Piwik toolbars is blank.

Then, when I go to personal preferences, I get error "You must be logged in to access this functionality."

And when I try to regenerate the API token I get error "Please specify a value for 'userLogin'."

Could anyone help me with that? I am by no means an IT expert. I am administrating my webpage which is on the external server.

**Comment by sgiehl** [comment]
@otykarol  hope you finished to solve your problem. If not try to get some help on our forum.
