### ISSUE TITLE
modal can't be closed with keyboard

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#12439]
Another odd issue:

![unbenannt](https://user-images.githubusercontent.com/6266037/34894999-f19f7c00-f7e3-11e7-956f-3f50eeb78133.gif)

How to reproduce:

1. delete email report
2. try to accept the modal by pressing "enter" or "space"
3. another modal will popup
4. repeat until you get bored

really minor bonus bug: even after closing the modal they don't get removed from the DOM

**Comment by mattab** [comment]
fixed in https://github.com/matomo-org/matomo/pull/12462
