### ISSUE TITLE
User with permission View can't create segments

### ISSUE THREAD

**Issue by mihadd** [matomo-org/matomo#12437]
Hi,

in our hight traffic matomo cluster installation is the "Archive reports when viewed from the browser" set to NO and "browser_archiving_disabled_enforce = 1". Our helpdesk colleagues use a matomo user, which has only VIEW permission. Until Piwik 3.2.0 they created a lot of segments and an admin user had to switch segments setting to "segmented reports are pre-processed (faster, requires cron)" (which was not comfortable too). But since 3.2.1 they can't create segments anymore. Every creation results in the error message "To modify a pre-processed segment, a user must have admin access or super user access." I think this is the result of changes at ticket #12254 which were released with 3.2.1. Can you correct this please so users with VIEW permission can create segments again. 

Thanks in advance.
Mike

Piwik version: 3.2.1
MySQL version: 5.5.58
PHP version: 5.6.33-0+deb8u1

**Comment by mattab** [comment]
Hi @mihadd 

Please see the INI setting below which lets you configure this:


```

; By default, any user with a "view" access for a website can create segment assigned to this website.
; Set this to "admin" or "superuser" to require that users should have at least this access to create new segments.
; Note: anonymous user (even if it has view access) is not allowed to create or edit segment.
; Possible values are "view", "admin", "superuser"
adding_segment_requires_access = "view"
```

Thanks,
