### ISSUE TITLE
In responsive view, the selectors get pushed to the left of the screen

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12457]
in responsive view, when the Website/Segment/Calendar/Dashboard selectors are stacked on two lines, the second line starts on the very left of the screen. It would be great to show the same left margin on each line.

## Got 

![missing left margin](https://user-images.githubusercontent.com/466765/35010917-4e593d04-fb69-11e7-8e4e-a49986b64e28.png)

## Expected
 
The segment selector (`All visits`) should have the same margin left as the search bar.

**Comment by Findus23** [comment]
This got solved with  #12470
