### ISSUE TITLE
ERROR: Failed to get data from API: Action table for type '12' was not found during Actions archiving

### ISSUE THREAD

**Issue by MyKit** [matomo-org/matomo#12452]
![image](https://user-images.githubusercontent.com/11173940/34980630-2600b132-facb-11e7-863e-3ab58ec2f63d.png)

Hi All,

I am getting this error on all the pages in Piwik dashboard. Please let me know how to fix this.

**Comment by tsteur** [comment]
Are you using the latest Matomo version?

**Comment by MyKit** [comment]
Hi @tsteur, Appreciate your response. :)
Nopes. I am currently on Piwik 3.0.4.
Also needed to know if I upgrade from 3.0.4 to the latest Matomo version, are there any database level changes and will it break any of my MySQL database level ETL integration. I hope the upgrade will also fix the above error.

**Comment by tsteur** [comment]
Update won't be any problem and should be no DB updates or anything like this. I'm quite certain we fixed this in a recent version. Please update :)
