### ISSUE TITLE
Format sparklines better

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#12451]
for example instead of 
![image](https://user-images.githubusercontent.com/273120/34970918-23e17c18-fadc-11e7-9a3e-e87f5e7f4c16.png)

it would be possibly better to show it like this:

![image](https://user-images.githubusercontent.com/273120/34970923-35a959c0-fadc-11e7-8b34-78940d410432.png)

**Comment by fdellwing** [comment]
It should be possible to span the text to get this result.

**Comment by fdellwing** [comment]
I have a fix for that, but it will work with IE10+ only. Does that matter or needs IE9 to be supported?

**Comment by Findus23** [comment]
According to https://matomo.org/faq/new-to-piwik/faq_20541/
Support is IE10+
