### ISSUE TITLE
Add new keyboard shortcuts for Top/Bottom of page

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12456]
We currently show available keyboard shortcuts when pressing `?` on keyboard:

![shortcuts](https://user-images.githubusercontent.com/466765/35009211-c4ea2600-fb63-11e7-995e-a04f1812bcee.png)

It would be useful to also add two commonly used keys:

* `Home` to go to top of the page (`Fn + Left arrow` on Mac)
* `End` to go to bottom of the page (`Fn + Right arrow` on Mac)

**Comment by fdellwing** [comment]
> Home to go to top of the page (Fn + Left arrow on Mac)

I'm pretty sure this is called `pos 1` on most keyboards?

**Comment by Findus23** [comment]
@fdellwing, I'm not sure if that's not just a German difference as [Wikipedia disagrees](https://en.wikipedia.org/wiki/Home_key).

**Comment by fdellwing** [comment]
Interesting fact, than please take that in mind for the i18n strings. Otherwise german users would possible be very irritatet.

**Comment by tsteur** [comment]
We made the keys translatable so it can be adjusted for different keyboards.
