### ISSUE TITLE
Page Overlay: Replace images with font icons

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#12465]
The images are blurry:

![image](https://user-images.githubusercontent.com/273120/35025039-de8b2214-fba7-11e7-922d-6490c21d9bbc.png)

![image](https://user-images.githubusercontent.com/273120/35025044-e9026d24-fba7-11e7-9204-40dc3d04cf6b.png)

It also looks like the links are maybe using wrong font color but not sure.

Also the headline main metrics should be the regular font color of headlines and not blue:
![image](https://user-images.githubusercontent.com/273120/35025092-359d2b88-fba8-11e7-91f5-6eb7baa3907f.png)

**Comment by tborges** [comment]
Hi, I would like to help you guys with these images and the UI. I've been reading the Github's article about open source, but I still think that you guys created your own rules? I never helped an open source before.  Is there a to do list that I need to check? Is this the best way to reach you guys or should just email?

**Comment by Findus23** [comment]
@tborges Checking the open github issue is definitely a good way to start 

Also keep in mind that https://github.com/matomo-org/matomo/pull/12532 fixes a part of this issue, so don’t duplicate this part 😃 

https://github.com/matomo-org/matomo/issues/9292 is also related. 

If you want to do something that needs less changes in the Matomo source, you can help me improve the large collection of „mass icons“ (browsers, os, brands, websites, etc.)
https://github.com/matomo-org/matomo-icons

You can find the dynamic todo list here:
https://travis-ci.org/matomo-org/matomo-icons

**Comment by tborges** [comment]
@Findus23 , I created a SVG file and I commit yesterday. Take a look at MATOMO-ICONS

**Comment by Findus23** [comment]
@tborges That's great.
Don't be confused by it, I mostly maintained it alone, so if you have any question just ask me.
