### ISSUE TITLE
Help users getting started and complete important steps with Matomo

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#12467]
5 initial steps to complete
* Embed tracking code
* Define a goal
* Upload your logo
* Add another user
* Add another website

Once these are completed, we should show another 5 steps. This can be very easily configured in the plugin as everything is already prepared. Each step can be easily skipped.

What about 
* Add a new email report
* Add a custom alert
* Install Mobile App (optionally) => hard to check automatically whether this was achieved 
* Check out list of Features???
* Customize dashboard
* Add another dashboard
* Use heatmap 
* Use session recording
* Import search engine
* Create a segment
* Track your site search engine
* Track a form
* Run an experiment

For view/admin users we need different steps as above target Super Users. Examples could be:

Eg.:
* Create email report
* Export a widget
* etc...

When dashboard is widgetized we should not show the Tour widget.

## Further ideas
* Should we show engagements steps also on admin home page? I would have done this already but problem is it would be shown over full width there. As it is tiny widget I would rather want to show only in one/third column but that's not really possible since other plugins would not be able to put their plugins next to it. We may need an option in the admin to hide it for users so they don't see it anymore. (eg once all steps are completed etc)
* Send weekly reminders of the currently open steps?
* Show paging to navigate through different "parts" of steps
* Plugins should be able to add more steps. Ideally they are able to define something like an order whether it should be done quite early or rather later but not super important in the beginning. A triggered filter event be good enough for now so plugins can change/sort the order of steps.

**Comment by mattab** [comment]
That's really a great idea!

Btw maybe when steps are completed we could play a nice Congrats animation. This one came up today and is fun: https://codepen.io/jscottsmith/pen/VjPaLO

**Comment by tsteur** [comment]
Current status:
* Completely rewrote the code
* Now fully uses the API
* Changed the UI a bit
* Renamed all the things (eg renamed steps to challenges)
* Added a lot more challenges (15 so far)
* Introduced Levels that a user can progress/advance to such as Beginner => Professional => Expert
* Added paging
* Made everything a lot more flexible, and plugins can enrich the plugin
* Store whether challenges are completed per user, not across user
* Added share on social media links when completing all challenges successfully (but might need to remove FB and LinkedIn again as the links don't really work)

There are 15 challenges so far which are enabled depending on activated plugins and settings (eg if general_settings_admin or enable_geolocation is enabled):

* Install tracking code
* Create goal
* Upload custom logo
* add user
* add website
* add scheduled report
* add/customise dashboard
* add segment
*  add annotation
* disable browser archiving
* configure geolocation
* view visits log
* view visitor profile
* view row evolution
* browse marketplace

Some of them can be detected directly whether they have already been achieved or not (eg when we know a specific user created a specific site depending on `creator_login` column), while others need to be completed even if the user had done an action before.

There are more actions that could be added but not sure about it's usefulness 

* Switch visualisation (this one be actually really awesome since it is hard to discover this feature but can't really figure out a way to detect this feature was used except we would add some JS events and detect it through that but would result in lot more requests and make things complicated)
* Install custom dimensions plugin (not really needed by many)
* Export a widget / use the API (not really needed by many and partially hard to do etc)
* Uses page overlay feature (the feature is sometimes bit broken etc)
* Uses row transitions feature (had it added initially but now that it is exposed in menu not needed anymore)
* Tracks an event, or tracks a ... (hard for people to achieve this often and we cannot really detect whether it has been achieved since we would need to possibly do a full table scan on log table or add lots of extra logic to tracker)
* Tag manager: Creates a container (hard to detect this event etc since containers are auto created when creating a site etc. there's usually not needed to add another container, tag, ...)

Some others could be added to other plugins:
* Added a custom dimensions (when custom dimension plugin is installed)
* form analytics: configured at least one form
* heatmaps: configured a heatmap
* session recording: configured a recording
* a/b test: configured an a/b test
* funnel: configured a funnel

Ideally we would have some nice icons maybe around the different levels but it's hard to find anything good GPL compatible. Added stars instead for now.

Be good to add a few more challenges but not really needed since we will have like 20 with the premium features. Any thoughts @mattab @Findus23 ?

**Comment by tsteur** [comment]
Here are some screens.
There will be later 5 stars. It's 4 stars only currently because on my install not too many challenges are available due to disabled plugins etc. I basically need many feedback on ideas for useful challenges to add that can be also easily detected whether it has been achieved or not.

![image](https://user-images.githubusercontent.com/273120/56173136-8fe78900-6040-11e9-9a3e-974141fcdfee.png)

![image](https://user-images.githubusercontent.com/273120/56173153-9c6be180-6040-11e9-943d-9cd3d6f41c5b.png)
![image](https://user-images.githubusercontent.com/273120/56173162-a5f54980-6040-11e9-82b1-b229eb220095.png)

![image](https://user-images.githubusercontent.com/273120/56173168-b1487500-6040-11e9-9ba1-4531047ef9c1.png)

**Comment by tsteur** [comment]
FYI added some more

* Setup Two FA
* Change visualisation
* Flatten a report
* Select a date range

Was also going to add "Use Pivoting" as a challenge but it's currently only available on a few reports where they might not have data and AFAIK we don't have a guide for it that I can link to.

Positioned it in the default dashboard now above visitor map.

**Comment by mattab** [comment]
Fixed in https://github.com/matomo-org/matomo/pull/12468 :tada:
