### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'description' in 'field list'

### ISSUE THREAD

**Issue by alphaonex86** [matomo-org/matomo#12474]
Hi,

When I add a goal:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'description' in 'field list'

Cheers,

**Comment by Findus23** [comment]
Hi, 
This seems to be the same issue as #11221.

**Comment by alphaonex86** [comment]
Same, fixed
