### ISSUE TITLE
Django in shared hosting!!

### ISSUE THREAD

**Issue by AsadLiam** [matomo-org/matomo#12492]
hey guys i have the same issue but with my django app so what should i do please help 
this is the code of .htaccess file
```
---------------------------------------------------------------------------------------------------------
# DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION BEGIN
PassengerAppRoot "/home/dasawork/store"
PassengerBaseURI "/test"
PassengerPython "/home/dasawork/virtualenv/store/3.5/bin/python3.5"
# DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION END
----------------------------------------------------------------------------------------------------------
```
it worked at night first and then in the morning it wasn't working and giving the error "/home/dasawork/public_html/test/.htaccess: Invalid command 'PassengerAppRoot', perhaps misspelled or defined by a module not included in the server configuration". hosting providers changed my root dir name! like when it worked it was "'/newhome/dasawork/...." but on the morning it was changed to "/home/dasawork/..." so can this cause the problem ?
please help

**Comment by Findus23** [comment]
I am not sure what a configuration error in the htaccess of your Django project (try to enable the module that provides the setting `PassengerAppRoot`) has to do with Matomo.

**Comment by AsadLiam** [comment]
yeah i have shared hosting so i have to go with shared hosting settings. :| 
can you please tell me what is "Matomo"?

**Comment by Findus23** [comment]
> Matomo is the leading open-source analytics platform that gives you more than just powerful analytics:

from https://matomo.org/

Or in other words, Matomo is an Open Source alternative to Google Analytics. 
You are currently posting in the issue tracker of Matomo, which is quite unrelated to your issue.

**Comment by AsadLiam** [comment]
hahhahah so sorry i mean i thought that would be a good place 
sorry

**Comment by AsadLiam** [comment]
it's not Matomo but an issue can you help?

**Comment by mohammad-aqajani** [comment]
> hey guys i have the same issue but with my django app so what should i do please help
> this is the code of .htaccess file
> 
> ```
> ---------------------------------------------------------------------------------------------------------
> # DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION BEGIN
> PassengerAppRoot "/home/dasawork/store"
> PassengerBaseURI "/test"
> PassengerPython "/home/dasawork/virtualenv/store/3.5/bin/python3.5"
> # DO NOT REMOVE. CLOUDLINUX PASSENGER CONFIGURATION END
> ----------------------------------------------------------------------------------------------------------
> ```
> 
> it worked at night first and then in the morning it wasn't working and giving the error "/home/dasawork/public_html/test/.htaccess: Invalid command 'PassengerAppRoot', perhaps misspelled or defined by a module not included in the server configuration". hosting providers changed my root dir name! like when it worked it was "'/newhome/dasawork/...." but on the morning it was changed to "/home/dasawork/..." so can this cause the problem ?
> please help

how did you solve this problem?
