### ISSUE TITLE
CPU overloading with piwik js library

### ISSUE THREAD

**Issue by nemish** [matomo-org/matomo#12497]
Hi! We are using piwik.js library in our project and we've found a cpu overloading. There are near 300 elements to check visibility on page and even when page is idle (no scroll, no other user interactions on page) every analytics tick loads cpu too much. And ```isNodeVisible``` function takes most of time. Looks like we could reduce DOM calls by storing state of already tracked elements. Here is a link on fork with possible changes. https://github.com/nemish/piwik/tree/cpu-performance-2.
Is there any workaround how to fix this stuff or other advise how to decrease cpu load?
Here is a screenshot which can explain current situation.
![2018-01-19 17 13 09](https://user-images.githubusercontent.com/949090/35271224-775e5df0-0042-11e8-8d64-b3016bce15bb.png)

**Comment by tsteur** [comment]
@nemish seems like you have visible content tracking enabled. Can you maybe share a link to the page? How many content blocks do you have on your page approx?

By default, Matomo checks for newly visible nodes on scroll, and every 750ms where the every 750ms can be customized and set to eg every 0ms (won't do it anymore) as on "scroll" should actually do the job. Possibly we should change the default value there to `0ms`.

Additionally, we could set a property that caches that a node has been visible at some point. I think a simple solution may be even just something like this:

```diff
diff --git a/js/piwik.js b/js/piwik.js
index c2adab6363..24b44d0a34 100644
--- a/js/piwik.js
+++ b/js/piwik.js
@@ -1,5 +1,5 @@
 /*!
- * Piwik - free/libre analytics platform
+ * Matomo - free/libre analytics platform
  *
  * JavaScript tracking client
  *
@@ -2671,9 +2671,13 @@ if (typeof window.Piwik !== 'object') {
             },
             isNodeVisible: function (node)
             {
+                if (node && 'hasBeenVisible' in node && node.hasBeenVisible) {
+                    return true;
+                }
                 var isItVisible  = isVisible(node);
                 var isInViewport = this.isOrWasNodeInViewport(node);
-                return isItVisible && isInViewport;
+                node.hasBeenVisible = isItVisible && isInViewport;
+                return node.hasBeenVisible;
             },
             buildInteractionRequestParams: function (interaction, name, piece, target)
             {
```

This way the cache will also be used when a plugin calls the function and the logic is a bit simpler compared to https://github.com/matomo-org/matomo/compare/3.x-dev...nemish:cpu-performance-2 which does the same?

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
