### ISSUE TITLE
Is my Piwik compromised?

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#12504]
Piwik 3.2.1, Matomo 3.3.0

Thanks to a small custom plugin I use and the fact it got broken out of the blue, during tedious debugging session (as there was nothing in the logs!) I've noticed that my account is recognized as '**anonymous**' instead of **super admin**. Then... I saw this in the logs as soon as I was logged-in:

```
error_log(serialize(Piwik::getCurrentUserLogin()));
```
```
// first my ip line
[Wed Jan 24 20:47:40.580978 2018] [:error] [pid 6796] [client my--ip--here--:24929] s:9:"anonymous";

// then this line -- strange?
[Wed Jan 24 20:47:41.609620 2018] [:error] [pid 6599] [client *.12.78.130:60558] s:18:"super user was set";

// then immediately mine IP again afterwards, but still as anonymous ???
[Wed Jan 24 20:47:43.672229 2018] [:error] [pid 6749] [client my--ip--here--:25027] s:9:"anonymous";

```

This IP **62.12.78.130** is NOT MINE!

All IP variants (so far): (edit/update: IPs are anonymised by me)

*.12.78.130
*.185.183.24
*.68.101.168
*.208.213.133

What is going on? Any ideas? Why am I recognized as anonymous after login? On 3 different servers, 3 different PHP/Server versions, mixed Piwik 3.2.1 / 3.3.0 (upgrade didn't resolve the issue).

Thanks

**Comment by dev-101** [comment]
Piwik's integrity checks show everything is fine (except one function I've disabled on purpose, nothing strange is there).

**Comment by dev-101** [comment]
Is Piwik 'phoning home' whenever we login?
Is something broken in your API during this brand/name change?
As otherwise I cannot explain how this can happen on 3 different, separate and unrelated systems.

**Comment by sgiehl** [comment]
@dev-101 The URL you posted is a "normal" tracking request. 
What type of archiving are you using? triggered by cron job or browser archiving? 
If you are using browser archiving every tracking request might trigger an archiving process. As archiving needs to be done with "super user" access, the access is changed to super user for it and the user name is being set to "super user was set"

**Comment by dev-101** [comment]
Hi Stefan, I don't use cron, so that explains this - thanks. However, why is Piwik not returning my username instead it always returns 'anonymous'? It started happening since 2 days ago out of the blue. I haven't done any changes, file integrity is ok, so nothing suspicious. Yet, this line required by my plugin no longer works properly. Why?

**Comment by sgiehl** [comment]
That line should return the currently logged in user. At which position do you call the method?

**Comment by dev-101** [comment]
Here's the initial code (again, everything was working fine until recently, and nothing was changed in my systems that should affect this behavior):

```
namespace Piwik\Plugins\MyPlugin;
use Piwik\Piwik;

class MyPlugin extends \Piwik\Plugin
{
	public function registerEvents()
	{
		$login = Piwik::getCurrentUserLogin();
```

**Comment by tsteur** [comment]
At the time you are logging this, the authentication has not been executed yet AFAIK

**Comment by dev-101** [comment]
Hi, but it was working just fine - how can we explain that? And logging line was called after *$login = Piwik::getCurrentUserLogin();* line. I am really puzzled by this now.

**Comment by mattab** [comment]
In your example above you typically want to move the "if" statement and this logic into your `MyMethod`. So you always define the events but inside the event observers you can skip doing something. (not sure if this would be enough to solve the issue)

**Comment by dev-101** [comment]
Thanks Mat, it fixed my issues completely. I am still not sure why this worked for months and then suddenly stopped, but sorry for the false alarm about security.

Regards
