### ISSUE TITLE
Map of India is wrong

### ISSUE THREAD

**Issue by wharpreet** [matomo-org/matomo#12507]
Hi,
Map of India visible in "Visitor Map" section is wrong. Please fix ASAP.
Thanks

![screenshot from 2018-01-25 12-07-27](https://user-images.githubusercontent.com/1982952/35374289-4146a128-01c8-11e8-8ae0-73eb21596d13.png)

**Comment by fdellwing** [comment]
Tried to google what part is wrong, but had not much luck.

**Comment by sgiehl** [comment]
We plan to replace/update our maps at some points. See #11929
Could you please describe what part is wrong?

**Comment by wharpreet** [comment]
Part of Kashmir is missing.
Google shows it correctly (screenshot attached)

<img width="233" alt="screen shot 2018-01-25 at 1 58 05 pm" src="https://user-images.githubusercontent.com/1982952/35378158-d8aecc98-01d7-11e8-900e-a111fda031c5.png">

**Comment by robocoder** [comment]
Google displays different maps of India depending on where you are. Both India and Pakistan have laws re: the inclusion of Kashmir (in whole or in part) on maps. This isn't the place to discuss the Kashmir territorial dispute between India, Pakistan, and (to a lesser extent) China.

I suggest closing this ticket and direct technical discussion to #11929 .

**Comment by varunKothare** [comment]
Customer Feedback:
"We can see that Indian country map is shown incorrectly in the user activity section of the website dashboard.
Our country didn't sell any land (Jammu & Kashmir District) to Pakistan for showing modified map like this.
Publishing such content in public platform like this is not acceptable in any case.
Kindly change the same and inform the steps taken within one month to avoid lodging complaint at Indian Ministry of Electronics & Information Technologies.

![image](https://user-images.githubusercontent.com/100554311/217668322-04eb7651-2776-42fd-815f-9e9b109c83fa.png)

The actual map published by Gov of India will be as follows: https://www.surveyofindia.gov.in/documents/polmap-eng-11012021.jpg
