### ISSUE TITLE
Include instructions for building Matomo from source

### ISSUE THREAD

**Issue by fitzoh** [matomo-org/matomo#12509]
We're looking at running a modified version of Motomo.
It's not clear from the README what steps should be performed to create a release locally.
Please include instructions in the README (or another relevant file) with instructions on how to create a Motomo release.

**Comment by Findus23** [comment]
While I don't think this is needed in your case, you can find the information on how to get Matomo running from the git repository here:
https://github.com/matomo-org/matomo-package/blob/master/scripts/build-package.sh
https://developer.matomo.org/guides/getting-started-part-1

**Comment by cah-andrewfitzgerald** [comment]
Thanks @Findus23, that `build-package.sh` script is what I was looking for.
Do you think it would be worthwhile to add a note to the README about any of the other associated repos?

**Comment by cah-andrewfitzgerald** [comment]
@Findus23 just to follow up on your comments on #7039 about a lack of compile step:

It looks like the biggest transformation steps that occur in a release build are stripping out the hidden dot files and generating the `vendor` file using composer.

Anything else?

**Comment by mattab** [comment]
@cah-andrewfitzgerald you can find the code in: https://github.com/matomo-org/matomo-package/blob/master/scripts/build-package.sh 

instructions in https://github.com/matomo-org/matomo-package/#core-matomo-package

In general you can also follow our FAQ to deploy Matomo from sources (ie. form Git repo) at: https://matomo.org/faq/how-to-install/faq_18271/

**Comment by mattab** [comment]
@cah-andrewfitzgerald feel free to open a PR to add instructions if you think that's helpful and we'll review it :+1:
