### ISSUE TITLE
Tracking stopped for 1 website after upgrade to 3.3

### ISSUE THREAD

**Issue by daylicron** [matomo-org/matomo#12513]
Hey there,
I'm running Matomo 3.3 on Apache 2.4.10 with PHP-FPM 5.6.33 on a Debian 8.10.
It's tracking 7 Websites successfully, but one not anymore. 

Actually I see the API requests from this one site in my Apache access_log. I can even import them using log-importer.py, but they aren't imported automatically via the API. Below a request for the broken site from my access_log:
`7fc98b06653286aad02111b62313231055234436 - - [26/Jan/2018:17:17:24 +0100] "GET /piwik.php?action_name=%27foo%20bar%20-%20foo%20bar%27%20foo%20-%20bar%20Dfoo%20-%20BMZ&idsite=10&rec=1&r=849186&h=17&m=17&s=37&url=http%3A%2F%2Ffoo%2Fwhat_we_do%2Fhss%2Findex.html&urlref=http%3A%2F%2bar%2foo%2foo%2bar%2Findex.html&_id=25f2a14e8d8484eb&_idts=15xyz&_idvc=5&_idn=0&_refts=0&_viewts=15xyz&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=0&java=0&gears=0&ag=0&cookie=1&res=1920x1080&gt_ms=10&pv_id=18qZlY HTTP/1.1" 200 43 "http://foobar" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.97 Safari/537.36 Vivaldi/1.94.1008.40"`

Of course we checked the tracking code and copied the generated one from Matomo into the website:
```
<!-- Matomo -->
<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(["setCookieDomain", "*.someurl"]);
  _paq.push(["setDomains", ["*.someurl"]]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//someurl/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '10']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//someurl?idsite=10&rec=1" style="border:0;" alt="" /></p></noscript>
<!-- End Matomo Code -->
```
Do you guys have any idea?

Cheers
Dennis

**Comment by daylicron** [comment]
Nobody having a clue about this?

**Comment by Findus23** [comment]
Hi,
Did you check the php error_log for errors?
Otherwise you can temporarily enable debugging ([more information](https://developer.matomo.org/api-reference/tracking-api#debugging-the-tracker)) 
When you then open the `/piwik.php?[...]` URL in the network tab of your browser you should see an extensive log why the data wasn't saved.

**Comment by daylicron** [comment]
Oh my god...

> Otherwise you can temporarily enable debugging (more information)
This helped me out: The URL of the Website was changed a bit unfortunately while I performed the Piwik Upgrade... After adjusting the Website's URL in Matomo, it's working now.
Thanks man!
