### ISSUE TITLE
CSS and JS not loading

### ISSUE THREAD

**Issue by ChristophRob** [matomo-org/matomo#12517]
Sometimes css and js stop loading on my matomo website. After it stops it takes days before its starting to work again. I think its a serverside problem because i experienced that with different macs and browsers with no extensions like AD-Blockers. Its only running on http. Could that be the root of the bug?

I attached two images. The first one shows, the same browser with 2 tabs, one working and one not working matomo with the same domain. (The pretty one would stop working after a refresh)
The second image shows dev tools with some hieroglyphics

![matomo_bug](https://user-images.githubusercontent.com/16916263/35502643-ebe2f90c-04dd-11e8-8647-c79b38b262f9.png)
![matomo_bug2](https://user-images.githubusercontent.com/16916263/35502644-ebfa4986-04dd-11e8-9224-f88501cc5efe.png)

**Comment by fdellwing** [comment]
I browsed at http://analytics.alumnii.de/ and it seems like you have Google Pagespeed enabled. This is not working well with matomo. Please disable it for this site and try again.

**Comment by ChristophRob** [comment]
Yes that seemed to work! Thank you very much. 

To disable Google Pagespeed:
I added a .htaccess file on my server root folder only with the text:
`ModPagespeed off
`
