### ISSUE TITLE
Rename our composer packages

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#12519]
Our composer packages are still listed under the vendor piwik on packagist. As there is no way to rename them, we need to create new packages and mark the old ones as abandoned

I've already started and will try to rename the other over the next days

- [x] `piwik/cache` -> `matomo/cache` (https://github.com/matomo-org/component-cache/pull/17)
  -> released as version 2.0.0; usage needs to be implemented in Matomo 4
- [x] `piwik/decompress` -> `matomo/decompress` (https://github.com/matomo-org/component-decompress/pull/12)
  -> released as version 2.0.0; usage needs to be implemented in Matomo 4
- [x] `piwik/device-detector` -> `matomo/device-detector`
- [x] `piwik/ini` -> `matomo/ini` (https://github.com/matomo-org/component-ini/pull/8)
  -> released as version 2.0.0; usage needs to be implemented in Matomo 4
- [x] `piwik/network` -> `matomo/network` (https://github.com/matomo-org/component-network/pull/14)
- [x] `piwik/piwik` -> `matomo/matomo`
   -> needs to be done in Matomo 4
- [x] `piwik/piwik-php-tracker` -> `matomo/matomo-php-tracker` (https://github.com/matomo-org/matomo-php-tracker/pull/51)
- [x] `piwik/referrer-spam-blacklist` -> `matomo/referrer-spam-blacklist` (#12518)
- [x] `piwik/searchengine-and-social-list` -> `matomo/searchengine-and-social-list` (#12518)

Renaming the php packages does only make sense with Matomo 4, so we can rename all namespaces and classes without the possibility to break any plugins. Imho it doesn't make sense to name the package `matomo/*` but the classes would still need something like `use Piwik\*`

**Comment by AndoniLarz** [comment]
Hi, I'm willing to use the piwik/piwik package in my project so I'm wondering : if you rename it to matomo/matomo, will I still be able to use piwik/piwik in my composer.json or should I wait until you rename it and use matomo/matomo ?

**Comment by sgiehl** [comment]
@AndoniLarz  what exactly are you going to use? It will take a while until we will rename this package, as we will likely do that in Matomo 4. As most of the remaining rename tasks will be done than. See #12420

**Comment by AndoniLarz** [comment]
Well I wanted to integrate this package into my Symfony project, and I wanted to know if you were going to rename it promptly so I should wait a bit, or if you were going to let it named piwik for some time.
Of course if you have some advice about how I could integrate piwik/matomo in my Symfony project (so I don't have to use two servers), I'd be glad to hear !

**Comment by robocoder** [comment]
Is it possible to create dummy packages? So piwik/piwik requires matomo/matomo?

**Comment by sgiehl** [comment]
I don't think this would make much sense for most of the packages... We are changing the php namespaces for some of the packages, so if we want to provide dummy packages here, we would need to wrap the new namespaces into the old ones to have it still working

**Comment by N3X15** [comment]
Is there something I'm supposed to be doing to fix my existing git installs?  Keep getting:

```
Package piwik/cache is abandoned, you should avoid using it. Use matomo/cache instead.
Package piwik/decompress is abandoned, you should avoid using it. Use matomo/decompress instead.
Package piwik/ini is abandoned, you should avoid using it. Use matomo/ini instead.
```

after `git fetch --all --prune && git checkout $RELEASE_TAG && git submodule update --init --recursive && composer i --no-dev`

**Comment by sgiehl** [comment]
you can ignore that messages. We will use the new packages in Matomo 4.

**Comment by N3X15** [comment]
Thanks.

**Comment by sgiehl** [comment]
Renaming the composer package of device detector can be done somewhen later. I'm planning to to do that with a new major release of Device Detector, but as I didn't have much time to work on that the past months, I will postpone that. But won't hurt in matter of Matomo, as it uses an own namespace, that won't change.

Regarding the rename of the piwik/piwik package. Not sure if we should do that with Matomo 4? actually shouldn't hurt to do it and have both package names maybe?

**Comment by tsteur** [comment]
@sgiehl personally no preference. Can we have easily both names? If that's possible be good.

**Comment by sgiehl** [comment]
> personally no preference. Can we have easily both names? If that's possible be good.

Actually like we have it for the components. Even though they are renamed to matomo/* the new releases are still available with the piwik/* name as they use the same repo.
See https://packagist.org/packages/matomo/cache and https://packagist.org/packages/piwik/cache

For piwik/piwik, we might not even need to mark the package as abandoned if we don't wont to "force" people to switch to the new name

**Comment by tsteur** [comment]
👍

**Comment by sgiehl** [comment]
Just release a new major version of device-detector including the rename to `matomo/device-detector`
