### ISSUE TITLE
Piwik Analytic Report not populating

### ISSUE THREAD

**Issue by WI-Manitowoc** [matomo-org/matomo#12510]
On Monday, 1/22/2018, I created numerous segments for our website.  As of 1/25/2018, they're still not populating.  Typically, it has taken up to 48 hours for the segment analytics to become available.

**Comment by fdellwing** [comment]
Do you use browser triggered or cron triggered archiving?

**Comment by Findus23** [comment]
When reports are not shown, even though live data is recorded, check if either browser archiving is activated or the cronjob is running successfully.
