### ISSUE TITLE
Debian Package for Piwki 3.3.0 still missing

### ISSUE THREAD

**Issue by sc0rp10** [matomo-org/matomo#12522]
Hi, version 3.3.0 was release about two weeks ago, but we cannot install it to our servers because this version is missing in debian.piwik.org
Can you please upload latest version to the repo?
Thanks!

**Comment by JedMeister** [comment]
I emailed the devs directly regarding this issue and here's what they said:

> The debian repo is currently bit out of date. It should be updated
in the next 2 weeks to the latest version (what the maintainer told
me)

**Comment by JedMeister** [comment]
FWIW the issue to follow regarding the progress of this is here:
https://github.com/matomo-org/matomo-package/issues/62

**Comment by aureq** [comment]
Hi everyone,

I'm hoping to have this released in the next 10 days or so.

**Comment by Findus23** [comment]
This has been solved a long time ago.
