### ISSUE TITLE
 "Possibly unhandled rejection: {}" after update from Piwik

### ISSUE THREAD

**Issue by thunfischbrot** [matomo-org/matomo#12527]
After upgrading automatically from previous Piwik version forms do not work any more, e.g. to change personal details or create an email report. The web console shows angularjs errors: "Possibly unhandled rejection: {}" (see screenshot).

The system report is all green, except for using http instead of https.

![2018-02-01 16_25_47-clipboard](https://user-images.githubusercontent.com/583358/35686689-2adc3efc-076d-11e8-8dfe-49284f9f41ab.png)

**Comment by mattab** [comment]
Hi @thunfischbrot 
Maybe this to clear caches and try again to request the UI? https://piwik.org/faq/how-to/faq_25548/
and also try another browser?

**Comment by thunfischbrot** [comment]
Hi @mattab 
thank you, I had tried in Windows 7 Chrome and Firefox as well as macOS Firefox with the same results. After clearing the cache I get the same results, now I tried macOS Safari which seems to work.

I will investigate further, but for now I can do what I need to do in Safari. I cleared the cache in Firefox but still getting the same result, going to try again later.

Thank you!
