### ISSUE TITLE
zend_db_adapter_mysqli_exception

### ISSUE THREAD

**Issue by triffic-tang** [matomo-org/matomo#12523]
Set up a Crontab to Automatically Archive the Reports.

I am going to start crontab, it shows the log as below:

```
[Zend_Db_Adapter_Mysqli_Exception]
The Mysqli extension is required for this adapter but the extension is not loaded.
```

But I have do installed the `Mysqli` module, what should I do?

**Comment by fdellwing** [comment]
Make sure the module is activated for php-cli. It is using another php.ini than your webserver!

**Comment by tsteur** [comment]
As @fdellwing pointed out you will need to make sure the server loads this extension as well when being executed from the CLI not only in your webserver.
