### ISSUE TITLE
Mobile Sidebar appears on desktop site

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#12531]
Seems like I am bad at hitting buttons 😄 
When one clicks right of the login button (e.g. on demo.matomo.org) on the desktop page the mobile sidebar appears once. (Tested in firefox and chromium)
![gif](https://user-images.githubusercontent.com/6266037/35748771-6f9d458a-084f-11e8-86d0-fea9332f14ea.gif)
<sub>(Would be nice if one could upload videos to github, converting a 37KB video to a 4.7 MB gif is quite inefficient)</sub>

**Comment by sgiehl** [comment]
I guess that area is meant for touch devices so the menu opens when swiping from the side. Are you using a device with touch screen?

**Comment by tsteur** [comment]
It is likely a builtin jquery/materializecss feature

**Comment by justju** [comment]
I updated the PR in a Point 2 like manner.
