### ISSUE TITLE
Matomo 3.3.0 complains about IntranetGeoIp.data.php file

### ISSUE THREAD

**Issue by brgsousa** [matomo-org/matomo#12544]
![capturar](https://user-images.githubusercontent.com/11218051/35946502-c3bdaa50-0c42-11e8-94d5-c8cf89392061.PNG)

I have php 7, matomo 3.3.0 and intranetgeoip 3.0.1  installed. But matomo complains about file integrity that config/IntranetGeoIP.data.php shouldn't exist. But it is a legit file of the intranetgeoip plugin

**Comment by sgiehl** [comment]
This needs to be solved in the plugin. Left a comment on the issue
