### ISSUE TITLE
Issues with Matomo Scheduled reports on Plesk

### ISSUE THREAD

**Issue by hwaqark** [matomo-org/matomo#12557]
Hi,

I have installed Matomo on Plesk server and have scheduled some reports using the default mail settings and have not changed anything. When I click send it says reports sent but we do not get it. Tried it on our office365 company email, private gmail and private outlook mail. 

Please help. 

Thanks

Hassan

**Comment by mattab** [comment]
Hi Hassan,

Thanks for the report. Can you please check: https://matomo.org/faq/troubleshooting/faq_34856/
and let us know what you find?
