### ISSUE TITLE
Media analytics tracking bitrate and buffered time

### ISSUE THREAD

**Issue by vookaphani** [matomo-org/matomo#12554]
Can we have media analytics also track the bitrate, buffered time, network Failures when the video is played?  This would help to derive QoS metrics for the media.  
Is there a way, we can calculate the number of concurrent plays for a  video at a given time.

**Comment by Findus23** [comment]
Hi,
This is the issue tracker of the Open Source Matomo project, but if you want to we can continue this on the forum:
https://forum.matomo.org/t/media-analytics-tracking-bitrate-and-buffered-time/27184

**Comment by tsteur** [comment]
@vookaphani we have this on our roadmap already. We have been partially discussing this feature with a couple of users but are still not sure what the most useful way be to track and present this data etc. If you have some detailed suggestions on what you want to see there, please let us know in the forum 👍
