### ISSUE TITLE
How to get the exact number of searches for a keyword/the number of times a keyword has produced no results.

### ISSUE THREAD

**Issue by Sobhika2** [matomo-org/matomo#12566]
Hello,

One of our application that is integrated with Piwik is mainly used as a search engine. Hence, it is very important for us to get the exact number of times a keyword has been searched or the number of times it has produced no results. However, Piwik currently is displaying 'The number of visits that searched for a keyword in the Search engine' as 'Searches'. This means, if a keyword is searched multiple times by a single user in a single visit, the 'Searches' field will display the count as one only.

How can I get the number of searches for a keyword/the number of times a keyword has produced no results despite if it is from a single visit or not?

Regards

**Comment by Findus23** [comment]
The discussion seems to have been continued in https://github.com/matomo-org/matomo/issues/14055
