### ISSUE TITLE
How to secure access to the admin UI

### ISSUE THREAD

**Issue by hsafe** [matomo-org/matomo#12569]
Hi,
Can you advise on how to segregate the matomo UI from the API ? this is particularly important for us since we would like to limit access to the admin page of our matomo. If for example the traffic to the api pass through but a rogue Interent user can not simply get to the admin panel ?

**Comment by sgiehl** [comment]
You may want to restrict access using a htaccess file. See https://forum.matomo.org/t/using-htaccess-to-restrict-access/1532/26
Additionally there is a feature within Piwik to only allow access to admin with defined IP addresses: https://matomo.org/faq/how-to/faq_25543/

**Comment by hsafe** [comment]
Awsome, thanks ;)
