### ISSUE TITLE
Error Loading MarketPlace

### ISSUE THREAD

**Issue by Sobhika2** [matomo-org/matomo#12567]
Hi,

I am getting an error while trying to access the MarketPlace in Piwik version 3.2.0. The error also appears while accessing the Administration tab. Attached is the error screens for the same.

The log displays below error messages:

[Fri Feb 16 12:41:52 2018] [error] [client 10.54.17.33] Error in Piwik: , referer: http://piwik-test.swissre.com/piwik/index.php?module=CoreAdminHome&action=home&idSite=1&period=day&date=yesterday&activated=

Can anybody help?

Regards
![administration](https://user-images.githubusercontent.com/26790315/36306922-d08d32b0-133f-11e8-8801-c6ed7e15a73e.png)
![marketplace](https://user-images.githubusercontent.com/26790315/36306923-d0a56b00-133f-11e8-8f8f-7584be28c679.png)

**Comment by cawale** [comment]
I am seeing the same thing.

**Comment by tsteur** [comment]
Did it just suddenly stop working? Where there maybe any changes like a Piwik/Matomo update or server update or something?

**Comment by Findus23** [comment]
@cawale 
Can you check this forum thread:
https://forum.matomo.org/t/request-to-marketplace-fails/27284

**Comment by cawale** [comment]
Tried the solution that you suggested but no luck. 

This is a new install v 3.3.0. I can get out to the internet from the server. I have used apt-get lots to get Matomo setup.

**Comment by Sobhika2** [comment]
I was able to fix this issue by changing the domain value to $domain = ‘http://plugins.matomo.org/’; in the config file under the below path : /opt/pwk/piwik/plugins/Marketplace/config # vi config.php.

I believe the redirection from piwik to matomo was not defined which was creating the issue.

**Comment by tsteur** [comment]
It should have still worked with plugins.piwik.org (just tested it here) but glad it works now.
