### ISSUE TITLE
Syntax error or access violation: 1064

### ISSUE THREAD

**Issue by wlinker** [matomo-org/matomo#12564]
in: Matomo matomo-3.x-dev, AND Matomo latest stable from webpage I have this error:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
An error occurred
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '. piwik_log_visit' at line 1
Go Back | Go to Matomo

Matomo.org homepage
Matomo Frequently Asked Questions
Matomo Documentation
Matomo Forums
Professional help for Matomo
« Back to Matomo

But i don't get any information about where are the problem, help me!

**Comment by wlinker** [comment]
My Error.log from PHP show this:
[15-Feb-2018 18:41:05 UTC] Error in Matomo: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;. piwik_log_visit&#039; at line 1

**Comment by yoshimasa0202** [comment]
My Error.log from PHP show this:
	
PHP message: Error in Matomo: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;. piwik_log_visit&#039; at line 1

piwik/console core:archive from CRON error show this:

INFO [2018-04-21 23:36:59] Error: Got invalid response from API request: ?module=API&method=API.get&idSite=11&period=day&date=last52&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:219:"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '. piwik_log_visit' at line 1";}'

--
My Server specs are:
CentOS Linux 6.9 (x86_64)
Mysql 8.0.11
Nginx 1.14.0
PHP 7.1.12

**Comment by thelittlefireman** [comment]
Same error after the installation step when you set the db.
i'm using the docker image of matomo : 3.4.0
```SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '. matomo_log_visit' at line 1```

Mysql 8.0.13

**Comment by sgiehl** [comment]
I hope this issue was meanwhile fixed silently somewhen in the last 4 years. If anyone still has this problem, please don't hesitate to create a new issue for it. Thanks.
