### ISSUE TITLE
SQL type FLOAT should not be used for economical data

### ISSUE THREAD

**Issue by olleharstedt** [matomo-org/matomo#12575]
In table `log_conversion`, `revenue` has type `FLOAT`. It should be `DECIMAL(11, 2)` or similar.

**Comment by fdellwing** [comment]
Why not?

Links to any studies? Performance tests? Other known problems?

**Comment by olleharstedt** [comment]
Precision. `0.1 + 0.2 != 0.3` in float.

**Comment by olleharstedt** [comment]
And today I tried to get all conversions with revenue = `0.29`, which was not possible in SQL using `= 0.29`.

**Comment by olleharstedt** [comment]
Here's a stackoverflow thread about it: https://stackoverflow.com/questions/13030368/best-data-type-to-store-money-values-in-mysql

**Comment by robocoder** [comment]
Looks like 4 decimals places (to accommodate Chile) would suffice.  https://en.wikipedia.org/wiki/ISO_4217

**Comment by sgiehl** [comment]
We can't address this issue prior Matomo 4.0, as we try to avoid any schema changes to log tables in minor releases...

**Comment by tsteur** [comment]
Note: We'll only change it for new installs and create an FAQ for existing installs. For more details see  https://github.com/matomo-org/matomo/pull/15408/files#r367739574

**Comment by sgiehl** [comment]
@tsteur can we close this issue, now as #15408 is merged, or shall we keep it open as reminder for anything?

**Comment by tsteur** [comment]
@sgiehl there are still some floats in other tables like log_conversion which we may want to change. Could also check there if `DECIMAL(X,Y)` works nicely for new installs meaning that it won't automatically convert a `5` to a `5.00` when inserting such a record and then selecting these values aren't automatically converted to `5.00` (but I think it does). We would then use `double` instead I guess. I suppose float might be too small for some currencies.

**Comment by olleharstedt** [comment]
`double` still uses floating-point arithmetic.
