### ISSUE TITLE
PHP API is not set to follow HTTP redirects

### ISSUE THREAD

**Issue by olleharstedt** [matomo-org/matomo#12571]
This setting

`curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);`

needs to be set in the PHP API, in case an HTTP request is being redirected to HTTPS.

**Comment by sgiehl** [comment]
What problem are you trying to solve?

**Comment by olleharstedt** [comment]
When using the PHP API, we set it up like

```lang=php
PiwikTracker::$URL = 'http://analytics.oursite.org';
$piwikTracker = new PiwikTracker($siteId = 1);
```

If HTTP redirects to HTTPS, it will fail silently.

**Comment by olleharstedt** [comment]
By which I mean, this call should return false:

     $result = $piwikTracker->doTrackGoal(20, 1);

**Comment by tsteur** [comment]
Sounds like this is actually an issue for https://github.com/matomo-org/matomo-php-tracker/ . Do you mind creating a PR there?

**Comment by olleharstedt** [comment]
Done.

**Comment by sgiehl** [comment]
Thanks. I'll close the issue here in favor of https://github.com/matomo-org/matomo-php-tracker/pull/31
