### ISSUE TITLE
Problems when I tried to upload the GeoLite in File Zilla

### ISSUE THREAD

**Issue by orl99** [matomo-org/matomo#12572]
Hello guys, I have been struggling when I tried to upload the GeoLiteCity.bat
I followed all the instructions, but I could not upload it. Can you help me ?
Best Regards
Orlando Garcia

**Comment by sgiehl** [comment]
Isn't the automatic download working for you in Matomo? It should do everything automatically...
Btw. for questions and support it's better to use our forum (https://forum.matomo.org), as this is an issue tracker only.
