### ISSUE TITLE
visitor logs for today seems to include yesterdays logs?

### ISSUE THREAD

**Issue by si458** [matomo-org/matomo#12583]
when you go into the vistor logs and select todays date,

the logs underneath it then show today and yesterdays logs instead of only todays?

but if you change the day to yesterday or a day the week before, it shows those says correctly

**Comment by fdellwing** [comment]
Did you try reloading without cache? There seems to be an odd caching sometimes.

**Comment by si458** [comment]
Yes i have tried CMD+SHIFT+R on firefox about 100times and still the same?
even weirdier is ive just noticed on the dashboard the Visitors in Real-time shows all todays hits and yesterdays?
even tho its not actually Real-Time and live as in right now...
https://screenshots.firefox.com/5ajYd132uNHdnuOC/stats.hestor.com
https://screenshots.firefox.com/MC14uNGplM5BKcCO/stats.hestor.com

**Comment by tsteur** [comment]
FYI: This is currently "expected" behaviour AFAIK. We have tried to fix it a few times but then reverted a fix again (AFAIK), cannot find the PR right now

**Comment by si458** [comment]
but to my mind is i want to see todays stats and only todays it should show todays, and not yesterdays aswell? as the date thats selected at the top is todays date only and not like weeks worth?

**Comment by tsteur** [comment]
yes sure, it is a bug. I'd recommend to have a search for a related issue. There should be one AFAIK.

**Comment by sgiehl** [comment]
See #8761 and linked issues
