### ISSUE TITLE
How can get the real ip address of visitor when there are two nginx proxy between the visitor and the backend web server?

### ISSUE THREAD

**Issue by fionaliupw** [matomo-org/matomo#12585]
How can get the real ip address of visitors when there are two nginx proxy between the visitor and the backend web server?
visiting routing:
the visitor->nginx of the tracked web->nginx of the Madomo web server ->the real ip address of the Madomo web server

Urgently,please! 

Thank you very much.

**Comment by sgiehl** [comment]
Aren't you using Javascript Tracking Pixel? If so, aren't the tracking requests sent directly to the Matomo server? 
You may find the correct settings in our faq: https://matomo.org/faq/how-to-install/faq_98/
