### ISSUE TITLE
Developer documentation: the list of all segments is missing the "Metrics" segments

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12590]
Just noticed a regression in : https://developer.matomo.org/api-reference/reporting-api-segmentation

Below the title "Metrics" it should list all metric segments. But there is nothing displayed after the Metrics title.

See the original API response here: https://demo2.matomo.org/index.php?module=API&action=listSegments&language=en

**Comment by sgiehl** [comment]
There are no metrics left to display, as all segments are dimensions or are changed to dimension after https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/API/Controller.php#L83-L85
Maybe that additional check is outdated as it converts all metric segments to dimensions?

**Comment by diosmosis** [comment]
@mattab looked further into @sgiehl's insight and saw that the `if` in question is regarding the "event value" segment. Also noticed this segment was removed in https://github.com/matomo-org/matomo/commit/641e9ce4aca81ddb3d66983aab80e477727a1d93 . If it's not supposed to be a segment, we can remove that check to show those segments in the "Metrics" category.

**Comment by mattab** [comment]
@diosmosis segment value should be a new segment ideally, as it would be useful for some use cases.

**Comment by diosmosis** [comment]
@mattab so add a "event value" segment? and it would be a "dimension" metric, correct? I'll try to add it & then will remove the if block that's causing metric segments to be displayed as dimension segments.
