### ISSUE TITLE
Matomo Analytics - GDPR Compliance Project

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12600]
This issue is the master issue where we discuss new features and changes needed in Matomo to make it easier for users be GDPR compliant. 

  

With Matomo, [privacy is built-in](http://matomo.org/privacy). We offer [several privacy controls ](http://matomo.org/docs/privacy)already, but this is not enough for GDPR compliance.

  

Steps we will take to make Matomo GDPR compliant:

- GDPR - Overview / Info Screen #12594 
- GDPR - Rights to access data  #12595 
- GDPR - Right to erasure or right to be forgotten #12596 
- GDPR - Right to rectification #12597 
- GDPR - The data subject right to restriction of processing & The right to withdraw consent  #12598 
- GDPR - The right to be informed #12599 
- GDPR - Compliance for old data collected without consent, Data Anonymisation & Removal tool #12641

GDPR rights which we won’t cover (at least for now):

- GDPR - Right to data portability: Not applicable to Matomo. 
- GDPR - Rights around automated decision making and profiling: By default, automated decision making and profiling is not possible with Matomo so we won’t cover this right, at least for now. 
  

We’re planning to finish this work at least 1 month before the GDPR start date of May 25th.

  

Please check these issues and feel free to comment.

**Comment by mattab** [comment]
And we'll likely also build a new very useful little tool:  Personal Data Anonymisation & Removal tool #12641

**Comment by mattab** [comment]
## information architecture of the Privacy features and tools. 

As the current "Settings" and GDPR Tools and GDPR Manager menu entries all refer to different tools and maybe we can simply the structure like something like this:


* "Anonymise data" (anon IP + delete logs + delete reports + anon old logs) ,
* "Privacy policy" (remind how important it is to have a good privacy policy + link to users opt-out)
* "Users opt-out" (iframe + DNT),
* "Asking for consent" (JS API doc, later the consent UI),
* "GDPR tools" (request to access+delete tool, + link to the tools available in the other sections) 
* "GDPR overview"

**Comment by HannesSE** [comment]
Could you also create a stripped-down "non personal data" only version of Matomo (that could be selected in the settings)?

That stripped-down version would not collect personal at all. For example, only the following could be tracked:

- How often a particular page was viewed (but not by whom)
- Which campaigns received the most clicks (but not by whom)
- Which campaigns received the most goals, etc.

As far as I understand it, such a Matomo version would be GDPR compliant without the need to show a cookie banner and without the need for consent (as no personal data is collected).

**Comment by mattab** [comment]
Hi Everyone, we have released the GDPR Compliant Matomo in 3.5.0-b2 -> Please help us test all the new tools! You can grab it from the beta release channel, learn more: http://piwik.org/faq/how-to-update/faq_159/

Your feedback welcome, please open new issue if you have any feedback or find a bug :rocket:
