### ISSUE TITLE
Manage Goals

### ISSUE THREAD

**Issue by Felixbachmann** [matomo-org/matomo#12612]
Just upgraded the version 3.3.0. Worked with no issue
When clicking on Manage Goals I get the error
Oops… there was a problem during the request

In the browser development console I see an error 500 and below is the page that was sent by the server
Any ideas?
Felix

<!DOCTYPE html>
<html>
    <head>
        <meta name="robots" content="noindex,nofollow">
        <style type="text/css">
            html, body {
                background-color: white;
            }
            td {
                border: 1px solid #ccc;
                border-collapse: collapse;
                padding: 5px;
            }
            table {
                border-collapse: collapse;
                border: 0px;
            }
            a {
                text-decoration: none;
            }
            a:hover {
                text-decoration: underline;
            }
        </style>
        <title>A fatal error occurred</title>
    </head>
    <body>

        <h1>A fatal error occurred</h1>

        <div style="width: 640px">

                    <p>
                The following error just broke Matomo (v3.3.0):
            </p>
            <pre>Key &quot;description&quot; for array with keys &quot;idsite, idgoal, name, match_attribute, pattern, pattern_type, case_sensitive, allow_multiple, revenue, deleted&quot; does not exist.</pre>
            <p>in</p>
            <pre>C:\web\IA3\intel\plugins\Goals\templates\_listGoalEdit.twig line 51</pre>

            <hr>
            <h3>Troubleshooting</h3>

            Follow these steps to solve the issue or report it to the team:
            <ul>
                <li>
                    If you have just updated Matomo to the latest version, please try to restart your web server.
                    This will clear the PHP opcache which may solve the problem.
                </li>
                <li>
                    If this is the first time you see this error, please try refresh the page.
                </li>
                <li>
                    <strong>If this error continues to happen</strong>, we appreciate if you send the
                    <a href="mailto:hello@matomo.org?subject=Fatal error in Matomo 3.3.0&body=Key%20%22description%22%20for%20array%20with%20keys%20%22idsite%2C%20idgoal%2C%20name%2C%20match_attribute%2C%20pattern%2C%20pattern_type%2C%20case_sensitive%2C%20allow_multiple%2C%20revenue%2C%20deleted%22%20does%20not%20exist.%20in%20C%3A%5Cweb%5CIA3%5Cintel%5Cplugins%5CGoals%5Ctemplates%5C_listGoalEdit.twig%2051%20using%20PHP%205.6.21">error report</a>
                    to the Matomo team.
                </li>
            </ul>
            <hr/>
           <h3>Further troubleshooting</h3>
            <p>
                If this error continues to happen, you may be able to fix this issue by disabling one or more of
                the Third-Party plugins. If you don't know which plugin is causing this error, we recommend to first disable any plugin not created by "Matomo" and not created by "InnoCraft".
                You can enable plugin again afterwards in the
                <a rel="noreferrer" target="_blank" href="index.php?module=CorePluginsAdmin&action=plugins">Plugins</a>
                or <a target="_blank" href="index.php?module=CorePluginsAdmin&action=themes">Themes</a> page under
                settings at any time.

                            </p>
            <table>
                            </table>
        </div>

    </body>
</html>

**Comment by tsteur** [comment]
Have a look at https://github.com/matomo-org/matomo/issues/11327
