### ISSUE TITLE
scrollTo feature not working anymore, notifications not visible etc

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#12625]
I noticed when a notification appears, example from an API or any other request error using `piwikApi`, then the notification is never scrolled to. At first I thought it was because it doesn't wait for angular to render a notification see https://github.com/matomo-org/matomo/commit/b801546b0797a354cfb9b452cf9ade5421c5a4f4

This was not the case so I thought `$.scrollTo` is getting an element instead of a position but that's all correct as well after checking out the docs for it. So I tried various things directly like `$.scrollTo(100)` or `$.scrollTo(document.getElementById('...'), 250)` etc. and nothing worked in latest Chrome 64 on Mac.

Seeing that the library is very old I wouldn't be surprised if it is broken. I didn't test any other browsers but this is pretty annoying since you press "create" or "update" somewhere, and nothing happens. Only later when you figure out to scroll around you may notice the error notification if it hasn't disappeared by now.

**Comment by fdellwing** [comment]
There is a native Javascript method for this: https://www.w3schools.com/Jsref/met_element_scrollintoview.asp

Could you try that? Maybe it is just a bug with Chrome 64?

**Comment by Findus23** [comment]
I think this has maybe to do that the library is using an old method to scroll that seems to have been removed.
https://stackoverflow.com/questions/45061901/chrome-61-body-doesnt-scroll

But as scrolltoView() is supported by every browser, that seems to be a simple solution:
https://caniuse.com/#feat=scrollintoview

**Comment by tsteur** [comment]
If we use `scrollIntoView` need to make sure it works on IE 10+ / Edge as well but should as we wouldn't set `smooth`.  As `$.scrollTo` seems to be only used in 2 places and they are all based on a node, `scrolltoView()` should work 👍

**Comment by fdellwing** [comment]
There is no really easy way to detect if smooth scrolling is supported, but following code does it: https://codepen.io/Fyrd/pen/RrqLBE

But what to use if not supported? Use the old method and hope?

**Comment by diosmosis** [comment]
Found the issue w/ jquery.scrollTo. Here: https://github.com/matomo-org/matomo/blob/3.x-dev/libs/bower_components/jquery.scrollTo/jquery.scrollTo.js#L43 jquery.scrollTo selects the body element as the element to change the `scrollLeft/scrollTop`, which doesn't work in latest chrome. Using `documentElement`, however does work.

Unfortunately, I can't find a way to monkey patch this. But there exists a polyfill for smooth scrolling: http://iamdustan.com/smoothscroll/. Would need to test across browsers.
