### ISSUE TITLE
E-Mail reports do not get scheduled

### ISSUE THREAD

**Issue by mordilion** [matomo-org/matomo#12634]
Hi everyone, 

I planned to schedule some E-Mail reports, but unfortunately they do not get scheduled. When I click "Send report now", then it works. Just the automatic process doesn't want to work.

Had anyone the same issue and can help me with that? Is it maybe a bug?

I installed also the Plugin "Scheduled Tasks" which shows me nothing!

I am using version 3.3.0 and I haven't set up the archive cron job.

Cheers!

**Comment by mattab** [comment]
Hi there, to fix the issue can you try upgrade to the latest Matomo version?
https://matomo.org/docs/update/

if you still experience this issue afterwards, please re-open this and post a comment. Thanks!
