### ISSUE TITLE
[Matomo Website] Wrong captcha description

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#12656]
Just a small thing. This site: https://matomo.org/development/ has a captcha and it's a nocaptcha recaptcha, but the text underneath still reads: `Type in the captcha, then click ‘Send the message’ button below.`

**Comment by sgiehl** [comment]
I've removed the text below the captcha for now.
@mattab  do you think we need to add a sentence there to explain that someone needs to check the captcha?

**Comment by fdellwing** [comment]
> do you think we need to add a sentence there to explain that someone needs to check the captcha?

Just my 2 cents about this: We have a application secured with this captcha aswell and there are many many people out there having trouble with it. But on the other hand, there should not be as many uninformed people using that webform, so you might be ok.
