### ISSUE TITLE
In the Visitors in Real time widget, do not write "Keyword not defined" 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12655]
Similarly to how it looks in the Visitor Log, let's hide the keyword when it is not know, ie. let's hide `Keyword not defined` in the "Visitors in Real time" widget.

**Comment by mattab** [comment]
Also, @sgiehl let's hide the `Keyword not defined` in the Tooltip in the visitor log on hover on the search engine icon as it's creating some confusion too.

**Comment by sgiehl** [comment]
I'll include that in the referenced PR

**Comment by mattab** [comment]
@sgiehl can you confirm you removed the "Keyword not defined" tooltip in the Visitor Profile as well as Visitor log? ie. everywhere where it could be shown?

**Comment by sgiehl** [comment]
Yes. My referenced PR changes the code so Realtime log, visitor log and visitor profile now uses the same code without that tooltip.
Btw. I've just create a [PR for visitor generator plugin](https://github.com/matomo-org/plugin-VisitorGenerator/pull/31), so it also generates some visits with search engine referrers without keywords, so stuff like this is easier to test ;-)
