### ISSUE TITLE
iframe opt-in/opt-out code is not properly closed

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#12665]
Hi, after updating to 3.4.0 and checking HTML opt-in/opt-out code, the generated code looks like this:

`<iframe
        style="border: 0; height: 200px; width: 600px;"
        src="https: // ... /index.php?module=CoreAdminHome&action=optOut&language=en&backgroundColor=&fontColor=&fontSize=&fontFamily="
        >`

However, this breaks my page completely, everything below the embedded code above ends-up hidden inside the iframe. This is because the code itself for iframe is not properly closed:

`<iframe
        style="border: 0; height: 200px; width: 600px;"
        src="https: // ... /index.php?module=CoreAdminHome&action=optOut&language=en&backgroundColor=&fontColor=&fontSize=&fontFamily="
        ></iframe>`

Not sure if this is because I updated Matomo, maybe it does not happen in fresh installations. However, check if you missed the closing `</iframe>` tag in your HTML template.

Thanks!

**Comment by sgiehl** [comment]
Thanks for the report. Seems the closing tag got lost...
