### ISSUE TITLE
Update Matomo Demo screenshot image

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#12664]
image url:
https://matomo.org/wp-content/uploads/2017/01/New-logos.png

(has piwik logo on top)

Used in example url:
https://matomo.org/changelog/matomo-3-4-0/

**Comment by Findus23** [comment]
Since https://matomo.org/changelog/matomo-3-9-0/ an updated image is used:
https://static.matomo.org/wp-content/uploads/2019/03/matomo-analytics-dashboard.webp
