### ISSUE TITLE
Add woff2 fonts

### ISSUE THREAD

**Issue by DevDavido** [matomo-org/matomo#12662]
After reading the changelog for Matomo 3.4 I saw you use woff fonts. Would be nice if you could add [woff2 fonts](https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a) as well:

> The new WOFF 2.0 Web Font compression format offers a 30% average gain over WOFF 1.0 (up to 50%+ in some cases). WOFF 2.0 is available since Chrome 36 and Opera 23.

**Comment by DevDavido** [comment]
This [converter tool](https://transfonter.org/) is very useful for converting from woff to woff2.

**Comment by Findus23** [comment]
@DevDavido thanks, I have already remembered, that I can just use the official converter:

https://github.com/matomo-org/matomo/pull/12695
