### ISSUE TITLE
Extra spacing in Visitor log when visits include duplicate actions

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12671]
Discussed internally:

> the problem is aggregating the events creating whitespace:
![image2](https://user-images.githubusercontent.com/466765/38061039-fae7c582-3349-11e8-8b41-d34f4488c69a.png)

> not sure why they are set visibility hidden when it should be display:none probably 
![image](https://user-images.githubusercontent.com/466765/38060964-a6493e3e-3349-11e8-9c86-2e51bd1f14b2.png)

-> @sgiehl are you maybe able to reproduce the problem?

**Comment by sgiehl** [comment]
That is because the css counter doesn't increase when it's set to display none. Also the `height: 0; width: 0; overflow: hidden;` should hide it nevertheless... which browser are you using? For me that works fine on demo in chrome, ie and firefox. Maybe that's caused by a plugin?

**Comment by sgiehl** [comment]
@mattab I'm not able to reproduce that anywhere. Are you still able to reproduce? If so, can you give me access to that instance so I can have a closer look?

**Comment by mattab** [comment]
@sgiehl I checked and the only time I could reproduce it was when the visit includes a lot of "repeat actions". When a pageview is somehow refreshed 500 times, then there is a huge space. See below

![repeat pages](https://user-images.githubusercontent.com/466765/39415529-80466f28-4c98-11e8-8fa6-d43ca9ba7672.png)


To reproduce, could you try refresh a page 500 times, and then open the visitor profile?

Note: the problem does not occur in the visitor log.
