### ISSUE TITLE
Nothing to see here.

### ISSUE THREAD

**Issue by alphaonex86** [matomo-org/matomo#12674]
Hi,

Since I have drop eaccelerator buggy code I have my root index.php set to "Nothing to see here."
Then web site buggy.

Cheers,

**Comment by sgiehl** [comment]
I can't see what your problem has to do with Matomo. Matomo  requires it's index.php, so you can't simply overwrite it with another file.

**Comment by alphaonex86** [comment]
It's Matomo features, see: #10414

**Comment by alphaonex86** [comment]
But it happen for the root directory of Matomo. I have not test again, but it's have happen few time I have edited the bootstraps to disable the "eaccelerator disabling function". But maybe unlinked
