### ISSUE TITLE
Store widget display type when changed

### ISSUE THREAD

**Issue by DevDavido** [matomo-org/matomo#12677]
Is there any way to keep the change of the display format of widgets? For example if I go to Visitors -> Software and take a look on the Browser version widget it always gets to the default pie chart view of the data. When I change it to Simple table and reload or visit another page and come back it's again a pie chart. What are the thoughts of the community?

**Comment by Findus23** [comment]
At least for a logged-in user the display type is saved over reloads for me.

**Comment by DevDavido** [comment]
It's been probably changed within the last two years, now it works as described. 👍

**Comment by Findus23** [comment]
That's great. Thanks for replying!
