### ISSUE TITLE
Goals may be created with invalid metadata causing tracking to fail

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12683]
#### Seen in production

In at least one case we have noticed that some Goals were found to be invalid in the database:

![image](https://user-images.githubusercontent.com/466765/38114938-b80bec94-3406-11e8-8075-93ef74cf5687.png)

This unfortunately seemed to cause tracking to fail for at least some of the requests: `Error in Matomo (tracker): General_ExceptionInvalidGoalPattern`

#### Steps:

* we should check that Goals attributes values are checked and how this could have happened and how can it be prevented.
* ideally the tracker should not fail when a goal is invalid, not because these checks are removed, but because the goal is fully checked and validated at every creation/update

**Comment by sgiehl** [comment]
Are you sure those goals might not have been created using the API directly?

**Comment by tsteur** [comment]
The API should make sure no invalid values can be assigned.

**Comment by mattab** [comment]
In theory it's fixed (?) so closing it
