### ISSUE TITLE
Improve evolution graph series picker visibility

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#12680]
The position of the series picker in evolution graphs currently moves with the number of selected elements. To improve the usability it might be good to give it a fixed position either completely left or right.

![image](https://user-images.githubusercontent.com/1579355/38109010-efc83090-3396-11e8-9d03-ceef1b6a30f8.png)

![image](https://user-images.githubusercontent.com/1579355/38109041-0de233a0-3397-11e8-9f9a-f1efde937bfd.png)

**Comment by mattab** [comment]
Thanks for the report. Maybe this is something that could be done at the same time as: https://github.com/matomo-org/matomo/issues/955 where we'll introduce a very valuable icon/button to switch the graph periods from weekly to monthly/daily/yearly

**Comment by tsteur** [comment]
Be good to simply always have it on the very left.
