### ISSUE TITLE
Change widget category of Realtime Map to Live!

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#12685]
Currently all widgets showing "live" data are grouped in the widget category `Live!`, except of the realtime map. As it shows live data as well it would be expected to be in `Live!`, but actually it is shown in `Visitors`

**Comment by sgiehl** [comment]
Note: Maybe we should also think about renaming the category `Live!` to `Realtime`

**Comment by Findus23** [comment]
I think this has already been done since as they are all in the `Visitors` category, right @sgiehl?

![grafik](https://user-images.githubusercontent.com/6266037/82762260-3f745a80-9e00-11ea-9b43-a754a661b566.png)

**Comment by sgiehl** [comment]
Seems that has been fixed with #13518
