### ISSUE TITLE
Opt-Out Checkbox not showing up on mobile device

### ISSUE THREAD

**Issue by gschwepp** [matomo-org/matomo#12694]
Hello, 

the opt-out checkbox is not showing up on my mobile device. The info text is just fine as expected. 

I tried following browser on an Android 7.1.2 device:
- Chrome 65.0.3325.109 
- Firefox 59.0.2

On the desktop-versions of both browser the checkbox is present, even when I force the responsive desgin.

**Comment by fdellwing** [comment]
Can not confirm this for Lineage 14.1-20180325 with Chrome 65.0.3325.109

**Comment by gschwepp** [comment]
Interesting, I just used some mobile devices of my colleagues and I can confirm that it is working with:

Chrome & Firefox on Android 6.0.1. 

Currently I cannot publicly provide a link. I need to ask the person in charge first.

**Comment by fdellwing** [comment]
Lineage 14.1 is based on Android 7.1, so it is not a Android 7.1 problem. But as it is working with other devices, this gets really strange.

**Comment by gschwepp** [comment]
For the sake of debugging: 
https://architektinnen-initiative.de/kontakt/datenschutzhinweis/

At the bottom of the page should be the opt-out link.

**Comment by Findus23** [comment]
Just to make sure we aren't missing something obvious:
You don't have DoNotTrack enable? Otherwise Matomo won't show a checkbox (as you are already opted out), but rather the following text:
Das Tracking ist bei Ihnen derzeit nicht aktiv, denn Ihr Browser hat uns mitgeteilt, dass Sie kein Tracking wünschen.

**Comment by gschwepp** [comment]
No. I disable this for checking. 
 But it is working now. I cleared all caches on both browsers and now it is actually working. I don't really understand why and how. 

Thank you for your help. Sorry for bothering you.
