### ISSUE TITLE
DoNotTrack not recognized by matomo optout-script

### ISSUE THREAD

**Issue by xopez** [matomo-org/matomo#12701]
Hello everyone,

I noticed that on LineageOS (Android Rom) the default browser (built-in and I think its Jelly Browser) doesn't really recognize the DoNotTrack-function. I set the option in the browser and my page still says that I can Opt-Out. Other Browsers are working fine and I'm told I have the option set. Don't know it's a browser bug or not. Screens with German text, but the position where it stands is marked red.

android package name of the browser: `org.lieangeos.jelly`
useragent: `Mozilla/5.0 (Linux; Android 7.1.2; HTC One A9 Build/NJH47F) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/65.0.3325.144 Mobile Safari/537.36`

OptOut-Iframe:
`<iframe style="border: 0; height: 200px; width: 600px;" src="https://analytics.mightful-noobs.de/index.php?module=CoreAdminHome&amp;action=optOut&amp;language=de&amp;backgroundColor=&amp;fontColor=606060&amp;fontSize=100%&amp;fontFamily=Montserrat%20Regular" width="300" height="150"></iframe>`

![screenshot_20180406-131112](https://user-images.githubusercontent.com/28950736/38418662-a429957c-399d-11e8-9109-a98b7f246817.png)
![screenshot_20180406-131107](https://user-images.githubusercontent.com/28950736/38418663-a44140f0-399d-11e8-918e-ba03a0708080.png)

**Comment by sgiehl** [comment]
Are you able to figure out which headers your browser sends when DNT is enabled?

**Comment by xopez** [comment]
I can give you this with mod_log_forensic of my apache-server
```
+Wsdm3wUJi8sAAHkC5lsAAAAA|GET /datenschutzerklaerung/ HTTP/1.1|Host:mightful-noobs.de|Connection:keep-alive|Cache-Control:max-age=0|Upgrade-Insecure-Requests:1|User-Agent:Mozilla/5.0 (Linux; Android 7.1.2; HTC One A9 Build/NJH47F) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/65.0.3325.144 Mobile Safari/537.36|Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8|dnt:1|Accept-Encoding:gzip, deflate|Accept-Language:de-DE,en-US;q=0.9|Cookie:wordpress_test_cookie=WP+Cookie+check; displayCookieConsent=y; cookie_notice_accepted=true; wordpress_logged_in_******=*****; wp-settings-1=hidetb%253D1%2526editor%253Dhtml%2526libraryContent%253Dbrowse%2526mfold%253Do%2526siteorigin_panels_setting_tab%253Dgeneral%2526imgsize%253Dfull%2526advImgDetails%253Dhide; wp-settings-time-1=1522325800; _pk_ses.1.0f3b=*; _pk_id.1.0f3b=9b34ab9d69372fdf.1520610117.12.1523017436.1523016369.|X-Requested-With:org.lineageos.jelly
-Wsdm3wUJi8sAAHkC5lsAAAAA
```
LogFormat for this line in Apache:
`LogFormat "%{forensic-id}n %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined`

As you can see "dnt:1" is send.

**Comment by Findus23** [comment]
Hi, I can reproduce it with LineageOS 14.1 and `org.lineageos.jelly`.
I'll check to find out why.

**Comment by Findus23** [comment]
@xopez Which version are you using exactly?

I am having a different user agent then you
```text
yours: Mozilla/5.0 (Linux; Android 7.1.2; HTC One A9 Build/NJH47F) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/65.0.3325.144 Mobile Safari/537.36
mine:  Mozilla/5.0  (Linux; Android 7.1.2; ONEPLUS A3003 Build/NJH47F) AppleWebKit/537.36  (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile  Safari/537.36

UPDATE: 
That's fascinating: When I switch the WebView-Imprementation in the Android Developer Options from "AOSP WebView" (the open source LineageOS ones) to "Chrome Stable" it starts sending a `Dnt:1" header and `$_SERVER["HTTP_DNT"]=="1"`.

But the Opt-Out screen is still shown.

**Comment by Findus23** [comment]
@sgiehl It seems like the request even gets tracked:
https://gist.github.com/Findus23/0913c69f10c4ff5ce2a0b53e8c98ef3e

**Comment by xopez** [comment]
I am using

14.1-20180405-NIGHTLY-hiaeuhl



But also noticed it before the version.

**Comment by xopez** [comment]
yes, cause it says it didn't find DNT.
`DEBUG PrivacyManager[2018-04-06 13:40:43 UTC] [92aa0] DoNotTrack header not found`
https://gist.github.com/Findus23/0913c69f10c4ff5ce2a0b53e8c98ef3e#file-gistfile1-txt-L52

**Comment by fdellwing** [comment]
As it works fine with Chrome, this is a Jellybug, isn't it?

**Comment by Findus23** [comment]
@I'm not sure

**Comment by Findus23** [comment]
@fdellwing At least partly.

But I'm stil unsure why it isn't working when one switches to the Chrome Webview, because it sends dnt:1 and $_SERVER["HTTP_DNT"] is correctly set to "1"

**Comment by fdellwing** [comment]
I think I choosed to get rid of it for Chrome while setting up the phone. At least there is no default Browser app on my phone anymore.

**Comment by Findus23** [comment]
After a lot of debugging I have now finally found (at least part of) the solution:

I have created an HTML page with an opt-out-iframe of an non-https matomo instance (so I can proxy the request)

It turns out that the DNT-header isn't sent to pages in iFrames.
![screenshot_20180406_174951](https://user-images.githubusercontent.com/6266037/38431010-37f1ae5a-39c3-11e8-94cb-fae4e47e85db.png)

@xopez So if you could try out to directly surf to the https://yourmatomo.example/index.php?module=CoreAdminHome&action=optOut&idsite=14&language=de URL, it should correctly show the Opt-Out.

**Comment by fdellwing** [comment]
It turns out that the DNT-header isn't sent to pages in iFrames.

So, a problem with the implementation of iframe in jelly?

**Comment by Findus23** [comment]
And to fully solve the mystery and show that this has nothing to do with Matomo:

I added JS to the page to make a AJAX request, and it turns out that it also doesn't get a DNT header:

![grafik](https://user-images.githubusercontent.com/6266037/38431460-8ba7e6bc-39c4-11e8-8f93-30368b34452b.png)

Therefore Matomo has no chance to know that the user has enabled DNT and therefore tracks the user.

I'll create a bugreport to LineageOS as it seems the DNT-feature is completely useless.

**Comment by fdellwing** [comment]
@Findus23 I dont see a thread in jira, can you provide a link?

**Comment by Findus23** [comment]
They only open their bug tracker from saturday to Sunday.

**Comment by fdellwing** [comment]
Ok, if you are able to please send it to me via forum :)

**Comment by xopez** [comment]
Just post it here, so we can follow it.

**Comment by Findus23** [comment]
@fdellwing, @xopez 
The bug has been reported here: https://jira.lineageos.org/browse/BUGBASH-1552
Also a bit unfortunately that a great OS encouraging people not to depend on Google are using Google Analytics on their website.

**Comment by Findus23** [comment]
Semi-related:
I have now started a discussion about using Google Analytics:
https://www.reddit.com/r/LineageOS/comments/8aowso/please_dont_use_google_analytics/
