### ISSUE TITLE
Pagination of counties.

### ISSUE THREAD

**Issue by JDSlimz** [matomo-org/matomo#12709]
I am using the latest version of Piwik available on the Synology DSM Package Manager.

When I am on the "Locations" page, viewing the  "Countries" panel, if I select "All" from the drop-down, the "Next" button is still visible. If I click the "Next" button, the page number decrements. The image I have shows the list on page "-2" of "37" though there should be no pages at all.

![Pagination Error](https://user-images.githubusercontent.com/10407342/38572703-d53a984c-3cc1-11e8-82c1-f922a19c9f51.PNG)

**Comment by fdellwing** [comment]
Regression of #12369?

**Comment by sgiehl** [comment]
This one should be meanwhile fixed. If not, feel free to create a new issue.
