### ISSUE TITLE
In Row evolution popover may return "Call to a member function toString() on null"

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12734]
As we get emails when there are errors, we want to prevent this error from being triggered. This was only triggered once in production. 

Message: ` Error: {"message":"Call to a member function toString() on null","file":"plugins\/CoreHome\/DataTableRowAction\/RowEvolution.php","line":106}`

URL where this was reproduced: `index.php?date=2018-04-16&apiMethod=MultiChannelConversionAttribution.getChannelAttribution&label=Campaigns+%3E+%404b551fa251-email_campaign_2018_03_02&disableLink=1&module=CoreHome&action=getRowEvolutionPopover&colors=%7B%22backgroundColor%22%3A%22%23ffffff%22%2C%22lineColor%22%3A%22%23162c4a%22%2C%22minPointColor%22%3A%22%23ff7f7f%22%2C%22maxPointColor%22%3A%22%2375bf7c%22%2C%22lastPointColor%22%3A%22%2355aaff%22%7D&idGoal=0&idSite=1&period=day`

**Comment by sgiehl** [comment]
I can provide a fix to prevent that error and throw an exception instead. But I wasn't able to reproduce that error with the given URL.
