### ISSUE TITLE
Filter data dynamically in Widget by Custom Dimension

### ISSUE THREAD

**Issue by qzmenko** [matomo-org/matomo#12738]
Hello.

Is it possible to filter data in embed widget by value of custom dimension?
For example something like this:

**&customDimension1={_myDynamicValue_}**

Not found anything similar in the documentation.

**Comment by Findus23** [comment]
You can set up Segments to filter data by custom dimensions or use the segmentation feature of the API which should also work with Widgets:
https://developer.matomo.org/api-reference/reporting-api-segmentation
