### ISSUE TITLE
After upgrade to Matomo3.4  import access.log, the database have visitor logs, but in website no show  vistior logs.

### ISSUE THREAD

**Issue by huang0808** [matomo-org/matomo#12736]

**Comment by huang0808** [comment]
how to fix it?

**Comment by mattab** [comment]
Thanks for creating the issue.

**Do you have logs registered in your Matomo (Piwik) database?** If your Matomo tracking code is properly installed, Matomo would record visits in your database. To check if you have logs in your database, go to Matomo > Visitors > Visits log, and select “today” in the calendar. If you see recent visitor information, it means that the visitor tracking is working, but maybe there is a problem with reports archiving.

**If you see visits in the Visits Log but not in the reports** then please check your archiving works correctly.
-> Please review our doc here: https://matomo.org/docs/setup-auto-archiving/

This should resolve your issue. Please check and if you have any issue let us know or re-open the issue.
