### ISSUE TITLE
doTrackGoal() in the PHP API should return success or failure response, not tracking GIF

### ISSUE THREAD

**Issue by olleharstedt** [matomo-org/matomo#12739]
As title. It's unsure from the result from `doTrackGoal()` if the tracking succeeded or failed. A better response than a tracking GIF or empty string would be to prefer.

**Comment by kylekatarnls** [comment]
I had to add debug `var_dump` to get curl error and fix it.

If you get empty string and no goal tracked in your analytics, you can try to debug it by doing this:

Modify the `doTrackGoal` method after the curl_exec call: `var_dump(curl_error($ch));` to dump the cURL error.

Hope it could help.

**Comment by olleharstedt** [comment]
Tracking works for us, _but_ if it suddenly stopped working we need to be able to see this. Checking for GIF or empty result is not a convincing way to do this.

**Comment by tsteur** [comment]
@olleharstedt @kylekatarnls 
Not sure when tracking a goal would fail? You mean if you set an idGoal and the idGoal did not exist?

We could possibly return an HTTP 400 here  https://github.com/matomo-org/matomo/blob/3.13.0/plugins/Goals/Tracker/GoalsRequestProcessor.php#L87-L92

**Comment by olleharstedt** [comment]
400 is one way, returning JSON with error message and error code another.

**Comment by olleharstedt** [comment]
Nice!
