### ISSUE TITLE
Error on System Check

### ISSUE THREAD

**Issue by kordic27** [matomo-org/matomo#12747]
Hi there,
I couldn't find this issue documented anywhere, so forgive me if it has been posted (or better yet, point me to it) -- thanks.
I have installed MySQL and PHP on my server and also installed piwik to the point where I can call up the System Check Screen and it renders without issue. 
However, when I click next and it looks for action=System Check, the page times out.
I looked at the logs and it generates the following error:
[19-Apr-2018 19:11:55 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in C:\inetpub\wwwroot\piwik\core\FileIntegrity.php on line 324

Has anyone experienced this issue before? I have tested some other pages and php DOES seem to be operating properly.  

Thanks

**Comment by tsteur** [comment]
Actually, I've had it this week as well and thought my server is playing up... Are you installing from git or the downloaded zip?

**Comment by tsteur** [comment]
I just tested it again and then it was fast... just fyi

**Comment by fdellwing** [comment]
https://forum.matomo.org/t/error-while-installing-matomo/27847/2

Can anyone confirm that increasing the time helps?

**Comment by Findus23** [comment]
Maybe something in the background was using so much I/O that there was none left to run the integrity checker. (It is sometimes a bit slow as it needs to read every file of Matomo.)

If anyone is experiencing this issue, please reopen it or create a new one.
