### ISSUE TITLE
Plenty of php notices in log: Constant MAX_SERIALIZED_ARRAY_DEPTH already defined

### ISSUE THREAD

**Issue by saschafoerster** [matomo-org/matomo#12743]
I've got thousands of lines in /var/log/apache2/error.log with this PHP Notice:

`[Thu Apr 19 10:31:56.432017 2018] [:error] [pid 18644] [client *.**.12:38588] PHP Notice:  Constant MAX_SERIALIZED_ARRAY_DEPTH already defined in /var/www/html/stats/libs/upgradephp/upgrade.php on line 324`

What can I do, to debug this?

**Comment by Findus23** [comment]
The constant is only defined once in the code (in the `upgradephp` library), so I guess there was something weird happening on your server.
If anyone comes across this issue again, please create a new issue.
