### ISSUE TITLE
Safari 11.1 (13605.1.33.1.2) + default script blocks documentReady

### ISSUE THREAD

**Issue by wkwkgit** [matomo-org/matomo#12749]
Subj.

Script is default and at the page botoom, after website UI scripts, but until its load failed all documentReady functions waits for it.
<script>
	  var _paq = _paq || [];
	  _paq.push(['trackPageView']);
	  _paq.push(['enableLinkTracking']);
	  (function() {
	    var u="//stats.domain/piwik/";
	    _paq.push(['setTrackerUrl', u+'piwik.php']);
	    _paq.push(['setSiteId', '1']);
	    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
	    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
	  })();
</script>

**Comment by sgiehl** [comment]
Not sure if I got your report right. The async script loading of piwik.js blocks your documentReady event on safari? Is that reproducible for you on any other browser?

**Comment by wkwkgit** [comment]
I tried Chrome and Firefox, last and updated, they are ok, it was only Safari. The matomo server was dead (something was happend on digitalocean), and i saw this problem. I will try to make this issue more informat in free time, because to reproduce it need the server that will not response and will keep connection.

**Comment by Findus23** [comment]
In case someone can reproduce this issue in the latest Matomo version, please create a new issue with more details about what doesn't work as expected.
