### ISSUE TITLE
Cant share dashboard with other user + new user doesnt get invite

### ISSUE THREAD

**Issue by KennethJoz** [matomo-org/matomo#12758]
Hi Matomo

1.
Dashboard wont show when I try to share/copy dashboard to other user. I have done it several times on another account, but in this case it just doesnt work. What am I doing wrong?

2.
New user doesnt get his invite. Is it possible to resend the invite link?

3.
Is it possible to compare two custom segments? i.e. segments based on different URLs?

4. 
When I look at my page titles all my pages are shown twice. Can you help me why that is? And how do I fix it?

I have removed all account specific information as this seems like an open forum.

Hope this is the right way to get support. I have tried several times through your homepage...

Best regards,
Kenneth

**Comment by sgiehl** [comment]
Hi @KennethJoz 
Seems your report somehow slipped through our triaging. We have meanwhile change a lot in Matomo 

> Dashboard wont show when I try to share/copy dashboard to other user. I have done it several times on another account, but in this case it just doesnt work. What am I doing wrong?

It's only possible to copy a dashboard to as use that does have access to the site, where your user has at least admin access. Nevertheless there had been a bug around that, which was fixed.

> New user doesnt get his invite. Is it possible to resend the invite link?

The system to add/invite users has meanwhile been changed completely. So this should be possible now.

> Is it possible to compare two custom segments? i.e. segments based on different URLs?

It is now possible to compare two segments by clicking the compare button in the segment selector.

> When I look at my page titles all my pages are shown twice. Can you help me why that is? And how do I fix it?

If you still have that issue, maybe try to find some help on the forum, as this is most likely a tracking problem and no issue within Matomo.
