### ISSUE TITLE
Piwik Log Utility not parsing the log file.

### ISSUE THREAD

**Issue by jbdundas** [matomo-org/matomo#12769]
Hi,

We are trying to use the link:- https://matomo.org/docs/log-analytics-tool-how-to/ 
for parsing our access.log in our Sonarqube server logs folder. However, whenever we try to do this, it keeps giving us this error:-
-------------------------------------------------------------------------------------
0 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)

=====> Warning: File log_file=./access.log does not exist <=====

Logs import summary
-------------------

    0 requests imported successfully
    0 requests were downloads
    0 requests ignored:
        0 HTTP errors
        0 HTTP redirects
        0 invalid log lines
        0 requests did not match any known site
        0 requests did not match any --hostname
        0 requests done by bots, search engines...
        0 requests to static resources (css, js, images, ico, ttf...)
        0 requests to file downloads did not match any --download-extensions

Website import summary
----------------------

    0 requests imported to 1 sites
        1 sites already existed
        0 sites were created:

    0 distinct hostnames did not match any existing site:

Performance summary
-------------------

    Total time: 0 seconds
    Requests imported per second: 0.0 requests per second
-------------------------------------------------------------------------------------

This is the command that we use:-
$ python ./import_logs.py --url=http://hostname/piwik --idsite=4  --token-auth=<token>  --show-progress log_file=./access.log --login=XXXXXX --password=XXXXXX  --enable-static --enable-bots

Now, the import.py is present in the logs folder where the access.log is also present. However, we still get this error. 

Can you please tell us what is wrong here and how to fix it?

Thanks,
Jitesh

**Comment by fdellwing** [comment]
`=====> Warning: File log_file=./access.log does not exist <=====`

Try using an absolute path to your logfile.
