### ISSUE TITLE
Cannot declare class Piwik\\Plugins\\Maqketplace\\Marketplace

### ISSUE THREAD

**Issue by w1z0rd** [matomo-org/matomo#12762]
Hi there,

since 2 days now, my matomo fails to load with internal server error 500.
apache error log:
```
AH01071: Got error 'PHP message: PHP Fatal error: Cannot declare class Piwik\\Plugins\\Maqketplace\\Marketplace, because the name is already in use in /var/www/vhosts/matomo/httpdocs/plugins/Marketplace/Marketplace.php on line 0\n'
```

Anyone an idea what this is about?

**Comment by sgiehl** [comment]
Did you add the typo in `Maqketplace` or is that the real error message? If so maybe check if there is a plugin directory with the name `Maqketplace`

**Comment by w1z0rd** [comment]
@sgiehl There is no directory named ```Maqketplace``` and matomo worked fine for several months before  :/

**Comment by sgiehl** [comment]
I wonder where the typo comes from. It's not included anywhere in Matomo source. Maybe try reuploading the source files...

**Comment by w1z0rd** [comment]
@sgiehl I searched through all MySQL tables and checked all files with grep - no string like ```Maqketplace```. Any idea where this came from?

**Comment by w1z0rd** [comment]
@sgiehl I've reuploaded matomo's files and everything works fine now. Was my matomo hacked?

**Comment by sgiehl** [comment]
> Was my matomo hacked?

We are not aware of any security breach in matomo that would allow changing any files in latest version. 
But if you think it might got hacked it might make sense to change your passwords...

**Comment by w1z0rd** [comment]
Ok thanks then :)

**Comment by w1z0rd** [comment]
This was the very first error:

```
Matomo encoutered an error: Class 'Zend_Loader' not found (which lead to: Circular dependency detected while trying to resolve entry 'Piwik\Plugins\CorePluginsAdmin\Controller')
```

**Comment by w1z0rd** [comment]
UPDATE: Files from my installation don't differ from the latest matomo 3.4.0 files (besides tmp/ of course) :)
