### ISSUE TITLE
Invalid MySQL Version when using MariaDB

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#12772]
Guess I cheered too soon.
Since I update my Matomo server to the latest beta, I can't access the marketplace.
Whenever I try to open
`https://matomo.example/index.php?module=Marketplace&action=overview&idSite=7&period=month&date=today&activated=&mode=admin&type=&show=`
I get *An error occurred: Invalid MySQL Version*

I am using MariaDB on Debian Stable (Stretch)

```
➜  ~/tools/certbot git:(master) mysql --version
mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
```
MariaDB [(none)]> SELECT @@version;
+--------------------------+
| @@version                |
+--------------------------+
| 10.1.26-MariaDB-0+deb9u1 |
+--------------------------+
1 row in set (0.00 sec)
```

I guess this has something to do with https://github.com/matomo-org/matomo/pull/12551 as I don't think something else has changed.

@diosmosis How did you test the version string detection?

**Comment by diosmosis** [comment]
Reproduced locally, error does not occur in matomo, but when fetching this URL: `https://plugins.matomo.org/api/2.0/plugins?keywords=&purchase_type=&query=&sort=lastupdated&release_channel=latest_stable&prefer_stable=1&piwik=3.5.0-b2&php=7.1.15&mysql=10.2.14-MariaDB-10.2.14%2Bmaria%7Ejessie&num_users=2&num_websites=1`
I suppose plugins.matomo.org cannot handle the mariadb version.

CC @tsteur

**Comment by Findus23** [comment]
That explains why I can nowhere find a validator or the error message string.

**Comment by tsteur** [comment]
That's probably because we are using https://github.com/vierbergenlars/php-semver to validate the version number. I'll try to remove the `+` part automatically on the Marketplace.

**Comment by tsteur** [comment]
fixed

**Comment by Findus23** [comment]
Just tested it and it's working fine.
Many thanks Thomas!
