### ISSUE TITLE
Visitor log: do not allow to show "all" rows as it can time out

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12789]
In Visitor Log, Ecommerce log, Media log, etc. it is currently possible to select `all` in the Rows selector, meaning that all visits will be displayed in the log. 

The idea was to allow users to export "All" the visitor log data for a day. But since Matomo 3.4.0, a new export feature in https://github.com/matomo-org/matomo/pull/11958 is available, which lets user select the number of rows to export. 

Therefore, it is not needed anymore to offer "All" in the rows selector for the purpose of exporting all data. 

## The problem

For many websites, selecting "All" will actually cause Matomo to time out with the following error:

```
Error: {"type":1,"message":"Maximum execution time of 240 seconds Exceeded", 
"file":"core\/EventDispatcher.php","line":105}
at index.php?forceView=1&viewDataTable=VisitorLog&module=Live&action=getLastVisitsDetails&small=1&idSite=21&period=day&date=2018-04-24&showtitle=1&random=2790

```

 
## Suggested steps

* Remove `all` from the rows selector from the Visitor Log, Ecommerce log, Media log, etc.
* In the update, also delete all users' viewdatatable visualisations settings for Visitor log(s) where the setting includes "showing all rows". This way, any user who has already selected "All" will be reset to showing 25 rows or so by default.

As a result, we would expect a lot less timeouts triggered in Matomo.

**Comment by diosmosis** [comment]
@mattab is there still a showing all rows in non-visitor log like reports? Eg, normal table reports, actions reports.
