### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1064

### ISSUE THREAD

**Issue by ybzhaoplus** [matomo-org/matomo#12784]
My environment:
php 7.2.5
mysql: 8.0.11
matomo: 3.4.0

Here is the error: after I imported old data to newly installed MySQL 8.0.11

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '. piwik_log_visit' at line 1

**Comment by mj** [comment]
This appears to be a duplicate of #12759.

**Comment by chauffer** [comment]
Thanks for finding that @mj!

**Comment by Findus23** [comment]
Fixed by #12759 and released in 3.5.0
