### ISSUE TITLE
Matomo reports wrong mysql version

### ISSUE THREAD

**Issue by paladox** [matomo-org/matomo#12781]
Hi, if the user uses mariadb, and uses mariadb 10.0 or 10.2 it is reporting this as 5.5.5

MySQL version: 5.5.5

Could this be fixed to show the correct version please?

**Comment by Findus23** [comment]
Hi, I think this may have already been solved with  #12551.
Matomo 3.5 will show the result of 
```sql
SELECT @@VERSION
```

**Comment by paladox** [comment]
ah thanks.
