### ISSUE TITLE
Integrate the URL Builder directly into the app

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12795]
One of the most useful tools on the website is our URL Builder: https://matomo.org/docs/tracking-campaigns-url-builder/ - This tool should be used generously, as it provides an efficient way to [measure marketing campaigns](https://matomo.org/docs/tracking-campaigns/) and provide insights into conversion rates per channel.

### To make the URL builder as easy and as fast as possible to use, we need to integrate it into Matomo directly. 

-> The question remains: what would be the best way to integrate it? 

Thoughts:

* it needs to be directly accessible from the Campaigns report. 
* Maybe it could be opened in a popover on a click?

**Comment by tsteur** [comment]
> it needs to be directly accessible from the Campaigns report.

Why not add a menu item "Campaign URL builder"?

**Comment by tsteur** [comment]
For people that use it regularly, it will be much easier to use when they need to (eg one click less), it will be much easier to discover this feature, and it is more of a joy to use this feature when it is not displayed in a popover.

**Comment by tsteur** [comment]
ping @mattab
