### ISSUE TITLE
Matomo Email Tracking demographic info needed - Help Please

### ISSUE THREAD

**Issue by mydevsite** [matomo-org/matomo#12804]
I am new to Matomo and would like to use it to track my email campaigns. I understand it can generate a tracking pixel which can be inserted into a HTML email. When the email is opened it will then be noted in the Matomo Dasboard under Actions -> Page Titles… I have done this but its basic and only shows it its been opened. I need to to display more info (such as demographics, a map would be nice, device type, browser, ip address. etc) Can Matomo do this and how easy or difficult would it be to implement?

Is it possible to display my email list and show who has opened it? If so how do I do this.
Can I track demographics on the emails opened? ( ip address, country, state, city, device type, browser, etc.) if so how can I do this
Can it track forwards, clicks and reopens? If so how can I implement this.
Any assistance would be greatly appreciated. Thanks in advance

**Comment by tsteur** [comment]
Could you please ask your question in the forums? https://forum.matomo.org/

We don't answer questions here but only bug reports and feature requests.

As for demographics etc should all work out of the box, just give it a try.
