### ISSUE TITLE
Improve wording of Opt-out-iFrame text

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#12810]
Someone mentioned [on the forum](https://forum.matomo.org/t/gdpr-does-matomo-opt-out-disable-tracking-completely/28070/3) that the opt-out Iframe-text is a bit misleading:

>  You may choose not to have a unique web analytics cookie identification number assigned to your computer to avoid the aggregation and analysis of data collected on this website. 
> To make that choice, please click below to receive an opt-out cookie.

>  Sie können sich hier entscheiden, ob in Ihrem Browser ein eindeutiger Webanalyse-Cookie abgelegt werden darf, um dem Betreiber der Website die Erfassung und Analyse verschiedener statistischer Daten zu ermöglichen. 
>Wenn Sie sich dagegen entscheiden möchten, klicken Sie den folgenden Link, um den Matomo-Deaktivierungs-Cookie in Ihrem Browser abzulegen.

 The text sounds as if the opt-out only stops the tracking-cookie from being created, but still continues to track the user or as if disabling cookies in the browser will stop all tracking.

This should be worded better to avoid confusion.

**Comment by Findus23** [comment]
In addition it should be made more clear that the checkmark needs to be unticked.

See also https://forum.matomo.org/t/opt-out-iframe-wird-nicht-angezeigt/27971/5?u=lukas

**Comment by mattab** [comment]
@Findus23 Moving out of 3.5.1 as we need to release 3.5.1 this week

**Comment by Findus23** [comment]
Many people seem to be thinking that the opt-out only disables identification, but still tracks the user:

https://forum.matomo.org/t/can-you-help-me-solve-this-problem/28441
(and some more)

**Comment by Findus23** [comment]
In addition the German translation is additionally misleading as it recommends clicking on a link:
>  Wenn Sie sich dagegen entscheiden möchten, klicken Sie den folgenden Link, um den Matomo-Deaktivierungs-Cookie in Ihrem Browser abzulegen.

**Comment by mattab** [comment]
@Findus23 could you maybe fix the German translation on Transifex?

Otherwise, does anyone have a suggestion on how to improve the opt-out text?

**Comment by Findus23** [comment]
@mattab I already fixed the German translation yesterday after writing the comment.

Unfortunately I can't think of any great wording myself.

**Comment by kiusau** [comment]
I would like to propose -- if it is, indeed, accurate -- the following wording:

"By selecting the following opt-out option you deny the developer of this website the ability to track your behavior while on the site.  Please understand that in so doing you also deny the developer valuable information needed to enhance your own and others experience while on the site. 

Unless you voluntarily provide additional information the most that an any developer can ever know about you is that you are a return visitor who has visited his site and clicked on various elements from a particular geographical location at a particular time.  

Information exchange is a two-way street.  Please keep this in mind as you are taking information from the owner's site."

Matomo

**Comment by kiusau** [comment]
Modify:  Unless you voluntarily provide additional information the most that an any developer can ever know about you is that you are a return visitor who has visited his site and clicked on various elements of the site with a specific kind of device from a particular geographical location at a particular time.

**Comment by diosmosis** [comment]
Forgot about this ticket, here's a version (w/ some of @kiusau's direction):

```
You may choose to prevent this website from aggregating and analyzing your actions on this website. Doing so will protect your privacy, but will also prevent the owner from learning from your actions and creating a better experience for you and other users.

(Note: opting out here may not completely prevent your behavior from being tracked as there may be other analytics tools in use or there may be third party content that is out of this website's direct control.)

You are currently opted-in. Uncheck this box to opt-out.
```

I think this works for a default, but I think ideally we would also make this configurable so users can enter their own text.

**Comment by mattab** [comment]
I'm not sure about the bit ` (Note: opting out here may not completely prevent your behavior from being tracked as there may be other analytics tools in use or there may be third party content that is out of this website's direct control.) ` because in some cases this is not true, and webmaster know for sure there is no other 3rd party tag or tracking code. Maybe we can remove it for now and also add the feature to customise the text in "Administration > Privacy > Opt-out" ?

**Comment by diosmosis** [comment]
👍 will do
