### ISSUE TITLE
Show "Keyword not defined" on hover on the Search engine icons

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12813]
To make it clear that most keywords are not defined, when a search engine is used, we want to explicitely display "Keyword not defined" in the tooltip, in the following screen:
* Visitor logs
* Real time visits widget
* Visitor profile
* Ecommerce log, etc.

Before we used to display "Keyword not defined" explicitly, which was not useful. Then in the 3.5.0 beta cycle we've removed it and even the tooltips. But instead, we need to actually display it in the tooltips to make this useful information available.

**Comment by sgiehl** [comment]
@mattab  Do I get that right: You want to readd the tooltips that say "Keyword not defined"?

**Comment by mattab** [comment]
Correct, all search engine icons + labels should have a tooltip with the keyword, or in 99% of cases `Keyword not defined` :+1:
