### ISSUE TITLE
Transition Overlay loading eternally

### ISSUE THREAD

**Issue by thesteffi** [matomo-org/matomo#12815]
Hi,

I started getting errors when trying to open the transition overlay. It keeps on loading and in console there is a 403 shown. 

<img width="719" alt="bildschirmfoto 2018-05-03 um 13 05 13" src="https://user-images.githubusercontent.com/28928635/39573238-ab5acce0-4ed2-11e8-925c-a33a55b10058.png">

To resolve it I already tried to set file and folder permissions to 777 temporarily but the error was still not resolved. Usually permissions are set to 755 for folders and 644 for files.

I also tried switching from php 7.2.4 to 7.0.29 but that didn't help either.

Hope you can help me find the issues cause.

Best,
Stefanie

**Comment by fdellwing** [comment]
https://en.wikipedia.org/wiki/HTTP_403

So the problem is, that the webserver blocks the call. You should take a look at your webserver logs to resolve the problem.

**Comment by thesteffi** [comment]
Just solved the issue by myself by disabling the single rule by its id (340162). For everyone else struggling with this issue and using Plesk see [here](https://support.plesk.com/hc/en-us/articles/115002531753-How-to-disable-a-single-ModSecurity-rule-for-a-website-) and for everyone else just google SecRuleRemoveById. If anyone has a better solution let me know :)
