### ISSUE TITLE
matomotimestamp bug 

### ISSUE THREAD

**Issue by Vinutab** [matomo-org/matomo#12819]
Hi,

One of our application is integrated with Matomo. We have pulled the report for the visitor log and we can see the timestamp under action(timestamps are 1525255391 and 1525255392). 
The report file also contains the values firstActionTimestamp (1525248191) and lastActionTimestamp (1525248192) for the visit.
Comparing firstActionTimestamp to the timestamp of the first action (and lastActionTimestamp to the timestamp of the last action) results in a difference of 7200 seconds, which corresponds to the local time zone offset. below is the code.

[
  {
    "idSite": "",
    "idVisit": "",
    "visitIp": "",
    "visitorId": "",
    "actionDetails": [
      {
        "type": "action",
       --
        "serverTimePretty": "May 2, 2018 10:03:11",
        "pageId": 
        "timeSpent": "1",
        "timeSpentPretty": "1s",
        "generationTimeMilliseconds": "72",
        "generationTime": "0.07s",
        "interactionPosition": "1",
        "icon": null,
        "timestamp": 1525255391
      },
      {
        "type": "event",
        "--
        "serverTimePretty": "May 2, 2018 10:03:12",
        "pageId": "",
        "eventCategory": "",
        "eventAction": "",
        "interactionPosition": "1",
        "timestamp": 1525255392,
        "icon": ""
      }
    ],
    
    --
    "serverDate": "2018-05-02",
    "visitServerHour": "8",
    "lastActionTimestamp": 1525248192,
    "lastActionDateTime": "2018-05-02 08:03:12",
    "serverTimestamp": 1525248192,
    "firstActionTimestamp": 1525248191,
    "serverTimePretty": "10:03:12",
    "serverDatePretty": "Wednesday, May 2, 2018",
    "serverDatePrettyFirstAction": "Wednesday, May 2, 2018",
    "serverTimePrettyFirstAction": "10:03:11",
  
  }
]

Could you please help with this.

Regards

**Comment by Vinutab** [comment]
Hi,

We are using the Time zone: Europe/Zurich.

**Comment by Vinutab** [comment]
Hi sgiehl,

Thank you. We have changed the Timezone to UTC and it's working as expected.

Regards

**Comment by rtyshyk** [comment]
Why the issue has been closed? 
unixtimestamp is always in UTC / GMT+0.  Why timezone has an influence on timestamp?

**Comment by rudyzeinoun** [comment]
> Why the issue has been closed?
> unixtimestamp is always in UTC / GMT+0. Why timezone has an influence on timestamp?

That is true. As a workaround to compare dates when using the API, I am using PHP's "gmmktime" and giving it the current time in my timezone. This is messy. Unix timestamps are always "UTC+0" as you said.
