### ISSUE TITLE
GDPR: When consent has been given by a user, set &consent=1 in the Tracking API URL

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12834]
### Current behavior

When [a user has given their consent](https://developer.matomo.org/guides/tracking-javascript-guide#asking-for-consent), and if the user has already [opted-out (via our opt-out iframe)](https://matomo.org/faq/how-to/faq_25918/), then the requests that were consented are currently not tracked (because of opt-out). 

EDIT:    We will keep this behavior but we want to make it clear which requests were consented. Then someone could write a plugin or we could add a setting, to change and ignore the opt-out when consent is given (we'll keep it privacy by default in core).

### Maybe a solution for this is to
1. add a `&consent=1` to all [Tracking API requests](http://developer.matomo.org/api-reference/tracking-api) that were consented (for the apache logs). Should be done in JS tracker. 
1. ~~Then when checking if user is opted-out, also check that `&consent=1` was not set.~~

(refs https://github.com/matomo-org/matomo/issues/12600 https://github.com/matomo-org/matomo/issues/12767 https://github.com/matomo-org/matomo/issues/12599)

**Comment by tsteur** [comment]
This makes only sense though when Matomo users are aware to not embed the opt out iframe when using the consent feature. If the Matomo user / website owner is not aware that they are mutually exclusive, then an opted out user would not expect to be tracked.

The safe solution that respects the privacy of users more be to never track when the user has opted out. (This is the current implementation).

**Comment by mattab** [comment]
I think we at least need to know when a request was consented (eg. add `&consent=1`), this would be useful to prove that the request had indeed consent enabled.

Regarding whether to track users who have given consent + User opted-out earlier. I'd be fine keeping current behavior as this should be a rare case and therefore not very important either way.

**Comment by mattab** [comment]
> Or should we make that configurable maybe?

Possibly, can you think of a practical way to make it customisable?

**Comment by mattab** [comment]
edited the title and description:

> We will keep this behavior but we want to make it clear which requests were consented. Then someone could write a plugin or we could add a setting, to change and ignore the opt-out when consent is given (we'll keep it privacy by default in core).
