### ISSUE TITLE
 Broken referrer due to single-sign-on

### ISSUE THREAD

**Issue by Vinutab** [matomo-org/matomo#12848]
When we open the site(site A) and click a link leading to another site B.
Site B will notice that the visitor has no active single-sign-on session and redirect the visitor to the login page, which will redirect you back to site B.
The referrer is now 'site B', instead of the original site referring (site A).

Can anyone please advise.

**Comment by Findus23** [comment]
Have you seen https://matomo.org/blog/2017/02/how-to-track-single-page-websites-using-piwik-analytics/ ?

You can always set the referrer manually with 
```js
_paq.push(['setReferrerUrl', previousPageUrl]);
```

**Comment by Vinutab** [comment]
Hi,

Sorry, there was a mistake in my earlier understanding.
When we open the site(site A) and click a link leading to another site B.
Site B will notice that the visitor has no active single-sign-on session and redirect the visitor to the login page, which will redirect you back to site B.
**The referrer is now the login link of the Site B instead of the original site referring (site A).**

So setting _paq.push(['setReferrerUrl', previousPageUrl]); is providing the login link of site B.

I also tried paq.push(['setConversionAttributionFirstReferrer', true]);, in the site B tracking code, but it is still showing the referrer as login link of site B.

Can you please help.
Thanks in advance

**Comment by Findus23** [comment]
Answered here and in https://github.com/matomo-org/matomo/issues/12932#issuecomment-633235746
