### ISSUE TITLE
Matomo outlink Issues

### ISSUE THREAD

**Issue by Vinutab** [matomo-org/matomo#12847]
Hi,
In some of the pages we have links leading to pages outside the application. Few of them trigger outlinks, but few doesn't.

We have a single page application which never trigger outlinks, and the event does not produce any information about the link clicked, preventing us to see where a user went. And we would generally prefer correct outlink information, even if events are triggered.

Can anyone help with this please.

**Comment by tsteur** [comment]
Can you maybe share a link so we can check if there is a bug? I would otherwise check out https://developer.matomo.org/guides/tracking-javascript-guide#download-and-outlink-tracking

**Comment by Vinutab** [comment]
Hi,

We are using _paq.push(['enableLinkTracking']); in the tracking code. But still outlink doesn't work for few sites.

**Comment by sgiehl** [comment]
Closing this issue as there hadn't been any further activity. In general tracking normal outlinks should work as expected. There also hadn't been any similar reports, so even if there was a problem it might be meanwhile fixed.
