### ISSUE TITLE
forum signup/login via github auth -> #11590

### ISSUE THREAD

**Issue by mpaolo** [matomo-org/matomo#12845]
there's seems a regression here, I'm no more able so login to piwik/matomo via github, keeps on cycling for new account etc :/ - seems same as #11590

**Comment by Findus23** [comment]
You can try logging in via password instead as it goes to the same account as long as you use the same E-Mail address.

But at least for me Github Login is still working.

**Comment by Findus23** [comment]
Forum login should work. If it doesn't, please contact us directly or create a new issue.
