### ISSUE TITLE
PHP Fatal error:  Cannot redeclare class Piwik\\Plugins\\GeoIp2\\GeoIp2 in /var/www/piwik/plugins/GeoIp2/GeoIp2.php on line 0

### ISSUE THREAD

**Issue by mpaolo** [matomo-org/matomo#12846]
that's what I see in the ssl_error.log after latest update, and matomo/site pages are just blank.
reminds me of similar issue long ago

**Comment by Findus23** [comment]
@mpaolo I guess you are using the Matomo 3.5.0 release candidate, correct?
Did you enable the new Geoip2 plugin manually? Were you using the https://github.com/diabl0/piwik-geoip2 plugin before?

@sgiehl Did you test what happens when one is using the old Geoip2 plugin at the same time as the new version?

**Comment by sgiehl** [comment]
@Findus23 actually not with the current implementation

**Comment by mpaolo** [comment]
ATM I just renamed such GeoIp2.php to GeoIp2_php, and got matomo back working ...

@Findus23 yep, on 3.5.0-rc1, Ii think switched to GeoIP PECL time ago, don't remember Ii installed that geopi2 plugin but I see it's installed & active

thx

**Comment by Findus23** [comment]
@mpaolo Do you by chance have a `geoip2` or similar folder in `/var/www/piwik/plugins/` in addition to the `GeoIp2` folder? If so it may help removing it and disabling it in `config/config.php.ini` and then using the new Geoip2 plugin.

**Comment by mpaolo** [comment]
ok, seems the usual mismatch/interference between old/new/different implementations.
Since I'm using a different geoip module I guess I'm fine and indeed a quick test confirms geo infos are fine.
So I'll just wait for instructions.


@Findus23 : 
/var/www/piwik# locate geoip2|sed -r 's,[^/]+$,,'|sort|uniq
/var/www/piwik/plugins/GeoIP2/vendor/
/var/www/piwik/plugins/GeoIP2/vendor/geoip2/
/var/www/piwik/plugins/GeoIP2/vendor/geoip2/geoip2/
/var/www/piwik/plugins/GeoIP2/vendor/geoip2/geoip2/src/
/var/www/piwik/plugins/GeoIP2/vendor/geoip2/geoip2/src/Database/
/var/www/piwik/plugins/GeoIP2/vendor/geoip2/geoip2/src/Exception/
/var/www/piwik/plugins/GeoIP2/vendor/geoip2/geoip2/src/Model/
/var/www/piwik/plugins/GeoIP2/vendor/geoip2/geoip2/src/Record/
/var/www/piwik/plugins/GeoIP2/vendor/geoip2/geoip2/src/WebService/

**Comment by mpaolo** [comment]
oh oh, but there are:
/var/www/piwik/plugins/GeoIp2
/var/www/piwik/plugins/GeoIP2
which one is right?

**Comment by sgiehl** [comment]
`GeoIp2`. The other one is a non-core plugin, that shouldn't be used anymore

**Comment by mpaolo** [comment]
hm, so Ii moved out GeoIP2 and renamed the .php, but now the plugin is inactive and I get a waring saying -rc1 is not compat with GeoIP2 plugin

**Comment by mpaolo** [comment]
ok, things are becoming a bit messy ...
- activating the plugin stepped through database update
- then integrity check wants to remove vendor/maxmind-db/reader/autoload.php
- PECL geoip no more available, 2 verzions of geopip2 available but not installed (so it says)
- warning about to be discontinued maxmind db support etc
- went through the download&install free geoip db, then geopi2 turned 'installed'
- selected such geopi2, removed such autoload.php, GeoIP2 entries from ini file
now all seems fine, all warnings gone.
Guess we can close the issue then - thx @all :)

**Comment by sgiehl** [comment]
> then integrity check wants to remove vendor/maxmind-db/reader/autoload.php

This is a known issue. The file won't be included in next release
