### ISSUE TITLE
Issue with tracking No Result Search Keywords

### ISSUE THREAD

**Issue by Vinutab** [matomo-org/matomo#12869]
Hi,

One of our application that is integrated with Piwik is mainly used as a search engine. Hence, it is very important for us to get the exact number of times a keyword has been searched or the number of times it has produced no results. 

How can I get the number of searches for a keyword/the number of times a keyword has produced no results despite if it is from a single visit or not?

We have used the below code.
_paq.push(['setCustomUrl', document.URL + '&search_count=' + searchCount]);

Please help.

**Comment by Findus23** [comment]
If you are using JS to set the number of search results, it is probably easiest to directly use the JS API:
https://developer.matomo.org/guides/tracking-javascript-guide#internal-search-tracking

If this issue still happens to you or someone else, please reopen this issue or open a new one.
