### ISSUE TITLE
[3.5.0] archive_tar must updated to 1.4.3

### ISSUE THREAD

**Issue by tuxmaster** [matomo-org/matomo#12868]
Hello the last matomo comes with archive_tar 1.4.2, but this version fails with php 7.2
For example the download of the geoip2 data bases fails with:

> PHP Fatal error:  Cannot use result of built-in function in write context in /var/www/piwik/html/vendor/pear/archive_tar/Archive/Tar.php on line 662

This bug is also noted on the pear [site](https://pear.php.net/package/Archive_Tar/download)

**Comment by fdellwing** [comment]
Please note that PHP7.2 is still not officially supported. This should be fixed nonetheless.

**Comment by Findus23** [comment]
Oddly I am using PHP 7.2 and didn't have the issue.

**Comment by DvdGiessen** [comment]
@fdellwing What is the correct supported range of PHP version for the latest version (3.5.0 as of writing) of Matomo? As per [the documentation](https://matomo.org/docs/requirements/) and [the README distributed with the latest version](https://github.com/matomo-org/matomo/blob/3.5.0/README.md#requirements) the required PHP version is "5.5.9 or greater".

Might it perhaps be a good idea to document up till which version of dependencies Matomo was tested to work correctly for a given release? That would also ensure that the required versions are clear in the future.

If hypothetically the PHP team would release a version 8 which breaks Matomo in every way imaginable, right now we'd have to update documentation to explicitly state it is not supported. Even then, we cannot update the README files included in previous releases. If we denote the last version that Matomo was tested against, users at least have a reference as to what is supposed to work and what is something to try at their own risk.

**Comment by futureweb** [comment]
alright - until Matomo is updated to archive_tar 1.4.3 --> quick and dirty fix ...

https://github.com/pear/Archive_Tar/commit/772f7d0ffaf225d575ac1feca44eefcd4a9b144e
