### ISSUE TITLE
New report "Transitions" available under the "Actions" category

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12865]
Transitions is a fantastic report and very insightful: https://matomo.org/docs/transitions/

The idea of this issue is to make Transitions a first class citizen of Matomo and visible to all users.

### Suggested steps

* Add a new report "Transitions" below "Contents"
* The transition report is then loaded in the page (not in popover). It shows the transition for the #1 most visited page URL on the site.
* A "related report" is available to switch to "Transitions (Page titles)" which shows the #1 most visited page title  

### Out of scope but related

* in the footer, ideally we show the "Export data" icon https://github.com/matomo-org/matomo/issues/6032
* in the footer, ideally we show "Export as image" icon https://github.com/matomo-org/matomo/issues/6248

**Comment by tsteur** [comment]
would there be a select field to switch to different page urls and titles?

**Comment by mattab** [comment]
Ideally yes. 
Btw If we build this selector it could be added later it in the Row evolution popover for page report.
