### ISSUE TITLE
After Update from 3.4.0 to 3.5.0 - CoreHome can't be displayed - HTTP 500 - GeoIp2.php 

### ISSUE THREAD

**Issue by doenersoldat** [matomo-org/matomo#12867]
After the automatic update of Matomo from 3.4.0 to 3.5.0 could display the CoreHome anymore
Log said following:

AH01071: Got error 'PHP message: PHP Fatal error: Cannot declare class Piwik\\Plugins\\GeoIp2\\GeoIp2, because the name is already in use in /var/www/vhosts/path/to/matomo/plugins/GeoIp2/GeoIp2.php on line 0\n', referer: https://xxxxxxxx.de/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday

**Comment by Findus23** [comment]
Hi, 

Check out #12846
and 
https://forum.matomo.org/t/php-fatal-error-after-update-matomo-to-3-5-0/28160
for the solution

**Comment by doenersoldat** [comment]
Problem was caused by two GeoIp Installations in the Plugin Folder.
There were two folders one called "GeoI**p**2" and one "GeoI**P**2". I deleted simply the older one "GeoI**P**2". Problem was fixed

**Comment by ranjith-siva** [comment]
I had a same problem while updating Piwik(Matomo) 3.4.0 to 3.5.0 the Problem was fixed.
Because i just Renamed the folder "GeoIP2" to "GeoIP2_need_to_delete" in the Plugin Folder.  
Thanks for helping.
