### ISSUE TITLE
Missing angular and $ after upgrade to 3.5

### ISSUE THREAD

**Issue by Kolatzek** [matomo-org/matomo#12875]
After Upgrade from 3.3 to 3.5 I got a page with empty dashboard. Also settings will not show anything. 
The web developer console in Firefox 59.0.2 let me know:

`
ReferenceError: angular is not defined[Weitere Informationen]
index.php:3:13
ReferenceError: $ is not defined[Weitere Informationen]
index.php:75:9
`

Chrome:

`
index.php:3 Uncaught ReferenceError: angular is not defined
    at index.php:3
    at index.php:5
index.php:75 Uncaught ReferenceError: $ is not defined
    at index.php:75`

**Comment by Kolatzek** [comment]
Sorry, was a php timeout by ProxyHttp::compressFile().

**Comment by Indigo744** [comment]
I had the exact same issue.
While no specific information was given here on how to resolve the issue, it lead me to its solution.
I share it if someone stumble on this thread looking for a way to make Matomo/Piwik work again.

It's simple: you only need to empty the cache.
See this FAQ for more information : https://matomo.org/faq/how-to/faq_25548/
` ./console cache:clear` or delete everything inside `\tmp` folder.
