### ISSUE TITLE
See IP addresses in Real-time visitor widget 

### ISSUE THREAD

**Issue by MESWEB** [matomo-org/matomo#12876]
After update in section "Visitors in Real-time" IPs of user disappear  I can't see users IPs.
This function is not longer support or I need enable it somewhere?

**Comment by sgiehl** [comment]
The IPs are still tracked but not directly shown in the most cases. For example you can see the IP of a visit in the visitor profile by clicking the grey header of the visit on the right side

**Comment by MESWEB** [comment]
But it's possible to show it like before update?

**Comment by sgiehl** [comment]
No it isn't. But what exactly do you need the IP for? 
For me the IP is meanwhile the most irrelevant information, as it should be anonymized in the most cases and doesn't add any value to the reports.

**Comment by derfred33** [comment]
I also want to see the IP addresses of those visiting my website. I need this to cross information with the site registrations in order to properly give support.

**Comment by MESWEB** [comment]
Yes. Now matomo is more complicated when I want find visitor IP.

**Comment by mattab** [comment]
Thanks for the feedback. 

-> we wouldn't display the IP address all the time, however it would be useful to restore the Visitor IP address, so we could show it on hover instead.

@sgiehl here are my thoughts on how to modify the Real-time widget:
* add the `Visitor IP: x.y.0.0` in the tooltip on the country flag. (couldn't find a better place)
* add the `Visitor ID xyz` below in the tooltip. (a bit consistent with Visitor Log. we wouldn't need to put the "Visit ID" in the real-time widget)
