### ISSUE TITLE
php issue when auto-archiving When Your Web Host Does Not Support Cron Tasks

### ISSUE THREAD

**Issue by pioc92** [matomo-org/matomo#12881]
Hi all,
i tried to configure auto archiving of reports with url http://your-server.org/path/to/piwik/misc/cron/archive.php?token_auth=XYZ
but i have an issue in the log file `ERROR CoreAdminHome[2018-05-10 09:28:42 UTC] [9f1a9] Empty or invalid response '#!/usr/bin/env php  Warning: session_cache_limiter(): Cannot change cache limiter when headers already sent in /home/planning/sites/routeur4g.fr/matomo/core/bootstrap.php on line 32 ' for website id 1, Time elapsed: 7.696s, skipping`
I tried to update php memory_limit to 512 but the issue persists.
Could you help me?

**Comment by pioc92** [comment]
Shared hosting o2switch (french), PHP Version 7.2.5, on Linux dolphin.o2switch.net 3.10.0-714.10.2.lve1.5.15.el6h.x86_64 #1 SMP Tue Mar 27 18:09:35 EDT 2018 x86_64

**Comment by oldrup** [comment]
Exactly same problem here. Did you find a solution?

**Comment by justinvelluppillai** [comment]
I will close this. If you have further trouble here I suggest asking for help on the forums.matomo.org.
