### ISSUE TITLE
Display visitor provider in Real time widget

### ISSUE THREAD

**Issue by chron0** [matomo-org/matomo#12887]
It looks like the new visitor log widget doesn't show geoip provider information, when hovering on the flag as it used to. Can we have it back please? :)

**Comment by sgiehl** [comment]
Which geoip provider are you using? It should still show country/region/city information if it was detected

**Comment by chron0** [comment]
![screenshot_2018-05-11_06-29-23](https://user-images.githubusercontent.com/3270028/39909992-b467b0a6-54e4-11e8-9808-3198251dbf54.png)

**Comment by sgiehl** [comment]
so what exactly are you missing?

**Comment by chron0** [comment]
Looks to me like geoip is still working, only the Provider value which used to be there is gone

**Comment by sgiehl** [comment]
Ah ok. You need to configure the ISP database in order to have provider information. If you don't have a paid account on maxmind and can use the GeoIP2-ISP database, you may need to wait for next release, which will bring support for GeoLite2-ASN database (see #12874)

**Comment by chron0** [comment]
Yes, I know. And it has been working for 5+ years with piwik. Only after upgrading to 3.5.0 it looks as if someone just took it out of the template of the hover. I was trying to find the commit or file in src but no luck so far.

**Comment by sgiehl** [comment]
Ah ok. Now I got what you are meaning. Will check that.

**Comment by chron0** [comment]
Much obliged! And a hearty thanks to all who put effort into an open-source solution for us.

**Comment by chron0** [comment]
Awesome, works in 3.5.1, thanks!
