### ISSUE TITLE
System check shows issues after GeoIP2 activation

### ISSUE THREAD

**Issue by DevDavido** [matomo-org/matomo#12883]
The following error shows up in "System Check -> File integrity" after GeoIP2 gets enabled or after I switched from the old GeoIP implementation:

```
Files were found in your Matomo but we didn't expect them.
--> Please delete these files to prevent errors. <--

File to delete: vendor/maxmind-db/reader/autoload.php
```

**Comment by sgiehl** [comment]
Thanks for the report. This issue is already known.
You can remove the file manually, as it is not used. It won't be included in future releases.
