### ISSUE TITLE
[matomo.org] Link to MatomoTracker.php wrong

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#12891]
https://matomo.org/docs/tracking-api/#use-case-tracking-data-using-the-php-client: This page has a directlink to download the MatomoTracker.php -> http://demo.matomo.org/index.php?module=SitesManager&action=downloadPiwikTracker&idSite={$IDSITE}&piwikUrl=http://piwik.example.org/

But the file it downloads is not very helpful.
```php
<?php
/**
 * Piwik - free/libre analytics platform
 *
 * @link http://piwik.org
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 *
 */

// PiwikTracker.php is now managed by composer. To prevent breaking existing
// code, this file has been left as a redirect to its new location in the
// vendor directory.
if (!class_exists('PiwikTracker')) {
    require_once __DIR__ . '/../../vendor/piwik/piwik-php-tracker/PiwikTracker.php';
}

if (PiwikTracker::VERSION !== 1) {
    throw new Exception("Expected PiwikTracker in libs/PiwikTracker/PiwikTracker.php to be version 1 for keeping backward compatibility.");
}
```
Instead it should link to https://raw.githubusercontent.com/matomo-org/matomo-php-tracker/master/PiwikTracker.php or https://github.com/matomo-org/matomo-php-tracker/releases/latest

(Or you could rework the Action if you really want to)

**Comment by tsteur** [comment]
@fdellwing I think I fixed this, can you double check please?

**Comment by fdellwing** [comment]
Well there is the link to the github repo for some days now, so it seems fixxed for now?

**Comment by tsteur** [comment]
thx
