### ISSUE TITLE
IP address of client not visible

### ISSUE THREAD

**Issue by regor2** [matomo-org/matomo#12893]
In the latest version, 3.5.0, the visitor IP was removed from the Real-Time Widget. This is unfortunate for an number of reasons including that, without the IP, the widget only tells me that people are hitting my site: that is it. Before, I could tell if it was just me hitting the site or someone else on my intranet, or, a vistor from the outside. When I open the Visitor Profile, their IP is not there either!

Does anyone else see value in the IP of the visitor? It seems to me that that is the simplest, most valuable identifier on the WWW.

Thank you for all the work you do.
Roger

**Comment by tsteur** [comment]
I think it should definitely be added again at least to the visitor profile 👍

**Comment by Findus23** [comment]
Hi @regor2 

See also https://github.com/matomo-org/matomo/issues/12876

The IP-Address is still visible on the visitor logs by clicking on the gray headers. And https://github.com/matomo-org/matomo/pull/12884 will reintroduce them on the Dashboard widget.

> It seems to me that that is the simplest, most valuable identifier on the WWW.

Because of this you will need to ask your visitors for consent if you want to store it non-anonymized and your visitors are from the EU.

**Comment by tsteur** [comment]
> Because of this you will need to ask your visitors for consent if you want to store it non-anonymized and your visitors are from the EU.

Is this why the IP is hidden? The IP is still being collected no matter if it is shown or not. And it is partially still shown in various screens so I wonder why it would be hidden there?

**Comment by Findus23** [comment]
@tsteur I think it was just hidden to be able to use the limited space for other information, correct @sgiehl?

**Comment by regor2** [comment]
If I'm correct, #12884 will add the IP to the tooltip and the visitor profile. I see that there is not any other optionality in the widget, but I was wondering if it would be possible to optionally add add the IP where it was before. But, if it is in the tooltip, it may not be hard for users to modify the code/write an addon to bring it back to where it was previously. It is up to you all of course though...

**Comment by n3rve** [comment]
This was the only reason why I preferred Matomo over GA. Is there anyway the former view can be restored? If not, I'm going to have to downgrade until the new version re-introduces this feature.

**Comment by tsteur** [comment]
@regor2 I meant speaking of Matomo Plugins see https://developer.matomo.org/develop . They are based on PHP/JS and you can use them to enrich the UI, add new reports, etc.

**Comment by regor2** [comment]
@tseur Thanks, that's clear: I guess I have some learning to do on the JS side of things. Cheers, rm
