### ISSUE TITLE
Monolog\Logger not found

### ISSUE THREAD

**Issue by Li-An** [matomo-org/matomo#12899]
Hello, I’ve updated Matomo and it asks to delete some directories and files. I did it and it’s now broken with the message **Class ‘Monolog\Logger’ not found**.
I’ve reuploaded all the files without any difference.

**Comment by sgiehl** [comment]
This class should be included in the vendor directory.
Does the error message include some kind of backtrace where the error occurred?

**Comment by Li-An** [comment]
There is no other message. See capture.

![](https://framapic.org/bxdGPCUa478R/jvr77VCfgOGr)

**Comment by Findus23** [comment]
Without any more details it is hard to know what causes this warning. If it still occurs, please reopen this issue or create a new one.
