### ISSUE TITLE
Cant fetch event category data

### ISSUE THREAD

**Issue by bluemanos** [matomo-org/matomo#12908]
I have a problem with fetching most of a data from API.

http://localhost:8080/index.php?module=API&method=Events.getCategory&idSite=6&period=range&date=2018-01-01,2018-01-31&segment=eventAction==PublicationReadingDuration&format=json&token_auth=9ee59c92cc717332a56d0fed157ac54c
Above URL is working fine - I’m using it to fetch list of events.
![image](https://user-images.githubusercontent.com/9991002/39989375-0d7bd4ce-576a-11e8-9285-23d3d1685b6f.png)

But when I want to get data for specify eventCategory, I’m getting empty array :confused:
http://localhost:8080/index.php?module=API&method=Events.getCategory&idSite=6&period=range&date=2018-01-01,2018-01-31&segment=eventAction==PublicationReadingDuration;eventCategory==industrikatalog-bog-nr-4-jop4tn&format=json&token_auth=9ee59c92cc717332a56d0fed157ac54c
![image](https://user-images.githubusercontent.com/9991002/39989394-1835e2c4-576a-11e8-83e6-4c8e7c7d6819.png)

And next magic for me is that for some other eventCategory the data is returning correctly
http://localhost:8080/index.php?module=API&method=Events.getCategory&idSite=6&period=range&date=2018-01-01,2018-01-31&segment=eventAction==PublicationReadingDuration;eventCategory==special-styrkerne-i43qh9&format=json&token_auth=9ee59c92cc717332a56d0fed157ac54c
![image](https://user-images.githubusercontent.com/9991002/39989411-202fce22-576a-11e8-8fac-28ffe89fd30b.png)

What’s wrong?
core:archive run and finish successful.

PS.
I’m using Matomo 3.3.0.

**Comment by tsteur** [comment]
At first I was thinking this is maybe related to https://github.com/matomo-org/matomo/issues/11900 but might not be as it seems to work in the last example. It seems to be related to eg typo in the segment, or some configuration setting regarding but seems unlikely as it works in the last case.

Does http://localhost:8080/index.php?module=API&method=Events.getCategory&idSite=6&period=range&date=2018-01-01,2018-01-31&segment=eventCategory==industrikatalog-bog-nr-4-jop4tn&format=json&token_auth=9ee59c92cc717332a56d0fed157ac54c  return results?

**Comment by bluemanos** [comment]
One more thing

Not working:
http://localhost:8080/index.php?module=API&method=Events.getCategory&idSite=6&period=range&date=2018-01-01,2018-01-31&segment=eventAction==openPDF;eventCategory==industrikatalog-bog-nr-4-jop4tn&format=json&token_auth=9ee59c92cc717332a56d0fed157ac54c

Working:
http://localhost:8080/index.php?module=API&method=Events.getAction&idSite=6&period=range&date=2018-01-01,2018-01-31&segment=eventAction==openPDF&secondaryDimension=eventCategory&filter_pattern_recursive=industrikatalog-bog-nr-4-jop4tn&expanded=1&format=json&token_auth=9ee59c92cc717332a56d0fed157ac54c

Main difference is as you see the second API use `&method=Events.getAction` instead `&method=Events.getCategory`. Of course the two methods return a different data structure, but `subtable` property is what I'm looking for.
In above example I used `eventAction==openPDF`, but this works as well for other `eventAction`'s.

**Comment by mattab** [comment]
This issue may be fixed now in 3.12.0-rc: https://matomo.org/faq/how-to-update/faq_159/
See #14761 #11900 - could you maybe check and let us know @bluemanos ?

**Comment by sgiehl** [comment]
Closing as it should meanwhile be fixed.
