### ISSUE TITLE
Feature request: support geo csv from db-ip.com

### ISSUE THREAD

**Issue by mxmilkb** [matomo-org/matomo#12904]
Similar to #11049, database from https://db-ip.com/db/download/city

**Comment by sgiehl** [comment]
We currently only support databases from maxmind.

**Comment by m-cameron** [comment]
@Findus23 In the article, it mentioned to refer to IP2Location. Where can we find it?

@sgiehl Is IP2Location LITE in the core?

**Comment by sgiehl** [comment]
@m-cameron no. Only Maxmind GeoIP databases are currently supported. But there is a plugin on marketplace to support IP2Location

**Comment by mattab** [comment]
we'll probably stop using Maxmind soon, and replace with db-ip, if our tests prove successful. refs #15308

**Comment by sgiehl** [comment]
@mattab we won't implement support for the CSV version of dp-ip, but their GeoIP2 version.

**Comment by mattab** [comment]
Indeed, we won't support CSV, so will close this issue. See progress in #15308
