### ISSUE TITLE
Allow to rollback database upgrade to a previous version

### ISSUE THREAD

**Issue by clement-michelet** [matomo-org/matomo#12906]
Hi,

I deployed 3.4 using docker compose on a server. When the 3.5 was released, update has been done using the automatic update button and the database has been upgraded.
After a container update, Matomo rollback to 3.4 leaving the tool in a non-usable state with the error message about an update in progress (code: `ExceptionDatabaseVersionNewerThanCodebase`).

While the best solution would be to have an updated container to latest version, a command to rollback database upgrade would allow to quickly restore the tool.

**Comment by MorbZ** [comment]
Same problem here. Please update the Docker image on time, it's been almost a week since the 3.5 release.

**Comment by mattab** [comment]
Thanks for the feedback. Unfortunately we likely won't implement a rollback system in Matomo. For Docker related issues please use the project issue tracker to contact maintainers: https://github.com/matomo-org/docker/issues
