### ISSUE TITLE
Email header bar: let developers customise the background color and font color

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12919]
In our [scheduled emails](https://matomo.org/docs/email-reports/) and in custom alerts emails we send, we now display our Header bar with logo and link to the dashboard:

![scheduled report](https://user-images.githubusercontent.com/466765/40091102-e0cd4722-5909-11e8-8530-c3bd75595ec4.png)
![custom alert](https://user-images.githubusercontent.com/466765/40091104-e0fff5aa-5909-11e8-8d88-9b0d4fc7fd9d.png)

-> The goal of this issue is to make the header bar font color, and header bar background color, ideally re-use the existing colors from the App header bar. 

cc @tsteur

**Comment by diosmosis** [comment]
Header bar color should respect matomo theme
