### ISSUE TITLE
In Visitor Log, only the country is displayed for the location of new visits

### ISSUE THREAD

**Issue by rlizzi** [matomo-org/matomo#12915]
I upgraded to version 3.5.0.  In the Visitor Log, the location of each visitor is shown beneath the IP address. For visits prior to the upgrade, the location is shown with the most precision available (city), and if I mouse over the location, I get the full location (city, state, country). For visits after the upgrade, only the country is shown, and when I mouse over, I get no more information. So something went wrong; the location detail is now missing for new visits.

**Comment by sgiehl** [comment]
Please check your geolocation settings in matomo if additional location information isn't detected properly anymore.

**Comment by mattab** [comment]
Hi @rlizzi - feel free to open a separate issue for this request (although it is on purpose we show only city (or region, if no city was detected))
