### ISSUE TITLE
PHP Fatal error: GeoIP2 name already in use

### ISSUE THREAD

**Issue by HealingRooms** [matomo-org/matomo#12916]
There is a problem after the upgrade from 3.2.1. to 3.5.0 which may be related to the following MySQL error message:

PHP Fatal error: Cannot declare class Piwik\Plugins\GeoIp2\GeoIp2, because the name is already in use in /home/......../public_html/piwik/plugins/GeoIp2/GeoIp2.php on line 0

This error message is logged when the dashboard page is attempted to be loaded.

**Comment by fdellwing** [comment]
Please remove the old GeoIP2 Plugin (from the Marketplace) as Matomo 3.5.0 brings it own GeoIp2 Plugin.

**Comment by HealingRooms** [comment]
Please clarify how I might resolve this (removing the GeoIP Plugin just for Matomo / Piwik) independently of the Matomo dashboard… unless you’re suggesting that it needs to be done from the cPanel dashboard, which would disable the GeoIP Plugin elsewhere on the website (which would be inappropriate).

Bryce Morrison
Healing Rooms Ministries
support@healingrooms.com
(509) 456-0517 ext. 218
Tu-Th 8:00 – 4:00 PST (GMT-8)

**Comment by sgiehl** [comment]
You need to remove the folder `plugins\GeoIP2` within the matomo directory. Matomo should now contain  `plugins\GeoIp2` which should provide full support for GeoIP2 databases from Maxmind. But you may need to reconfigure your geo location settings within Matomo.

**Comment by Findus23** [comment]
And you may need to remove `GeoIP2` from the `config/config.ini.php`

See also https://github.com/matomo-org/matomo/issues/12846

**Comment by HealingRooms** [comment]
Thank you. The deletion of the two (2) GeoIP2 folders did the trick.

/plugins/GeoIp2
/plugins/GeoIP2

I had commented out their reference in the config/config.ini.php file as well.

**Comment by Findus23** [comment]
Keep in mind that if you also deleted the new implementation (`GeoIP2`), geolocalisation will be broken if you stop using the old geoip.

**Comment by sgiehl** [comment]
@HealingRooms  you should reupload the GeoIp2 plugin from the release package as Matomo might not work properly without it.
