### ISSUE TITLE
GDPR - API

### ISSUE THREAD

**Issue by maximilienborne** [matomo-org/matomo#12917]
Hello,
Do you provide methods through the API to get, delete or export data from a specific user or just the interface ? 
We need to purge every data of a user each year automatically.
Thank you

**Comment by mattab** [comment]
Currently the API is not documented good enough so quite hard to use probably. We'll improve that in a next release

**Comment by mattab** [comment]
Also, we may change the API signature so it's kinda on purpose we havent' documented it yet

**Comment by Findus23** [comment]
closing in favor of https://github.com/matomo-org/matomo/issues/15160 (documenting the GDPR tools API)
