### ISSUE TITLE
GDPR settings is config.ini.php

### ISSUE THREAD

**Issue by pleaded** [matomo-org/matomo#12920]
Hi there,

Thank you for the rapid support of GDPR.

Could you please provide information how to enable particular (or all) GDPR features for anonymisation of user_ids and order_ids in Matomo before its run instead of enabling it during the runtime in UI? 
Is there an appropriate config option in .ini.php that controls these features? or specific row in the database?

Solved: its stored in the database.

**Comment by tsteur** [comment]
You can call the API method `PrivacyManager.setAnonymizeIpSettings($anonymizeIPEnable, $maskLength, $useAnonymizedIpForVisitEnrichment, $anonymizeUserId = false, $anonymizeOrderId = false)` after you set up the instance. See https://developer.matomo.org/api-reference/reporting-api

You can tweak the DB also directly but this may change over time. Check the option table with prefix Privacy Manager see https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/PrivacyManager/Config.php#L31-L61
