### ISSUE TITLE
Translations may be loaded twice during each request

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#12923]
You can reproduce this likely by calling eg `Plugin\Manager::loadAllPluginsAndGetTheirInfo()`.

I presume that initially we maybe only load translations for activated or installed plugins or something. Then when calling this method we might load more plugins compared to initially causing `$translation->addDirectory()` to be called which in return invalidates translations and causes a re-fetch of all translations. 

The workaround be to maybe always load all translations of even disabled plugins maybe? (it should be maybe already implemented as we once said this is behaviour we want to have AFAIK).

**Comment by sgiehl** [comment]
Not sure if always loading all translations is that good. For example a plugin could overwrite another plugins translations for any reason. That might not make sense if the plugin is not active

**Comment by tsteur** [comment]
OK all good. I'm thinking this issue actually rarely occurs so we don't need to do anything.
