### ISSUE TITLE
Scheduled reports use different from: header thus mails are rejected

### ISSUE THREAD

**Issue by andi-makandra** [matomo-org/matomo#12926]
Hi,

I have an installation with most recent matomo 3.5.0 and have the issue that scheduled reports aren't working. The reason for that is, that the from: header is incorrect and differs from the correct one which is used when I use the manual report.

The setup is with a postfix at an AWS instance.

I have some output (modified to hide internal infos)

The scheduled report which doesn't work:

> 
> May  7 06:01:12 aws-matomo postfix/smtp[27428]: 1234567890: to=foo@bar.de, relay=relay.example.de[1.2.3.4]:25, delay=0.97, delays=0.03/0/0.93/0.01, dsn=5.0.0, status=bounced (host relay.example.de[1.2.3.4] said: 553 #5.1.8 Domain of sender address <root@ip-172-XX-XX-XX.eu-central-1.compute.internal> does not exist (in reply to MAIL FROM command))
> May  7 06:01:12 aws-matomo postfix/cleanup[27417]: 1234567890: message-id=<1234567890@aws-matomo.example.de>
> May  7 06:01:12 aws-matomo postfix/bounce[27455]: 1234567890: sender non-delivery notification: 2234B7DB7B
> May  7 06:01:12 aws-matomo postfix/qmgr[18644]: 1234567890: from=<>, size=2861, nrcpt=1 (queue active)
> May  7 06:01:12 aws-matomo postfix/qmgr[18644]: 1234567890: removed

Hier das manuelle:

> May  7 14:49:42 aws-matomo postfix/cleanup[2725]: 1234567890: message-id=<1234567890.1234567890@aws-matomo.example.de>
> May  7 14:49:42 aws-matomo postfix/qmgr[18644]: 1234567890: from=postmaster@correctdomain.de, size=1008477, nrcpt=1 (queue active)
> May  7 14:49:42 aws-matomo postfix/smtp[28974]: 1234567890: to=foo@bar.de, relay=relay.example.de[62.116.166.112]:25, delay=0.92, delays=0.02/0/0.51/0.39, dsn=2.0.0, status=sent (250 ok:  Message 1234567890 accepted)
> May  7 14:49:42 aws-matomo postfix/qmgr[18644]: 1234567890: removed

As you can see the relevant diff is the **from=** part. 

I already tried to use **noreply_email_address = "noreply@correctdomain.de"** but didn't change anything. So I'm uncertain why the scheduled report doesn't use the same from Header as the manual one. Thanks!

**Comment by andi-makandra** [comment]
Still the same with 3.5.1

**Comment by mattab** [comment]
Isn't this a configuration issue rather than Matomo issue, or is something making you think it's an issue in Matomo?

**Comment by andi-makandra** [comment]
Could be, but then I would encourage to improve the documentation for the automatic reports :) I have another update, when I use the direct SMTP settings it also works for the automatic ones. So this is a "workaround" which is quite ok. But would still be interesting to see why the manual report works without the dedicated smtp settings and the automatic report doesn't. I would expect that both use the same source to  gather the informations needed.

**Comment by mattab** [comment]
It's now documented in: https://matomo.org/faq/troubleshooting/faq_34856/
Assuming this is enough and we don't need to do more?
