### ISSUE TITLE
Impress and privacy in footer for login-page

### ISSUE THREAD

**Issue by marove2000** [matomo-org/matomo#12938]
Hello Everybody,

du to the new GDPR it is necessary to link the impress and privacy notes on every page, even if it is only a login page. This is the case for the Matomo Backend. Right now there is no possibility to change the template, add a impress or privacy-note to the footer.

Ideal: It should be possible to add custom pages to Matomo to be shown in the footer.

Is there any workaround for this?

Regards

**Comment by sgiehl** [comment]
At the moment it would already be doable to add footer links on the login page by writing a simple custom plugin.
Main plugin file would look like this:
```php
<?php

namespace Piwik\Plugins\FooterLinks;

class FooterLinks extends \Piwik\Plugin
{
    public function getListHooksRegistered()
    {
        return [
            'Template.loginNav' => 'loginNav',
        ];
    }

    public function loginNav(&$content, $pos) {
        if ($pos == 'bottom') {
            $content .= '| <a href="/imprint">Imprint</a>';
        }
    }
}
```

**Comment by marove2000** [comment]
Thanks for this Workaround :). A implementation in Main would be great anyways.

**Comment by tsteur** [comment]
Moving it for now to 3.6.0 as I reckon it won't be doable in 3.5.1 which will be likely in a few days.

**Comment by tsteur** [comment]
When anonymous access (public access) is enabled, we should also give users the ability to enter a privacy URL.

The same applies for exported widgets. eg maybe people could append a URL parameter with a link to a privacy URL or configure a privacy policy URL **PER SITE**?

**Comment by mattab** [comment]
likely we wouldn't need to define a privacy policy *per site*. Since in theory a same company/entity is responsible for the whole of Matomo, the entity/business' privacy policy would apply.

> When anonymous access (public access) is enabled, we should also give users the ability to enter a privacy URL.

Where would we display the privacy policy link in this case? In the top menu bar maybe under `Privacy`? Only when "anonymous" view access is enabled?

**Comment by tsteur** [comment]
> likely we wouldn't need to define a privacy policy per site. 

It was just if they embedded the widgets in different websites and wanted to apply the same policy across the same website maybe. Then it would be possible. But it could be always doable eg by setting only one URL, and then maybe allowing to pass another privacy URL by a URL parameter or something maybe (although this could be also misused maybe). One URL could be fine for the start.

For public access we would maybe show it on the very bottom of the page
![image](https://user-images.githubusercontent.com/273120/40506011-257b4e50-5fea-11e8-862d-99b6323959e7.png)
 
For widgets maybe as well?

**Comment by mattab** [comment]
@tsteur (not sure about displaying it in embedded widgets, might be too much..)


### Goal of this issue

To summarise we want to do the following:

* Allow Super user to define a **Privacy policy** link URL 
* Allow Super user to define a **Terms and conditions** link URL
* Show a link to the Privacy policy, and Terms and conditions, in the **Login** page footer
* When anonymous access (public access) is enabled, also display both links in the bottom of all reporting + admin pages (or maybe below the left menu?)


Any feedback?

**Comment by tsteur** [comment]
> not sure about displaying it in embedded widgets, might be too much.. 
I would say there would need to be at least an option as some might have requirements to show eg privacy policy link on each page... and people might not always embed a widget but link to it etc

> When anonymous access (public access) is enabled, also display both links in the bottom of all reporting + admin pages (or maybe below the left menu?)
Probably at the bottom so it also works for "all websites" etc. and could be reused some logic for widgets /exported dashboard etc

Later, when implementing the feature to send an email to a user (or invite user instead of directly adding a user), then we would also show the links in that mail.

**Comment by mattab** [comment]
New settings are available in Administration > General Settings > PrivacyManager
![privacymanager](https://user-images.githubusercontent.com/466765/44697965-1452b080-aa4c-11e8-96d0-55d7513557e5.png)
