### ISSUE TITLE
After update to 3.5, widgets are not loaded

### ISSUE THREAD

**Issue by stuartkondziella** [matomo-org/matomo#12933]
We updated to 3.5 yesterday. When I now try and look at visitor logs from this month or yesterday, I get an "Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Piwik administrator for assistance."

We checked the error log and after adjusting some smaller things, it now says everything is working fine, however, we still have the problem with the widgets not being loaded and the error notification being shown.

The following output is from the error log:
2018/05/18 09:38:03 [error] 25464#25464: *1117 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 8192 bytes) in /var/www/clients/client1/web93/web/core/DataTable/Row.php on line 69
PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 32768 bytes) in /var/www/plugins/CorePluginsAdmin/Controller.php on line 1" while reading response header from upstream, client: 91.54.177.35, server: ****.***.org, request: "POST /index.php?date=today&forceView=1&viewDataTable=VisitorLog&module=Live&action=getLastVisitsDetails&small=1&widget=1&filter_limit=-1&idSite=1&period=month HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php7.0-fpm/web93.sock:", host: "s*****.*****.org", referrer: "https://****.*****.org/index.php?module=CoreHome&action=index&idSite=1&period=month&date=today"

Browser: Chrome (Version 66.0.3359.181)
OS: Windows 10
![screenshot](https://user-images.githubusercontent.com/32926065/40223544-b5a98148-5a83-11e8-8a21-c277696375b2.PNG)

**Comment by sgiehl** [comment]
please remove the widget and readd it to the dashboard. Seems you had chosen to show all available records. That might get too huge for the visitorlog and thus exceeds the memory limit. Afaik we already removed the option to choose all records for that report to prevent the error...
