### ISSUE TITLE
piwik.js JS Error in Firefox < 6 and Opera < Opera 11.60

### ISSUE THREAD

**Issue by MichaelHeerklotz** [matomo-org/matomo#12936]
As documented here: https://www.w3schools.com/jsref/met_document_addeventlistener.asp
"The useCapture parameter became optional in Firefox 6 and Opera 11.60 (has always been optional for Chrome, IE and Safari)"

These two lines are missing the default "useCapture " value of "false":

https://github.com/matomo-org/matomo/blob/7751aeb30ee64807c7de347767adfd616a224b60/js/piwik.js#L1295
https://github.com/matomo-org/matomo/blob/7751aeb30ee64807c7de347767adfd616a224b60/js/piwik.js#L5480

**Comment by Findus23** [comment]
FYI: The lines have been added in https://github.com/matomo-org/matomo/pull/10522
