### ISSUE TITLE
Need information regarding Unique visits

### ISSUE THREAD

**Issue by Vinutab** [matomo-org/matomo#12946]
Hi,

Currently we are using visitor id in our applications. If we would like to track the users we can use the user id's. Will it provide the unique users? or does it behave like the same way as the visitor id?

**Comment by sgiehl** [comment]
User IDs allows tracking unique users across devices. By default each device is counted as new unique user. If the same User ID is set on multiple devices it will only be counted as one unique visitor.
See https://matomo.org/docs/user-id/ for more information about User IDs
