### ISSUE TITLE
Please change wording of "You are currently opted in."

### ISSUE THREAD

**Issue by gwire** [matomo-org/matomo#12954]
When we added the opt-out iframe in the past we received a complaint that we were asserting consent where no consent had been given. This was due to the message in the opt out frame defaulting to "You are currently opted in." the first time it is displayed (before the user has had a chance to opt out).

While the wording doesn't have any impact in how we actually regard the data collection, it is now more important to communicate that we do not regard a lack of response as positive consent. (e.g. [GDPR section 32](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32016R0679) states "Silence, pre-ticked boxes or inactivity should not therefore constitute consent.")

Therefore I feel that is it safer to express the status (in english) as "not opted out" rather than "opted in".

```json
      'YouAreOptedIn' => 'You are not currently opted out.',
```

Related #12810

**Comment by tsteur** [comment]
Sounds better 👍 

I wonder: When someone opts out, but later basically opts in again, would it require another message like "You opted in"?

**Comment by electric-paper** [comment]
I have created a pull request. This changes the current YouAreOptedIn into the text given here.
https://github.com/matomo-org/matomo/pull/13187
