### ISSUE TITLE
Geoip2 geolocation lookup is slow

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12955]
We got a report which says: " it seems that it takes 0.08 seconds per request for it to lookup the GeoLite2-City.mmdb file, which is about 1.589 days of lookups based on the queue size in my earlier message."

This is for a customer using QueuedTracking who has 1.7 million requests in the queue and the queue doesn't process, likely because the Geoip2 lookup is too slow.

-> we need to investigate/profile the speed of Geoip2 lookup and figure out how long it takes and whether it regressed from Geoip1 in terms of performance.

Can we improve the performance in some ways? cc @sgiehl @diosmosis

**Comment by sgiehl** [comment]
Maxmind provides a PHP extension that should improve performance.

**Comment by sgiehl** [comment]
The reason why the lookup is "slow" is quite simple to explain. Each tracking request is handled in a separate process, which opens the mmdb file for lookup. Opening the mmdb and reading the metadata takes a while. The only way to speed up the lookup would be to handle everything in one process, so the mmdb only needs to be opened up once.

**Comment by diosmosis** [comment]
Does the PHP extension also create a new process?

**Comment by fdellwing** [comment]
Not a C profi, but looking at the readme it should be able to provide one global reader and query this reader every time?

global
```php
use MaxMind\Db\Reader;

$reader = new Reader('GeoIP2-City.mmdb');
```

query
```php
$foo = $reader->get($ipAddress);
```

Or are you not able to do this because you cannot access a preinstanced reader in the piwik.php calls?

**Comment by mattab** [comment]
> The only way to speed up the lookup would be to handle everything in one process, so the mmdb only needs to be opened up once.

@sgiehl @diosmosis How do-able is it to make this change and improve performance when QueuedTracking is used?

**Comment by diosmosis** [comment]
@mattab Do you know if they're using the PHP reader now? Do you know what they were using w/ GeoIP v1?

**Comment by mattab** [comment]
They're using the default code we provide (no PHP extension) @diosmosis

**Comment by diosmosis** [comment]
Even before?

**Comment by sgiehl** [comment]
@mattab one reason why GeoIp Legacy might be slower: GeoIP Legacy did not include any IPv6 data. GeoIp2 includes all IPv6 data. That's a lot more data...

**Comment by mattab** [comment]
Could we maybe profile the code and get to the bottom of the issue / understand exactly the slowness and if it can be improved?

**Comment by sgiehl** [comment]
I just ran a simple benchmark by running 40.000 dynamic IP lookups within my virtual machine.

With default PHP library without the extensions we have:
Requests per second: 67.4305675507       (0,01483 s / req)

With the extension installed:
Request per second: 17707.655926848     (0,000056 s / req)

So everyone who want's to run fast lookups should install the extension. There is nothing we can improve that much to get such a speed improvement like the extension.

**Comment by mattab** [comment]
Thanks @sgiehl - very useful...
Since customer is waiting for our instructions, could you please propose doc for our FAQs about geolocation so they match the Geoip2 tool?  Maybe this FAQ should be updated to include these instructions?  https://matomo.org/faq/how-to/faq_164/

**Comment by sgiehl** [comment]
@mattab I have updated the FAQ to describe how to install the extension. Maybe you could have a look and maybe check if it's easy enough to understand...

**Comment by tsteur** [comment]
Could the FAQ entry also cover how to get notifications when there is an update of the extension available and that it needs to be recompiled when changing PHP version etc? If possible, that would be great as it is important to keep the extensions up to date re bugfixes etc and to eventually avoid random issues etc.

**Comment by tsteur** [comment]
Also I suggest to write a blog post about this, and maybe we mention it in the next newsletter in the "did you know" section as it can cause major problems to many Matomo's the performance break. Also in the release changelog should mention it.

**Comment by tsteur** [comment]
Should we create separate issue for the blog post and the newsletter entry?

**Comment by mattab** [comment]
> I just ran a simple benchmark by running 40.000 dynamic IP lookups within my virtual machine.

@sgiehl Could you please paste the benchmark script you ran? we'd like to run it in production on the powerful box and see how it behaves there. 

Also, can you compare Geoip1 lookup VS Geoip2 (no extension) on your virtual machine?

**Comment by sgiehl** [comment]
```php
<?php

require_once './vendor/autoload.php';

use GeoIp2\Database\Reader;
use GeoIp2\Exception\AddressNotFoundException;

$reader = new Reader('misc/GeoLite2-City.mmdb');
$count = 40000;
$startTime = microtime(true);
for ($i = 0; $i < $count; $i++) {
    $ip = long2ip(rand(0, pow(2, 32) - 1));
    try {
        $t = $reader->city($ip);
    } catch (AddressNotFoundException $e) {
    }
    if ($i % 1000 === 0) {
        echo $i . ' ' . $ip . "\n";
    }
}
$endTime = microtime(true);

$duration = $endTime - $startTime;
echo 'Requests per second: ' . $count / $duration . "\n";
```

should be runable directly in Matomo home dir.

**Comment by tsteur** [comment]
will this do the "heavy" work each time? or is there anything cached?

**Comment by sgiehl** [comment]
It only opens geoip database once. so it only measures the time needed for each lookup. While tracking the database might get opened for each request (if not using queued). So that comes on top. But maybe that's not the case when using the extension. 

Guess that can be easily tested when moving the `$reader = ...` in the `for`...

**Comment by tsteur** [comment]
We are basically trying to figure out how it compares GeoIP1 vs GeoIP2 to know if we need the extension or not. Ideally we wouldn't need the extension.

**Comment by sgiehl** [comment]
Here's the same script to benchmark geoip legacy with city database:

```
<?php

require_once './libs/MaxMindGeoIP/geoipcity.inc';

$geoip = geoip_open('./misc/GeoIPCity.dat', GEOIP_STANDARD);

$count = 40000;
$startTime = microtime(true);
for ($i = 0; $i < $count; $i++) {
    $ip = long2ip(rand(0, pow(2, 32) - 1));
    $t = geoip_record_by_addr($geoip, $ip);
    if ($i % 1000 === 0) {
        echo $i . ' ' . $ip . "\n";
    }
}
$endTime = microtime(true);

$duration = $endTime - $startTime;
echo 'Requests per second: ' . $count / $duration . "\n";
```

For my local instance that results in:

Requests per second: 1710.4010527379    (0,000584658 s / req)

so compared GeoIP2 is much faster with the extension, but a lot slower without the extension.

**Comment by tsteur** [comment]
and fyi I tried to install the extension as described on https://matomo.org/faq/how-to/faq_164/ through git, but there is a `cd libmaxminddb` missing and `./configure` doesn't work.

**Comment by diosmosis** [comment]
You have to run `./bootstrap` (it's in the git repo README).

**Comment by sgiehl** [comment]
I've improve the FAQ and mentioned the additional commands needed when cloning from git

**Comment by tsteur** [comment]
What about the blog post announcement?

**Comment by tsteur** [comment]
I will probably draft something otherwise...

**Comment by sgiehl** [comment]
A blog post has been published. Should we maybe add a more visible note in the description of the provider that it is "slow" without the extension?
Otherwise guess we can close this issue, as there is imho not much more we could do about

**Comment by tsteur** [comment]
I think notice is not needed actually.

**Comment by mattab** [comment]
The article: [Thinking about switching to GeoIP2 for better location detection? Here’s what you should know](https://matomo.org/blog/2018/06/thinking-about-switching-to-geoip2-for-better-location-detection-heres-what-you-should-know/)
