### ISSUE TITLE
[GDPR Tools] Segmentation dropdown misses custom dimensions

### ISSUE THREAD

**Issue by simonschaufi** [matomo-org/matomo#12962]
While it is possible to select my custom dimension in the dashboard, I couldn't find it in the GDPR Tools segmentation filter as well. I guess this was just forgotten while implementing it. 

Could the custom dimensions also be included so I can delete all visits by a custom dimensions name/value?

Thank you so much for these awesome tools!

**Comment by tsteur** [comment]
Custom Dimensions (and Goals) etc are per site. Therefore you need to select a specific site to see them. It won't work for all websites. Note: They are shown under Visitors/Actions just fyi

**Comment by simonschaufi** [comment]
Thank you for the hint. I see it now ;)
