### ISSUE TITLE
Update Geoip FAQs and Docs to explain Geoip2 (and remove docs about Geoip1)

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12964]
Let's update the following Guides & FAQs:

* [x] https://matomo.org/faq/how-to/faq_164/
* [x] https://matomo.org/faq/how-to/faq_163/
* [ ] https://matomo.org/faq/how-to/faq_166/ 
* [ ] https://matomo.org/faq/how-to/faq_165/
* [x] https://matomo.org/faq/how-to/faq_180/
* [x] https://matomo.org/faq/how-to/faq_167/
* [x] https://matomo.org/docs/geo-locate/

So they reference Geoip2 instead of Geoip. We can then remove the Geoip1 doc I would say (it will still be in the archive.org history if needed).

**Comment by sgiehl** [comment]
updated the first one. will try to tackle the remaining ones the coming days

**Comment by sgiehl** [comment]
I've updated some more faqs/docs. Remaining ones are about setting up apache/nginx modules. Not sure if that's something I'm able to describe well, but I'll give it a try tomorrow.

**Comment by mattab** [comment]
Thanks @sgiehl - let me know if it's do-able to update the remaining FAQs. If not do-able maybe we can delete them otherwise...

**Comment by sgiehl** [comment]
@mattab  Those are the docs for installing the modules:

https://maxmind.github.io/mod_maxminddb/
https://github.com/leev/ngx_http_geoip2_module/blob/master/README.md#installing

We currently link to those pages within Matomo. Not sure if it's worth to rewrite their READMEs and add a small part how to configure the variables in Matomo

**Comment by mattab** [comment]
maybe it makes sense to simply link to these resources from the FAQ?

**Comment by sgiehl** [comment]
@mattab  I've updated the FAQs. They are now mainly mentioning the links. Feel free to remove them if they don't have enough value anymore.

**Comment by mattab** [comment]
Thank you for updating FAQs and the guide, looks good to me :+1:
