### ISSUE TITLE
GDPR Data Subject Tool: Allow finding a user only through visits segment

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#12976]
We should only allow and only show segments that are based on the `log_visit` table.

All other segments should usually not be needed anyway to identify a data subject. And if so, it could be later still done potentially through the visitor log and segmentation. Although I doubt it is needed.

Why? Because this DB query will query over all visits, joining a segment with `log_link_visit_action` (or other tables) can not only take a really long time to find the data subjects, it could even result in the worst case maybe in temporary tables etc.

I think it would also make the tool slightly easier to use by showing only more relevant segments.

@mattab any chance to have this in 3.6.0?

**Comment by mattab** [comment]
:+1: Good call
