### ISSUE TITLE
File integrity check on maxmind autoload.php

### ISSUE THREAD

**Issue by ejouvin** [matomo-org/matomo#12981]
- Version: 3.5.0
- Operating System: Ubuntu
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:
Download package from http://builds.matomo.org/piwik-3.5.0.tar.gz
Install the application.
On integrity check the file vendor\maxmind-db\reader\autoload.php is marked as unexpected, even if it comes from the package.

**Comment by Findus23** [comment]
Hi, this is an bug in 3.5.0 and has already been fixed. See also https://github.com/matomo-org/matomo/issues/12883
