### ISSUE TITLE
After clicking "Check for updates" button, the "zen menu" icon is displayed twice

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#12990]
When there is a new update available, and one clicks "Check for updates" button, then the Zen mode icon is displayed twice:

![screenshot from 2018-05-25 13-43-56](https://user-images.githubusercontent.com/466765/40542759-c71b7ef6-6021-11e8-9643-d7e72658c330.png)

**Comment by fdellwing** [comment]
This is not a new bug, it is at least since 3.4.0.

Wanted to just report this bug as well, so you got me by like 30mins ;)
