### ISSUE TITLE
Show less unknowns in devices/brands reports

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#12999]
There are usually many "Unknown" devices/brands due to the inability to detect the device/brand of a desktop computer. We can't eliminate all the unknowns, but we can try to reduce their number by:

* Introduce a "Generic Desktop" device type and device brand that is used if the device is a desktop. Since most of the unknowns are like desktops, this should put a big dent in the number.
* For brands, if the OS == Mac, assume the brand is Apple.

CC @mattab @sgiehl @tsteur

**Comment by tsteur** [comment]
👍

**Comment by sgiehl** [comment]
> For brands, if the OS == Mac, assume the brand is Apple.

That is already done by device detector since last release. See https://github.com/matomo-org/device-detector/commit/bb137a76700aedcf297a39c85d39e13136abba5d

**Comment by sgiehl** [comment]
I would suggest to simply hide the `Unknown` for the brand list. For device models I would introduce a `Generic $type` for most device types. Maybe group mobile, phablet and tablet together to `Generic mobile device` as we often only can detect if it is a mobile or desktop device based on the OS

**Comment by diosmosis** [comment]
I think #13015 fixes this (only brands have large unknown visits now, and may not ever be possible to detect those), will close.
