### ISSUE TITLE
Matomo falsely says a segment will be preprocessed when browser archiving is disabled & enforced

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13000]
When you configure segments with "real time archiving" and only later enable "enforce disable browser archiving" so that segments are only processed during cli archiving, then it still shows "AND 1 RESULT IS AVAILABLE, USE UP AND DOWN ARROW KEYS TO NAVIGATE.SEGMENTED REPORTS ARE PRE-PROCESSED (FASTER, REQUIRES CRON)" for these segments even though they are not being pre-processed.

You can reproduce this by creating a regular segment "processed in real time". Then add the following config settings:

```ini
[General]
browser_archiving_disabled_enforce = 1
enable_general_settings_admin = 0
enable_browser_archiving_triggering = 0
```

This is not only problematic when people enable this setting later, but it could be also problematic when moving / migrating a DB to another Matomo where this setting is disabled.

**Comment by tsteur** [comment]
Or alternatively, Matomo needs to actually pre-process all segments.

**Comment by mattab** [comment]
Good find!

> Or alternatively, Matomo needs to actually pre-process all segments.

For now I would just fix the bug itself. Maybe we could also actually pre-process all segments eventually (but let's create another issue).

**Comment by tsteur** [comment]
We'll implement that when `browser_archiving_disabled_enforce = 1` we archive all segments. It's easiest fix and most user friendly.

**Comment by sgiehl** [comment]
Just looked through the code and if I see that correctly that was already implemented I think with #15499
@diosmosis is that correct?

**Comment by diosmosis** [comment]
@sgiehl I don't think so, if a segment is set to processed in real time and `browser_archiving_disabled_enforce = 1`, then core:archive shouldn't launch it. Would be easy to change though, I think the change would be in SegmentArchiving.

**Comment by sgiehl** [comment]
Isn't that what this code should do:
https://github.com/matomo-org/matomo/blob/85e665e70d9fd38acda2c70767d25b800dc97a45/core/CronArchive/SegmentArchiving.php#L318-L321

**Comment by diosmosis** [comment]
Yes, which means this has been implemented for quite a while. Tested locally and it works as @tsteur describes, so I'll close this for now.
