### ISSUE TITLE
No reports generated for 1 site

### ISSUE THREAD

**Issue by kaplun** [matomo-org/matomo#13006]
Hi! I am running `import_logs.py` in a pipe to continuously import extended Apache logs from 2 websited. One is lighter (1 event/second on average), the second one is more used (200 events/second).

I run `core:archive` cronjob every hour.

Now: reports do appear for the lighter site, while they do not appear for the heavier one (unless I force by hand `core:archive`.

I haven't found any particular errors in the log, but I am open to suggestions on how to debug this.

**Comment by mattab** [comment]
Makes sense that you need to run `core:archive` to get reports to show up. 
for a large site, it won' work to "browser trigger archiving" so you'll need to setup the cron Please check: https://matomo.org/docs/setup-auto-archiving/

**Comment by kaplun** [comment]
I am using the `core:archive`. The issue seems to be that the job is so long that it doesn't finish within one hour.
Also it leads to all sorts of memory issues with the DB. I guess this is the reason why it was been killed.

**Comment by mattab** [comment]
@kaplun I understand. We could help you make it work great (we do this for our customers of our on-premises support subscription, see: https://matomo.org/support/ ). Otherwise as a quick workaround, try running the core:archive less often

**Comment by kaplun** [comment]
Sorry to abuse this ticket: I was wondering: if I rotate my logs after 7 days (to keep DB fit), will it still be possible to have monthly and yearly reports?
