### ISSUE TITLE
307 Internal Redirect

### ISSUE THREAD

**Issue by Aftabnack** [matomo-org/matomo#13018]
Hi,

We are using matomo to track our SPA. Kudos on creating this amazing tool!!
I'm running into a issue off late.
On every client side route navigation I'm setting a bunch of data and calling `trackPageView`.

```javascript
    window._paq.push(['setUserId', username]);
    window._paq.push(['setTrackerUrl', url + 'piwik.php']);
    window._paq.push(['setSiteId', '13']);
    window._paq.push(['setCustomUrl', window.location.href]);
    window._paq.push(['trackPageView']);
```

It tracks couple of actions as soon as I enter the application. But post that every route navigation it makes a request which returns with a status of `307 Internal Redirect` and that action doesn't get tracked!

Any idea about what the problem is?

My Setup:

![screenshot from 2018-05-31 12-40-14](https://user-images.githubusercontent.com/15635777/40767324-d7664fea-64cf-11e8-9c82-8b11b9facc10.png)

**Comment by Aftabnack** [comment]
Here is my network tab filtered for piwik requests

![screenshot from 2018-05-31 13-00-43](https://user-images.githubusercontent.com/15635777/40768374-c406b43c-64d2-11e8-805d-3ea12ad83724.png)

And here is the visitor log entry on Piwik dashboard

![screenshot from 2018-05-31 13-00-57](https://user-images.githubusercontent.com/15635777/40768404-d709db68-64d2-11e8-8b14-b1d4b8b7b1a6.png)

**Comment by Aftabnack** [comment]
Sorry to bother. But this is since I had a chrome extension blocking third party trackers!

**Comment by Aftabnack** [comment]
Should this be documented somewhere on the matomo website?
I searched all over the internet why 307 is happening.
There should be a note somewhere mentioning that ad blockers could mess with tracking!

**Comment by mattab** [comment]
Never heard before of a 307 request, not sure where this comes from. Adblockers already mentioned in our faq: https://piwik.org/faq/troubleshooting/faq_58/

**Comment by Aftabnack** [comment]
I'm using `Ghostry` chrome extension. This somehow intercepts all my outgoing requests to piwik, and responds with a 307.

This is a screenshot of how it looks.
![screenshot from 2018-05-31 18-03-01](https://user-images.githubusercontent.com/15635777/40782495-2649b49e-64fd-11e8-86dc-38b5d3341829.png)

**Comment by Aftabnack** [comment]
Maybe I should have just searched for Matomo and Ghostery which would have redirected me to that FAQ. 
I was looking for "307 Internal Redirect" with "Piwik/Matomo" which obviously took me nowhere.

Thought this can also be mentioned somewhere accessible. The probability of people looking into their network tab to see what the error is will be small. But devs like me can't resist to dig in. :smile:
