### ISSUE TITLE
Error when attempting fresh install 

### ISSUE THREAD

**Issue by Joseph310** [matomo-org/matomo#13014]
Hello,

I am trying to install Matomo in a system. I downloaded the newest version from the website and copied it onto the server. Then I open the /analytics subfolder in a browser - just like always, but now I get the following error: 

`Matomo encoutered an error: An exception has been thrown during the rendering of a template (".submit is undefined: failed at `.submit;` line: 1699"). (which lead to: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO))`

The server is running nothing special with the php version 5.6.35.

What could be the problem?

Thanks
- Joseph

PS: there is also a typo in the error message: "encouNtered"...

**Comment by Findus23** [comment]
Thanks for mentioning the type. Seems like it has been there for quite a while:
https://github.com/matomo-org/matomo/blob/1aba0f2ba6d437097d49ff47073f3523fbacafb3/core/FrontController.php#L91

You issue isn't related to Matomo. Your SQL server tells you that the Username/Password is incorrect.

```
Access denied for user ''@'localhost'
```

You can edit it in the `config/config.ini.php` or delete it if you want to start the setup from the beginning.

**Comment by Joseph310** [comment]
It is a fresh install - I havn't even seen the setup scripts. I don't have a `config.ini.php` in the folder. Should I edit the 
`[database_tests]
host = localhost
username = "@USERNAME@"` 
section of the global.ini.php?

**Comment by mattab** [comment]
Try re-upload all files, maybe some files were not uploaded correct. Thanks for reporting the typo, will be fixed in https://github.com/matomo-org/matomo/pull/13020

**Comment by Joseph310** [comment]
Tried that - same error. Can I copy/paste the `config.ini.php` from a different installation and modify it by hand, or do other files also get changed during the setup-process?
