### ISSUE TITLE
Not showing Geo ISP/ASN database information

### ISSUE THREAD

**Issue by tpimpao** [matomo-org/matomo#13013]
The free ASN database not displaying any information. 
The plugin detect both databases.

_"Note: This GeoIP implementation has access to the following types of databases: City, ISP Database. "_

**Comment by sgiehl** [comment]
Would you check the API response of this request on your instance:

http://demo.matomo.org/index.php?module=API&method=UserCountry.getLocationFromIP&ip=212.44.43.3&format=JSON&provider=geoip2php&token_auth={authtoken}

**Comment by tpimpao** [comment]
Hi @sgiehl 
The API is working:

[{"continent_name":"Europe","continent_code":"EU","country_code":"GB","country_name":"United Kingdom","city_name":"Linton","lat":52.1,"long":0.267,"postal_code":"CB21","region_code":"CAM","region_name":"Cambridgeshire","isp":"Redcentric Managed Solutions Limited","ip":"212.44.43.3"}]

The widget for provider must be enable? In Location page not appear the provider widget.

Thanks,
TP

**Comment by sgiehl** [comment]
Is the provider plugin enabled?

**Comment by tpimpao** [comment]
damn! 
Enabling now... 
Sorry @sgiehl
