### ISSUE TITLE
Show the "Row icons" such as Transitions, Overlay, etc. on hover also when the table has many rows

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13021]
Earlier we had removed the display of Row icons when a report table has many rows. We did this to prevent performance issues. However it is a confusing behaviour where users don't understand why the icons are not visible (and often we also forget why). So it would be great to restore the standard behavior of showing our super valuable row icons, in all rows, even when there are many rows. 

(If there is still a performance issue, we can hopefully investigate why and find a solution to it)

**Comment by tsteur** [comment]
Yes there is still a performance issue cause no change was made to it.

**Comment by mattab** [comment]
:ok: so we would need to solve the performance issue, which hopefully will be possible. For now not scheduled as we have many other priorities, but it will be good to have later

**Comment by mattab** [comment]
This was fixed recently :tada:
