### ISSUE TITLE
global(.ini).php in local PIWIK_USER_PATH not updated (composer)

### ISSUE THREAD

**Issue by flexjoly** [matomo-org/matomo#13037]
Hi,

We update matomo with composer and host a central piwik/matomo, with local config files for each directadmin account. 

The constant 'PIWIK_USER_PATH' is set to the right config-dir inside an user-account. That works fine!

Matomo also needs 'global.php' and 'global.ini.php' to be in this local dir. In the above configuration these file are not updated, when composer updates the central matomo. 
Since it is adviced NOT to change these global files, what is the purpose of keeping them in a local user-path? 

This issue could be fixed if these file would be (also) loaded from the central matomo. Or that you could change the absolute paths in bootstrap.php.
Same for common.ini.php > here an option to set the path would be best, so you can have a own central common.ini.php somewhere else on your server.

When looking into the code of matomo, I see that the config files are chained. 
Why not have a chain like, load:
- from matomo vendor dir: /config/config.ini.php (holds the global (updated) settings)
- if exists /your/global/path/to/global/config/config.ini.php  > instead of common.ini.php
- PIWIK_USER_PATH/config/config.ini.php

Can this be changed in matomo? 
Or what can we do to have the global files inside the central matomo-dir?

Thanks in advance, flexjoly

**Comment by tsteur** [comment]
Totally agreed 👍 I'm planning on changing this
