### ISSUE TITLE
Placeholder for SiteUrl is displayed incorrectly

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13035]
related to #11279

Those are really low-priority nitpicks but good issues for beginners. 

When adding a new website, the placeholder is shown in one line instead of two lines. 

![screenshot_20180605_095225](https://user-images.githubusercontent.com/6266037/40962574-2e8c18b6-68a6-11e8-9d60-90803f6aec66.png)

This is caused by the spaces here:

https://github.com/matomo-org/matomo/blob/918ef6f92c9a44be67fc8d11442f6eefd925e781/plugins/WebsiteMeasurable/Settings/Urls.php#L44

In addition an placeholder URL like `https://siteURL.example/` should be shown as the current text is a real URL.

**Comment by sunsplat** [comment]
I'd like to work on this

**Comment by fdellwing** [comment]
@sunsplat There is a PR for this -> #13036

But if you find a solution that is not ignoring the W3C paper it will be preferred.

**Comment by Findus23** [comment]
@sunsplat If you are interested, we have many more Matomo-Beginner-Friendly issues you could try to tackle:
https://github.com/matomo-org/matomo/labels/help%20wanted
