### ISSUE TITLE
Missing Morpheus icons via composer

### ISSUE THREAD

**Issue by flexjoly** [matomo-org/matomo#13030]
Hi,

We use composer to get matomo in our projects. 
For a while now, some icons are missing. As far as I can see it is due to the icons-dir in Morpheus-plugin which is empty. 

I read https://github.com/matomo-org/matomo/issues/11617, but this won't fix it for us, since we use the official composer package. 

How do we get the icons back?

Thanks in advance, 
flexjoly

**Comment by Findus23** [comment]
Hi,

If you want to use Matomo from this git repostitory you need to do some steps that are already automated on the build.
https://matomo.org/faq/how-to-install/faq_18271/
Especially you need to checkout all submodules using `git submodule update --init --recursive`.

I am not sure if setup only via composer is supported.

**Comment by flexjoly** [comment]
Hi,

Thanks for your reply....
But we don't use Matomo from the git repo.... So I cannot do this inside composer....

**Comment by Findus23** [comment]
I can't think of a way to use all Matomo dependencies with Matomo. 

So I'd recommend you to either use the build from https://builds.matomo.org/ or use git as explained [here](https://matomo.org/faq/how-to-install/faq_18271/).

**Comment by flexjoly** [comment]
I looked again to #13030 ....

https://packagist.org/packages/piwik/
https://packagist.org/packages/matomo/

Then all the composer users would miss these icons or have to do some special action with git.... because only these icons are missing.... Maybe they even don't use git.....
As far as I know you cannot use git inside the composer-dirs, for the need to be ignored by git....
So that cannot be the solution, I think....

So i guess the composer-package is not complete. Or if it is not maintained then there should be a notification in packagist about that. 
But when looking through the issues here, there are tasks to update the composer packages: see #12645, #12519, #12518

**Comment by flexjoly** [comment]
Images en fonts etc are all there, only the icons are missing.... :-(
Makes no sense....

**Comment by Findus23** [comment]
Hi,

The reason why the icons aren't there is that they are a completly seperate project (https://github.com/matomo-org/matomo-icons) that is included as a submodule.

You should also be missing `misc/log-analytics` which is also a submodule.

**Comment by flexjoly** [comment]
Oh ok!!
Thanks, I wil look into that!

**Comment by creativecoder** [comment]
There is a work around for this, you can see an example in https://github.com/creativecoder/piwik-heroku/blob/master/composer.json

Basically you need to manually define the sub repos, like `matomo/matomo-icons`, in the `"repositories"` section of your composer.json file, and require them as dependencies in your project. Then add a `"post-install-cmd"` in composer.json that copies the dependent packages into the correct folders within `vendor/piwik/piwik`.

**Comment by heitorsilva** [comment]
My work around was:
Going inside `plugins/Morpheus`, deleting empty icons folder, cloning https://github.com/matomo-org/matomo-icons.git, renaming the folder from `matomo-icons` to `icons`.
