### ISSUE TITLE
Provider/ISP to URL conversion breaks when ISP ends with "com"

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13045]
Another beginner friendly bug:

When I click on the ISP `Rostelecom` it wan't to go to `http://www.rostelecom/` as it thinks the providername is an URL ending with `com`. As many ISPs are called telecom I guess this could happen quite often:
https://github.com/matomo-org/matomo/blob/9243b9a7b6fae8237596f76cda1fe8b6816463af/plugins/Provider/Provider.php#L82-L84
https://github.com/matomo-org/matomo/blob/9243b9a7b6fae8237596f76cda1fe8b6816463af/plugins/Provider/Provider.php#L118-L126

PS: This code was added in def7586305ef208ec0456e5840cb239a25ff9124 11 years ago!

**Comment by sunsplat** [comment]
I would like to work on this!

@Findus23 where do you click on the ISP in the web interface?

**Comment by Findus23** [comment]
Hi, 

That’s perfect!

You can see the url in the visitor log and location report. 

https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday#?idSite=3&period=day&date=yesterday&category=General_Visitors&subcategory=Live_VisitorLog
https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday#?idSite=3&period=day&date=yesterday&category=General_Visitors&subcategory=UserCountry_SubmenuLocations

but I think the best place to fix this are the lines I linked to above. 
You may also want to take a look at https://developer.matomo.org/guides/getting-started-part-1

**Comment by justju** [comment]
Hi,

I don't think it's the `com`-ending. This seems to happen with providers, that only have no spaces.

![test](https://user-images.githubusercontent.com/33963037/41790069-ade3d0d2-7651-11e8-88e1-807031b70dcf.PNG)

**Comment by sunsplat** [comment]
I found the issue here:
```
function getHostnameUrl($in)
{
    if ($in == DataTable::LABEL_SUMMARY_ROW || empty($in) || strtolower($in) === 'ip') {
        return null;
    }

    // if the name looks like it can be used in a URL, use it in one, otherwise link to startpage
    if (preg_match("/^[-a-zA-Z0-9_.]+$/", $in)) {
        return "http://www." . $in . "/";
    } else {
        return "https://startpage.com/do/search?q=" . urlencode($in);
    }
}
```
Removing:
```
if (preg_match("/^[-a-zA-Z0-9_.]+$/", $in)) {
        return "http://www." . $in . "/";
    } else {
```
will solve the problem, but I don't know if this is good long-term solution. 

I think it will take refactoring a bit to get the IP passed in and using gethostbyaddr() to get the url for the provider. This way, it should work no matter the url extension.

@Findus23  Is there a way I can test my change by adding test providers? Are providers saved to the db somewhere?

**Comment by justju** [comment]
How about changing the regex to be more specific, e.g.:
`^[-a-zA-Z0-9_.]+\.[-a-zA-Z0-9_]+$`

This should match if there is at least a Second-level domain followed by a dot and a Top-level domain after.
