### ISSUE TITLE
No data for a date range of two adjacent days

### ISSUE THREAD

**Issue by KaiNissen** [matomo-org/matomo#13047]
We recently upgraded our instance from 2.17.1 to 3.5.1. Since then, we can’t retrieve any data in any module when defining a date range of two adjacent days (e. g. Dec 1st to Dec 2nd). Extending the date range to three days, or retrieving data for a single day or a whole week works, though.

Strangely enough, this problem occurs for date ranges that are more than two weeks before the current date.

I already [started a thread](https://forum.matomo.org/t/28632) in the forum, but got no response so far.

**Comment by mattab** [comment]
Hi @KaiNissen 
Could you please confirm whether this issue is fixed for you in the latest version of Matomo or if you still experience this?

**Comment by KaiNissen** [comment]
We're still running 3.5.1. We can do an upgrade in January and keep you updated.

**Comment by KaiNissen** [comment]
We just upgraded to 3.8.1 and are not able to reproduce this anymore. Date ranges of exactly one day don't return report data, but I consider that an edge case. Thank you for your support!

**Comment by tsteur** [comment]
Awesome, thanks for letting us know
