### ISSUE TITLE
Any document on downgrade Piwik Database?

### ISSUE THREAD

**Issue by yangboz** [matomo-org/matomo#13040]
After upgrading Piwik to Matomo, try to migrate the docker of  bitnami/mariadb_piwik  to another machine, but meet this error message as following:
```
Your Piwik codebase is running the old version 3.2.1 
and we have detected that your Piwik Database has already been upgraded to the newer version 3.5.1. 
Maybe your Piwik administrators are currently finishing the upgrade process.
Please try again in a few minutes.
 If you still have this issue please contact your Piwik administrator for assistance.
```
How to handle this situation? TIA.

**Comment by Findus23** [comment]
Hi,

The only way to downgrade Matomo is to rollback to a backup you made before the upgrade.
Database migrations only work in one direction as they e.g. have to convert country codes.

The best solution would be replacing your Matomo files with the latest version (3.5.1)

**Comment by yangboz** [comment]
And after "replacing your Matomo files with the latest version (3.5.1)", but it still require me to phpar/composer installation, any configuration to skip this step, because I used docker-compose version. Thanks again.

**Comment by Findus23** [comment]
Are you using the version from https://builds.matomo.org/?
You shouldn't need to run composer with them as all dependencies are already installed.

**Comment by yangboz** [comment]
Sorry, I used this onehttps://github.com/matomo-org/matomo/releases/tag/3.5.1, then I will try another.
Thanks.

**Comment by yangboz** [comment]
Bad things still, even used https://builds.matomo.org/piwik-3.5.1.tar.gz:
```
Welcome!

Matomo is a free/libre web analytics software that makes it easy to get the information you want from your visitors.

This process is split up into 8 easy steps and will take around 5 minutes.
```
Any other suggestions?

**Comment by Findus23** [comment]
Did you copy over your `config/config.ini.php`?
https://piwik.org/docs/update/#the-manual-three-step-update

Otherwise you will have to go through the setup again, but when you enter the database details where an existing Piwik database exists (pay attention to the table prefix, it is probably `piwik_` for you) it will keep the existing data.

**Comment by yangboz** [comment]
Oh, great! I copied this "config/config.ini.php" to the piwik-3.5.1 folder and skipped this step successfully, many thanks your help and thunder-alike quick reply.

**Comment by yangboz** [comment]
And also it helpful  people how to use docker-compose to upgrade/migrate your Piwik2 to Matomo3 ?
check here:https://github.com/benkoo/TensorCloud/blob/master/Volumerize/README.md
