### ISSUE TITLE
when select segment Explore traffic no data in user flow

### ISSUE THREAD

**Issue by huang0808** [matomo-org/matomo#13054]
@nbezzala @bangpound @znerol @dandv @Sija when select segment Explore traffic no data in user flow. anyone who meet this issuse?

**Comment by mattab** [comment]
Hi there, Thank you for creating the issue. To request support for a [Premium Feature](http://plugins.matomo.org/premium) please contact shop at innocraft.com or ask in the Premium Features forum here: https://forum.matomo.org/c/premium-features

Looking forward to helping you there. Closing this issue now. Thanks.
