### ISSUE TITLE
Search Engine Keywords Performance Plugin (v3.2.1) doesn't work

### ISSUE THREAD

**Issue by robles-design** [matomo-org/matomo#13058]
Hi,
the Search Engine Keywords Performance Plugin (v3.2.1) doesn't work after the latest plugin update on my Matomo installation (v3.5.1) yesterday. I can't find it in the menu. I've purchased the plugin on 14th July 2017, so it should still work for 1 month.

Greetings,
Robert

**Comment by sgiehl** [comment]
Hi Robert.
The reports were rearranged and can now be found at "Search Engines & Keywords."
We have further improved the plugin to better integrate in the existing reports.
If you don't see the reports there please let us know, as that might be a bug.

**Comment by robles-design** [comment]
Hi sgiehl, thank you! I've found them now. It would be nice to have an option to rearrange the order of Combined Keywords, Web Keywords on Google and so on like in the dashboard, cause I have to scroll now, even if I set the lines of Combined Keywords to only 5.

**Comment by sgiehl** [comment]
Thanks for the suggestion. That would be a feature that needs to be implemented in Matomo itself. I think there was an open issue for that, but can't find it right now.

**Comment by robles-design** [comment]
That woulb be nice to have. Thanks again for the quick answer.
