### ISSUE TITLE
Replace our github service "Piwik Plugins" with an app "Matomo Plugins" or webhook

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13050]
![image](https://user-images.githubusercontent.com/273120/41205664-be738c58-6d4b-11e8-94f7-7d2ccab9e0df.png)

On October 1st, we otherwise won't receive any new plugins anymore on the Marketplace and neither any plugin updates see https://developer.github.com/changes/2018-04-25-github-services-deprecation/   and https://developer.github.com/apps/differences-between-apps/#about-github-apps/ and https://developer.github.com/webhooks/

October 1st will be soon, especially if something needs to be reviewed or added by Github or something so we should aim to have finished by August 1st maybe? Also considering we need to notify all developers and give them time to upgrade etc. This means we might need to modify our current hook and if the old service is being used, decline the plugin submission and send the author(s) an email update with instructions on how to use the new webhook or app. We should have this active for 1 or 2 months (better 3) so it is really important to finish this as early as possible ideally.

Also we will need to publish a blog post and ideally notify some of the developers (we don't have contact details for all of them) by email and update the marketplace guide etc.

**Comment by Findus23** [comment]
Depending on how similar the new GitHub Apps API is to regular webhooks it may make sense to support both on the `https://plugins.matomo.org/postreceive-hook` (or a similar) endpoint.
That way everyone could simply enable the app without configuration or manually add the webhook if they are using something else than github.

**Comment by tsteur** [comment]
Marketplace is updated to support webhooks. Also updated the guide on https://developer.matomo.org/guides/distributing-your-plugin#activate-the-piwik-plugins-webhook

We will soon send emails to developers automatically if/when they release a new version through the GitHub service.

We might also email developers once in case they don't release a new version in the meantime.

**Comment by tsteur** [comment]
Updated all our repositories to use the new webhook, and developers should now be notified when they release new version and use outdated github service.
