### ISSUE TITLE
import_logs.py fails with "got more than 100 headers"

### ISSUE THREAD

**Issue by werk21** [matomo-org/matomo#13055]
Since update to 3.5.1 the import via import_logs.py fails with fatal error "got more than 100 headers".

We added 

`httplib._MAXHEADERS = 1000`

in line 52 and the script imports again.

Maybe you will add this line to import_logs.py or set an config-item for this.

See also https://stackoverflow.com/questions/23055378/http-client-httpexception-got-more-than-100-headers/23055649

**Comment by mattab** [comment]
Hi @werk21 Thanks for the report. Would you mind opening this bug report in the log analytics project here: https://github.com/matomo-org/matomo-log-analytics/issues ?

**Comment by mattab** [comment]
Will be fixed in https://github.com/matomo-org/matomo-log-analytics/issues/219
