### ISSUE TITLE
Custom Dimension segment / Blank reports

### ISSUE THREAD

**Issue by L3on1d** [matomo-org/matomo#13061]
Hi!

Visits Over Time and Visits Overview show no data for custom dimensions segment. However according to visitor log, devices, software, etc data exists. Tried to invalidate report, and generate it again. No luck.

Thanks.

**Comment by EugenVau** [comment]
Same issue here, Matomo 3.5.1. 
Hint: Custom Dimensions Plugin updated today.

**Comment by tsteur** [comment]
Just to clarify: Which commands or API's are you using to invalidate data? AFAIK the invalid data might still be used until the data is archived again just fyi.

**Comment by mattab** [comment]
Hi there, to fix the issue can you try upgrade to the latest Matomo version?
https://matomo.org/docs/update/

if you still experience this issue afterwards, please re-open this and post a comment. Thanks!
