### ISSUE TITLE
problem in RssRenderer

### ISSUE THREAD

**Issue by jsoltani** [matomo-org/matomo#13062]
i get error 
WARNING: /var/www/html/analytics/plugins/RssWidget/RssRenderer.php(47): Warning - simplexml_load_string(): Entity: line 1: parser error : Opening and ending tag mismatch: meta line 1 and head - Matomo 3.5.1

**Comment by Findus23** [comment]
I guess this has been a short-time error on the matomo.org website.
Please reopen or create a new issue if someone sees this error again.
