### ISSUE TITLE
Zoomed in map of the world contains two Coral Triangles (Australia, etc.)

### ISSUE THREAD

**Issue by mikegasche** [matomo-org/matomo#13071]
![bildschirmfoto 2018-06-18 um 13 56 03](https://user-images.githubusercontent.com/2489564/41534692-b0e5e7f2-72ff-11e8-8344-ba3ede614ff3.png)

See attached Picture.

**Comment by mikegasche** [comment]
PS: Funny.

**Comment by sgiehl** [comment]
The map and all zoom levels are separate SVG images, so maybe it does not replace the svg correctly when zooming. Which browser are you using? 
Are you able to reproduce that on  demo.matomo.org ?

**Comment by mikegasche** [comment]
Safari 11.1.1 on macOS High Sierra 10.13.5.

**Comment by mikegasche** [comment]
On demo.matomo.org it seems fine.

**Comment by mikegasche** [comment]
...and it seems not to be reproduceable at the moment. Maybe a temporary Safari SVG rendering problem.

**Comment by sgiehl** [comment]
Closing now, as not reproducible.
