### ISSUE TITLE
Impossible to use the same widget 2 times

### ISSUE THREAD

**Issue by Zefling** [matomo-org/matomo#13079]
The second widget takes priority over the first. For example, there can't have separate graphs for visits and views.

![image](https://user-images.githubusercontent.com/3032555/41584920-e0ffa672-73a8-11e8-985b-2c505ee0a978.png)

![image](https://user-images.githubusercontent.com/3032555/41585091-5346ca80-73a9-11e8-9bd8-f4bd324c3645.png)

**Comment by sgiehl** [comment]
It's currently by design that each widget can only be added once. Actually it is a bug that it's currently possible to add it multiple times

**Comment by Zefling** [comment]
Ok, but this impact also different types of widget. The second force the content of the first.

![image](https://user-images.githubusercontent.com/3032555/41684704-8e5dc944-74de-11e8-8eee-a04952c18021.png)

**Comment by mattab** [comment]
> It's currently by design that each widget can only be added once. Actually it is a bug that it's currently possible to add it multiple times

@sgiehl fyi it was changed a few years back and it is on purpose we can now add the same widget multiple times, as it is sometimes useful for some reports to be displayed with a different visualisation eg. table, insights (We grey it out in the widgets list to remind users it is already in the dashboard.)

**Comment by sgiehl** [comment]
That seems to be fixed meanwhile. It's now possible to select different metrics in each added widget of the same type
