### ISSUE TITLE
Edit the tracking cookies FAQ and add information about default timeouts

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13084]
Currently the information about default tracking cookies lifetime is only visible in the guide here: https://developer.matomo.org/api-reference/tracking-javascript

Let's edit our FAQ: https://matomo.org/faq/general/faq_146/ and list there the default timeout value for tracking cookies. The FAQ could also link to the API reference to mention it is possible to customise the values.

**Comment by diosmosis** [comment]
@mattab do you want this information to be automated in any way?

**Comment by mattab** [comment]
Not sure what you mean by automated here? I suppose the answer is no

**Comment by diosmosis** [comment]
Just that it will be duplicated so wondering if you wanted to make it displayed in one place via iframe or API or something so it would only have to be edited in one place if the values change.

**Comment by mattab** [comment]
It's fine to be duplicated

**Comment by diosmosis** [comment]
Don't think I have access to change the faq, but here's the text I came up w/:

```
<strong>Default expiration times</strong>

The cookies described above will eventually expire and be removed from your users' browsers. The default expiration times are listed below:

* <strong>_pk_id</strong> - 13 months
* <strong>_pk_ref</strong> - 6 months
* <strong>_pk_ses</strong>, <strong>_pk_cvar</strong>, <strong>_pk_hsr</strong> - 30 minutes

These defaults can be modified via JavaScript. <a href="https://developer.matomo.org/api-reference/tracking-javascript#configuration-of-tracking-cookies" target="_blank" rel="noreferrer noopener">Learn more about setting custom expiration times.</a>
```

**Comment by mattab** [comment]
Faq has been modified as suggested
