### ISSUE TITLE
Wrong result for No Result Search keyword

### ISSUE THREAD

**Issue by RichardS156** [matomo-org/matomo#13086]
Wrong result is showing for the keywords under Search Keywords with No Results. For the keywords search results are available.

**Comment by sgiehl** [comment]
Sorry. I don't fully understand your issue? Are you trying to track site searches with zero results?
If so, `searchCount` needs to be `0` for your code...

**Comment by RichardS156** [comment]
When we search for the keyword Senc ,it returns the search results. But It's appearing in No search keyword result. The same is happening with many other keywords as well.
Code:
var searchValue = $("input[id*='csr_sboxID']").val();
 _paq.push(['trackSiteSearch',searchValue,false, 0]);
_paq.push(['trackPageView'])

Could you please suggest if we have to include any other code.

Best regards

**Comment by RMastop** [comment]
Hi @RichardS,

Try to use the following:
_paq.push(['trackSiteSearch',searchValue,false, searchCount]);
It's not needed to use trackPageView when you use trackSiteSearch.

It looks like you always add a 0 as searchCount, that causes the system to register it as a no-result site search.

Cheers

**Comment by RichardS156** [comment]
Hi,

We are  using trackSiteSearch code in every search result page as below, but still we have the issue.

1.	This will track the keyword if there are search results appearing on the page.

var searchVal = $("input[id*='csr_sboxID']").val();
                     if(ctx.DataProvider.get_totalRows() > 0)
                    {
                    
                    _paq.push(['trackSiteSearch',searchVal,false, false]);
                        
                    }

2.	This will track the keyword when there are No search results appearing on the page.

  <div id="NoResult">
                
                       
                       var searchValue = $("input[id*='csr_sboxID']").val();
                     _paq.push(['trackSiteSearch',searchValue,false, 0]);
</div>
