### ISSUE TITLE
SQL errors: Incorrect integer value: 'undefined' for column 'time_since_load' 

### ISSUE THREAD

**Issue by tchwpkgorg** [matomo-org/matomo#13097]
I'm getting hundreds of Error query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'undefined' for column 'time_since_load'  with Matomo 3.5.1 running on Ubuntu 18.04 (PHP 7.2.5, Apache 2.4.29, MySQL server 5.7.22):

`[Sat Jun 23 20:21:50.360091 2018] [proxy_fcgi:error] [pid 5247:tid 139715835094784] [client 157.37.120.61:14819] AH01071: Got error 'PHP message: Error in Matomo (tracker): Error query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'undefined' for column 'time_since_load' at row 1 In query: INSERT INTO matomo_log_hsr_event (`idloghsr`,`time_since_load`,`event_type`,`idselector`,`x`,`y`,`idhsrblob`) VALUES(?,?,?,?,?,?,?)  Parameters: array (   0 => '35978',   1 => 'undefined',   2 => 12,   3 => '15986',   4 => '0',   5 => '540',   6 => NULL, )\n', referer: https://enbraun.example.com/v2/index.php?page=edit_time`

`[Sat Jun 23 20:21:54.786001 2018] [proxy_fcgi:error] [pid 5247:tid 139715843487488] [client 157.37.120.61:14817] AH01071: Got error 'PHP message: Error in Matomo (tracker): Error query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'undefined' for column 'time_since_load' at row 1 In query: INSERT INTO matomo_log_hsr_event (`idloghsr`,`time_since_load`,`event_type`,`idselector`,`x`,`y`,`idhsrblob`) VALUES(?,?,?,?,?,?,?)  Parameters: array (   0 => '35978',   1 => 'undefined',   2 => 12,   3 => '15986',   4 => '0',   5 => '499',   6 => NULL, )\n', referer: https://enbraun.example.com/v2/index.php?page=edit_time`

`[Sat Jun 23 20:21:55.585545 2018] [proxy_fcgi:error] [pid 5247:tid 139715843487488] [client 157.37.120.61:14821] AH01071: Got error 'PHP message: Error in Matomo (tracker): Error query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'undefined' for column 'time_since_load' at row 1 In query: INSERT INTO matomo_log_hsr_event (`idloghsr`,`time_since_load`,`event_type`,`idselector`,`x`,`y`,`idhsrblob`) VALUES(?,?,?,?,?,?,?)  Parameters: array (   0 => '35978',   1 => 'undefined',   2 => 12,   3 => '15986',   4 => '0',   5 => '499',   6 => NULL, )\n', referer: https://enbraun.example.com/v2/index.php?page=edit_time`

`[Sat Jun 23 22:11:31.793884 2018] [proxy_fcgi:error] [pid 5312:tid 139715784689408] [client 185.17.127.226:55867] AH01071: Got error 'PHP message: Error in Matomo (tracker): Error query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'undefined' for column 'time_since_load' at row 1 In query: INSERT INTO matomo_log_hsr_event (`idloghsr`,`time_since_load`,`event_type`,`idselector`,`x`,`y`,`idhsrblob`) VALUES(?,?,?,?,?,?,?)  Parameters: array (   0 => '35999',   1 => 'undefined',   2 => 12,   3 => '17346',   4 => '0',   5 => '6',   6 => NULL, )\n', referer: https://timereports.example.com/v2/index.php?page=projects_report`

`[Sat Jun 23 22:11:31.865527 2018] [proxy_fcgi:error] [pid 5247:tid 139715809892096] [client 185.17.127.226:55330] AH01071: Got error 'PHP message: Error in Matomo (tracker): Error query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'undefined' for column 'time_since_load' at row 1 In query: INSERT INTO matomo_log_hsr_event (`idloghsr`,`time_since_load`,`event_type`,`idselector`,`x`,`y`,`idhsrblob`) VALUES(?,?,?,?,?,?,?)  Parameters: array (   0 => '35999',   1 => 'undefined',   2 => 12,   3 => '17346',   4 => '0',   5 => '6',   6 => NULL, )\n', referer: https://timereports.example.com/v2/index.php?page=projects_report`

`[Sat Jun 23 22:11:33.190518 2018] [proxy_fcgi:error] [pid 5312:tid 139715784689408] [client 185.17.127.226:55867] AH01071: Got error 'PHP message: Error in Matomo (tracker): Error query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'undefined' for column 'time_since_load' at row 1 In query: INSERT INTO matomo_log_hsr_event (`idloghsr`,`time_since_load`,`event_type`,`idselector`,`x`,`y`,`idhsrblob`) VALUES(?,?,?,?,?,?,?)  Parameters: array (   0 => '35999',   1 => 'undefined',   2 => 12,   3 => '17346',   4 => '0',   5 => '36',   6 => NULL, )\n', referer: https://timereports.example.com/v2/index.php?page=projects_report`

`[Sat Jun 23 22:11:33.252043 2018] [proxy_fcgi:error] [pid 5247:tid 139715809892096] [client 185.17.127.226:55330] AH01071: Got error 'PHP message: Error in Matomo (tracker): Error query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'undefined' for column 'time_since_load' at row 1 In query: INSERT INTO matomo_log_hsr_event (`idloghsr`,`time_since_load`,`event_type`,`idselector`,`x`,`y`,`idhsrblob`) VALUES(?,?,?,?,?,?,?)  Parameters: array (   0 => '35999',   1 => 'undefined',   2 => 12,   3 => '17346',   4 => '0',   5 => '36',   6 => NULL, )\n', referer: https://timereports.example.com/v2/index.php?page=projects_report`

**Comment by sgiehl** [comment]
this is related to #13098

**Comment by tsteur** [comment]
Isn't this something for Matomo 4?

**Comment by tsteur** [comment]
@mattab I think we can close this issue? We have internally an issue for that. We're still waiting for exact steps and browser info to reproduce this
