### ISSUE TITLE
Engagement Visits by Days Since Last Visit 365 show error

### ISSUE THREAD

**Issue by huang0808** [matomo-org/matomo#13091]
@Sija @nbezzala @bangpound @znerol @dandv It seems the wrong show in Visits by Days Since Last Visit. beacuse in 365+ days, i did not put tracking code in website, but 365+ days show a value.

**Comment by huang0808** [comment]
@sgiehl  Could you see this issue? Thanks!

**Comment by Findus23** [comment]
I am sorry, but I don't understand what the issue here is. If you are still experiencing it, please reopen the issue with more details.
