### ISSUE TITLE
Still outgoing Internet request with Internet features disabled

### ISSUE THREAD

**Issue by swsharp** [matomo-org/matomo#13095]
I have found in testing version 3.5.1 that the Dashboard and Administration page load times are just over 30 seconds. This indicated to me that there must be another Internet request timing out before the Dashboard can finish loading. I didn't have this problem testing 3.4.0 with the Internet features disabled. 

I tried Personal Settings and the Plugins page as well and they were also affected. I have also had some page loads fail due to a 504 Gateway Timeout response.

I have all of the Internet features disabled using the newer property and I even tried adding the old properties as well:
```
[General]
enable_internet_features = 0
enable_marketplace = 0
enable_auto_update = 0
enable_update_communication = 0
```

I don't see any of the usual curl errors on the administration page when there is a request timeout.

Once I configured the proxy settings in config.ini.php the Dashboard load times decreased to ~500ms. While I was able to configure Matomo to use the proxy for the purpose of this test it isn't in keeping with my organization's policy and I need to be able to disable outgoing traffic.

**Comment by sgiehl** [comment]
There are not yet all features disabled by the settings. See https://github.com/matomo-org/matomo/pull/13076 and #6324

**Comment by sgiehl** [comment]
Closing in favor of the mentioned issues. If you still see outgoing requests after they were solved. Feel free to recreate a new issue.
