### ISSUE TITLE
Typo in TagManager.UrlParameterVariableDescription Enlgish version

### ISSUE THREAD

**Issue by baywet** [matomo-org/matomo#13106]
Hi,
I've been the main French translator for a while now and I'm working on translating the latest tag manager release.
Label with key TagManager.UrlParameterVariableDescription  reads "Get the value of a specific URL parameter." however all similar labels read "GetS the value…."
I believe an S is missing and the label should be updated.

**Comment by sgiehl** [comment]
@baywet thanks for the report. You can report tag manager related stuff also directly in the tagmanager repo: https://github.com/matomo-org/tag-manager/issues

**Comment by sgiehl** [comment]
Btw. There are currently two strings starting with `Get the` and four starting with `Gets the`. See https://github.com/matomo-org/tag-manager/blob/master/lang/en.json#L418-L420
We should use the same wording everywhere I guess, but not sure which one is better... @tsteur

**Comment by baywet** [comment]
Hi Stefan,
Should I close this issue and re open on the other repo out can keep investigating on this one exceptionally?

**Comment by sgiehl** [comment]
No need to create a new one there. Shouldn't be a big thing to change it, so we can leave it here and close once it's done.

**Comment by tsteur** [comment]
Don't know which one is better, maybe `Gets the ...`?

**Comment by baywet** [comment]
most of the other variables are documented with Gets the… it would be consistent at least
