### ISSUE TITLE
Update 3.5.0 to 3.5.1 failed with error

### ISSUE THREAD

**Issue by Qixuga** [matomo-org/matomo#13108]
I update "successfully" from 3.5.0 to 3.5.1 but after that, i got the following errors if i like to call the gui:

`Entry "Piwik\Plugins\CorePluginsAdmin\Menu" cannot be resolved: Entry "Piwik\Plugins\Marketplace\Plugins" cannot be resolved: Entry "Piwik\Plugins\Marketplace\Api\Client" cannot be resolved: Entry "Piwik\Plugins\CoreUpdater\Updater" cannot be resolved: Parameter $tmpPath of __construct() has no value defined or guessableFull definition:Object ( class = Piwik\Plugins\CoreUpdater\Updater scope = singleton lazy = false __construct( $translator = get(Piwik\Translation\Translator) $releaseChannels = get(Piwik\Plugin\ReleaseChannels) $tmpPath = #UNDEFINED# ))Full definition:Object ( class = Piwik\Plugins\Marketplace\Api\Client scope = singleton lazy = false __construct( $service = get(Piwik\Plugins\Marketplace\Api\Service) $cache = get(Piwik\Cache\Lazy) $logger = get(Psr\Log\LoggerInterface) $environment = get(Piwik\Plugins\Marketplace\Environment) ))Full definition:Object ( class = Piwik\Plugins\Marketplace\Plugins scope = singleton lazy = false __construct( $marketplaceClient = get(Piwik\Plugins\Marketplace\Api\Client) $consumer = get(Piwik\Plugins\Marketplace\Consumer) $advertising = get(Piwik\ProfessionalServices\Advertising) ))Full definition:Object ( class = Piwik\Plugins\CorePluginsAdmin\Menu scope = singleton lazy = false __construct( $marketplacePlugins = (default value) NULL ))`

console tests seems to be successfully:
```
> ./console diagnostics:run
INFO [2018-06-26 14:26:36] 20016  Unable to test if mod_pagespeed is enabled: the request to http://unknown/./console?module=Installation&action=getEmptyPageForSystemCheck failed
Huzzah! There are no problems with your Matomo setup. Give yourself a pat on the back.
```

But why the system can't get the url to call the for pagespeed-test?
There is also a bug open: #12024 

Sometimes the log also seems to have a problem to got access to the SiteID
/piwik/core/Plugin/Controller.php:959
error >General_ExceptionPrivilegeAccessWebsite< shown.

I followed the cli-update instructions, clear the cache... 
test the update via web-gui (not working) and
i also replace all files with the new version 3.5.1 (insert the config again).
login seems to work but then the upper error occures.

so may be someone can help me?
Thank you

**Comment by Qixuga** [comment]
I got an update - i decided to deactivate the plugins from the error message.
first marketplace and the system is accessable!

> ./console plugin:deactivate Marketplace

After calling the GUI works fine!
So i try to active the plugin again after some successfully checks at the gui and it works to now!

but why the error?

**Comment by huang0808** [comment]
Is there a cache？

**Comment by sgiehl** [comment]
@Qixuga  do you have some additional php cache running? like APC, xCache, eAccelerator or similar

**Comment by Qixuga** [comment]
Yes there are caches active and it seems that after deactivate, empty caches and activate again it works fine!
Thank you for your support!
