### ISSUE TITLE
Load the plugin Proxy used long time

### ISSUE THREAD

**Issue by huang0808** [matomo-org/matomo#13107]
@mattab @tsteur My site load the plugin Proxy used long time 16s. Before update the speed is normal and quick. After update to v3.5.1, the speed is very slowly. Could you help me see it? Thanks!

https://xx/index.php?module=Proxy&action=getCoreJs&cb=38788ba285b2388562b1275f82c43e23

**Comment by sgiehl** [comment]
That request compiles/combines the javascript files. The first request might be slow, but afterwards the assets should be built and directly served. This should not be an issue of Matomo, but something on the server side. Maybe try cleaning the tmp directory of Matomo.

**Comment by huang0808** [comment]
@sgiehl  thank your reply, I will check the server side.

**Comment by huang0808** [comment]
@sgiehl   i delete below tmp files, now show error.  what is the problem? could you help me see? thanks!
*1740303 FastCGI sent in stderr: "PHP message: Error in Matomo (tracker): Error query: SQLSTATE[HY000]: General error: 1030 Got error 28 from storage engine In query: SELECT MIN(idaction) as idaction, type, name FROM piwik_log_action WHERE ( hash = CRC32(?) AND name = ? AND type = ? )  GROUP BY type, hash, name Parameters: array (   0 => 'mouser.cn/ProductDetail/Amphenol-Pcd/USBFTV71G?qs=/ha2pyFadug0yA5zchDI5j7Oq60F/q%2bWNs1Wt2AAKBI=',   1 => 'mouser.cn/ProductDetail/Amphenol-Pcd/USBFTV71G?qs=/ha2pyFadug0yA5zchDI5j7Oq60F/q%2bWNs1Wt2AAKBI=',   2 => 1, )
PHP message: PHP Warning:  file_put_contents(): Only 0 of 601124 bytes written, possibly out of free disk space in /var/www/html/chinalytics2/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php on line 254" while reading response header from upstream, client: 218.88.126.55,

**Comment by sgiehl** [comment]
As the error messages says: Did you check if you are maybe out of disc space? Additionally you should run the Matomo system check.
For further help maybe try searching or asking your questions on our forum: https://forum.matomo.org
We are not able to troubleshoot everyone here in the public issue tracker.

**Comment by huang0808** [comment]
@sgiehl thank you very much, I check the disk space that no space.
