### ISSUE TITLE
Strange values during the filter by dimension

### ISSUE THREAD

**Issue by imyaro** [matomo-org/matomo#13118]
Hello,
I faced an issue with Matomo (v. 3.5.1)
I'm tracking all the e-commerce actions with the dimensions
When I'm at the product overview in it looking good:
![image](https://user-images.githubusercontent.com/7985237/42122089-8cb8ea30-7c66-11e8-8220-8398e9abbcc0.png)

But when I'm trying to filter results by dimensions I get:
![image](https://user-images.githubusercontent.com/7985237/42122106-e3c9256a-7c66-11e8-8cab-82144488d88e.png)

If I trying to increase quantity in the cart for **1** I get +21 for the first product and +15 for the second one (when the dimension filter applied)

+1 to cart request path (From Q-ty = 9 to 10 ):
`https://my-piwik-tracker-domain.com/piwik.php?idsite=1&rec=1&apiv=1&r=527642&cip=172.18.0.1&uid=1&_idts=1529999593&_idvc=139&_viewts=1530241181&_ects=1530246016&_id=356a192b7913b04c&url=http%3A%2F%2Fdomain.com%2Fcart&urlref=http%3A%2F%2Fdomain.com%2FproductUrl&dimension3=28&dimension10=33&idgoal=0&revenue=112&ec_items=%5B%5B%22aenean-tellus-metus-bibendum-sed%22%2C%22Aenean+tellus+metus+bibendum+sed%22%2C%22Caterogy3%22%2C%22100.000000%22%2C10%5D%5D`

Decoded:
`https://my-piwik-tracker-domain.com/piwik.php?idsite=1&rec=1&apiv=1&r=527642&cip=172.18.0.1&uid=1&_idts=1529999593&_idvc=139&_viewts=1530241181&_ects=1530246016&_id=356a192b7913b04c&url=http://domain.com/cart&urlref=http://domain.com/productUrl&dimension3=28&dimension10=33&idgoal=0&revenue=112&ec_items=[["aenean-tellus-metus-bibendum-sed","Aenean tellus metus bibendum sed","Caterogy3","100.000000",10]]`

Am I doing something wrong?

**Comment by sgiehl** [comment]
which segment are you using?

**Comment by zvse** [comment]
Sorry, forgot about this point

Simple filter by the dimension (ID=3) and it value (=28)
![image](https://user-images.githubusercontent.com/7985237/42123741-32ee9ca0-7c81-11e8-958c-d30c8513a5ff.png)

**Comment by zvse** [comment]
Example log output
Different product, but I always receive logs like this
[Log output.log](https://github.com/matomo-org/matomo/files/2151624/Log.output.log)

**Comment by sgiehl** [comment]
@imyaro 
Hm. Seems we missed to get back to you on that one. Hope you where meanwhile able to solve your problems.
If not maybe try to get some help on our forum or let us know here, so we can reopen the issue. Thanks.
