### ISSUE TITLE
VisitsSummary.get different result when period is range

### ISSUE THREAD

**Issue by homewantad** [matomo-org/matomo#13119]
Hi,

when I use your example query with different period inputs, 2 fields are missing by the range query.

The result for this query 

`https://demo.matomo.org/?module=API&method=VisitsSummary.get&idSite=7&period=range&date=2017-06-30,2018-06-30&format=JSON&token_auth=anonymous`

is 

```
{
nb_visits: 260152,
nb_actions: 516247,
nb_visits_converted: 40,
bounce_count: 176310,
sum_visit_length: 33869407,
max_actions: 1041,
bounce_rate: "68%",
nb_actions_per_visit: 2,
avg_time_on_site: 130
}
```

With day and today:

https://demo.matomo.org/?module=API&method=VisitsSummary.get&idSite=7&period=day&date=today&format=JSON&token_auth=anonymous

```
{
nb_uniq_visitors: 105,
nb_users: 0,
nb_visits: 111,
nb_actions: 213,
nb_visits_converted: 0,
bounce_count: 76,
sum_visit_length: 9307,
max_actions: 18,
bounce_rate: "68%",
nb_actions_per_visit: 1.9,
avg_time_on_site: 84
}
```

**Comment by Findus23** [comment]
This is to be expected as Matomo does not calculate unique visitors for date ranges and years by default. This can be changed as explained here:
https://matomo.org/faq/how-to/faq_113/
