### ISSUE TITLE
Add "Clicked URL"  Segment can not work

### ISSUE THREAD

**Issue by huang0808** [matomo-org/matomo#13111]
![screenshot from 2018-06-28 15-47-09](https://user-images.githubusercontent.com/34669327/42020477-979ddbb8-7aea-11e8-95f5-81e4a5c77b8f.png)
@Sija @nbezzala @tsteur I add "Clicked URL" of segment, it can not work, no data to show.  i think that maybe a bug.

**Comment by mattab** [comment]
Thanks for the report. Duplicates https://github.com/matomo-org/matomo/issues/11900

**Comment by mattab** [comment]
This should be fixed in Matomo 3.12.0 which will be released tomorrow - if you still experience this issue then, let us know.
