### ISSUE TITLE
[question] Matomo Analytics getting started

### ISSUE THREAD

**Issue by dindu-nuffin** [matomo-org/matomo#13127]
I have a locally installed Matomo analytics server. 
My "Trusted Matomo Hostname" settings is
[#screenshot](https://raw.githubusercontent.com/dindu-nuffin/matomo/master/matomo_trusted.jpg)

I created website and added it to matomo for the test purposes
[#screenshot](https://raw.githubusercontent.com/dindu-nuffin/matomo/master/matomo_website.jpg)

Then I added javascript tracking code on all pages of test website
My "JavaScript Tracking" settings
[#screenshot](https://raw.githubusercontent.com/dindu-nuffin/matomo/master/matomo_tracking.jpg)
and tracking code

```
<!-- Matomo -->
<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//matomo.localhost:666/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '3']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

I visit website by hostname "matomo-test.localhost" from the same machine or by ip "192.168.7.141:156" address from another machine.
In developer tools I can see that piwik.js is loaded and sending statistics
[#screenshot](https://raw.githubusercontent.com/dindu-nuffin/matomo/master/matomo_stat_post.jpg)

But in the dashboard I cannot see any visits.
[#screenshot](https://raw.githubusercontent.com/dindu-nuffin/matomo/master/matomo_dashboard.jpg)

What am I doing wrong?

**Comment by dindu-nuffin** [comment]
@fdellwing [call to piwik.php](https://raw.githubusercontent.com/dindu-nuffin/matomo/master/matomo_stat_post.jpg)

**Comment by fdellwing** [comment]
Ok, I do see a DNT header being sent. Matomo will, with default settings, respect that header and don't track anything. You can, however change this behaviour under Settings -> Privacy -> Users opt-out.

**Comment by dindu-nuffin** [comment]
@fdellwing thanks! I understood what the problem is.

**Comment by Findus23** [comment]
@dindu-nuffin If you have more questions about Matomo in the future, please ask them on [the forum](https://forum.matomo.org/).
