### ISSUE TITLE
Plugin "Site Migration": "no commands defined"

### ISSUE THREAD

**Issue by larsen0815** [matomo-org/matomo#13128]
Using Matomo 3.5.1 (on Debian Stretch), I have downloaded the plugin from https://plugins.matomo.org/SiteMigration and unzipped it into the plugins directory.

When I run `./console migration:site --help` from the main directory, I get this error message:

````
[InvalidArgumentException]
  There are no commands defined in the "migration" namespace.
````

Same happens when I try to migrate a siteID.
As version 1.0.8 has last been updated in 2015, I suspect it's not compatible anymore.

**Comment by sgiehl** [comment]
Correct. The plugin might not be compatible with Matomo 3+ as it isn't maintained anymore.

**Comment by ma2thieu** [comment]
After unzipping the plugin files you need to activate the plugin in Matomo admin panel or else you get this error message.
I just migrated one site between two Matomo 3.5.1 instances with SiteMigration 1.0.8 and it worked well.

**Comment by sgiehl** [comment]
Closing this issue now. We released a new plugin for migrating measurables. See https://plugins.matomo.org/Migration

**Comment by larsen0815** [comment]
I now had another use case for the (new) migration plugin (didn't continue last year) and got the same error message as with the last plugin.

> After unzipping the plugin files you need to activate the plugin in Matomo admin panel or else you get this error message.

Solved it. This should really be documented in https://plugins.matomo.org/Migration as it is kinda unexpected if you are not familiar with plugins.

**Comment by Findus23** [comment]
You don't normally need to unzip the plugin as you can directly use the Marketplace to download (and in the same step activate) the plugin (unless your server doesn't have a connection to the internet.

**Comment by larsen0815** [comment]
Don't remember how this plugin initially got installed. Maybe that's the reason why it wasn't activated before.
