### ISSUE TITLE
Possilbe bug with site-search tracking by piwik

### ISSUE THREAD

**Issue by JeffS25** [matomo-org/matomo#13140]
Site search keyword is returning 'Undefined' as a search keyword.
The number of search results are more than 200 for 'Undefined' keyword. Can you please help me know in understanding why it's showing 'Undefined' as search keyword?

Thanks,
Jeff
![undefined](https://user-images.githubusercontent.com/40857207/42319426-905f6d78-806f-11e8-9c46-a00d721b73fa.png)

**Comment by tsteur** [comment]
Are you tracking Site Search using the Javascript `trackSiteSearch()` function?

**Comment by Findus23** [comment]
Without checking what data is sent to Matomo in the HTTP request, it is hard to know if this is a bug in Matomo (but `undefined` sounds a lot like JS).

If you or someone else can reproduce this issue and provide more details, please reopen the issue or create a new one.
