### ISSUE TITLE
Update FAQ 16646 with "enable_internet_features = 0"

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#13144]
https://matomo.org/faq/troubleshooting/faq_16646/

This article seems really really outdated... (and contains a typo as well)

**Comment by Findus23** [comment]
Thanks for the suggestion. Updating this faq has been my plan for a while but only now I have time to actually do it. I'll try to rewrite it in the next days.

**Comment by Findus23** [comment]
I have now updated the description: https://matomo.org/faq/troubleshooting/faq_16646/
It still depends on https://github.com/matomo-org/matomo/pull/13076, so I'll rewrite it after 3.6.0 is released.

**Comment by mattab** [comment]
@Findus23 we'll release 3.6.0 in a week or so. Could you please update again the FAQ and close this issue?

**Comment by Findus23** [comment]
@mattab Done
