### ISSUE TITLE
I can not display properly if there are pictograms etc. in the title

### ISSUE THREAD

**Issue by ghost** [matomo-org/matomo#13148]
If pictograms are included in the title, they are not displayed normally (become empty)
Example of title: Hello 😄

![default](https://user-images.githubusercontent.com/37808790/42422557-68af9e5e-8323-11e8-8436-f90bb6f2038b.PNG)****

**Comment by sgiehl** [comment]
@03-26 Are those titles even tracked correctly? e.g. are they showing up in the page title report or is that only a failure of the tooltip?

Guess that is related to #8790
