### ISSUE TITLE
very slow response time

### ISSUE THREAD

**Issue by broros** [matomo-org/matomo#13152]
matomo and my website are installed on the SAME server but still very slow

how do I speed this up?

![piwik](https://user-images.githubusercontent.com/598228/42440372-6eca2d76-831a-11e8-9c64-52c3643f293e.png)

**Comment by sgiehl** [comment]
Are all requests that slow? 
If you have browser archiving enabled in Matomo, some of the tracking request might trigger an archiving process, which let the requests run a bit longer.
If you want to avoid that, you can disable browser archiving and set up an archiving cron. See https://matomo.org/docs/setup-auto-archiving/

**Comment by fdellwing** [comment]
Also note, that it does not matter on what server the sites are running, as each request is made from the users browser and it is therefore irrelevant (mostly) where the server is.

**Comment by broros** [comment]
why is matomo calling two files? piwik.js and piwik.php

calling just one file ( piwik.js) would be better

**Comment by sgiehl** [comment]
because Matomo needs javascript to measure some stuff. piwik.js should only be loaded on the first page, afterwards browsers should have in cache. piwik.php will be requested on anytime something is tracked (page view, content impression, outlink, download, ...)

**Comment by broros** [comment]
develop a rest API for tracking so only JavaScript will be loaded form the browser

**Comment by sgiehl** [comment]
If you are able to provide a solution to transfer data from the users
browser to Matomo without sending a request, we would for sure implement
it. But even a Rest API requires a request...

If you don't want to track any JavaScript stuff and want to avoid any
additional request maybe have a look at the PHP Tracker or Log Analytics.

**Comment by broros** [comment]
this takes too long to load the page

`/piwik.php?action_name=Great%20Health%20%E2%80%93%20Ideas%20to%20help%20you%20look%20and%20feel%20your%20best.&idsite=4&rec=1&r=971077&h=4&m=3&s=5&url=https%3A%2F%2Fmywebsite.org%2F&_id=e41a0c80b23d269d&_idts=1531479785&_idvc=1&_idn=0&_refts=0&_viewts=1531479785&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=1&java=1&gears=0&ag=0&cookie=1&res=1280x1024&gt_ms=110&pv_id=O4tHRK`

**Comment by fdellwing** [comment]
Did you setup cron archiving as suggested in https://github.com/matomo-org/matomo/issues/13152#issuecomment-403408157?

**Comment by tsteur** [comment]
You may also just get a better server and find the request time very fast. Or install queued tracking, there it takes like 5ms. https://plugins.matomo.org/QueuedTracking
