### ISSUE TITLE
Live.getLastVisitsDetails segment

### ISSUE THREAD

**Issue by pmmcoder** [matomo-org/matomo#13150]
Do you have such a parameter to get online visitors in recent minutes? Give an example, thank you.

**Comment by fdellwing** [comment]
Please ask such questions in the forums: https://forum.matomo.org/

**Comment by pmmcoder** [comment]
&period=day&date=2018-07-11&filter_sort_order=desc&segment=visitLocalMinute>10;visitLocalHour==17


The above parameters return records of 2017-07-10, whether there are bug, or other questions

**Comment by mattab** [comment]
see the API in Live here: https://developer.matomo.org/api-reference/reporting-api#Live
