### ISSUE TITLE
Broken referrer link and issue with Outlink tracking

### ISSUE THREAD

**Issue by RichardS156** [matomo-org/matomo#13157]
Hi Team,

I am facing two issues.

1.Broken referrer issue
We open the site(site A) and click a link leading to another site B.
Site B notices that the visitor has no active single-sign-on session and redirect the visitor to the login page, which will redirect you back to site B.
The referrer is now the login link of the Site B instead of the original site referring (site A).

Is this the way it works or do we need to make any changes? Can you please help.

2.In some of the pages we have links leading to pages outside the application. Few of them trigger outlinks, but few doesn't.

We have a single page application which never trigger outlinks, and the event does not produce any information about the link clicked, preventing us to see where a user went. And we would generally prefer correct outlink information, even if events are triggered.
We are using _paq.push(['enableLinkTracking']); in the tracking code. But still outlink doesn't work for few sites.
Should I use setLinkTrackingTimer( 750 ); in the script? 
if I use it will it cause any delay in opening the clicked page?

Regards,
Richard

**Comment by justinvelluppillai** [comment]
Hi @RichardS156 I will close this issue as it is so old now - if you still have this problem please feel free to raise it in forums.matomo.org, or reopen this if you think it is a bug.
