### ISSUE TITLE
Issue in piwik.js function logEvent

### ISSUE THREAD

**Issue by hamburger123456** [matomo-org/matomo#13165]
If you call the function

    logEvent(category, action, name, value, customData, callback)

without parameter it shout gives an error.

    (logConsoleError(‘Error while logging event: Parameters category and action must not be empty or filled with whitespaces’);

But it doesn’t. Because the line

     if (trim(String(category)).length === 0 || trim(String(action)).length === 0) { ...

will not work. String(category) returns always 9 (the length of the word undefined) when categorie is empty
So the error will never been showed.

**Comment by fdellwing** [comment]
I do not have time to provide a PR atm, but this should be fixxed really simple.

```javascript
if (category === undefined || action === undefined || trim(String(category)).length === 0 || trim(String(action)).length === 0) { ...
```

**Comment by tsteur** [comment]
@fdellwing just fyi to make JSLint in the tests happy we will need to use something like `typeof value === "undefined"`. Should be definitely an easy fix

**Comment by fdellwing** [comment]
Maybe not the right place for that, you can DM me in the forums with an answer if you want:

I'm not experienced with JSLint, what is it's problem with ˋvalue === undefinedˋ? This is perfectly valid JS, isn't it?

**Comment by tsteur** [comment]
It definitely is valid. It's just when the JS tests run, there is a test to check if [JSLint](https://www.jslint.com/) is "happy" and it usually complains about it.

**Comment by hamburger123456** [comment]
whats about 
`if (!category || ... `
and:
if you use trim, why not here also?
` buildEventRequest(trim(String(category)), trim(String(action)), name, value),  `

**Comment by fdellwing** [comment]
Never use something like `!category` if you have no control over the input, you are asking for trouble.
