### ISSUE TITLE
Installation Tracker-Status 403

### ISSUE THREAD

**Issue by Daijobou** [matomo-org/matomo#13170]
I want install matomo and get in step 2 this optional tracking-status error

> GET request to piwik.php failed. Try whitelisting this URL from HTTP Authentication and disable mod_security (you may have to ask your webhost).

mod_security exists, but its status "off". I can access piwik.php and get as result

> As Matomo is not installed yet, the Tracking API cannot proceed and will exit without error.

So i want ignore this optional warning and get in next step a 403 site for

/folder_a/folder_b/folder_c/matomo-3.5.1/index.php?action=databaseSetup&trackerStatus=403&clientProtocol=https

So I installed it on a subdomain and again I get a warning for tracking-status. I ignore it again and now its installed successful. I take a look in matomo system-check and now tracking-status is fine. 

Summary
1. In install process tracking-status report a warning
2. after install tracking-status is fine.

So the detection by install is little lost? ^^

**Comment by sgiehl** [comment]
@Daijobou did you see any failing requests during installation? It should send a request to piwik.php and show the warning if it fails due to any reason.

**Comment by Daijobou** [comment]
In plesk mod_security had a issue, its was active and show wrong in-active. Solution was to start and stop mod_security.
