### ISSUE TITLE
Visitor profile: Key "totalEvents" for array with keys "..." does not exist

### ISSUE THREAD

**Issue by dw** [matomo-org/matomo#13171]
Hi there,

Running latest Matomo with (as far as I can tell) all the standard plug-ins enabled produced this for maybe 70% of clicks on the "View visitor profile" icon of the "Visitors in Real-time" dashboard widget. This has been broken for many months across many releases, I just decided to look into it today.

The AJAX call fails with HTTP 500, and the pop-up modal just displays a constant modal. Opening the AJAX URL directly reveals the error.

The URL is:

````
/piwik/index.php?date=today&module=Live&action=getVisitorProfilePopup&visitorId=...&idSite=6&period=day
````

The error text is:

````
A fatal error occurred

The following error just broke Matomo (v3.5.1):

Key "totalEvents" for array with keys "visitorId, totalVisits, totalVisitDuration, totalActions, 
totalOutlinks, totalDownloads, totalSearches, totalPageViews, totalUniquePageViews, 
totalRevisitedPages, totalPageViewsWithTiming, searches, totalGoalConversions, 
totalConversionsByGoal, hasLatLong, lastVisits, nextVisitorId, previousVisitorId, 
totalVisitDurationPretty, userId, firstVisit, lastVisit, visitsAggregated, visitedPages, 
averagePageGenerationTime, devices, continents, countries" does not exist.

in

/home/www/piwik/plugins/Live/templates/_profileSummary.twig line 11
````

**Comment by sgiehl** [comment]
Did you maybe disable the Events plugin?

**Comment by dw** [comment]
Oh man, that was easy! Yes, somehow the plug-in was disabled. This is a very old install. Any idea why it was only broken for certain visitors?

**Comment by dw** [comment]
Regardless, thanks for the amazingly quick response!

**Comment by sgiehl** [comment]
Seems to happen only if the user had some actions != page view. Will check if there's something we can improve
