### ISSUE TITLE
Events collected but event report shows no data

### ISSUE THREAD

**Issue by digihiveinc** [matomo-org/matomo#13189]
I am using matomo 3.5.1 for tracking multiple sites.

I am tracking events with request to pixel like so
...piwik.php?idsite=2&rec=1&e_c=notifications&e_a=sent&e_n=email

Events show up in visitors log
<img width="381" alt="acme - friday 2c july 20 2c 2018 - web analytics reports - matomo 2018-07-20 05-04-19" src="https://user-images.githubusercontent.com/17980436/42994325-ca8ce9b8-8bdb-11e8-8e63-81d7b022c8ce.png">
and more here: http://take.ms/JozXk6

but strangely in the event report, nothing shows up
<img width="537" alt="acme - friday july 20 2018 - web analytics reports - matomo 2018-07-20 05-17-40" src="https://user-images.githubusercontent.com/17980436/42994412-05491fae-8bdc-11e8-8e31-a93cd61f37ed.png">

I don't use cron to generate reports, and all other reports are available.

**Comment by bigretromike** [comment]
what was the issue ? how was it solved ?

**Comment by digihiveinc** [comment]
> what was the issue ? how was it solved ?

the issue was outside of matomo. our data center decided to block certain requests to the server where matomo is installed.
