### ISSUE TITLE
limiting urls to track

### ISSUE THREAD

**Issue by amit300788** [matomo-org/matomo#13183]
Hi All,

When i limited the url tracking Matomo is showing wrong url along with click events. Before this when all the urls were being tracked, it was working fine. Please help.

**Comment by sgiehl** [comment]
@amit300788  Feel free to ask in our forum if you still need help. If it turns out, that there is any bug withing Matomo feel free to recreate the issue with a more detailed explanation and if possible a way how to reproduce it
