### ISSUE TITLE
piwik,js not loading

### ISSUE THREAD

**Issue by broros** [matomo-org/matomo#13191]
when I do a test in chrome dev toolbar I get an error. does anybody know what this is? or how to fix it?

![piwikcanceled](https://user-images.githubusercontent.com/598228/43048186-647b4be2-8d98-11e8-9e06-76257dce77fe.png)

**Comment by Findus23** [comment]
Chances are really high that a browser extension (especially an adblocker) is telling chrome to not load the file.

**Comment by broros** [comment]
you are correct, its the brave browser
