### ISSUE TITLE
Page Overlay with https 

### ISSUE THREAD

**Issue by KToghia** [matomo-org/matomo#13199]
When trying to access the page overlay I get the message: 

  | Content was blocked because it was not signed by a valid security certificate.
-- | --
The matomo server certificate is valid, and the site I am connecting to is http.
![image](https://user-images.githubusercontent.com/17910900/43107851-a75304ae-8e93-11e8-9b77-aa1e501b4f43.png)

**Comment by mattab** [comment]
@KToghia The issue is probably that the certificate of the website is not valid, please check if loading the site in its own browser tab works fine? Please create a new issue if you still experience this.
