### ISSUE TITLE
matomo super user login not working

### ISSUE THREAD

**Issue by ShiroyaBhavin** [matomo-org/matomo#13206]
Hello Team,

i am use innocraft matomo piwik trial 2 days and after we are upgrade business plan,
but one problem super user login not working

so Please let me know what's problem

Thanks

**Comment by sgiehl** [comment]
@ShiroyaBhavin Please get in touch with support@innocraft.cloud about that issue. They should be able to help you.

**Comment by sgiehl** [comment]
I'm not able to help you here, as I don't have any possibilities to do so.

**Comment by ShiroyaBhavin** [comment]
@sgiehl 

i have a critical issue please help me.

**Comment by sgiehl** [comment]
I've pinged the support. That's all I'm able to do.

**Comment by ShiroyaBhavin** [comment]
@sgiehl okay 

Thank you
