### ISSUE TITLE
Piwik certificate not accepted by Google Chrome v66

### ISSUE THREAD

**Issue by JeffS25** [matomo-org/matomo#13208]
Hi,

We are not able to access https://piwik.swissre.com/piwik/  in google chrome, getting error ERR_CERT_COMMON_NAME_INVALID please check attached screenshot for the same.
Please can you look into this and provide solution for this.

Thanks

![from_clipboard_1](https://user-images.githubusercontent.com/40857207/43198709-33a82ac0-902d-11e8-9513-2deada807a62.png)

**Comment by sgiehl** [comment]
It seem the new version of chrome does not trust the certificate any longer. There is nothing we can do about that. You need to get in touch with your server admin or hoster in order to get a new ssl certificate that is trusted.
