### ISSUE TITLE
Export  reports in "Insights" visualization mode leds to "Error: Invalid dimension 'false'."

### ISSUE THREAD

**Issue by andristeiner** [matomo-org/matomo#13213]
We're using the latest Matomo version 3.5.1 and ran into a issue we can reproduce on any installation.

# Problem

* select any report, we're using "Behaviour" > "Page titles" in this example
* make sure the "Insights" visulaization mode is active ("Change visualization" > "Insights" at the botom left controls)
* "Export this dataset in other formats", select any format with any options
* the error message "Error: Invalid dimension 'false'." is displayed

# Example export url (redacted)

```
https://xxxx/index.php?comparedToXPeriods=1&date=2018-07-26&expanded=1&filterBy=&filter_limit=100&format=CSV&idSite=1&language=en&limitDecreaser=50&limitIncreaser=50&method=Insights.getInsights&minGrowthPercent=1&minImpactPercent=0.1&module=API&orderBy=absolute&period=day&pivotBy=false&pivotByColumn=false&reportUniqueId=Actions_getExitPageUrls&token_auth=xxx&translateColumnNames=1
```

# Workaround

As described in #10117 for a slightly different problem, if i remove the `pivotBy=false` manually from the URL, everything seems to be fine.

**Comment by sgiehl** [comment]
@andristeiner Thanks for the report. I'm able to reproduce it.
