### ISSUE TITLE
Create automated test to make sure woff2 files are up to date

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#13210]
Refs #12695 

One way might be to just run woff2_compress in a test and see if the result is the same as what's in git. A test like this would probably be added to ReleaseCheckListTest. Would need to add woff2 to travis.

woff2 is not available as a package on travis, but it seems it can be built from source (and then added to a travis cache directory), see:

https://github.com/ManageIQ/font-fabulous/blob/master/.travis.yml

**Comment by tsteur** [comment]
I don't think woff2 tests are needed. Woff2 is used by default by all modern browsers, and all the fonts are generated in one go just like .woff, .ttf, ...

**Comment by mattab** [comment]
@Findus23 thanks for the details. Would you maybe be able to create the test maybe?

**Comment by diosmosis** [comment]
Fixed by #15172
