### ISSUE TITLE
Content tracking delay in viewing the data

### ISSUE THREAD

**Issue by Vinutab** [matomo-org/matomo#13224]
Dear Team,

We are tracking the contents and the content information is available in the visitor log till today. But the data is not appearing under Contents Tab. I can see the Contents data till last Monday, i.e 23rd .Can you please let me know how much time it would take to load the data in front-end under contents?

**Comment by tsteur** [comment]
If not done already, try to set up a CLI archiving: https://matomo.org/docs/setup-auto-archiving/

If you have done already, likely the cronjob fails eg not enough memory or something.
