### ISSUE TITLE
Incorrect proxy settings lead to slow page loading

### ISSUE THREAD

**Issue by akupaka** [matomo-org/matomo#13241]
Hello!

We have been using Piwik 3.0.4 for our intranet site for few months. Some time ago performance decreased drastically when loading Piwik pages (dashboard, settings etc), every new page load took more than 60 seconds! We analyzed Ubuntu server, MySQL etc, but everything looked fine.
The only hint was that there was an error message "curl_exec: Connection timed out after 60001 milliseconds. Hostname requested was: plugins.piwik.org" on settings page.
As our main user does not go to this page we did not pay attention to this message at first. But the fact that every page took 60+ seconds to load made us think that those are connected. We checked system proxy settings which were fine. Then we googled proxy settings for Piwik and found that there are "personal" settings which were configured to use old proxy, we shut down recently.

In general this is our mess, we forgot about "personal" proxy settings. So I wanted to mention this here in order other users could resolve the same issue.

But I really don't understand why it took so long to load dashboard etc when proxy settings was wrong?!

Thank you!

**Comment by fdellwing** [comment]
> But I really don't understand why it took so long to load dashboard etc when proxy settings was wrong?!

That is easy to answer: He tried to connect to the marketplace and the connection did not return an error, it just timed out (after 60 seconds).

**Comment by akupaka** [comment]
@fdellwing ,
but why it even tries to connect to marketplace when user opens dashboard? Is there a way to prevent this behaviour? Thank you!

**Comment by fdellwing** [comment]
I cannot really say why it connects to the marketplace, but @tsteur should be able to.

The only way to disable this I think is to completely disable the marketplace via config option.

**Comment by Findus23** [comment]
> why it even tries to connect to marketplace when user opens dashboard

For checking for updates for Matomo and Plugins. 

In the meantime there is now also a FAQ entry that explains how to configure Matomo without accessing the internet more detailed:

https://matomo.org/faq/troubleshooting/faq_16646/
