### ISSUE TITLE
Continuous integration works neither based on Ubuntu precise nor based on trusty

### ISSUE THREAD

**Issue by johsin18** [matomo-org/matomo#13244]
I generated a .travis.yml file for my plugin, to have continuous integration.
However, most of the jobs fail due to infrastructure problems.

When using the default .travis.yml file based on Ubuntu "precise", python2.6 cannot be installed
```
E: Package 'python2.6' has no installation candidate
E: Unable to locate package python2.6-dev
```
https://travis-ci.org/johsin18/DevicePixelRatioMatomoPlugin/builds/410685631
Also, Travis CI considers the "precise" dist to be deprecated.

When switching to Ubuntu "trusty", at least one job complains that this is illegal:
```
Diffing generated with existing (located at /home/travis/build/johsin18/DevicePixelRatioMatomoPlugin/DevicePixelRatio/.travis.yml)...
46c46
< dist: trusty
---
> dist: precise
```
Your .travis.yml file is out of date! Please update it using the generate:travis-yml command.
https://travis-ci.org/johsin18/DevicePixelRatioMatomoPlugin/jobs/410685632
A certain job based on PHP 5.5 succeeds, but honestly I don't know why.
https://travis-ci.org/johsin18/DevicePixelRatioMatomoPlugin/jobs/410685634

**Comment by johsin18** [comment]
I found the --dist-trusty switch to generate:travis-yml in the meantime, which solves the problem.
I would consider this issue fixed if you mention that switch here
https://developer.matomo.org/guides/tests-travis
or make it the default (why would anybody like to use Ubuntu precise still, which has reached it end of life?).

**Comment by Findus23** [comment]
This has been fixed a long time ago.
