### ISSUE TITLE
Unable to track outgoing link via Piwik

### ISSUE THREAD

**Issue by iomde** [matomo-org/matomo#13247]
Hello,

How can I see outgoing links via PIWIK?

the Outlinks section says: 'There is no data for this report'.

The aim is to track a single youtube video from the homepage of my website.

Here is the link: https://www.returningfromgermany.de/en

I hope someone can help me out!

Best regards!

**Comment by tsteur** [comment]
To track videos have a look at https://github.com/innocraft/plugin-MediaAnalytics 

Outgoing links within a youtube video are not being tracked if this is what you are looking for. Hope this helps. Please ask further questions in our forum: https://forum.matomo.org/
