### ISSUE TITLE
Demo / Default Dashboard: 2 Widgets not found

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13254]
2 Widgets are shown as not found: https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday
![screenshot_20180807-102433](https://user-images.githubusercontent.com/273120/43745309-2f3df0fa-9a32-11e8-999d-950ce172daea.png)
![screenshot_20180807-102526](https://user-images.githubusercontent.com/273120/43745310-2f72e0da-9a32-11e8-8b78-56725d93d05a.png)

Not sure if only a problem on demo or in general

**Comment by diosmosis** [comment]
The empty widget appears to be for a goal that doesn't exist: `widgetGoal_10`, not sure what could cause that, maybe a goal was deleted?

**Comment by diosmosis** [comment]
The other widget has a uniqueId of `widgetReferrersgetReferrerTypeforceView1viewDataTabletableGoalsdocumentationForGoalsPage1idGoalecommerceOrder`, not sure if this is expected or not. Wondering if it would be good to revert demo to 3.5.1 and see if the bug remains. If it's not a regression, then I don't think they're blockers for 3.6.0.

**Comment by tsteur** [comment]
I noticed there are also only 2 columns shown instead of 3 etc. @mattab I noticed there is a user dashboard entry where this dashboard is configured. Is this on purpose? Can we remove the goal reports? And can we maybe use the regular default dashboard?

**Comment by mattab** [comment]
@tsteur It was not on purpose, the dashboard default layout got updated. I've deleted the entry in `user_dashboard` and now it should look good :ok_hand:
