### ISSUE TITLE
Make all emails use the pretty HTML emails with branding

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#13251]
After #13250 theme variables will be defined in a class and the LESS variables will be generated in an event. Before these APIs are made public the following things need to be determined/done:

* Non-report emails need to be themed this way.
* Every part of report emails need to use the correct theme variables.
* If there are redundant properties in `EmailStyles` and `ThemeStyles` they should be resolved.
* If it should be allowed, PDF reports should be themed the same way as well.

At the moment the styling of reports/emails isn't entirely consistent so can't be made public API.

**Comment by diosmosis** [comment]
I think there are emails that are not styled at all (like the password reset email). I don't know how many email twig files use hardcoded inline styles instead of using the `...Styles` classes. Not sure about redundant properties, don't think PDF reports have been styled.

**Comment by mattab** [comment]
> Non-report emails need to be themed this way.

Now that you mention it, it would be I think good to have the consistent theming across all emails sent :+1: For the other points not sure, but maybe they don't take long?

**Comment by mattab** [comment]
Just renamed the issue title to clarify the impact from user point of view.

## Important

* When all emails are changed to HTML, it's important to remove the link on the Password Email reset. Instead people should be forced to copy paste the URL in their browser.
* Update the text from "visit the following link" to "please copy and paste the following link in your browser:"
