### ISSUE TITLE
Mobile: Icons not fully shown and shown not correctly

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13256]
This is on Android 7.0 with Via Browser and with Chrome. The arrow icon to sort the table is shown funny and the table icons in the dashboard are not fully visible (maybe also in regular reports).

![screenshot_20180807-102642](https://user-images.githubusercontent.com/273120/43745396-9069cf66-9a32-11e8-938e-7f8fac2f54ed.png)

**Comment by sgiehl** [comment]
With Chrome on Android 8 it looks correct. Not sure if there is still anything we could/should do.
