### ISSUE TITLE
Alert shown without content in dashboard 

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13257]
See 
![image](https://user-images.githubusercontent.com/273120/43745442-d47e650e-9a32-11e8-9273-c42c99b2a7e9.png)

To reproduce click on "Google" in the "Search Engines" widget in the default dashboard on https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday#?idSite=3&period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1

Didn't check if it maybe was already fixed.

**Comment by sgiehl** [comment]
That's caused by the SearchEnginesKeywordsPerformance plugin. I'll fix it there and release a new version   soon...
