### ISSUE TITLE
Unable to login in some instances upgraded to beta3

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13260]
After upgrading demo and demo2 to the beta3 (this update applied both beta2 and beta3 SQL upgrades), logging in does not work anymore: although there is no error and it appears to work, I'm still logged out after logging in.

However it seems to work fine on the localhost running beta3 also upgraded from beta1. It will be great to investigate this on demo/demo2 so we can address the root cause.

**Comment by GreenReaper** [comment]
The suggetsts that commit that this is due to a discrepancy between SQL time and PHP which might cause passwords to maybe look like they're expired. Is there a way to resolve this for those who hit it, perhaps through SQL? I'm not sure how to autoupdate once -b4 is out because I can't login...

**Comment by Findus23** [comment]
The easiest way to fix this is apply the changes from https://github.com/matomo-org/matomo/pull/13261 manually.

So either make the changes you can see in https://github.com/matomo-org/matomo/pull/13261/files
or download https://patch-diff.githubusercontent.com/raw/matomo-org/matomo/pull/13261.patch and apply it with `patch -p1 <13261.patch`

But maybe wait a minute until @diosmosis finished the changes.

**Comment by GreenReaper** [comment]
OK. I hackily just logged in to mysql and set
`update piwik_user set ts_password_modified = '2018-08-08 18:52:56';`
and it let me login. FWIW my system time zone is CEST and time_zone in MySQL is SYSTEM.
