### ISSUE TITLE
Impact of irregular capitalized URLS.

### ISSUE THREAD

**Issue by Frederic-P** [matomo-org/matomo#13263]
I noticed a minor issue when testing Matomo for the first time, though I'm not sure about the impact it has on the quality of the analytics. If a page has nog `title` attribute, and the Matomo tracking code is present, then it will use the URL  as content for the `name` field in the SQL-table `matomo_log_action`. The `idaction` and `hash` are different even though there's only a small change in the URL. 

here is my SQL-table:
|idaction|name|hash|type|url_prefix|
|---|-------------------------|-------|---|------|
| 1 | Matomo test             | hash1 | 4 | NULL |
| 2 | localhost/dariah/matomo | hash2 | 1 | 0    |
| 3 | localhost/Dariah/matomo | hash3 | 1 | 0    |
| 4 | localhost/DAriah/matomo | hash4 | 1 | 0    |

Visitors of the site can quite easily add random capitals all over the URL to generate much more records than needed. Could Matomo compensate for this by forcing lowercase on everything? Or at least add a configuration variable so that it forces lower case on the part that matches the configuration string. Or is there an option in the GUI that can compensate for this kind of behavior?

My matomo version is: 3.5.1

Googling it revealed a report dating back from 2015, though that one is closed: https://github.com/matomo-org/matomo/issues/7209

**Comment by Findus23** [comment]
I don't think Matomo can assume that the lowercase variant of a URL points to the same thing as the uppercase one. If the URL it maps to files on a Linux webserver, then it is always case sensitive and if there is some web application reading the URL it might also handle case differently. 

If you know for sure that your URLs are case insensitive, then you can normalize the data in the tracking code easily:

```javascript
_paq.push(['setCustomUrl', window.location.toString().toLowerCase()]);
```
