### ISSUE TITLE
travis tests all have the https check though it should be disabled

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#13271]
For some reason now UI tests aren't skipping the HTTPS check in `ControllerAdmin::notifyIfURLIsNotSecure()` which causes most tests to fail since the HTTPS notification shows up.

I checked and the host on travis-ci is still `localhost`, but `Url::isLocalHost(Url::getCurrentHost())` returns false for some reason. I'm not sure why. I tried w/o the strict `in_array()` call, but it didn't work.

I added a check for `if (defined('PIWIK_TEST_MODE')) return;` but that change was rejected.

**Comment by sgiehl** [comment]
It's not `localhost` but `localhost:3000`.
@diosmosis  your debugging output somehow got trimmed. printing the host `urlencoded` shows `localhost%3A3000`. Not sure why the port is now included in `_SERVER['HTTP_HOST']`

**Comment by diosmosis** [comment]
I see, that makes more sense now, thanks @sgiehl I'll put a fix in my other PR.
