### ISSUE TITLE
Updates all Guides and FAQs to reference the new "Write" permission

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13297]
we have introduced a new **Write** permission in Matomo in 3.6.0 in #13163 

To make sure this is clear and remove any confusion we will update all our help resources, and make sure our content consistently lists Write permission next to View/Admin or Super User, when applicable.

Also some important related changes were made:
* Admin users can now create users that have access to one of the website they have admin access for. This is a powerful new capability for admin users so we need to document it clearly especially in https://matomo.org/faq/general/faq_69/ and in https://matomo.org/docs/manage-users/
* maybe other changes worth mentioning?

### Content to review before we can close the issue

* User guides
* FAQs
* Developer guides

### Which content is affected?

To find affected guides and FAQs, we look for keywords such as: "permission", or "view" or "admin", or "Super user". 

Let's keep a list of all the pages that have been updated as part of this issue :heavy_check_mark:

**Comment by mattab** [comment]
Created [What is the ‘write’ permission in Matomo?](https://matomo.org/faq/general/faq_26910/)

Updated:

* https://matomo.org/docs/manage-users/
* https://matomo.org/faq/general/faq_70/
* https://matomo.org/faq/general/faq_69/
* https://matomo.org/faq/new-to-piwik/faq_46/
* https://matomo.org/docs/custom-dimensions/
* https://matomo.org/docs/custom-reports/
* https://matomo.org/docs/tracking-goals-web-analytics/
* https://matomo.org/docs/ab-testing/
* Updated the few guides on developer websites i could find mentioning "permission" or "access":
  * https://developer.matomo.org/guides/permissions
  * https://developer.matomo.org/guides/persistence-and-the-mysql-backend
  * https://developer.matomo.org/guides/apis

Still to do: 

* Can a 'write' permission user share a dashboard? Should be able to, check & update https://matomo.org/faq/how-to/faq_25986/
* Update https://matomo.org/docs/tag-manager/ to explain how Write permission differs from Admin?

**Comment by tsteur** [comment]
@mattab a "write" user cannot copy dashboard to other user. That would be only something for admins as a "write" user shouldn't be able to make changes on another users. That's something for admins. 

Seems like all FAQs updated, can we close the issue?

**Comment by mattab** [comment]
Makes sense indeed! 👍
