### ISSUE TITLE
When viewing dashboard as anonymous, an arrow is shown in dashboard selector

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13290]
![image](https://user-images.githubusercontent.com/273120/44067850-87a5fd16-9fcb-11e8-9a31-9d9b7559fd56.png)

seeing this only as anonymous. The regular icon/arrow is drawn in `::before`, and the misplaced icon/arrow in `::after` 
![image](https://user-images.githubusercontent.com/273120/44067886-b2227b82-9fcb-11e8-94b5-fb05235ef829.png)

Is this a regression? If not feel free to move out of 3.6 milestone.

**Comment by sgiehl** [comment]
I'm not able to reproduce that. Your html seems to differ from what I see:
![image](https://user-images.githubusercontent.com/1579355/44167722-3c96f280-a0cf-11e8-880f-9c46432519aa.png)

Not sure why the `Manage dashboard` is a `span` in your case. Are you maybe using a custom Theme?

**Comment by tsteur** [comment]
found the problem somewhere else 👍
