### ISSUE TITLE
Cronarchiving API error should be stderr and not stdout

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#13306]
See: https://forum.matomo.org/t/geoip2-libmaxminddb-maxmind-db-reader-php-c-module-performance/29534/12

```
INFO [2018-08-17 09:39:56] 14195 Error: Got invalid response from API request: ?module=API&method=API.get&idSite=1&period=year&date=last3&format=php&trigger=archivephp. Response was ‘a:2:{s:6:“result”;s:5:“error”;s:7:“message”;s:113:“Mysqli prepare error: Table ‘piwik.piwik_archive_blob_2018_02’ doesn’t exist in engine - caused by plugin Actions”;}’
```

This should be also written to STDERR instead of only to STDOUT to allow sending it via cron mail.

**Comment by mattab** [comment]
In 3.6.0 RC the script will now return an error code of 1. Maybe this would fix the issue for you as well, as it will cause cron emails to be sent

**Comment by fdellwing** [comment]
Should be enough to be happy, I think.
