### ISSUE TITLE
When you are logged out, the URL gets lost when you log in

### ISSUE THREAD

**Issue by chris-morgan** [matomo-org/matomo#13328]
**Steps to reproduce:**

1. I am unauthenticated.
2. I load `/index.php?module=MultiSites&action=index&idSite=1&period=range&date=last30`.
3. Matomo appropriately complains of the permissions error and presents me with a login form.
4. I log in.

**Expected result:** I am at the page I requested, `/index.php?module=MultiSites&action=index&idSite=1&period=range&date=last30`.

**Actual result:** I am at the site’s default URL, which for me is `/index.php?module=CoreHome&action=index&idSite=1&period=range&date=last30`.

**Remarks:** this is more common than you might imagine for me: if I have a browser tab open persistently, #13327 means that I will be logged out fairly regularly, and then when I go to the open tab my place is lost.

**Comment by tsteur** [comment]
👍  be good to fix this. Getting bit annoyed by this as well.

**Comment by chris-morgan** [comment]
Might need to be a little bit careful about how the hash is handled with this, to ensure that it’s preserved. (BTW, what’s with that, having both a real query string and a hash query string? Is it a relic of the days before `history.pushState` was universally supported?)

**Comment by tsteur** [comment]
> BTW, what’s with that, having both a real query string and a hash query string? Is it a relic of the days before history.pushState was universally supported

Yes it is. And there's now some logic checking for hashes etc making it quite some work to make the switch to pushState. Will happen though at some point 👍

**Comment by chris-morgan** [comment]
See my comment in #13441: this is not fixed, because the hash still gets lost, and the hash is used for critical navigation.
