### ISSUE TITLE
Real-time widget border is slightly misplaced

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13322]
See image. This happens for the first visit. I tried to fix it but not sure where it is coming from. The border should be 1px further up. It seems to be caused by #visitsTotal but not sure.

![image](https://user-images.githubusercontent.com/273120/44366348-8002be00-a520-11e8-9d9d-1c6274d2163c.png)

**Comment by sgiehl** [comment]
The datatable row columns (td) within #visitsTotal all have a border-bottom and the the #visitsLive below has a border-top
