### ISSUE TITLE
Regular expression to exclude URL param does not work

### ISSUE THREAD

**Issue by gtmadev** [matomo-org/matomo#13336]
### How to reproduce

The following example assumes a URL like `http://www.foo.com/payment/EF123-233444df`.
We want to strip away the `EF123-233444df` parameter, which is the payment ID.

1. In the "Excluded Parameters" section of site settings, add an exclusion line.
`[^payment/]+$` 

![screenshot_4](https://user-images.githubusercontent.com/30833539/44440640-96ca1300-a5fb-11e8-907e-794e0c9f693f.png)
(this reg expression does test out fine - see image:

![screenshot_2](https://user-images.githubusercontent.com/30833539/44440529-05f33780-a5fb-11e8-9244-540beb27a777.png)

2. Navigate to the URL, and then observe the log result. It will still contain the filtered parameter.

![screenshot_3](https://user-images.githubusercontent.com/30833539/44440599-6aae9200-a5fb-11e8-8b28-f752e340678e.png)

**Note: The payment parameters says "3". That is only because my test is different than my example URL stated above. The actual testing URL looks like this: `/payment/3`**

**Comment by fdellwing** [comment]
This function handles only get parameters.

**Comment by Findus23** [comment]
"Excluded Paramters" only applies to URL parameters (as in GET paramters). If you want to modify the URL the best way is to use `_paq.push(['setCustomUrl', 'theurl']);` to set a custom URL JS-side or write a tracking plugin that applies the change during tracking.
