### ISSUE TITLE
Call to undefined method Piwik\API\Request::getMethodIfApiRequest()

### ISSUE THREAD

**Issue by XinfinityoO** [matomo-org/matomo#13331]
Upgraded to v3.60 Rc1
Getting the following error.
Cant load any page or login

Call to undefined method Piwik\API\Request::getMethodIfApiRequest()

Had to restore back from backup

**Comment by diosmosis** [comment]
hi @XinfinityoO, I was able to upgrade from 3.5.1 to 3.6.0-rc1 w/o issue. My guess is that the update didn't update one or more files correctly. If this error happens again, can you check if the core/API/Request.php on your server file matches https://raw.githubusercontent.com/matomo-org/matomo/9227214071990af8ae68aa6b7a3b1c527bb7359f/core/API/Request.php ?

CC @tsteur

**Comment by diosmosis** [comment]
Note: you could also try the manual three step update if this happened with the automatic update: https://matomo.org/docs/update/#the-manual-three-step-update

**Comment by XinfinityoO** [comment]
thanks. manual update worked fine.
