### ISSUE TITLE
Segmented visitor log does not inherit existing segment

### ISSUE THREAD

**Issue by fatica** [matomo-org/matomo#13344]
When you view the dashboard segmented (E.g. Visitor location = US), then you click on a row to "Open segmented visitor log", the resulting visitor log is not segmented by the dashboard-level segment.

![image](https://user-images.githubusercontent.com/836159/44597259-42a26880-a78c-11e8-8aa5-052e52b4793e.png)

In the screenshot above, I would expect the visitor log to only show the visits that resulted in the 21 impressions.  However I actually receive a list of all visitors that generated impressions for that content (a much long list)

**Comment by metalocator** [comment]
Awesome, thank you!
