### ISSUE TITLE
[Website] Update really old screenshot in docs

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#13341]
This screenshot (https://matomo.org/docs/update/#3-update-matomo) should be replaced with a somewhat newer image. Showing a screen for Piwik version 0.2.x seems really weird. 

P.S. Maybe edit this screens to: https://matomo.org/docs/update/#click-on-the-alert-box-in-matomo
https://matomo.org/docs/update/#read-the-message-and-click-update-automatically
https://matomo.org/docs/update/#watch-the-magic

**Comment by Findus23** [comment]
This has been solved thanks to @NanorPiwik
