### ISSUE TITLE
Use random_bytes() instead of uniqid/md5 in Common::generateUniqId() for improved security

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13357]
Replace Common::generateUniqId()'s use of md5 & uniqid w/ random_bytes() (there's are polyfills for PHP 5.*, eg, https://github.com/symfony/polyfill). Would prevent attackers from being able to guess what new token auths would be.

Noted in https://github.com/matomo-org/matomo/pull/12208

**Comment by sgiehl** [comment]
already fixed with #13357
