### ISSUE TITLE
In visitor log do not show the domain for pageviews

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13359]
See 
![image](https://user-images.githubusercontent.com/273120/44748762-a948cd00-ab64-11e8-8533-b42afda2353c.png)

The domain is in most cases not needed and visible on hover anyway. This de-clutters the visitor log and makes it more clear which pages a user viewed. Also when the domain is really long, parts of the URL are otherwise not visible.

In case this is a problem to remove it, could be a config or better a check if multiple URLs are configured for a site and show it depending on that for example.

refs https://github.com/matomo-org/matomo/issues/13332

**Comment by mattab** [comment]
> In case this is a problem to remove it, could be a config or better a check if multiple URLs are configured for a site and show it depending on that for example.

It makes sense to remove the domains from URLs, when there is only one URL defined for the site :+1:  (otherwise it's important to show the various domains to remove any possible confusion.)
