### ISSUE TITLE
3.6.0 period=day&date=today no longer highlights current date

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#13369]
Hi, after upgrading to 3.6.0 when we use "period=day&date=today" after ? in url parameters, we no longer have selected/highlighted current (today) date.

If I replace "today" with actual (hard coded) current date value, then it is shown as a square around current date.

![2018-08-30_012644](https://user-images.githubusercontent.com/5383059/44821095-0fc8fc00-abf4-11e8-9912-386aa2f4ef49.png)

![2018-08-30_012705](https://user-images.githubusercontent.com/5383059/44821096-0fc8fc00-abf4-11e8-8dcd-ac6376c5b02e.png)

I currently don't have earlier 3.5.x version installed (I upgraded all instances at once, what a mistake!) to verify this, but I am pretty sure it worked before. In Piwik 2.x which I still keep works fine.

**Comment by sgiehl** [comment]
Thanks for the report.
That also doesn't work anymore with `yesterday` and is reproducible on our demo.

**Comment by mcmarable** [comment]
Noted same thing #13367

**Comment by dev-101** [comment]
Any ETA on new release? This bug alone should be enough to push new version, as it skews daily reports because of date/timezone mismatch.

Thanks

**Comment by mcmarable** [comment]
@dev-101 Agree... Does anyone have a temporary solution of fix?

**Comment by dev-101** [comment]
Fix is already applied, see above changes #13373

You can manually replace that file or add code changes, but Matomo uses caching, and another omission is that there is no way to clear or regenerate template cache files, unless I missed that option somehow.

**Comment by mcmarable** [comment]
I have edited the file specified in #13373 and cleared all caches and my install is still exhibiting the exact same behavior.

**Comment by sgiehl** [comment]
@mcmarable  did you clear the `tmp` directory of Matomo and your browser cache after applying the patch?

Due date of 3.6.1 is currently September 22...

**Comment by mcmarable** [comment]
@sgiehl Apologies, yes I did clear out /tmp but hard clearing the browser cache is what did the trick. Thank you

**Comment by dev-101** [comment]
Not sure if it is related, but now default "Visits over time" widget does not include "today", even when it is set to "/var/www/tehnoblog.org/piwik/tmp"Last 30 days (including today)". Removing tmp/cache doesn't help. Will wait until server's time pass the new day mark, if it makes any difference.

**Comment by dev-101** [comment]
Not sure if it is related, but now default "Visits over time" widget does not include "today", even when it is set to "Last 30 days (including today)". Removing tmp/cache doesn't help. Will wait until server's time pass the new day mark, if it makes any difference.

**Comment by diosmosis** [comment]
@dev-101 can you post a screenshot (including an open calendar to see the selected date) + URL w/ any sensitive info redacted? Also would be good to know what timezone your website is in & what timezone you are currently in.

**Comment by dev-101** [comment]
I can confirm that this is not related to the fix for this particular issue (day highlight). Reverting changes did not fix the problem with today reports -1 day behind.

@diosmosis 
My server's time is synchronized with my local time down to the ~second. However, for some reason Matomo is working in GMT/UTC.

I have checked zones and dates, and all checks up, including PHP CLI, and this was not the problem in 3.5.1 and I haven't changed anything in php/server config in the meantime.

**Comment by dev-101** [comment]
I have checked all 3.6.0 installations on different servers, all have the same problem I didn't noticed before.
3.5.1 that I forgot to upgrade in one domain is working fine without this problem.

**Comment by dev-101** [comment]
I've noticed that in 3.5.1 under Admin Dashboard > Websites > Settings we could select the city, but in 3.6.0 only the country. Although this change alone should not affect small countries, which are likely in the same timezone, this means that some changes made there might be responsible for this problem, and unrelated to the original issue reported here.

P.S.
UTC time now turned to new date/day, and so Matomo 3.6.0 "correctly" respects "today" option/setting.

**Comment by diosmosis** [comment]
@dev-101 just in case you're not aware, every website has a configured timezone:

![image](https://user-images.githubusercontent.com/125140/45656795-3912d480-ba9c-11e8-8a57-67622aba9a13.png)

Reports are shown for dates in that timezone (so 'today' is today in the website's timezone).

**Comment by dev-101** [comment]
Thanks, just checked: all settings are the same (global + per website) in all instances that I run.
Time zones are all "wrong" (read: set correctly but still run as GMT/UTC) in all cases of 3.6.0 (updated from 3.5.1, not fresh installs).

**Comment by dev-101** [comment]
"Visitors in Real-time" displays correct times, this seems to affect only some widgets like "Visits Over Time", tables like Behaviour > Pages etc.

**Comment by diosmosis** [comment]
@dev-101 I was able to reproduce the issue w/ evolution graphs and created a fix here: https://github.com/matomo-org/matomo/pull/13445. Looks like this has been a problem for a while, not sure why it wasn't apparent before.

Was not able to reproduce this issue w/ other types of reports that only span one period (like table reports).

**Comment by dev-101** [comment]
v3.6.1

While date highlighting is fixed, **Visits Over Time** widget still works wrong. It is 1:00 AM here and the widget's chart still counts for the previous day.
