### ISSUE TITLE
upgrade to 3.6.0 failed with Class 'Piwik\Twigÿÿ' not found

### ISSUE THREAD

**Issue by pmaubertel** [matomo-org/matomo#13366]
While doing the automatic upgrade from version 3.5.1 to 3.6.0, the upgrade process failed
with the following message : 
An error occurred
Class 'Piwik\Twigÿÿ' not found

**Comment by sgiehl** [comment]
Did you meanwhile manage to update? The error message seems weird, as their isn't and shouldn't be any class called `Piwik\Twigÿÿ`. Maybe some files got corrupted while updating...

**Comment by sgiehl** [comment]
closing now. @pmaubertel  if you can still reproduce that issue feel free to create a new one with a detailed explanation how to reproduce.
