### ISSUE TITLE
"Report date to load by default" Broken in 3.6.0

### ISSUE THREAD

**Issue by mcmarable** [matomo-org/matomo#13367]
After upgrading to 3.6.0, "Report date to load by default" when logging in is off by one (1) day if any of the following highlighted options are selected:

![image](https://user-images.githubusercontent.com/42813646/44803858-a7dfca80-ab8d-11e8-8eca-54ddc0b8a746.png)

Here is the result in the dashboard:

![image](https://user-images.githubusercontent.com/42813646/44803957-ef665680-ab8d-11e8-866f-f54ea4362b2a.png)

**Comment by tocsinde** [comment]
The last day of the range is missing in the description of the X axis, but nevertheless the last point of the graph is showing the data from the correct day. You can see it while hovering on the dot.

**Comment by mcmarable** [comment]
Screenshots were taken 5 minutes prior to posting the issue. The second date in image above should be 2018-08-29 as it was prior to updating to 3.6.0 this morning. Note the date range is what is automatically populated when selecting "Last 30 days (including today)".

**Comment by sgiehl** [comment]
@mcmarable  which timezone is you website in matomo set up? And which timezone has your computer configured?

**Comment by mcmarable** [comment]
@sgiehl - America/New York. The solution provided in #13369 does not resolve this issue

**Comment by sgiehl** [comment]
Anyone still having this issue with Matomo 4?

**Comment by sgiehl** [comment]
Closing as there hadn't been any recent reports, so we assume this problem was meanwhile fixed.
