### ISSUE TITLE
File integrity check fails in 3.6.0

### ISSUE THREAD

**Issue by thueske** [matomo-org/matomo#13364]
Hey,

the file integrity check in 3.6.0 shows the following errors:

```
Es wurden unerwartete Dateien in deiner Matomo-Installation gefunden.
--> Bitte lösche diese Dateien, um Fehler zu vermeiden. <--

Zu löschende Datei: vendor/davaxi/sparkline/autoload.php
Zu löschende Datei: vendor/davaxi/sparkline/src/autoload.php
Zu löschende Datei: vendor/piwik/device-detector/autoload.php


Um alle diese Dateien auf einmal zu löschen, kannst du folgenden Befehl ausführen:
rm "/html/matomo/vendor/davaxi/sparkline/autoload.php" "/html/matomo/vendor/davaxi/sparkline/src/autoload.php" "/html/matomo/vendor/piwik/device-detector/autoload.php"
```

Installation was made via the zip file from matomo.org

**Comment by fdellwing** [comment]
You can delete the files, they are not needed.

**Comment by thueske** [comment]
Yes, I know @fdellwing... but I think the files should'nt be included - stable release with warnings isn't nice :)

**Comment by fdellwing** [comment]
That's why the second paragraph is there ;)

**Comment by Findus23** [comment]
Thanks @thueske for reporting.
As @fdellwing mentioned the files can be deleted, but nevertheless they should normally get deleted on the build. 

This seems to be caused by an edge-case in the build-script: https://github.com/matomo-org/matomo-package/issues/77

**Comment by mattab** [comment]
FYI:  3.6.0 was re-packaged without the bug, and 3.6.1-b1 is available to remove these warning messages in system check about */autoload.php files
