### ISSUE TITLE
WARNING: /var/www/html/plugins/API/API.php(401): Notice - compact(): Undefined variable: idGoal

### ISSUE THREAD

**Issue by rockerdaddy** [matomo-org/matomo#13375]
Fresh VM, fresh install, Matomo 3.5.1. A settings-page upgrade three days later brought the message along into 3.6.0. Full message, which appears in multiple popups (scheduled task?) on the Settings page:

WARNING: /var/www/html/plugins/API/API.php(401): Notice - compact(): Undefined variable: idGoal - Matomo 3.6.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)

CentOS 7.5.1804 (Core)
Matomo version: 3.6.0
MySQL version: 5.5.56-MariaDB
PHP version: 7.3.0beta2

Goals module has been disabled in case that fixed it. (Narrator: "It didn't.")

**Comment by sgiehl** [comment]
refs #13418
