### ISSUE TITLE
system check for forced SSL connection shouldn't warn behind reverse proxy

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13374]
followup to #13193 and reported on the forum:
https://forum.matomo.org/t/matomo-behind-reverse-proxy-and-force-ssl-setting/29672

When `assume_secure_protocol=1` is already set, Matomo shouldn't complain to setup SSL.

**Comment by cpoetter** [comment]
I am seeing the same bug. Is there a timeline for a fix?

**Comment by Findus23** [comment]
Two years later I was again thinking about this and I'm not 100% sure if the current status isn't correct. If I am not mistaken `force_ssl=1` tells Matomo that it is set up via HTTPS and it therefore should use only HTTPS URLs, secure cookies, etc.

`assume_secure_protocol=1` alone does not force that, which means that if you use Matomo behind a reverse proxy that adds SSL, you still need to add `force_ssl=1` to get secure cookies (as the system check reminds)

There is even a function in Matomo that checks this case:

https://github.com/matomo-org/matomo/blob/115527353a9e75e01aa4d263408956ae45403bea/core/Url.php#L711-L723

Of course one could argue that `assume_secure_protocol=1` should always automatically set `force_ssl=1`, but I am also not sure about that as that would make the meaning of `force_ssl` confusing.

In case I am wrong, changing the check is simply a matter of modifying this:

https://github.com/matomo-org/matomo/blob/b16a791aa3650d85af829156129c2bd44c7cb075/plugins/Diagnostics/Diagnostic/ForceSSLCheck.php#L48-L52

**Comment by tsteur** [comment]
When `assume_secure_protocol=1` is configured, then this system check should not complain.

**Comment by tsteur** [comment]
As suggested in #17861 we keep the system check as it is and instead adjust the documentation and mention that we suggest to also set `force_ssl=1` when someone configures assume secure protocol for security to make sure any HTTP request is redirected to HTTPS.

This is to be done in https://matomo.org/faq/how-to-install/faq_98/ and could also mention it in https://matomo.org/faq/how-to-install/

**Comment by geekdenz** [comment]
> This is to be done in https://matomo.org/faq/how-to-install/faq_98/ and could also mention it in https://matomo.org/faq/how-to-install/

OK, added it:
https://matomo.org/faq/how-to-install/faq_98/
and it automatically got added to
https://matomo.org/faq/how-to-install/

**Comment by tsteur** [comment]
Nice @geekdenz  👍  Maybe be good to mention that it will cause HTTP requests to be redirected to HTTPS. And could be good to put in a link to https://matomo.org/faq/how-to/faq_91/ to get more information if needed.

**Comment by geekdenz** [comment]
> put in a link to https://matomo.org/faq/how-to/faq_91/ to get more information if needed.

done

**Comment by tsteur** [comment]
Great 👍 💯
