### ISSUE TITLE
default all websites dashboard show 0 visits in all the sites

### ISSUE THREAD

**Issue by juanremi** [matomo-org/matomo#13370]
After upgrade matomo to 3.6.0, when i load the "All websites dashboard" with the url:
index.php?module=MultiSites&action=index&idSite=1&period=day&date=today

all the sites have 0 in their metrics (visits, pageviews, etc), ad you can see on the attached image
![as5d45asdadsdssdasd](https://user-images.githubusercontent.com/5168033/44827713-eef3ad00-abd9-11e8-9a11-b017a40ee873.jpg)

to see the values, i need select the date of today and load the data via the url:
index.php?module=MultiSites&action=index&idSite=1&period=day&date=2018-08-29&updated=1

**Comment by GitPuffy** [comment]
Same issue for me with a clean installation of version 3.8.1

**Comment by mattab** [comment]
Thanks for creating the issue.

**Do you have logs registered in your Matomo (Piwik) database?** If your Matomo tracking code is properly installed, Matomo would record visits in your database. To check if you have logs in your database, go to Matomo > Visitors > Visits log, and select “today” in the calendar. If you see recent visitor information, it means that the visitor tracking is working, but maybe there is a problem with reports archiving.

**If you see visits in the Visits Log but not in the reports** then please check your archiving works correctly.
-> Please review our doc here: https://matomo.org/docs/setup-auto-archiving/

This should resolve your issue. Please check and if you have any issue let us know or re-open the issue.

**Comment by danger89** [comment]
> select “today” in the calendar. 

Yea after the archive setup in crontab (and running it once manually). The actual solution in my case was indeed setting the day to today. Could Matomo not set the day to today automatically when I load the webpage?

**Comment by tsteur** [comment]
You can load today by default in your personal settings under Administration
