### ISSUE TITLE
dropdown-menu missing causing fatal error after update to 3.6.0

### ISSUE THREAD

**Issue by gemal** [matomo-org/matomo#13382]
A fatal error occurred

The following error just broke Matomo (v3.6.0):

An exception has been thrown during the rendering of a template ("The ui asset with 'href' = /var/www/XXXX/plugins/CoreHome/angularjs/dropdown-menu/dropdown-menu.directive.less is not readable").

in

/var/www/XXXX/plugins/CoreUpdater/templates/runUpdaterAndExit_welcome.twig line 8

Troubleshooting
Follow these steps to solve the issue or report it to the team:

    If you have just updated Matomo to the latest version, please try to restart your web server. This will clear the PHP opcache which may solve the problem.
    If this is the first time you see this error, please try refresh the page.
    If this error continues to happen, we appreciate if you send the error report to the Matomo team.

**Comment by sgiehl** [comment]
Maybe the file wasn't created correctly during the update? Please try reuploading Matomo manually
