### ISSUE TITLE
Manage Users: SQL Error for role write

### ISSUE THREAD

**Issue by Legion2** [matomo-org/matomo#13384]
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND (u.login LIKE '%user%' OR u.email LIKE '%user%') GROUP BY u.lo' at line 4`
Can't filter for username and role at the same time if role `Write` is selected.

Steps to reproduce:
- matomo version 3.6.0
- php version 7.0.7
- open "Manage Users"
- type `user` in the "User search" field
- select `Write` in the Filter by access field

Expected:
- no error is displayed and the all users with name containing `user` and role `Write` are displayed

Actual:
- Error `SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND (u.login LIKE '%user%' OR u.email LIKE '%user%') GROUP BY u.lo' at line 4` is displayed.

**Comment by fdellwing** [comment]
Can confirm this error.
