### ISSUE TITLE
Integrity check asks to delete PiwikTracker.php

### ISSUE THREAD

**Issue by userpqr** [matomo-org/matomo#13381]
Recently I upgraded Matomo to version 3.6.0 After the upgrade I get the following errors in integrity check -

Files were found in your Matomo but we didn't expect them.
--> Please delete these files to prevent errors. <--

File to delete: PiwikTracker.php
File to delete: misc/others/api_internal_call.php
File to delete: vendor/davaxi/sparkline/autoload.php
File to delete: vendor/davaxi/sparkline/src/autoload.php
File to delete: vendor/piwik/device-detector/autoload.php

To delete all these files at once, you can run this command:
rm "***/PiwikTracker.php" "***/api_internal_call.php" "***/autoload.php" "***/sparkline/src/autoload.php" "***/device-detector/autoload.php" (some information is redacted)

I am not sure why I am getting this error. Before the upgrade, I did not see these errors. Moreover, if I click on website->settings, it shows "Forbidden" after the upgrade. Not sure if these two errors are related either. Can someone please help ?

Thanks,

**Comment by mattab** [comment]
Hi there, to fix the issue please delete the file(s) as the message recommends. if you still experience the other problem, please create a separate issue and we'll investigate.
