### ISSUE TITLE
After Update to matomo 3.6 problems with PHP FPM versions

### ISSUE THREAD

**Issue by kanow** [matomo-org/matomo#13389]
Hi,
after updating matomo to 3.6 we can't use matomo on php FPM versions. We must switch to CGI versions to get matomo working. Those problems are in different version, from 5.5 till 7.1.
The last upgrade step, the database update, failed with 500 error. But on reloading the page I can login into the matomo user interface and everything seems working correctly. 
Error Log says:

```
[Wed Sep 05 18:11:35.038238 2018] [fcgid:warn] [pid 18398:tid 139911537600256] (104)Connection reset by peer: [client xx.xx.xx.xx:55632] mod_fcgid: error reading data from FastCGI server, referer: https://piwik.customerdomain.de/index.php?module=CoreUpdater&action=
[Wed Sep 05 18:11:35.038283 2018] [core:error] [pid 18398:tid 139911537600256] [client xx.xx.xx.xx:55632] End of script output before headers: index.php, referer: https://piwik.customerdomain.de/index.php?module=CoreUpdater&action=
```
PHP 7.1 is running.

**Comment by fdellwing** [comment]
Please check if the FPM server has the rights to access the files.

**Comment by mattab** [comment]
I also experienced this problem once but I couldn't also see any information in the log and ended up ignoring it as everything was working after this error

**Comment by michalkleiner** [comment]
Hello there! We will close this issue now as there's no response for several years. We hope you were able to solve the problem, but feel free to reopen this issue or create a new issue with replication steps if the issue still persists. Thank you for your understanding.
