### ISSUE TITLE
Save GeoIP DB in user dir

### ISSUE THREAD

**Issue by Dreamsorcerer** [matomo-org/matomo#13396]
In the Geolocation settings, there is an option to install the GeoIP database. However, as I have the Matomo code installed in /usr/share/matomo/ and owned by root (as per the Debian package install), Matomo is unable to save the file.

Please change the location of this database to somewhere in the user directory, which is writeable by the server.

I have changed `PIWIK_INCLUDE_PATH` to `PIWIK_USER_PATH` at:
https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/GeoIp2/LocationProvider/GeoIp2.php#L128
and
https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/UserCountry/LocationProvider/GeoIp.php#L202

After creating a `misc` subdirectory in the user dir, it is successfully downloading the file.

**Comment by sgiehl** [comment]
we will make the path for GeoIP2 configurable using DI. See #13913
GeoIP Legacy won't be changed anymore, as it is discontinued by Maxmind
