### ISSUE TITLE
undefined method createTestConfig() in BenchmarkTestCase 

### ISSUE THREAD

**Issue by aaaronfeng** [matomo-org/matomo#13398]
When I run the tests in the Benchmarks package, I got the following error:

undefined method ```createTestConfig()```

After checking the commit history, the method ```createTestConfig``` belong to the class ```IntegrationTestCase``` which used to be the superclass of ```BenchmarkTestCase```

**Comment by diosmosis** [comment]
I might be wrong, but the benchmark code there isn't really maintained. Could probably be removed at this point. CC @tsteur

**Comment by tsteur** [comment]
Yeah I'd say so, could be removed. I didn't even really know it existed. It isn't maintained and I think even the automated tests might not execute them.
