### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by JeffS25** [matomo-org/matomo#13395]
Hello Team,

We are getting 401 authorization error in piwik.php, when we check for any of the site in Piwik, the error comes only when we login for the first time. Once we hit other links there is no authorization error.
Could you please help us out on this. 

Thanks.

**Comment by sgiehl** [comment]
Access to piwik.php should not be restricted in any way. Did you maybe set up a global htaccess rule or similar?
For further support you may also try to get some help on our forum.
