### ISSUE TITLE
different visitor id is getting generated for the sites

### ISSUE THREAD

**Issue by Vinutab** [matomo-org/matomo#13399]
Hi Team,

We have a site A,B and C where the tracking is enabled. For the site B, we have set the user id. We have a link in site A to navigate to the site B. When we checked the visitor id, it's different for the site A and site B. But the visitor id is matching for the site A and C. This issue is happening mainly in the IE.

Could you please help us.

Regards,
Vinuta

**Comment by MichaelHeerklotz** [comment]
Hello Vinuta,
this is how it works at the moment. Setting the user id will overide the visitor id with the user id.

Greetings,
Michael

**Comment by mattab** [comment]
This was fixed and now the visitor IDs are not tied to the user id anymore. see: https://github.com/matomo-org/matomo/pull/14360
