### ISSUE TITLE
Laravel Php error

### ISSUE THREAD

**Issue by vicky01091991** [matomo-org/matomo#13409]
Hello Guys,

I am getting this error
"<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />"

for that i made changes in php.ini file always_populate_raw_post_data to -1 after tha also i am getting same error any one help me out for this error. I am using php5.6.16 version

**Comment by fdellwing** [comment]
Did you restart the webserver (or FPM-server) after modifying the php.ini?

**Comment by tsteur** [comment]
I recommend you have a look at https://forum.matomo.org/t/always-populate-raw-post-data-1-and-yes-i-did-it/16664 and https://github.com/matomo-org/matomo/issues/8812

I would otherwise recommend to google for this error or post in a Laravel forum.
