### ISSUE TITLE
Same icon is used for "segmented visitor log" and "show visitor profile"

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13419]
![image](https://user-images.githubusercontent.com/273120/45456393-b0640380-b73e-11e8-936d-5811a665091d.png)

Need to replace the "segmented visitor log" icon I would say.

**Comment by tsteur** [comment]
It is hard to find a good icon for segmented visitor log with a compatible license. What about eg 

![image](https://user-images.githubusercontent.com/273120/45728649-f7f5fe00-bc1c-11e8-9d6e-7c12281d4a9a.png)

showing some visits/entries will be shown part kind of only to part of it (the broken part in the top right corner)

It would have been nice to have a "user" icon in there, ideally stacked or so in some way but it can be quite confusing with the "segment" icon and the "visitor profile" icon.

Maybe 
![image](https://user-images.githubusercontent.com/273120/45728734-75ba0980-bc1d-11e8-8e88-74887a2a8f9b.png)

**Comment by mattab** [comment]
Looks nice already :+1: feedback:

* in "Visitors", it's hard to click the icons to show profile/segmented log. So would be more usable to show labels next to icons like "View Visitor profile" and "View Visits log"
* can we show the paging info below "Visitors"?
* in "Visitors", if no user id is set, maybe we could hide the "User id" column
* One idea was to make the list of "Visitors" look a bit like the Visits log to be consistent, but without action details... it would be good to find ways to make it overall more visual, ideally a "Wow" moment when you open the report (like what people experience first time they use the Visits log)... Maybe we could show icons for country, device? (eg. picking the last visit's details). Or even better we could show a full summary of the visitor, in one line (like a condensed version of a visitor profile's left sections)
* Can we maybe rename "Visitors" menu to "Audience" as to prevent confusion between similar terms Visitors/Profiles?
* in "Real-time visitors" not sure if the data reloads works
* for "Segmented visits log" icons, just found those potential ones, but didn't check what it woud look like... maybe the second one is good?

![peoplel](https://user-images.githubusercontent.com/466765/45991696-3175b000-c0da-11e8-8fcd-27e63ebfcbce.png)
![contacts](https://user-images.githubusercontent.com/466765/45991697-3175b000-c0da-11e8-9509-cc35af63e2ba.png)

maybe using first one for "Visits log" and second one for visitor profile, would work?
![double](https://user-images.githubusercontent.com/466765/45991803-8ca7a280-c0da-11e8-8ab4-b4617d9057c1.png)

**Comment by tsteur** [comment]
I think you are commenting on the wrong issue @mattab 

This is only about the issue re the icons. The contacts icon works maybe best. The other ones are too confusing with other icons we use such as segmentation.

> in "Visitors", it's hard to click the icons to show profile/segmented log. So would be more usable to show labels next to icons like "View Visitor profile" and "View Visits log"

Nah we won't be doing this for consistency etc. Some day we will change behaviour of row actions.

> can we show the paging info below "Visitors"?

Paging info does not really work here unless we grouped all visitors with every live query to find out how many there are.

> One idea was to make the list of "Visitors" look a bit like the Visits log to be consistent, but without action details... it would be good to find ways to make it overall more visual, ideally a "Wow" moment when you open the report (like what people experience first time they use the Visits log)... Maybe we could show icons for country, device?

showing device etc doesn't work as there are multiple visits grouped into one with different devices, locations etc. would rather look messy and not too valuable etc. This is similar report as GA has.

> Can we maybe rename "Visitors" menu to "Audience" as to prevent confusion between similar terms Visitors/Profiles?

Audience be confusing with our media reports where we talk about audience as in has listened or watched to something. Maybe different name?

**Comment by mattab** [comment]
oops, meant to comment in https://github.com/matomo-org/matomo/pull/13414

> This is similar report as GA has.

there is a huge difference in readability and feeling of browsing through users when using Visits log (visual and agreeable) VS Visitors table (tabular & not visual). Would be good to do much better visually than GA, but it's not easy to do and not required in first iteration.. so we can see later...

>  Audience be confusing with our media reports where we talk about audience as in has listened or watched to something. Maybe different name?

couldn't find better than Audience so far. Another good one may be "Overview" as it gives an overview of everyone, of all visits/visitors.

**Comment by tsteur** [comment]
> couldn't find better than Audience so far. Another good one may be "Overview" as it gives an overview of everyone, of all visits/visitors.

It's probably hard to just use a synonym for it. Wouldn't make it too much clearer or rather confusing maybe. Would maybe something like "Visit(or) Attributes" or so make sense? But this wouldn't quite match "Engagement" and "Times".  Although those two reports could be potentially maybe even fit better under "Behaviour"?

> there is a huge difference in readability and feeling of browsing through users when using Visits log (visual and agreeable) VS Visitors table (tabular & not visual). Would be good to do much better visually than GA, but it's not easy to do and not required in first iteration.. so we can see later...

I don't think the goal/purpose of this report here is not to "browse" through it but really identify high value visitors of a specific segment in an efficient way and analyze their behaviour and to complete this missing part if userIds are not used. With Matomo 4 we can hopefully also add a revenue column / life time value column etc.
