### ISSUE TITLE
Multi_server_environment var should disable update via GUI module but it doesn’t

### ISSUE THREAD

**Issue by pestevao** [matomo-org/matomo#13417]
![___79749cacc66ff81522ec7505a5f6dee9ff90b672](https://user-images.githubusercontent.com/8450871/45431274-3a5c8f80-b69f-11e8-95d1-1b8833ef8440.jpg)

With the mouse over the “NEW UPDATE: MATOMO 3.6.0 !” (top hand) text you can go to the update page if you click on it (see URL at bottom hand).

https://forum.matomo.org/t/multi-server-environment-var-should-disable-update-via-gui-module-but-it-doesnt/27761/3?u=pestevao

Pedro

**Comment by rick-pri** [comment]
Yup, I just found this out too in the 3.13.x releases (still!)
