### ISSUE TITLE
Getting visitor id

### ISSUE THREAD

**Issue by ccesarrod** [matomo-org/matomo#13411]
Hello,

 I am able to track visitors with their email. Those users get an id that i can see in the profile. How can I get the visitorID base on the userid I assigned and get their searches etc?

**Comment by tsteur** [comment]
The visitor ID is shown in the top of the visitor profile:

![image](https://user-images.githubusercontent.com/273120/45388286-9f4ac200-b66c-11e8-9bca-9e4852d1edeb.png)

You can use the ID for example by using [Segments](https://matomo.org/docs/segmentation/) and get their searches etc. You may also click on the export icon next to the ID to see the raw data.

**Comment by tsteur** [comment]
The visit list on the right should also show you all searches (but also many other actions)

**Comment by ccesarrod** [comment]
I got it to work using Live.getVisitorProfile and using segments with user ID. Thank you for the suggestion.

I am new to this API , is there a way to get, using the api , recent searches by visitorid. This Live.getVisitorProfile works but bring all other info that I don't need.

Thank you

**Comment by tsteur** [comment]
Not sure if it works but worth a try... you could add to the segment `actionType==sitesearches`  or `pageviews, contents, sitesearches, events, outlinks, downloads`... otherwise you may need to filter client side the actions.
