### ISSUE TITLE
Statistics gap with Prestashop

### ISSUE THREAD

**Issue by KLM-KLM** [matomo-org/matomo#13458]
Hello,
I install Matomoto on Prestashop 1.6, and when I look at the stats, for example yeasterday, I have 78 visitors in the Presashop BO but I have only 8 visitors in Matomoto...
What's the problem ? Did I miss some settings ?
Thank you

**Comment by fdellwing** [comment]
I would guess, the missing 70 visitors have DNT enabled or are using Adblock Plus.

**Comment by siva538** [comment]
We observed slightly variation of this issue. In the "Visitors in Real-Time" this is showing up as same visitor, but the "Actions" are getting incremented, though it is for a different user and logged in from a different machine. 

Not sure where to correct this behavior. Please help.

Regds,
Kumar.

**Comment by KLM-KLM** [comment]
Thank you for your reply.
The answer "Not sure where to correct this behavior. Please help." is for me ?
So in the "Actions" section, one action is for one visitor or 1 visitor can generate X actions ?
What is the more precise stat to see unique visitor ?
Regarding DNT and Adblock plus I guess there is no solution...?

**Comment by fdellwing** [comment]
Regarding DNT: You can ignore this via Matomo settings
Regarding Adblock: You cannot do a thing about this

**Comment by siva538** [comment]
> Thank you for your reply.
> The answer "Not sure where to correct this behavior. Please help." is for me ?
> So in the "Actions" section, one action is for one visitor or 1 visitor can generate X actions ?
> What is the more precise stat to see unique visitor ?
> Regarding DNT and Adblock plus I guess there is no solution...?

Sorry for the confusion. This was due to Anonymize IP setting. It is taken care now.

**Comment by tsteur** [comment]
Thanks. @KLM-KLM  please comment if this doesn't fix your issue and we can reopen

**Comment by KLM-KLM** [comment]
Hi,

thank you for your reply.

Your colleague talk me about the DNT (Do Not Track), how could I disable it please ?

Thank you


________________________________
De : Sivakumar Rallabhandi <notifications@github.com>
Envoyé : jeudi 20 septembre 2018 11:09
À : matomo-org/matomo
Cc : KLM-KLM; Author
Objet : Re: [matomo-org/matomo] Statistics gap with Prestashop (#13458)


We observed slightly variation of this issue. In the "Visitors in Real-Time" this is showing up as same visitor, but the "Actions" are getting incremented, though it is for a different user and logged in from a different machine.

Not sure where to correct this behavior. Please help.

Regds,
Kumar.
