### ISSUE TITLE
500 error when retrieving reports

### ISSUE THREAD

**Issue by aaaronfeng** [matomo-org/matomo#13455]
We got the following error when retrieving reports:

![2a6617f](https://user-images.githubusercontent.com/37856774/45793742-1f54d580-bcc6-11e8-8f0c-a0dad75f6d9d.PNG)

```GET /index.php?forceView=1&viewDataTable=VisitorLog&module=Live&action=getLastVisitsDetails&small=1&idSite=2&period=day&date=2018-09-20&showtitle=1&random=1584 HTTP/1.0" 500 321```

Do you know how to resolve this issue?

**Comment by siva538** [comment]
Me too faced the same issue and it has to do with the settings in the PHP:

[https://stackoverflow.com/questions/29803321/piwik-error-while-request-data-in-a-daterange](url)

" i increased memory_limit from 128M to 512M and max_execution_time from 30 to 120 in my php.ini and the issue resolved. this may be useful for someone with same problem. thanks "

It did resolve the issue for me. Just let us know if it solved the problem for you too.

Regds,
Kumar

**Comment by aaaronfeng** [comment]
Thank you. It works!
