### ISSUE TITLE
Geolocation - Location provider - incorrect display of options

### ISSUE THREAD

**Issue by narfk** [matomo-org/matomo#13453]
In Matomo 3.6.0 the screen “location provider” in geolocation displays the option to select the GEO IP Legacy (Apache) even there is no apache module installed or active.
Maybe it shows up because we have set the server variable GEOIP_ADRESS.
But thats all - the modul isn’t there.

**Comment by sgiehl** [comment]
yes, the detection for the GeoIP Apache module checks for the existence of the server variable `GEOIP_ADRESS`. If you switch to use another server variable, it won't be shown as available anymore.
