### ISSUE TITLE
Error 503 in instalation - systemCheck

### ISSUE THREAD

**Issue by TekyChile** [matomo-org/matomo#13468]
Hi! I tried to install Matomo 3.6.0 in my self-hosted server. Everything´s ok in the first index.php but, when I push the install buton try to do something and in a minute after the script send me a 503 error page. :/

There´s a print:
![2018-09-21 1](https://user-images.githubusercontent.com/33565974/45891761-c6a43c00-bd9c-11e8-8769-a9378558580c.png)
![2018-09-21](https://user-images.githubusercontent.com/33565974/45891764-c6a43c00-bd9c-11e8-9824-54b6f9a494e1.png)

My server php info:
![2018-09-21 2](https://user-images.githubusercontent.com/33565974/45891862-fd7a5200-bd9c-11e8-8155-3bb2265996f1.png)

I miss something, I know, but any idea what would be?

Cheers to all!

**Comment by Findus23** [comment]
Hi, 

Only the php error_log can tell you what exactly goes wrong.

**Comment by Findus23** [comment]
Please always include the exact error message from the php error_log as it helps finding out what exactly goes wrong.
