### ISSUE TITLE
Add possibility to import an exported container from Google Tag Manager

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13461]
We could try to see if it is possible to import them. Problem is that not all trigger/variable parameters can be mapped maybe and we would need to see how much they behave the same or different. Also most tags wouldn't be possible to import them.

After the import we would need to give an overview of what was imported, what wasn't imported (down to each parameter of trigger/variable/tag), and ideally when something was imported whether it maybe behaves differently in Matomo. 

Also we have probably couple options that GTM doesn't have, so need to see how this affects behaviour and what default values to use for those options.

We'd need a map of all their tags/triggers/variables and their parameters to make this happen. Not sure if this is documented somewhere.

**Comment by sgiehl** [comment]
Did you create that issue here and not in tag-manager repo on purpose?

**Comment by tsteur** [comment]
Nope :) will close
