### ISSUE TITLE
Offer possibility to sync JavaScript tracker with any CDN

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13462]
We would start with one CDN, for example AWS CloudFront, but have an API to easily add more through plugins or core directly.

Plugins also need to be able to sync their own files to the CDN, for example the tag manager:
refs https://github.com/matomo-org/tag-manager/issues/81#issuecomment-423368044

**Comment by tsteur** [comment]
I presume many/most CDNs don't need to upload a file to the CDN but they fetch it automatically. Possibly more interesting be a feature to invalidate the cache on a CDN.

**Comment by SARAVANA1501** [comment]
@tsteur For tag-manager I understood, there is a change event, what about whole matomo core? What are all the files should be hosted in CDN, Thought of contributing to matomo level. If you provide some information about matomo core, that would be great  for me to start.

**Comment by tsteur** [comment]
You can use the very same logic for the JS tracker by also listening to this event:

```
'CustomPiwikJs.piwikJsChanged' => array('function' => 'onStaticFileChanged', 'after' => true),
```

**Comment by tsteur** [comment]
This be actually perfect for a new plugin if you wanted to share the code and could be put on the Matomo Marketplace see https://developer.matomo.org/guides/distributing-your-plugin

**Comment by SARAVANA1501** [comment]
Cool. I will create initial version of plugin with AWS s3 support, Lets leverage further from there.

**Comment by SARAVANA1501** [comment]
@tsteur Created initial draft of plugin... I will publish this to marketplace ASAP.
https://github.com/SARAVANA1501/plugin-TrackerJsCdnSync

**Comment by SARAVANA1501** [comment]
https://plugins.matomo.org/TrackerJsCdnSync

**Comment by tsteur** [comment]
Awesome 👍  well done

**Comment by SARAVANA1501** [comment]
@tsteur Can we officially close this thread?

**Comment by tsteur** [comment]
@SARAVANA1501 maybe one more thing... I reckon it be good if the install instructions could directly show the correct CDN URL if a CDN endpoint / path is configured. This could work like this:

Listen to these events:
```php
            'API.TagManager.getContainerEmbedCode.end' => 'onGetTagManagerCode',
            'API.TagManager.getContainerInstallInstructions.end' => 'onGetTagManagerCode',
```

Then rewrite the path like this:

```php
    public function onGetTagManagerCode(&$returnedValue, $extraInfo)
    {
      if (self::getCdnUrl()) { // if user has a CDN url configured
            $piwikBase = $this->getBaseUrl();
            $containerJs = $piwikBase . '/' . trim(Piwik\Container\StaticContainer::get('TagManagerContainerWebDir'), '/') .'/';
            if (is_string($returnedValue)) {
                $returnedValue = str_replace($containerJs, self::getCdnUrl() . '/', $returnedValue);
            } elseif (is_array($returnedValue)) {
                foreach ($returnedValue as &$val) {
                    if (!empty($val['embedCode'])) {
                        $val['embedCode'] = str_replace($containerJs, self::getCdnUrl() . '/', $val['embedCode']);
                    }
                }
            }
            $returnedValue = str_replace($containerJs, self::getCdnUrl() . '/', $returnedValue);
      }
    }

    private function getBaseUrl()
    {
        $piwikBase = str_replace(array('http://', 'https://'), '', Piwik\SettingsPiwik::getPiwikUrl());
        return rtrim($piwikBase, '/');
    }

    private static function getCdnUrl($includeProtocol = false)
    {
        return 'https://mycdn.mydomain.com/mypath'; // path should be read from a config
    }
```

Not sure it's clear but it would basically replace any path like `https://matomo.example.com/js/container_349449.js` and turn it into `https:://cdn.example.com/mypath/foo/container_349449.js`.

**Comment by SARAVANA1501** [comment]
'API.TagManager.getContainerEmbedCode.end' => 'onGetTagManagerCode',
'API.TagManager.getContainerInstallInstructions.end' => 'onGetTagManagerCode',  Method is invoked but i am receiving params as empty. It is not working as expected. Where i can documentation for all these events?

**Comment by tsteur** [comment]
@SARAVANA1501 there is only this documentation about it: https://developer.matomo.org/3.x/api-reference/events#apipluginnamemethodnameend

 We're using it ourselves though as well and it works for us.
It should be invoked when you view install instructions etc

**Comment by plastikschnitzer** [comment]
Do you also plan to include other cdn?

**Comment by SARAVANA1501** [comment]
@plastikschnitzer Add you CDN specification [here](https://github.com/SARAVANA1501/plugin-TrackerJsCdnSync/issues). If possible feel free to contribute.

**Comment by SARAVANA1501** [comment]
@tsteur I am getting empty params, Have a look at the code : https://github.com/SARAVANA1501/plugin-TrackerJsCdnSync/blob/14441664bc1d5063bab70c9005a67ea0a456f320/TrackerJsCdnSync.php#L42

**Comment by tsteur** [comment]
@SARAVANA1501 

maybe try 
```php
     fwrite($myfile, var_export($returnedValue, 1));
        fwrite($myfile, var_export($extraInfo, 1));
```

**Comment by SARAVANA1501** [comment]
```
        $myfile = fopen("newfile.txt", "w") or die("Unable to open file!");
        fwrite($myfile, var_export($returnedValue, 1));
        fwrite($myfile, var_export(array(array("description" => "fgs", "embedCode" => "Sdfsdf")),1));
        $returnedValue = array(array("description" => "fgs", "embedCode" => "Sdfsdf"));
        $returnedValue[0]["embedCode"]="sdfsdfs";
        fclose($myfile); 
```
Getting params now, But returning corrected value is not working. I tried above code (line number 4 and 5) not working.

**Comment by tsteur** [comment]
Try removing this line maybe and see if it works? `$returnedValue = array(array("description" => "fgs", "embedCode" => "Sdfsdf"));`

I don't think you can simply overwrite `$returnedValue[0]` but should probably use a logic like in https://github.com/matomo-org/matomo/issues/13462#issuecomment-644993731

**Comment by SARAVANA1501** [comment]
https://github.com/matomo-org/matomo/issues/13462#issuecomment-644993731 this is not at all working, Feel free contribute a rough solution as a PR, I will refactor and write proper test case for that.

**Comment by tsteur** [comment]
@SARAVANA1501 we're using the above code ourselves and it works nicely for us. Unfortunately I don't really have time to create this PR. Adding those events and the methods should replace the shown path to the JS when you go to the TagManager and then view install instructions.

**Comment by SARAVANA1501** [comment]
@tsteur Working perfectly man, I have some other plugin which is blocking some action. i will publish soon. thanks.

**Comment by tsteur** [comment]
Awesome, thanks!

**Comment by SARAVANA1501** [comment]
@tsteur You know, we have plugin to save the container file in CDN, But how to sync piwik.js tracker file to CDN?

**Comment by SARAVANA1501** [comment]
I know we have to configure `CustomPiwikJs.piwikJsChanged' => array('function' => 'onStaticFileChanged', 'after' => true),` to sync the file after update, what about initial or first time load?

**Comment by tsteur** [comment]
Yes exactly that's how you would do it 👍 

BTW In Matomo 4 it would become `'CustomJsTracker.trackerJsChanged' => array('function' => 'onStaticFileChanged', 'after' => true),`
