### ISSUE TITLE
Not compatible with latest version

### ISSUE THREAD

**Issue by agentscript** [matomo-org/matomo#13465]
![notcompatible](https://user-images.githubusercontent.com/1674254/45879933-32d36f80-bd9e-11e8-904b-f373f994766c.PNG)

The Heatmap and Record Session is not  compatible with latest version.

**Comment by fdellwing** [comment]
Did you try updating it?

**Comment by tsteur** [comment]
The plugin is definitely compatible and it has specified that it is compatible. Wondering if something else is causing a bug there. Have you specified the license key in your Matomo? Could you maybe email shop@innocraft.com about this? Cheers.
