### ISSUE TITLE
No view allowed for superuser

### ISSUE THREAD

**Issue by mformanu** [matomo-org/matomo#13474]
Hi there,
I tried three times to install Matomo on shared Webspace (Hetzner Germany) and can't access the view of the website. I can log in, but not change settings and the dashboard says that I do not have permission ID=1. Support told me that other customers did not complain and that there is no known problem coming from their side. The installation runs through without problems and the db has the tables and rows and is filling data. Console is clean.

Is it possible that my htaccess files causes problems? The database is not on the same Webspace (db server is 123.your-server.de and the website is on 456.your-server.de)

The lines in my htaccess:

```
# Security
# Header set X-Frame-Options: SAMEORIGIN
Header set X-Content-Type-Options "nosniff"
Header set X-XSS-Protection: "1; mode=block"

RewriteCond %{HTTPS} off
# First rewrite to HTTPS:
# Don't put www. here. If it is already there it will be included, if not
# the subsequent rule will catch it.
RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
# Now, rewrite any request to the wrong domain to use www.
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule .* https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

RewriteCond %{THE_REQUEST} ^.*/index\.php
RewriteRule ^(.*)index.php$ /$1 [R=301,L]
```
Is it possible that my configuration is locking myself out?

Thanks in advance!

**Comment by tsteur** [comment]
It shouldn't cause it I reckon (not tested). Never heard of any such issue. Maybe check your site table what content it has and if a site 1 exists... if not, maybe create such a site in the DB manually (in case you are familiar with SQL). Did you install any third party plugins that are causing trouble?

**Comment by mformanu** [comment]
I can see the website in the "all websites" view at the start and it displays the number of views and the chart at the right. phpMyAdmin shows this structure (screenshot): https://auszeitweltweit-my.sharepoint.com/:i:/g/personal/manuel_dsj_auszeit-weltweit_de/EeHsHD4DnIlKuhp1JihPqlABtBk8uGzx0PiEu2ifP-Zoxw?e=cfQdkP

So the data seems to be stored correctly since in installed Matomo and included the snipped on our website.

What is perhaps worth mentioning: the php GeiIP PlugIn says "note: could not find a database"

I did not install any PlugIn or tried to. On personal settings it displays "you have to be logged in to change the settings" and I can not save anything. If I try to save something it displays "Token not valid". But I can save IPs to be dismissed in tracking.

Data integrity-test just gives a warning about forced SSL and the not very accurate GeoIP. Is there something else I can provide?

Thank you.

**Comment by mattab** [comment]
Hi there, to fix the issue can you try upgrade to the latest Matomo version?
https://matomo.org/docs/update/

if you still experience this issue afterwards, please re-open this and post a comment. 

Or you can contact us at https://matomo.org/contact/

Thanks!
