### ISSUE TITLE
Realtime visitor log should show another symbol than nothing if no data available

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#13484]
We import some data from haproxy and do not have an useragent there, so the realtime visitor log looks like this:

![matomo3](https://user-images.githubusercontent.com/22813377/46074577-4872db80-c188-11e8-9b51-b88cbb0c28f2.png)

I propose a change to something like a question mark.

**Comment by Findus23** [comment]
Hi,
There is already a github issue about replacing the "unknown" icons with proper icons.
https://github.com/matomo-org/matomo-icons/issues/11
I am just waiting for someone to create them :slightly_smiling_face:
