### ISSUE TITLE
Real time map is not working after 3.6.0 upgrade

### ISSUE THREAD

**Issue by Vinutab** [matomo-org/matomo#13490]
Hi Team,

Real time map is not showing the data, it's just showing as Loading data. This issue is only with http link. With https link , we are able to view the data.

Location Provider:GeoIp Legacy(php)

Please help.

Regards,
Vinuta

**Comment by sgiehl** [comment]
Are you able to see any errors in the browser console?

**Comment by Vinutab** [comment]
Hi sgiehl,

I am attaching the errors and the screenshot. We have already set cors_domains[] = *

Please help.

Regards,
Vinuta
![http_console_error](https://user-images.githubusercontent.com/38976040/46331784-1c97a000-c637-11e8-97d1-092463123710.png)
![http_screen](https://user-images.githubusercontent.com/38976040/46331785-1c97a000-c637-11e8-8431-662d0d9e4a9d.png)
![https_screen](https://user-images.githubusercontent.com/38976040/46331786-1c97a000-c637-11e8-880c-50b99af7c6f3.png)

**Comment by Findus23** [comment]
The Map should not need CORS headers as it is not a Cross-Origin-Request. 
If this still occurs in the latest Matomo release, please reopen this issue or create a new one.
