### ISSUE TITLE
(Matomo) City Not saving on database

### ISSUE THREAD

**Issue by retsie** [matomo-org/matomo#13495]
I have GeoLite2-City.mmdb on misc folder..
Country is saving but city is not..
There is any additional configuration to make city saving to database?

![city](https://user-images.githubusercontent.com/6046283/46185309-f064e200-c30b-11e8-93e5-d508a4f4ea00.PNG)

**Comment by sgiehl** [comment]
Which location provider did you choose in Matomo admin? It needs to be set to GeoIP 2 in order to work.

**Comment by retsie** [comment]
> Which location provider did you choose in Matomo admin? It needs to be set to GeoIP 2 in order to work.

I already used geoIp 2 dude with GeoLite2-City.mmdb database.

Currently I using on only local dev. (docker environment)

**Comment by retsie** [comment]
> Is the location provider able to detect any cities or regions? What result do you get when calling this API method on your instance:
> `path.to.matomo/index.php?module=API&method=UserCountry.getLocationFromIP&ip=67.51.31.21&format=JSON&token_auth=your_token_auth`

Country and continent only

**Comment by sgiehl** [comment]
then the location provider doesn't work correctly. is the location provider reported as working when navigating to geo location settings in Matomo admin?

**Comment by retsie** [comment]
> then the location provider doesn't work correctly. is the location provider reported as working when navigating to geo location settings in Matomo admin?

Ill just purchased google cloud platform and geolocation is working properly.
Thanks dude..
