### ISSUE TITLE
Return 403 for /console via htaccess

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13492]
By default, opening /console shows the PHP source, which is a bit ugly.
http://demo.matomo.org/console

The default .htaccess file should return 403 for this path.

**Comment by tsteur** [comment]
>  Or is the problem, that the file does not get interpreted because it has no .php ending?

exactly. The source is public anyway though so it is not much of a problem.

**Comment by fdellwing** [comment]
Well I dont see a good method to provide a .htaccess now without breaking existing installations.

**Comment by tsteur** [comment]
Personally I would close this issue. If someone is concerned about it, they can block it in their htaccess or webserver. We're not showing the URLs to users so they shouldn't get confused IMO
