### ISSUE TITLE
Live.getSimpleLastVisitCount widget loses segment upon refresh

### ISSUE THREAD

**Issue by fsuter** [matomo-org/matomo#13499]
I'm using Matomo 3.6.0 to monitor statistics on a web site (let's call it foo.com). I use various widgets to display statistics on foo.com itself (in some backend tool). All widgets are filtered with a Page URL based segment to display statistics only for the currently chosen page in the backend tool. So far so good.

One of the widgets I'm using is the Live.getSimpleLastVisitCount. It's actually the only Live widget that I use in my reporting too. The problem I have is that it loses the segment information when it refreshes. Hence it switches to displaying live stats for the whole site and not just for the current page.

I can reproduce the same behaviour out of the Matomo backend, in the Settings > Widget section:

- I open the widget in a new window
- I modify the URL to add a page segment => works
- the widget refreshes after a few seconds => segment information lost

I can see the different when looking at the request parameters using Chrome Developer Tools. During the initial request a query parameter `segment: pageUrl=$foo/bar/` is passed. In the refresh requests sent via AJAX, there's no segment information anymore.

Is this a bug or some wrong setting on our side?

**Comment by sgiehl** [comment]
Thanks for the report. I was able to reproduce and will start working on a fix now.

**Comment by sgiehl** [comment]
fixed in #13512

**Comment by fsuter** [comment]
Brilliant, thanks a lot!
