### ISSUE TITLE
I removed the line `PluginsInstalled[] = "DoNotTrack"` from my `config/config.ini.php` file but i got again the error:

### ISSUE THREAD

**Issue by mrotondi** [matomo-org/matomo#13525]
> The following error just broke Matomo (v3.6.0):
> Class 'Piwik_Plugin' not found in C:\xampp\htdocs\www.beaepartners.it\piwik\plugins\DoNotTrack\DoNotTrack.php line 20

im upgrading from version 2.x

tnx

_Originally posted by @mrotondi in https://github.com/matomo-org/matomo/issue_comments#issuecomment-426544571_

**Comment by Findus23** [comment]
Hi,

The easiest way to fix all old files is to completly replace the Matomo directory (except for the config/config.ini.php) with the latest zip instead of overwriting them and leaving old plugins there. 
https://matomo.org/docs/update/#the-manual-three-step-update

**Comment by mrotondi** [comment]
great it seems work fine
tnx
