### ISSUE TITLE
Matomo integration in Angular 6

### ISSUE THREAD

**Issue by jahid-ict** [matomo-org/matomo#13524]
I am confused where to put the tracking code. If I put it in `index.html` then I can't use `_paq.push(['trackPageView']);` inside any component. Any suggestion please?

**Comment by Findus23** [comment]
Hi,
If you write an SPA you simply add the tracking JS to the rest of your Javascript.

Keep in mind that Matomo isn't able to automatically detect page changes in SPAs, so you need to pay attention to a few things:
https://developer.matomo.org/guides/spa-tracking

There are also a handful complete Matomo integrations for Angular, but I know too little about Angular to know which one works with Angular 6 and you should use:
https://github.com/Arnaud73/ngx-matomo (seems to support Angular 5+)
http://luisfarzati.github.io/angulartics/
http://github.com/mike-spainhower/angular-piwik
https://github.com/angulartics/angulartics2
