### ISSUE TITLE
Class 'Piwik_Plugin' not found in \piwik\plugins\DoNotTrack\DoNotTrack.php 20 using PHP 7.2.5

### ISSUE THREAD

**Issue by mrotondi** [matomo-org/matomo#13521]
i got this error during motomo upgrade

**Comment by Findus23** [comment]
Hi,

Can you check if all files are there or maybe replace them with the latest Matomo version?

BTW: XAMPP is only intended for development and should not be used for public websites as it has really insecure defaults.

**Comment by mrotondi** [comment]
Hi,
im only testing the upgrade on the local copy of the website its not for production scope, i replaced all files manually to the latest version downloaded today morning.

tnx

**Comment by tsteur** [comment]
From what Piwik/Matomo version did you upgrade? Sounds like you updated maybe from a 1.X or 2.X version and the plugin `DoNotTrack ` is not compatible? You can disable this plugin in your `config/config.ini.php` by removing the line `Plugins[] = DoNotTrack`

**Comment by mrotondi** [comment]
I removed the line `PluginsInstalled[] = "DoNotTrack"` from my `config/config.ini.php` file but i got again the error:  

> The following error just broke Matomo (v3.6.0):
> Class 'Piwik_Plugin' not found in C:\xampp\htdocs\www.beaepartners.it\piwik\plugins\DoNotTrack\DoNotTrack.php line 20

im upgrading from version 2.x

tnx
