### ISSUE TITLE
"GeoIP2 plugin from Marketplace has been removed due to compatibility issues. Please check your geolocation settings."

### ISSUE THREAD

**Issue by RAIMUNDOS54** [matomo-org/matomo#13527]
This message keeps being shown even after configuring GeoIP2 correctly, which by the way is not specified in the documentation that if you were using it once in Piwik you should install a new plugin instead of just saying that it has a native support.

**Comment by sgiehl** [comment]
You may need to remove the plugin folder `GeoIP2`. But `GeoIp2` should be shipped with core, which handles GeoIP 2 support if activated.

**Comment by RAIMUNDOS54** [comment]
If I remove the plugin the message still appears and the GeoIP2 support is over. Also, where the database should be located if there is no plugin anymore? This is confusing.

**Comment by Findus23** [comment]
Hi,
Make sure you deleted `GeoIP2` (the old plugin by a third party developer) and not `GeoIp2` (the new official plugin). In case the latter is missing, please replace it with the latest one from the latest build zip.

**Comment by RAIMUNDOS54** [comment]
There is no GeoIP2 folder and the message's still here.

**Comment by sgiehl** [comment]
You may need to remove the plugin from the config file or uninstall (remove) it in matomo plugin admin

**Comment by RAIMUNDOS54** [comment]
PluginsInstalled[] = "GeoIP2" removed from the config file but nothing.

**Comment by jota2016** [comment]
Hi,
Same here. After upgrading to 3.7.0, the annoying message is permanently shown.
There is no GeoIP2 directory, only GeoIp2. The only active plugin is GeoIp2 (Core), and the older configuration has been deleted. I am using GeoIp2 Php with maxminddb extension.
Where can there be any residual configuration of the old plugin?
Thanks.
