### ISSUE TITLE
don't post travis build status to IRC

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13531]
As no one is left in the #piwik-dev channel, I guess we can also stop posting travis results there.

https://github.com/matomo-org/matomo/blob/9544e8af2a970944470d6153f0ff09d5bc30d4cd/.travis.yml#L152-L160

Does this part get generated by the travis-scripts (I couldn't find it there) or can it just be deleted directly?

**Comment by sgiehl** [comment]
guess it can be simply removed as it should be a custom part that is not generated
