### ISSUE TITLE
Update JavaScript code in app/docs/faq to use window._paq instead of _paq

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13539]
our current JavaScript tracking code in https://developer.matomo.org/guides/tracking-javascript-guide reads:

```js
  var _paq = _paq || [];
```

When people copy paste this line and code into other places like inside Tag manager containers, and this line is copied, then the _paq value ends up being set to empty array, because the global _paq is not available in the function scope. 

But we want to make it easy for users to copy paste bits of the code without breaking things. 
By changing the line to the line below, we make sure to always read the global _paq:

```js
  var _paq = window._paq || [];
```

### Steps 

* Confirm that using `window._paq` does not risk triggering errors on some browsers?
* Update all user guides, FAQs mentions
* Update developer guides mentions
* Update product the JS Tracking code generated

**Comment by fdellwing** [comment]
> Confirm that using window._paq does not risk triggering errors on some browsers?

To be safe, just use `window['_paq']`. That is supported by all browsers.

**Comment by tsteur** [comment]
just tested `var _paq = window._paq || [];` and `window._paq = window._paq || [];` on browsers back to IE6 and Firefox 3 and worked fine. It's bit easier / nicer to read than `window['_paq']` maybe

**Comment by fdellwing** [comment]
It's fine for me.
