### ISSUE TITLE
Remove user alias from database

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#13547]
Now that user alias has been removed from the UI, it can be removed from the DB as well. This should be done for Matomo 4.

**Comment by tsteur** [comment]
Actually, it could be removed in 3.7 or so as well as it isn't a DB update on a major big table.

**Comment by diosmosis** [comment]
Some users might be making use of it, though?

**Comment by tsteur** [comment]
👍

**Comment by Legion2** [comment]
Please don't remove user alias from database, it's the only field where you can store custom data. We are currently using it to store the users full name and the `login` is only a short department id.
We are also planning to use the [loginldap plugin](https://plugins.matomo.org/loginldap) and then the `login` is only an unique user id form ldap which doesn't contain any information about the full name.

If the `alias` is removed we have big problems managing the users permissions.

**Comment by sgiehl** [comment]
@tsteur shall we remove the alias in Matomo 4? 🤔

**Comment by tsteur** [comment]
Yes, I was going to wait though for the token auth branch (#6559) to be merged first to avoid merge conflicts. Be good to in the meanwhile work on some analytics features maybe.
