### ISSUE TITLE
Insufficent Memory on First Launch

### ISSUE THREAD

**Issue by milo-trujillo** [matomo-org/matomo#13550]
I've just installed Matomo for the first time and (before running first-time setup) get the following error:

~~~
[Sun Oct 07 04:32:31.079324 2018] [php7:error] [pid 40895] [client XXX] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /usr/local/www/apache24/data/analytics/core/FrontController.php on line 416
[Sun Oct 07 04:32:31.080234 2018] [php7:error] [pid 40895] [client XXX] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /usr/local/www/apache24/data/analytics/core/FrontController.php on line 416
~~~

Since Matomo hasn't been set up to monitor any sites yet, it clearly doesn't have any visitor data to process. I've tried increasing the `memory_limit` in php.ini from 128MB to 512 and even 1024MB, but get the same result.

What's wrong? Is there something else I need to reconfigure before Matomo will work?

This is all with the latest Matomo in PHP 7.2.10 with Apache 2.4 on FreeBSD.

**Comment by tsteur** [comment]
Installation should be definitely fine with that amount of memory. Hard to say what it could be. Maybe someone else has an idea.

**Comment by sgiehl** [comment]
@milo-trujillo  which version have you installed. Latest stable or beta release? Or did you fetch latest revision from github?

**Comment by milo-trujillo** [comment]
The latest stable off of https://builds.matomo.org/matomo.zip

**Comment by seonwoolee** [comment]
I too am having this issue. Alpine Linux, php 7.2.10, Nginx 1.14.1. Also using the stable build off of the link @milo-trujillo provided.

```
PHP message: PHP Fatal error:  Allowed memory size of 822083584 bytes exhausted (tried to allocate 20480 bytes) in /www/seonwoolee.com/analytics/core/FrontController.php on line 234" while reading response header from upstream, client: 207.244.109.180, server: seonwoolee.com, request: "GET /analytics/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "seonwoolee.com"
```

I didn't observe any errors in /var/log/php7/error.log.

Is there anywhere else I should be looking for clues?

**Comment by ropg** [comment]
Having the same problem on a fresh install before it's tracking anything.

```
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 69632 bytes) in /usr/local/www/rop.nl/stats/core/FrontController.php on line 412

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /usr/local/www/rop.nl/stats/core/FrontController.php on line 412
```

Server FreeBSD 11.2-RELEASE-p4, apache24-2.4.37, PHP 7.2.12, PHP memory_limit 1G

**Comment by tsteur** [comment]
Anyone is able to debug this maybe on their server? Wonder if it's maybe some recursion or so...

**Comment by Findus23** [comment]
This might have been fixed in the meantime. If you or anyone else can reproduce this issue on the latest Matomo version, please reopen the issue or create a new one.
