### ISSUE TITLE
admins can't share dashboard with users

### ISSUE THREAD

**Issue by jordo1138** [matomo-org/matomo#13567]
Matomo 3.6.0 
only super-users added can share dashboards with other users, the "copy dashboard to user" isn't visible in the dropdown for admins. 
According to https://matomo.org/faq/how-to/faq_25986/ admin's should be able to share dashboards also

**Comment by sgiehl** [comment]
@mattab should we update the documentation or change the implementation so admins can do that as well?

**Comment by mattab** [comment]
@sgiehl An admin user should be able to share dashboards with users who have view/write/admin access to any of the website(s) the admin user has access to.

**Comment by jordo1138** [comment]
@mattab that’s the expected behavior but it’s not working that way on our 3.6.0
I confirmed by checking it with all of our admin accounts for any of the siteID’s and none of them have the option visible, only super-users do

**Comment by tsteur** [comment]
just fyi it forever needed super user access in past.
