### ISSUE TITLE
Bug: Events send on Beforeunload is sent twice in Chrome

### ISSUE THREAD

**Issue by viezel** [matomo-org/matomo#13577]
Matomo: 3.6.0
Browser: Chrome 69.0.3497.100

```html
<script type="text/javascript">
    function onExit() {
        window.removeEventListener("beforeunload", onExit);
        window._paq.push(['trackEvent', "MyExitCategory", "MyExitAction", "web", 1]);
    }
    window.addEventListener('beforeunload', onExit)
</script>
```

Results in: 
![grafik](https://user-images.githubusercontent.com/6266037/46754067-cfb06b00-ccc1-11e8-87dd-6cd8b25c8e53.png)
 (works in Firefox and Safari - but not in Chrome)
The `MyExitCategory` tracking event should only appear once. 

Is this a known bug?

**Comment by sgiehl** [comment]
Are you sure the event is triggered twice and the user for example didn't have the site open in two tabs and closed both?

**Comment by viezel** [comment]
yes.

**Comment by viezel** [comment]
this is a small hotfix - creating a state varialble - but not really ideal.

```html
<script type="text/javascript">
    var beforeunloadFired = false;
    function onExit() {
        if (beforeunloadFired === false) {
            window._paq.push(['trackEvent', "MyExitCategory", "MyExitAction", "web", 1]);
        }
        window.removeEventListener("beforeunload", onExit);
        beforeunloadFired = true;
    }
    window.addEventListener('beforeunload', onExit)
</script>
```

**Comment by fdellwing** [comment]
Are you sure the event is not fired twice?

**Comment by viezel** [comment]
I think chrome might be firing it twice, but only one request is shown in the Network tab of Chrome Dev Tools.

**Comment by tsteur** [comment]
It might be `sendBeacon`. The request that you see in the network tab, is that request failing?

**Comment by viezel** [comment]
nope it works fine. 

```
Request URL: https://demo.matomo.org/piwik.php?e_c=MyExitCategory&e_a=MyExitAction&e_n=web&e_v=1&idsite=44&rec=1&r=141047&h=21&m=47&s=56&url=http%3A%2F%2Flocalhost%3A8000%2Ftrack-debug.html&_id=8c3935eb9df1b675&_idts=1539200863&_idvc=1&_idn=0&_refts=0&_viewts=1539200863&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=0&java=0&gears=0&ag=0&cookie=1&res=1680x1050&gt_ms=8&pv_id=4wahMw
Request Method: GET
Status Code: 200 OK
```

http://prntscr.com/l4l1yi
https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=44&period=day&date=yesterday&updated=2#?idSite=44&period=day&date=2018-10-10&category=General_Visitors&subcategory=Live_VisitorLog

**Comment by fdellwing** [comment]
I'm unable to reproduce the behaviour you noticed with:

Chrome 69.0.3497.100 64 Bit on Ubuntu 14.04

**Comment by viezel** [comment]
interesting..  I have it on two different MacOS now.

**Comment by fdellwing** [comment]
I just tried it with Chrome 70.0.3538.45 (Beta) 64 Bit on Ubuntu 14.04.

![matomo4](https://user-images.githubusercontent.com/22813377/46800524-3bddae00-cd58-11e8-8308-0a1bbb583222.png)

**Comment by mattab** [comment]
Hi @viezel Are you still able to reproduce this issue? if so can you please list again the steps to reproduce and browser you can reproduce this in? We'd really like to fix this issue if it's confirmed. Thanks!

**Comment by viezel** [comment]
@mattab Just tested it again, and it seems fixed in newest version 👍
