### ISSUE TITLE
Transitions and segmented visitor log provide no data when there is a colon in the query string

### ISSUE THREAD

**Issue by weberste** [matomo-org/matomo#13588]
When a URL contains a query string with a ":"

Example: http://mysite.com/explore?filters=ac:9087b429-0fa9-4252-b953-7c3d3b2a1c8b and trying to open transitions or the segmented visitor log from the "Pages" report, the overlay always shows "Either the action had no pageviews during the period 
or it is invalid.", which  is not the case.

The URL of the overlay is like so:

https://matomo.mysite.com/index.php?module=CoreHome&action=index&date=2018-10-01&period=month&idSite=5&updated=1#?idSite=5&period=day&date=2018-10-11&category=General_Actions&subcategory=General_Pages&popover=RowAction$3ATransitions$3Aurl$3Ahttp$3A$2F$2F10.41.5.128$2Fch0w$2Fworth$2Fexplore$3Ffilters$3Dac$3A9087b429-0fa9-4252-b953-7c3d3b2a1c8b

So at least on that level, it looks ok (the colon ":" being encoded as $3D).

Not sure if it's related to https://github.com/matomo-org/matomo/issues/13460 and might be fixed with https://github.com/matomo-org/matomo/pull/13481 ...

**Comment by fdellwing** [comment]
If you are able to, please test if the PR resolves the issue: https://github.com/matomo-org/matomo/pull/13481.patch

**Comment by tsteur** [comment]
Works for me. Possibly fixed by https://github.com/matomo-org/matomo/pull/13481
transitions
![image](https://user-images.githubusercontent.com/273120/66178327-6b9c6900-e6c1-11e9-98b6-f15b886fa98b.png)
visitor log:
![image](https://user-images.githubusercontent.com/273120/66178352-84a51a00-e6c1-11e9-833f-e43214ce5f13.png)
