### ISSUE TITLE
custom variable Report not getting data

### ISSUE THREAD

**Issue by hiraghuak** [matomo-org/matomo#13587]
Hi,
custom variable Report not getting data, please find the screenshot, we are trying to generate a custom variable report using "Custom Reports", we need to track Media data, already we have purchased "Media Plugin" if it works we are planning to take full version so kindly support as soon as possible 

https://prnt.sc/l4oahh
https://prnt.sc/l4o9hh
https://prnt.sc/l4o9sb
https://prnt.sc/l4o9w6
http://prntscr.com/l4qf3r

**Comment by tsteur** [comment]
Hi @hiraghuak 

sorry for the late reply. Only seeing this issue now. For support for our premium features it's best to contact shop@innocraft.com directly as this issue tracker is purely for issues around the Matomo core. If you still have this issue and haven't contacted our support yet, be great to send us an email .

Thanks
