### ISSUE TITLE
Detect Nginx during install and suggest taking a look at the official config

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13589]
Matomo can be used with Nginx instead of Apache.
As Nginx doesn't recognize .htaccess (by default) it is important to use a proper nginx config that blocks access to e.g. `tmp/`.

Therefore I'd suggest detecting nginx during the installer and show a notice to the admin urging them to take a look at the Matomo nginx config.

One way to detect it would be using `$_SERVER["SERVER_SOFTWARE"]` which returns `nginx/1.14.0` for me. While it isn't 100% accurate, it should be okay for a notice.

**Comment by fdellwing** [comment]
Via JS, you could look at the headers. Even with `server_tokens off` it will identify itself as nginx.

**Comment by fdellwing** [comment]
I will post feedback as soon as I had time to look throught the options.

**Comment by Findus23** [comment]
Just saw that Nextcloud is using $_SERVER["SERVER_SOFTWARE"], so using it for detection should be fine.
https://github.com/nextcloud/serverinfo/blob/21e7b5d6b1029c8030ef7f95b5e03938b72ea93c/lib/Controller/ApiController.php#L135-L145
