### ISSUE TITLE
Refererer name should allow more than 70 characters

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13582]
Currently, for some unknown reason (what was I thinking?!) the `log_visit.referer_name` and `log_conversion.referer_name` columns are limited to 70 characters.  This can be very limiting because it is common for campaign names (for example) to exceed 70 characters.

I've just tested and it is not too slow, but it's definitely not fast to upgrade a column from VARCHAR 70 to VARCHAR 255. So we can't do it before Matomo 4.

* it took 10 seconds to change the field on a log_conversion table with 200K rows
* it took 680 seconds to change the field on log_visit with 5M rows

Related bug we recently discovered:  https://github.com/matomo-org/matomo/pull/13573

###  Suggested steps

* Change referer_name column to 255 length 
* Modify code to remove the 70 chars limit
* add a test that referrer names with 250 characters are tracked, and retrieved correctly
* Quickly check if some other columns have arbitrary varchar and should be increased as well?

**Comment by sgiehl** [comment]
fixed with #15251
