### ISSUE TITLE
Trigger click event on select element (Matomo UI)

### ISSUE THREAD

**Issue by eramirezprotec** [matomo-org/matomo#13590]
Piwik UI is great, but I'm finding difficulties to do some "easy" stuff with it. For example, I have a select:

```
<div piwik-field uicontrol="select" name="language"
         title="Language"
         introduction="Select fields"
         value="1"
         inline-help="Single select"
         options='{1: "English",2:"Spanish"}'>
    </div>
```

How can I trigger a click event on one of the select options? I need to change programmatically the value of the select and I also need (obviously) that the interface (the select element) reflects the changes.

I'm not using AngularJS, I'm using jQuery. 

Thank you very much.

**Comment by eramirezprotec** [comment]
Solution?:

$("#elementId ul > li:nth-child(X)").click();

**Comment by tsteur** [comment]
Might work 👍  Depending on the content might even work to use something like `... > li:contains('text')` but that only works if two entries don't contain the same word. I recommend you use angular if possible as pretty much all Matomo UI is built with angular and we're removing more and more old jquery.
