### ISSUE TITLE
Real time map issue in http after 3.6.0 upgrade 

### ISSUE THREAD

**Issue by Vinutab** [matomo-org/matomo#13599]
Hi Team,

Real time map is not showing the data, it's just showing as Loading data. This issue is only with http link. With https link , we are able to view the data.

Location Provider:GeoIp Legacy(php)

I am attaching the errors and the screenshot. 

Please help.
![https_screen](https://user-images.githubusercontent.com/38976040/46864550-5be49e80-ce38-11e8-9a4a-913567055949.png)
![http_screen](https://user-images.githubusercontent.com/38976040/46864587-73bc2280-ce38-11e8-9b86-c95c78cfe0b2.png)

Regards,
Vinuta

**Comment by fdellwing** [comment]
Already answered in the forums: https://forum.matomo.org/t/real-time-map-issue-in-http-after-3-6-0-upgrade/30164/2
