### ISSUE TITLE
Matomo not showing visits for certain days 

### ISSUE THREAD

**Issue by lucastx** [matomo-org/matomo#13600]
Hello,

I've been using Piwik / Matomo for 4 years at work, but for the last months it has been somehow been losing data on visits for specific days (sometimes a range of days):

![captura de tela de 2018-10-12 17-42-43](https://user-images.githubusercontent.com/676362/46893119-3b234580-ce46-11e8-8dc3-3e1bfee4e53b.png)

As a latest example (using Matomo 3.6.0 on Apache2, Debian 9) has been October 2 and 3:

![captura de tela de 2018-10-12 17-41-24](https://user-images.githubusercontent.com/676362/46893069-0b743d80-ce46-11e8-8a7b-32bb3dbc4de5.png)

The website has been visited on these days, and I've looked at Apache logs and there seem to have been actual requests for Matomo scripts, returning 200 (IPs redacted):

[access.log.10.gz](https://github.com/matomo-org/matomo/files/2474558/access.log.10.gz)

Error logs show nothing related to this.

Where should I look for more tips on what was going on these days, and/or have more logs on the next time this happens?

Thank you for this great piece of software!

**Comment by lucastx** [comment]
No, it doesn't. I configured Piwik to remove visitor logs after 7 days for privacy reasons...

**Comment by sgiehl** [comment]
Ah ok. So there is no data available to process any new reports that are older than 7 days.
Are you using a cron job for archiving the reports or is that browser triggered. 
If it's triggered by the browser and you are not opening Matomo for more than a week maybe the log data gets deleted before the reports are archived. I'm not sure if we check if the reports are generated before the log data is removed...

**Comment by lucastx** [comment]
It was apparently triggered by the browser as I did not find any cronjob running anywhere. I think I made this on a previous Piwik installation.

i disabled this log removal setting for now and will investigate this further later. Thank you!
