### ISSUE TITLE
Multiple users for a single website

### ISSUE THREAD

**Issue by sandeshnaroju** [matomo-org/matomo#13602]
I know a website can have multiple user admins to see the analytics with different permissions like view read and write in matomo. But my use case is completely different. I want to know if this is possible with Matomo.

I have a website in which users create accounts with their email ids. Now users can create pages inside their accounts and make their pages public so that the general people can read it online. 

For this site I have added Matomo but I get data of all the user accounts in my website. I want I should be able to differentiate based on the user account(email ids). Each user account will have different page views. I want to able to track based on the user. Is it possible? What is the procedure to do it?

**Comment by Findus23** [comment]
Hi,

Did you take at the Matomo [User ID](https://matomo.org/docs/user-id/) feature combined with segments?

Please ask general questions on the forum and only report bugs on GitHub
https://forum.matomo.org/
