### ISSUE TITLE
Matomo administration pages lack general settings, plugin activation, etc.

### ISSUE THREAD

**Issue by BBauman** [matomo-org/matomo#13614]
Ever since around the GDPR update, Matomo's administration page has changed quite drastically.  This makes much of the documentation inaccurate, and seems to have removed some controls completely.

For example:
Activating plugins: https://matomo.org/faq/plugins/faq_21/
Changing plugin configuration: https://plugins.matomo.org/QueuedTracking#faq

**Comment by Findus23** [comment]
Hi, 
I am not sure what change you are referring to but the plugin settings, the marketplace and the general settings are still where they where before.

**Comment by BBauman** [comment]
Hello.  I'm attaching an image of what my admin sidebar now looks like:

https://imgur.com/Mf4KxhP
