### ISSUE TITLE
API method getPageUrls doesn't return all the pages

### ISSUE THREAD

**Issue by MatG01** [matomo-org/matomo#13619]
I recently switched from Matomo 2.x to 3.6 and I have this problem, which worked under 2.x

This API call
https://example.com/piwik/index.php?module=API&method=Actions.getPageUrls&token_auth=xxxxx&idSite=1&flat=1&filter_sort_column=nb_hits&showColumns=label,nb_hits&format=JSON&period=range&date=2018-09-01,2018-10-01&filter_limit=-1&segment=pageUrl=@%2Fpage%2F
used to give me all the the hits on URLs /page/... (about 30000 URLs)
Now I only get around 400 URLs labeled "/page/page1", "/page/page2" a.s.o.
Additionally I get one entry labeled "/page/ - Others" which seemingly is the accumulation of all the missing URLs. How can I get rid of this accumulation and get the complete set of raw data instead?

I'm aware of the filter_truncate parameter, which does a similar thing by returning an accumulating entry labeled "Others". However, the label I get is a bit different, and I'm not using the filter_truncate parameter.

Many thanks in advance for any advice.

**Comment by oscarfroberg** [comment]
I am also having similar issues. I'm using `method=Actions.getPageUrls&idSite=1&period=range&date=last30&format=JSON` but getting significantly less results than from the GUI.

**Comment by tsteur** [comment]
@oscarfroberg you need to set `filter_limit=-1`. @MatG01 check out https://matomo.org/faq/how-to/faq_54/

**Comment by oscarfroberg** [comment]
Sigh. Here's the full request:

`?module=API&method=Actions.getPageUrls&idSite=263&date=last30&period=range&filter_limit=-1&filter_sort_column=nb_hits&token_auth=[TOKEN]&format=json`
