### ISSUE TITLE
Drop support for (at least) IE 10

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13613]
While we are on the topic of unpopular support changes, let's continue with Internet Explorer. :slightly_smiling_face: 

Internet Explorer 10 hasn't been receiving security updates since `January 12, 2016` ([source](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support)) and using it to access the internet is highly dangerous. In addition IE 10 never was really popular and seems to be only be used by 0.07%.
Therefore I think it is really easy to completely drop support for IE 10 in Matomo 4.

Personally I would like to also drop IE 11 and only support Edge, but I guess this won't be feasible as far to many companies are using it and don't have another way to access Matomo.
In addition IE 11 still receives security updates (but unfortunately no bug fixes anymore).
Funfact: 
> Internet Explorer 11 will be supported for the life of Windows 7, Windows 8.1, and Windows 10.
> https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support

As Microsoft doesn't seem to be planning to release an update that isn't called Windows 10, IE 11 will probably be supported for eternity :slightly_smiling_face: . 

Note: This does **not** mean IE 10 users won't be tracked anymore. The tracking script will continue to support ancient browsers. (Although it might be worth it to move the definition of "ancient" to IE7+ https://github.com/matomo-org/matomo/issues/6093#issuecomment-361696889)

**Comment by tsteur** [comment]
Dropping support for IE10 in Matomo 4 should be fine I reckon.

**Comment by tsteur** [comment]
I think it's quite clear we will drop support for IE 10. The only question is are there also other browser we should consider dropping support for? I would say for now we only drop IE 10. If we run into any issues during development re any browser then we consider dropping it as well depending on the problem etc. 

This applies of course only to the tracking part.

**Comment by tsteur** [comment]
I suppose we could close this issue @Findus23 ?

**Comment by Findus23** [comment]
> If we run into any issues during development re any browser then we consider dropping it as well depending on the problem etc.

As great as it would be, dropping support for IE11 will be quite hard as it is still "supported" by Microsoft.

> This applies of course only to the tracking part.

You mean this (dropping IE10 support) applies to everything apart from tracking?

**Comment by tsteur** [comment]
> You mean this (dropping IE10 support) applies to everything apart from tracking?

Yes.

**Comment by tsteur** [comment]
Actually I reopen so it won't be forgotten to put this into the release notes.
 Might be good to start writing the release notes already and enrich over the next 3-5 months... @mattab maybe we start a doc?

**Comment by mattab** [comment]
@tsteur  in general whenever there is an issue, and it has been closed, then it will appear in the changelog. To highlight the issue to the top of the changelog, we can add `Major` label to the issue. 

still sounds good to keep track of release notes, created https://github.com/matomo-org/matomo/wiki/Matomo-4.0.0-release-notes
