### ISSUE TITLE
Different `delete_logs_older_than` value for log tables

### ISSUE THREAD

**Issue by luohui8891** [matomo-org/matomo#13610]
Hi guys,
I set up 3.5.1 in my server and collect data for almost 60k+ sites.
I also set `delete_logs_older_than` to 35 days because we need monthly unique visitors. 
But the database is still very big. It also effect query and backup.
So I need slim the database.
I fount that the biggest table is relationship table `log_link_visit_action`. There are almost 750+ million records in this table. (35 days data)

Because the monthly unique visitors is only need monthly data of `log_visit`, so can I just keep the 35 values for `log_visit` table and setup another value (like 5 days) for others?

**Comment by mattab** [comment]
Hi @luohui8891 
We recommend to contact the professional support team @ http://matomo.org/support/ for getting the best possible help with your very high traffic instance. Thanks,

**Comment by luohui8891** [comment]
Sure.
