### ISSUE TITLE
Don't tell people to run chmod -R 755 on their install if update fails

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#13628]
Related to #13626 

Please don't tell people to run `chmod -R 755 /var/www/piwik`. This will make all the files executable by everyone.

Either use `chmod -R 754 /var/www/piwik` (the easy solution) or `find /var/www/piwik -type d -exec chmod 755 {} \;` (the good solution).

**Comment by mattab** [comment]
Thanks for the suggestion: pull request welcome @fdellwing

**Comment by fdellwing** [comment]
@mattab There is a PR for this: #13630

**Comment by Findus23** [comment]
See also https://github.com/matomo-org/matomo/issues/4046
