### ISSUE TITLE
Custom Report for Media ("Video's reporting")

### ISSUE THREAD

**Issue by hiraghuak** [matomo-org/matomo#13623]
Hi,

I have purchased Media plugin, our main focus is to create a custom report, each user's video activity tracking with some of the custom variable or custom Dimension.
http://prntscr.com/l6zac0
http://prntscr.com/l6zb7o 
http://prntscr.com/l6zg0b ("this Error Msg we are getting its been 7days same msg only we are getting")

if it's working I am planning to take a premium version.

Kindly help us with this

**Comment by sgiehl** [comment]
If you created a custom report you may need to reprocess the reports. See https://matomo.org/faq/custom-reports/#faq_25265
For further help, you can also contact our premium plugin support at https://matomo.org/contact/marketplace/
