### ISSUE TITLE
Keep Reporting API URL simpler when exporting custom report data 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13645]
When exporting custom report data, the URl looks like this:
![untitled](https://user-images.githubusercontent.com/466765/47534998-f99a9c00-d915-11e8-9737-ec9454c18f30.png)

The URL includes `&reportUniqueId=CustomReports_getCustomReport_idCustomReport--2` but actually this URL parameter is not needed for the API.

So let's remove this parameter from Export API URLs.

**Comment by sgiehl** [comment]
The export uses all parameters that are set as request parameters for the datatable. In that special case the custom report sets the uniqueReportId. We can't filter that list of parameters in core, as there is no way to identify if the parameter is required or not. We need to adjust that in the plugin.
ping @tsteur

**Comment by tsteur** [comment]
The report unique ID is needed eg I think for the insights visualisation. It shouldn't be a problem to have this parameter in there?
