### ISSUE TITLE
API Live.getLastVisitsDetails may returns visits from the day before

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13659]
Reproduced:

* URL = `/?module=API&method=Live.getLastVisitsDetails&format=json&idSite=3&period=day&date=2018-11-01`
* Some of the visits in the response had dates set to 2018-10-31, see screenshot below:

![output](https://user-images.githubusercontent.com/466765/47826880-74b0f600-dddf-11e8-9328-7ee162644193.png)

Goal:

* Understand why visits from the day before may be returned by Live.getLastVisitsDetails API
* Document the limitation, or if possible solve the problem

**Comment by tsteur** [comment]
see eg https://github.com/matomo-org/matomo/pull/11425 ?

**Comment by mattab** [comment]
As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
