### ISSUE TITLE
Is there a plan for updating the .NET API library to .NET Core?

### ISSUE THREAD

**Issue by uncled1023** [matomo-org/matomo#13657]
Specifically talking about this repository here: https://github.com/matomo-org/piwik-dotnet-tracker

As of now, all of the libraries are unable to be used with .net CORE, which is rapidly gaining usage over .net framework.  Are there any plans to work on those libraries, or to create new ones?

Thanks!

**Comment by MichaelHeerklotz** [comment]
I have started a conversion to .NET Core, but it may take some time to finish it.

**Comment by Findus23** [comment]
Closing in favor of https://github.com/matomo-org/piwik-dotnet-tracker/issues/70
