### ISSUE TITLE
unexpected folder tmptpm gets created day by day

### ISSUE THREAD

**Issue by kkretsch** [matomo-org/matomo#13661]
I'm using last stable version 3.6.1 and just moved to a new server with my installation.
Everything works but each day (or over night) I find that folder **tmptpm** in the web root.
The piwik tool systemCheckPage find that one and mentions to delete it. But that will return.

Contents of that folder is a tree tmptpm/logs/piwik.log nothing else.
And that file contains:
INFO Diagnostics[2018-10-31 16:20:08 UTC] [1cba3] Unable to test if mod_pagespeed is enabled: the request to https://stat.mydomain.xxx/index.php?module=Installation&action=getEmptyPageForSystemCheck failed
INFO Diagnostics[2018-11-01 08:14:22 UTC] [a6028] Unable to test if mod_pagespeed is enabled: the request to https://stat.mydomain.xxx/index.php?module=Installation&action=getEmptyPageForSystemCheck failed

I grepped for the tpm substring without any matches.

Plugins additionally installed are CustomOptOut and Tagmanager, but they where the same before the server move.

php is 7.0.30 als fpm module under apache, using debian 9 as server.

**Comment by tsteur** [comment]
By any chance, have you configured a custom `logger_file_path` in the `config/config.ini.php`? I've looked through source as well and couldn't find any `tpm` typo. There's otherwise this code and maybe there's a bug in there in https://github.com/matomo-org/matomo/blob/3.6.1/plugins/Monolog/config/config.php#L74-L96

**Comment by kkretsch** [comment]
Thanks for that hint. I really had there a typo, which didn't came to my attention before the server move.
