### ISSUE TITLE
HTML in report documentation is shown plain text

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#13668]
Some report documentation contains some HTML tags. Currently [the filter `rawSafeDecoded` is used](https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/CoreHome/templates/_dataTable.twig#L44) on that attribute, which causes all HTML-tags to be encoded.

Instead we might use the `raw` filter, but need to ensure that possible user input is encoded if there is any in some report documentation.

![image](https://user-images.githubusercontent.com/1579355/47986319-9e6a6580-e0dc-11e8-8796-44e6d9524120.png)

Note: This also regressed in the UI tests (https://builds-artifacts.matomo.org/matomo-org/matomo/3.x-dev/30903/UIIntegrationTest_actions_pages_tooltip_help.png)

**Comment by tsteur** [comment]
It would be good if the `raw` filter be only applied when a viewdatatable config option is enabled.
