### ISSUE TITLE
Visitor counting seems to be wrong

### ISSUE THREAD

**Issue by martingreiner** [matomo-org/matomo#13672]
We are analysing the hits of a captive portal with matomo, with the embedded image-link integration.
It seems that the counting is not very exact, at least if there are many users/clients hitting the same "site".

I can verify about 1000 Hits in the webserver-log matomo is hosted,
but the tools shows me only about 180 hits/users/clients.

Is this an already known bug?

kindly regards for your feedback

**Comment by fdellwing** [comment]
Are you sure, you are looking at the correct metric?

The metric that correlates most with the access log is the pageview metric and not the visitor metric.

**Comment by martingreiner** [comment]
I see what you are meening, let me please verify this.
I will keep you up to date, it seems, some less visitors have most of the page-views.

Regards
Martin


Von: Fabian Dellwing <notifications@github.com>
Gesendet: Dienstag, 6. November 2018 12:51
An: matomo-org/matomo <matomo@noreply.github.com>
Cc: Greiner Martin <martin.greiner@citycom-austria.com>; Author <author@noreply.github.com>
Betreff: Re: [matomo-org/matomo] Visitor counting seems to be wrong (#13672)


Are you sure, you are looking at the correct metric?

The metric that correlates most with the access log is the pageview metric and not the visitor metric.

**Comment by Findus23** [comment]
@martingreiner If there is still an issue in the latest Matomo version, please reopen this issue or create a new issue with more details.
