### ISSUE TITLE
[Question] Merging multiple Matomo instances into one.

### ISSUE THREAD

**Issue by Telokis** [matomo-org/matomo#13673]
I am running a setup where I have multiple servers that each have their own Matomo instance running. Those servers also serve a web application that sends stats to the Matomo instance.
There is no internet connection at all available.

Is there a way to retrieve multiple Matomo databases generated by this setup and merge them in one big instance? For example, I was thinking about exporting the SQL database and execute it on the main instance.

**Comment by Telokis** [comment]
Anyone?

**Comment by mattab** [comment]
currently it isn't available, but maybe we work on this in the next 6 months.

**Comment by mattab** [comment]
Hi @Telokis 
We have in the meantime released Migration feature which lets you easily merge multiple Matomo instances into one, learn more: https://matomo.org/faq/how-to/faq_19238/

and at: https://plugins.matomo.org/Migration
