### ISSUE TITLE
JS Tracker: enable alwaysUseSendBeacon by default

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13681]
assuming that the trial went well, then in Matomo 4.0.0 we would like to enable the feature `alwaysUseSendBeacon` by default. 

see https://github.com/matomo-org/matomo/pull/13451 https://github.com/matomo-org/matomo/issues/6641

**Comment by tsteur** [comment]
One thing to keep in mind is that the callback parameter won't work anymore (because there is no event or what so ever when the request is finished). Some users rely on this see eg https://github.com/matomo-org/matomo/issues/13679#issuecomment-436748761

**Comment by mattab** [comment]
* Another concern is that if all send beacon requests are sent as POST then these request could not [be replayed (FAQ)](https://matomo.org/faq/log-analytics-tool/faq_19221/), which could result in rare cases (maintenance, downtime) in lost data when recovering logs. (will need to document this more clearly in this FAQ which actions wouldn't be likely replayed because of send beacon)

**Comment by tsteur** [comment]
They are sent as request parameters unless the request is large AFAIK

**Comment by mattab** [comment]
Also we just found out that when closing the tab/window, Chrome seems to not execute sendBeacon on beforeunload unfortunately!? so we wouldn't want to rely on this feature probably...

**Comment by tsteur** [comment]
@mattab it's still good for sending requests when the browser closes. It will be more reliable than the XHR. It just means we can't collect all requests, optimize them, and send them at the end of the page view. Like instead of pinging Matomo every 15s using heartbeat it would have better to send only one request when the browser closes... but this won't work reliably

**Comment by sgiehl** [comment]
fixed with #15405, will be included in Matomo 4

**Comment by tsteur** [comment]
BTW a benefit is that it will improve page load time when using send beacon.
