### ISSUE TITLE
Display the name of the user being edited

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13690]
When editing a user, to avoid confusion and possible mis-clicks, it would be useful to show the name of the User being edited.

Currently it looks like this:

![write user name](https://user-images.githubusercontent.com/466765/48242733-7adb4e00-e441-11e8-97d5-e64a8b22b5d6.png)

-> Instead of `Edit user` the title could say `Edit user 'angela'`

**Comment by luggesexe** [comment]
Hey,
I'm trying to solve this problem and just found the file path that causes the problem (plugins/UsersManager/angularjs/user-edit-form). Now I don't know exactly where Matomo stores the titles. I have not been able to find anything in the surrounding files either. 
I would be grateful for any help.

**Comment by mattab** [comment]
Fixed in  #17115
