### ISSUE TITLE
Goals: Key "description" for array with keys does not exist

### ISSUE THREAD

**Issue by baenziger** [matomo-org/matomo#13702]
When trying to open Goals in settings, the following error is displayed. Trying to open manage goals within a website causes the same error:

The following error just broke Matomo (v3.6.1):

```
Key "description" for array with keys "idsite, idgoal, name, match_attribute, allow_multiple, revenue, deleted, event_value_as_revenue" does not exist.
in F:\Websites\Piwik\piwik\plugins\Goals\templates\_listGoalEdit.twig line 51          
```  

Unfortunately, I'm not sure if this appeared after the update to 3.6.1 or existed earlier, as I wasn't using goals much.

**Comment by fdellwing** [comment]
Possible regression from #13483?

//cc @diosmosis

**Comment by tsteur** [comment]
see https://github.com/matomo-org/matomo/issues/11327
