### ISSUE TITLE
Show the title of the site at the top of the page?

### ISSUE THREAD

**Issue by davidaigle** [matomo-org/matomo#13704]
We have a large number of web assets e.g. websites, web-based applications or specific website sub-sections being tracked using Piwik. Although we can pick an asset on the All Websites index page, once we pick one it would be great of the website name/title would appear on the Dashboard page, probably aligned top left side of the page, just below the horizontal menu. Right now when you get to the Dashboard page, the site you are currently viewing visitor data for is only seen in the drop-down menu that is aligned to the top right of the page.

**Comment by tsteur** [comment]
Do you mean the exported dashboard? It should be shown in the website selector in exported dashboard? I don't think we will add it to the dashboard page as well otherwise.

**Comment by sgiehl** [comment]
Closing as there hadn't been any further feedback on this.
If you are still in need of a custom widget to e.g. show the websites name, maybe check our forums for help to create your own widget for that.
