### ISSUE TITLE
Export reports broken down by day, week or month?

### ISSUE THREAD

**Issue by davidaigle** [matomo-org/matomo#13705]
When we export reports either through the Dashboard or through the automated email report, and select a date range, it would be great if Piwik could separate the data over the date range by either day, week or month. This way was can see some trends that are not just available in the Overview report histogram, which can be useful but is not granular enough.

**Comment by tsteur** [comment]
This can be already done. Just change the period from `range` to `date` in the API request. I think the automated email report can do this now as well starting from 3.7.0

**Comment by tsteur** [comment]
for automated reports see https://github.com/matomo-org/matomo/pull/13689
