### ISSUE TITLE
Website selector: Ctrl+Click should open the website in a new tab

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13701]
Steps to reproduce:

* Click on website selector
* Do Ctrl+Click on a website name
* Got: the website clicked opens in the same window
* Expected instead: the website clicked opens in a new tab

**Comment by fdellwing** [comment]
FYI: Clicking it with middle mousebutton should also open new tab

**Comment by Findus23** [comment]
For me middle-mousebutton-clicking does work. So I guess there is maybe something catching the "Ctrl".
