### ISSUE TITLE
Require password confirmation when giving someone super user access

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13711]
Similar to #2932 and https://github.com/matomo-org/matomo/issues/13710 it would be also good to eventually have a password confirmation when giving someone user access

**Comment by diosmosis** [comment]
Would this affect just the UI or the API too? Since the API would require token_auth, then requiring a password too would be redundant, no? And if it's not in the API, then the UI would just verify the password before sending the API request, correct?
