### ISSUE TITLE
visitEndServerHour parameter is missing in segment API

### ISSUE THREAD

**Issue by mhow2** [matomo-org/matomo#13718]
`visitEndServerHour` segment parameter is missing from https://developer.matomo.org/api-reference/reporting-api-segmentation API. I tested on a live instance too, it doesn't seem implemented.

However; `visitStartServerHour` is available.

Regards

**Comment by tsteur** [comment]
The segment name should be `visitServerHour` (didn't change the name for BC). Feel free to reopen if this is not the case.
