### ISSUE TITLE
Personal token auth should be only visible after entering the password

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13710]
Currently, you only need to click to view the token auth. I reckon instead we should ask a user to enter the password again before showing it. We could potentially always show the first 5 characters though. from @tsteur

**Comment by diosmosis** [comment]
Depends on https://github.com/matomo-org/matomo/issues/6559

**Comment by tsteur** [comment]
FYI as we likely will implement https://github.com/matomo-org/matomo/issues/6559 app specific passwords in Matomo 4 and have the tokens stored securely in the DB this issue will likely become obsolete since the token will only be visible after creating the token.

**Comment by tsteur** [comment]
Closing this as a duplicate of https://github.com/matomo-org/matomo/issues/9457
