### ISSUE TITLE
Your browser was unable to load the scripts of this page.

### ISSUE THREAD

**Issue by gamelife1314** [matomo-org/matomo#13726]
Some errors occur when I open home page, as following:

`Your browser was unable to load the scripts of this page.`
`Your browser was unable to load the style of this page.`

<img width="725" alt="2018-11-19 10 18 47" src="https://user-images.githubusercontent.com/10297148/48682711-9fbf8600-ebe4-11e8-8a43-4ac4ca98eef7.png">

<img width="1427" alt="2018-11-19 10 19 28" src="https://user-images.githubusercontent.com/10297148/48682720-ac43de80-ebe4-11e8-9a3d-b7fd7e9f903d.png">

 Reason is that  js-file just is loaded part `/index.php?module=Installation&action=getInstallationJs&cb=3a2f662255342cb246990020a3fdda57`.

<img width="1434" alt="2018-11-19 10 27 55" src="https://user-images.githubusercontent.com/10297148/48682991-e1046580-ebe5-11e8-95b9-ae0ff2e36a96.png">

**Comment by tsteur** [comment]
see https://github.com/matomo-org/matomo/issues/12812

**Comment by gamelife1314** [comment]
Thanks a lot, @tsteur, I have seen  #12812, but it didn't work. I'll try other solutions. 

My matomo is deployed and started by docker.

**Comment by tsteur** [comment]
Maybe check if some extensions are enabled that improve performance or so. They can cause trouble. Like modpagespeed etc

**Comment by Pixelshiftarr** [comment]
I had the same issue. Disabeling my add blocker (ublock origin in firefox) and refreshing fixed it!
