### ISSUE TITLE
warning message "variable @default-box-shade is undefined"

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13736]
This error has been reported once:

> An exception has been thrown during the rendering of a template ("variable @default-box-shade is undefined: failed at `box-shadow: @default-box-shade;` line: 3036"). plugins/CoreUpdater/templates/runUpdaterAndExit_welcome.twig 8 using PHP 7.0.24

**Comment by sgiehl** [comment]
Maybe the file containing that definition was not correctly updated?

**Comment by tsteur** [comment]
Would say so too. I think this can be closed. Feel free to re-open if needed.
