### ISSUE TITLE
3.7.0 Update Error

### ISSUE THREAD

**Issue by siulca** [matomo-org/matomo#13730]
Updating from 3.6.1 to 3.7.0 got the following error.

![image](https://user-images.githubusercontent.com/6707451/48704791-5e80a380-ebef-11e8-8411-e704da38dd71.png)

However Motomo appears to have loaded OK afterwards. Will this error affect my analytics?

**Comment by fdellwing** [comment]
If you are able to run `./console core:update` in the root folder of your installation.

**Comment by siulca** [comment]
Why if it seems to work fine? I don't think I have access to the server's console.

**Comment by tsteur** [comment]
It shouldn't affect your analytics but may affect scheduled reports. You could try execute this MySQL query if you are familiar with databases:

```sql
ALTER TABLE piwik_report ADD column evolution_graph_within_period TINYINT(4) NOT NULL DEFAULT 0, ADD column evolution_graph_period_n INT(11) NULL;
```

Haven't tested the query but should work. You may need to replay piwik_report with a different value in case you use a different table prefix (if you don't know what it is, it likely doesn't need to be replaced)
