### ISSUE TITLE
After update to 3.7.0: content not loading, .htaccess config problem

### ISSUE THREAD

**Issue by ecobux** [matomo-org/matomo#13738]
On one specific server (shared hosting), the update to 3.7.0 caused the panels not to appear (dashboard, all websites and settings). In the JS console there appeared several errors like

> Error: "[$compile:tpload] http://errors.angularjs.org/1.6.5/$compile/tpload?p0=plugins%2FCoreHome%2Fangularjs%2Fcontent-block%2Fcontent-block.directive.html%3Fcb%3D850e76cd9c654537ca47d425e7a85c78&p1=500&p2=Internal%20Server%20Error"

I could fix (?) it by removing some lines from .htaccess in the /plugins folder:

```
# Serve HTML files as text/html mime type - Note: requires mod_mime apache module!
<IfModule mod_mime.c>
   AddHandler text/html .html
   AddHandler text/html .htm
</IfModule>
```

**Comment by tsteur** [comment]
duplicate of https://github.com/matomo-org/matomo/issues/13749
