### ISSUE TITLE
Duplicate Actions and events in same session with UserID

### ISSUE THREAD

**Issue by IsraelDominguez** [matomo-org/matomo#13744]
Hi

We have installed Matomo 3.7.0 and we hava an importat problem with actions stored for users sessions tracked with Javascript. We have duplicated tracked events and page views for the same user session. For example We have user page view duplicated in the same second and views pages twice when is imposible to see more than one time.

This does not happen with all users. We currently have a lot of traffic and We have configured the Mysql Queue plugin.

**Comment by IsraelDominguez** [comment]
Edit: We have duplicated actions when the user has a referer (other site, facebook,...) when the user is "direct entrance" We have correct actions number.

**Comment by tsteur** [comment]
Can you check if you can reproduce this in your browser? Once we know steps to reproduce we can look at it.

**Comment by cofundhub** [comment]
Same problem here. The system generated four actions for the same page hit.

**Comment by tsteur** [comment]
@cofundhub do you also have the queued tracking plugin enabled? What we ideally need would be exact ways to reproduce it. Also ideally, if possible, ensure the same tracking request is not issued 4 times in the browser. If someone can use browser developer tools to verify that, that would be great.

**Comment by cofundhub** [comment]
@tsteur Thanks for the quick followup. No, we didn't have the queued tracking plugin. We are new to matomo. The system did give the notification that the geolocation information needs update. After we updated that part, the duplicate actions are gone as well. Now it's working perfectly. Hopefully this helps.
