### ISSUE TITLE
Replace Promo video with new Matomo videos

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13740]
Now that there are new Matomo Marketing videos, we should replace the Welcome widget on the default dashboard (and also replace all mentions of Piwik with Matomo)

![grafik](https://user-images.githubusercontent.com/6266037/48801254-2fac1f80-ed0c-11e8-8353-1156eb8d741b.png)

https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/CoreHome/templates/getPromoVideo.twig

**Comment by tsteur** [comment]
👍  We don't have an "overall" video yet AFAIK. So not sure which one we'd show there? maybe we randomize the shown video?

**Comment by Findus23** [comment]
@tsteur A random video sounds good. Bonus would be only showing premium videos for plugins that are installed.

**Comment by tsteur** [comment]
FYI: Showing the videos in a widget will mean we need to embed a video player like https://github.com/sampotts/plyr and load it on every request etc. Unless we maybe only show placeholder images with a play button and link to a landing page in Matomo? The individual pages are here: https://matomo.org/docs/videos/   This allows us to better manage the videos eg if we remove one, change the file name, etc.

**Comment by tsteur** [comment]
Maybe we could only link to the https://matomo.org/docs/videos/  page to keep things simple?

**Comment by Findus23** [comment]
I think a placeholder image with play button that just links to the Matomo video page is probably the best solution.

**Comment by tsteur** [comment]
Sweet we simply link to https://matomo.org/docs/videos/

**Comment by mattab** [comment]
@katebutler the video shared in the FB/Twitter link is the [old one](https://www.youtube.com/watch?v=OslfF_EH81g)... can you fix it and make it so it shares the new video? https://www.youtube.com/watch?v=wxi6aumoTSI

**Comment by mattab** [comment]
@katebutler did you open a new PR for fixing the share link?
