### ISSUE TITLE
When looking at Yesterday's data, and there is data for today, notify users to try to look at Today

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13754]
A common cause of confusion for new users (who have just setup Matomo, or created a new website), is that by default Matomo shows Yesterday's data. And people often don't realise they should look at Today's to see their data. So it would be valuable to guide new users and help them understand they're looking at the wrong date (small improvement to onboarding).

### Suggested change 

* When a user is looking at "Yesterday's" data, or "Last week" or "Last month" 
* And there is "No data" 
* And there is data for "Today" (or "This week" or "This month" or "This year")
* Then we could display a message (maybe a close-able notification?) to advise users they are viewing reports the previous day/week/month/year and that they can <a>click to view Today/This week/This month/This year's report </a>

What do you think?

**Comment by tsteur** [comment]
I'm pretty sure I've suggested somewhere before to select "today" automatically when eg no data has been tracked yet, or only started tracking on that day etc.

**Comment by Findus23** [comment]
I just got tricked by this again when setting up a new Matomo instance, but seeing no reports unit I noticed I was looking at the wrong day.

I think many first time users get an impression of Matomo being kind of broken because of this.

**Comment by Findus23** [comment]
Since I last wrote here, at least three or four people I helped tripped up about this, so I think it would be amazing to new users if we could get this into 4.0.

**Comment by dev-clavis** [comment]
I also got tricked.
You might also assoicate the creation date of a new site (siteid) and prevent the ui from looking previous that date.
