### ISSUE TITLE
Event Value: "The value is not a number" when using variable

### ISSUE THREAD

**Issue by jrpub** [matomo-org/matomo#13761]
Hi,

Sorry if this issue is not a bug. When I try to set a variable name as the value of an event in the tag manager, I have the error message: 

`Event Value: The value is not a number.`

I tried with several variables (custom - for instance a constant - or a predefined one). Is this not supported or did I miss something? The weird thing is that there is the variable selector button near the "Event value", so I guess this is a supported feature.

```
Matomo version: 3.7.0
MySQL version: 5.7.24-0ubuntu0.18.04.1
PHP version: 7.0.32-0ubuntu0.16.04.1
```

**Comment by tsteur** [comment]
It's a bug indeed and created a fix for it. 

FYI: If you find more issues, please create them in https://github.com/matomo-org/tag-manager/issues ideally.
Cheers

**Comment by Findus23** [comment]
@tsteur 
> FYI: If you find more issues, please create them in https://github.com/matomo-org/tag-manager/issues ideally.

I guess this will happen more often now that MTM is a part of Matomo.

You should be able to easily move the issue to the tag-manager repo:
https://help.github.com/articles/transferring-an-issue-to-another-repository/
