### ISSUE TITLE
413 Request Entity Too Large (Tracking API)

### ISSUE THREAD

**Issue by savsgio** [matomo-org/matomo#13775]
I using the http api to try to registrer tracks with a bulk insert. Sometimes i got this error

```html
<html><head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body></html>
```

Example of body requests:
```json
{
   "requests": [
      "?idsite=1&url=http://example.org&action_name=Test bulk log Pageview&rec=1",
      "?idsite=1&url=http://example.net/test.htm&action_name=Another bulk page view&rec=1"
   ],
   "token_auth": "33dc3f2536d3025974cccb4b4d2d98f4"
}
```

The request field has a maximun lenght of 70 items or less per POST request. but i don't know why matomo returns these error.
I follow the [Tracking HTTP API guide](https://developer.matomo.org/api-reference/tracking-api)

Matomo version: 3.7.0

**Comment by tsteur** [comment]
It looks like a server configuration issue. I recommend you have a look in our [forum](https://forum.matomo.org) or post a question there if you can't find more info. A web search might help as well. Unfortunately we cannot provide support for server configurations here.

**Comment by fdellwing** [comment]
@savsgio Short anwser: Increase `client_max_body_size` in your `nginx.conf`.

**Comment by savsgio** [comment]
Finally, I decided to do the requests with batches of 100 items in the `requests` field array.

Thanks @tsteur and @fdellwing.
