### ISSUE TITLE
Ability to store the Geoip2 databases in a custom directory rather than misc/

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13770]
In the context of our Debian Matomo Package and as discussed in https://github.com/matomo-org/matomo/pull/13766, currently the databases must be stored in `path/to/matomo/misc/` folder (eg. `misc/GeoIP2-City.mmdb`). But this folder may be non-writable and therefore the automatic & regular download of geoip databases fails and generates errors.

-> To make the Debian package for Matomo more flexible and useful we could allow customisation of the geoip2 DBs path in `config.ini.php`.

**Comment by aureq** [comment]
Referencing https://github.com/matomo-org/matomo-package/issues/83
