### ISSUE TITLE
title-text of JavaScript Tracking option help box shows HTML

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13783]
![image](https://user-images.githubusercontent.com/6266037/49304265-1c4b4200-f4cc-11e8-97a4-ca5f7bc36f5f.png)

This seems to be caused by 
https://github.com/matomo-org/matomo/blob/e11866e11ddad88dbf7aee5f56431c8958acdb02/plugins/CoreAdminHome/templates/trackingCodeGenerator.twig#L61

and 
https://github.com/matomo-org/matomo/blob/e11866e11ddad88dbf7aee5f56431c8958acdb02/plugins/CoreAdminHome/angularjs/trackingcode/jstrackingcode.controller.js#L156

which of course doesn't work.

**Comment by sgiehl** [comment]
meanwhile the ui tooltips were removed from form fields. but now the browser tooltip shows up, as there is a title attribute set...
We could use `data-title` instead of `title` attributes to circumvent the browser tooltips for all formfields maybe?

**Comment by tsteur** [comment]
Than for the plugins in core, but still needs to be done for other plugins

**Comment by tsteur** [comment]
I think since https://github.com/matomo-org/matomo/pull/13442 it may not really be needed to do any more work in the plugins actually? The regular browser title might still appear for the other plugins but it may be even somewhat helpful maybe?

**Comment by Findus23** [comment]
So this has been solved with #13931 and #13442.
