### ISSUE TITLE
Linux version for Matomo 3.5.1   

### ISSUE THREAD

**Issue by JeffS25** [matomo-org/matomo#13782]
Hi Team

Could you please let me know which linux version Matomo 3.5.1 works on?

**Comment by Findus23** [comment]
All where you can install a webserver, a MySQL or MariaDB database and a PHP version between 5.5.9 and 7.2 (7.0+ is recommended)

**Comment by JeffS25** [comment]
Can you help me on piwik servers, what linux version will be suitable for 3.5.1

**Comment by Findus23** [comment]
As said before. It doesn't matter which Linux distribution you are using or which version (apart from of course using the latest one that is receiving security updates)

If you want to discuss questions about Matomo you can use the forum: https://forum.matomo.org/
This repository is intended for bug reporting.

**Comment by JeffS25** [comment]
Okay thank you!
