### ISSUE TITLE
Report for "today" is not the same as report for any date explicitly selected

### ISSUE THREAD

**Issue by mskala** [matomo-org/matomo#13786]
I have my Matomo dashboard set to default to "today", and the string "today" appears in a query field of the URL when I go to the dashboard.  When I go to the dashboard, I get the current day's stats under "Visits overview" but the previous day's graph under "Visits over time," and the previous day's date is shown in the drop-down date selector widget.  But if I manually select the current date, I get the current date shown in the URL and the date selector, and the graph shows today's statistics.  Choosing the string value "today" as a default has a different effect from explicitly selecting the current date; some parts of the dashboard use the previous day's date when "today" is the default.

See screenshot - Matomo is configured to use "today," as seen in the URL; and as seen in the live visitor log, today is December 1; but the date-selector widget has defaulted to November 30.

![screenshot_2018-12-01_17-15-44](https://user-images.githubusercontent.com/1533051/49333441-ede16b80-f58c-11e8-9a2c-4f2a204148c4.png)

I don't believe that this is caused by a time zone issue; all my time zones match, and all aspects of it appear to roll over at midnight local time every day.  It seems to be new behaviour in 3.7.0; the previous version correctly showed today's stats in all parts of the dashboard when so configured.

**Comment by tsteur** [comment]
from which version did you update @mskala ? maybe you have any thoughts @diosmosis ?

**Comment by mskala** [comment]
As far as I know, the previous version (3.6.1).

**Comment by mskala** [comment]
Both are "America/Toronto".

**Comment by diosmosis** [comment]
@mskala created a fix in this PR: https://github.com/matomo-org/matomo/pull/13787

**Comment by mskala** [comment]
I don't think it's completely fixed after all.  The "Visits Over Time" graph is still showing yesterday as the most recent day now (shortly after midnight) even though the drop-down date widget has updated to the new date; and, as before, manually selecting today's date gives a different result showing the current day's data in the graph.
