### ISSUE TITLE
something missing on setting db on install 

### ISSUE THREAD

**Issue by NathanQ** [matomo-org/matomo#13812]
I had an issue if I didn't set the db info before [using the composer](https://developer.matomo.org/guides/getting-started-part-1#get-install-composer), installing didn't work and the site said ""Error: Matomo is already installed." I went back and forth a little bit on this trying to set it in the config.ini.php after set up with this result. Maybe a bit of chicken and egg issue. The `matomo/config/global.ini.php` states "Edit the config.ini.php instead," but it is not present before setup. Anyway, setting db in the `matomo/config/global.ini.php` like so got me running.
```
[database]
host = "127.0.0.1"
username = "matomo"
password = "matomolikeamomo"
dbname = "matomodb"
tables_prefix =
port = 3306
adapter = PDO\MYSQL
type = InnoDB
schema = Mysql
```
Maybe I missed something in the docs?

Thanks

**Comment by tsteur** [comment]
Can you confirm you installed Matomo through git, init & updated all submodules, ran composer, and did not have yet a `config/config.ini.php`? Is this the full error message?

If you don't want to develop on top of Matomo, I recommend to download the latest version from https://matomo.org/download/ btw compared to git.

**Comment by NathanQ** [comment]
Hi @tsteur, I can confirm this, but I ran into issues with permissions issues and had to run the `sudo chown -R www-data:www-data ./*various_dirs*` create directories in the tmp directory during setup which may be where this stems from. This was a fresh install of php, mysql, and nginx and they're users ran as their default installed on Ubuntu 18.04 server.  For instance, when I run the composer, the new directories' permissions were displayed as question marks. My user wasn't meshing right. I did get up and running, but I'll try it again.

**Comment by tsteur** [comment]
AFAIK there aren't any known issues from our side and I reckon it is indeed just some server configuration. The `various_dirs` are expected to need write permission, eg also the `config` directory. The `config/config.ini.php` is created during the installation. Where are you stuck in the installation process exactly? Does it even load? Otherwise composer should for sure not require any DB configuration.

**Comment by NathanQ** [comment]
Hi again. 
Went to update and ran into permission issues. Updating under one user and my webserver runs as another unable to read the other user's files. Where are the server user and group permissions documented?
Thank you!

**Comment by NathanQ** [comment]
Got it running. If the server setup includes say a user other than the web server user. Mine's `matomo` and my web server is `www-data`.

On setup and after updates, in the matomo/tmp directory these commands must be run:
```
sudo chown matomo:www-data -R .
sudo find . -type d -exec chmod 2775 {} \;
sudo find . -type f -exec chmod 664 {} \;
```
