### ISSUE TITLE
Page Overlay: Links do not have bubbles even if they are not a redirect

### ISSUE THREAD

**Issue by chrisprog20** [matomo-org/matomo#13811]
Hello, 

I discovered that some of the links in the page overlay do not have bubbles even if they are not a redirect.
Even if no one clicked this link there should be at least a bubble with label "0%". I already saw this for other links. I think this is a bug, isn't it?

Thank you for your answer :)

Cheers
Christian

**Comment by mattab** [comment]
Thanks for creating the issue. When there is a bubble with "0%" displayed it is when there were a few clicks but the number must be close to 0. For links without clicks there is no bubble displayed.

**Comment by chrisprog20** [comment]
Thank you for the clarification! :)
