### ISSUE TITLE
MATOMO 3.7.0 - WARNING - create_function() is deprecated

### ISSUE THREAD

**Issue by gpwebcgti** [matomo-org/matomo#13810]
I got the following warning after login to web interface.

> WARNING: /var/www/html/piwik/libs/HTML/QuickForm2/Rule/**Compare.php(103)**: Deprecated - Function create_function() is deprecated - Matomo 3.7.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)

It started just after upgrading to the 3.7.0 version.

Is it important?
Does someone know how to solve that?

**Comment by tsteur** [comment]
Hi there, this was fixed in https://github.com/matomo-org/matomo/pull/13463 . Will be fixed in next release.
