### ISSUE TITLE
Seperate 'Delete old visitor logs' & 'Schedule old data deletion' from Privacy Manager plugin

### ISSUE THREAD

**Issue by bahooha** [matomo-org/matomo#13814]
Recently I disabled the 'PrivacyManager' plugin, because I do not plan on using any of it's Anonymize data features. Unfortunatly this also meant I was no longer able to access the 'Delete old visitor logs and reports' setting link from the General settings tab.

In my Matomo setup, I do no plan on using anonymize or GPDR related plugins, and thought that disabling the plugins would lead to an (even) faster dashboard. I do use the data deletion to keep sql filesize minimal.

Maybe there is an intentional link between delete old logs & schedule old data deletion that I've missed. But can I suggest to seperate the delete olds logs & schedule old data deletion from the PrivacyManager into a new Data Delete plugin?

**Comment by tsteur** [comment]
@bahooha thanks for the suggestion. Indeed someone may be interested in deleting data for performance reasons and not for privacy reasons. I don't think we will split this into a separate plugin though as loading the `PrivacyManager` pretty much should not slow it down at all. The dashboard won't load faster by disabling it. I'll close the issue as I don't want to give any false hopes. We won't be working on this as it would be quite a bit of work in separating it without gaining much benefit from it. I recommend to leave the privacy manager enabled and there won't be a noticeable performance difference.
