### ISSUE TITLE
Double encoded single quotes in goal names

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13828]
## Reproduce
* Create a goal called `hello ' world` and also use this text as the Goal description
* Then see the goal appear as `hello &#039; world`

## in Goals

See the below screenshots of Goal overview and Manage goals showing the double encoding:

![new goal](https://user-images.githubusercontent.com/466765/49832492-b62fba80-fdfb-11e8-928e-dddd1c98739b.png)

![hello world](https://user-images.githubusercontent.com/466765/49832493-b62fba80-fdfb-11e8-8d7e-a60821dfc74b.png)

## in Forms

Similar issue in Form Analytics: 
![form description](https://user-images.githubusercontent.com/466765/49863865-19eecd80-fe66-11e8-8a9e-d59b7dd346f1.png)

Maybe a regression from https://github.com/matomo-org/matomo/pull/13715

Would be valuable to add some UI tests that would catch the issue.

**Comment by sgiehl** [comment]
That's a more global and general issue of our input sanitize. 

For goals we send the values using `encodeURIComponent`. That kind of circumvents the automatic input sanitize for all chars expect `- _ . ! ~ * ' ( )`, which keep untouched. Thus the `'` is stored as `&#039;` in the database. Will create a PR to fix that partially. But imho it would make most sense to finally get rid of the global input sanitize

**Comment by tsteur** [comment]
> But imho it would make most sense to finally get rid of the global input sanitize

That would be awesome. Also causes issues eg in tag mananger https://github.com/matomo-org/tag-manager/issues/134 . Not sure if it will be ever possible to fully get rid of it though as it could cause so many issues. Best might be to support it slowly and refactor it step by step. Like if a variable starts with `underscore _` in API, it gets it unserialized or something like that. Or maybe it can be configured somehow.

**Comment by diosmosis** [comment]
Should be fixed in 3.x-dev
