### ISSUE TITLE
Fix release numbering in changelog

### ISSUE THREAD

**Issue by mcnesium** [matomo-org/matomo#13827]
Our monitoring system complained about our Matomo not being up to date. Though we did update as soon as the Docker image was released, the monitoring system kept throwing alerts. Why was that?

Because [in v3.7.0 `CHANGELOG.md` has not been updated](https://github.com/matomo-org/matomo/blob/4baf32cfe4fbe246381bc385d74bf3ab841fee1a/CHANGELOG.md), and thus the monitoring tool thought, this was still v3.6.1. Let's not discuss whether that is a good metric, but focus on why this is not done automatically somehow. On the tag to v3.8.0-b4 [the version number in `CHANGELOG.md` switched all the way from 3.6.1 to 3.8.0](https://github.com/matomo-org/matomo/commit/1bea8652a119d9098c695bba6c15bcd7d7fbaea9) even though whe are obviously not there yet.

Can you guys please fix this?

**Comment by Findus23** [comment]
Hi,

The `CHANGELOG.md` is **not** the changelog of the Matomo application, but a changelog for developers depending on Matomo. As nothing changed with 3.7.0., there is no entry.

For checking the latest version of Matomo, please use the API:
https://api.matomo.org/1.0/getLatestVersion/

Or check the `https://builds.piwik.org/LATEST` file.

**Comment by tsteur** [comment]
If you want to know the current version of your Matomo, please fetch the API method `API.getMatomoVersion` see https://developer.matomo.org/api-reference/reporting-api
