### ISSUE TITLE
Add Table of Content to General Settings

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13837]
Just a random thought, but now that Matomo has more and more features (and quite a few plugins that also have options) General Settings is becoming quite long (12137px for me)

One easier fix would be adding a table of content to the top so one could quickly jump to the plugin one wants to configure.

**Comment by tsteur** [comment]
We would possibly add the same table as in the tracking code page at some point

**Comment by tsteur** [comment]
Will be great to have. We now have so many settings in there that can provide quite a lot of value and it's easily missed what Matomo offers when not seeing some kind of overview.

It would be a "horizontal table of contents" probably.

**Comment by tsteur** [comment]
we'll use the same UI pattern as we use on the Measurable -> Tracking code page
![image](https://user-images.githubusercontent.com/273120/127236680-2930c739-381e-4725-8593-115452b56efa.png)
