### ISSUE TITLE
Stop failing when CIP tracking parameter is set but not authenticated

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13854]
see eg https://github.com/matomo-org/matomo-php-tracker/pull/39 

in https://github.com/matomo-org/matomo/pull/13675 we started failing the tracking request when no CIP parameter is set. However, I noticed that by default we always set the CIP parameter in the PHP tracker. So if someone now uses the php tracker without a valid token, all tracking requests will fail. Maybe we should wait for Matomo 4 for this change?

We could restore old behaviour and use the REMOTE_ADDR as a fallback instead when no token provided. @mattab ?

**Comment by mattab** [comment]
Sounds good @tsteur 
Reckon it's important to address this as currently it must break a lot of PHP SDK usages.

**Comment by diosmosis** [comment]
@tsteur is this fixed by this revert: https://github.com/matomo-org/matomo/pull/13858 ?

**Comment by tsteur** [comment]
We would only need to revert this line: https://github.com/matomo-org/matomo/pull/13858/files#diff-6700aaf1ce500fe51e284b9ec6f01b01L892

for the other ones (userCountry) it be still good to fail if they are specified.

**Comment by tsteur** [comment]
Getting confused now as well. Didn't see this was reverted :) Ideally, we would have only reverted the line I mentioned but kept the other ones.  (hoping this clarifies it a bit more).

Cause `city`, `country` etc is not set by the PHP tracker or so. This way it's fine to fail the tracking request so users become aware there is a tracking problem.
