### ISSUE TITLE
Matomo does not display information in Behaviour for non ecommerce websites

### ISSUE THREAD

**Issue by anna-bildyug** [matomo-org/matomo#13876]
We use matomo for non-ecommerce site. 
I created website in matomo cloud and set it as non-ecommerce in settings. I've seen that all activities are tracked in visitors view, but not in behaviour.
After some research and clicking around I found out that I can see data in behaviour only when site is set as ecommerce.
I am not sure that it is correct and clear behaviour

**Comment by tsteur** [comment]
Hi there, just tried to reproduce this on my test Matomo but couldn't. You should definitely see data in behaviour when ecommerce is disabled. Could you please get in touch with our support via email: support@matomo.cloud . This way it will be easier to help you and investigate the issue. Please also mention your subdomain in the email (xyz.matomo.cloud for example)

**Comment by YouAint1stURLast** [comment]
Hi Tsteur,

We self host our instances and we are running into an issue where some instances show Behaviour data and some instances do not. In the troubled accounts randomly we will see some Behaviour data and then the next day it will disappear.

I am open sending you more client specific information in a private chat.

Thank you.

**Comment by tsteur** [comment]
@YouAint1stURLast this is something you maybe want to ask in your forum https://forum.matomo.org or contact our support https://matomo.org/support-plans/

**Comment by YouAint1stURLast** [comment]
Hi Thomas,

Thank you for the advice.

Does the behavioral reporting rely on the _id parameter at all? If there is
a problem with this parameter at all could it break the behavioral reports?

Thank you,

Ross
