### ISSUE TITLE
“Anonymize past data” is not working

### ISSUE THREAD

**Issue by cleger80** [matomo-org/matomo#13878]
Version 3.7.0

When we start “Anonymize past data” , we always stay in the "In progress" Status (even after days).
We tried manually from the Matomo backend and also with the command line.
![matomo_anonymization](https://user-images.githubusercontent.com/15106126/50148279-5f712780-02b8-11e9-8dbb-f475960cc265.png)

**Comment by tsteur** [comment]
Do you get any error when you execute it on the command line? Can you paste the output here?

If your DB is very large, it could take a VERY long time for such a big date range (depending when you started tracking data and how much data is in there). Maybe check your processlist if the command is maybe still running or so? You might also need to use something like `nohup` to keep the command active after you log out via ssh...

**Comment by mattab** [comment]
Any update @cleger80 - do you still have an issue with the feature in Matomo?

**Comment by wlabarron** [comment]
I'm having a similar problem. My task is stuck as "Scheduled", and I don't know what I can execute on the command line to make it start now.

**Comment by tsteur** [comment]
you could try to run `./console core:run-scheduled-tasks "Piwik\Plugins\PrivacyManager\Tasks.anonymizePastData"`

**Comment by tsteur** [comment]
@wlabarron @cleger80  do you still experience this issue? Does it work when manually trigging the task as mentioned in my previous comment?

**Comment by wlabarron** [comment]
Whoops, hadn't realised I didn't reply. If I remember right, the above command triggered the process to start and the tasks I had at the time are all marked as done now.

I've just scheduled another task to test this, so I'll check on that in a couple of days and see how it looks.

**Comment by wlabarron** [comment]
@tsteur Looks like the task I created a couple of days ago ran by itself, without needing the command above run manually.

**Comment by tsteur** [comment]
Great, thanks for testing and confirming @wlabarron very appreciated
