### ISSUE TITLE
Actions_SubmenuPageTitles : two lines in report for same page title

### ISSUE THREAD

**Issue by eldk** [matomo-org/matomo#13880]
Hello,

Page  "Actions_SubmenuPageTitles"  begin to display two lines in report for same page.

Each line have columns "Pageviews ..." with different numbers.

"Open Transitions" and "Open Raw Evolutions" gives same datas for the two lines. 

First seen on a domain with one page from which title have not been modified and no change at all on server.

Matomo version was 3.8.0-b4. I have upgraded to 3.8.0-b5 : no change : one page title gives two lines in report.

It's happened on a second domain with more pages too.

It's look like something change past some event or date as ?

Thanks,

Eric

**Comment by tsteur** [comment]
Can you post a screenshot maybe to clarify what you mean by "two lines for same page". Does the title maybe include a `/`?

**Comment by eldk** [comment]
Yes, 

I think it's related to 3.8.0-b4 as I upgrade to it on 12 december.

![screenshot](https://user-images.githubusercontent.com/11083657/50187653-0a1c3100-031f-11e9-905f-37244972c852.png)

**Comment by tsteur** [comment]
Could you paste the exact titles? Feel free to change the letters... Are there maybe any extra spaces in the middle or something?

**Comment by eldk** [comment]
One link to the one page website : 

https://lamaille.opalesurfcasting.net/

I will remove it later.

**Comment by tsteur** [comment]
OK thanks. Maybe you could email us an image of the two titles to hello at matomo.org just to get a better understanding. Feel free to remove the link again.

**Comment by eldk** [comment]
OK

**Comment by tsteur** [comment]
Cheers for sending the mail 👍  I've tried to reproduce by tracking it first with Matomo 3.7.0 and then with Matomo 3.8.0-b5 but didn't run into the problem. Thanks though for sending the link and I can now see the issue. There is one entry with a leading space, and another without... Makes me realise this might only happen when period != day. 

I remember when a delimiter is set, it may add a space here https://github.com/matomo-org/matomo/blob/3.8.0-b5/plugins/Actions/ArchivingHelper.php#L468-L477 but don't quite understand the problem.

and thought that https://github.com/matomo-org/matomo/compare/3.x-dev...13880?quick_pull=1 might fix the issue but not sure if this would have any side effects.

@diosmosis @mattab @sgiehl  do you maybe know why exactly the whitespace is prepended?

**Comment by tsteur** [comment]
Note: putting this into 3.8.0 to look at it as it may or may not be considered a regression. It was expected there would be a difference when the title contains `/` but wasn't thinking it would regress when it contains a ` - `. @eldk any chance you have set a custom action title delimiter of `-`?

refs https://github.com/matomo-org/matomo/pull/13688 and https://github.com/matomo-org/matomo/issues/2956

**Comment by eldk** [comment]
>any chance you have set a custom action title delimiter of -?

No, I haven't set any custom title delimiter.

This happened too with page title without any special character.

For example a two words title : Foo Bar

**Comment by tsteur** [comment]
Cheers 👍  I can see this might be an issue for all pages...

so maybe a fix like this could be more appropriate where we still keep prepending the whitespace https://github.com/matomo-org/matomo/compare/3.x-dev...13841_2?quick_pull=1 ... it's a bit funny but might be the safest fix. Still not understanding why we prepend titles with a whitespace.

**Comment by tsteur** [comment]
That's what I thought and did in https://github.com/matomo-org/matomo/compare/3.x-dev...13880?quick_pull=1 but thinking it could break something? Trying to understand when that whitespace is important :)

**Comment by eldk** [comment]
Hello,

- With Matomo 3.8.0-b4 :

>"Open Transitions" and "Open Raw Evolutions" gives same datas for the two lines.

and reported numbers were accurate - total pageviews number is the total pageviews for the chosen period, datas previous to 3.8.0-b4 update included .

- With Matomo 3.8.0-b5

>"Open Transitions" and "Open Raw Evolutions" gives same datas for the two lines.

but reported numbers are not accurate - total pageviews number is the total pageviews since Matomo 3.8.0-b4 update - previous datas are not reported in the total pageviews number.

To repro : 

- Use Matomo 3.8.0-b4
- Use a period or date range that include datas collected before Matomo 3.8.0-b4 update.
- Check numbers in Actions_SubmenuPageTitles > "Open Transitions"
=> the reported numbers are accurate for chosen period
- Use Matomo 3.8.0-b5
- Check numbers in Actions_SubmenuPageTitles and go to "Open Transitions"
=> the reported numbers are only those since 3.8.0-b4 update

**Comment by mattab** [comment]
>  Trying to understand when that whitespace is important :)

This was a long time ago, but the comment helps me remember why, if we didn't put the whitespace in, then somehow if you have the following 2 requests:

* `/some-path`
* `/some-path/`

They would be both aggregated under the same (maybe under `some-path/` but not sure),
but we do want to keep them different since `/some-path` will show as `some-path` while `/some-path/` will show as `some-path (directory) -> /` where the page is `/` and `some-path` appears as a clickable directory.

Sorry it's probably not very clear but maybe if you remove and try to run the tests they would fail? (hoping that tests test for this)

**Comment by eldk** [comment]
I've tried https://github.com/matomo-org/matomo/compare/3.x-dev...13841_2?quick_pull=1

Datas are added to origin line (the one that exist before 3.8.0-b4). Same title hash ?

But second "new line" is still there.

**Comment by tsteur** [comment]
@eldk not sure what you mean by "Back to origin title hash ?" and "New title hash"?

If it still appears there's a good chance you may need to invalidate some report data see https://matomo.org/faq/how-to/faq_155/ If you can access the server you can for example execute a command like `./console core:invalidate-report-data --dates=2018-12-01,2018-12-22` otherwise you can also use the HTTP API. The data might only become available correctly after the next archiving run depending on whether this is done by a cron job or through browser.
