### ISSUE TITLE
Referrer Websites report should group same label (HTTP vs. HTTPS)

### ISSUE THREAD

**Issue by GreenReaper** [matomo-org/matomo#13882]
While reviewing visits from Tumblr, I expanded referrals and clicked "open row evolution" on the first sub-row:

![tumblrevolution](https://user-images.githubusercontent.com/383043/50219979-d8d84b00-0388-11e9-9fab-429bd32d8366.png)

To my surprise it showed a very sparse graph with only a few views each day. I found that whichever of the two rows I clicked evolution on, it was giving me the data for the second row. Hovering over the 'index' links to the left, I found that the first row was for referrals from the HTTPS url, and the second for HTTP.

The parameters encoded within the graph's request URL are:

> date=today
> apiMethod=Referrers.getWebsites
> label=t.umblr.com+>+@index
> disableLink=1
> module=CoreHome
> action=getRowEvolutionPopover
> colors={"backgroundColor":"#ffffff","lineColor":"#162c4a","minPointColor":"#ff7f7f","maxPointColor":"#75bf7c","lastPointColor":"#55aaff","fillColor":"#ffffff"}
> flat=0
> idSite=1
> period=day

These requests are the same if I click on either row evolution icon - which makes sense, the path just says "index". But when processing the request, it picked the less-used option - _not_ the option I selected. If it's going to separate them by scheme/URL, duplicating the label, it should use scheme/URL for the evolution.

"Metrics for Website" on the popup itself showed the website domain name as well as the path, but _not_ the access scheme. Perhaps if it had shown "http:" or "https:" as well, this issue would have been more visible.

There seems to be plenty of information within the row's <tr> to make this distinction, e.g.:
`<tr data-segment-filter="referrerUrl==https%3A%2F%2Ft.umblr.com%2F" data-url-label="https://t.umblr.com/" data-row-metadata="{&quot;segment&quot;:&quot;referrerUrl==https%3A%2F%2Ft.umblr.com%2F&quot;,&quot;url&quot;:&quot;https:\/\/t.umblr.com\/&quot;}" class=" ">`

In this _particular_ case it doesn't matter because I can just use the top-level graph which does work as it combines views from all paths (and here, there is only one path). However, in the general case it is a problem:

![multipleurl](https://user-images.githubusercontent.com/383043/50221426-fdcebd00-038c-11e9-8e4e-5352bd84451d.PNG) - HTTP or HTTPS? Can't tell at a glance. Row evolution for both picks the second.

I'm using Matamo 3.8.0-b5 on nginx with PHP 7.3 and MariaDB 10.1.37 on Debian Stretch.

---

Even more generally (maybe this has an issue already): HTTPS and HTTP requests are not combined. While technically these may be completely different sites, in practice they're almost certainly not and would be more useful together. One of our main referrers is, by default, HTTP, but may be configured to force a user's requests to HTTPS. So some visitors from it will be using HTTP and others HTTPS, resulting in two entries.

This makes it difficult to track unique requests from that site (you have to either open them twice or try to remember which complicated numerical URLs you've seen that day) and also decreases the number of useful samples in the top-50 AJAX report available via the dashboard.

Perhaps there should be an option - and I'd argue that it should be the default - to use 'group by' or similar in the database requests to merge entries which will end up with the same label. Of course the same option would have to be used throughout where requests are made, like row evolution. Or the merger could be done in PHP but this would be less efficient and I imagine it wouldn't end up with 50 items in top-50 etc.

**Comment by tsteur** [comment]
Thanks for that 👍 

Any chance you could try this change? https://github.com/matomo-org/matomo/pull/13884/files 

I'll also change the title so it's more clear for us what to do.

**Comment by GreenReaper** [comment]
The change does appear to group the graph. So the line graph now shows more visits than either.
If you click the row evolution it will then show 7 views which is bigger than the row.
So far all well and good. However...

It has a more interesting impact on the referrer path list. Entries are not _always_ grouped. So for example:
* the 2nd referrer is: **https:**//www.furaffinity.net/view/29795460/ and has 4 unique visitors
* the 10th referrer is: **http:**//www.furaffinity.net/view/29795460/ and has 3 unique visitors

There are **eight** referrers listed on the first page which shows as "1-10". I am guessing that on that page, there were two pairs that were merged. So merging between pairs is only done if they are on the same page.

Seemingly the merge has taken place *after* the "1-10" list is determined. In SQL it would be doing something like `(select ... offset 0 limit 10) group by 'label'`.  To get consistent results, what needs to happen is for the `group by` to be _within_ the subquery, not outside it. That way it will always merge mergable rows and always show the right number for each page of the results list.

There is also the question of whether https: or http: is preferred for the link on the label. I'd tend towards https: but that might misrepresnt how many people visit with https and overall it doesn't matter a huge amount - it might be inefficient to indicate a preference, especially if it has to count which has the most hits.

**Comment by tsteur** [comment]
Cheers makes sense 👍  Could you do me a favour and test the updated PR? https://github.com/matomo-org/matomo/pull/13884/files

**Comment by GreenReaper** [comment]
The updated PR does not change the above situation. Here is what I am seeing, in case it helps:

![views](https://user-images.githubusercontent.com/383043/50248380-bbc86a00-03d2-11e9-81c7-215e82c16b20.png)
![page1](https://user-images.githubusercontent.com/383043/50248382-bbc86a00-03d2-11e9-9e2d-271c58d1dc1e.png)
![page2](https://user-images.githubusercontent.com/383043/50248381-bbc86a00-03d2-11e9-9d1a-edfc5954e4fb.png)

**Comment by GreenReaper** [comment]
Oh, never mind, I messed up and left the last filter as queueFiter. 😅
I think it is working properly now, I see a 7, but I will test a bit more...

**Comment by GreenReaper** [comment]
So, it does appear to be grouping! In fact I can tell the actual number in the table has been impacted because in this case the dashboard view for this website is showing 1-41 rather than 1-50.

This is very helpful for me - reducing the duplicates makes that list far more useful.

I should caution that this might not be the desired behaviour if someone particularly wanted to tell whether visitors referred via https vs. http had some difference in actions/average time/bounce rate, etc. However I'm struggling to think of a case where this would be as useful as having them grouped.

**Comment by tsteur** [comment]
Same, I think it should be definitely grouped 👍  If needed, one could possibly work around with segments if needed maybe.
