### ISSUE TITLE
Revisit INI config recognized in #13923 after merged

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#13937]
After https://github.com/matomo-org/matomo/pull/13923 is merged, we can see what effect it will have on a Matomo instance, and can better decide whether to enable these options all the time. Though if things don't work we'll want to fix those issues if possible, so we can enable these logs all the time.

**Comment by mattab** [comment]
Is there any cons to activating it all the time? or what do we need to do to "see what effect it will have on a Matomo instance, and can better decide whether to enable these options all the time" ?

**Comment by tsteur** [comment]
Eg storage size etc. Being able to fill someone's hard drive etc.

**Comment by mattab** [comment]
Duplicates https://github.com/matomo-org/matomo/issues/15220
