### ISSUE TITLE
Tag Manager "Manage Containers" section is not rendering anything even when TagManager plugin is enabled. 

### ISSUE THREAD

**Issue by Addyvan** [matomo-org/matomo#13940]

**Comment by tsteur** [comment]
Can you provide us some more details? Can you maybe check https://github.com/matomo-org/tag-manager/issues/140 where it was just a caching problem and https://github.com/matomo-org/tag-manager/issues/132 where it was a mod_pagespeed problem for example.

**Comment by tsteur** [comment]
I reckon this will be fixed with the next 3.8 release as Tag Manager was not marked as a core plugin the wrong JS asset file was invalidated.
