### ISSUE TITLE
[https://forum.matomo.org] ssl cert expired

### ISSUE THREAD

**Issue by babatundebusari** [matomo-org/matomo#13945]
![image](https://user-images.githubusercontent.com/6054104/50950540-45ba9e80-1478-11e9-983e-d6cf9f529ebe.png)

![image](https://user-images.githubusercontent.com/6054104/50950613-7e5a7800-1478-11e9-9be5-2bcafffc8730.png)

**Comment by Findus23** [comment]
This should be fixed now.
