### ISSUE TITLE
Clicking on a graph leads to error

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13941]
Reproduce on Matomo 3.8.0-rc2:

* On this page: https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=week&date=today&updated=1#?idSite=62&period=week&date=2019-01-03&category=General_Visitors&subcategory=General_Overview
* Click on a dot in the graph. The url it tries to load is: https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=range&date=2018-08-06&updated=2#?idSite=62&period=range&date=2018-08-06&category=General_Visitors&subcategory=General_Overview

* The error is displayed: `The date '2018-07-30' is not a correct date range. It should have the following format: 'lastN', 'previousN', 'YYYY-MM-DD,YYYY-MM-DD'.`
* Expected instead the page to reload and that the selected date is the clicked date. The URL it tries to load should have been https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=week&date=2018-08-06&updated=2#?idSite=62&period=week&date=2018-08-06&category=General_Visitors&subcategory=General_Overview

This should be a regression because it appears to work in 3.7.1

**Comment by diosmosis** [comment]
FYI, just a proxying issue. Will look at it soon.

**Comment by diosmosis** [comment]
Fixed in ProxySite (fixed on demo.matomo.org)
