### ISSUE TITLE
builds.matomo.org - SEC_ERROR_EXPIRED_CERTIFICATE

### ISSUE THREAD

**Issue by eldk** [matomo-org/matomo#13944]
Hello,

Error while updating to 3.8.0-RC2 :  SEC_ERROR_EXPIRED_CERTIFICATE.

>builds.matomo.org utilise un certificat de sécurité invalide. Le certificat a expiré le 10 janvier 2019 à 00:59:59 UTC+1. La date courante est 10 janvier 2019 à 02:50. Code d’erreur : SEC_ERROR_EXPIRED_CERTIFICATE

Thanks,

Eric

**Comment by kartolo** [comment]
connected to #13945?

**Comment by Findus23** [comment]
Yes, this is the same certificate as #13945

**Comment by Findus23** [comment]
This should be fixed now.
