### ISSUE TITLE
GEO location isnt' working (DB is not available)

### ISSUE THREAD

**Issue by narfk** [matomo-org/matomo#13947]
I use Matomo with Geolocation > GEOIP Legacy (PHP).
The Download URL https://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz is not reachable. 

It seems there is a new version (v2), but it's a binary (.imdb).
https://dev.maxmind.com/geoip/geoip2/geolite2/

So, how to use GEO Location for the future?

**Comment by sgiehl** [comment]
you need to activate the `GeoIP2` plugin if that wasn't already done. Then you should be able to set up GeoIP2 as location provider. This will use the imdb files

**Comment by narfk** [comment]
thank you!
i didn't know about the GeoIp2 Plugin.
Works fine.
