### ISSUE TITLE
measuring wordpress infinite scroll on single page load

### ISSUE THREAD

**Issue by babatundebusari** [matomo-org/matomo#13946]
Using this plugin **https://wordpress.org/plugins/ajax-load-more/**
which allows infinite scroll to another page on single page load

how can i implement matomo to track every single new page load?
i do see this doc page https://developer.matomo.org/guides/spa-tracking

but still not clear of a simple way to integrate this for the particular plugin for wordpress

**Comment by tsteur** [comment]
Hi. Please ask this question in our forum: https://forum.matomo.org

We only manage bugs and features here. Hopefully in the forum someone can help you. Otherwise I reckon you contact the plugin developers ajax-load-more how to listen to an event when another page is being viewed.
