### ISSUE TITLE
Allow reenabling cookies

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#13950]
Suggested here: https://forum.matomo.org/t/disable-and-enable-cookies/31171

As one can disable cookies it sounds reasonable to provide a way to re-enable cookies (e.g. to disable cookies by default, but allow an opt in)

In theory this should work, but there may be some issues in the details. (e.g. one has to undo the `browserFeatures.cookie = '0';`)
```javascript
this.enableCookies = function () {
    configCookiesDisabled = false;
};
```

**Comment by mattab** [comment]
marking as duplicate of https://github.com/matomo-org/matomo/issues/13056
