### ISSUE TITLE
Check that when a website (or a segment) is deleted, we also delete all archive data (numeric, blob)

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13966]
In order to space disk size and costs, when a website is deleted, or when a segment is deleted, we need to make sure that archived reports stored in the `archive_numeric*` and `archive_blob*` tables are also deleted.

**Comment by tsteur** [comment]
refs https://github.com/matomo-org/matomo/issues/13976 when a user is deleted, we need to make sure to also delete all segments and their archives.

**Comment by mattab** [comment]
Notes from a call:

* likely this could be implemented as a job that deletes all archives that are not part of the "Known segments"
* for each archive table, get the list of unique done flags for each segment known in the system
  * use this list to delete all the other archives (whose done flags are not in this list)
* making sure only archives older than 24 hours are deleted (as newer archives may be currently in use)

**Comment by tsteur** [comment]
@mattab how about segments that aren't automatically archived. I suppose we keep them in the archive tables? or delete them as well when they are older?

**Comment by tsteur** [comment]
@mattab are there maybe also range archives that we can delete?

**Comment by mattab** [comment]
Segments that aren't automatically archived,  keep them forever. 
Range archives might be already deleted automatically after some time, iirc. So there shouldn't need to do anything special with then.
