### ISSUE TITLE
Segments are not deleted when User is deleted

### ISSUE THREAD

**Issue by pfleckenbw** [matomo-org/matomo#13976]
When I delete a user with username "TestUsername" and later create a new user with the same username, the second user get all segments defined of the first user.
IMHO. the delete-user-action should delete also the users segments. At least his private segments. All public segments should be transfered to an Admin of the website.

### Reproduction:
1. Create an User named "TestUsername"
2. Give him Permissions to WebsiteA
3. Sign in with  "TestUsername"
4. Create any segment
5. Delete the User "TestUsername"
6. Create another User named "TestUsername" (with any eMail-address)
7. Give him Permissions to WebsiteA
8. Sign in with "TestUsername"
9. The previously created Segement is already there :-(

### Environment
* Matomo-Versuib: 3.7.0
* MySQL-Version: 5.1.73-log
* PHP-Version: 5.6.39 (Yes, it's outdated, but I can't believe, that the PHP-Version is the reason for this issue

**Comment by mattab** [comment]
Thanks for the report @pfleckenbw! This bug is still active it seems. 

Liking your suggestions below :+1: 

> the delete-user-action should delete also the users segments. At least his private segments. All public segments should be transferred to a [Super User.]

**Comment by mattab** [comment]
fixed in  #17231
