### ISSUE TITLE
Add shortcuts to admin homepage

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13979]
Add a new widget with some buttons to quickly perform some common actions such as 
* Add new website
* Add new user

Those few things can be otherwise hard to find and maybe make users think they cannot add a 2nd website. Especially since they might not know "Measurables" is websites etc.

![image](https://user-images.githubusercontent.com/273120/51443691-c66b7b80-1d51-11e9-8ebd-edbd4490faea.png)

Others items would maybe not be needed for now as most of them can be found easier. Those are two actions we want users to take though in many cases (add user and add website).

**Comment by AGiallelis** [comment]
Is anyone working on this issue?

**Comment by Findus23** [comment]
I think no one is working on this at the moment, but I think this would be a great first issue to contribute to Matomo as this shouldn't be hard following https://developer.matomo.org/guides/widgets

**Comment by courtneywright** [comment]
I'll give this a go.

**Comment by courtneywright** [comment]
I’m currently working on this issue and came across a problem. I'm trying to link to the 'Add new user' dialog in the UserManagement->index module. However, the dialog's visibility is determined by an angularjs component state. How can I href to another page and pass along this angularjs state?

**Comment by tsteur** [comment]
@courtneywright I'm not quite sure why you're adding this link in the UsersManager->index module? Or do you mean you're trying to add a logic that directly opens the `dialog` in the users manager? If you add the URL parameter `&showaddsite=1` this should already happen.
