### ISSUE TITLE
Clarify supported PHP versions

### ISSUE THREAD

**Issue by J0WI** [matomo-org/matomo#13985]
The current system requirements are "PHP version >= 5.5.9".
This is not true. PHP 7.2 throws warnings before Matomo 3.8.0 and PHP 7.3 still does.
No warnings should be present in officially supported PHP versions.

See also:
https://github.com/matomo-org/matomo/issues/11936: tests are only run on PHP 5
https://github.com/matomo-org/matomo/issues/13272: fixes issue with PHP 7.2
https://github.com/matomo-org/matomo/issues/13418: PHP 7.3 issues

**Comment by Findus23** [comment]
Hi, I agree that there are still issues with 7.3 (but this should only be warnings by PHP that the coding style is ambiguous and nothing that changes how PHP works).
This mostly depends on https://github.com/matomo-org/matomo/pull/13639 which has the potential to break things for 5.x users as the latest version of the library doesn't supprot 5.x anymore.

I don't know of any 7.2 errors or warnings. I have been running Matomo with 7.2 for a long time and didn't see any. If you are experiencing warnings, please report them, so they can be fixed.

**Comment by J0WI** [comment]
I didn't use PHP 7.2 before #13272. I updated PHP for Matomo 3.8.0 in the Docker image: https://github.com/matomo-org/docker/commit/15c48dba053c52bcfe9a2ec67c9d28825283654a
But I think it's bad to ship with PHP 7.3 by default while there are still warnings.

**Comment by Findus23** [comment]
Now with 3.8.1 all PHP 7.3 bugs should be fixed (unless someone finds a new one)

**Comment by J0WI** [comment]
> unless someone finds a new one

This risk could be reduced by adding PHP 7.3 to Travis CI.
