### ISSUE TITLE
Content Tracking: Interactions count greater than impressions count

### ISSUE THREAD

**Issue by theseyi** [matomo-org/matomo#13988]
May potentially be related to #6270

- I have single page application that features a search page
- Search results are manually using internal search tracking via `trackSiteSearch` 
- As per Piwik/Matomo [recommendation](https://developer.matomo.org/guides/tracking-javascript-guide#internal-search-tracking), `trackPageView` is not called on the search page since `trackSiteSearch` is already being called
```
// We recommend not to call trackPageView() on the Site Search Result page
```
- I am also tracking content impressions automatically using data-attributes and initializing via a call to `trackAllContentImpressions`
- Interaction tracking is handled by Piwik automatically on click, for each content block

The steps to reproduce this issue
- Perform a search query
- - the content impression should now be tracked for the items in the search result
- - `trackSiteSearch` is called
- Click on the trackable content in search result
- - on page transition, the interaction **_is_** tracked
- Navigate back to the Search results page by clicking the back button in the browser
- - the content impression **_is not_** tracked for the items in the result
- - click the trackable content in search result
- - on page transition, the interaction **_is_** tracked

The above steps will result in more content interactions than content impressions for the content block that is interacted with.

~~I believe the issue emanates from the fact that on back navigation, all content impressions are not registered in Piwik even though a call is made via `trackAllContentImpressions`, because a call to `trackPageView` is not made to force Piwik to register the impressions?~~

~~As per [Content Tracking](https://developer.matomo.org/guides/tracking-javascript-guide) section:~~
```
We won't send an impression of the same content block twice if you call this method multiple times unless trackPageView() is called meanwhile. This is useful for single page applications.
```

EDIT:

After a bit of further investigation, it does not seem that failure to call `trackPageView` is the cause of this issue. Manually, adding a call to `trackPageView` still allowed reproduction of the issue

**Comment by theseyi** [comment]
Adding an image if it helps visualize the issue:
@tsteur @mattab 
![image](https://user-images.githubusercontent.com/3725821/51557685-731d2a00-1e32-11e9-9510-0268606819f8.png)

**Comment by tsteur** [comment]
I had a quick look in the code... while impressions may be only tracked once within a pageview, an interaction may be tracked multiple times from what I see. Basically what you want would be maybe "Unique Impressions" and "Unique interactions"?
See https://github.com/matomo-org/matomo/issues/6272 where I explained behaviour.

Also in the code I'm seeing that an interaction could be tracked without an impression being tracked I think. See https://github.com/matomo-org/matomo/issues/6270

**Comment by theseyi** [comment]
Thanks for taking a look @tsteur . I think a primary issue here is when i navigate back to the page containing content impressions, and `trackAllContentImpressions` is invoked via
```js
_paq.push(['trackAllContentImpressions'])
```
, this new call is not reflected in Piwik. i.e. the impressions count is not incremented.

However, clicking on any content block immediately increments the count for that content block's `interactions`

- Is there any reason why a manual / direct call to `trackAllContentImpressions` will be ignored even after `trackSiteSearch`?
- I would assume the direct call should be respected?

**Comment by tsteur** [comment]
created https://github.com/matomo-org/matomo/pull/14002 re `trackSiteSearch` 👍
