### ISSUE TITLE
Add type "browser notification" to scheduled reports

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#13989]
Adding this to 3.10 but we may want to move this to 3.11. Milestone doesn't exist yet.

We can already send reports via text messages (SMS). It would be awesome if we could alternatively use browser notifications as a different delivery. It would be the same content as text messages though to keep things simple. 

We would maybe not send text messages when never any data tracked.

Not sure if text in notifications is maybe limited? If they are, then it would be great to only get notified about the number of visits overall and link to multi sites if multiple sites are set up, or to the reporting of the only configured site.

**Comment by mattab** [comment]
Won't fix, as it's a bit too complex for the value to users.
