### ISSUE TITLE
Upgrade from 3.7.0 to 3.8.0 broke all sorts of things

### ISSUE THREAD

**Issue by robo2bobo** [matomo-org/matomo#13990]
Wow, somebody really messed it up this time. The upgrade from 3.7.0 to 3.8.0 came up with the following problems:

1) The upgrade procedure produced this error:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbuser.matomo_brute_force_log' doesn't exist
```

2) The upgrade procedure caused the following PHP error

```
Error in Matomo (tracker): Error query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbuser.matomo_tracking_failure' doesn't exist In query: SELECT idsite FROM matomo_tracking_failure WHERE idsite = ? and idfailure = ? Parameters: array (   0 => 1,   1 => 2, )
```

3) The integrity check now reports these two files need to be deleted:

```
File to delete: misc/internal-docs/content-tracking.md
File to delete: .lfsconfig
```

4) Many Settings pages (like the new change admin password) generate this error:

```
Error in Matomo: Could not verify the security token on this form.
```

**Comment by rudyzeinoun** [comment]
By running `./console core:update`, I noticed that the database queries counted as 5 in total, but they are in fact 7, so I saw the queries running beyond 5/5 to 6/5 then 7/5. Maybe this is related, as the database upgrade was the failing step when updating from web.

**Comment by mattab** [comment]
thanks for the report. duplicates #13836
