### ISSUE TITLE
Widget > Visits in Real-Time :: New 3.8.0 Hover URLs are unclear, cluttered and way too long just as this issue's title! pun fully intended :)

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#13991]
Ok,I've made my point
Just see the pictures, it's all there :)

**Matomo 3.7.0: (before 3.8.0 update)**
![piwik-matomo-3 7 0-old-hover-tooltips](https://user-images.githubusercontent.com/5383059/51520681-a6f15300-1e24-11e9-930d-5c8dd904de35.png)

**Matomo 3.8.0 update**
![piwik-matomo-3 8 0-new-hover-tooltips-include-urls](https://user-images.githubusercontent.com/5383059/51520697-b2dd1500-1e24-11e9-89cf-65be716ad2de.png)

**Proposition / Some common sense here**
![piwik-matomo-3 8 x-fix-proposition](https://user-images.githubusercontent.com/5383059/51520707-bbcde680-1e24-11e9-902d-bd57f272ed2d.png)

Thanks!

**Comment by mzcarlos** [comment]
In addition they took a long time to appear (~ 1 sec). In the 3.7.0 they appeared immediately. Using chromium 69.

**Comment by fdellwing** [comment]
@McLive You probably setup your tracking code to group by domain (2nd option in tracking code settings). This way `document.domain` will be added before `document.title` as title for the tracking.

**Comment by fdellwing** [comment]
That is not a thing that will get saved if you leave the site. Take a look at your tracking code that you use.

**Comment by McLive** [comment]
Oh I seee. This is my tracking code:
![image](https://user-images.githubusercontent.com/5620071/51617396-6f6dce00-1f2c-11e9-8a61-18882018de74.png)

So I guess I have to remove the first option?

**Comment by fdellwing** [comment]
I would remove it with >3.8.0 as the domain is now added automatically.

**Comment by McLive** [comment]
Thanks! That works fine
