### ISSUE TITLE
Opt-out iframe builder broken

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#14008]
There are two problems with the iframe builder right now.

~~1. If you choose `em` instead of `px` and enter a float number, this number is not getting added to the iframe code. It only accepts integers.~~

2. If you choose `white` as font color the background color is still transparent (so the iframe seems empty), but the builder shows `black` in the color picker.

**Comment by Findus23** [comment]
For the latter, I can't think of any other solution as to set the color to white by default which feels a bit redundant and makes transparent impossible to select. Maybe an additional "transparent" button has to be added.

**Comment by tsteur** [comment]
We don't support `white` etc right? may be best to just not support it before making things overly complex

**Comment by fdellwing** [comment]
@tsteur I'm not sure what you mean with "We don't support white etc"? You have a color picker there, you can choose any color you want and that includes off course white, too.

**Comment by fdellwing** [comment]
It seems like 1. works, but in another way than I thought. If I enter `1,5` it works as expected.

For 2. a PR will follow soon :)

**Comment by fdellwing** [comment]
I'm still not sure, you are understanding the problem here ;)
