### ISSUE TITLE
Error while sending STMT_CLOSE packet [3.8.1-b1]

### ISSUE THREAD

**Issue by robles-design** [matomo-org/matomo#14012]
Hello,

I'm getting the following error in my php-logs since version 3.8. I've updated to 3.8.1-b1, but the error is still there:
`[PHP Warning:  Error while sending STMT_CLOSE packet. PID=20377 in /www/htdocs/piwik/libs/Zend/Db/Statement/Mysqli.php on line 105`

Best regards
Robert

**Comment by fdellwing** [comment]
Please take a look at your PHP error log and your MySQL error log.

**Comment by robles-design** [comment]
This is my php error log created via .htaccess. It's a shared host I don't have access to the real logs.

**Comment by tsteur** [comment]
I don't think we can do much here. Looks like some DB issue to me. Has this happened before? For how long have you been using Matomo? Did it happen with 3.8.0?

**Comment by robles-design** [comment]
Yes, as I mentioned in my first post I'm getting the error since 3.8. That's why I updated to 3.8.1-b1 yesterday. There are some new errors now (3 times):
`Error in Matomo: Zend_Session is currently marked as read-only.`

There weren't any errors before version 3.8. I noticed the errors yesterday, because there were some Ooops warnings in the front end and I took a look in the logs. After the update to 3.8.1-b1 the Ooops warnings popped up two or three times again. Then I deleted all tmp files in the matomo directory and the Ooops warnings are gone now, but the errors in the php error log are still rising. Last one from 23-Jan-2019 17:40:04, German timezone.

**Comment by diosmosis** [comment]
@tsteur found this comment in another project: https://github.com/walkor/Workerman/issues/357#issuecomment-416863614 seems to suggest the problem occurs because something closes the connection and then php tries to close it itself. Possibly done at the end of a request?

@robles-design might be helpful to contact the web host in this case, though it is strange it would start happening after an update.

**Comment by robles-design** [comment]
Ok, the good news: no new errors in the php error log since yesterday. Last one was `Error in Matomo: Zend_Session is currently marked as read-only`.

The bad news: it all starts again. Maybe it's related with the A/B-testing plugin, because the Oops warnings popped up first in one of the A/B tests, is there again and stays there even after a reload (see screenshot from today). It displays new entries in the overview.
![matomo-ab-test-oops](https://user-images.githubusercontent.com/25033650/51683108-5c6d0380-1fe9-11e9-9d02-d2b378c19713.png)

Then going to the admin page I get this messages: 
`WARNING: /www/htdocs/piwik/core/DataTable/Row.php(623): Warning - Cannot use a scalar value as an array - Matomo 3.8.1-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)`

After a reload the admin messages are gone.

**Comment by robles-design** [comment]
No more errors in the php error log since 23-Jan-2019, but the  A/B-testing plugin doesn't work (see last post). Any ideas?

**Comment by robles-design** [comment]
Update: Since yesterday the A/B-testing plugin is working again, no more Oops warnings, nothing changed. Today I've updated to Matomo 3.8.1 and all works fine. 

Thanks for your support. You can clos this ticket now.

**Comment by tsteur** [comment]
Awesome glad it works now 👍  feel free to contact us directly through shop at innocraft.com if you otherwise experience any trouble re a/b testing.
