### ISSUE TITLE
Update docs regarding session_handler [3.8.0]

### ISSUE THREAD

**Issue by toredash** [matomo-org/matomo#14010]
According to https://matomo.org/faq/how-to/faq_20521/ using Redis for handling sessions are supported. As of 3.8.0 (https://github.com/matomo-org/matomo/commit/332f42c8798685d1a7df425ebfa42b35937b9b5f https://github.com/matomo-org/matomo/commit/3a655d1d6c393f5880f5f3de26ac39e317f15419) this is not **supported** by Matomo, but configurable.

Suggest that the FAQ is updated to reflect this.

AFAIK the FAQ docs isn't on github ?

**Comment by Findus23** [comment]
Hi,
I'm not 100% sure, but I think that you can of course still use Redis. The db session is just the default, not the only option.

**Comment by tsteur** [comment]
>  I just want use the most tested/supported setup Matomo provides.

That would be DB tables and redis wouldn't really give you much of a performance benefit at all. Redis can be still used though. 

I'll update the config
