### ISSUE TITLE
Two-factor authentication after Update to 3.8.0

### ISSUE THREAD

**Issue by scysys** [matomo-org/matomo#14020]
After Update to Version 3.8.0 I get this screen

![bildschirmfoto 2019-01-24 um 16 51 57](https://user-images.githubusercontent.com/1695531/51690133-5d596180-1ff8-11e9-9b65-ae7c99f2013b.png)

I definitely never has setup the Two-factor authentication!

**Comment by fdellwing** [comment]
https://forum.matomo.org/t/post-upgrade-superuser-login/31401
