### ISSUE TITLE
 Too much action data， then page load slow

### ISSUE THREAD

**Issue by Playtigertomorrownight** [matomo-org/matomo#14025]
When I have a lot of data (>60000 records/day) in the matomo_log_link_visit_action table, my Visits in Real-time panel loads very slowly and the memory usage is very large. How can I deal with it?

**Comment by tsteur** [comment]
60K records a day aren't all that many. If this is slow I would recommend you upgrade your server or remove the real time widget from your dashboard.

**Comment by Playtigertomorrownight** [comment]
I got it , thank you for your help
