### ISSUE TITLE
Document the new Ecommerce JavaScript Tracker functions

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14035]
Let's document and update the following pages: 
* https://developer.matomo.org/api-reference/tracking-javascript 
* https://matomo.org/docs/ecommerce-analytics/

for the new method `getEcommerceItems`

**Comment by diosmosis** [comment]
Developer docs PR: https://github.com/matomo-org/developer-documentation/pull/293

**Comment by diosmosis** [comment]
Proposed text for https://matomo.org/docs/ecommerce-analytics/:

3. `getEcommerceItems()` &mdash; This returns the itmes in the cart so you can inspect exactly what will be tracked the next time `trackEcommerceCartUpdate()` or `trackEcommerceOrder()` is called.
