### ISSUE TITLE
Action name stopped respecting slashes while using several categories for action name

### ISSUE THREAD

**Issue by mplabsorg** [matomo-org/matomo#14031]
According to Tracking HTTP API specification

> action_name (recommended) — The title of the action being tracked. It is possible to use slashes / to set one or several categories for this action. For example, Help / Feedback will create the Action Feedback in the category Help.

the setting several categorizes for actions worked well before upgrade to 3.8.  
After automatic upgrade , the categories appears as one line in the reports 

For example
Prior 3.8 upgrade  4 categories INSTALL/TAP/NOK/E_ENGINE_ALREADY_INSTALLED. 
would appear as tree view hierarchy 

Now both forms appearing in a report 
* a tree view hierarchy 
* 4 category in one line . separated by slashes  ( _probably_ new tracking reports ) 

(see attached picture)

![image](https://user-images.githubusercontent.com/21021110/51806240-4462e180-2280-11e9-8ce0-ec7b178aaba1.png)

====
Matomo version: 3.8.0
MySQL version: 5.5.56-MariaDB
PHP version: 7.0.22

**Comment by sgiehl** [comment]
Guess that's caused by #13688 
Setting `action_title_category_delimiter = /` in your config file should fix it
