### ISSUE TITLE
ScheduledReports: CustomDimensions are added multiple times to the list "Statistics included"

### ISSUE THREAD

**Issue by peterbo** [matomo-org/matomo#14039]
ScheduledReports: CustomDimensions are added multiple times to the list "Statistics included" and are not uniquely check/uncheckable. Reproduced on multiple instances (version 3.6.1 and 3.8.1 with the latest version of CustomDimensions available. Both, action- and visitor dimensions are affected by this bug. They're also reported multiple times in the resulting ScheduledReports.

![cd-multi](https://user-images.githubusercontent.com/1018973/51851317-f0113d80-2323-11e9-87d2-777dabc50aac.JPG)

**Comment by tsteur** [comment]
Hi @peterbo  :)

Cheers for reporting it. Released a new version of custom dimensions that should fix it. We fixed it a while ago but looks like we didn't publish a new release.

**Comment by peterbo** [comment]
Hey @tsteur, that was fast, thank you! :)
