### ISSUE TITLE
Matomo shows IP of virtual machine host

### ISSUE THREAD

**Issue by SamuelNitsche** [matomo-org/matomo#14036]
Hey, I have a really strange problem with matomo.

When I track users, every user "has" the ip address of the host which the virtual machine with matomo is running on. I really have no idea what could cause this kind of problem.

I am very confused and appreciate every kind of help.
Thank you!

**Comment by Findus23** [comment]
Hi,
This sounds as if you are running Matomo behind a reverse proxy.

See here for how to configure Matomo in that case:
https://matomo.org/faq/how-to-install/faq_98/

**Comment by sgiehl** [comment]
I guess Matomo is installed behind some kind of proxy. Maybe this helps: https://matomo.org/faq/how-to-install/faq_98/

**Comment by SamuelNitsche** [comment]
I found the issue. Absolutely my bad. I added a new network interface on my host which messed up my iptables and masqueraded all ip addresses.
