### ISSUE TITLE
Matomo is adding my site subdomain to my email

### ISSUE THREAD

**Issue by davidtessier** [matomo-org/matomo#14038]
I have an email address (noreply@whatever.com).
My Matomo installation is set to analytics.whatever.com

When I try to send automated reports, Matomo doesn't use the email address as defined in the settings, it is adding my sub domain and in turn it is failing and I get the error message: 

> An error occurred while sending 'HTML Email Report - 8.today.5.en - lpnxtyZpMNAIdViRHKaBRduonRwcQTDLfi_9X_YO.html' to email@hotmail.com. Error was 'Relaying disallowed as noreply@analytics.whatever.com'

As you can see, in the above error message, the email it is trying to use does is not the right email. It adds the sub domain. In Matomo General Settings -> Email I do not have it set like this. 

How can I change this so that email reports will work from an address that doesn't include the subdomain?

**Comment by fdellwing** [comment]
What does you config says about `noreply_email_address` (and `login_password_recovery_replyto_email_address`)?

**Comment by davidtessier** [comment]
> 
> 
> What does you config says about `noreply_email_address` (and `login_password_recovery_email_address`/`login_password_recovery_replyto_email_address`)?

The config file shows the same as what I see in the web page for Matomo Email Settings; no subdomain (what I would expect).

**Comment by fdellwing** [comment]
> Does it have to be in a specific sequence in the file?

Pretty sure it has to be in the General section?

**Comment by davidtessier** [comment]
> 
> 
> > Does it have to be in a specific sequence in the file?
> 
> Pretty sure it has to be in the General section?

Moving the code to the general section worked. I have reverted the global.ini.php file, and done a test, and emails are sending. 

Thank you to all who helped me sort this out. I really appreciate it!
