### ISSUE TITLE
Missing faq 27245

### ISSUE THREAD

**Issue by Paradinight** [matomo-org/matomo#14044]
Hello,
the https://matomo.org/faq/general/faq_27245 is missing. The link to the site is in the Two-factor authentication (2FA) text (personal setting)

**Comment by sgiehl** [comment]
Thanks for your report. Seems the FAQ wasn't published yet.
ping @tsteur

**Comment by tsteur** [comment]
Cheers for letting us know @Paradinight , it's published now
