### ISSUE TITLE
Invalidate reports for a specific date range

### ISSUE THREAD

**Issue by NanorPiwik** [matomo-org/matomo#14048]
Currently one can invalidate reports thanks to the Invalidate reports plugin for the last month or for a longer period. But for some websites, even a month of data requires a lot of processing. Would it be possible to specify a specific date range?

**Comment by tsteur** [comment]
I'll move it to the invalidate reports plugin as it is already possible through the UI. I reckon it's not too important as users can still do it through the API and CLI already.

**Comment by tsteur** [comment]
@NanorPiwik @Findus23 turns out it is only possible to transfer issues within same organisation. So I will close this issue and created the issue here: https://github.com/innocraft/plugin-InvalidateReports/issues/10
