### ISSUE TITLE
update 404 github links

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#14047]
couple of 404s:
https://developer.matomo.org/guides/theming

![dev matomo_github_theme_404_links_](https://user-images.githubusercontent.com/5383059/51903047-ab38e580-23bb-11e9-96a5-092a8faa9a6b.png)

**Comment by Findus23** [comment]
Hi,
Thanks for reporting.
It would be great if you could open issues here as they don't have anything to do with the Matomo software itself:
https://github.com/matomo-org/developer-documentation

**Comment by dev-101** [comment]
Thanks!
