### ISSUE TITLE
Embed report iframe markup at scrolling=yes

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#14056]
see https://github.com/matomo-org/matomo/issues/10460#issuecomment-458926213

In Widgets listing  page when we generate the iframe HTML that users can copy maybe we could add this attribute to the iframe. To be tested

**Comment by courtneywright** [comment]
I'll do this as my first PR

**Comment by courtneywright** [comment]
@tsteur I changed it, could you have a look please?

**Comment by tsteur** [comment]
Thanks @courtneywright
