### ISSUE TITLE
Visits in the past 365 days from Greenland?

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#14053]
Ok, this is just for fun :)

Few days ago I spotted a visit from [Greenland](https://en.wikipedia.org/wiki/Greenland). Hooray! :)

And then I clicked on Visitors Map widget, which loaded Greenland territory, then counties/regions, cities with each new click... But, the Visitor Map widget is not the one with an issue here.

Visitors > Locations > Segments is.

There's just no way to select Greenland there, or am I wrong? 2-letters country codes in Visit Location filter doesn't contain GL ISO 3166 code. Ok, maybe because it's not technically a country, and there is a Region filter, but can you really decipher those short-codes? I can't. And, I don't see 'GL' in there, either.

Now, this part is gonna hurt, and I don't expect NLP anytime soon in Matomo, but in GA all I had to type in in 'AI' box was '_how many visitors from Greenland were in the past 365 days_' and ... I got the answer.

Any chance we can expect this to be improved a little? 2-letter country codes are great, but why not include full country name next to it? And so on.

Thanks

**Comment by tsteur** [comment]
I haven't tested but `gl` should work? seeing visitors for us re gl

![image](https://user-images.githubusercontent.com/273120/52233823-f2c3f200-2924-11e9-9f9d-94c2a75d675e.png)

In the list of countries, just as with any other country, I think we only show like top 20 or top 50 which is why it might not be shown.

**Comment by dev-101** [comment]
Nope, "GL" in Country filter does not work, I have already tried (and confirmed again just moments ago to be sure), returns 0 results (but should be 4).

**Comment by tsteur** [comment]
It definitely works here. Checked the visitor log...  with `&segment=countryCode%3D%3Dgl`

**Comment by dev-101** [comment]
Nope, appending it in url and creating custom segment on-the-fly still returns no views.

**Comment by dev-101** [comment]
I think I know now why I only have report in the chart, but not in pages. The access logs were deleted as per  archiving configuration, so that's why page views are showing 0.

This could be helpful message in custom reports, if no results were found:

> There is no data for this report. Likely the data has been purged because the regular deletion of old raw data is enabled and the date for this report is more than 30 days old. A super user can change this setting by going to Administration => Privacy.

**Comment by sgiehl** [comment]
@dev-101 FYI:  I've added a new readable segment `countryName` in #13929. This will make it possible to create segments like `countryName==Greenland`
