### ISSUE TITLE
Visitor Map tooltip shows %s

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14054]
Just a quick note as I just noticed it (sorry if it has already been reported before)

The visitor map (e.g. on the dashboard of demo.matomo.org) shows the correct tooltip for countries with visitors but `%s No Visit` else.
![grafik](https://user-images.githubusercontent.com/6266037/51967169-e0524000-246e-11e9-9f87-812e4c8dd723.png)

**Comment by dev-101** [comment]
This is present in 3.7.0 as well.
