### ISSUE TITLE
Avoid double HTML entities / special characters encoding

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#14065]
Hi, if the page's `<title>` (in `<head>` section) contains for e.g. already encoded **&** character:

`&#38;`

or:

`&amp;`

-----------------------------------------------

M will encode it again, resulting in:

`&amp;amp;`

being displayed in the tooltip (but tooltip just copies values from `<img>` element)

-----------------------------------------------

which, again, will look like this in HTML:

`&amp;`

which is wrong.

-----------------------------------------------

It should simply be/look like this:

`&`

because it is already encoded HTML entity.

See screenshots for illustration.

![matomo-html-char-encoding-bug-1](https://user-images.githubusercontent.com/5383059/52137449-dd13ab80-264a-11e9-85ff-74abc956ea63.png)
![matomo-html-char-encoding-bug-2](https://user-images.githubusercontent.com/5383059/52137450-dd13ab80-264a-11e9-8623-f1dfea1849b4.png)

**Comment by tsteur** [comment]
Cheers 👍

**Comment by fdellwing** [comment]
I guess the "fix" here would be to first decode it and then encode it again to make sure everything is fine?

**Comment by johsin18** [comment]
I also experience this bug, and would like to have it fixed.
