### ISSUE TITLE
re-run scheduled report manually for previous months data

### ISSUE THREAD

**Issue by davidtessier** [matomo-org/matomo#14066]
I am wondering how I can re-run a monthly scheduled report, and get the previous month's data? This seems like a bug to me...

I started using Matomo in January, so I have partial data for the month. I've setup a monthly email report, and I setup a cronjob to run it at 10:00 my time (15 o'clock UTC ). 

Since today is the 1st day of January...
I got the automated email report **(good)**
I got it at 10:00am as expected **(good)**
The report showed the data for January (good)
All of this worked as I would expect. 

**Here's what's weird to me...**   
I want to re-run the report. So I log into Matomo, settings, email reports, and I click "send report now". 
The same report gets emailed to me right away, but it's showing data for the month of February. Since we're only 14 hours into February there's not a lot of data yet... I wanted to re-run the report, and I would have expected to see January's data, like I got in the automated email. The same data is presented when I click "download" instead of "send report now". 

How come I am seeing February when I re-run manually, and is there a way to re-send the report and get the previous month's data? I don't see any option for this in the UI. 

![2019-02-01 14_18_59-personal email reports - administration - matomo](https://user-images.githubusercontent.com/1824441/52144523-8dbe8280-262c-11e9-98b3-f19c50ff48ef.png)

**Comment by tsteur** [comment]
When you click on Download, you can change the date in the URL parameter and then you should get the report you want.

**Comment by extractjan** [comment]
Hi,
I read this solution on different forums, but it doesn't work for me. 
I'm using Matomo 3.11.0, and when I change the URL parameter and reload the page, I get an white screen with an error 
"Sie müssen angemeldet sein, um diese Funktion nutzen zu können." 
(in english "You must be logged in to use this feature.")
I am definitely logged in... so what am I missing here?
Any help appreciated..
Thanks

**Comment by tsteur** [comment]
The suggested solution is out of date as the token_auth is no longer in the URL. You need to go to your personal settings, find the token_auth value (32 characters) and append this to the URL like &token_auth=$token
