### ISSUE TITLE
switch back to simple table from insights visualization - how?

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#14071]
I was curious to test insights visualisation in behaviour > pages and when I was presented with couple of drop-down choices, I simply decided to cancel and go back. Except that I can't. Now, I always see this and just cannot switch to simple table view.

![page-visualisation-insights](https://user-images.githubusercontent.com/5383059/52239233-46efb780-28ce-11e9-94bd-87c5d6230eb3.png)

Hovering over bottom left corner only reveals export icon, no switch report visualization options.
Any help with this which does not involve deleting current session?

**Comment by dev-101** [comment]
All right, I don't know why date range created a problem for this (a year mode was active), but when I switched to day mode, drop-down form reappeared and I was able to switch back again.

I will leave this issue open, as this definitely needs improvement in terms of UI, so that users don't get stuck in 'blank' report forever.

**Comment by mattab** [comment]
see also https://github.com/matomo-org/matomo/issues/5815
