### ISSUE TITLE
Return http status 403 on failed login

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#14085]
Would it be possible to return a 403 http status code on the login post request if invalid credentials are used? This way the webserver and other software can capitalize on this information more easily.

**Comment by mattab** [comment]
Thanks for the suggestion :+1: 
 Wondering if there could maybe be side effects on some server configuration, but probably not?

**Comment by mattab** [comment]
Pull request welcome @fdellwing :+1:

**Comment by fdellwing** [comment]
I took a look into it and was not able to fiddle with the return codes. If anyone can hint me a method or example, will look into it further.

**Comment by Findus23** [comment]
Solved in https://github.com/matomo-org/matomo/pull/14708
