### ISSUE TITLE
Idvist not set after migration

### ISSUE THREAD

**Issue by CannyDuck** [matomo-org/matomo#14102]
I migrate Matomo 3.8.1 to an new server. After that I am using the same tracking code. After the migration the visits are tracked in db but not recognized on the browser. In compare to the old log entries in the table link_visit_action the columns idvisit and idaction_url_ref are 0. So that my be the cause of missing trackings in the browser view. You have any ideas what is wrong after the migration?

**Comment by tsteur** [comment]
Hi there, I suggest you ask this question in our forum: https://forum.matomo.org

Maybe provide some more details there eg what you mean by "not recognized on the browser" and explain you did the migration to a new server.
