### ISSUE TITLE
Let any user in Matomo signup to our Matomo newsletter

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14118]
Currently we let Super Users signup to our newsletter during the installation of Matomo.
It looks like this:
https://github.com/matomo-org/matomo/raw/3.x-dev/plugins/Installation/tests/UI/expected-screenshots/Installation_superuser.png

(there are 2 different checkboxes)

In this issue we would let all users sign up to Matomo newsletter from within their profile page in Matomo. 

Also it may be worth thinking if we want to keep the 2 separate newsletters or simplify and only have one newsletter signup? cc @tsteur

**Comment by tsteur** [comment]
One sign up sounds good. Be also good to be able to follow us on Twitter & FB from there
