### ISSUE TITLE
Tracker script piwik.js is missing CORS header

### ISSUE THREAD

**Issue by franky47** [matomo-org/matomo#14117]
From what I can tell, the CORS settings only apply to the API, the tracking script `piwik.js` is not served with the `Access-Control-Allow-Origin` response header.

I would like to use the [`integrity`](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) attribute on the tracker script, to make sure it has not been tampered with, and it requires the resource to be served with CORS headers.

**Comment by mattab** [comment]
Hi @franky47 please check our CORS Faq: https://matomo.org/faq/how-to/faq_18694/

If you have any specific issue with this, please create a new issue with steps to reproduce. Thanks!
