### ISSUE TITLE
Insights No rows match the criteria

### ISSUE THREAD

**Issue by mritzmann** [matomo-org/matomo#14124]
## Problem

The Insights are no longer displayed. Message: `No rows match the criteria`

![screenshot](https://user-images.githubusercontent.com/4533780/53173215-849b5280-35e7-11e9-8c3c-9c6235c8821b.png)

* To be found at `Behaviour` -> `pages` -> Switch Table to `Insights`
* URL: `/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday&updated=4#?idSite=7&period=day&date=2019-02-14&category=General_Actions&subcategory=General_Pages`

## Reproducible

The problem does not occur in the [demo version](https://demo.matomo.org).

## System

* Matomo Version: 3.8.1
* PHP 5.6.40

## Notes

The html alt tag says:

> The following rows have a growth of at least 1% compared to Wed, Feb 13. Changes affecting less than 3 visits were ignored.

The Pages Views are different enough in my case.

---

Maybe the problem is already known?

**Comment by tsteur** [comment]
I tested on various instances and it works fine everywhere. Does it work for you for other day? or when comparing for other periods?

**Comment by mritzmann** [comment]
> Does it work for you for other day?

Does not work for any date.

> or when comparing for other periods?

Tested previous day and same day in the previous week. Unfortunately both do not work.


Today I cloned the installation and disabled all non-core plugins. Problem persists.

**Comment by tsteur** [comment]
I've looked into the code but can't really see any reason why it shouldn't work. Is there any chance you could give us view access and email us credentials at hello at matomo.org ? 

Can you otherwise maybe access your database and see if the SQL query gives you a result for your username?
`select * from matomo_option where option_name like '%viewdata%actions%getpageurls%'` (you may need to adjust the prefix) or maybe try another user?

**Comment by hebnony** [comment]
I have the same problem since 1 to 3 month.
Matomo version: 3.8.1
MySQL version: 5.7.21
PHP version: 5.6.33
Under docker.

**Comment by b3wii** [comment]
Same problem:
Matomo version: 3.9.1
MySQL version: 10.1.37
PHP version: 7.2.15

**Comment by tsteur** [comment]
To investigate the issue, someone would ideally give us access to their Matomo and server (so we can debug and find the issue).

**Comment by moedech** [comment]
We will prepare a copy for you @tsteur and send you the login credentials

**Comment by tsteur** [comment]
Cheers. I've replied.

**Comment by tsteur** [comment]
We can reproduce the issue when selecting "all" in the filter limit
