### ISSUE TITLE
stastics chart is garbled in report

### ISSUE THREAD

**Issue by yhlin00001** [matomo-org/matomo#14128]
Hi, we need to support. Please tell us how to address this issue. (we use traditional chinese [zh-tw])
![garbled](https://user-images.githubusercontent.com/1841976/53225618-9fd39400-36b3-11e9-9a99-c3c4a23c81fe.png)

**Comment by mattab** [comment]
Hi there please try follow instructions here: https://matomo.org/faq/how-to-install/faq_142/
and let us know if it works then?

**Comment by yhlin00001** [comment]
Great! Thanks for your support.
