### ISSUE TITLE
Display useful error message when embedding the whole app as iframe using Widgetize 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14126]
When exporting in an iframe the whole application using the [Widgetize feature](https://matomo.org/docs/embed-matomo-reports/), when users try to export a report's data, they click on "Export this dataset in other formats" which generates JS error "TypeError: dataTable is undefined".

## Steps to reproduce

as reported by a customer:

* for example using this URL: 
`https://demo.matomo.org/index.php?module=Widgetize&action=iframe&moduleToWidgetize=CoreHome&actionToWidgetize=index&idSite=62&period=week&date=yesterday`
* go under a report and click export icon "Export this dataset in other formats"
* Got: JS error  "TypeError: dataTable is undefined" and the popover stays on "Loading Export..."
* Expected to see the popover and choose export options, and successfully export the data.

**Comment by diosmosis** [comment]
@mattab I'm not sure if widgetizing the entire app is supported by Widgetize? should just need to create an iframe to `module=CoreHome&action=index`

**Comment by tsteur** [comment]
This is not a supported feature and we're not really planning to add this @mattab

**Comment by tsteur** [comment]
There are potentially heaps of issues and it can be potentially heaps of work to make it work etc. It be very very appreciated to close this issue as wont fix or keep it open as a feature enhancement for the future in the backlog.

**Comment by mattab** [comment]
Yes correct, we don't want to implement it :+1: 

That said, my suggestion would be: when module=Widgetize & moduleToWidgetize=CoreHome could we output a simple error message that says something like this (or better)

> CoreHome embedding via an iframe is not a supported feature. Instead you can follow these steps:
> 1) in your iframe, embed Matomo directly using `module=CoreHome` (instead of module=Widgetize) and 
> 2) [change the INI setting as per this FAQ to allow iframing Matomo](http://matomo.org/faq/how-to/faq_193/). 


This would help guide users towards the supported way to do things and make clear we don't support it.
