### ISSUE TITLE
unable to install laravel-debugbar plugin 

### ISSUE THREAD

**Issue by MohammadDarwish** [matomo-org/matomo#14138]
when i run this command "composer require barryvdh/laravel-debugbar
"
 

I get the below error

Using version ^3.2 for barryvdh/laravel-debugbar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Deprecation Notice: strpos(): Non-string needles will be interpreted as strings in the future. Use an
explicit chr() call to preserve the current behavior in phar://C:/ProgramData/ComposerSetup/bin/compos
er.phar/src/Composer/Util/RemoteFilesystem.php:230
Deprecation Notice: strpos(): Non-string needles will be interpreted as strings in the future. Use an
explicit chr() call to preserve the current behavior in phar://C:/ProgramData/ComposerSetup/bin/compos
er.phar/src/Composer/Util/RemoteFilesystem.php:230
Deprecation Notice: strpos(): Non-string needles will be interpreted as strings in the future. Use an
explicit chr() call to preserve the current behavior in phar://C:/ProgramData/ComposerSetup/bin/compos
er.phar/src/Composer/Util/RemoteFilesystem.php:230

                                                                                                     
  [Composer\Downloader\TransportException]                                                           
  The "27.0.0.1/index.html" file could not be downloaded: failed to open stream: No such file or di  
  rectory                                                                                            
                                                                                                     

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-s
cripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-plat
form-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

please help me !!!!

**Comment by Findus23** [comment]
Hi,

I don't think this issue has anything to do with the Matomo project. So I'd recommend you to ask the question somewhere else (e.g. stackoverflow)

BTW: Look into your composer settings if you by chance have set a proxy or something like this to `27.0.0.1`.
