### ISSUE TITLE
duplicate orders, when the option "anonymize order numbers" is enabled

### ISSUE THREAD

**Issue by ryrun** [matomo-org/matomo#14130]
Currently the documentaion is saying, when the same orderId will be tracked as completed order, it will automatically discard the order as it is already recorded:
https://matomo.org/docs/ecommerce-analytics/#tracking-ecommerce-orders-items-purchased-required

It seems, this is not working, when you have enabled to anonymize the order number. Its not documented, if this is intended or a bug.

**Comment by tsteur** [comment]
It's not 100% intended, neither really a bug. I guess it's best to just document this behaviour.

**Comment by tsteur** [comment]
Done
