### ISSUE TITLE
Event action counter mismatch between Behavior page and custom report

### ISSUE THREAD

**Issue by labolanimichele** [matomo-org/matomo#14139]
Hello,

we are facing an issue that makes us doubt what data we can trust in Matomo.
It could also be we are interpreting the data wrong - if so, we'd be pleased to know it.

When looking in the behavior page at the counter for Event actions on a specific date (e.g. feb 22) for one specific action is showing the current value of 3
![capture 1](https://user-images.githubusercontent.com/22618797/53407924-97ce6980-39bd-11e9-8fe0-d1438b149fd8.PNG)

However, the custom report aggregates a different value.
We built a report as such:
![capture 2](https://user-images.githubusercontent.com/22618797/53407993-b5033800-39bd-11e9-99be-3d3b7dd1a0ec.PNG)

The result for the date is of 9 events:
![capture](https://user-images.githubusercontent.com/22618797/53408059-e24fe600-39bd-11e9-93d0-7799dab5b06b.PNG)

Anything you suggest we look into?

**Comment by tsteur** [comment]
Not sure if I understand correctly but wouldn't you also need to add to the segment filter the expression `event category = _servicenow_interaction`?

If that doesn't help, could you please email shop at innocraft.com ?
