### ISSUE TITLE
Tooltip should appear on top of other elements

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14150]
As reproduced in Administration > Users > Permissions > Capabilities:

![tooltip](https://user-images.githubusercontent.com/466765/53608764-e5024380-3c28-11e9-95b9-21fbaf39f4f1.png)

-> The tooltip in black should appear on top of the other elements.

**Comment by fdellwing** [comment]
The `z-index` of the default `ui-tooltip` is only 2000, this seems to low. Should be set to like 9999.
