### ISSUE TITLE
[InvalidArgumentException] There are no commands defined in the "tests" namespace 

### ISSUE THREAD

**Issue by Protosac** [matomo-org/matomo#14156]
I reviewed a previous issue #7356 which is similar but I didn't find any insights on how to remedy this for other namespaces. Here's a screenshot of the error:

![matomo-test-error](https://user-images.githubusercontent.com/6880594/53672459-7aa4cf80-3c37-11e9-9cf5-e39ccf85b066.jpg)

Explanation:
- I run `./console development:enable`. - Success
- I run `./console generate:test --testtype unit` - Success
- After entering additional info, it shows that generation was successful
- However, no files were actually generated. 
- So I proceeded to manually add the appropriate files and folders according to the documentation here: https://developer.matomo.org/guides/tests-php
- I run: `./console tests:run MyTest`
- This error ocurred. 
- I run: `./console tests:run plugins/MyPlugin/MyTest.php`
- Error still occurs

Running `./console list` shows the error is indeed valid. The problem is I have no idea why this command isn't there nor how to add it. 

Any insights on this are greatly appreciated!

**Comment by tsteur** [comment]
Make sure development mode is really enabled and the plugin `TestRunner` needs to be enabled as well.

**Comment by Protosac** [comment]
Thanks for your reply. Dev mode is enabled as noted above but there's no plugin named `TestRunner` in the plugins nor in the config.

Before posting this issue I tried searching Matomo marketplace for a test plugin as well. The only thing that pops up is A/B Testing. Tried it again today, same results. 

So where can I find and install the TestRunner?

**Comment by Findus23** [comment]
Just to be sure: You are running the Matomo version from this repository and not the build zip from https://builds.matomo.org/.
Because in the latter many files only needed for tests are removed.

You can check https://developer.matomo.org/guides/getting-started-part-1 for more infos.

**Comment by tsteur** [comment]
It sounds definitely like you installed Matomo from the zip. Be good to install it from GIT and then it'll work 👍
