### ISSUE TITLE
Error in Goals

### ISSUE THREAD

**Issue by ratnesh-kadam** [matomo-org/matomo#14162]
We are getting the error on demo.matomo.org
Error: requested report Goals.getVisitUntilConversion for websiteid = 62 not found in list of available reports.

Steps to reproduce.
1) Goals -> Overview -> Visits to Conversions -> Hover on any visit which has conversions -> Click on Open Row Evolution icon.

**Comment by tsteur** [comment]
@diosmosis when you have some time maybe you can have a look?
