### ISSUE TITLE
How to get token_auth programmatically, e.g. using OAuth 2.0 ?

### ISSUE THREAD

**Issue by saadsarfrazz** [matomo-org/matomo#14163]
Hi,

I am working on "Reporting HTTP API" to export data from matomo.
It is mentioned here
 https://developer.matomo.org/api-reference/reporting-api#authenticate-to-the-api-via-token_auth-parameter 
that token_auth can be generated manually (in user settings) to be used in API reporting.
I wanted to ask if there as any programmatic way to retrieve this token e.g. using OAuth 2.0 may be?
Also what is that age of token_auth.Does it not expire unless user regenerates it?

Regards,

Saad.

**Comment by tsteur** [comment]
You can find more info about APIs here: https://developer.matomo.org/api-reference/reporting-api

Checkout `UsersManager.getTokenAuth` method to get token. There is no oauth and token doesn't expire unless you regenerate.

For further questions please ask in the forums: https://forum.matomo.org

**Comment by Findus23** [comment]
Just for future reference: Matomo 4 allows creating multiple API token per user and you can use `UsersManager.createAppSpecificTokenAuth` to create a new one.
