### ISSUE TITLE
Upgrading via one-click upgrade sometimes does not proceed (stays at the same version)

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14177]
Upgrading via one-click upgrade sometimes does not proceed and Matomo stays at the same version, yet there is no error message. 

This can be often reproduced on the demo.matomo.org

Behaviour: 

* The update box shows an update is available:
![Screenshot from 2019-03-11 16-26-08](https://user-images.githubusercontent.com/466765/54098677-653f5a80-441a-11e9-8cc6-7f7ad04cf016.png)

* Clicking the box, we get to the standard upgrade screen:
![2](https://user-images.githubusercontent.com/466765/54098712-886a0a00-441a-11e9-99b8-503f2bdffc8c.png)

* Clicking "Update automatically" leads to the success screen:
![Screenshot from 2019-03-11 16-27-40](https://user-images.githubusercontent.com/466765/54098726-99b31680-441a-11e9-8d74-c3be69e15276.png)

* Then it shows the same as before the auto upgrade:

![same](https://user-images.githubusercontent.com/466765/54098795-e991dd80-441a-11e9-9eb0-bb964d6c599a.png)

It may be an issue only on demo.matomo.org, not sure?

**Comment by tsteur** [comment]
I would very likely say this is only a demo issue and be tempted to just close it until someone else reports it. Also if it sometimes works you can just do it again. Be good if this can be closed or put in low prio backlog since there are more important issues to tackle :)

**Comment by fdellwing** [comment]
I notice this quite often with our two instances. Doing a hard reload will bring up the database upgrade and afterwards everything is fine.

**Comment by mattab** [comment]
Thank you for the report :+1:  To likely fix the issue, could you upgrade to the latest Matomo version?
see https://matomo.org/docs/update/ 

if you still experience this issue afterwards, please re-open this and post a comment. Thanks!
