### ISSUE TITLE
PIWIK Tracking sites not added on it

### ISSUE THREAD

**Issue by rrswissre** [matomo-org/matomo#14181]
Dear Matomo Support team,

We have an issue with PIWIK tracking sites that are not added on to it.

The site which is added is  https://dna.swissre.com  with site ID 76.

Could you please check the attached screen shots and help us understand how this is being tracked.

![DNA-PROD-ON-PIWIK](https://user-images.githubusercontent.com/47180731/54129007-9bc2a880-440d-11e9-8fa1-bcdc032ff5a9.png)

![DNA-1](https://user-images.githubusercontent.com/47180731/54129021-a8470100-440d-11e9-826a-7848026d6b81.png)

We have checked on the sites and the code is same as what has been generated by PIWIK.

Hence could I request you to look into this ASAP.

Thanks & Regards
Raghu

**Comment by Findus23** [comment]
Hi,

Can you further explain what the problem is? What is not added onto what?
Can you check in the browser's developer tools for errors on the website where Matomo is added.

In addition, this issue tracker is intended for reporting reproducible bugs in Matomo, for more general troubleshooting there is a forum: https://forum.matomo.org/

**Comment by tsteur** [comment]
Hi there, as @Findus23 suggested such questions are best asked in the forum: https://forum.matomo.org

I suggest you ask there. I tried to access https://dna.swissre.com/ but I couldn't. Maybe it's an internal site? It may be tracked eg through JS tracker, [through log analytics](https://matomo.org/log-analytics/), ... it's best you contact maybe also your IT or sysadmin team.

**Comment by rrswissre** [comment]
Dear Lukas,

Sure, let me explain the problem here on this email as well.


  1.  Some time back we added a site on PIWIK with URL as https://dna.swissre.com/ named as DNA (DNA Prod site) with Site ID as 76 and yes this is an internal site.
  2.  However, when the users were pulling reports from PIWIK, they could that PIWIK is tracking DNA Prod along with DNA Train & Dev environment as well.

[cid:image001.jpg@01D4D8B4.5E7BC6B0]

  1.  The code on the DNA Prod is same as the code that was generated on the PIWIK when the site was added.

We are not sure how the other two sites are getting tracked. Hence raise this ticket.

Regards
Raghu

**Comment by rrswissre** [comment]
> Hi there, as @Findus23 suggested such questions are best asked in the forum: https://forum.matomo.org
> I suggest you ask there. I tried to access https://dna.swissre.com/ but I couldn't. Maybe it's an internal site? It may be tracked eg through JS tracker, through log analytics, ... it's best you contact maybe also your IT or sysadmin team.

Hi tsteur,

We worked within our teams as well. The code is same as it was generated by the PIWIK site after the DNA site was added.

Yes DNA is an internal site, you will not able to access it.

Regards
Raghu

**Comment by Findus23** [comment]
Hi @rrswissre,

This is only the bug tracker for bugs in Matomo. If you need further support please either contact the Team for paid enterprise support (https://matomo.org/enterprise-analytics/) or ask a question on the forum (https://forum.matomo.org/) giving more details.

As I don't know anything about your setup, the only thing I can recommend you is this:
>  Can you check in the browser's developer tools for errors on the website where Matomo is added.

**Comment by fdellwing** [comment]
I would guess the error is, that the tracking code is present in prod and dev. This way dev will send the data to Matomo. As far as I am aware of, Matomo currently does nit give a crap about what site it should handle. If it gets requests, it will track them.
