### ISSUE TITLE
Segments for Download reports are partially broken

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#14180]
regression from #14076

In Download urls reports the segment metadata is not always set correctly.
When viewing the report normal all segments for folders have a `^pageUrl=` segment. Same applies for all rows when viewing the report flattened.

See build failure: https://travis-ci.org/matomo-org/matomo/jobs/504647208

ping @diosmosis

**Comment by diosmosis** [comment]
@sgiehl fixed in my `fix-build2` branch. There's one failing test left before it can be merged.
