### ISSUE TITLE
Twig has a security issue in sandbox 

### ISSUE THREAD

**Issue by mikkeschiren** [matomo-org/matomo#14189]
Created https://github.com/matomo-org/matomo/pull/14188

This is about:
https://symfony.com/blog/twig-sandbox-information-disclosure

**Comment by Findus23** [comment]
I'm pretty sure Matomo doesn't use the twig sandbox feature, so this shouldn't matter.

Nevertheless, updating Twig shouldn't hurt.

**Comment by fdellwing** [comment]
Just did a code search, did not find anything related to twig using sandbox.

**Comment by mikkeschiren** [comment]
Matomo core does not, but a plugin can. So an update would not hurt.

**Comment by Findus23** [comment]
That would be highly unlikely as not the sandbox feature but just disallowing `__toString()` is broken, but as said before I'm all for updating twig (as there were also a few bugfix releases in between)
