### ISSUE TITLE
Copy dashboard doesn't work with special characters in the username

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14191]
reported in https://forum.matomo.org/t/copy-dashboard-to-user-not-working-on-usernames-containing-special-characters/32016

1. Create user called `test123_-.@+`

2. give the user view access to all website

3. try to copy the dashboard to this user

The following error appears:

> Cannot copy dashboard to user test123_-.%40%2B, user not found or user does not have access to same site.

Bonus question from the forum:
> Finally, why exactly might copying dashboard layouts fail when a user does not have access to the same site as mentioned in the above error message? Ain’t those layouts in general independent from user rights towards sites? :thinking:

**Comment by sgiehl** [comment]
> Finally, why exactly might copying dashboard layouts fail when a user does not have access to the same site as mentioned in the above error message? Ain’t those layouts in general independent from user rights towards sites? thinking

the message is simply incorrect, as it only checks if the user exists, there is even no site given in the request.
