### ISSUE TITLE
Visitor log shows "0000000005 visits" instead of "5 visits"

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#14194]
When I hover the visitor returning icon it shows some zeros in advance that are not needed.

![image](https://user-images.githubusercontent.com/273120/54240240-6095b600-4582-11e9-8fe7-e32de24d4df9.png)

**Comment by fdellwing** [comment]
Is this a new bug in the beta? Can not reproduce that in local install and demo.

**Comment by tsteur** [comment]
I noticed it while testing https://github.com/matomo-org/matomo/pull/14063 but don't think it's due to that PR.

**Comment by diosmosis** [comment]
I can't reproduce this either, was it locally?

**Comment by tsteur** [comment]
Yes was locally, will close it then.
