### ISSUE TITLE
Changed period in row evolution breaks graph/metric association

### ISSUE THREAD

**Issue by peterbo** [matomo-org/matomo#14208]
Steps to reproduce: 
- Navigate to Visitors->Devices (maybe other reports are affected too) 
- open row evolution of a row in e.g. device type
- change period from (e.g.) week to day
- click through the metrics (association is broken)

Bug is reproducible on the demo.

![row-evolution-graph-selection](https://user-images.githubusercontent.com/1018973/54446345-ff6b0f80-4746-11e9-9ef9-71b5539958ad.JPG)

**Comment by tsteur** [comment]
FYI: Tried to fix it but couldn't fix it within 4 hours. Pushed the changes here but there are a few challenges see comment: https://github.com/matomo-org/matomo/commit/7253a4fdbf2eda90130ba47e119117b07ac8679a

I reckon to fix this, we would actually need to reload the popover with some additional parameters eg which period to select, which metrics to preselect. I reckon fixing this will take another 8 hours as you need to put a lot of "hacks" into various visualisations to make this work. 

A problem is really that it not only remembers which metrics are selected, but it even shows metrics below the graph that aren't available for that period etc.
