### ISSUE TITLE
add new user - will not accept apostrophe in email address

### ISSUE THREAD

**Issue by tackcalb** [matomo-org/matomo#14205]
Trying to add user blah.o'blah@blah.com. Rejected as not valid format. There is an old issue from 2013 where this was reported as fixed at the time, however, this does not currently appear to be the case. Have also tried double quotation marks (this was suggested as an alternative), without success.

**Comment by Findus23** [comment]
Hi, this sounds pretty much like this issue described in #11796 (which hasn't been solved yet)
