### ISSUE TITLE
Need responsive Matomo opt-out iframe please (do not close until it's resolved on my end, thank you)

### ISSUE THREAD

**Issue by CDUCI** [matomo-org/matomo#14218]
Hi. I appreciate quick response on the issue earlier, but please do not close the posting until I have confirmed it's resolved on my end. Thank you. 

Will the plugin you mentioned work with the Matomo Cloud-based version? We did not install Matomo in our web server. 

Looking forward to your response. Thanks again.

**Comment by tsteur** [comment]
@CDUCI I will close this issue and reply in https://github.com/matomo-org/matomo/issues/14209
