### ISSUE TITLE
Multiple archiver processes affect the report mails

### ISSUE THREAD

**Issue by chgarling** [matomo-org/matomo#14217]
Hi there,
we are running some archiver processes in parallel with code like that:

`for ((n=0;n<4;n++)); do (${PHP_BIN} ${ARCHIVE_BIN} ${ARCHIVE_OPTS} >> ${LOG_FILE} 2>&1 &); done`

Now users are telling us, that they got the email report 5 times. This matches the number of parallel archiver jobs. Is there a way to avoid this behaviour?

Installed version of Matomo is 3.8.0 on Debian 8.11 with PHP 5.6.40.

**Comment by tsteur** [comment]
I recommend you add a `sleep 5` or `sleep $n` after launching an archiver which should fix the problem where it possible runs into a race condition. You can generally launch multiple archivers at once, but there should a little gap in between.
