### ISSUE TITLE
Field report in form analytics evolution graph graph gives error

### ISSUE THREAD

**Issue by shachiarkatkar** [matomo-org/matomo#14225]
##Description##

In the online demo of matomo(https://demo.matomo.org/) the row evolution report is not working for Form Analytics > Field reports

##Steps to replicate:##

       1. Go to Forms > Search for "Comment Form"
       2. Open any field report.
       3. Click on Open Row Evolution

![image](https://user-images.githubusercontent.com/2101412/54587501-44908980-4a46-11e9-8514-04820d6bbccb.png)

##Expected Result### 

It should show a graph with metrics

##Actual Result##

It gives the following error:

Error: Requested report FormAnalytics.getFieldSize for Website id=47 not found in the list of available reports.

![image](https://user-images.githubusercontent.com/2101412/54587514-4c502e00-4a46-11e9-9fda-59a5669b706f.png)

Please assist.

Thanks,
Shachi

**Comment by tsteur** [comment]
Thanks for reporting it.

**Comment by tsteur** [comment]
This has been fixed in the plugin directly
