### ISSUE TITLE
Rename "Visitor Log" to "Visits Log" in all user and dev guides and FAQs

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14223]
Now that the feature "Visitor Log" was renamed to "Visits Log" an update of all user guides and dev guides and FAQs to use the updated feature name will help users find their way and not create confusion.

## Done so far

* https://matomo.org/docs/real-time/
* *all others todo*

**Comment by sgiehl** [comment]
I've update:
* https://matomo.org/docs/user-profile/
* https://matomo.org/docs/user-id/
* https://matomo.org/docs/privacy/
* https://matomo.org/faq/how-to/faq_150/
* https://matomo.org/faq/roll-up-reporting/faq_23226/
* https://matomo.org/faq/troubleshooting/faq_58/
* https://matomo.org/faq/how-to/faq_20184/

**Comment by tsteur** [comment]
updated 
* https://matomo.org/privacy/
* https://matomo.org/docs/video-piwiks-analytics-visitors-feature/
* https://developer.matomo.org/guides/visualizing-report-data
* https://developer.matomo.org/api-reference/tracking-api
* https://developer.matomo.org/guides/media-analytics/reference
* https://developer.matomo.org/guides/media-analytics/options
* https://developer.matomo.org/api-reference/Piwik/Plugins/Live/VisitorDetailsAbstract

Let's assume it is done everywhere and replace it in other places when we see it
