### ISSUE TITLE
new v 3.9.0 errors

### ISSUE THREAD

**Issue by romanpan2** [matomo-org/matomo#14237]
Hello.
after auto upgrading to 3.9 in dashboard matomo
`
JSON.parse Error: "SyntaxError: Unexpected end of JSON input" in:

init @ index.php?module=Proxy&action=getCoreJs&cb=cff481c228a6d710970f4318d7abab8a:2774
`

not working:

schedule of last visits,
map of visits,
fonts in Russian are displayed incorrectly. Question marks show

and not working mobile app (iOs)

**Comment by tsteur** [comment]
Could you try to clear the cache eg by executing `./console cache:clear` in your Matomo directory?

**Comment by romanpan2** [comment]
Yes, I did reset the cache.Not help. The problem remained

**Comment by mattab** [comment]
Thank you for the report :+1:  To likely fix the issue, could you upgrade to the latest Matomo version?
see https://matomo.org/docs/update/ 

if you still experience this issue afterwards, please re-open this and post a comment. Thanks!
