### ISSUE TITLE
Create a mobile demo version of Matomo

### ISSUE THREAD

**Issue by NanorPiwik** [matomo-org/matomo#14234]
Currently at http://demo.matomo.org/ only a demo version of a website is shown.
As a result we don't know what Matomo support on mobile or not and how the UI differ from a website.
Wouldn't it be possible to have a demo version of it?

**Comment by fdellwing** [comment]
You mean like https://demo2.matomo.org/?

**Comment by tsteur** [comment]
I think it is meant to have another "website" in there showing tracked data from a Mobile app.

@NanorPiwik the UI for Mobile looks the very same. The features that don't work are still shown etc. They don't differ in any way. Therefore I would close the issue for now. We may reopen this at a later time when it becomes more relevant.
