### ISSUE TITLE
Make theme-color themeable

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14230]
Many people theme their Matomo instance to be more on brand, but when the main navbar color is changed, mobile phones still show the default blue color as it is hard-coded here:

https://github.com/matomo-org/matomo/blob/cb5453316711264b07b89a7077b51404a189aa98/plugins/Morpheus/templates/layout.twig#L25

It would be great if there was a way to modify this value without copying the whole template (which may cause issues after updates)

**Comment by simivar** [comment]
@Findus23 I've created a PR but the only way to do it I came up with is loading whole `ThemeStyles` into `View` object. Maybe you see other option?
