### ISSUE TITLE
Missing properties from Matomo (Piwik) API calls

### ISSUE THREAD

**Issue by dasseya1** [matomo-org/matomo#14235]
We are currently using Matomo to track visitors on several web apps. We are calling the API to get daily data. Sometimes, some properties are missing from the results. Is it a known issue? Will this be addressed soon?

**Comment by tsteur** [comment]
Can you be maybe more specific what is sometimes missing from what results?

**Comment by dasseya1** [comment]
API URL: https://.../index.php?&module=API&method=API.get&format=JSON&idSite=1&period=day&date=previous3&token_auth=...

Result: 
`
{
...,
  "2019-03-18": {
    "nb_uniq_visitors": 11,
    "nb_visits": 29,
    "nb_users": 6,
    "nb_actions": 413,
    "max_actions": 117,
    "bounce_count": 5,
    "sum_visit_length": 31982,
    "nb_visits_returning": 27,
    "nb_actions_returning": 398,
    "nb_uniq_visitors_returning": 11,
    "nb_users_returning": 6,
    "max_actions_returning": 117,
    "bounce_rate_returning": "19%",
    "nb_actions_per_visit_returning": 14.7,
    "avg_time_on_site_returning": 1140,
    "nb_conversions": 0,
    "nb_visits_converted": 0,
    "revenue": 0,
    "conversion_rate": "0%",
    "nb_conversions_new_visit": 0,
    "nb_visits_converted_new_visit": 0,
    "revenue_new_visit": 0,
    "conversion_rate_new_visit": "0%",
    "nb_conversions_returning_visit": 0,
    "nb_visits_converted_returning_visit": 0,
    "revenue_returning_visit": 0,
    "conversion_rate_returning_visit": "0%",
    "nb_pageviews": 255,
    "nb_uniq_pageviews": 145,
    "nb_downloads": 0,
    "nb_uniq_downloads": 0,
    "nb_outlinks": 6,
    "nb_uniq_outlinks": 6,
    "nb_searches": 63,
    "nb_keywords": 15,
    "nb_hits_with_time_generation": 250,
    "avg_time_generation": 0.033,
    "bounce_rate": "17%",
    "nb_actions_per_visit": 14.2,
    "avg_time_on_site": 1103
  }
}`

The issue is that the API call doesn't return all the properties every time. Sometimes, `nb_uniq_visitors`  or `bounce_count` or something else doesn't appear in the result.

Is it a known issue?

**Comment by tsteur** [comment]
`nb_uniq_visitors ` may not be returned eg for month or yearly or ranges. `bounce_count ` not sure. You mean you request the same API method with same information and it's sometimes not returned?

**Comment by dasseya1** [comment]
Is there any way to return the `nb_uniq_visitors` every time the API call is made (e.g. for month or year or ranges)?

**Comment by tsteur** [comment]
yes, does this help? https://matomo.org/faq/how-to/faq_113/

**Comment by dasseya1** [comment]
Is it the only property that must be manually enabled to appear in the API call results?

**Comment by tsteur** [comment]
Yes AFAIK. It should also enable `nb_users` or something.

**Comment by dasseya1** [comment]
Could you provide me a URL (web page) that shows the list of properties that must be enabled before they show in the API call results?

**Comment by tsteur** [comment]
I don't know what you mean? otherwise all properties of a report should show up AFAIK

**Comment by tsteur** [comment]
Let us know if there is anything missing or so.
