### ISSUE TITLE
May want to document the composer dependency in the install docs

### ISSUE THREAD

**Issue by bhartvigsen** [matomo-org/matomo#14245]
Piwik_ShouldPrintBackTraceWithMessage() throws an immediate fatal error and you can't install otherwise. I was able to stick 'return false' into the top of the function, THEN get the message to install composer, and then remove the 'return false' and proceed as normal.

**Comment by Findus23** [comment]
Hi,
Matomo doesn't depend on composer in any way if you use the files from https://matomo.org/download

And if you want to run Matomo from git to develop something locally, check out this guide:
https://developer.matomo.org/guides/getting-started-part-1

**Comment by bhartvigsen** [comment]
Okay that's fine, but again you might want to adjust the docs to reflect that. I'm not asking you to change the process or code, just update your docs to reflect this stuff.
