### ISSUE TITLE
HeartBeatTimer / visit length stopped on page (not website) by firing event

### ISSUE THREAD

**Issue by crnm21** [matomo-org/matomo#14243]
By my observations the HeartBeatTimer stops updating the visit length for a webpage if an event is tracked but continues to update the visit length for the overall visit (and by that, the website).

Minimum setup to reproduce this:

Load a js tracker with heartbeattimer option for a page.
Fire event for this page by js event tracking.
Wait 30 seconds with active tab.

Result:
Event is tracked.
Visit length for the page is 0 seconds.
Visit length for website/session is 30 seconds.

Expected result:
Event is tracked.
Visit length for the page is 30 seconds.
Visit length for website/session is 30 seconds.

Refiring the HeartBeatTimer after firing the event does not help (I tried this already).

**Comment by tsteur** [comment]
That's expected behaviour at the moment (not saying it's the best). See eg https://github.com/matomo-org/matomo/issues/9539  and https://github.com/matomo-org/matomo/issues/9540
