### ISSUE TITLE
Matomo dashboard does not show statistics which are more that 10 years old!

### ISSUE THREAD

**Issue by glatzenarsch** [matomo-org/matomo#14255]
Hello

I am using Matomo over 3 years now. My project is to import very large amount of logs over 15years.
Problem is that when i imported logs nad archive them with:
/usr/bin/php /usr/share/matomo/console core:archive --force-idsites=42 --force-date-range=2008-01-01,2009-01-01 --url=…

dashboard doesnt show them. Is there some limit because everything from 2009-2019 shows fantastic.

32 users
21 segments
49 websites
45 activated plugins
Matomo version: 3.5.1
MySQL version: 10.1.37-MariaDB-0+deb9u1
PHP version: 7.0.33-0+deb9u2

Thank you very much.

**Comment by tsteur** [comment]
I do remember seeing some limits around 2008 or so somewhere in the code but can't find the right timestamp right now.

Maybe @mattab  remembers?

Can you otherwise maybe check in the database in the `matomo_log_visit` table and `visit_last_action_time` column if there are entries for before 2009?

**Comment by mattab** [comment]
AFAIK there shouldn't be a limit, except for data before when the first website came online - Tue, 06 Aug 1991 00:00:00 GMT. 
see error triggered in https://github.com/matomo-org/matomo/blob/2ec7485470701ef5f11521d6bbe62d583e25cddf/core/Date.php#L154-L162

But this was 28 years ago

**Comment by tsteur** [comment]
I just remembered this was fixed in Matomo 3.9. I saw this morning the limit in the tracker is set to 20 years so figured that can't be it. But just now randomly remembered we only increased it from 10 to 20 years a month ago. So if you update to the latest version and try again then it should work.

**Comment by glatzenarsch** [comment]
I do imported one month from 2008 year:

Logs import summary
-------------------

    341972 requests imported successfully
    542 requests were downloads
    2316284 requests ignored:
        23695 HTTP errors
        30083 HTTP redirects
        0 invalid log lines
        0 filtered log lines
        0 requests did not match any known site
        0 requests did not match any --hostname
        669 requests done by bots, search engines...
        2261837 requests to static resources (css, js, images, ico, ttf...)
        0 requests to file downloads did not match any --download-extensions

Website import summary
----------------------

    341972 requests imported to 1 sites
        1 sites already existed
        0 sites were created:

    0 distinct hostnames did not match any existing site:


and run core:archive --force-all-websites --force-all-periods=315576000 --force-date-last-n=1000 --url='https://matomo.srce.hr/'

and 

core:archive --url="https://matomo.srce.hr/"  instead.
That do nothing...

MariaDB [matomo]> select visit_last_action_time from piwik_log_visit where visit_last_action_time like '2008%';
Empty set (36.10 sec)

this query does show no results.. i dont understand.

thank you.

**Comment by tsteur** [comment]
See https://github.com/matomo-org/matomo/issues/14255#issuecomment-476070706 you need to update to the latest version.

**Comment by glatzenarsch** [comment]
thank you!
