### ISSUE TITLE
New version notification email contains URL not linked in Thunderbird

### ISSUE THREAD

**Issue by agilare** [matomo-org/matomo#14256]
Hello,

The (HTML) body of the email contains URL that I need to copy and paste in my browser's URL field :

Extract (in french, here GitHub auto-links URLs) : 

> Bonjour,
> 
> Il y a une nouvelle mise à jour de Matomo disponible
> 
> Vous pouvez mettre à jour vers la version 3.9.1 automatiquement ou télécharger l'archive et l'installer manuellement :
> https://piwik.energie-environnement.ch/index.php?module=CoreUpdater&action=newVersionAvailable
> 
> Voir les changements pour cette version :
> https://matomo.org/changelog/matomo-3-9-1/ 

`<a>` have they been forgotten ?

**Comment by mattab** [comment]
Hi @agilare - the link should be there in the email, see the code at https://github.com/matomo-org/matomo/blob/f856128c5a4969429ed2ba035d48bb451b2e0340/plugins/CoreUpdater/templates/_updateCommunicationEmail.twig#L13

Please reopen if you still have the issue?

**Comment by agilare** [comment]
It's almost right, it just remains one URL not linked, the one in `<p>{{ 'CoreUpdater_ReceiveEmailBecauseIsSuperUser'|translate(host) }}</p>`
