### ISSUE TITLE
Changing session name with const PIWIK_SESSION_NAME not possible

### ISSUE THREAD

**Issue by shenziro** [matomo-org/matomo#14254]
According to https://matomo.org/docs/include-piwik-in-your-project/#bootstrap-php-execute-custom-code-before-matomo-runs the session name can be configured by setting the constant "PIWIK_SESSION_NAME".

This is not (longer?) possible. Tested with 3.9 and 3.9.1.

It seems that the session name is hardcoded in core/Session.php. I found no variable or constant to change it without fiddling around with the Session.php file and loosing my changes on every update.

**Comment by simivar** [comment]
It was removed back in 2014 by @mattab in 3ce2344f57fe91bf9f5b824d33129538540941fc. 

@mattab could you please provide some context why it was removed and if it can/should be restored?

**Comment by mattab** [comment]
It is a bug I introduced I believe. @shenziro @simivar please feel free to open a PR to fix this issue again and we will merge it (since it is a documented feature). Thanks :+1:
