### ISSUE TITLE
Row Evolution in Social Networks broken

### ISSUE THREAD

**Issue by campino2k** [matomo-org/matomo#14264]
Report: Social Network by Month -> Click Row Evolution, nothing happens.

Open Devtools, retry, find a failed XHR containing following message:

```
Call to undefined method Piwik\DataTable\Map::getRows() in /[_$_my_piwik_path_]/plugins/Referrers/API.php line 625   
```

**Comment by sgiehl** [comment]
Thanks for the report. I'm able to reproduce that when the report is flattened.

**Comment by campino2k** [comment]
> report is flattened.

That was something I did not think of, thanks for looking into that.
