### ISSUE TITLE
Suggestion: Suggest GPS geolocation

### ISSUE THREAD

**Issue by AntoineWtrnd** [matomo-org/matomo#14269]
Hello guys, 

**This is a suggestion, since i'm not contributor, i didn't "Pull request" so if this is not the right place, just remove it**

I just enabled GeoIP 2 (PHP) and it work great on a Wi-Fi network.

But here in Canada, Mobile ISP (LTE network and mobile plan and all this...) is not giving IP based on user city (probably same thing in USA), so when we detect IP on a LTE or 3G network in North America, informations is all false. City is not the right, it's giving me the city 2h away from me now, using LTE network.

So, that why i suggest that user could use GPS geolocation (which is now a part of HTML5, so compatible in all browser (which have GPS)) 

Like, only access this on LTE network give me all the right informations: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation

I hope this feature will appear in new version.

PS: IP detection for city is 50% functionnal now in 2019 since alllot of people use his phone, so on LTE network. 

PS2: Clearly, user need to accept his geolocation with that, but probably better to have less REAL RESULTS than alot of false results...

**Comment by fdellwing** [comment]
This could be a plugin, but will mostlikely never be added into core because the user get's promted for location access and this is not likely to be good for a lot of websites.

**Comment by Findus23** [comment]
Hi,

Honestly I am pretty sure no one would accept to share ones exact location with a website (I definitly wouldn't and would wonder about why the website would want to have my personal data).

Unlike GeoIP it is hard to prove that you are only storing anonymized rough data.

Nevertheless this could probably be solved as a plugin.

**Comment by melvin881** [comment]
> 
> 
> This could be a plugin, but will mostlikely never be added into core because the user get's promted for location access and this is not likely to be good for a lot of websites.

You're right with the prompt, but device on LTE it all false, i mean, what the point to use IP detection ? Every ISP can provide any IP from his country anytime. Probably not legal, but the city detection on mobile phone is a real mess, and probably because the prompt thing, it will stay a real mess until someone find a tricks to make it work perfectly without prompt.

**Comment by melvin881** [comment]
> 
> 
> Hi,
> 
> Honestly I am pretty sure no one would accept to share ones exact location with a website (I definitly wouldn't and would wonder about why the website would want to have my personal data).
> 
> Unlike GeoIP it is hard to prove that you are only storing anonymized rough data.
> 
> Nevertheless this could probably be solved as a plugin.

I use Google Autosuggestion Input, and user have to accept it (or not) to get the closest street of his GPS, to find his street. And 80% accept it. So since the first was accepted, i could be able to geolocate everybody. There some tricks that you need to do with metrics. Everybody hate to be tracked.

**Comment by fdellwing** [comment]
I'm not quite sure about this, but I do think that you would need to proxy the `matomo.js` for this to work with the acceptance you already got, because this should be domain specific.

**Comment by melvin881** [comment]
HTML is part of browser, not server itself :)

**Comment by mattab** [comment]
Thanks for the suggestion! 
We won't implement this ourselves, but it could be done as a 3rd party custom plugin. 
Will now close this issue as won't fix.
