### ISSUE TITLE
CustomReport plugin bug: tracker API request in the future in reports

### ISSUE THREAD

**Issue by toredash** [matomo-org/matomo#14279]
Hi,

We have an issue with the Premium plugin CustomReport. It seems each day there are tracking data in the future. It is always for the hour 23. This has been reported before in the forums: https://forum.matomo.org/t/visits-per-server-time-shows-11-unique-visits-for-today-at-11pm/31104/3

We see this every day.

The CustomReport we have is as such:
![image](https://user-images.githubusercontent.com/312038/55180298-97c2b480-5189-11e9-94a4-e8821b134454.png)

A current screenshot of the Widget as of 17:45 UTC, today as this issue is filed:
![image](https://user-images.githubusercontent.com/312038/55180382-ca6cad00-5189-11e9-8f24-3b4eab6dfd1d.png)
Notice that it is sorted by the hour, and there is a lot of unq. visitors already for hour 23, and that should not be possible.

The query for this widget is:
`index.php?date=2019-03-28&module=CustomReports&action=getCustomReport&idCustomReport=6&widget=1&idSite=8&period=day`

We run matomo in multiple containers, and set TZ values as such:
```
TZ=${TZ:-UTC}
ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime
echo ${TZ} > /etc/timezone
```

Our docker images is based on nginx:stable-alpine.

Running matomo 3.8.1

What else can I provide to aid on this issue ? thanks

**Comment by tsteur** [comment]
Hi there, I don't think it's related to the premium feature as the regular Matomo feature seems to report this as well according to the forum post. 

I don't know what the timezone of your website is. Is there a chance you could check if there are maybe visits for the UTC time in the DB? Like this:

```sql
select * from piwik_log_visit where visit_last_action_time >='2019-04-08 23:00:00' and visit_last_action_time <= '2019-04-08 23:59:59' LIMIT 15;
```

You maybe need to adjust `piwik_log_visit` table name, and you very likely need to adjust the hour of the day as the DB stores it in UTC.

**Comment by toredash** [comment]
Hi,

Thanks for the feedback @tsteur, your correct. It was a misconfigured website which had a different timezone set than UTC. The SQL query yielded nothing, so our fault :)

Thanks for the help, I'll close the issue
