### ISSUE TITLE
Re-enabling Google Authenticator plugin causes non-obvious error

### ISSUE THREAD

**Issue by STRML** [matomo-org/matomo#14276]
Posting this as much for reference (hello if you come here from Google) and to bring up a bad user experience.

In Matomo >= 3.8.0, if you don't read the release notes carefully, you might notice your [Google Authenticator plugin](https://github.com/sgiehl/piwik-plugin-GoogleAuthenticator) was disabled. Okay, that's no problem, re-enable it. Everything looks fine on the admin panel, but tracking completely breaks!

The error is not obvious:

```
[Tue Mar 26 23:19:09.359669 2019] [proxy_fcgi:error] [pid 21220] [client x.x.x.x:30431] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Piwik\\Tracker\\Db\\Pdo\\Mysql::getConnection() in /srv/www/public_html/core/Session/SaveHandler/DbTable.php:59
Stack trace:
#0 [internal function]: Piwik\\Session\\SaveHandler\\DbTable->open('/var/lib/php/se...', 'MATOMO_SESSID')
#1 /srv/www/public_html/libs/Zend/Session.php(469): session_start()
#2 /srv/www/public_html/core/Session.php(133): Zend_Session::start()
#3 /srv/www/public_html/plugins/GoogleAuthenticator/Auth.php(111): Piwik\\Session::start()
#4 /srv/www/public_html/core/Tracker/Request.php(201): Piwik\\Plugins\\GoogleAuthenticator\\Auth->authenticate()
#5 /srv/www/public_html/core/Tracker/Request.php(168): Piwik\\Tracker\\Request::authenticateSuperUserOrAdminOrWrite('de12bbfdaf2c970...', 2)
#6 /srv/www/public_html/core/Tracker/Request.php(131): Piwik\\Tracker\\Request->authenticateTrackingApi('de12bbfdaf2c970...')
#7 /srv/www/...
'
```

I am unsure why calling `Piwik\\Session::start()` for tracking creates this error, and it led me down a rabbit hole of debugging our db connection before I realized the plugin connection.

Simply disabling the plugin fixed the issue.

It should probably not be possible to enable it on newer versions to prevent this.

**Comment by tsteur** [comment]
Thanks for letting us know.
AFAIK the latest version of GoogleAuthenticator has defined to not be compatible with 3.8 version and as such it shouldn't be possible to activate it (https://github.com/sgiehl/piwik-plugin-GoogleAuthenticator/blob/master/plugin.json#L10) . Did you maybe activate it again through the config file? In this case it shouldn't have been loaded AFAIK. 
maybe you didn't have the latest version of Google Authenticator?

**Comment by STRML** [comment]
It's possible that I walked through a small hole in the logic - it is likely I activated an old version that didn't have the version limit. 

Regardless, I don't expect a fix, but I hope this will help anyone else who runs across it.
