### ISSUE TITLE
Review opened Pull requests on other repositories

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14275]
We haven't gone over all our PRs for some time, so the goal of this issue is to review each PR assigned to `Current sprint` across all our repos. List is available at: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+org%3Amatomo-org+org%3Ainnocraft+milestone%3A%22Current+sprint%22+

This follows up https://github.com/matomo-org/matomo/issues/14274

**Comment by Findus23** [comment]
Bonus task: Assign the `Current sprint` milestone to new PRs:
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+org%3Amatomo-org+org%3Ainnocraft+-milestone%3A%22Current+sprint%22+-repo%3Amatomo-org%2Fmatomo+

**Comment by Findus23** [comment]
Maybe the new Github org-wide project view could be used to keep an overview over new PRs in all smaller repos:
https://github.com/orgs/matomo-org/projects
