### ISSUE TITLE
Most recent packagist version is `3.9.0-b2`

### ISSUE THREAD

**Issue by creativecoder** [matomo-org/matomo#14280]
The most recent version of Matomo that can be installed through composer (via [packagist](https://packagist.org/packages/piwik/piwik)) is `3.9.0-b2`, while the [most recent release version](https://github.com/matomo-org/matomo/releases) is `3.9.1`.

**Comment by sgiehl** [comment]
Maybe we need to (re)add the packagist webhook. 
@tsteur @mattab could you have a look, I don't have enough rights to check the settings

**Comment by mattab** [comment]
Thanks for the report, it may be fixed now?

**Comment by creativecoder** [comment]
> ... it may be fixed now?

Yes, I think so. Packagist page is now showing `3.9.1`. Thanks!
