### ISSUE TITLE
Missing debian package for 3.9.1

### ISSUE THREAD

**Issue by elukey** [matomo-org/matomo#14286]
Hi!

I noticed that the last release is 3.9.1 but in debian.piwik.org I can only find 3.8.1. Would it be possible to get the latest .deb in the repo?

Thanks in advance!

**Comment by Findus23** [comment]
See https://github.com/matomo-org/matomo-package/issues/88 for when @aureq publishes updates to the debian package

**Comment by elukey** [comment]
Thank you! Wasn't aware of it.
