### ISSUE TITLE
E-Mail reports with graphs not working when selecting german as language

### ISSUE THREAD

**Issue by Swift42** [matomo-org/matomo#14285]
Hi there,

the system check reports all green and I have updated to the latest version (3.9.1).
But the problem persists:
Every time I create a report which includes a graph, the email is not sent, but only when I selected "german" on my profile. 
No error is reported.

When I disable the graphs via "Display tables only (no graphs)" OR selecting English as language, all is working fine.

**Comment by fdellwing** [comment]
Just tried it and was not able to reproduce the error.

**Comment by mattab** [comment]
@Swift42 are you still able to reproduce this with the latest Matomo version?

**Comment by Findus23** [comment]
@Swift42, if you or someone else can reproduce this issue with the latest Matomo version, please reopen the issue.
