### ISSUE TITLE
Matomo date selection for March shows only 30 days 

### ISSUE THREAD

**Issue by TerryLipford** [matomo-org/matomo#14297]
The drop-down calendar does not show 31 days for March, only 30.

**Comment by fdellwing** [comment]
Works for me.

![Screenshot_20190401_091352](https://user-images.githubusercontent.com/22813377/55309569-82d27380-545e-11e9-9c3d-75795235627f.png)

**Comment by mattab** [comment]
Works here, please post a screenshot if you can still see this issue with latest Matomo?
