### ISSUE TITLE
What's the meaning of 'visit_first_action_time' and 'visitor_localtime'?

### ISSUE THREAD

**Issue by linxiaolicnic** [matomo-org/matomo#14305]
What's the meaning of 'visit_first_action_time' and 'visitor_localtime'? 
What's their difference?

**Comment by tsteur** [comment]
See https://developer.matomo.org/guides/persistence-and-the-mysql-backend

**Comment by tsteur** [comment]
For further questions please ask in our forums https://forum.matomo.org/c/plugins-platform

**Comment by linxiaolicnic** [comment]
Thanks a lot!
But what's the relationship between 'visit_first_action_time' and 'visitor_localtime'?
It seems visitor_localtime is ahead 8 hours of visit_first_action_time?

**Comment by linxiaolicnic** [comment]
The 'visit_first_action_time' looks fine on the matomo web, but in database this time value seems is 8 hours ahead of  real visit_first action_time.
such as :
on the matomo web: Mar 5, 2019 14:07:58
but in matomo database, in table matomo_log_visit I got this record is:
select idvisit, visitor_localtime, visit_first_action_time, visit_last_action_time from matomo_log_visit;
|   24535 | 14:09:23          | 2019-03-05 06:07:58     | 2019-03-05 06:08:27    |

It just 8 housr ahead of real visit_first_action_time.

**Comment by tsteur** [comment]
`visit_first_action_time` is UTC, `visitor_localtime ` is local time depending on users' timezone

**Comment by linxiaolicnic** [comment]
Thank you the response!
I still can not understand well what's the relationship between 'visitor_localtime' and  'visit_first_action_time&& visit_last_action_time', it seems visitor_localtime is several 
minutes later after visit_last_action_time. Is there some relationship?

**Comment by tsteur** [comment]
there is no relationship

**Comment by linxiaolicnic** [comment]
Why need visitor_localtime?

**Comment by tsteur** [comment]
the local user time report uses it

**Comment by linxiaolicnic** [comment]
Does it stand for just visitor's local time or stands for one visit time base of visitor's local time zone?

**Comment by tsteur** [comment]
`visitor's local time ` not in the visitors local time zone
