### ISSUE TITLE
date range from xx.03. to 31.03. returns wrong visit results

### ISSUE THREAD

**Issue by allesmeins89** [matomo-org/matomo#14301]
The 31st of march seems to be buggy then I use date range filter. It looks like the day has a negative value. This is only the case if the _from_ is a date of march and the _to_ is exactly 31.03. (so 28.02 - 31.03. looks good).
The result values are from _Visitor Map_ and _Visitors Overview_.

customer 1:
01.03. - 30.03. -> 8,904 visits
01.03. - 31.03. -> 5,680 visits
28.02. - 31.03. -> 9,521 visits

customer 2:
01.03. - 30.03. -> 39,171 visits
01.03. - 31.03. -> 30,105 visits
28.02. - 31.03. -> 48,457 visits

Maybe it's an issue with the switch from winter time to summer time. On 31.03. at 3:00 am the clock was set to 2:00 am.

**Comment by allesmeins89** [comment]
One more example. For the date range of 25.03. to 31.03. is the result 0, but from 26.03. to 31.03. it is 8,500.

**Comment by sgiehl** [comment]
does that only happen when choosing a range? Or is the number also incorrect if you select a week/month including the 31.03.?

**Comment by allesmeins89** [comment]
Then I select the week of 31.03. or the month march anything looks fine.
date range: 25.03. - 31.03. -> 0 visits
week (from 25.03. to 31.03.) -> 10,301 visits

date range: 01.03. - 31.03. -> 30,105 visits
month (march) -> 46,953 visits

**Comment by allesmeins89** [comment]
I got a mail from that customer. He wrote that the sum of the single days (18., 19., 20., 21., 22., 23. and 24.03.) is 9,996. Then he use the range filter the result of these days is 3,528.
So it's not the 31.03. It is a general date range issue.

**Comment by tsteur** [comment]
Could you try to invalidate the reports and reprocess them? see eg https://matomo.org/faq/how-to/faq_155/ curious if this fixes the issue.

**Comment by allesmeins89** [comment]
Actually we move our matomo server into our new infrastructure. Then I will try it.

**Comment by mattab** [comment]
@allesmeins89 could you please try again if you still experience this issue?

It would be great to hear confirmation if the issue is still active for you. (fyi there is another similar - but different - issue at https://github.com/matomo-org/matomo/issues/15363

This one may also be a duplicate of https://github.com/matomo-org/matomo/issues/14123

**Comment by allesmeins89** [comment]
Looks like it will work.
