### ISSUE TITLE
the location is logged correctly, but it doesn't light up in the map

### ISSUE THREAD

**Issue by ibro0** [matomo-org/matomo#14300]
As the title stated, i can see that the region is logging Ar Riyad visits correctly in the Region column. The issue is that it doesn't appear "light up" in the map.
I have attached a screenshot.
![2019-04-01 09_06_03-Window](https://user-images.githubusercontent.com/16525392/55306724-d1cbd900-545d-11e9-96d4-698382147a51.png)

Keep in mind that i'm using "IntranetGeoIP" plugin because all of my clients are from local ip addresses.
Matomo 3.9.1 and i had this issue in the previous versions as well.

**Comment by Findus23** [comment]
I feel like this is a similar issue as #13691 (country/region code names changed from FIPS to ISO code and the maps haven't been updated yet.)
This should therefore be fixed one day with #11929.

**Comment by tsteur** [comment]
@ibro0 I suggest you create an issue in https://github.com/ThaDafinser/Piwik-IntranetGeoIP/issues otherwise as the plugin might not use the same region codes. Or it is related to #13691
