### ISSUE TITLE
New cli command to send test-mail to admin

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14302]
See also #14455 for a description of this proposed feature.

Many bugs similar to #11534, #12634 (e-mail reports work when sent automatically, but not when sent regularily) have been reported in the last months and my current theory is that this is caused by servers where php mail is only set up correctly for the webserver, but broken in the php.ini read by php-cli.

One way to help debugging this (that would also be useful in other cases) would be a new `console` command that would send a testmail (or if it is easy a report selected by id) to the admin (or another address).

While I am not 100% sure if this will fix #11534 and co. it might be usefull for other people who want to make sure they have set up their Matomo instance correctly. (And getting e-mails to work is often one of the most complex parts as it totally depends on the server environment)

**Comment by mattab** [comment]
see https://github.com/matomo-org/matomo/issues/14455#issue-445266467 for suggested email subject and content

**Comment by mattab** [comment]
Documented in: [ Emails from Matomo are not being sent, how do I troubleshoot and solve the issue?](https://matomo.org/faq/troubleshooting/faq_34856/)
