### ISSUE TITLE
PR #14051 breaks template override functionality in 3.9.1

### ISSUE THREAD

**Issue by ddrjm** [matomo-org/matomo#14307]
Before upgrading I had a couple of template overrides inside a custom theme as stated here:
https://developer.matomo.org/guides/theming#twig-the-template-engine

After the 3.9.1 upgrade, the templates are no longer being loaded.
I have manually reverted this section in my installation 
https://github.com/matomo-org/matomo/pull/14051/files#diff-55e7eb22dafce9c6bf9d3fc98022f2ebL547
and the overrides started working again.

After a few `var_dumps` I found out that the new code just loops across all folders and **doesn't consider the theme folder** to search there.

Aside from the custom theme generated by the console that only overrides colors and a adds a couple of static html to some visualization templates, the installation is clean.

**Comment by tsteur** [comment]
Does your plugin have a `plugin.json` file?

**Comment by ddrjm** [comment]
> Does your plugin have a `plugin.json` file?

Yes. It is a theme generated by the console.

**Comment by tsteur** [comment]
Any chance you can point us to the GitHub repo or send the code to hello at matomo.org ? we can't reproduce the issue.

**Comment by ddrjm** [comment]
@tsteur Sent the theme files via email.

**Comment by tsteur** [comment]
Thanks a lot! We were able to reproduce it and fixed it in https://github.com/matomo-org/matomo/pull/14337
