### ISSUE TITLE
Master Behind Release Tag

### ISSUE THREAD

**Issue by claytondaley** [matomo-org/matomo#14306]
I have an instance of Matomo that I update using `git`.  I pulled master today only to be notified (in the UI) that I don't have the latest version (3.8.0 vs 3.9.1).  I came here and confirmed that master is behind the current release tag.

Is this intentional?  If so, why?

**Comment by sgiehl** [comment]
ping @mattab

**Comment by tsteur** [comment]
shouldn't you check out 3.x-dev?

**Comment by claytondaley** [comment]
I'm not developing.  I'm pulling to a production machine.

**Comment by tsteur** [comment]
Yes the same, I mean you would need to pull 3.x-dev and not master?

**Comment by Findus23** [comment]
@tsteur Normally the `master` branch is up to date with the stable release, but it seems like there is no pr like https://github.com/matomo-org/matomo/pull/13996 for 3.9.0

**Comment by claytondaley** [comment]
@tsteur I'm not exactly sure how you manage PRs here, but `dev` is usually treated as an unstable branch only appropriate for development machines.  For example, there's no guarantee that upgrade scrips are present for the changes merged from PRs.

**Comment by tsteur** [comment]
@Findus23 totally forgot we're still doing this. I suppose we need to stop possibly with Matomo 4. Think we discussed a year ago or so. Since it's not recommended / less secure etc. 

If someone wants to still use git, they can check out specific release versions.

**Comment by claytondaley** [comment]
I don't think that's the right advice, but you certainly can certainly deprecate `master` in this repo (e.g. strand it at 3x) and tell users that they need to merge the appropriate tags into their own, local `release` branch.

I'm sure I used a git repo to merge in a fix/PR I had submitted but had not yet been released.  I'd argue that it's important to have that option even if you don't maintain a production branch in the upstream repo.

**Comment by claytondaley** [comment]
FWIW our release scripts will refuse to run if we haven't checked out `master` and we use branch permissions (on bitbucket) to (1) limit who can commit to `master` and (2) prohibit rewriting of `master`.  You can "roll back" a change by committing the prior version, but it provides a clear audit trail.  We go to the trouble because we're a Healthcare IT company that needs the audit trail, but it's a nice pattern.

Obviously, you should run your business as you see fit, but that pattern is designed to ensure that `git pull` on `master` returns the current stable version of the software.

**Comment by mattab** [comment]
I try to keep master up to date with releases but sometimes forget. So it's not safe to rely on `master` branch. please instead use the Git tag named: https://builds.matomo.org/LATEST
