### ISSUE TITLE
Custom Reports - Improve metrics selection for events, adding "Events Count"

### ISSUE THREAD

**Issue by labolanimichele** [matomo-org/matomo#14312]
Currently users can go to the behavior page to see the counter for at the counter for Event actions and event categories. For example, the one highlighted below shows the value 3 for the _service-now-case-created_ event action.

![image](https://user-images.githubusercontent.com/22618797/55473168-3f1e6c00-560e-11e9-9669-541d03dfe15c.png)

However, when building a Custom Report based on events, there is no metric allowing to insert this value on a report. None of the entries indicated below is in fact matching with the one of the previous screenshot.

![image](https://user-images.githubusercontent.com/22618797/55473286-9c1a2200-560e-11e9-888f-dae2214b4bf0.png)

The "_Events Count_" metric should be added to the list under "_Visitors_" or under"_Events_". Its value should match what shown in the behavior page for Event Action and Event Category as "_Events_".
I would also recommend renaming it "_Events Count_" on the behavior page, for consistency and better clarity.

The suggested description for this metric would be "_Amount of times an event got triggered_"

Also, it should be better clarified in the description what "_Total Events_" represents (under "_Visitors_"). In fact, the description states "The total number (sum) of events". This is today misleading, as it can be interpreted as being exactly the total Events Count which this issue is about (but it's not).
I have no suggestion on what the description should be. After discussing this topic with the Matomo team via email, it is in fact still not clear to me what this metric is (I only got that "_You are correct "Total Events" and "Events" are not the same metric._")

**Comment by mattab** [comment]
Thank you @labolanimichele for reporting the issue. The new "Events count" metric would be a valuable addition. Just to answer the question:

> it should be better clarified in the description what "Total Events" represents (under "Visitors"). In fact, the description states "The total number (sum) of events". This is today misleading, as it can be interpreted as being exactly the total Events Count which this issue is about (but it's not).

 "Total Events" may be better described as the "Sum of all events in all visits". 

A known confusion is that `Total events` is the sum of all events of all visits, and even if a segment filters only one particular segment (eg. `Segment Action contains X`) the total events will still count all events of all visits and ignore the segment. (not expected)

**Comment by ibril15** [comment]
Hi All,

I ran into this exact issue.  I wanted to report on the Count of a specific Event per Measurable (I'm using this in the context of Rollup Reporting, but I imagine it's the same without it).  I'm also trying to build a table such as this:

Measurable | Count of Events
------------ | -------------
ABC | 12
XYZ | 34

Where the filter is "Event Action = something".  Using "Total Events" ignores the filter as the discussion above specifies.

Is there a workaround to achieve this?  If not, is there any tentative plan to include this new "Events Count" or make "Total Events" respect the filter?

Thanks a lot.

-Igor

**Comment by tsteur** [comment]
`Total events` is likely listed under `Visitors` or so and refers to the count of all events. You'd want to likely use the metric `Hits`. I suggest you get in touch with our support shop at innocraft.com @ibril15

**Comment by ibril15** [comment]
"Hits" worked!  Thank you!

**Comment by tsteur** [comment]
Awesome 👍
