### ISSUE TITLE
Is there a way to know when a request to the piwik has failed ?

### ISSUE THREAD

**Issue by Krypternite** [matomo-org/matomo#14325]
I would like to know if I can know that a request to the Piwik server has failed, like in case of being blocked by an AdBlocker. This can be helpful in showing a message to the users to disabled blockers.

Thanks

**Comment by tsteur** [comment]
Hi there, could you please ask this question in our forum? https://forum.matomo.org

**Comment by tsteur** [comment]
We generally don't answer questions here.
