### ISSUE TITLE
Wrong COM_STMT_PREPARE response size

### ISSUE THREAD

**Issue by MarcusMoeller** [matomo-org/matomo#14329]
Sometimes when I try to connect or run the archiver I got an error like:

./console core:archive
WARNING [2019-04-09 11:40:15] 31996  /usr/share/nginx/html/libs/Zend/Db/Statement/Mysqli.php(70): Warning - Wrong COM_STMT_PREPARE response size. Received 1 - Matomo 3.9.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
WARNING [2019-04-09 11:40:15] 31996  /usr/share/nginx/html/libs/Zend/Db/Statement/Mysqli.php(70): Warning - Packets out of order. Expected 1 received 2. Packet size=79 - Matomo 3.9.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
WARNING [2019-04-09 11:40:15] 31996  /usr/share/nginx/html/libs/Zend/Db/Statement/Mysqli.php(70): Warning - mysqli::prepare(): MySQL server has gone away - Matomo 3.9.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
                                                    
  [Zend_Db_Statement_Mysqli_Exception]              
  Mysqli prepare error: MySQL server has gone away  

When I re-run the archiver it works again after a while.

**Comment by fdellwing** [comment]
This was a big issue a while ago in Laravel, but I never saw it in Matomo.

Could you take a closer look at your PHP error log and the mysql log?

**Comment by tsteur** [comment]
Could we move this to the [forum](https://forum.matomo.org/) as the warning suggests?  It sounds like some server configuration issue. Maybe this is of help? https://groups.google.com/forum/#!msg/codership-team/tMlZYnp3MC0/Om4QzBmqr4IJ  or https://groups.google.com/forum/#!topic/proxysql/noyc-lI9gTk 
Happy to reopen though if there's something to do in Matomo
