### ISSUE TITLE
After Update - Error: You can't access this resource as it requires 'view' access for the website id = 1.

### ISSUE THREAD

**Issue by markus003** [matomo-org/matomo#14323]
Hi,

after upgrading Piwik vom Version 3.8.1 to Version 3.9.1 i get the following Error at Login as superuser (local admin):

` "Error: You can't access this resource as it requires 'view' access for the website id = 1."`

I stopped all services (httpd and MySQL), unzip the new files in the directory und override the config.ini.php file.  Additionally i also update my plugins (securityInfo to 3.0.6 and LoginLdap to 4.0.6). 

Please, can anybody help me. I'm a newbie with piwik.
Thank you

Best Regards,
Markus

**Comment by markus003** [comment]
And i add the following to the config/global.php:

`'EnableDbVersionCheck' => true,`

Because i get "No entry or class found for 'EnableDbVersionCheck'" at first Error at Login Page.

**Comment by tsteur** [comment]
> Because i get "No entry or class found for 'EnableDbVersionCheck'" at first Error at Login Page.

Sounds like some file wasn't updated (`config/global.php` likely). 

Could you please ask this question in the forum? https://forum.matomo.org

We don't answer questions here unless there is a bug. Maybe check if anything else changed on your server? Do you maybe have different users on your Matomo? Can you try a different user?
