### ISSUE TITLE
Add new Edge (Chromium) user agent

### ISSUE THREAD

**Issue by Aarklendoia** [matomo-org/matomo#14327]
The new Edge based on Chromium is available for Edge Insiders.

The user agent is :
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.48 Safari/537.36 Edg/74.1.96.24`

Could you add it?

**Comment by fdellwing** [comment]
Duplicate of #14268

**Comment by sgiehl** [comment]
should already be detected with latest master

**Comment by Aarklendoia** [comment]
I use version 3.9.1 and it displays Chrome 74.0 (and not Edge 74.1).

**Comment by sgiehl** [comment]
It was not included in latest release. But should be in the next one.

**Comment by Aarklendoia** [comment]
Ok, thanks.
