### ISSUE TITLE
To investigate the issue, someone would ideally give us access to their Matomo and server (so we can debug and find the issue).

### ISSUE THREAD

**Issue by b3wii** [matomo-org/matomo#14328]
To investigate the issue, someone would ideally give us access to their Matomo and server (so we can debug and find the issue).

_Originally posted by @tsteur in https://github.com/matomo-org/matomo/issues/14124#issuecomment-480993172_

Sorry cant do that. If you let me know what to do i could try to get you the information you need.

**Comment by b3wii** [comment]
Didnt want to open a new issue. Please delete.

**Comment by tsteur** [comment]
I think we can't delete issues. Will close it.
