### ISSUE TITLE
Index sizes

### ISSUE THREAD

**Issue by Tolriq** [matomo-org/matomo#14336]
Currently evaluating Matomo as a full replacement for Google Analytics for a very large user base.

But it seems I've under evaluated the necessary disk space for my requirements.

![image](https://user-images.githubusercontent.com/932609/55905466-462b1880-5bd2-11e9-9c40-96ead0cbbc9c.png)

Are all the indexes necessary even when only using cron archiving? (That amount of data is just 4 days and not everyone is migrated to it yet).

**Comment by tsteur** [comment]
Yes they are definitely all needed. We're very cautious with indexes and only add the ones that are really needed. Such questions by better asked in the forum btw: https://forum.matomo.org

The index on `log_link_visit_action` are btw:

```
  PRIMARY KEY (`idlink_va`),
  KEY `index_idvisit` (`idvisit`),
  KEY `index_idsite_servertime` (`idsite`,`server_time`)
```
