### ISSUE TITLE
Wrong GeoLiteCity DB URL

### ISSUE THREAD

**Issue by Xairoo** [matomo-org/matomo#14330]
The URL for the GeoLiteCity DB is wrong.

Current version is located at plugins/UserCountry/LocationProvider/GeoIp.php:
http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz

But it should be:
https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz

The working link can be found on this site:
https://dev.maxmind.com/geoip/geoip2/geolite2/

Looks like MaxMind has changed the DB format or just the naming too.

**Comment by Findus23** [comment]
Hi,

This code is only there for legacy reasons. 
The new GeoIp2 plugin supports the new database type and uses the URL you are mentioning:

https://github.com/matomo-org/matomo/blob/ff1c579f1faa003e461db2534f2606bd4ac4ddaa/plugins/GeoIp2/LocationProvider/GeoIp2.php#L23

If you want to migrate to GeoIP2, make a backup and enable the GeoIp2 plugin which will do the database migration, that might take a while.

**Comment by fdellwing** [comment]
You may also want to take a look at this blogpost: https://matomo.org/blog/2018/06/thinking-about-switching-to-geoip2-for-better-location-detection-heres-what-you-should-know/

**Comment by nerdoc** [comment]
@Findus23 - ok, but maybe you should remove the code from Matomo instructing users do download the old DB. even when you find the download link and copy the database (.mmdb format) into *misc*, Matomo won't recognize it. These instructions should be removed.

**Comment by tsteur** [comment]
@nerdoc make sure you're on the latest Matomo version and that you have enabled the GeoIP2 DB. Then the URL should be correct.
