### ISSUE TITLE
Data table labels should stick to the left

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#14333]
If you go into any reporting page that has eg 2 reports next to each other, and view a page with all columns, then you will quickly notice that you need to scroll to the right in order to see all metrics. You will see it looks like this:

![image](https://user-images.githubusercontent.com/273120/55841456-523bb980-5b83-11e9-8844-6f32c4e1395a.png)

Because the left column isn't sticky / not visible, you constantly need to scroll left/right to see which values belong to which label and the whole report/feature is basically unusable.

Could almost be a major issue @mattab ?

Problem: We need to have some smart logic that if the label is too wide, then we may need to disable this feature.

It would be fine to use the new `sticky` CSS feature which may make this easy to implement even if it's not supported by IE for example.

**Comment by mattab** [comment]
This issue makes using Matomo a bit frustrating. Would there maybe be a solution we can try? would be aewsome to fix before Matomo 4 :+1:
