### ISSUE TITLE
Warning “non well formed numeric value”

### ISSUE THREAD

**Issue by jmumby** [matomo-org/matomo#14331]
a user has encountered the message

`WARNING: core/Metrics/Formatter.php(193): Notice - A non well formed numeric value encountered - Matomo 3.9.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)`

when visiting path: /index.php module=CoreAdminHome&action=home&date=today&period=day&idSite=1.

**Comment by sgiehl** [comment]
this might already be fixed with #14017

**Comment by mattab** [comment]
Thank you for the report :+1:  

this will likely be fixed in Matomo 3.10.0 (RC release is out
if you still experience this issue afterwards, please re-open this and post a comment. Thanks!
