### ISSUE TITLE
Console: invalidating reports with segment based on custom Dimensions fails

### ISSUE THREAD

**Issue by peterbo** [matomo-org/matomo#14344]
For example:
`/path/to/matomo/console core:invalidate-report-data --dates=2019-03-11,2019-03-11 --sites=5 --segment="dimension2==Test123"`
In this case, dimension2 is an action dimension set up and active for this site-ID.

Fails with 
`[Exception]
  Segment 'dimension2' is not a supported segment.`

Probably because the custom dimensions are not correctly returned by getSegmentMetadata.

**Comment by tsteur** [comment]
cheers @peterbo created 2 PRs

**Comment by mattab** [comment]
Another customer reported it today. was this bug fixed maybe already and can now be closed?
