### ISSUE TITLE
csv export for VisitsSummary.getVisits with idSite=all and non-superuser not working

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14362]
Reported twice in https://forum.matomo.org/t/matomo-api-to-fetch-results-for-idsite-all-in-csv-xls-or-tsv-format-not-working-for-normal-users/31663 and reproduced on my Matomo instance

Requesting the `VisitsSummary.getVisits` API when
- the user of the token_auth is not a superuser
- idSite=all is requested
- and format=csv (or xls)

then the following error appears:
> Error: The parameter 'idSite=' is missing from the request.

All other requests seem to work fine (e.g. format=json)

**Comment by tsteur** [comment]
I can't really test it right now @Findus23 could you maybe try https://github.com/matomo-org/matomo/compare/3.x-dev...14362?quick_pull=1 ?

**Comment by mattab** [comment]
@Findus23 are you able to test the patch from the last comment above?
