### ISSUE TITLE
piwik/matomo.php? request is not getting called from hybrid mobile application

### ISSUE THREAD

**Issue by JeyakumarThangaraj** [matomo-org/matomo#14377]
Dear Team,
piwik/matomo.php? request is not getting called from hybrid mobile application using javascript tracking code. but same has been working fine with sample web application. Kindly advise.

Thanks

**Comment by tsteur** [comment]
Maybe check out https://github.com/matomo-org/matomo/issues/14375 and otherwise be great to ask this question in the forum: https://forum.matomo.org
