### ISSUE TITLE
Issue when running archive with vitess

### ISSUE THREAD

**Issue by brunowego** [matomo-org/matomo#14389]
I think this is out of matomo scope, but I'm excite about the idea behind vitess.

I have a kubernetes cluster with vitess, I solved issues with lock's and sql mode, instructions where vitess not support, now I'm stop in other challenge, take a look in the output below, I get this when run arquive:

```sh
Error: Got invalid response from API request: ?module=API&method=API.get&idSite=1&period=day&date=last3&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:427:"SQLSTATE[HY000]: General error: 1105 vtgate: http://vtgate-zone1-76d8bbd7d4-gmmvq:15001/: syntax error at position 519 near ':' - in plugin Actions, caused by: SQLSTATE[HY000]: General error: 1105 vtgate: http://vtgate-zone1-76d8bbd7d4-gmmvq:15001/: syntax error at position 519 near ':', caused by: SQLSTATE[HY000]: General error: 1105 vtgate: http://vtgate-zone1-76d8bbd7d4-gmmvq:15001/: syntax error at position 519 near ':'";}'
```

Any tips are welcome. Thanks.

**Comment by tsteur** [comment]
Hi there,

I suppose vitess has some MySQL limitations. Unfortunately, we only support plain MySQL/MariaDB. see also https://github.com/matomo-org/matomo/issues/500

We've found there are quite a few DBs based on MySQL, eg column oriented DBs but they usually don't have all the features of MySQL or are limited in the number of joins, etc.

I've looked into the error message but there is basically no info in there. Maybe it's trying to rewrite some query and doesn't do it? We can't really help here. Maybe check in the forum https://forum.matomo.org if someone has done it before.
