### ISSUE TITLE
LoginSAML should redirect to original URL after login when using "Force SAML Login"

### ISSUE THREAD

**Issue by pimlottc-gov** [matomo-org/matomo#14388]
When using the "Force SAML Login" option, the user should end up at the original page they requested before going through the SAML flow.

Steps to reproduce:
1. Open Matomo UI via a deep link
2. Get redirected through SAML

Expected result:
End up on originally requested page

Actual result:
End on on Matomo UI default page

**Comment by tsteur** [comment]
@pimlottc-gov could you email shop at innocraft.com about this? That would be great.
