### ISSUE TITLE
Unable to configure GeoIP 2 to use country-only database

### ISSUE THREAD

**Issue by mfb** [matomo-org/matomo#14385]
For privacy policy reasons, we need Matomo to log only the visitor's country, not their city.

Therefore, we have configured the country-only Geo IP 2 database at index.php?module=UserCountry&action=adminIndex by using https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz as the download URL.

Inexplicably, however, Matomo is reporting:

> According to this provider, your current location is:
> 
> (37.735, -122.373)
> San Francisco, CA
> 94124
> United States
> 
> Note: This GeoIP implementation has access to the following types of databases: City.

No idea what could cause this, but I was thinking perhaps the plugin downloaded a City database and has failed to overwrite that with the Country database I specified?  However, autoupdates have been running:

> The updater was last run on 2019-04-29.

So, I'm stumped on how to properly setup country-only GeoIP lookup.

**Comment by sgiehl** [comment]
Do you still have that problem? Tried to reproduce that, but when I set up GeoIP with the country db url, it works like it should. Did you maybe set it up with the city database and changed to download url afterwards to the country db url? The task to update the database stored locally might not be automatically triggered when the url is changed...

**Comment by mfb** [comment]
It was initially using the city database.  So my question is, why is it not updating to use the country database when the autoupdate runs - it's now run several times on a weekly basis.

**Comment by sgiehl** [comment]
@mfb I've just investigated that one. The "issue" is quite simple. Once Matomo downloaded a database file, it's created in the folder `misc`. When changing the download url to another database type it will create a new file with this name.

So in your case you had the city database defined. So a `GeoLite2-City.mmdb` was created. Changing the download to country database created the file `GeoLite2-Country.mmdb`, but the city database file is not automatically removed. That way it will be used, until you remove it manually.

@tsteur @mattab  any opinion if we should change the behavior here? Not sure if it's good to automatically remove other database files that might already exist...

**Comment by tsteur** [comment]
I wouldn't delete any, but if a user has configured to download the country DB, can we prefer using that DB in matomo? (I don't know how it works)

**Comment by sgiehl** [comment]
It walks through [this list](https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/GeoIp2/LocationProvider/GeoIp2.php#L41) and stops as soon as a file exists, which is then used. We could maybe manipulate it to prefer a specific db if autoupdate is configured.

**Comment by mattab** [comment]
Another solution could be to improve the text in the UI and list the filename used by the database. eg. write `Note: This GeoIP implementation has access to the following types of databases: City (database in misc/GeoLite2-City.mmdb)` or so.

**Comment by mfb** [comment]
I'd propose since GeoLite2-City.mmdb is built in to the image, that file could be last in the list, allowing any other file to override it.

**Comment by mattab** [comment]
we'll probably stop using Maxmind soon, so closing this issue now, see #15308
