### ISSUE TITLE
About Matomo API Filed Name

### ISSUE THREAD

**Issue by baojianquan** [matomo-org/matomo#14382]
How can i get the API response filed descriptions ?
It doesn't match with the database filed name.

**Comment by tsteur** [comment]
Hi there, what do you mean by filed name?

**Comment by baojianquan** [comment]
For example,i got some json data from api Live.getLastVisitsDetail,but i don't know the fileds visitLocalTime/lastActionTimestamp how it means?
Where can I find some instructions?

**Comment by tsteur** [comment]
I see, you mean the field names. Some fields may be explained in https://glossary.matomo.org/ and some may be kind of explained in https://developer.matomo.org/guides/persistence-and-the-mysql-backend#log-data-persistence (look for `visit_last_action_time `, `visitor_localtime `). for any further info please ask in the forum: https://forum.matomo.org
