### ISSUE TITLE
Matomo - strange behaviour with woo-commerce (innocraft plugin)

### ISSUE THREAD

**Issue by jacas** [matomo-org/matomo#14384]
Hi,
I'm using Matomo Cloud.
My site only accepts logged in users. After several tests, my user has the same visitor ID (_id), but when i purchase something (woo-commerce) Matomo creates a new visitor ID, maintaining the other visits on the "old" visitor ID.

Checking the data in network, i see the visitor ID (_id) is the same for all cases... so, I assume the issue is with Matomo.

Is my users's visitor ID being maintained for some reason, disrupting the link between ecommerce records?

Help?

**Comment by tsteur** [comment]
Hi @jacas could you email shop at innocraft.com about this? We can follow up and investigate the issue through this.
