### ISSUE TITLE
piwik.php url download query parameter is case sensitive

### ISSUE THREAD

**Issue by MERamadan** [matomo-org/matomo#14396]
**Issue:**
When posting a download action with query parameter **Downalod** (capital D), it is tracked as a page view instead of download action. 

**Excepted:**
All query parameter keys should be case insensitive to avoid similar issues. 

**Generate Steps:**
- Url with **Downalod** (capital D) is logged as a page view without title 
http://localhost/piwik.php?idsite=1&rec=1&apiv=1&r=061746&_idts=1556711817&_idvc=0&_id=0dcabb7d69b1aa23&url=http%3a%2f%2flocalhost%2fpiwik.org%2fpath%2fagain%2flatest.zip&Download=http%3a%2f%2flocalhost%2fpiwik.org%2fpath%2fagain%2flatest.zip

- Url with **download** is logged as a download action 
http://localhost/piwik.php?idsite=1&rec=1&apiv=1&r=061746&_idts=1556711817&_idvc=0&_id=0dcabb7d69b1aa23&url=http%3a%2f%2flocalhost%2fpiwik.org%2fpath%2fagain%2flatest.zip&download=http%3a%2f%2flocalhost%2fpiwik.org%2fpath%2fagain%2flatest.zip

**Related Issue (Matomo .Net Client):**
https://github.com/matomo-org/piwik-dotnet-tracker/issues/68

**Comment by MERamadan** [comment]
Proposed Solution:
File: matomo\core\Tracker\Request.php
Added the following line to lower incoming request query keys before set this->params
	**$params=array_change_key_case($params, CASE_LOWER);**

Complete Code:

 ` public function __construct($params, $tokenAuth = false)
    {
        if (!is_array($params)) {
            $params = array();
        }			
	**$params=array_change_key_case($params, CASE_LOWER);**
        $this->params = $params;
        $this->rawParams = $params;
        $this->tokenAuth = $tokenAuth;
        $this->timestamp = time();
        $this->isEmptyRequest = empty($params);
        $this->customTimestampDoesNotRequireTokenauthWhenNewerThan = (int) TrackerConfig::getConfigValue('tracking_requests_require_authentication_when_custom_timestamp_newer_than');

        // When the 'url' and referrer url parameter are not given, we might be in the 'Simple Image Tracker' mode.
        // The URL can default to the Referrer, which will be in this case
        // the URL of the page containing the Simple Image beacon
        if (empty($this->params['urlref'])
            && empty($this->params['url'])
            && array_key_exists('HTTP_REFERER', $_SERVER)
        ) {
            $url = $_SERVER['HTTP_REFERER'];
            if (!empty($url)) {
                $this->params['url'] = $url;
            }
        }

        // check for 4byte utf8 characters in all tracking params and replace them with �
        // @TODO Remove as soon as our database tables use utf8mb4 instead of utf8
        $this->params = $this->replaceUnsupportedUtf8Chars($this->params);
    }`

**Comment by tsteur** [comment]
Hi there, the proposed solution could break a lot of  things. In general, the last time this was suggested it was closed because urls are usually not case insensitive see https://github.com/matomo-org/matomo/issues/10534

You would implement this in the client you use. For example if you use JS, and want pageviews to be case insensitive, you could do something like `_paq.push(['setCustomUrl', location.href.toLowerCase()])`. Similar things probably work in the dot net tracker.
