### ISSUE TITLE
Add option to core:archive that allows you to continue even if the site is not in matomo anymore

### ISSUE THREAD

**Issue by paladox** [matomo-org/matomo#14393]
Hi, could a option be added that allows you to continue even if you get a error like:

  [Piwik\Exception\UnexpectedWebsiteFoundException]                               
  An unexpected website was found in the request: website id was set to '2897' .  

please?

This would be super useful.

Or is there a way to clear the deleted websites so they are not run?

**Comment by tsteur** [comment]
We would not add an option but we could in general implement this as standard behaviour. I'm seeing for some things this is already implemented in the archiver, eg when archiving days, but not in some other places.

**Comment by paladox** [comment]
@tsteur would you know how I would be able to fix this? Is there another command i should run to fix this please? :)

**Comment by tsteur** [comment]
@paladox I suppose this file here https://github.com/matomo-org/matomo/blob/3.10.0-b1/core/CronArchive.php would need to be patched in some places to catch `UnexpectedWebsiteFoundException` similar to here: https://github.com/matomo-org/matomo/blob/3.10.0-b1/core/CronArchive.php

There isn't any workaround I'm aware of.

**Comment by paladox** [comment]
https://github.com/matomo-org/matomo/blob/3.10.0-b1/core/CronArchive.php is the same as your first link :)

**Comment by tsteur** [comment]
Sorry, looks like I need some coffee haha :) here is the correct link: https://github.com/matomo-org/matomo/blob/3.10.0-b1/core/CronArchive.php#L696-L699

**Comment by paladox** [comment]
@tsteur thanks for the pointer! Fixed in https://github.com/matomo-org/matomo/pull/14397 !
