### ISSUE TITLE
Cron: archive not working

### ISSUE THREAD

**Issue by bahooha** [matomo-org/matomo#14404]
I have archiving via CRON set up as per: https://matomo.org/docs/setup-auto-archiving/#linux-unix-how-to-set-up-a-crontab-to-automatically-archive-the-reports

This has worked perfectly for years, but unfortunately since a couple of weeks not anymore. I'm not sure if this is since the update to 3.9.1 or if it has started failing earlier. If I understand correct, the update  to Matomo 3.9.1 has been installed on March 22 and the error/not working cron started on April 3rd.

On this day I've recieved an error email from cron:
```
[Exception]                                                                                    
2 total errors during this script execution, please investigate and try and fix these errors.  

core:archive [--url="..."] [--force-all-websites] [--force-all-periods[="..."]] [--force-timeout-for-periods[="..."]] [--skip-idsites[="..."]] [--skip-all-segments] [--force-idsites[="..."]] [--force-periods[="..."]] [--force-date-last-n="..."] [--force-date-range[="..."]] [--force-idsegments="..."] [--concurrent-requests-per-website[="..."]] [--concurrent-archivers[="..."]] [--disable-scheduled-tasks] [--accept-invalid-ssl-certificate] [--php-cli-options[="..."]]
```

At the times the CRON fires, I can see that the archive.log file is being updated, but shows an empty response. I can't find anything in the error logs.

When I manually trigger the archive.php as described in https://matomo.org/docs/setup-auto-archiving/#web-cron-when-your-web-host-does-not-support-cron-tasks I get the following error:
```Error: Entry &quot;Piwik\Plugins\Monolog\Formatter\LineMessageFormatter&quot; cannot be resolved: Parameter $logMessageFormat of __construct() has no value defined or guessable
Full definition:
Object (
    class = Piwik\Plugins\Monolog\Formatter\LineMessageFormatter
    scope = singleton
    lazy = false
    __construct(
        $logMessageFormat = #UNDEFINED#
        $allowInlineLineBreaks = (default value) true
    )
)
```
I have checked if all files are available against a clean install. Nothing seems wrong.

Can anybody shed any light on this?

**Comment by tsteur** [comment]
Looking at the code it does sound like some files are missing. Make sure you have the latest version and try maybe again to update the code using the manual 3 step update: https://matomo.org/docs/update/#the-manual-three-step-update

In case you're installing Matomo from git: that's not really recommended.

**Comment by bahooha** [comment]
I had already checked file integrity, but to be sure I've followed the steps from your link: no avail.

File are 100% identical to a clean installation.

Any other ideas?

**Comment by tsteur** [comment]
Do you have some `config.php` created? Or maybe the plugin `Monolog` is not active?

**Comment by tsteur** [comment]
In general we're not seeing this problem somewhere else, so it looks like some configuration or server issue.

**Comment by bahooha** [comment]
I do not understand why, but it turns out the Monolog plugin was inactive.

Thank you very much for your help, Thomas!

**Comment by tsteur** [comment]
Awesome, glad you found it

**Comment by thelfensdrfer** [comment]
Just wanted to say that I had the exact same error. Did we disable the plugins ourselves or did it happen automatically?

**Comment by tsteur** [comment]
Shouldn't have happened automatically.
