### ISSUE TITLE
Row functions not visible

### ISSUE THREAD

**Issue by babielcbo** [matomo-org/matomo#14418]
We are using Matomo on premise. For some users, the buttons for opening transitions are not displayed on hover in a row.
If we delete the account and create a new one, the buttons are displayed again. However, it happens that they disappear again after a while.
![image001](https://user-images.githubusercontent.com/43536414/57224506-f8a39f00-7009-11e9-80c9-cbfbb9f509e0.jpg)

**Comment by sgiehl** [comment]
@babielcbo The row actions are currently disabled for browser performance reasons when more than 255 rows are displayed in a table. So maybe try reducing the limit of rows shown,

**Comment by tsteur** [comment]
@babielcbo  closing as it's likely due to @sgiehl comment. Feel free to comment if that's not the case.
