### ISSUE TITLE
When testing UserAgent browser is detected but same browser is ignored in raports

### ISSUE THREAD

**Issue by bigretromike** [matomo-org/matomo#14426]
UserAgents:
` Kodi/16.1 (Linux; Android 6.0; SHIELD Android TV Build/MRA58K) Android/6.0.0 Sys_CPU/armv8l App_Bitness/32 Version/16.1`
` Kodi/17.0-ALPHA1 (X11; Linux armv7l) OpenELEC/8.0 HW_RaspberryPi/1.0 App_Bitness/32 Version/17.0-ALPHA1`
`Kodi/14.1 (Windows NT 6.3; WOW64) App_Bitness/32 Version/14.1`

Those are detected correct on `module=DevicesDetection&action=detection`, all of them are missing browsers families, yet all of them are 'unknown' browser in every raport. 
Is that the issue that Kodi browser is not liked with any other family ?

Do adding family for browser will fix that ?

**Comment by Findus23** [comment]
Hi,

As you can e.g. see [here](https://devicedetector.lw1.at/%20Kodi%2F17.0-ALPHA1%20(X11;%20Linux%20armv7l)%20OpenELEC%2F8.0%20HW_RaspberryPi%2F1.0%20App_Bitness%2F32%20Version%2F17.0-ALPHA1) DeviceDetector (the library Matomo uses and maintains for user agent detection) detects all these user agents as `mediaplayer` instead of browsers.

There is a quite old issue for Matomo to also support other device types from DeviceDetector: #5413

**Comment by Findus23** [comment]
Just noticed that there was this exact discussion two years ago in #5615 :)

**Comment by bigretromike** [comment]
I dont know how #5615 is exact, but ok.

**Comment by Findus23** [comment]
Ah, it's https://github.com/matomo-org/device-detector/issues/5615

**Comment by bigretromike** [comment]
Yeah, I dig thru that. 
So until https://github.com/matomo-org/matomo/issues/5413 this is possible only by tweaking browsers.yml and Browser.php, not the best solution.

Ok, thanks - looks like `module=DevicesDetection&action=detection` give wrong results because it say its a Browser where for Piwik/Matomo its not.

**Comment by Findus23** [comment]
I am currently in the process of creating a new website that will show the exact DeviceDetector results for  a user agent. You can find the current status here: https://devicedetector.lw1.at/

**Comment by bigretromike** [comment]
Yes, your page does detect it as mediaplayer which is correct, nonetheless the issue is still with the core ;-)
While I have you here, do you know how I could process all data saved in Matomo with newly created browsers so it recognized those old 'unknown' rows ?
