### ISSUE TITLE
Core Archive spawns cron jobs that call from IP 0.0.0.0

### ISSUE THREAD

**Issue by James-Oakley** [matomo-org/matomo#14435]
I started encountering problems where the console core:archive cron job was failing to run. The curl calls that are spawned were failing with 302 forbidden.

I don't have root access to the server my installation runs on, so I asked my hosting provider to check the mod_security logs. They found that a WAF rule was being tripped because the calling IP was showing as 0.0.0.0, and they were blocking requests from there to prevent IP-spoofing abuse.

I've not been able to learn my way around Matomo's source code, so I thought I'd report it here for others to comment: Surely, a localhost originating curl call should come through from 127.0.0.1. Is this something Matomo manually overrides, or if not where does it come from?

TIA.

**Comment by tsteur** [comment]
@James-Oakley we generally don't answer questions in the issue tracker, especially when they are related to server configuration etc. I recommend you ask this question in the forum https://forum.matomo.org or get in touch with support: https://matomo.org/support-plans/

AFAIK we don't overwrite anything here and just issue regular requests.
