### ISSUE TITLE
FAQ scroll to broken in FF

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#14434]
https://matomo.org/faq/#troubleshooting

Should scroll the troubleshooting category into view but does not work correctly in Firefox. Scrolling ends just before the headline would come into view. Works fine in Chrome.

```
ii  firefox                                           66.0.4+build3-0ubuntu0.18.04.1              amd64        Safe and easy web browser from Mozilla
ii  google-chrome-stable                              74.0.3729.131-1                             amd64        The web browser from Google
```

**Comment by tsteur** [comment]
AFAIK they are just regular anchor links. not sure we can do much?

**Comment by fdellwing** [comment]
Might have just be a temporary Firefox bug, they did fuck up a lot of things in the last time.
