### ISSUE TITLE
Capturing microservices logs for end to end analytics

### ISSUE THREAD

**Issue by p-chavan** [matomo-org/matomo#14440]
We want to capture analytics data for both UI and Service. This will help us establish the relation between UI and Service errors. Is there any way to do this already?
For example, if the landing page has 100 views and the internal page has 50 views. We want to find out if service errors/exceptions are resulting in fewer views for internal pages.

**Comment by tsteur** [comment]
Hi @p-chavan we generally don't answer questions in the issue tracker. Could you ask this in the forum? https://forum.matomo.org  You may also want to describe in more details what exactly you want to do. Something you may want to check out is https://plugins.matomo.org/CustomDimensions

Cheers
