### ISSUE TITLE
Feature request: option to disable tracking failure notifications

### ISSUE THREAD

**Issue by timodenissen** [matomo-org/matomo#14447]
Hello,

as asked in the forum [1]: please add an option to disable the automatic notifications about tracking failures.

Cheers,
Timo

[1] https://forum.matomo.org/t/how-to-disable-e-mails-about-tracking-failures/32854

**Comment by fdellwing** [comment]
Is it enough to provide an option via `config.ini.php` or do we need to make this configurable via UI?

**Comment by timodenissen** [comment]
An option in `config.ini.php` is fine for me, perhaps at a later time an option via UI?

**Comment by fdellwing** [comment]
Did a PR for this, but others have to decide if that is enough ;)

You can test the change by applying this patch: https://patch-diff.githubusercontent.com/raw/matomo-org/matomo/pull/14448.patch

**Comment by mattab** [comment]
documented in new FAQ: [How do I disable tracking failure notification emails?](https://matomo.org/faq/how-to/faq_35802/)
