### ISSUE TITLE
Why the visitor_days_since_first is not gradually increasing

### ISSUE THREAD

**Issue by chenqingan** [matomo-org/matomo#14452]
![image](https://user-images.githubusercontent.com/30650695/57837241-f8b75200-77f4-11e9-968c-5f9a14c468d9.png)
Look at this image, according to the concept of visitor_days_since_first, this value should have be six. 
There are many error values in my project like this, and it is happening yet.
My matomo version is 3.5.1

**Comment by tsteur** [comment]
Could you update to the latest version and see if it's fixed there? AFAIK there was some work done on this. Feel free to reopen the issue if you still experience any issues with the latest version.

**Comment by chenqingan** [comment]
Today I have updated to the latest version (3.9.1). And there are still same problems. The visitor_days_since_first of all users visiting today change to zero.
![image](https://user-images.githubusercontent.com/30650695/58072802-6be50d80-7bd3-11e9-9e9d-094d23ddb4d4.png)
![image](https://user-images.githubusercontent.com/30650695/58072876-a8186e00-7bd3-11e9-9e32-defea6ee34f8.png)

**Comment by chenqingan** [comment]
@tsteur How can I reopen this issue, I cant find the entry.

**Comment by tsteur** [comment]
@diosmosis do you remember maybe details about it? I think you looked at it a while ago

**Comment by diosmosis** [comment]
We changed it to set the value to 0 if the visitor wasn't known. There might be an issue w/ the code that checks if a visitor is known or not. @chenqingan can you see what `visitor_returning` for those visits is set to?

**Comment by chenqingan** [comment]
Okay.Then I found more problems. 
Today the value is still zero. I updated to 3.9.1 at May 21th. I afraid that the value will be only zero later.
Before I update to the latest, such problem is existing, but casual and random. The percentage of wrong value is about 1%.
![image](https://user-images.githubusercontent.com/30650695/58147829-e0c94d80-7c8e-11e9-9d5d-ae96c1788347.png)
![image](https://user-images.githubusercontent.com/30650695/58148273-a82a7380-7c90-11e9-9290-76ab35482a1c.png)
![image](https://user-images.githubusercontent.com/30650695/58148297-bf696100-7c90-11e9-834c-68a770654418.png)

**Comment by diosmosis** [comment]
Hmm, I'm not sure what to make of that. @chenqingan do you have access to web server logs for your matomo (ie, apache logs)? If you can find the log entry for the request to matomo.php for a specific problematic idvisitor/time, can you check the value of `_idts`? If it's non-zero, then the javascript tracker is working properly and matomo is setting the value incorrectly. If it's zero, then it means the javascript tracker is failing to send the proper value. In that case it would be helpful to look at a few of the user agents for visitors where this isn't working.

**Comment by chenqingan** [comment]
grep -cE '_idts=[^0-9]+' matomo-access_log
computing result is 0.

**Comment by diosmosis** [comment]
@chenqingan can you email the access logs for a couple problematic visitors to hello@matomo.org (grep the file by visitorid/userid)? We can try and reproduce the issue.

**Comment by chenqingan** [comment]
@diosmosis  I have sent an email to you.

**Comment by diosmosis** [comment]
@chenqingan thanks for sending the logs, I see the problem, `new_visit=1` is used which is exposing a bug in the visitor recognition code. Will look into a fix.

**Comment by diosmosis** [comment]
@chenqingan would you be able to check if this change works for you: https://github.com/matomo-org/matomo/pull/14491 ?

**Comment by chenqingan** [comment]
@diosmosis Im afraid that I couldn't deploy this merge to my online edition. Because I have only one productive edition that is used to assure apps work normal. Sorry :)
