### ISSUE TITLE
Heatmap Javascript error "Cannot read property 'nested' of null"

### ISSUE THREAD

**Issue by Zewy** [matomo-org/matomo#14457]
I get this Error in Chrome (74.0.3729.157)

URL: 

> https://www.mysite.com/matomo/plugins/HeatmapSessionRecording/libs/svg.js/dist/svg.min.js?cb=496c87a846c4eec4bace62bc59306268

Error:
> svg.min.js?cb=496c87a846c4eec4bace62bc59306268:1 Uncaught TypeError: Cannot read property 'nested' of null
>     at Function.g.prepare (svg.min.js?cb=496c87a846c4eec4bace62bc59306268:1)
>     at HTMLDocument.<anonymous> (svg.min.js?cb=496c87a846c4eec4bace62bc59306268:1)

```
Matomo version: 3.9.1
MySQL version: 5.6.43
PHP version: 5.6.38
```

**Comment by tsteur** [comment]
Hi there,

could you email shop at innocraft.com about this? Cheers

**Comment by kayakr** [comment]
I see this issue also when trying to display a heatmap.

**Comment by tsteur** [comment]
@kayakr could you email our support at shop at innocraft.com as well? We'll be happy to have a look. Cheers

**Comment by kayakr** [comment]
@tsteur Emailed, thanks.
