### ISSUE TITLE
Console command that sends a simple test email

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14455]
-> The goal of this issue is to create a simple console command that sends a test email. The email should have the default Matomo header and footer and just say something like `Hello, world! <br/> This is a test email sent from $MATOMO_URL` and subject `This is a test email sent from $MATOMO_URL` where MATOMO_URL is the matomo instance URL.

Why? To have a simple way to check if sending an email from CLI works. Because many people experience the problem that [Scheduled email reports](https://matomo.org/docs/email-reports/) are not sent from `core:archive` crontab, while they are sent correctly when one manually clicks on `Send report now` button. See this example bug report https://forum.matomo.org/t/auto-archiving-no-emails-sent/32643 (there are many other similar ones). In some (all?) cases, the problem is that the emails won't send from CLI. For example because PHP CLI config is different from the apache/nginx config and there may be something (eg. sendmail) mis-configured.

A common work-around is to use a SMTP server where usually this problem goes away.

**Comment by Findus23** [comment]
Sounds a lot like #14302.
I'm closing this in favor of #14302 as I have cross-linked the related issues there.
