### ISSUE TITLE
Mail traking generates numerous actions

### ISSUE THREAD

**Issue by AlejandroITOP** [matomo-org/matomo#14451]
I am tracking the emails by pixel.The problem is that when the person opens the email is generated in matomo an action equal to the length of the action name that we passed as a parameter.
Example:
"https://localhost:3000/matomo.php?idsite=1&amp;rec=1&amp;action_name=email&amp;uid=9999&amp;_rcn=emailTracking"

when opening the mail as the action name is "email", in matomo we see 5 actions that are 1- e, 2-em, 3-ema, 4-emai and 5-email

**Comment by tsteur** [comment]
Looks like your link is wrong, could you ask this question in the forum? https://forum.matomo.org

Also possible the client is requesting multiple versions of that link.
