### ISSUE TITLE
Cities do not correspond to regions

### ISSUE THREAD

**Issue by h3t1** [matomo-org/matomo#14462]
Hi, I'm using matomo 3.9.1 with GeoIP 2 (PHP)
The problem is that Moroccan cities are not matching regions (also the map is showing incorrect regions for cities) as you can see in the picture below :
![map](https://user-images.githubusercontent.com/20133892/57977538-f702af80-79e9-11e9-8322-f37ba857681e.png)
I also tested some IP address here:
https://www.maxmind.com/en/geoip-demo
and seems like everything is OK, so I do not know where the problem comes from.
**PS: I can help correct Moroccan cities to match their regions**

**Comment by sgiehl** [comment]
Hi there. Sorry for the delay. What exactly is wrong with the regions? We actually only use the data provided by Maxmind in this case. Only the region names are stored within in Matomo, but I don't think the mapping from ISO codes to region names has changed. See https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/GeoIp2/data/isoRegionNames.php#L2979-L3060

**Comment by h3t1** [comment]
Hi! Thank you for your reply,
I think the ISO mapping may have changed because Morocco has recently changed its regions from 16 to 12 regions.
![image](https://user-images.githubusercontent.com/20133892/62039128-fc048c00-b1ee-11e9-90b9-ee17531db5a3.png)
![image](https://user-images.githubusercontent.com/20133892/62039177-10e11f80-b1ef-11e9-8ec4-00c15dfca7c7.png)
source : [https://en.wikipedia.org/wiki/Regions_of_Morocco](https://en.wikipedia.org/wiki/Regions_of_Morocco)

**Comment by h3t1** [comment]
here is a demo that shows the difference between Maxmind and Matomo for the same address ip:
IP address: **41.249.92.68**
![rabat](https://user-images.githubusercontent.com/20133892/62040228-13447900-b1f1-11e9-8929-2293c3caa751.png)
![Untitled1](https://user-images.githubusercontent.com/20133892/62040410-7e8e4b00-b1f1-11e9-80dd-40542d3e755f.png)

**Comment by sgiehl** [comment]
ah ok. so we need to update our region mapping. Will have a look at that

**Comment by r3tr0sp3c** [comment]
Also for greek city / region combinations

<img width="1149" alt="screenshot" src="https://user-images.githubusercontent.com/47220281/199346252-8e98acef-538b-42df-b1c2-07ff850ceab4.png">

Larisa and Volos belong to Thessaly, in the mainlands , not Zakynthos which is an island.
