### ISSUE TITLE
CSS issue on Matomo privacy page

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#14468]
On widescreen monitors the opt-out is kind of broken. The iframe should have a width of 100% to prevent this from happening :)

![Screenshot_20190521_154610](https://user-images.githubusercontent.com/22813377/58101296-aeace280-7bdf-11e9-8a5a-3bdee44f0c00.png)

https://matomo.org/privacy-policy/#optout

**Comment by Findus23** [comment]
Thanks for noticing!
I have now added a `display:block` to make sure the iFrame is it's own block.
