### ISSUE TITLE
Add TypeScript declaration 

### ISSUE THREAD

**Issue by alexandrestein** [matomo-org/matomo#14472]
I'm using **VueJS** with **TypeScript**.

**TypeScript** is great to develop complex application with much less risks of type error and some other common errors.
But when you try to use pure **JS** it become a nightmare (at least for me).

I'm sure some of the maintainer has much more **JS** and probably **TS** skills than I  do.

Would it be possible to see the typescript declaration for the **Piwik** file.

**Comment by Findus23** [comment]
Hi,

While I have used typescript before, I don't think I can maintain proper typings.
So if someone wants to help, they can create a typeset declaration and submit it to https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by tsteur** [comment]
Hi @alexandrestein there are no plans to convert the JS tracker to typescript or any typeset declaration (as we would likely need to maintain it). We can currently manage the code without it and we want to avoid needing to convert the code re cross browser etc.

**Comment by alexandrestein** [comment]
Well, worth to try. :smile: 
Thank you for your quick answers.

**Comment by tsteur** [comment]
Thanks for the suggestion though. We might consider it at a later stage but not anytime soon.
