### ISSUE TITLE
A fatal error occurred - The string to escape is not a valid UTF-8 string

### ISSUE THREAD

**Issue by MERamadan** [matomo-org/matomo#14485]
We are facing the below issues as we our url's have Arabic characters. This happens when track download files and file names are in Arabic.

Firstly we get a bad request response when we track the file download, then we applied the **utf8mb4** setting on mysql as suggested at issue #11136, after that we got a OK response from matomo. 

However, when we open the dashboard or visitors log we are getting error _"Oops… there was a problem during the request....."_.

**Errors:**
(1) The string to escape is not a valid UTF-8 string.
in D:\Matomo\matomo\plugins\Live\templates\getLastVisitsStart.twig line 73  

(2) The string to escape is not a valid UTF-8 string.
in D:\Matomo\matomo\plugins\CoreHome\templates\_dataTable.twig line 67  

**Screenshot:**
![matomo-1](https://user-images.githubusercontent.com/24781219/58378416-6fe2a800-7fa4-11e9-9ec0-5e0ba48d438d.png)

**Environment Information:**
Matomo v3.9.1
MySQL 8.0.15 (Community - Win64) 
IIS 10
Windows Server 2019 (1809)

**MySQL Configurations**
![mysql-1](https://user-images.githubusercontent.com/24781219/58378532-4aef3480-7fa6-11e9-9f17-9d19aeb0cff2.png)

**Tracking Url's** to try to reproduce the issue
http://10.10.158.242:6660/piwik.php?idsite=1&rec=1&apiv=1&r=946539&uid=fa%40ecas.com&_idts=1558851102&_idvc=0&_id=909de6088a99b7d5&url=http%3a%2f%2f10.10.158.242%3a4040%2fECASLibrary002%2f%d8%b3%d8%ac%d9%84+%d8%b9%d9%85%d9%84+2019_DMA_00006+(1)%2f%d9%86%d9%85%d9%88%d8%b0%d8%ac+%d8%b9%d8%b1%d8%b6+%d8%a7%d9%84%d8%ac%d9%87%d8%a9.pptx&urlref=http%3a%2f%2f10.10.158.242%3a4040%2findex.aspx&dimension1=8e7449cd-ba1c-e611-80d2-0050568e7fa1&dimension2=External&dimension3=1cfc40ed-7b7f-e911-89cb-005056bb5a0e&dimension4=ec_workitem&download=http%3a%2f%2f10.10.158.242%3a4040%2fECASLibrary002%2f%d8%b3%d8%ac%d9%84+%d8%b9%d9%85%d9%84+2019_DMA_00006+(1)%2f%d9%86%d9%85%d9%88%d8%b0%d8%ac+%d8%b9%d8%b1%d8%b6+%d8%a7%d9%84%d8%ac%d9%87%d8%a9.pptx

http://10.10.158.242:6660/piwik.php?idsite=1&rec=1&apiv=1&r=574682&uid=fa%40ecas.com&_idts=1558851106&_idvc=0&_id=909de6088a99b7d5&url=http%3a%2f%2f10.10.158.242%3a4040%2fECASLibrary002%2f%d8%b3%d8%ac%d9%84+%d8%b9%d9%85%d9%84+2019_DMA_00006+(1)%2f%d8%af%d8%b1%d8%a7%d8%b3%d8%a9+%d8%a7%d9%84%d9%82%d8%b7%d8%a7%d8%b9+-+2017_00020-+SectorAnalysis.docx&urlref=http%3a%2f%2f10.10.158.242%3a4040%2findex.aspx&dimension1=8e7449cd-ba1c-e611-80d2-0050568e7fa1&dimension2=External&dimension3=1cfc40ed-7b7f-e911-89cb-005056bb5a0e&dimension4=ec_workitem&download=http%3a%2f%2f10.10.158.242%3a4040%2fECASLibrary002%2f%d8%b3%d8%ac%d9%84+%d8%b9%d9%85%d9%84+2019_DMA_00006+(1)%2f%d8%af%d8%b1%d8%a7%d8%b3%d8%a9+%d8%a7%d9%84%d9%82%d8%b7%d8%a7%d8%b9+-+2017_00020-+SectorAnalysis.docx

http://10.10.158.242:6660/piwik.php?idsite=1&rec=1&apiv=1&r=075426&uid=fa%40ecas.com&_idts=1558851118&_idvc=0&_id=909de6088a99b7d5&url=http%3a%2f%2f10.10.158.242%3a4040%2fECASLibrary002%2f%d8%b3%d8%ac%d9%84+%d8%b9%d9%85%d9%84+2019_DMA_00006+(1)%2f%d9%86%d9%85%d9%88%d8%b0%d8%ac+%d8%a7%d9%84%d8%b9%d8%b1%d8%b6+%d8%a7%d9%84%d8%aa%d9%82%d8%af%d9%8a%d9%85%d9%8a+%d9%84%d9%84%d9%85%d8%ac%d9%84%d8%b3+%d8%a7%d9%84%d8%aa%d9%86%d9%81%d9%8a%d8%b0%d9%8a.pptx&urlref=http%3a%2f%2f10.10.158.242%3a4040%2findex.aspx&dimension1=8e7449cd-ba1c-e611-80d2-0050568e7fa1&dimension2=External&dimension3=1cfc40ed-7b7f-e911-89cb-005056bb5a0e&dimension4=ec_workitem&download=http%3a%2f%2f10.10.158.242%3a4040%2fECASLibrary002%2f%d8%b3%d8%ac%d9%84+%d8%b9%d9%85%d9%84+2019_DMA_00006+(1)%2f%d9%86%d9%85%d9%88%d8%b0%d8%ac+%d8%a7%d9%84%d8%b9%d8%b1%d8%b6+%d8%a7%d9%84%d8%aa%d9%82%d8%af%d9%8a%d9%85%d9%8a+%d9%84%d9%84%d9%85%d8%ac%d9%84%d8%b3+%d8%a7%d9%84%d8%aa%d9%86%d9%81%d9%8a%d8%b0%d9%8a.pptx

**Comment by tsteur** [comment]
refs https://github.com/matomo-org/matomo/issues/9785 and https://github.com/matomo-org/matomo/issues/11136 

can you confirm all Matomo tables have  UTF8MB4?
