### ISSUE TITLE
core:purge-old-archive-data command: remove --force-optimize-tables option and always optimise tables

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14498]
Customer reported bug that running the command `./console core:purge-old-archive-data all` didn't save DB space. They also had to run ` ./console database:optimize-archive-tables all` afterwards.

Suggested steps:

* In the `core:purge-old-archive-data` console command, let's remove `--force-optimize-tables` option and always optimise tables
* ~~in `Db::optimizeTables` let's remove the second parameter `$force = false` and always force optimise tables (the code already checks `isOptimizeInnoDBSupported` which should be enough)~~ (not wanted actually)

**Comment by tsteur** [comment]
On Cloud we don't want to run always optimize. So this would need to be again a setting to disable this behaviour.

**Comment by mattab** [comment]
Ok, removed the second bullet point, but first one still valid (as per discussion)
