### ISSUE TITLE
Corrupt data after migration

### ISSUE THREAD

**Issue by nationalfonds** [matomo-org/matomo#14509]
# Description

A few months ago we migrated our Matomo instance from one server to another. After importing the data into the new system, we noticed that some of it had become corrupted. (See below)

As we suspected the error to be located in the cached data, we tried to regenerate it on the CLI using Matomo's **console** command. This fixed some of the corrupted data points with the side-effect that formerly correct data points became corrupted.

Is there maybe a bug in the command generating this data?

# Screenshots

## Wrong

![wrong](https://user-images.githubusercontent.com/51316610/58791522-a5b20d00-85f2-11e9-8703-da7d936cbf1c.png)

## Right

![right](https://user-images.githubusercontent.com/51316610/58791526-a8146700-85f2-11e9-9e9c-d6ea24edd08a.png)

# System summary

Component | Old Server | New Server
-- | -- | --
Matomo | 3.7.0 | 3.7.0
MySQL/MariaDB | 5.5.62 | 10.1.38
PHP | 5.6.39 | 7.0.33

Please feel free to ask for more information!

**Comment by tsteur** [comment]
Hi there,

we can't really help you here as it's hard to say what and how you migrated your data, what the data exactly looks like etc. I suggest you either ask this question in the forum: https://forum.matomo.org or check out our support plans where we can help you as well see https://matomo.org/support-plans/

If you find any specific bug in Matomo, feel free to create a new issue and if there's a way for us to reproduce it we may look into it. In general we don't answer questions here though or possible user errors during migration (best to try forum or contact our support).
