### ISSUE TITLE
A fatal error occurred

### ISSUE THREAD

**Issue by uhlhosting** [matomo-org/matomo#14500]
A fatal error occurred

The following error just broke Matomo (v3.9.1):

Variable "themeStyles" does not exist.
in /var/www/html/matomo/plugins/Morpheus/templates/layout.twig line 25    

```
A fatal error occurred

The following error just broke Matomo (v3.9.1):

Variable "themeStyles" does not exist.
in /var/www/html/matomo/plugins/Morpheus/templates/layout.twig line 25            
Troubleshooting

Follow these steps to solve the issue or report it to the team:
If you have just updated Matomo to the latest version, please try to restart your web server. This will clear the PHP opcache which may solve the problem.
If this is the first time you see this error, please try refresh the page.
If this error continues to happen, we appreciate if you send the error report to the Matomo team.
Further troubleshooting

If this error continues to happen, you may be able to fix this issue by disabling one or more of the Third-Party plugins. If you don't know which plugin is causing this error, we recommend to first disable any plugin not created by "Matomo" and not created by "InnoCraft". You can enable plugin again afterwards in the Plugins or Themes page under settings at any time.

BeeLikedDBIP | uninstall
-- | --
MarketingCampaignsReporting | uninstall
Signup | uninstall
WooCommerceAnalytics | uninstall



```

**Comment by Findus23** [comment]
Hi,

Can you please check if all Matomo files are complete and not corrupted? (e.g. via the integrity checker or by replacing them with the latest ones)

**Comment by uhlhosting** [comment]
@Findus23 found the issue, 2 .txt files did not had right permissions, its funny alto how this found in the end another resolution. I fixed the permissions and upgraded again it worked.

**Comment by lohic** [comment]
Hello,

@uhlhosting what are the 2 .txt files ? I have the same issue.

thank you

**Comment by uhlhosting** [comment]
@lohic you will have to check manually the permission. Do a shell basic script to check that for you, and just seek for any users outside the ones servicing matomo.
