### ISSUE TITLE
In Visitors > Real-time report, hide the calendar

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14517]
In Visitors > Real-time report, the report is real-time and it's not possible to change the date, so let's hide the calendar. This will be consistent with how it works on Visitors>Real-time map report.

![Screenshot from 2019-06-10 15-53-29](https://user-images.githubusercontent.com/466765/59171617-e9c78380-8b97-11e9-9846-cd40e3346892.png)

![Screenshot from 2019-06-10 15-53-22](https://user-images.githubusercontent.com/466765/59171619-eaf8b080-8b97-11e9-9d97-7ed7564bd7f6.png)

**Comment by tsteur** [comment]
This one might be tricky since it shouldn't be removed in Dashboard and the widget itself wouldn't know where it is displayed.
