### ISSUE TITLE
CustomReports plugin - Unable to move the location "Report SubCategory" once created

### ISSUE THREAD

**Issue by siva538** [matomo-org/matomo#14514]
Hi - 

When we create a customreport under a subcategory, there is no way we can bring the report back to the main category directly under the "Custom Reports" section, as the option of subcategory (drop down) is not filled with "blank".

Assuming someone created the report by mistake under a different subcategory, won't be able to bring that back to main menu of "Custom Reports".

Example:
Left side menu structure:

CustomReports:
          |____ Manage Reports
          |____ Report1

So if by mistake Report2 is created under "Report1" subcategory. No way we can bring it back under  "Custom Reports" section.

Expected (when updated):

CustomReports:
          |____ Manage Reports
          |____ Report1
          |____ Report2

Actual:

CustomReports:
          |____ Manage Reports
          |____ Report1
                        |____ Report2

And Report2 menu is not shown directly in the Left side menu.

Thanks in advance.

**Comment by sgiehl** [comment]
ping @tsteur

**Comment by tsteur** [comment]
Thx, this will be fixed in a new update very soon. If you have any other issues please email shop at innocraft . com

**Comment by siva538** [comment]
Amazing quick response. Thanks a lot for your help @tsteur  & @sgiehl
