### ISSUE TITLE
Handle "Got invalid response from API request" better

### ISSUE THREAD

**Issue by fdellwing** [matomo-org/matomo#14515]
We often have users on the forum that have some problem with the cron archiving.

Currently, the achiever tries to parse the response and fails. It then produces this two lines:

```
Jun 06 10:00:10 matomo matomo-console[871]: WARNING [2019-06-06 08:00:10] 871  /nix/store/5yq6hsmabykncchhxh44ay25nql87z4h-matomo-3.9.1/share/core/Common.php(271): Notice - unserialize(): Error at offset 0 of 295 bytes - Matomo 3.9.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
Jun 06 10:00:10 matomo matomo-console[871]: ERROR [2019-06-06 08:00:10] 871  Empty or invalid response 'Got invalid response from API request: https://matomo.matomo?module=API&method=API.get&idSite=1&period=day&date=last6&format=php&trigger=archivephp&token_auth=removed. Response was 'curl_exec: Could not resolve host: matomo.matomo. Hostname requested was: matomo.matomo'' for website id 1, Time elapsed: 0.307s, skipping
```

If you know where to look, you are easily able to find the reason for the error `curl_exec: Could not resolve host: matomo.matomo. Hostname requested was: matomo.matomo`. But for a user using this the first time, this is hard to spot.

Another example for such an error message would be:

```
a:2:{s:6:"result";s:5:"error";s:7:"message";s:427:"SQLSTATE[42000]: Syntax error or access violation: 1064 Routing query to backend failed. See the error log for further details. - in plugin Actions, caused by: SQLSTATE[42000]: Syntax error or access violation: 1064 Routing query to backend failed. See the error log for further details., caused by: SQLSTATE[42000]: Syntax error or access violation: 1064 Routing query to backend failed. See the error log for further details.";}
```

Again preceded by `ERROR [2019-03-19 14:58:46] 17845 Got invalid response from API request: ?module=API&method=API.get&idSite=52&period=day&date=last52&format=php&trigger=archivephp. Response was` and on most devices out of sight of the user to the right.

It would be better to really print out what the error was, even on a new line.

```
Jun 06 10:00:10 matomo matomo-console[871]: ERROR [2019-06-06 08:00:10] 871  Empty or invalid response 'Got invalid response from API request: https://matomo.matomo?module=API&method=API.get&idSite=1&period=day&date=last6&format=php&trigger=archivephp&token_auth=removed.

Response was 'curl_exec: Could not resolve host: matomo.matomo. Hostname requested was: matomo.matomo'

' for website id 1, Time elapsed: 0.307s, skipping
```

**Comment by Tealk** [comment]
i get the same error, how do i fix it?

**Comment by kwisatz** [comment]
In my case, the error is not easy to spot and the only way to find out what is causing it was by guessing, reading other issues in here (e.g. #15123) and checking out the mariadb error log.

Matomo itself doesn't give a clue (or the wrong clue entirely):
```
INFO [2020-01-19 01:36:09] 14513  Archived website id = 12, period = month, 0 segments, 17876 visits in last 52 months, 760 visits this month, Time elapsed: 1.658s                                            
INFO [2020-01-19 01:36:09] 14513  Will pre-process for website id = 12, period = year, date = last7                                                     
INFO [2020-01-19 01:36:09] 14513  - pre-processing all visits                                                                                                                                                   
ERROR [2020-01-19 01:36:32] 14513  Got invalid response from API request: ?module=API&method=API.get&idSite=12&period=year&date=last7&format=php&trigger=archivephp. The response was empty. This usually means a server error. A solution to this error is generally to increase the value of 'memory_limit' in your php.ini f
ile.  For more information and the error message please check in your PHP CLI error log file. As this core:archive command triggers PHP processes over the CLI, you can find where PHP CLI logs are stored by running this command: php -i | grep error_log
INFO [2020-01-19 01:36:32] 14513  Archived website id = 12, period = year, 0 segments, 0 visits in last 7 years, 0 visits this year, Time elapsed: 22.715s                                                     
INFO [2020-01-19 01:36:32] 14513  Archived website id = 12, 3 API requests, Time elapsed: 25.563s [9/11 done] 
```

It also did **not** write to the php-cli error log.

**Comment by tsteur** [comment]
@kwisatz Maybe check if your PHP ini settings if possible to see if you can enable more granular logging? It seems Matomo did not get any information from PHP so maybe it could be even a segfault or something. Have you checked the `matomo.log` in case it is enabled? 

See https://matomo.org/faq/troubleshooting/faq_115/
Where it says you can add a line like this to `config/config.ini.php`

```
[log]
log_writers[] = file
log_writers[] = screen
```

Not sure but it might also help to launch the archiver using `core:archive -vvv` in case you are using CLI archiving.

**Comment by mattab** [comment]
it's really valuable to make error reporting clearer and easier :+1: recently we've actually made a few small improvements to how errors are reported in `core:archive`, and now we will report the stack trace along with the error, and make error reporting cleaner, etc. if you're still finding it's not clear enough, please create a new issue with the error output and we'll look into it.
