### ISSUE TITLE
Page Name not defined

### ISSUE THREAD

**Issue by daylicron** [matomo-org/matomo#14512]
Hey there,

I'm running Matomo 3.9.1

I've found in the page title section the following line:
![image](https://user-images.githubusercontent.com/32066194/58937457-c73a0280-8772-11e9-8419-852d8708127d.png)

As a possible explanation I found https://matomo.org/faq/general/faq_74/ . So I grepped trough my access_log an searched for something without page title. As I understand the page title is the first string after the action name, so I looked for something like 
``
[...]action_name=&idsite=[...]
``

But I didn't find what I was looking for. So I tried to find something inside the database, but coldn't find anything.

I assume I'm running into something like https://stackoverflow.com/questions/22869190/piwik-page-name-not-defined

> Detected Site Search keyword 'ban'. NOTE: The Page URL was changed / removed, during the Site Search detection, was 'http://widgets.digitalmediacommunications.com/widget/embed/index/?p=903&k=ban', now is 'http://widgets.digitalmediacommunications.com/widget/embed/index/?p=903' Action is a SITE_SEARCH, Action name = ban, Action URL = http://widgets.digitalmediacommunications.com/widget/embed/index/?p=903
>I'm think that somehow my k=ban is triggering piwik site search feature. So when I turned off site search it worked! I will reviste this issue if I choose to work with site search someday.

Actually I would guess, that there are some page titles inside the database which are NULL, 0, or something like that. When I find them I should be able to trace back the url(s) which are causing this. I just don't know where to look for it.

Can someone help me out?

**Comment by tsteur** [comment]
@daylicron I reckon it is better you ask this question in the forum: https://forum.matomo.org 

We can't really know what is exactly happening here unfortunately. 

You might find some help there. In general we don't answer questions here. If you find a bug and can tell us steps to reproduce, we're happy to look into it or create another issue for it. You could also get in touch with our support if you're not finding any help in the forum: https://matomo.org/support-plans/
