### ISSUE TITLE
Is there anyway to add some properties on event?

### ISSUE THREAD

**Issue by xpader** [matomo-org/matomo#14519]
I use set page custom variables to log  properties on event, but is there any way to set properties on event formal?
And I see Custom Dimensions will replace Custom Variables, Is there anyway to support any custom properties on visit and action, because custom dimesions limit 5 names, hope save custom variables.

**Comment by sgiehl** [comment]
It is possible to use more than 5 custom dimensions. See https://matomo.org/faq/how-to/faq_21121/
