### ISSUE TITLE
If the collected data occurs at 2019-06-10 00:00:00, this information will be counted in 2019-06-09 and 2019-06-10

### ISSUE THREAD

**Issue by yhlin00001** [matomo-org/matomo#14525]
Hi, as subject.
  Is it a normal situation or bug issue for matomo?

**Comment by tsteur** [comment]
This shouldn't happen. Where exactly do you see this behaviour?

**Comment by yhlin00001** [comment]
It is real case!, our matomo has happened. our matomo is version 3.5.1.

we have had 3 records in 2019-04-06 00:00:00, we exported 2019-04-05 data included those 3 2019-04-06 00:00:00 records by matomo API, and we exported 2019-04-06 data included those 3 2019-04-06 00:00:00 records too.

**Comment by tsteur** [comment]
Which export API do you use exactly? If you use the Live API we may return the data for two days when requesting one day AFAIK. This may be on purpose. 

Also I recommend you update to the latest version to see if it is fixed. Otherwise we can't really look into it.

**Comment by mattab** [comment]
Thank you for the report :+1:  To likely fix the issue, could you upgrade to the latest Matomo version?
see https://matomo.org/docs/update/ 

if you still experience this issue afterwards, please re-open this and post a comment. Thanks!
