### ISSUE TITLE
option to disable fastcgi

### ISSUE THREAD

**Issue by Ludea** [matomo-org/matomo#14523]
Hi,
I know Matomo is based on FastCGI.
but , can we have an option to disable FastCGI ? 
I have a reverse proxy which doesn't handle this ([traefik](traefik.io)). 

I don't know if it need a lot of rework, but i could be interesting to support more reverse proxy.

**Comment by Findus23** [comment]
Hi,

Matomo isn't based on FastCGI (or any other PHP server implementation). You can set up your webserver and PHP however you want, as long as it is running PHP (and in case of a reverse proxy if it forwards the visitor IP correctly).
If you are using php-apache, FastCGI, Nginx, Lighttpd, Apache, Traefik or something else doesn't matter to Matomo.

**Comment by Ludea** [comment]
I see this from [docker hub](https://hub.docker.com/_/matomo)

> You'll now need to use a suitable reverse proxy to access the user interface; which is available on TCP port 9000. Nginx provides the necessary functions for translation between HTTP and FastCGI.

Traefik is not an http server, only a reverse proxy

**Comment by Findus23** [comment]
Please ask questions about the docker images here: https://github.com/matomo-org/docker

**Comment by LabN36** [comment]
is matomo run on port 9000 ?
