### ISSUE TITLE
Copy downloaded plugins from Marketplace to MATOMO_PLUGIN_DIRS folder too

### ISSUE THREAD

**Issue by nabiltntn** [matomo-org/matomo#14534]
Hi,
The new feature allowing different folders for plugins using the `MATOMO_PLUGIN_DIRS` env is great.

But is it possible to copy downloaded plugins from Marketplace UI also into declared directories in addition to Matomo `/plugins` folder.

Download logic copies extracted .zip file to '/plugins' folder and it's not using new `getPluginsDirectories` function

https://github.com/matomo-org/matomo/blob/6395855aa7f3813cc7f413a18d31505ea26ba32a/plugins/CorePluginsAdmin/PluginInstaller.php#L52

https://github.com/matomo-org/matomo/blob/6395855aa7f3813cc7f413a18d31505ea26ba32a/plugins/CorePluginsAdmin/PluginInstaller.php#L68

https://github.com/matomo-org/matomo/blob/6395855aa7f3813cc7f413a18d31505ea26ba32a/plugins/CorePluginsAdmin/PluginInstaller.php#L298

https://github.com/matomo-org/matomo/blob/6395855aa7f3813cc7f413a18d31505ea26ba32a/plugins/CorePluginsAdmin/PluginInstaller.php#L300

The goal is to easily "track" all the added/deleted plugins so creating new Matomo deployment becomes much easier.

This is useful with Kubernetes because i can define `MATOMO_PLUGIN_DIRS` folder to point to a Persistent Volume path shared between many PODs

**Comment by tsteur** [comment]
That would be a new feature. Cause you can configure multiple plugin directories, we wouldn't know where to copy it. We would need a setting for the plugin to be copied somewhere else. Feel free to create a PR for this.
