### ISSUE TITLE
Warning message: core/Plugin/Report.php(488): Warning - Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14547]
Seen in production on web.innocraft instance: `core/Plugin/Report.php(488): Warning - Illegal offset type in isset or empty`

What it looks like:
![Screenshot from 2019-06-20 15-13-32](https://user-images.githubusercontent.com/466765/59815852-0620a880-936e-11e9-9161-64e6694cc9d7.png)

**Comment by tsteur** [comment]
See chat yesterday, this was fixed by some other PR a while ago. Only happens for cohorts.
