### ISSUE TITLE
warning Piwik.php(122): Warning - A non-numeric value encountered

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14540]
WARNING: www/demo.piwik.org/core/Piwik.php(122): Warning - A non-numeric value encountered - Matomo 3.10.0-rc1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)

**Comment by fdellwing** [comment]
https://github.com/matomo-org/matomo/blob/4fc073e863c97bbb699213561d8d1c5c16c76792/core/Piwik.php#L120-L123

**Comment by mattab** [comment]
Again got the error on demo where it was displayed 10 times in a row... this may affect all users, not sur... Could we maybe add a silent fail in front of it? or throw an exception (may cause some feature of Matomo to fail)? @diosmosis @tsteur

**Comment by Findus23** [comment]
@mattab I already though a few times that it might be helpful to add an option that can be temporarily enabled (with a system check urging everyone to disable it again) that will display proper stack traces to all error messages. 

That would make debugging far easier as the whole error message people post isn't that helpful in many cases when the php error or warning just occurs in some helper function or in twig.

**Comment by tsteur** [comment]
It could also be just logged to the file. Such things aren't easy to troubleshoot etc. Best to move this to 3.11

**Comment by tsteur** [comment]
To find the root cause for these issues better we have changed the file log to include a trace in https://github.com/matomo-org/matomo/pull/14961
So when this issue happens again be good to get a trace and then we can maybe look into this further.

**Comment by romankk** [comment]
@mattab 
Keep getting 
`WARNING: /var/www/matomo/html/matomo/core/Piwik.php(122): Warning - A non-numeric value encountered - Matomo 3.12.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Goals, Action: getItemsName, In CLI mode: false)`

**Comment by tsteur** [comment]
Can you enable logging to file see https://matomo.org/faq/troubleshooting/faq_115/ and then maybe it will be logging a backtrace into the `$MATOMODIR/tmp/logs/matomo.log`.
Basically you need to add 
```
[log]
log_writers[] = screen
log_writers[] = file
```

to your `config/config.ini.php`

**Comment by SejlaG** [comment]
Hi all, 

Any updates on this issue? We keep seeing the error. 

It occurs 10 times in a row. Please see image. 
![image](https://user-images.githubusercontent.com/43573824/69805881-ee353680-11e1-11ea-8163-3b8729bdb8c0.png)

**Comment by mattab** [comment]
Reopening as the error shows up in 3.13.0
