### ISSUE TITLE
Call to undefined method Piwik\Plugin\Manager::getPluginDirectory() when upgrading from 3.5.1 to 3.9.1.

### ISSUE THREAD

**Issue by AnnoyingTechnology** [matomo-org/matomo#14552]
Hi, when trying to update from the web interface I encounter the following error

`Matomo encoutered an error: Call to undefined method Piwik\Plugin\Manager::getPluginDirectory() (which lead to: Circular dependency detected while trying to resolve entry 'Piwik\Twig')`

PHP : PHP 7.2.17-1+0~20190410151005.18+stretch~1.gbp23a36d
Server : nginx/1.15.11

**Comment by Findus23** [comment]
Hi,

This sounds a lot like https://github.com/matomo-org/matomo/issues/14250 which has been fixed in 3.9.1, but as the old code is still running during the update, you still saw it (see https://github.com/matomo-org/matomo/issues/14250#issuecomment-483585843)
