### ISSUE TITLE
Behaviour: forced reflows slow down browser rendering

### ISSUE THREAD

**Issue by TheBigfoot** [matomo-org/matomo#14554]
We are trying to display the behaviour tab in matomo, for having an overview over the last week of visits for a normal page (140k visitors in a week, 18 websites in total in this instance). 
Our server response arrives after 4.3 seconds, then the browser is ~16seconds busy with scripting and rendering.

Is there a possibility to speed this up?

I attached some network tools screenshots containing network graph and details for the performance views with breaking down the js functions.
![Selection_001](https://user-images.githubusercontent.com/746624/59928308-bfe74a00-943e-11e9-98cd-0c58270801c0.png)
![Selection_002](https://user-images.githubusercontent.com/746624/59928309-c07fe080-943e-11e9-874f-12053215e9da.png)
![Selection_003](https://user-images.githubusercontent.com/746624/59928310-c07fe080-943e-11e9-97dd-f7ad4612a551.png)
![Selection_004](https://user-images.githubusercontent.com/746624/59928312-c07fe080-943e-11e9-8738-6be56d71b3bf.png)

Our server configuration:
Matomo-Version: 3.9.1
MySQL-Version: 5.5.62
PHP-Version: 7.0.33
Database is hosted an a seperate server with SSD storage.

**Comment by tsteur** [comment]
What browser is that? How many rows are shown? 

We might have an issue for this already somewhere but can't find right now. We checked this last week with 5 or 10K rows and it was fine BTW (Chromium).

**Comment by TheBigfoot** [comment]
It is Chrome 75.0.3770.80-1 for Linux
I was also searching for an issue but couldn't find any matching to rendering times.

**Comment by Findus23** [comment]
Do you by chance use any browser extensions that do expensive calculations?
7 seconds is by far too much.

**Comment by tsteur** [comment]
Also let us know how many rows are shown (results, entries, ... in the report)

**Comment by TheBigfoot** [comment]
I tried with another Chrome instance with no plugins installed.
Rendering took the same time, but this matomo page is return 5900 rows.

**Comment by mattab** [comment]
Thank you for the report :+1:  To likely fix the issue, could you upgrade to the latest Matomo version?
see https://matomo.org/docs/update/ 
(this was improved a recent release)
if you still experience this issue afterwards, please re-open this and post a comment. Thanks!

**Comment by tomper00** [comment]
I have a very similar issue right now running Matomo version: 3.13.1
The interesting thing here is that I am the only user that have the problem.
The problem seems to follow me between browsers. 
I have logged out from Chrome and then tried to use Firefox and Safari and it is still slow.

**Comment by mattab** [comment]
@tomper00 Could you create a new issue and post some more details like the above screenshots? as this issue is already closed.
