### ISSUE TITLE
The class \Piwik\Plugins\ExamplePlugin\Updates_0_0_2 was not found in /var/www/plugins/ExamplePlugin/Updates/0.0.2.php

### ISSUE THREAD

**Issue by danielmorlock** [matomo-org/matomo#14555]
https://github.com/matomo-org/matomo/blob/2a4eebfd87bde157228037534e1fe93a2ed56e9b/plugins/ExamplePlugin/Updates/0.0.2.php#L10

The namespace seems to be invalid. We are running into the following exception when updating to Matomo 3.9.1:

```
  [Exception]                                                                                                             
  The class \Piwik\Plugins\ExamplePlugin\Updates_0_0_2 was not found in /var/www/plugins/ExamplePlugin/Updates/0.0.2.php  
```

`core:update` run properly when changing the namespace to `Piwik\Plugins\ExamplePlugin`.

**Comment by sgiehl** [comment]
Thanks for the report. You are right, the namespace should not include `Updates`. Will create a PR to fix that
