### ISSUE TITLE
inconsistent font sizes in links in Help page

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14563]
The links to the product review pages look bigger than other links on the page, and look bigger than what they look like in the popover. See the big links here:

![Screenshot from 2019-06-24 11-15-12](https://user-images.githubusercontent.com/466765/59983239-6a46b380-9671-11e9-9d1f-f3c11d5b06ac.png)

See it in the demo at: 
https://demo.matomo.org/index.php?module=Feedback&action=index&idSite=1&period=week&date=today

--> Ideally the blue links sizes are consistent and made smaller below the images.

**Comment by fdellwing** [comment]
With the PR the links are now consistently in size:

Non-popup: 16px → 13px
Popup: 12px → 13px
