### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by dvpfig** [matomo-org/matomo#14575]
I had a functioning website running on a CPANEL server with Wordpress and Matomo installed from Softaculous. 

Last week I started to get this error of "MySQL server has gone away" and I cannot find a workaround to fix it. 
I do not have access to "my.cnf" file to change timeout or other database configurations since they are not accessible via the File explorer in cpanel. 

The website has very little traffic, just a couple dozens visits per day and the database connected to Matomo is also rather small at 160MB. 

The visits are still tracked by Matomo but all the overview and graphs are not showing up and the wordpress admin site also gets stuck when trying to show the Matomo Visits graphs. 

Is there a way to fix this issue or do I need to reinstall Matomo? 

ERROR:
"... Backend fatal error: PHP Fatal error:  Uncaught Zend_Db_Statement_Mysqli_Exception: Mysqli prepare error: MySQL server has gone away in ..."

I do not have access to the solutions presented in FAQ: https://matomo.org/faq/troubleshooting/faq_183/

**Comment by tsteur** [comment]
Hi @dvpfig unfortunately we cannot provide support for specific server configurations here. I suggest you ask in the forum https://forum.matomo.org what you can do instead if there is anything. Cheers
