### ISSUE TITLE
Messing Goal stats in Actions

### ISSUE THREAD

**Issue by bobivass** [matomo-org/matomo#14572]
Hi,
I have a Goal named "Payable Link Clicked", which is triggered when "Click on a Link to an external website" matches some pattern.
For several days now, in Visitors/Visits log, as well as in Dashboard/Visits in Real-time, this Goal appears on top of the Actions of most of the visitors, with a different (old) date. Check the screenshot, please.
![image](https://user-images.githubusercontent.com/52205387/60254332-741d2080-98d6-11e9-873e-a765345fa75a.png)
As you can see the visitor log is from June 25, 2019, and the first action is "Payable Link Clicked", with the date Nov 23, 2018.
Can anyone help me with this bug?

**Comment by tsteur** [comment]
Are you using the latest version of Matomo? Can you try to convert this goal yourself and see if it shows the correct date afterwards?

**Comment by bobivass** [comment]
I'm using the latest version, I think - Matomo version: 3.9.1
What do you mean by "try to convert this goal yourself"?

**Comment by tsteur** [comment]
I meant could you trigger this goal, aka perform the steps needed so this goal is converted and appears in the visitor log. And then check the time. Or is this for all visits?

**Comment by bobivass** [comment]
![image](https://user-images.githubusercontent.com/52205387/60169138-d3176280-980e-11e9-8bf4-0ad46ed6b7d4.png)

It is for many of the visits. All Actions "Payable Link Clicked" (in red borders) are with the date Nov 25, 2018.

**Comment by tsteur** [comment]
We can't reproduce this here. Are you using any third party plugins (plugins that are not from Matomo, InnoCraft / premium feature)? What timezone is your site set to (you can see in Administration => Sites => Manage)?

We might need access to your database to have an idea how this happens, would that be possible?

**Comment by bobivass** [comment]
No, I'm not using any third party plugins.
TIME ZONE: Bulgaria
Yes, it is possible. What do you need for this, and where to send it?

**Comment by tsteur** [comment]
You could send us an email with credentials to hello at matomo.org.

**Comment by bobivass** [comment]
Credentials just sent.

**Comment by tsteur** [comment]
Tracked values seem to be stored correctly. Might be a server issue or something in our code. @sgiehl do you remember any changes on this recently maybe?

@bobivass did this only start recently? Have you changed anything on the server maybe?

**Comment by tsteur** [comment]
Thanks for your recent email.
There is definitely something wrong see 
`<serverTimePretty>Nov 26, 2018 18:23:00</serverTimePretty><timestamp>1543256580</timestamp>` for a goal, 

and `<serverTimePretty>Jun 27, 2019 10:40:59</serverTimePretty><timestamp>1561632059</timestamp>` for a regular action.

Interestingly there is actually a wrong date tracked for this visit:
![image](https://user-images.githubusercontent.com/273120/60250414-e4bc4100-98c6-11e9-88d9-13703797a4be.png)

So maybe it's a problem with the tracking code or so. Do you use the JavaScript tracker @bobivass ? It's a bit funny it works for some, but broken for some others. Do you customise the tracker in any way?

**Comment by tsteur** [comment]
Also have you adjusted any configs in `config/config.ini.php`? For example to increase the visit time?

**Comment by tsteur** [comment]
FYI: For this visitor the first action time is `2019-06-27 07:40:59` and last action time is `2019-06-27 08:28:55` so seems all normal.

**Comment by bobivass** [comment]
The only thing I added in `config/config.ini.php` is `force_ssl = 1`

I'm using JS tracker, but I'm using it since I installed Matomo, and there was no problem. The issue started on June 21, 2019.
Here is the tracking code I have:
`
<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
window.addEventListener('load', function() {
    var u="https://www.mysite.com/st/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src='https://www.mysite.com/st/piwik.js'; s.parentNode.insertBefore(g,s);
  });
</script>
`

**Comment by tsteur** [comment]
In theory recording a token > 1 day would actually require a token so not quite sure how this happens.  Do you have multiple servers maybe and one server randomly has a wrong date set?

**Comment by bobivass** [comment]
No, just one server.

**Comment by tsteur** [comment]
@Findus23  maybe any thoughts how this could happen? Seems like `time()` randomly returns a different value which doesn't seem possible. Haven't heard anything like it before so suspecting some server issue as code for these things seems quite straight forward.

**Comment by bobivass** [comment]
Not sure if it is related to this issue, but on May 20, 2019, I had a database problem, here is the error message I got:
`SQLSTATE[42S02]: Base table or view not found: 1932 Table 'thumbsy_matomo.matomo_log_visit' doesn't exist in engine`
This table was corrupted and my hosting support repaired it.

**Comment by bobivass** [comment]
@tsteur today I got this error:
`SQLSTATE[HY000]: General error: 1114 The table 'matomo_archive_numeric_2019_07' is full`

**Comment by bobivass** [comment]
Hi, @tsteur I still have this problem. Any ideas what causes this and how to fix it?

**Comment by tsteur** [comment]
Sorry no idea. I suggest you ask in the forums: https://forum.matomo.org

I searched for `1932 Table doesn't exist in engine` and there might be some solutions coming up. Give it a try maybe

**Comment by bobivass** [comment]
@tsteur I have new findings. Please, check this:

![image](https://user-images.githubusercontent.com/52205387/64263161-e1cd7480-cf37-11e9-8504-f14df70b5f61.png)

There are the same idvisit for two completely different dates - 2019-05-26 and 2019-09-04. I hope this will help your team to discover the problem.

**Comment by tsteur** [comment]
thanks for the screenshot @bobivass I've noticed this in the past as well yet cannot explain how this can possibly happen. I'm really at the end of my wisdom here. I'm hoping someone else has an idea

**Comment by bobivass** [comment]
Thank you @tsteur for your efforts, I appreciate them.
Finally, I found the problem and fixed it.
After repairing the `matomo_log_visit` table, the auto-increment of the` idvisit` column started from 0. But there are the same `idvisits` in the table `matomo_log_link_visit_action` already.
So, I run this sql line:
`ALTER TABLE matomo_log_visit AUTO_INCREMENT=N`
Where the `N` is the last value of the `idvisits` column in `matomo_log_link_visit_action`.

**Comment by tsteur** [comment]
That explains it. Thanks for letting us know 👍 Would have never thought of this.
