### ISSUE TITLE
resetUserId in android/ios

### ISSUE THREAD

**Issue by JeyakumarThangaraj** [matomo-org/matomo#14573]
Dear Team,

We have integrated Android/ Ios SDK. and tracking seems working. but we dont find anyway to resetuserid in android/ios while logging out. Kindly advise,

Thanks.

**Comment by tsteur** [comment]
Hi @JeyakumarThangaraj could you create these issues on https://github.com/matomo-org/matomo-sdk-android and https://github.com/matomo-org/matomo-sdk-ios ? Make sure to check the docs or code if it's there or not.
