### ISSUE TITLE
JS Tracker: add rtf to list of downloads

### ISSUE THREAD

**Issue by jaapvandeputte** [matomo-org/matomo#14579]
Hi there,

I'm new here so sorry when I'm mistaken in any etiquette.

I have a little question: is it possible Matomo as default adds rtf to the list of downloads? I know I can add this with a line of javascript, but it's a bit easier when that is already there.

**Comment by jaapvandeputte** [comment]
And docx, xlsx and pptx too, as they are often used?

**Comment by sgiehl** [comment]
you can see the full list here: https://github.com/matomo-org/matomo/blob/7a93a2b5ff683e7bb27339502a60c00add9fe26e/js/piwik.js#L3065
It already includes `docx, pptx, xlsx`. Feel free to create a PR to add `rtf` to that list.

**Comment by jaapvandeputte** [comment]
@sgielh: thanks, I have been using an old list. Good to hear that `docx pptx xlsx` are on the list. Can you please explain what an PO is and how I can create this?

**Comment by sgiehl** [comment]
@jaapvandeputte I meant opening a Pull Request here on github

**Comment by mattab** [comment]
@jaapvandeputte please see how to do this in: https://developer.matomo.org/guides/contributing-to-piwik-core#contribution-process
