### ISSUE TITLE
Random failing integration test: 1) Piwik\Plugins\SEO\tests\Integration\SEOTest::test_API google-index expected non-zero rank, got [0]

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14577]
There is a regularly randomly failing integration test:

```
1) Piwik\Plugins\SEO\tests\Integration\SEOTest::test_API
google-index expected non-zero rank, got [0]
Failed asserting that a integer is not empty.
/home/travis/build/matomo-org/matomo/plugins/SEO/tests/Integration/SEOTest.php:61

```
seen for example in https://travis-ci.org/matomo-org/matomo/jobs/550650396

is there maybe a way to avoid this random failure? (maybe it would help to re-try after 10 seconds when it fails, but probably won't be enough to fix the issue)

**Comment by Findus23** [comment]
Investigating this was already on my todo, but I wouldn't be surprised if this is just the fact that the Google SEO integration is basically broken: https://github.com/matomo-org/matomo/issues/12248

**Comment by Findus23** [comment]
I guess the best "solution" would just be ignoring that test and making it not fail the whole build.
