### ISSUE TITLE
strlen() expects parameter 1 to be string, array given in strlen called at /core/Tracker/Request.php 

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#14580]
Saw this on a Matomo server

```
E_WARNING: strlen() expects parameter 1 to be string, array given
in strlen called at /core/Tracker/Request.php (629)
in Piwik\Tracker\Request::getCustomVariables called at /core/Tracker/Action.php (183)
in Piwik\Tracker\Action::getCustomVariables called at /plugins/CustomVariables/Tracker/CustomVariablesRequestProcessor.php (76)
in Piwik\Plugins\CustomVariables\Tracker\CustomVariablesRequestProcessor::afterRequestProcessed called at /core/Tracker/Visit.php (152)
in Piwik\Tracker\Visit::handle called at /core/Tracker.php (138)
in Piwik\Tracker::trackRequest called at /plugins/BulkTracking/Tracker/Handler.php (56)
```

**Comment by nitesh-kumar-verma-nile** [comment]
Fatal error: Uncaught TypeError: strlen(): Argument #1 ($string) must be of type string, array given in /home/clients/8ec632cac2800371701e3fac27f83091/sites/dev.pop-fiit.com/vendor/ralouphie/getallheaders/.eda8f040.inc(62) : eval()'d code:4 Stack trace: #0 /home/clients/8ec632cac2800371701e3fac27f83091/sites/dev.pop-fiit.com/vendor/ralouphie/getallheaders/.eda8f040.inc(62) : eval()'d code(4): jgxtbopx(Array) #1 /home/clients/8ec632cac2800371701e3fac27f83091/sites/dev.pop-fiit.com/vendor/ralouphie/getallheaders/.eda8f040.inc(62): eval() #2 /home/clients/8ec632cac2800371701e3fac27f83091/sites/dev.pop-fiit.com/public/index.php(4): include('/home/clients/8...') #3 {main} thrown in /home/clients/8ec632cac2800371701e3fac27f83091/sites/dev.pop-fiit.com/vendor/ralouphie/getallheaders/.eda8f040.inc(62) : eval()'d code on line 4

**Comment by heurteph-ei** [comment]
@nitesh-kumar-verma-nile 
It seems this has no relation with Matomo, but with `ralouphie` application...
