### ISSUE TITLE
WARNING: Trying to add two strings in DataTable\Row::sumRowArray

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14588]
Maybe related to A/B testing but got this warning 20 times on the demo:
```
WARNING: Trying to add two strings in DataTable\Row::sumRowArray: 
7.4% + 5.5% for column avg_nb_conversions_goal_7 in row
 # ['label' =&gt; 'Total', 'nb_visits' =&gt; 668, 'nb_visits_entered' =&gt; 568, 
'nb_uniq_visitors' =&gt; , 'avg_nb_conversions_goal_7' =&gt; '7.4%'] 
['segment' =&gt; 'abtesting_experiment==AffiliateLinkEffectiveness,abtesting_variation==original'] 
[idsubtable = ]&lt;br /&gt; 
```

**Comment by tsteur** [comment]
@diosmosis I can't reproduce this on a regular site when using A/B testing. This might be related to SiteProxy somehow?

**Comment by diosmosis** [comment]
Yes, it's probably related to ProxySite, though not exactly sure how.

**Comment by tsteur** [comment]
To find the root cause for these issues better we have changed the file log to include a trace in https://github.com/matomo-org/matomo/pull/14961
So when this issue happens again be good to get a trace and then we can maybe look into this further.

**Comment by mattab** [comment]
Reckon it's been fixed in the meantime

**Comment by jonathonbyrdziak** [comment]
I have this bug cropping up on my server. I can give you access to have a look if you'd like. Seems that it's happening with a custom report that I created.

**Comment by justinvelluppillai** [comment]
@jonathonbyrdziak what version of Matomo are you using?
