### ISSUE TITLE
disableHeartBeatTimer doesn't really removes event listeners

### ISSUE THREAD

**Issue by IIIEII** [matomo-org/matomo#14586]
In piwik.js:
[setUpHeartBeat](https://github.com/matomo-org/matomo/blob/3ab69975f682acc733e1bd5f561a98ca6fe0683a/js/piwik.js#L3730)() attaches to 'focus' and 'blur' window events without capture:
```
addEventListener(windowAlias, 'focus', heartBeatOnFocus);
addEventListener(windowAlias, 'blur', heartBeatOnBlur);
```
But [disableHeartBeatTimer](https://github.com/matomo-org/matomo/blob/3ab69975f682acc733e1bd5f561a98ca6fe0683a/js/piwik.js#L6849)() removes those events with capture (third parameter):
```
windowAlias.removeEventListener('focus', heartBeatOnFocus, true);
windowAlias.removeEventListener('blur', heartBeatOnBlur, true);
```
So event listeners are not really removed and script continue to send ping requests.

**Comment by tsteur** [comment]
Thanks, that should be an easy fix.
