### ISSUE TITLE
Show button "Open Visit Log" in report

### ISSUE THREAD

**Issue by phips28** [matomo-org/matomo#14582]
Hello,

I am currently coding a custom report and need a little help from the community :)

As you can see in the screenshot I print a table of visits (which match some criteria)

![image](https://user-images.githubusercontent.com/3694800/60296054-82def400-9925-11e9-8cce-cfcccdf168c3.png)

In the row I want to add the button "Open Visit Log" to open the session with `idVisit` & `visitorId`.

![from page urls page](https://user-images.githubusercontent.com/3694800/60294708-478ef600-9922-11e9-8c16-27fc8f8ad83e.png)

Is that possible? 
I couldn't find any docs or code example in existing reports how to add this button.

I dont have a custom render() function or something like that. It's just a DataTable with some simple arrays in it and it gets generated automatically.

And another question: how can I tell the report that VISITOR_ID is a string, not an integer. It gets auto-formatted.

Thank you!

**Comment by tsteur** [comment]
Hi @phips28 I recommend you ask this in our developer forum: https://forum.matomo.org/c/plugins-platform We don't answer any such questions here. You would basically need to add some metadata to each row called `segment` that contains the correct segment definition.
