### ISSUE TITLE
French translation typo

### ISSUE THREAD

**Issue by JackNUMBER** [matomo-org/matomo#14607]
On the fresh Matomo update the first feedback opening has some typo ([fr.json](https://github.com/matomo-org/matomo/blob/e8a67a8e1612d025acfcc9deb563bcb803e3ef69/plugins/Feedback/lang/fr.json#L33)).
After a quick search there is other typo in translations files

![image](https://user-images.githubusercontent.com/2306550/60471297-65cb5d80-9c64-11e9-9403-b43566d6f382.png)

In [fr.sjon](https://github.com/matomo-org/matomo/blob/master/plugins/Feedback/lang/fr.json):
>**ReviewMatomoTitle**
> Vous coryez en Matomo?
> Vous croyez en Matomo ?

>**TopLinkTooltip**
>Dites nous ce que vous en pensez [...]
>Dites-nous ce que vous en pensez [...]

>**RateFeatureLeaveMessageDislike**
>[...] N'hésitez pas à nous dire comme nous pouvons améliorer.
>[...] N'hésitez pas à nous dire comment nous pouvons l'améliorer.

And many others punctuation or typing mistakes.
I'll try to check some files to fix some one.

**Comment by sgiehl** [comment]
I've updated those changes manually on transifex.
