### ISSUE TITLE
Web keywords on Google - Sort by impressions doesn't work - Matomo 3.10

### ISSUE THREAD

**Issue by robles-design** [matomo-org/matomo#14603]
Hi,

I noticed that in the last version and after an update to Matomo 3.10.0 it doesn't work either.

Aquisitions > search engines and web keywords > web keywords on Google
Click on impressions to sort the impressions descending doesn't sort it the right way (see screenshot).

Matomo-Version: 3.10.0
MySQL-Version: 5.7.26-nmm1-log
PHP-Version: 7.3.6-nmm1

Thanks and best regards
Robert
![Screenshot_20190701_152402-sortbyimpressions](https://user-images.githubusercontent.com/25033650/60440942-3f7ed100-9c16-11e9-8956-4b841ae41bd2.png)

**Comment by sgiehl** [comment]
Thanks for the report. I'm able to reproduce that. We will try to fix that in the next release of the plugin.

**Comment by robles-design** [comment]
Great. Thank you!
