### ISSUE TITLE
No longer refreshes automatically in pinned tabs

### ISSUE THREAD

**Issue by CyrilBrulebois** [matomo-org/matomo#14611]
I've just upgraded from 3.9 to 3.10 and here's a big regression for my use case: I keep a few pinned tabs in my Firefox (Calendar, Matomo, Twitter) to make sure they're kept open all the time, and the Matomo tab was previously getting refreshed automatically upon new visits (real-time visits widget). With the upgrade to 3.10, that no longer happens, and forcing a refresh gets me back to the login page. This doesn't seem to have been triggered by any other changes on the machine hosting this Matomo instance.

Browser: Firefox ESR 60.7.1esr (64-bit).

**Comment by tsteur** [comment]
This is actually expected behaviour as otherwise Matomo server's are being pinged without anyone ever viewing it. You could either select "remember me" or could try a plugin like https://plugins.matomo.org/LiveTab which would very likely to the same in keeping your session active.

**Comment by CyrilBrulebois** [comment]
I think keeping the tab around was a way of expressing “I want this to be updated and I'll look whenever I want”, but I also reckon that the simple solution you proposed is rather reasonable (even if that wasn't required before). Ticking “Remember me” seems to be sufficient to get the old, ever-refreshing behaviour back.

Thanks for your swift feedback.
