### ISSUE TITLE
Make it easy to search Matomo.org user guides and FAQs within the app

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14626]
The goal of this issue is to make it very easy and obvious for users to search through our great Matomo.org resources (user guides, FAQs) directly from within the app. While keeping it very simple for us to implement. 

Suggested places where people can access Matomo.org search:

* When clicking on the Help icon, the Help page opens, and at the top of this Help page, we'd display a big search field. 
* When searching in the "Awesome search" field (at the top of the left menu), a new dropdown element would appear at the bottom.

## Help page design

At the top of [our Help page](https://demo.matomo.org/index.php?module=Feedback&action=index&idSite=1&period=week&date=today), above the "About Matomo 3.10.0" block, we would:

*  add a new block "How can we help?" with below a big search field. The search field would show a grey text like "Search Matomo.org help resources" or so. 
* add a link to `Browser all user guides` and to `Browse all FAQs`

It could look like Slack help page:

![Screenshot from 2019-07-03 17-10-16](https://user-images.githubusercontent.com/466765/60691000-35afe300-9f20-11e9-9cd6-f3b9b75066d0.png)

(we probably don't need the "Popular help topics" section for now)

## Awesome menu

When any term is entered in the awesome menu, the dropdown would include a new element, at the very bottom, called eg `Help resources`, with a sub-item called eg. `Search KEYWORD_HERE on Matomo.org`

Example suggested mockup:
![Screenshot from 2019-07-05 12-31-53](https://user-images.githubusercontent.com/466765/60691072-ffbf2e80-9f20-11e9-84b7-2ae3fef7143d.png)

## Behaviour

In both cases, when people enter a search term, and click the button or link, a new tab would open in their browsers, and open the Matomo.org search result page. For example if you search for `custom dimension` it would open: https://matomo.org/?s=custom+dimension

We don't want to include the help resources within the app because it is too much work to implement. Rather we want to do the easiest solution that will still provide great value to users when they need help.

As always, thoughts/suggestions welcome!

**Comment by atom-box** [comment]
_(User feedback)_

Feature:
Like: No
Choice: makeeasier
Feedback:
Open learn more links in new tab. Otherwise I lose my settings...
Source: On-Premise
