### ISSUE TITLE
'secondaryDimension' isn't set in the Request

### ISSUE THREAD

**Issue by hebbet** [matomo-org/matomo#14621]
After upgrading from 3.9.0 to 3.10.0 i get the folllowing error, when i click on "row evolution" in "behavoir" > "Events"
![image](https://user-images.githubusercontent.com/1423115/60587097-e2a92500-9d93-11e9-8c30-610f5a7a6e50.png)

Error: The parameter 'secondaryDimension' isn't set in the Request, and a default value wasn't provided.

System info: 
php 7.2
mysql 10.1
apache 2.4

**Comment by SejlaG** [comment]
Hi, 

We are experiencing the same issue after upgrading to 3.10.0

Best Seki

**Comment by tsteur** [comment]
Thanks for reporting this, I can reproduce it 👍

**Comment by xpader** [comment]
What time can fixed it? Now all the Row Evolution show the same error..
