### ISSUE TITLE
Tour.getEngagement is called on every page load

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#14648]
The Tour.getEngagement API method is called on every page load (including modals) even if there is no tour widget visible. Shouldn't need to call it this often, instead it should only be used if there's a tour widget visible.

**Comment by tsteur** [comment]
@diosmosis there is no such API. I suppose you mean a different API?

**Comment by diosmosis** [comment]
@tsteur in `plugins/Tour/javascripts/engagement.js` there's an AJAX call to `Tour.getEngagement` (though it looks like it could be a controller method?). That's what I was seeing.

**Comment by tsteur** [comment]
Didn't look too much into it but I reckon this is only once the dashboard was opened and it contains the default dashboard. And it should only do it after the window was focused again (like moved to another tab and then back). Might not be big of an issue but ideally definitely should be only executed when we're on the dashboard and when the widget is on the dashboard.

**Comment by sgiehl** [comment]
https://github.com/matomo-org/matomo/blob/b3555e1f1efcbb63158e6c116e1fb5c8805851f8/plugins/Tour/templates/engagement.twig#L52-L54

That event isn't actually unloaded when switching the page. So it's executed on every page once the dashboard was loaded with the widget.
