### ISSUE TITLE
can't set customVariableMaximumLength

### ISSUE THREAD

**Issue by confirmTing** [matomo-org/matomo#14650]
my `_cvar` is to long, i want set customVariableMaximumLength to 500, but not found some method.

**Comment by tsteur** [comment]
Hi @confirmTing thanks for creating the feature request. It is hard coded to 200 and it's unlikely we are going to change this as we will deprecate Custom Variables in Matomo 4 see https://github.com/matomo-org/matomo/issues/11524 

I will close this issue therefore. Could you check if custom dimension works maybe better for you? https://plugins.matomo.org/CustomDimensions I don't know the limit there right now unfortunately.

**Comment by confirmTing** [comment]
@tsteui ths
