### ISSUE TITLE
Matomo (Piwik) core JS file fails to execute under new Content Security Policy

### ISSUE THREAD

**Issue by ash-j-f** [matomo-org/matomo#14653]
Although the Matomo maintainers claim it works under the strictest CSP settings, it fails to execute on all major browsers. The error is "blocked by client" as expected when a script is blocked by CSP.

The Matomo JS file appears to contain a call to create and embed a new script in the DOM, which is one possible thing violating the CS.

The CSP settings are:
```
<meta http-equiv=\"Content-Security-Policy\" content=\"frame-src 'self'; script-src 'self' https://www.google.com/ https://www.gstatic.com/ \" />
```

Matomo's claim to work under strict CSP is here:
https://matomo.org/faq/general/faq_20904/

I have implemented the loading of the JS file in the way they suggest.

**Comment by ash-j-f** [comment]
Woops wrong repo, sorry :D

**Comment by ash-j-f** [comment]
In case anyone comes across this ticket, the issue we were having was ad blocker plugins in all the test browsers were blocking Matomo from running, and we were getting errors such as "net::ERR_BLOCKED_BY_CLIENT" in Chrome. Disabling the ad blocker plugins of course allowed Matomo to run, and it now works even with our very strict Content Security Policy enabled.

**Comment by tsteur** [comment]
👍
