### ISSUE TITLE
Natomo.js never sends anything

### ISSUE THREAD

**Issue by vitaminwater** [matomo-org/matomo#14654]
Everything went smoothly, and everything seems to load without errors.
But nothing is tracked, and when looking at the browser's network activity, I can see matomo.js loaded successfully, but there no requests done for tracking.

I went through this: https://matomo.org/faq/troubleshooting/faq_58/

Also checked the matomo_log_visit table, which is empty.

**Comment by Findus23** [comment]
Hi, first of all: Troubleshooting like this can be done far easier on the forum (https://forum.matomo.org/) as we try to keep this issue tracker for a list of reproducable bugs in Matomo.

That said, I'd recommend you to check if you might have enabled DoNotTrack in your browser or if there is maybe some browser extension that is blocking the request.
