### ISSUE TITLE
Social networks report does not show names of networks until after any settings change

### ISSUE THREAD

**Issue by mskala** [matomo-org/matomo#14651]
When I first visit the "Social networks" report, it does not show the names and icons of the networks:

![Screenshot_2019-07-11_10-57-56](https://user-images.githubusercontent.com/1533051/61061897-266ee080-a3cb-11e9-8827-d0fe0e475cba.png)

If I change any settings using the hidden gear icon, for instance by switching to hierarchical mode and back, then the names and icons appear:

![Screenshot_2019-07-11_10-58-20](https://user-images.githubusercontent.com/1533051/61061983-4f8f7100-a3cb-11e9-83db-2fc69fa0db90.png)

It is not a specific value of the settings that causes the problem - the problem happens regardless of what the original settings were, and it goes away on any _change_ in settings, even changing back to where they began.  Changing the date range causes it to reset; the names disappear. 

Clicking on "Row evolution" for a network with its name missing produces a pop-up with the error "Error: Expected label to be an array, got instead: " (nothing visible after the colon).  Row evolution works normally after a settings change causes the network names to appear.

The problem seems specific to the "Social networks" page; I haven't seen something similar on other pages, though there may be some that I haven't had occasion to visit.

It has existed for at least a few months; I kept hoping that the next Matomo upgrade would fix it, but so far no such luck.

**Comment by mattab** [comment]
Thanks for the report @mskala - so far we haven't heard or seen this bug in Matomo. Are you using any browser extension, do you get the same issue across different browsers and devices?

**Comment by mskala** [comment]
Symptoms are the same in Firefox and Pale Moon under Linux, and in Internet Explorer under Windows 10.  My Firefox has AdBlocker Ultimate and NoScript but my Matomo installation is supposed to be whitelisted in both of them; and the other two browsers are unextended.

**Comment by sgiehl** [comment]
@mskala Do you still have this issue with latest 3.12.0 ?

**Comment by mskala** [comment]
Yes, it's still present for me in 3.12.0.

**Comment by mattab** [comment]
@mskala Can you reproduce this issue on https://demo.matomo.org?  unfortunately we're unable to reproduce this issue so far

**Comment by mskala** [comment]
No, it doesn't happen on the demo stie.  Still happens on my own site in 3.13.1.

**Comment by mskala** [comment]
This is still a problem in 4.0.0.  I don't understand what "feedback" you're waiting for.

**Comment by sgiehl** [comment]
@mskala I'm still not able to reproduce that locally, so it's hard to find a possible reason. 
Which browser are you having this issue with? Can you maybe see any error in the browser console.
Could you maybe give us access to you Matomo instance so we can have a look there? Feel free to send use the credentials to support@matomo.org and mention this issue in the email.

**Comment by mskala** [comment]
As mentioned, this happens in every browser I have tried.  My main browser at the moment is Firefox Developer Edition 67.0b16 (64-bit) under Linux, but it's also been a problem in several other versions of Firefox, Pale Moon, and Internet Explorer on multiple Linux and Windows machines.  I don't have a Chrome installation to check with.

I tried creating an account just now, intending it for sharing with you, but I wasn't able to reproduce the problem in the second account.  I went through giving the new account a number of different settings and access levels (including superuser) and it consistently worked in the new account and didn't work in my old account.  If I can get the problem to reproduce in an unprivileged account I'll share that with you but it doesn't look good at the moment.

That does suggest that maybe there's something uniquely screwed up about my own user account, which has been part of my system since I first installed Piwik - and it was Piwik at the time - many versions and several years ago.  Maybe I can just delete and re-create my own account and resolve the problem that way.  Is there any important reason I shouldn't go that route?  If that works, it leaves the original cause of the issue unknown and unfixed, but it would at least resolve my own problem.

The browser console produces many warnings about invalid CSS on every Matomo page load, but nothing obviously different between cases where this issue shows up and cases where it doesn't, and nothing that looks like an error affecting Javascript execution.  I can dig into copying out the entire list of errors for each case if that's useful, but I won't have time to do that instantly.  Something similar that occurred to me would be to just capture and diff the HTML; from "inspect element" it looks to me like the missing elements are actually not present in the generated HTML at all, not just being hidden by CSS.

**Comment by sgiehl** [comment]
@mskala thanks for the additional infos.

Could you please have a look at your database and look up the option value in the table `matomo_option` with the option name `viewDataTableParameters_login_Referrers.getSocials` (login needs to be replaced with your login).
If it exists you could try if removing that record changes anything

**Comment by ghost** [comment]
Thank you, this SQL command seems to have resolved the problem with social network names not displaying.

```
delete from piwik_option where option_name = 'viewDataTableParameters_mskala_Referrers.getSocials';
```

Current-day archive reports stopped working when I did that; after waiting for the cron job to run a couple of times and seeing that it still didn't update them, I ran the console command described at https://matomo.org/faq/how-to/faq_155/ to invalidate recent reports.  This produced several pages of "LOAD DATA INFILE failed... Error was: 
  Try #1: LOAD DATA INFILE : SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'piwik'@'localhost' (using password: YES)[28000]" messages.

While I was trying to figure out how to resolve that, the cron job ran again and regenerated the reports, so the LOAD DATA INFILE error evidently was not fatal.
