### ISSUE TITLE
Features are available only through secret mouseover icons (and hard to access on mobile)

### ISSUE THREAD

**Issue by ghost** [matomo-org/matomo#14652]
Many reports have important features - such as the switch that controls which style of report to display - accessible only through icons that are hidden except during mouse-over.  This makes the features nearly impossible to discover without being told out-of-band of their existence.  It's especially a problem on some phone and tablet interfaces where users may not be able to move the "mouse" pointer without registering a click.

On this screen, the green icons for configuring the style of the report only appear when the mouse pointer is within the white rectangle containing the report.  The "help" and "thumbs up" icons next to the title "Social Networks" appear only when the mouse pointer is in that rectangle and on about the same horizontal level as the title.  The "thumbs down" icon is especially evil:  it does not appear until the mouse is _hovering over the "thumbs up" icon_.  There are also per-row icons for things like "row evolution" which will only appear with the mouse over the row in question.

![Screenshot_2019-07-11_11-17-40](https://user-images.githubusercontent.com/1533051/61063716-6f746400-a3ce-11e9-87eb-0e6c5e0a5f69.png)

There is no legitimate reason for these icons to ever be hidden at all, and they shouldn't ever be hidden.  But at the very least, the config icons at the bottom should not be hidden.  They appear in what otherwise looks like unused visual space and there's no reason for someone to expect icons in that location unless previously told about their existence.  They are easy to miss.  The others at least can be argued to be relevant to specific items and located near those items in places users might expect to look - although such an argument is weak.

**Comment by tsteur** [comment]
Thanks for the feedback @mskala 

We quite like a clean UI as if we were to show all the icons all the time it would be quite bloated/messy. Eg the thumbs up/down it's totally fine if people only discover this by accident / experience for us as they aren't too important. This is different though for some other features. For the mobile version we could definitely improve this though and eventually show more icons without needing to hover.

**Comment by mskala** [comment]
A blank white page with nothing on it would be even more "clean."  I prefer a usable UI.

**Comment by atom-box** [comment]
A user comment about the green icons which appear during mouseover:

>The single most annoying thing about Matomo is that controls are invisible until the mouse hovers over their area.

> The user needs to use the mouse like a torch in a dungeon to figure out how to do anything. This is a **terrible** design trope that unfortunately is all too common.
> 
> At most - if at all - this hiding of controls should be done only when it is important to keep a central view clear (keeping in mind that Matomo doesn't have a central view), and then only if the location of controls is immediately obvious at all times. This is almost never the case for professional or statistical tools like Matomo, so it should not be done in Matomo all.
> 
> 
> With that out of the way, thank you for an absolutely wonderful utility and keep up the great work!
>

**Comment by Stan-vw** [comment]
The current ticket is quite broadly stating that "important controls are hidden until mouse-over". Is the issue specifically limited to:
- change report
- per-row icons for things like "row evolution"
- help
- thumbs up/down
or are there other (important) controls that are not visible until mouse-over?

The main reason I'm asking is that I'm not sure if there's a way to quickly find all actions that have conditional show, but to properly redesign any/all of them it'd be very helpful to know the full list. Particularly if they can be bulk-adjusted, in which case there is a risk of making a subset unusable without knowing it.

Thanks in advance for elaborating.

**Comment by mattab** [comment]
Thanks for creating this issue! We appreciate your input. This issue covers a lot of ground, and it's a bit too broad for us to tackle effectively as is. So, we're going to close it for now.

But don't let this stop you! If you've got specific ideas or improvements related to this topic, feel free to open new issues for each one. That way, we can dive into them in more detail.
