### ISSUE TITLE
Configurable GeoIP2 database location

### ISSUE THREAD

**Issue by joseph-long** [matomo-org/matomo#14658]
Is there a way to configure Matomo to look in a different location for the GeoIP2 databases? The matomo source is on a read-only volume, but I have the GeoLite2 databases in `/var/lib/geoip-databases` if only I could point Matomo there...

**Comment by tsteur** [comment]
You can created a file `config/config.php` and configure an alternative path like 

```
<?php
return array('path.geoip2' => 'your path');
```

In the future please ask questions in the forums as we usually don't answer them here: https://forum.matomo.org
