### ISSUE TITLE
Custom report grouping under "Main reports"

### ISSUE THREAD

**Issue by amandahenriette** [matomo-org/matomo#14670]
Hi!

I encountered a usability-related problem with Custom reports. The management gets quite complicated when there exists a lot of reports, both main- and sub-reports. 

Would be great if you introduced grouping of Matomo custom reports, where user could browse the reports by main reports (and thus, see which reports are related to each other in an easy way).

I know that report category can be chosen, but we at least prefer to keep custom reports under custom reports :)

Thanks in advance!

Br,

Amanda

**Comment by tsteur** [comment]
Hi @amandahenriette 

not quite sure what you mean by `where user could browse the reports by main reports (and thus, see which reports are related to each other in an easy way).`?

Like you can put multiple reports together onto one page by assigning the same subcategory.

**Comment by amandahenriette** [comment]
Hey @tsteur 

Sorry, I clearly explained myself too vaguely and used wrong terms! Is there any help with this illustration?
![Matomo Custom reports](https://user-images.githubusercontent.com/47037993/61541010-11cfbf80-aa3f-11e9-8136-dcd24a90f55e.PNG)

**Comment by tsteur** [comment]
Thanks @amandahenriette we've made a change to show the subcategory there in the future, and to also have a search box to search for reports (searches in all properties including name, category, subcategory, ...). The select field in the table header isn't a concept we have so far in Matomo so it's not as easy to implement. Hope the search still works for you. It will be included in the next release.

In the future you can directly email shop at innocraft.com btw. Then they will also keep you in the loop when we implement a change you asked for etc.

**Comment by amandahenriette** [comment]
Hi @tsteur,

Ok, those sound good! And thanks for the email, I will keep that in mind next time.
