### ISSUE TITLE
Ecommerce product level data does not show when the date range is longer than one day

### ISSUE THREAD

**Issue by YouAint1stURLast** [matomo-org/matomo#14673]
**Issue**
When users search for ecommerce data over a period of time no data appears up. However, if you search for a single date within the a date range then you can see data. It appears that the only way to see ecommerce data is to search for a single day. This makes it very difficult to aggregate data over a long period of time.

**Steps to Reproduce**
-  Enter Ecom Reporting
- Select a custom date range that spans multiple days
- Notice no data appears
- Select a single date within the above custom date range
- Notice that data does appear

**Comment by tsteur** [comment]
This works nicely for us. See eg https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=day&date=yesterday#?idSite=62&period=range&date=2019-07-11,2019-07-13&category=Goals_Ecommerce&subcategory=Goals_Products

Does data appear for other reports when you select ranges? I suppose on your Matomo might be the archiving of range dates disabled in the config?

**Comment by YouAint1stURLast** [comment]
Hi Tsteur,

Thank you for the response. The data does seem to be flowing in now. 

Thanks again for following up.
