### ISSUE TITLE
Can not click checkbox in Administration > Websites > Tracking Code (in IE 11)

### ISSUE THREAD

**Issue by yhlin00001** [matomo-org/matomo#14693]
Hi folks,
  As subject. Any suggestions ?

**Comment by tsteur** [comment]
![image](https://user-images.githubusercontent.com/273120/61829550-41f2e480-aebd-11e9-8814-e0aeb38314d8.png)

This works for me. Are you using the latest version of Matomo @yhlin00001 ?

**Comment by yhlin00001** [comment]
Wow! our version is 3.5.1.

Thank you for reply.

**Comment by tsteur** [comment]
I recommend you update. I think we actually fixed this in a recent version.

**Comment by yhlin00001** [comment]
It is very tricky!
After I try the latest version of Matomo which is working in IE really, then I back to 3.5.1 version of Matomo to check what happen in IE 11, and to my surprise it is working.

Why? Why? Why?
