### ISSUE TITLE
Special character apostrophe is not getting printed properly in visits log (campaign url)

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#14695]
Expected: apostrophe should be printed in visits log

Result: instead we can see HTML entity &#39 is getting printed in visits log (no issue in campaign report)

steps to reproduce:
1.     Create a Campaign URL with params containing apostrophe
2.     Visit the page through campaign URL
3.     Check the Visits log

Note: When using the campaign URL, in the address bar of the browser it's getting encoded properly as %27 and also in the Campaign report. Issue occurs only in "Visits log"
![campaign_params_error](https://user-images.githubusercontent.com/26726594/61836987-e170a100-aed6-11e9-8895-d714c0683fff.png)
![campaign_report](https://user-images.githubusercontent.com/26726594/61836993-e6cdeb80-aed6-11e9-9d55-93e1533af9bd.png)

**Comment by KarthikRaja1388** [comment]
Exported report is also getting affected by this issue as apostrophe is not getting encoded.

**Comment by tsteur** [comment]
same problem here https://github.com/matomo-org/matomo/issues/18190
