### ISSUE TITLE
Warning - ucwords() expects exactly 1 parameter, 2 given

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14694]
reported in https://forum.matomo.org/t/warning-messages-ucwords-expects-exactly-1-parameter-after-update-to-3-11-0/33611
introduced in #14449

https://github.com/matomo-org/matomo/blob/e236d140a7b7f28995117ae10e2155735127f873/core/Http.php#L868

It seems like the second parameter has only been introduced in PHP 5.5.16, but Matomo supports (I think 5.5.9+)
https://3v4l.org/Uf3Ya
https://stackoverflow.com/questions/42575390/is-ucwords-delimiter-parameter-supported-in-php-5-6

**Comment by tsteur** [comment]
We will need to detect the PHP version and change logic based on this. I would say in PHP.5.5.9-PHP 5.5.15 we can simply not include the ucwords and assume user is not using curl2? Could also just explode instead and run strtoupper and all elements and then implode again...

**Comment by Findus23** [comment]
Disabling the fix in https://github.com/matomo-org/matomo/pull/14449 for the affected PHP versions sounds fine to me. No one apart from me even reported the original issue and as you say an ancient PHP version in combination with a really new curl version would be odd.

**Comment by sommer-gei** [comment]
Well don, but I wonder why this patch is not in the current 3.13.3 release?

**Comment by sgiehl** [comment]
actually it should be included. But @sommer-gei which php version are you using and which error do you still get? 🤔

**Comment by sommer-gei** [comment]
@sgiehl: Same error as in the issue title "Warning - ucwords() expects exactly 1 parameter, 2 given" with PHP 5.5.9 (yes I know it’s old).
I can’t see the fix in https://github.com/matomo-org/matomo/blob/3.13.3/core/Http.php#L937

Thanks for your Feedback!

**Comment by sgiehl** [comment]
Yeah you're right. That has been remove again in https://github.com/matomo-org/matomo/pull/14877
Can't say why 🤷‍♂

**Comment by diosmosis** [comment]
cc @tsteur not sure if this was due to a code merge issue or if there was a reason to remove it?

**Comment by tsteur** [comment]
Probably some github merge issue. We've had it a few times that suddenly some commit magically disappeared. Be good to add it again
