### ISSUE TITLE
Too many visitorids in segment

### ISSUE THREAD

**Issue by DrAthanas** [matomo-org/matomo#14704]
As soon as I add more than 292 visitorids to my call I get the following error:

> error message="visitorId is expected to be a 16 hex char string"

using a curl command to pull data:

curl -s -X POST -d 'module=API&method=Actions.getPageUrls&period=range&date=2018-01-01,2019-07-25&format=xml&idSite={site_id}&segment=visitorId=={n_1}, ....visitorId=={n_293}

**Comment by tsteur** [comment]
We don't have any limit there. I suppose either your browser or web server truncates the URL at a certain length. I reckon you check your server logs or check the server config

**Comment by DrAthanas** [comment]
As stated I am using curl which has no character limit for URLs

**Comment by tsteur** [comment]
Your web server might have a limit.
