### ISSUE TITLE
GDPR Tools can not filter on data subject "Events"

### ISSUE THREAD

**Issue by twanmeijerink** [matomo-org/matomo#14702]
Current situation:
1. Register a new Event Categories, like "Feedback - Titel: home".
2. Go to GDPR Tools
3. Find data subjects by "Events" -  "Equals" - "Feedback - Titel: home"
4. Result: "More than 400 results were found and the result was truncated to the first 400 visits." while only 1 event is available. 

Expected situation:
1. Register an Event Categories, eg. "Feedback - Titel: home".
2. Go to GDPR Tools
3. Find data subjects by "Events" -  "Equals" - "Feedback - Titel: home"
4. Result: "1 result found"

**Comment by tsteur** [comment]
@twanmeijerink are you using the latest version of Matomo? Cause it should actually not be possible to segment by event anymore see https://github.com/matomo-org/matomo/issues/12976 .

**Comment by twanmeijerink** [comment]
Ah ok, no on 3.9.
Is there a specific reason not to include events? Events are perfect to store any kind of data ofcourse..

Met vriendelijke groet,
Twan Meijerink

________________________________
Van: Thomas Steur <notifications@github.com>
Verzonden: zondag, juli 28, 2019 11:04 PM
Aan: matomo-org/matomo
CC: twanmeijerink; Mention
Onderwerp: Re: [matomo-org/matomo] GDPR Tools can not filter on data subject "Events" (#14702)


@twanmeijerink<https://github.com/twanmeijerink> are you using the latest version of Matomo? Cause it should actually not be possible to segment by event anymore see #12976<https://github.com/matomo-org/matomo/issues/12976> .

**Comment by tsteur** [comment]
It's a performance reason. It would be a lot of trouble for most Matomo databases out there scanning the entire database of all visitors/actions that were ever taken for specific events. And with events you usually can't really identify a user. You would rather use a custom dimension or userId or so to identify a specific visitor. Or do you record personal data like an email address in events?

**Comment by twanmeijerink** [comment]
Yes, we record emailaddres in events.. :-(

**Comment by tsteur** [comment]
Any chance you could save it as a visit custom dimension or userId on top? We're actually not planning on allowing to filter by events for performance reason. I'm sorry but I'll have to close the issue for now. I highly recommend ideally setting it eg as a visit custom dimension (additionally if needed). This will allow you to filter for it.
