### ISSUE TITLE
Error when trying to view custom report

### ISSUE THREAD

**Issue by hayleymapley** [matomo-org/matomo#14710]
I have created a custom report to look at unique visitors that trigger search events.
However, when I click on the Custom Reports tab and then the tab which has the name of my custom report, I get the following error message (
![error_matomo](https://user-images.githubusercontent.com/40159686/62086267-e4420c00-b2b1-11e9-9c69-cbe964f518a3.png)
):

An error occurred
Action 'getCustomReport' not found in the module 'CustomReports'

Weirdly, clicking on that report tab again sometimes shows a different non-error message (
![report_matomo](https://user-images.githubusercontent.com/40159686/62086277-ec01b080-b2b1-11e9-8463-1295a50e4af9.png)
):

No data for this report...

This is what the Manage Reports tab looks like (
![manage_matomo](https://user-images.githubusercontent.com/40159686/62086293-f8860900-b2b1-11e9-8a5a-1c0b9e15be91.png)
)

This non-fatal, but will possibly not allow me to see my data when it comes in.
Any help is appreciated!

**Comment by tsteur** [comment]
Hi @hayleymapley  could you email our support about this? The email is shop at innocraft.com

Does it maybe work by now? Sounds like it could be some caching issue in case your Matomo uses for example multiple servers or so.

**Comment by Jion72** [comment]
> Does it maybe work by now? Sounds like it could be some caching issue in case your Matomo uses for example multiple servers or so.

Hi, I'm experiencing the same problem as described above.
Is there any tests I can run?
Thank you very much

**Comment by tsteur** [comment]
@Jion72 be good to reach out to our support: The email is shop at innocraft.com
