### ISSUE TITLE
matomo js blocked in google chrome

### ISSUE THREAD

**Issue by siddvish12** [matomo-org/matomo#14720]
Hi Team,

1. Operating System : Window 7--64 bits
2. XAMPP for Windows 7.3.7(PHP 7.3.7)
3. Matomo Version 3.10.0

Downloaded Matomo on 17-July-2019.(upgrade to 3.11.0 [how to verify DB has been upgraded ]on 1-Aug-2019,but still issue persist in chrome)

Placed the Matomo folder in htdocs folder of XAMPP server
Using xampp-control application made Appache and Mysql up
with url http://localhost/matomo install matomo and configured database.

My application(Technology used: Struts 2,jsp,spring 3,jquery),Server: Wildfly 10,supports Chrome (my chrome v75), IE 11

IE11 doesn't stop loading matomo.js,but chrome refuses to load

As directed I tried to follow the instructions given in FAQ: https://matomo.org/faq/general/faq_20904/

As said moved the tracking code to tracking.js file <script type="text/javascript" src="js/tracking.js"></script>
and matomo.js <script src="http://localhost/matomo/matomo.js" async defer></script>,
both the script tag placed inbetween <head> tag

<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' http://localhost/matomo/matomo.js; style-src 'self'; frame-src 'self'; "/>

on the load of application in chrome(Version 75)
gives error

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' http://localhost/matomo/matomo.js". Either the 'unsafe-inline' keyword, a hash ('sha256-P47U9SvEMh8b3csLjO/YQ+vBliC1ROVLgzJzLGztmLA='), or a nonce ('nonce-...') is required to enable inline execution.

on adding attribute 'unsafe-inline' gives error

Refused to load the script 'http://localhost/matomo/matomo.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline' 'unsafe-eval' 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Thankyou Team for the spontaneous reply.

Hope to soon find solution.

Sunitha

**Comment by tsteur** [comment]
Hi there, maybe check out https://github.com/matomo-org/matomo/issues/14653 and related issues https://github.com/matomo-org/matomo/issues?utf8=%E2%9C%93&q=is%3Aissue+content+security+ . Maybe you find something there. It seems like other users are using it successfully. If there's still an issue please comment and we can reopen the issue. Be good if you could find out exactly what the problem is, so we can have a look.

**Comment by andrelung** [comment]
Sorry for reviving the issue, but I am running into a similar problem. We implemented 
https://github.com/matomo-org/tracker-proxy

...and the "matomo Failed to load resource: net::ERR_BLOCKED_BY_CLIENT" problems stopped. I am not entirely sure why this worked, but I wanted to let everyone know, who stumbles upon this thread.
