### ISSUE TITLE
Cannot declare class Piwik\Config

### ISSUE THREAD

**Issue by korn519** [matomo-org/matomo#14725]
I use vesion is 3.11, PHP version is 7 .I have installed it on my windows.But it reported an error on centos6 when i want to install. 

"Fatal error: Cannot declare class Piwik\Config, because the name is already in use in /home/nginxroot/matomodev/core/Config.php on line 43"
		
Has anyone ever met this?

**Comment by tsteur** [comment]
@korn519 I recommend you remove all Matomo files again (except for `config/config.ini.php` in case you could finish the install) and then copy over the files again. We haven't heard of anything like this before and our tests don't show such an error.

**Comment by mattab** [comment]
fyi a similar report (with a different class name) was found today in the forums: https://forum.matomo.org/t/error-in-installation/34308

**Comment by korn519** [comment]
I remove all files again.Thanks a lot.
