### ISSUE TITLE
"Unable to write in the cache directory" error

### ISSUE THREAD

**Issue by Tennyleaz** [matomo-org/matomo#14723]
I'm using Matomo 3.11.0, on ubuntu 18.04, php 7.2.
In some rare occasions, the web interface shows an error  `Unable to write in the cache directory` in one of the tmp directories, ex: `public_html/tmp/templates_c/73`.

My apache log looks like:

    [Fri Aug 02 11:09:19.824045 2019] [php7:notice] [pid 26971] [client 10.10.12.13:53169] Error in Matomo: Unable to write in the cache directory (/var/www/matomo/public_html/tmp/templates_c/73)., referer: http://10.10.1.2/index.php?module=UserCountry&action=adminIndex&idSite=1&period=day&date=yesterday&showtitle=1&random=8909
    [Fri Aug 02 11:09:36.196121 2019] [php7:notice] [pid 26605] [client 10.10.12.13:53177] Error in Matomo: Unable to write in the cache directory (/var/www/matomo/public_html/tmp/templates_c/73)., referer: http://10.10.1.2/index.php?module=CoreAdminHome&action=home&idSite=1&period=day&date=yesterday\

I have to manually change owner of the `templates_c/...` directory.
Any suggestions?

**Comment by tsteur** [comment]
@Tennyleaz sorry this sounds like an issue with your server where we can't really help. We wouldn't change the permission to someone else so likely something on your server is changing it. For example if you delete some files manually or so. I suggest you ask in the forum or search there: https://forum.matomo.org other people might have had similar issues before. Best to give them more details like what operating system, what hoster you are with, etc.
