### ISSUE TITLE
When creating a goal, the option “Allow multiple conversions per Visit” is not visible

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14732]
reported by a user by email:

When creating a goal, the option “Allow multiple conversions per Visit” is not visible in the Create Goal screen. 

this was regressed in 3.11.0. Should have been visible as a regression in some UI tests but was missed for some reasons.

**Comment by ldibanyez** [comment]
For those of us that need to set this option in our goals and can't wait for 3.12.0, what is the alternative/workaround?

**Comment by diosmosis** [comment]
@ldibanyez can you apply this one character change yourself: https://github.com/matomo-org/matomo/pull/14741/files ? That would make the option show up.
