### ISSUE TITLE
User avatar set with javascript

### ISSUE THREAD

**Issue by Natgho** [matomo-org/matomo#14735]
Hi,
When user logged in my website, I use to "setUser" command for matomo. also can I add User avatar?

**Comment by Findus23** [comment]
This sounds like #6936.

The plugin that supports this hasn't been updated in 5 years, but if you could update it to work in the latest Matomo version, you could step up as a new maintainer:
https://github.com/surenjie/VisitorAvatar
https://github.com/surenjie/VisitorAvatar/issues/5
The documentation for the Matomo API is here: https://developer.matomo.org/api-reference/events#livegetextravisitordetails

**Comment by Natgho** [comment]
Thank you for your answer. 
I saw this method during research. I want to use with more basically (like setUserId), for example;
_paq.push("setUserAvatar", userImage)

do you have any plans for such a development?
