### ISSUE TITLE
Singapore flag not shown in city.

### ISSUE THREAD

**Issue by Tennyleaz** [matomo-org/matomo#14730]
I am using GeoIP 2 (PHP) database in matomo. 
The Singapore flag is shown in countries view, but not shown in cities view.

Matomo 3.11.0
PHP 7.2.19

**Comment by sgiehl** [comment]
I'm able to see the same on our demo. Will check that...

**Comment by mattab** [comment]
re-opening as it seems not fixed, eg. seen today running latest 3.12.0-b4, there is no flag for Singapore: 
![Screenshot from 2019-09-26 13-14-38](https://user-images.githubusercontent.com/466765/65650602-b7b33200-e05f-11e9-82f5-2c9c5ed50b41.png)

**Comment by sgiehl** [comment]
@mattab I'm only seeing that on the demo site. Might it be possible that only a City is set for those visitors but no country?

**Comment by diosmosis** [comment]
It might be that the data on the demo proxy was archived before the fix for this was merged and pushed onto cloud.
