### ISSUE TITLE
Less data than actual

### ISSUE THREAD

**Issue by zhangduo0729** [matomo-org/matomo#14749]
Less data than actual！

![C78B9FD9-F34E-49de-847C-437F7935F806](https://user-images.githubusercontent.com/25076700/62777857-4cc68f80-bae1-11e9-8df5-59009822c8e0.png)

**Comment by zhangduo0729** [comment]
3.10.0

**Comment by tsteur** [comment]
Sorry I don't understand your question? Could you please update to the latest version and describe in as much detail as possible what the problem is? Cheers
