### ISSUE TITLE
"create new segment" button in segment editor should send user to the visitor log

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#14744]
Currently when clicking the button in the segmented visitor log, the user is taken to the same page w/ a segment. This removes the context of the segmented visitor log, so the user can no longer see the visits the segment will select. Sending the user to the visitor log will allow the user to see the selected visits, and tweak the segment more easily if needed.

**Comment by katebutler** [comment]
Was implemented in #14884
