### ISSUE TITLE
Other Important issues to close and PRs to merge in Matomo 4

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14746]
List of issues and Pull Requests that are in other `matomo-org/*` Github projects that we'd want to merge in Matomo 4:

* [x] ~https://github.com/matomo-org/matomo-php-tracker/pull/35~ https://github.com/matomo-org/matomo-php-tracker/pull/65 PHP Tracker SDK should throw an exception when a curl error is triggered to ease debug 
* [ ] add here any other issue/PR...

**Comment by sgiehl** [comment]
the linked issue has been merged
