### ISSUE TITLE
Page not tracked vie the live api

### ISSUE THREAD

**Issue by markkap** [matomo-org/matomo#14758]
Hi there, sorry if this is not the right place to ask this

I got a page at https://dev2.whilefly.com/?p=1758 which doesn't seem to get reported via the `Live.getLastVisitsDetails` API, while a page like https://dev2.whilefly.com/?p=2355 is being tracked and reported. 

In our setup matomo is a black box to which there is no admin access and data is retrieved every few minutes via `Live.getLastVisitsDetails` and being processed. It seems like we have no problem with properly getting events this way but page views are failing.
I had a suspicion that it is somehow related to URL length, but when I load the matomo.php... url I get the pixel so probably that is not the problem here.

This is on version 3.10

I am a matomo noob and right now not sure where to look and what to do next. Any guidence will be appriciated.

**Comment by tsteur** [comment]
Not quite the right place unfortunately. Could you ask this in the https://forum.matomo.org

Maybe have a look here: https://github.com/matomo-org/matomo/issues/8593 It may help you find the problem to see if it is a tracking problem

**Comment by markkap** [comment]
@tsteur turn out I wasn't reading correctly the output of the API and therefore missed that the pageview was actually reported it was just not reported with the expected custom variables values as one of them was longer than 200 characters.

So there are two bugs here
1. The live API does not report timespent if a custom variable is too long. I guess this is an edge case but if the page view is registered it should at least properly provide all the data which can be provided.
2. If the request to matomo.php can not be completed as the user requested, a 5xx code should be returned and not 200 as the request was only partially completed at best. This will save a huge amount of time for people that do not read the small details in the documentation.
