### ISSUE TITLE
Pressing "Enter" key does not work to apply a Segment using Keyboard

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14755]
Pressing "Enter" key does not work to apply a Segment using Keyboard. 

Steps to reproduce:
* Create at least one Segment
* Press `s` to open segment selector
* Press tab twice to select the first segment in the list 
* Press enter
  * Expected: Segment opens, page reloads.
  * Got: nothing.

Same applies for the "Add a new segment" button. 

_Note: it already works fine to create a segment using keyword once you can get to the segment editor._

**Comment by sgiehl** [comment]
That one is quite easy to fix. Will provide a PR for it.
