### ISSUE TITLE
Feature request [CustomReports]: invalidate specific report

### ISSUE THREAD

**Issue by toredash** [matomo-org/matomo#14768]
It is not possible to force reports generation for a newly generated report, without having to invalidate all reports for the given site.

We want to be able to create a new report, invalidate it, and then have the archive process generate reports for the newly created custom report.

Our goal is to be able to introduce custom reports, generate then with previous data and new, without having to invalidate all reports for the site. Re-generating all reports this way can take days.

Is there anything else I can contribute with in terms of understanding the feature request ?

**Comment by sgiehl** [comment]
@toredash there is a (not documented) console command to trigger custom report archiving for a given sites and date (range): `./console customreports:archive --idsites=1,2,3 --date=2019-01-01,2019-08-14`.
The command is currently not documented as it's no neither an official feature nor a clean solution and that might break with upcoming Matomo releases. A clean solution will hopefully be provided with #11974
