### ISSUE TITLE
Warning: CustomVariables.php(82): Notice - Undefined index: CustomVariables.MaxNumCustomVariables

### ISSUE THREAD

**Issue by howdytom** [matomo-org/matomo#14773]
Hi there,

since I have upgraded to Matomo 3.11.0, the following warning sporadically shows up on the _Diagnostic_ > _System Check_ page:

`WARNING: plugins/CustomVariables/CustomVariables.php(82): Notice - Undefined index: CustomVariables.MaxNumCustomVariables - Matomo 3.11.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)`

I don’t use CustomVariables at all. It’s disabled on the plugins page. Any ideas?

**Comment by sgiehl** [comment]
Guess that's caused by disabling the plugin. Seems other plugins use methods of that plugin that don't work properly when the plugin is disabled

**Comment by howdytom** [comment]
Besides Matomo Core plugins I do not use any additional plugins. I haven't noticed any issues when _CustomVariables_ is disabled.
