### ISSUE TITLE
don't allow updating 0 plugins

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14785]
Just a minor usability improvement:
When no updates are selected, but `Update Selected` is clicked, the user is redirected to an error page.

![image](https://user-images.githubusercontent.com/6266037/63228227-673eee00-c1f0-11e9-9c7a-5f2107c41f92.png)

![image](https://user-images.githubusercontent.com/6266037/63228237-7625a080-c1f0-11e9-9354-ff2218728d4b.png)

> The parameter 'pluginName' isn't set in the Request, and a default value wasn't provided.

**Comment by sgiehl** [comment]
this was fixed with #14811
