### ISSUE TITLE
[Docs] Explain shell_exec requirement

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14782]
I am a bit confused by the usage of `shell_exec` in Matomo and can't find any docs for it.

- https://matomo.org/docs/requirements/ doesn't mention that it is required
- In the few places I checked there is often a `if (!function_exists('shell_exec')) {` indicating that is only recommended, but not required
- There are no docs explaining what Matomo needs shell_exec for (or even what it is and how to enable it)
   - Therefore there are many recurring questions about it on the forum like https://forum.matomo.org/t/shell-exec-sie-mussen-diese-eingebaute-funktion-aktivieren/23079/2
- The system check is called `RecommendedFunctionsCheck` indicating that it isn't required
- but the warning it gives is `You need to enable this built-in function.` and `Sie müssen diese eingebaute Funktion aktivieren` indicating that it is required.

Can someone who knows the background help clarifying all docs?

**Comment by whalehub** [comment]
@mattab I see that addressing this topic is planned for the 4.x series of releases, but in the meantime, do you mind answering the question of whether or not enabling `shell_exec` is mandatory for using the 3.x series of Matomo releases?

**Comment by tsteur** [comment]
I had a very quick look and doesn't seem to be required, only optional.

**Comment by mattab** [comment]
btw It is optional but (only?) required for the "CLI processes" to work during core:archive, which is important for higher traffic websites, or for Matomo instances that have a lot of segments, or that have a lot of websites. learn more: https://matomo.org/faq/troubleshooting/how-to-make-the-diagnostic-managing-processes-via-cli-to-display-ok/

**Comment by tsteur** [comment]
As part of this issue we change `You need to enable this built-in function.` to `We recommend you enable this built-in function.`. We could also link to https://matomo.org/faq/troubleshooting/how-to-make-the-diagnostic-managing-processes-via-cli-to-display-ok/
