### ISSUE TITLE
Do I need to publish the source code of my website under GPLv3 if I use matomo?

### ISSUE THREAD

**Issue by oleks** [matomo-org/matomo#14780]
Matomo is [licensed under GPLv3](https://github.com/matomo-org/matomo/blob/3.x-dev/misc/gpl-3.0.txt). This means that if I use matomo in "covered work", then my "covered work" must be open source and licensed under GPLv3.

Does this mean that if I use matomo to track the users of my web-site (e.g., using some JavaScript provided by this codebase, pointing at PHP end-points provided by this codebase), then I have to publish the source code of my web-site (server-side and client-side) under GPLv3?

**Comment by Findus23** [comment]
(DISCLAIMER: this is in no way legal advice)

It would mean this (you need to at least publish the other JS under GPL3, not soure about PHP) if all of Matomo was GPL3 licensed.

## BUT:

To avoid exactly this situation, the tracking code of Matomo is not GPL-licensed, but instead under a BSD-3-clause license. So as long as you follow these three rules (essenially meaning you are not allowed to remove the license header of the matomo.js file), you are free to use Matomo without any implications for the rest of the website.

https://github.com/matomo-org/matomo/blob/c2186baf5ca5966d7391b91161fa7109bbb8d634/matomo.js#L6-L9
