### ISSUE TITLE
Support piwik in strict mode?

### ISSUE THREAD

**Issue by alexyeunghk01** [matomo-org/matomo#14791]
as I am using es6 module and import piwik.js via npm package, every dependency are in js strict mode
It will show error `ReferenceError: JSON_PIWIK is not defined`

Can we wrap all global variables with `window.`? It seems can fix the issue easily, I am ok to open PR to do it

**Comment by Findus23** [comment]
Hi,

Quick question: How are you using `piwik.js via npm package`? As far as I know there is no npm module for the tracking code.

**Comment by tsteur** [comment]
Sure feel free to do a PR 👍 That should be fine to prefix it with `window.`

**Comment by nina-py** [comment]
I think this ticket should be closed as there is nothing to do - the JSON_PIWIK variable is long gone from the codebase: https://github.com/matomo-org/matomo/pull/15785/files

**Comment by Findus23** [comment]
It would still be great if someone could test if importing matomo.js as an npm package.

**Comment by tsteur** [comment]
Did a quick test and what was missing was still prefixing some variables with window which I fixed in https://github.com/matomo-org/matomo/pull/16498
