### ISSUE TITLE
Fatal error when trying to run the archive command.

### ISSUE THREAD

**Issue by sixcorners** [matomo-org/matomo#14805]
I am getting a fatal error when trying to run console core:archive.
> Warning: require(../protected/config/global.php): failed to open stream: No
> such file or directory in
> /home/public/vendor/php-di/php-di/src/DI/Definition/Source/DefinitionFile.php
> on line 56
> 
> Fatal error: require(): Failed opening required
> '../protected/config/global.php'
> (include_path='/home/public/vendor/pear/pear_exception:/home/public/vendor/pear/console_getopt:/home/public/vendor/pear/pear-core-minimal/src:/home/public/vendor/pear/archive_tar:.://usr/local/php/7.2.21-nfsn1/lib/:/usr/local/php/lib/')
> in
> /home/public/vendor/php-di/php-di/src/DI/Definition/Source/DefinitionFile.php
> on line 56
> /home/public/console core:archive --url=https://matomo.asdf/
> exited with return code 255
> 
My bootstrap.php looks like this
```php
<?php
define('PIWIK_USER_PATH', '../protected');
```

**Comment by tsteur** [comment]
Hi @sixcorners AFAIK we don't support setting a different path.
