### ISSUE TITLE
Auto-archive mysql prepare error: lost connection to MySQL server during query -in plugin Actions

### ISSUE THREAD

**Issue by lexlpz** [matomo-org/matomo#14804]
Hi guys,
A couple of days ago I updated PHP to version 7.3 and everything is working fine except Matomo. I checked on the website and it should be fully compatible, so I decided to look the issue up over here. I couldn't find the same issue posted, my apologies in advance if it actually is posted here. 

The issue I am facing is with the auto archive, eventhough it looks more like a MySQL issue but I would like your guidance. I have the auto archive set up every hour and since the update to PHP 7.3 I get an error email from the cron task: 

`ERROR [2019-08-23 18:07:07] 1388920  Got invalid response from API request: ?module=API&method=API.get&idSite=2&period=day&date=last3&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:165:"Mysqli prepare error: Lost connection to MySQL server during query - in plugin Actions, caused by: Mysqli prepare error: Lost connection to MySQL server during query";}'
ERROR [2019-08-23 18:07:07] 1388920  Empty or invalid response '' for website id 2, Time elapsed: 2.260s, skipping ERROR [2019-08-23 18:07:08] 1388920  Got invalid response from API request: ?module=API&method=API.get&idSite=3&period=day&date=last3&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:165:"Mysqli prepare error: Lost connection to MySQL server during query - in plugin Actions, caused by: Mysqli prepare error: Lost connection to MySQL server during query";}'
ERROR [2019-08-23 18:07:08] 1388920  Empty or invalid response '' for website id 3, Time elapsed: 0.687s, skipping ERROR [2019-08-23 18:07:09] 1388920  Got invalid response from API request: ?module=API&method=API.get&idSite=4&period=day&date=last4&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:167:"Mysqli prepare error: Lost connection to MySQL server during query - in plugin Referrers, caused by: Mysqli prepare error: Lost connection to MySQL server during query";}'
ERROR [2019-08-23 18:07:09] 1388920  Empty or invalid response '' for website id 4, Time elapsed: 0.722s, skipping ERROR [2019-08-23 18:07:10] 1388920  Got invalid response from API request: ?module=API&method=API.get&idSite=5&period=day&date=last2&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:167:"Mysqli prepare error: Lost connection to MySQL server during query - in plugin Referrers, caused by: Mysqli prepare error: Lost connection to MySQL server during query";}'
ERROR [2019-08-23 18:07:10] 1388920  Empty or invalid response '' for website id 5, Time elapsed: 1.051s, skipping ERROR [2019-08-23 18:07:11] 1388920  8 total errors during this script execution, please investigate and try and fix these errors.
                                                                                         
  [Exception]                                                                                    
  8 total errors during this script execution, please investigate and try and fix these errors.  
                                                                                                 
core:archive [--url="..."] [--force-all-websites] [--force-all-periods[="..."]] [--force-timeout-for-periods[="..."]] [--skip-idsites[="..."]] [--skip-all-segments] [--force-idsites[="..."]] [--force-periods[="..."]] [--force-date-last-n="..."] [--force-date-range[="..."]] [--force-idsegments="..."] [--concurrent-requests-per-website[="..."]] [--concurrent-archivers[="..."]] [--disable-scheduled-tasks] [--accept-invalid-ssl-certificate] [--php-cli-options[="..."]]
`
Could it be the innodb_log_file_size parameter of MySQL? I have my Matomo installation on a shared host. 
Any help would be greatly appreciated. 

These are my versions:
Matomo version: 3.11.0
MySQL version: 10.1.41-MariaDB-cll-lve
PHP version: 7.3.8

Thank you in advance,
Alex.

**Comment by tsteur** [comment]
Hi Alex, could you please ask this question in the forum: https://forum.matomo.org

Thanks
