### ISSUE TITLE
Notice message "A non well formed numeric value encountered" in vendor/davaxi/sparkline/src/Sparkline/FormatTrait.php 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14800]
Reported in forums by at least two users: https://forum.matomo.org/t/formattrait-php-193-notice-a-non-well-formed-numeric-value-encountered-matomo-3-10-0/33422

> On the dashboard an orange alert box appers with following error message:
“WARNING: httpdocs/st/vendor/davaxi/sparkline/src/Sparkline/FormatTrait.php(193): Notice - A non well formed numeric value encountered - Matomo 3.11.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)”

**Comment by Findus23** [comment]
Seems like it is the same issue as #14662
(sorry, I didn't check before)

**Comment by Kervinou** [comment]
same issue for me, my new server use MariaDB last version on Debian Linux Buster
