### ISSUE TITLE
plugins can be enumerated if you know their file paths

### ISSUE THREAD

**Issue by sixcorners** [matomo-org/matomo#14806]
Links like this:
https://matomo.asdf/plugins/BotTracker/plugin.json
resolve and show what plugins you have installed.
It would be nice if this wasn't exposed.

**Comment by tsteur** [comment]
Hi there, if that's an issue for you (eg if you consider this a security issue), you could simply disallow requests to plugin.json and other files in plugins (php, js, ...) Images you would likely still need to allow though. In general we have no plans of changing anything there and will close therefore.
