### ISSUE TITLE
Make Matomo compatible with PHP 7.4

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14821]
similar to #13418

### Status:

All Warnings in Matomo itself and the broken Twig rendering are fixed in Matomo 3.12. All remaining warnings depend on third-party libraries (see below).

Soon PHP 7.4 will be released (RC 1 is planned or September 5th), so it would be great if Matomo would work mostly fine when it is released.

I set up a Matomo instance using the latest beta4 at https://matomo-beta.lw1.at
If you want to get access, just message me.

Current status is that Matomo is nearly completly unusable as it renders invalid HTML with missing whitespaces:
```html
<ul class="right hide-on-med-and-down"><li role="menuitem" class="active"><atitle="Zeige Webanalytik Berichte für Testsite."                  id="topmenu-corehome"
                  href="index.php?module=CoreHome&amp;action=index&amp;idSite=1&amp;period=day&amp;date=yesterday"               target="_self" tabindex="3">Dashboard</a></li><li role="menuitem" class=""><atitle="Vergleichen Sie Webanalytikstatistiken für alle Ihre Websites."                  id="topmenu-multisites"
                  href="index.php?module=MultiSites&amp;action=index&amp;idSite=1&amp;period=day&amp;date=yesterday"               target="_self" tabindex="3">Alle Websites</a></li><li role="menuitem" class=""><atitle=""                  id="topmenu-tagmanager"
```

This seem to be caused by a required change in Twig (https://github.com/twigphp/Twig/pull/3004/commits/1fb0f9701d8443083495cd2645e8a0c45d54c34d), so updating to twig 1.41.0 or later should solve this.

**Comment by Findus23** [comment]
One more bug that breaks archiving: (appears as a response in archiving)

```
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/matomo-beta/libs/upgradephp/upgrade.php on line 180 PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/matomo-beta/libs/upgradephp/upgrade.php on line 194 PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/matomo-beta/libs/upgradephp/upgrade.php on line 194 PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/matomo-beta/libs/upgradephp/upgrade.php on line 200 PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/matomo-beta/libs/upgradephp/upgrade.php on line 202 
```
https://github.com/matomo-org/matomo/blob/7ef892665d8e51471a0eb3fa93a4b0f9967278b7/libs/upgradephp/upgrade.php#L180
I don't know what that line means, but I am also confused why this function is here when Matomo is using a custom ini parser.

**Comment by Findus23** [comment]
One more warning in the log:
```
/var/www/matomo-beta/core/DataTable/Filter/ColumnDelete.php(164): Deprecated - array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead - Matomo 3.11.0
```
https://github.com/matomo-org/matomo/blob/b16a791aa3650d85af829156129c2bd44c7cb075/core/DataTable/Filter/ColumnDelete.php#L164

**Comment by Findus23** [comment]
Another occurrence of the braces will be fixed with https://github.com/leafo/lessphp/pull/647 (if it gets merged as the last release was 5 years ago)

**Comment by Findus23** [comment]
Two more deprecation warnings in tcpdf will be fixed with 
https://github.com/tecnickcom/TCPDF/pull/123
and 
https://github.com/tecnickcom/TCPDF/pull/131

**Comment by Findus23** [comment]
Another potential bug (but I don't think it happens in Matomo and is only very minor):
https://github.com/davaxi/Sparkline/pull/10

**Comment by mattab** [comment]
@Findus23 Thanks for creating the issue! :+1:  What is the status of PHP 7.4 compatibility now?

**Comment by Findus23** [comment]
@mattab I think all remaining issues are in third party libraries as mentioned above. And Matomo won't be completly ususable as of now.
But I don't have a great solution for updating those.

**Comment by tsteur** [comment]
We'd need to fork it in this case since we can't wait to Matomo 4 unfortunately.
