### ISSUE TITLE
Dashboard title with space

### ISSUE THREAD

**Issue by Laul0** [matomo-org/matomo#14820]
## Summary

It is possible to create several custom Dashboard without any restriction into the title of them.

## Current behavior

When I create a new Dashboard with a space into the title, the space is encoded (replaced by a `%20`)

<img width="234" alt="Screen Shot 2019-08-19 at 19 15 39" src="https://user-images.githubusercontent.com/15279205/63783440-05027f00-c8bb-11e9-8206-451724193900.png">

## Expected behavior

Several possibilities are available

1. Prevent user to create a Dashboard with some special chars (useless because the dashboard title is not used into the URL)
2. Allow special char but display them without encodage

**Comment by tsteur** [comment]
Thanks @Laul0 I can reproduce that 👍
