### ISSUE TITLE
Premium Bundle is listed twice in Administration > Markteplace

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14837]
Reproduced in https://demo.matomo.org/index.php?module=Marketplace&action=overview&idSite=1&period=week&date=today&activated=&mode=admin&type=&show=&show=premium&updated=1

Screenshot:

![Screenshot from 2019-09-01 12-10-46](https://user-images.githubusercontent.com/466765/64074899-9dc93e00-ccb1-11e9-8d51-10d00680d8d3.png)

**Comment by tsteur** [comment]
I reckon it's fixed.
