### ISSUE TITLE
Question about Unique visitors count

### ISSUE THREAD

**Issue by protovateadmin** [matomo-org/matomo#14842]
Hi folks!

Everything fine with matomo, thanks to Matomo dev team for nice product. Only one thing which I can't understand how Matomo aggregating unique visitors count. For example, we use log import feature (we are importing web server logs to Matomo application), if I take first month when we start using matomo I see about 20 millions unique visitors for that Month.
![first month](https://user-images.githubusercontent.com/54355837/64109883-48f8f680-cd89-11e9-8304-ff32450d4f75.JPG)

Question 1. I assume, since we just started use Matomo, probably all users are unique except those who visit site again during that period?

Then every month this number decreases, for example 7 months later I see 7 millions for same period "month" with bigger visits & pageviews count.

![next month](https://user-images.githubusercontent.com/54355837/64109999-91b0af80-cd89-11e9-981a-8de8a50ede93.JPG)

And finally, If I take last month (August 2019). I see about 2 millions.

![last month](https://user-images.githubusercontent.com/54355837/64110150-f5d37380-cd89-11e9-9533-121db7c0ba4f.JPG)

Also, if I take period "day" or "week" for same month, for example August 28 I see probably same number  ~2 millions.

![last month period week](https://user-images.githubusercontent.com/54355837/64110646-629b3d80-cd8b-11e9-9526-8e872cfd00b8.JPG)

Question 2. So how to interpret month results? I suppose month results = unique users sum of all days of given month?

Thank you in advance.

**Comment by tsteur** [comment]
Hi there,

could you please ask this question in our forum https://forum.matomo.org ? Thanks!

In general visitors from January will be counted as unique visitors again in February. Eg in February it only looks how many unique visitors had visisted your site in that date range. What you're probably after is "unique new visitors" which we don't offer.
