### ISSUE TITLE
Wrong percentage on Visitors Location page

### ISSUE THREAD

**Issue by hedii** [matomo-org/matomo#14849]
Hi, there is a diff in unique visitors percent stat on the Visitors Location page (`/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=General_Visitors&subcategory=UserCountry_SubmenuLocations`) between the Country map widget and the Country table widget.

See the pictures below (19,7% for France on the map, 23,9% for France on the table, both for the same unique visitors number).

<img width="1567" alt="Capture d’écran 2019-09-03 à 11 01 30" src="https://user-images.githubusercontent.com/5358048/64160022-7f8f4980-ce3b-11e9-8ec4-bed9b08e44e3.png">
<img width="1554" alt="Capture d’écran 2019-09-03 à 11 01 05" src="https://user-images.githubusercontent.com/5358048/64160023-7f8f4980-ce3b-11e9-95b3-e3307f1cd37e.png">

**Comment by sgiehl** [comment]
Thanks for the report. I'm able to reproduce that on our demo. We'll need to look into that.
Would you mind checking which number the "totals" row is showing for the table

**Comment by hedii** [comment]
The table Totals row is 796 484

**Comment by sgiehl** [comment]
ok. So it differs from the number shown on the map :thinking:

**Comment by hedii** [comment]
Yes indeed. All tables on this page (Country, Region, City) show the same unique visitors number 796 484. Only the map shows 768 820.

**Comment by PoorWei** [comment]
Similar issue here, seems wrong calculation under World-Wide level.
Probably forgot **changing denominator** when select other views except "vistor"

Take following picture as example:
**Visits** taken in Taiwan is 1361 / 1744 = 78%

Same calculation, **actions** taken in Taiwan should be: 7172 / 9747 = 73.6%
but it shows 7172 / 1744 = 411%

![image](https://user-images.githubusercontent.com/54881568/64230340-2e588600-cf1f-11e9-889b-e8fd38216e74.png)

![image](https://user-images.githubusercontent.com/54881568/64230390-53e58f80-cf1f-11e9-8c62-b105df440640.png)

**Comment by sgiehl** [comment]
Yes. The percentage calculation is incorrect. It always uses the visit count on world map. I'll prepare a fix for that.

The number of unique visits displayed as total on the visitor map might differ for the following reason:
The total numbers are fetched from the visit summary, which includes the overall unique visitors. The country reports calculates the unique visitors based on the country, so people switching the country might be counted multiple times in the country report, but only once in the summary.

@mattab Shall we use a summed up value for this case, so the number of unqiue visitors matches the country report?

**Comment by mattab** [comment]
@sgiehl not sure I understand the comment, but we generally want the map to use Visits of a country divided by the total visits metrics (from visit summary), or if the map shows unique visitors for a country, then to calculate ratio against Unique visitors (from visit summary) overall.

**Comment by sgiehl** [comment]
sure. that works smoothly for all metrics except unique visitors. The sum of all unique visitors in the country table is another number than the one in visitor summary. That might be caused by the way how unique visitors are calculated for each country. Maybe that is a bug :man_shrugging: 

That means the percentage shown on the map is then another one as in the country table...

**Comment by mattab** [comment]
That's a bit strange, do you have an example screenshot (showing also the calendar) where this can be seen?

**Comment by sgiehl** [comment]
Sure. You can see that for every site on demo. Simply go to locations page and enable the totals row of the country report:

![image](https://user-images.githubusercontent.com/1579355/64632226-fce92a00-d3f8-11e9-838a-90233d4d7d97.png)
