### ISSUE TITLE
Bug: execution of php files stalls if database DNS resolves to an non-existing IP

### ISSUE THREAD

**Issue by toredash** [matomo-org/matomo#14864]
Hi,

Running Matomo 3.11 / Nginx 1.16 / PHP 7.3.9 and ran into an issue where parsing of PHP files related to matomo stall completely.

Our database got migrated to from one AWS RDS Serverless instance to another. When the migration was done, the existing database was turned off. After this, the DNS name for the turned of database still resolve to an IP address, but nothing responds.

The issue was discovered when matomo was restarted, requests for index.php would then time out on the client-side. Increase of log level in nginx and php-fpm didn't indicate anything, other than that the client terminated the connection.

Requesting php files that isn't part of matomo worked fine, and issues requests for php-fpm internal /ping and /status command worked as expected as well.

We also tried to decrease php_admin_value[max_execution_time] to 5 seconds, but the request for e.g. index.php never times out on the server side, and the client will in the end terminate the request, which is logged in php-fpm as client initiated closure.

Changing the DNS hostname to our next database, resolved the issue. It was extremely hard to debug since there was no logs or outputs that would indicate what could be wrong.

**Comment by tsteur** [comment]
You can enable tracker  debug in this case eg https://matomo.org/faq/troubleshooting/faq_115/  It would have likely shown the error. Cheers
