### ISSUE TITLE
[Question] pre-inject customizable config.ini.php prior to setup and still continue the setup process

### ISSUE THREAD

**Issue by Bulletninja** [matomo-org/matomo#14862]
Is there a standard way to inject some config.ini.php without ruining the setup process?
I'm guessing `bootstrap.php` is the right place. But i'm not sure how to approach this. My idea is to read some environment variables from `bootstrap.php` and determine if i need some config from the get go, like say:
```
proxy_client_headers[] = HTTP_X_FORWARDED_FOR
proxy_host_headers[] = HTTP_X_FORWARDED_HOST
```
then be able to initialize `config.ini.php` with that. And then continue with the normal setup process. Is this possible? Does this make sense? Or is there a different (recommended) approach for this sort of thing?

**Comment by tsteur** [comment]
Check out https://plugins.matomo.org/EnvironmentVariables

**Comment by tsteur** [comment]
Or you can create a plugin like this: https://github.com/innocraft/plugin-ForceSSL/ and overwrite config like here: https://github.com/innocraft/plugin-ForceSSL/blob/master/config/config.php#L11
