### ISSUE TITLE
Composer install fails: required package matomo-org/jshrink does not exist

### ISSUE THREAD

**Issue by creativecoder** [matomo-org/matomo#14874]
I maintain a composer managed install of Matomo. For several releases now I've been unable to update Matomo because it's composer.json file requires a package that does not exist in packagist: `matomo-org/jshrink`.

When running `composer require piwik/piwik:3.11.0`, I get this output

```
Problem 1
    - Installation request for piwik/piwik 3.11.0 -> satisfiable by piwik/piwik[3.11.0].
    - piwik/piwik 3.11.0 requires matomo-org/jshrink 1.3.1 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by Findus23** [comment]
Hi,

The package is defined in the package.json:
https://github.com/matomo-org/matomo/blob/9855f8c1aaa2e7af6725423ba047fdf54a821106/composer.json#L89-L116

This hack is required as the original package doesn't support 5.5 anymore, but Matomo needs the support.

**Comment by creativecoder** [comment]
Thanks! -- I should have seen that in the composer configuration.

 I was able to work around the error by copying the same repository config into my project.

**Comment by bluikko** [comment]
This issue seems to still be present in Matomo 4.x? https://github.com/matomo-org/matomo/issues/14874#issuecomment-529585366 says it should be fixed?

**Comment by sgiehl** [comment]
@bluikko we meanwhile directly require tedvim/jshrink again, so any requirement of matomo-org/jshrink should be removed.
If you have any similar issues, please create a new issue with a detailed description about the error and how to reproduce

**Comment by bluikko** [comment]
> we meanwhile directly require tedvim/jshrink again

I see - yes, it was about "tedivm" and not "matomo-org". The details are not clear to me right now but seems `vendor/tedivm/jshrink` was needed to be deleted as part of the install. It is an ExtraTools install so uses composer. Might create a new issue if I get the details, it is clearly not related to this issue.

**Comment by sgiehl** [comment]
If it is ExtraTools related, please create an issue in the plugin repo https://github.com/digitalist-se/extratools
