### ISSUE TITLE
Inconsistent Event Total

### ISSUE THREAD

**Issue by rjxp** [matomo-org/matomo#14872]
I have an inconsistency in the presentation of events: For the period 2019-06-04 to 2019-06-14 (range1), the graphical interface outputs 908,740 events for an event. If I increase the period to 2019-06-02 to 2019-06-14 (range2), I get 425.874 (with otherwise the same settings for area and segments). See screenshots range1.png and range2.png:

![range1](https://user-images.githubusercontent.com/40763587/64521726-d17f1600-d2f8-11e9-97e4-5e3e8329ddd9.png)

![range2](https://user-images.githubusercontent.com/40763587/64521770-e3f94f80-d2f8-11e9-8d82-84776b57386a.png)

If I export the data of the time series, I get the correct sum for the first/shorter period (range1) by adding the fields nb_events. For the second period (range2) I get 1,085,064 > 908,740 > 425,874, whereas the dataset for day 2019-06-02 is completely missing. The numbers in the export also match the values you get in the user interface of the time series when hovering over the corresponding day, where the graph for 2019-06-02 drops to zero.

Confidence in Matomo's numbers thus decreases enormously. Actually, I always have to validate the overview values against the export data, which would be very unwieldy. Is there a possibility to check my database against further inconsistencies of this kind?

**Comment by tsteur** [comment]
@rjxp I recommend you invalidate the report for the date range showing a too low value as described in https://matomo.org/faq/how-to/faq_155/ The data should then be archived again and I suppose it will show the correct value then. Hard to say why it doesn't show it the first time there could be many reasons like maybe your server had an issue with archiving etc. Feel free to comment if it still doesn't work after invalidating the report. From our side things are looking good so when the report is invalidated, it should definitely show the correct value.
