### ISSUE TITLE
Unique Visitors metric appear in Graph metric selector for periods for which the metric is disabled

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14881]
Unique Visitors metric appear in Graph metric selector for periods for which the metric is disabled, causing confusion amongst users. And also many support requests to our team.

--> When [Unique Visitors metric is disabled](https://matomo.org/faq/how-to/faq_113/) for the currently selected period, let's hide it from the evolution graph metric picker.

This is what it currently looks like (no data for Unique Visitors): 
![Screenshot from 2019-09-10 16-09-37](https://user-images.githubusercontent.com/466765/64621618-42502c00-d3e6-11e9-9b1b-1348de01dbc7.png)

**Comment by mattab** [comment]
It is working for the main use case, but there is still a little issue:

* Open a weekly report, plot the Unique Visitors metric in the graph.
* Switch to the monthly report by eg. double click on "month" radio in calendar
* The evolution graph still shows Unique Visitors metric with 0 values: 

![Screenshot from 2019-09-30 13-07-59](https://user-images.githubusercontent.com/466765/65841876-8d28e800-e383-11e9-9369-c62f59077bf1.png)


-> Even when the metrics are saved as user preferences, the "Unique visitors" metric preference should be ignored when the Unique Visitors feature is disabled for the currently selected period.

**Comment by mattab** [comment]
@sgiehl are you able to fix this issue maybe?

**Comment by sgiehl** [comment]
@mattab That's are more general problem that needs to be solved. It might always be possible that a metric that is selected for display might become unavailable. E.g. if a plugin metric is chosen and the plugin is disabled.

Also it is not possible to simply remove the metric from the list, as it could then happen that no metric to display remains. In this case a default metric might need to be displayed. But how would such a default metric be determined? The first metric appearing in the report?

Imho we should plan for Matomo 4 to create a metric class for every existing metric. That way we can simply use such classes to check if a metric is available and maybe even use those classes to define alternative metrics to display if one is not available.
