### ISSUE TITLE
Non expected referer_type

### ISSUE THREAD

**Issue by bobivass** [matomo-org/matomo#14893]
Hi,
In Dashboard/Visits Overview I'm getting this error: `Non expected referer_type = 46 - in plugin Referrers`. Also, I'm getting the same error when I try to check Row Evolution of sites, search engines, etc.
Any idea what could be the problem?

**Comment by sgiehl** [comment]
Are you using any additional plugins?

>

**Comment by bobivass** [comment]
No, I'm not using any additional plugins.

**Comment by bobivass** [comment]
I have fixed it - just deactivated and activated the core's plugin Referrers.
