### ISSUE TITLE
Detect when a website uses WordPress, or Wix and link to our relevant guides

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14891]
When a website doesn't yet have data tracked in Matomo, then we could try and detect whether the website is using WordPress or Wix, and then based on this information we could show a special section which links to our guides (with maybe the WP or Wix logo), in the `No data has been recorded yet, get set up below` screen.

The guides we would like to include:
* https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-tracking-code-on-wordpress/
* https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-analytics-tracking-code-on-wix/
* a few more will be created in the next few months

**Comment by mattab** [comment]
This library might be helpful https://github.com/madeITBelgium/Wappalyzer
this is a port of the popular Wappalyzer in PHP

**Comment by tsteur** [comment]
@mattab I believe this was done in https://github.com/matomo-org/matomo/issues/16787 . Can we close it?
