### ISSUE TITLE
Inconsistent reporting API result: "nb_users" reports vastly different results across the same date range when using different ?period=values

### ISSUE THREAD

**Issue by digihiveinc** [matomo-org/matomo#14894]
Hello

When using reporting API the nb_users value is inconsistent for the time range, when the ?period=values is different

Example
/index.php?date=2019-08-01,2019-08-31&period=month&idSite=*&filter_limit=-1&format=JSON&format_metrics=1&expanded=1&module=API&method=API.get

would give a different result in nb_value VS

/index.php?date=2019-08-01,2019-08-31&period=day&idSite=*&filter_limit=-1&format=JSON&format_metrics=1&expanded=1&module=API&method=API.get

In my case the results were
total of 10052 nb_users when calculated by month VS 20285 by day

Same discrepancy happening across the different date range picks.

**Comment by tsteur** [comment]
Hi there,

I suggest you invalidate your reports for the given date ranges see https://matomo.org/faq/how-to/faq_155/ and then wait for the data to be archived again. If the issue still happens, feel free to ping us again with more details and examples. We may also need access to your server to investigate further.

Cheers
