### ISSUE TITLE
Funnels-tracking with two domains leads to wrong exits in funnel

### ISSUE THREAD

**Issue by utrautmann** [matomo-org/matomo#14902]
Funnel tracking seems to have a problem with a funnel configuration which is running over two domains.

Background:
I'm running a website with two domains (www.xyz.com and service.xyz.com). Both domains are covered with my tracking script and both domains are configured as "URLs" for aliases:
_paq.push(["setCookieDomain", "*.xyz.com"]);
_paq.push(["setDomains", ["*.xyz.com"]]);

Now I configured a goal with a funnel:

- The first funnel step is reached at **www**.xyz.com/abc.
- The second funnel step is reached at **service**.xyz.com/secondpath
- The goal is reached  at **service**.xyz.com/successpath

If I set the funnel in the second step with "Path contains" and value "secondpath" then the url service.xyz.com/secondpath will always be wrong listed as exit url in step 1. 
If I set instead the funnel in the second step with "URL starts" oder "URL matches expression" to "service.xyz.com/secondpath" then step 2 is correctly reached in the funnel.

Same problem happens with the goal, when i configured without hostname. The goal is reached in "Goal-statistics", but not reached as goal in the funnel. The Goal-URL is listed as exit url in the funnel.

Do I need to configure the full path in funnels?

**Comment by tsteur** [comment]
Hi @utrautmann 
I've had a quick look at the code and in general it shouldn't have a problem when there are different domains. It doesn't really differentiate between such things as long as you track them into the same site. Maybe one funnel step isn't quite matching or so. 

Could you please get in touch with our support at shop at innocraft.com and post them your issue? They will be happy to have a look and we will investigate further. 

Cheers
