### ISSUE TITLE
Meta: Update Cookie Implementations

### ISSUE THREAD

**Issue by MichaelRoosz** [matomo-org/matomo#14904]
We have lots of open issues with the cookies Matomo is using, so I think it makes sense to collect all relevant issues we have here.

Please feel free to add more tickets and or ideas.

My plan is to find a solution and create mergeable pull requests for all these issues before the end of October so that they can be included in one of the upcoming releases and before the "SameSite" cookie flag changes get released with Chrome 80.

**Cookies Matomo is using at the moment:**

Cookies using the PHP Session Manager:
- Matomo Auth Cookie (MATOMO_SESSID)

Cookies using the PHP Cookie class:
- Opt-Out IgnoreCookie (piwik_ignore)
- 3rd Party Cookie (_pk_uid)
- Language Manager Cookie (matomo_lang)

Cookies used by the JS Tracker (1st party cookies):
- _pk_id
- _pk_ses
- _pk_ref
- _pk_cvar
- mtm_consent
- mtm_consent_removed

**Relevant for all PHP (cookie class and php session) cookies:**
- Feature request: cookie attribute SameSite=Strict #14395

**Relevant for all PHP cookie class cookies:**
- simplified cookies #14444

**Opt-Out IgnoreCookie (piwik_ignore):**
- IgnoreCookie: added support for cookie_domain and ignore cookie signature #13301
- When a user opts-out, do not send any tracking requests to the Tracking API #12767
- Third party cookie in the optout cookie iframe #12454
- Ignore cookie iframe not working when different URL is used for the tracking code than the one - used for the Piwik interface #9466
- Feature request: Separate opt-out for each site #6505

**3rd Party Cookie (_pk_uid):**
- Fix 3rd party cookie / global visitorid race condition #13109
- Tracking Cookie gets set if "DNT=1" #10162

**JS Tracker 1st Party cookies:**
- First party cookies created in multiple domains when using "addTracker" function #14350
- Allow reenabling cookies #13950
- Add possibility to turn cookies back on #13056

**Comment by tsteur** [comment]
Cheers @MichaelHeerklotz  very appreciated

**Comment by mattab** [comment]
Great news is that almost all issues linked here are now closed, so I will also close this one, and thank you for raising these issues back then! Very appreciated. And happy new year! 🎉
