### ISSUE TITLE
Heatmap never gets generated

### ISSUE THREAD

**Issue by alljamin** [matomo-org/matomo#14903]
I'm on Matomo [Business plan](https://matomo.org/pricing/) with a cloud-hosted solution. I'm trying to get heatmaps to work, but no matter what rules I specify I receive the following error:

> No page view has been recorded yet for this heatmap. If there are supposed to be recordings by now, maybe the page targets configured for this heatmap do not match any page on your website. It is also recommended to check the "System Check" under "Administration" (only Super Users) to see if your system is configured to automatically track Heatmaps.

Does not seem to like valid regexp as well:
![Screen Shot 2019-09-20 at 6 09 08 pm](https://user-images.githubusercontent.com/10956179/65312535-de8de600-dbd1-11e9-9bed-0a426abc1719.png)

![Screen Shot 2019-09-20 at 6 11 18 pm](https://user-images.githubusercontent.com/10956179/65312648-1bf27380-dbd2-11e9-9618-801334847377.png)

My account has Super User rights but the "System Check" menu is not available under "Administration" so there is no way to check if my system is configured to track Heatmaps.

![Screen Shot 2019-09-20 at 5 23 37 pm](https://user-images.githubusercontent.com/10956179/65309601-92d83e00-dbcb-11e9-90a4-57d3e5fbe6c6.png)

Here is what the "Administration" menu has:
![Screen Shot 2019-09-20 at 5 30 04 pm](https://user-images.githubusercontent.com/10956179/65309987-653fc480-dbcc-11e9-88b7-5ff347a22b6a.png)

Is there something I am missing in the setup? Any pointers will be highly appreciated

**Comment by tsteur** [comment]
Hi there,

could you get in touch with our support? They will be happy to help. The email is support at matomo.cloud. Cheers
