### ISSUE TITLE
get reports manually for previous months

### ISSUE THREAD

**Issue by extractjan** [matomo-org/matomo#14909]
This is the same question as here
https://github.com/matomo-org/matomo/issues/14066
but the solution doesn't work for me.

I'm using Matomo 3.11.0. When I change the URL parameter of the HTML report and reload the page, I get a white screen with an error
"Sie müssen angemeldet sein, um diese Funktion nutzen zu können."
(in english "You must be logged in to use this feature.")
I am definitely logged in... so what am I missing here?
Any help appreciated..
Thanks

**Comment by tsteur** [comment]
Hi there, could you please ask questions in the forums? We don't answer questions here: https://forum.matomo.org 

In general the suggested solution in #14066 is out of date as the token_auth is no longer in the URL. You need to go to your personal settings, find the token_auth value (32 characters) and append this to the URL like `&token_auth=$token`
