### ISSUE TITLE
Segment the data into smaller groups (Google analytics like Filters inside the Views)

### ISSUE THREAD

**Issue by AlexMisiulia** [matomo-org/matomo#14915]
Hi!

My use case is that I want to divide data at my Analytics for "Technical" and "Product" (similar to Google analytics Filters inside the Views). I know that ideally I should use different log systems for these purposes but know I don't have enough time. Question: Is it possible to divide data into these groups?

For example. This is a visitor log:
- Event: technical info - screen state
- Event: action completed - contact picked - with number 999

When I apply filter "Technical" (only include events with category "technical info") I expect to see:
- Event: technical info - screen state

For "Product" (exclude events with category "technical info"):
- Event: action completed - contact picked - with number 999

I tried "Segments" but it hides the entire information in "Visitor log" if it contains event that I want to exclude from this view.

**Comment by tsteur** [comment]
@AlexMisiulia I recommend you give the latest beta of Matomo 3.12 a try. This might behave the way you want to. The visitor log should show all the information though if you segment AFAIK.
