### ISSUE TITLE
account objects cloud version

### ISSUE THREAD

**Issue by IljaKraval** [matomo-org/matomo#14922]
Hi all,

I see on my page only 2 visits for 3 hours and it is not changing, 
but  it is a lot of visitors in Visitor Log this day.

Any bug ? 

Best regards, 
Ilja

![objects](https://user-images.githubusercontent.com/46327785/65859643-f0595100-e368-11e9-9c17-900cd41a8ae4.png)

**Comment by tsteur** [comment]
@IljaKraval could you ping our support about this? email is support at matomo.cloud. They will be happy to have a look. Thanks
