### ISSUE TITLE
TypeError: $widget.dashboardWidget is not a function

### ISSUE THREAD

**Issue by AramVK** [matomo-org/matomo#14944]
I wanted to re-arange a newly added widget to my dashboard and I noticed the position doesn't get saved. I fired up the console and when dropping the widget after dragging, I see the following error coming up:

`TypeError: $widget.dashboardWidget is not a function index.php:3136:9`

Line 3136:

`$widget.dashboardWidget('reload',false,true);}`

I figured this would be the cause. Running version 3.11.0.

**Comment by tsteur** [comment]
I can't reproduce this here. Any chance you can reproduce this on our demo? https://demo.matomo.org/index.php

Do you know if you're using any third party plugins?

**Comment by AramVK** [comment]
I can reproduce it on that demo as well, by adding a widget. I added User Comments (a Goal). Then I dragged that widget to another position.

`TypeError: $widget.dashboardWidget is not a function index.php:3247:9`

**Comment by tsteur** [comment]
I see. It only happens for some widgets but not for others. In this case it couldn't find the widget element in  https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/Dashboard/javascripts/dashboardObject.js#L450-L452
