### ISSUE TITLE
E-Mail reports not sent

### ISSUE THREAD

**Issue by chris246** [matomo-org/matomo#14940]
Hi,

since August, some monthly email reports are not sent any more.
They are all scheduled for the first day of a month at 2am, but only between 2 and 4 reports are actually sent.
Archiving is done via cron.

**Comment by tsteur** [comment]
Hi there,

could you check your webserver and PHP error logs to see if something is in there?

Also could you enable the logging to a file in Matomo see https://matomo.org/faq/troubleshooting/faq_115/ 
You want to add `log_writers[] = file` to the `[log]` section basically and then see in the log file in the `tmp/logs/matomo.log` file within Matomo if there's any error in there when it didn't send an expected mail.

**Comment by chris246** [comment]
Hi,

thanks. I've enabled it and will report back in about a month, when the next reports are sent

**Comment by Findus23** [comment]
Hi,

Please also take a look at https://github.com/matomo-org/matomo/pull/14467.

Since Matomo 3.10 there is an included command you can use to quickly send a test mail exactly the way the scheduled report would be sent.
Just keep in mind to use the same php as used in the cronjob.

```
sudo -u www-data php console core:test-email test@example.com
```

**Comment by chris246** [comment]
Hi,

the reports for October were all sent.
We moved our database to an SSD in the meantime, so maybe that fixed it (archiving is much faster now).
Maybe, also the latest Matomo update (3.12.0) influenced that, as there were changes to the archiving process?

If you want, to can close this issue.
If it occurs again, I'll write here.

**Comment by tsteur** [comment]
Awesome 👍 feel free to comment again.
