### ISSUE TITLE
Adwords Configuration

### ISSUE THREAD

**Issue by tiurlumbangaol** [matomo-org/matomo#14953]
Hi,
i want to setup Adwords plugin (AOM) in my matomo, i apply for adwords developer token, but the google team reply me with :

Thank you for your response. 
 

According to our [policy](https://support.google.com/adspolicy/answer/6169371?hl=en#pp), any automatic or programmatic use of Google Ads by agencies or end-advertiser clients requires them to use their own Google Ads API (AdWords API) token; you cannot provide indirect access to your API token via APIs that you provide. End users of your tool will need to manually sign in to use your tool, rather than having automatic access, to make manual or programmatic changes to their accounts.

We suggest that you contact Matomo and encourage them to apply for their own developer token for their platform.

What should i do to make the AOM plugin working in matomo? Please advise.

**Comment by tsteur** [comment]
Hi there,
as we don't develop the plugin I recommend you get in touch with the plugin developer directly:
https://github.com/advanced-online-marketing/AOM
