### ISSUE TITLE
Exclude URL query parameters - MVC ID based

### ISSUE THREAD

**Issue by siva538** [matomo-org/matomo#14956]
Hello Matomo team,

We are currently using the feature of "Exclude querystring parameters" and that is helping to a certain extent.

However it doesn't handle the MVC based URLs like mentioned in this link - 

[https://stackoverflow.com/questions/5832598/google-analytics-and-asp-net-mvc-filtering-the-id-out-of-the-url](url)

We were able to handle them using the "setCustomURL" for the module where it is a single page based, but for the native pages, it cannot be used as we just call "trackpageview" and nothing else.

Reaching out to you to seek any thoughts on how to handle such instances.

Few additional examples:

/core/viewlistdetails/120
/administrator/import/ImportRunProgress/12

Thanks in advance.

**Comment by tsteur** [comment]
Thanks for the feature request 👍  If you are familiar with PHP you could write a plugin that is listening to the `Tracker.isExcludedVisit` event. You could then get `$request->getParam('url')` and based on that info set `$excluded = true` in a custom plugin depending on the tracked URL.

The alternative be to add custom url parameters for those pages too using `setCustomUrl`

**Comment by siva538** [comment]
@tsteur , thanks a lot for the guidance. However our requirement is not to exclude the visit altogether, but we wanted to remove the "120" and "12" (id's) from the tracking URL. Is that possible to do so?

Thank you!

**Comment by tsteur** [comment]
@siva538 for questions please ask them in the forum: https://forum.matomo.org
You might want to ask this in the developer forum or so.
