### ISSUE TITLE
Referer URL list for social networks like github and stackoverflow

### ISSUE THREAD

**Issue by cweiske** [matomo-org/matomo#14957]
Matomo 3.11.0 shows a pie chart in Aquisition > Social Networks, but no detail URLs.
In Acquisition > All Channels > Referrers, links from social networks are grouped together and shown with the icon of the network, e.g.

> (social network) GitHub | 61

I'd really like to see the actual URLs where the users came from.
I guess this is not possible for twitter links (because of .t.co referrers) but on stackoverflow and github it is.

**Comment by tsteur** [comment]
>  Aquisition > Social Networks

Can you see the URLs when you switch to the Table visualisation in the bottom left? It should show URLs for social networks then.

**Comment by cweiske** [comment]
This did indeed help, thanks!

Switching to "simple table" lets me expand the networks and see individual urls.
