### ISSUE TITLE
Translate the "Asking for consent" page

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#14954]
I just noticed that the Matomo admin page about "Asking for consent" (`plugins/PrivacyManager/templates/askingForConsent.twig`) is not translatable. As many Matomo users don't speak English, it is odd that such a prominently displayed guide is only shown in English.

**Comment by maxpereira** [comment]
I am going to work on this. Can someone please assign the issue to me? Thanks!

**Comment by Findus23** [comment]
@maxpereira Are you still working on this? Is there some way I can help?
