### ISSUE TITLE
Delete a visitor record?

### ISSUE THREAD

**Issue by qwertz22** [matomo-org/matomo#14966]
[Question / Feature Request]

Hello,

I'm using the newest version of matomo. And I have a lot of visitor records which I want to delete them directly.

I wish a button to delete a visitor's profile (and all of his data).

![2019-10-07 11_06_22-Window](https://user-images.githubusercontent.com/33823543/66298874-bfda5f80-e8f2-11e9-971c-f8fbde881437.png)

Is there a possibility or a external plugin to do that yet? 

Thanks.

**Comment by Findus23** [comment]
Hi,

You can use the GDPR tools to do exactly this.
https://matomo.org/docs/gdpr/#3-right-to-erasure

**Comment by qwertz22** [comment]
Thank you. This plugin is good. But I have to copy the visitor id and paste it into another page. It would be nice to do it directly in the popup of the visitor's profile (see my screenshot).

**Comment by Findus23** [comment]
You are right that a simple button would be useful. This has already been proposed in https://github.com/matomo-org/matomo/issues/14109 and https://github.com/matomo-org/matomo/issues/3385#issuecomment-383769596.
