### ISSUE TITLE
Add new feature to disable custom logo feature

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#14972]
* Add a new setting `enable_custom_logo = 1` under `[General]` in the config
* When feature is disabled, throw an exception in `CoreAdminHome.setBrandingSettings` API
* When feature is disabled, do not show the `div` for that setting in `CoreAdminHome/generalSettings.twig`.
* When feature is disabled, throw an exception in CoreAdminHome controller in `uploadCustomLogo` action.

We don't need to change anything else.

**Comment by alcalyn** [comment]
What is the need behind this issue ?

I'm not sure on how to test it

**Comment by tsteur** [comment]
@alcalyn someone is already working on this issue. Thanks for asking though! Very appreciated.
