### ISSUE TITLE
Show more clearly the freshness of reports when looking at Today or This week

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14977]
When viewing a report where the date includes Today, and when clicking on the help icon next to a report title, one can sometimes see the "Generated X hours Y min ago." information. This gives the freshness of the report:

![Screenshot from 2019-10-07 23-19-33](https://user-images.githubusercontent.com/466765/66468671-0bebf680-eae3-11e9-87e1-755313ac9402.png)

It's a common frustration point to not know when were the reports processed, and not knowing whether the current report may be inaccurate because it was processed hours ago. "When was this data processed?" people ask themselves.

How could we make the situation more clear?
* could we also display the freshness info with a subtle time icon: "(icon) 5 hours ago" or "(icon) 34 min ago", on the top right (Selector bar), when date includes today?
* show this freshness info in the help infobox on all report titles. Currently the freshness is not visible under Evolution graphs and likely other reports too. We expect this info to show on all pre-processed reports (except a few specific which are not actual aggregated reports like all real-time reports).
* ...

**Comment by jmumby** [comment]
Showing the time the report will be updated would be good also. It is good to know how fresh a report is, I would also want to know when the report will be updated next.

**Comment by flamisz** [comment]
@mattab where would be this icon and text exactly? Pos1, pos2, pos3 or somewhere else?

<img width="1440" alt="Screen Shot 2021-04-16 at 3 23 23 PM" src="https://user-images.githubusercontent.com/6749509/114967213-249f4e80-9ec8-11eb-8964-48d21341da1b.png">

**Comment by mattab** [comment]
Maybe Pos3 or Pos1? (only when the date range is, or includes, today)

**Comment by flamisz** [comment]
Hi @mattab, I looked into this issue and had a chat with @tsteur as well about it.

Showing a generated date on the top of the page is not that clear every time, as the page contains more reports, and that can happen, the data was not generated at the same time for every one of them.

But what I see is not easy to find this information currently on the UI, what if we improve that part? We can add a small time/clock icon to every report and hovering that icon will show the reported time. Could that work for you? Maybe the icon can be permanent if the date range contains today, not just showing it when the user hovers the header of the report.

Let me know what you think about this solution.

**Comment by mattab** [comment]
> But what I see is not easy to find this information currently on the UI, what if we improve that part? 

:+1: 

> We can add a small time/clock icon to every report and hovering that icon will show the reported time. Could that work for you? Maybe the icon can be permanent if the date range contains today, not just showing it when the user hovers the header of the report.

:+1:  that could work well, would be helpful to see what it could look like.

**Comment by flamisz** [comment]
@mattab and @tsteur that's what I had in my mind. A permanent small icon, when the date range contains today and we have the report generated time. I can add it to more reports probably.
The icon is a pie chart on the video, I will add a proper clock later.

What are your thoughts? Should we show the icon permanently or just on hover like the others? It is smaller and lighter than the others now. 

Instead of the tooltip, it can be something hidden until we hover it, like in the second video.

https://user-images.githubusercontent.com/6749509/115791366-69713b00-a41c-11eb-8519-ddb87efd6e5e.mov

https://user-images.githubusercontent.com/6749509/115792111-cf11f700-a41d-11eb-8aa0-e31f4cceb399.mov

**Comment by mattab** [comment]
@flamisz Video 1 looks good to me :+1:
