### ISSUE TITLE
Some reports (eg. Channel Type) show no columns in date comparison mode

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14984]
reproduced at: [demo url](https://demo.matomo.org/index.php?module=CoreHome&action=index&date=2019-10-09&period=day&idSite=1#?idSite=1&period=month&date=2019-09-18&segment=&category=Referrers_Referrers&subcategory=Referrers_WidgetGetAll&compareDates%5B%5D=2018-09-01,2018-09-30&comparePeriods%5B%5D=range)

Here is what we see:

![Screenshot from 2019-10-10 16-43-09](https://user-images.githubusercontent.com/466765/66537505-2672ae00-eb7d-11e9-8bf7-85a6051d0018.png)

The columns are missing. 
Note that when removing comparison mode again, the state will be also broken then for non-comparison mode, and not show any column also.

Workaround: currently it's possible to display the columns as expected with a few extra clickks:
* Click the second icon below the report
* Select `Display simple table`
* Then we get the columns correctly in comparison mode.

 

Expected to see the columns like in non-comparison mode.

**Comment by sgiehl** [comment]
I'm not able to reproduce that. For me the table is scrollable to the right and all columns are there.
Might those columns only be hidden from visible space and related to #15053

**Comment by tsteur** [comment]
works for me too

**Comment by sgiehl** [comment]
Still works for me. @mattab could you check if you are able to reproduce that issue?

**Comment by mattab** [comment]
cannot reproduce anymore :+1:
