### ISSUE TITLE
Under "Comparisons" use the same date format for all periods

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14986]
### Reproduce:
* Select month of September
* In calendar, click "Compare" and select **"Compare to: previous period"**
* Git under "Comparisons" 
  * August 2019 (Month)
  * From 2018-08-01 to 2018-08-31 (Range) 
* Expected instead 
  * August 2019 (Month)
  * August 2018 (Month) 

It works this way already when selecting "Compare to: Previous period". 

### Got

![Screenshot from 2019-10-10 17-21-40](https://user-images.githubusercontent.com/466765/66538994-1958bd80-eb83-11e9-8280-38922737c82a.png)

**Comment by tsteur** [comment]
Looks like this is fixed.
