### ISSUE TITLE
LDAP Injection

### ISSUE THREAD

**Issue by JeyakumarThangaraj** [matomo-org/matomo#14987]
Dear Team,

LDAP injection has found on piwik request in both android and IOS. Kindly advise how to resolve this issue. Please find Reference - https://github.com/matomo-org/matomo-sdk-android/issues/266

Find the details below:
LDAP injection attempt ( uid )

• Signature Type :Request
• Attack Type :LDAP Injection
• Accuracy :Low
• Risk :Low

Regards,
Jeyakumar

![image](https://user-images.githubusercontent.com/49137580/66560331-d802e680-eb5f-11e9-9996-045862c7b08b.png)

**Comment by Findus23** [comment]
As I already mentioned in https://github.com/matomo-org/matomo-sdk-android/issues/266#issuecomment-539550618:
Please use the intended ways to report security issues (so Hackerone or a mail to security@matomo.org). 
And most importantly, please provide more details:
- What exactly is the security issue?
- How can I reproduce it?
- How can an attacker use this?
- What would an attacker get access to?
- What are the security implications?
