### ISSUE TITLE
Visitors/Visits log : View visitor profile is only displayed on first page

### ISSUE THREAD

**Issue by eldk** [matomo-org/matomo#14998]
Hello,

- Matomo 3.12.0-b7 and b6
- Firefox 69 or Chromium 79

Except on first load for Visitors/Visits log, link "View visitor profile" is not displayed when :
- click on next page
- change number of row to display

To reproduce : 

1 - go to Visitor/Visits Log
2 - click at bottom on next or change number of row to display from 10 to another one.

Should you reproduce ?

Thanks,

Eric

**Comment by tsteur** [comment]
@eldk tried to reproduce this for quite a while but couldn't. Anyone else can reproduce this maybe?

**Comment by eldk** [comment]
Hello,

Same in 3.12.0-rc1. Maybe this is something in my config. I'll have a look to find missing step(s) to reproduce.

Thanks,

Eric

**Comment by tsteur** [comment]
Thanks @eldk that be great

**Comment by eldk** [comment]
Hello,

Webserver access logs :

First access to Visitors/Visits Log - profile links available : 

`/index.php?forceView=1&viewDataTable=VisitorLog&module=Live&action=getLastVisitsDetails&small=1&idSite=7&period=range&date=2019-10-01,2019-10-17&segment=&showtitle=1&random=7834`

Clic on next - profile links missing: 

`/index.php?date=2019-10-01,2019-10-17&viewDataTable=VisitorLog&smallWidth=true&hideProfileLink=false&pageUrlNotDefined=Page+URL+not+defined&forceView=1&module=Live&action=getLastVisitsDetails&small=1&idSite=7&period=range&random=2641&filter_offset=10&totals=0&filter_limit=10&filter_sort_order=desc`

Should hideProfileLink=false be hideProfileLink=0  (https://github.com/matomo-org/matomo/search?q=hideProfileLink&unscoped_q=hideProfileLink)?

Thanks,

Eric

**Comment by eldk** [comment]
add 

```twig
 <pre>
    {{ dump(clientSideParameters.hideProfileLink) }}
</pre>
```

return : 

`bool(false)` on first page

but : 

`string(5) "false"` on next page.

https://neptune.opalesurfcasting.net/index.php?module=CoreHome&action=index&idSite=5&period=year&date=today#?idSite=5&period=year&date=today&segment=&category=General_Visitors&subcategory=Live_VisitorLog

**Comment by tsteur** [comment]
Yes that makes sense indeed. I'm actually really sorry as I didn't read your issue properly and somehow missed the part it's only around profile link.

This has been an issue for a while by the looks or probably always been an issue if I see this right.

Created https://github.com/matomo-org/matomo/pull/15020

**Comment by eldk** [comment]
Ok thanks, this is solved.
