### ISSUE TITLE
Create write/master - read connection string options

### ISSUE THREAD

**Issue by sw-waterford** [matomo-org/matomo#15013]
With the introduction of AWS Aurora it would be extremely helpful to segment read-only and write traffic so that users can take advantage of clustering this was requested back in 2015 I don't see any option for it to date is this something in the current roadmap for the tool?

**Comment by tsteur** [comment]
Hi @sw-waterford see https://matomo.org/faq/how-to-install/faq_35746/ on how to configure it.

**Comment by sw-waterford** [comment]
Thanks! missed this when reviewing the documentation and couldn't find it in the closed issues prior to submitting
