### ISSUE TITLE
Web Cron error since 3.12 beta 7

### ISSUE THREAD

**Issue by pioc92** [matomo-org/matomo#15012]
Hi all,
i have a matomo install on a shared hosting with a webcron (https://mydomain.fr/misc/cron/archive.php?token_auth=xxxxxx)
Since matomo beta 7 3.12, my cron failed with this error

Error: Entry &quot;Piwik\Plugins\Monolog\Formatter\LineMessageFormatter&quot; cannot be resolved: Parameter $logMessageFormat of __construct() has no value defined or guessable
Full definition:
Object (
    class = Piwik\Plugins\Monolog\Formatter\LineMessageFormatter
    scope = singleton
    lazy = false
    __construct(
        $logMessageFormat = #UNDEFINED#
        $allowInlineLineBreaks = (default value) true
    )
)
Archiving on report visiting is working fine if i enable it.
Do you have an idea?

**Comment by pioc92** [comment]
I tried the last rc1 and error persists

**Comment by Findus23** [comment]
I can reproduce this locally.

**Comment by tsteur** [comment]
Thanks! That should be fixed
