### ISSUE TITLE
Show periods labels in the evolution graphs to make it easier to change period

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15021]
Since #955 and https://github.com/matomo-org/matomo/pull/13689  Evolution graphs show a button to switch the display of historical data by day, week, month or year, it looks like [this:](https://media.githubusercontent.com/media/matomo-org/matomo/218087c66b491f067b758001bc811297b8ea7528/tests/UI/expected-screenshots/EvolutionGraph_periods_list.png) 

![EvolutionGraph_periods_list](https://user-images.githubusercontent.com/466765/67073684-1c3b5a00-f1e4-11e9-9cb3-1f18d6debc98.png)

The feature is a little hidden. Be great to make it easier to discover this feature.

Thoughts:

*  we show the buttons always on the graph? Something like this:
![2-no-constancy](https://user-images.githubusercontent.com/466765/67073746-3ecd7300-f1e4-11e9-9c62-e115b54827b1.gif)

* or maybe the current selected period could be displayed as text next to the icon at the bottom right, so it more clearly appears as clickable?

**Comment by flamisz** [comment]
Hi @mattab, 
how do you feel about putting it under the graph, like in the middle. This is probably the quickest way, but of course it can be on the top right, but probably takes more time.

<img width="811" alt="Screen Shot 2021-04-08 at 3 31 25 PM" src="https://user-images.githubusercontent.com/6749509/113964452-a4516b80-987f-11eb-989a-fba68c0dfea2.png">

This would be visible every time (not just when hovered) and of course would be better formatted with css.

**Comment by mattab** [comment]
@flamisz I reckon we might not want to show all the 4 states at all times (too much info/pixels). But showing the text label of the current state, will "hint" users that other states are available (and which one they're currently looking at).

 maybe we could try to move the icon to the right, and adding the text label on the right of the icon, like roughly on this mockup, could work? No idea if it will feel right but it might. Then on hover the icon+text would have the colored background. And show the select list on hover. 

![edited Screenshot from 2021-04-09 17-35-28](https://user-images.githubusercontent.com/466765/114133883-dbe11600-995a-11eb-9fd5-c61438463a66.png)

**Comment by flamisz** [comment]
thanks @mattab, I can make today a quick change, so you can see it feels. I'll let you know when it's ready.

**Comment by flamisz** [comment]
@mattab this is a short video how could it look like:

https://user-images.githubusercontent.com/6749509/114372416-a09e4b80-9bd5-11eb-9b5c-ea095fdd08a3.mov

simple change in the less file and adding some styles.

**Comment by mattab** [comment]
Nice! it looks good to me.
 (would write the label like the submenu font: same size, and case)
