### ISSUE TITLE
Entry pages segmented visitor log is showing wrong URLS

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#15027]
Issue: When viewing the segmented visits log for a particular URL under "Behaviour > Entry pages", it's displaying the wrong URLs as the entry page.

Steps to reproduce:
1.  Navigate to Behavior->Entry Pages
2.  Ensure the View Mode is Flat (not Hierarchical)
3. Sort by Entrances descending (most common entrance page at the top)
4. View Segmented Visitor Log for first item
5. Observe that the header of the page is "Visit Log showing visits where Entry Page URL is "[correct URL]" the entry page for the first URL is not correct

_Note: this is reproducible in the demo site at https://demo.matomo.org (Site: Demo-Site, date: 2019-09-25, Segment: All Visits)_

Screenshot
![Screenshot from 2019-10-21 14-03-01](https://user-images.githubusercontent.com/26726594/67170021-98fc4d00-f40b-11e9-8970-c26198135be9.png)

**Comment by tsteur** [comment]
Thanks @KarthikRaja1388

**Comment by pebosi** [comment]
Seems to be fixed, can't reproduce in demo or my own installation

**Comment by dktcoding** [comment]
This is happening to me too, even when using `Only track visits and actions when the action URL starts with one of the above URLs`.

So far I tried invalidating the reports and regenerating them (which took almost 4 days to no effect). 

Any clues on how to solve it?

We currently track a few moodle installations from a public university (around half a million students) and with the current epidemiological situation people started having time for statistics...

**Comment by dktcoding** [comment]
In the example it shows that the user was first seen 4 days ago, but the visit log show an entry from one year ago, on another site.

![Screenshot_20200404_031805](https://user-images.githubusercontent.com/709639/78420164-05b67d00-7623-11ea-9138-9aface46d5cc.png)

I tried deleting all the caches, doing `mysqlcheck -o` and when doing:

```sql
SELECT * FROM matomo_log_visit 
LEFT JOIN matomo_log_link_visit_action ON matomo_log_visit.idvisit = matomo_log_link_visit_action.idvisit 
LEFT JOIN matomo_log_action ON matomo_log_action.idaction = matomo_log_link_visit_action.idaction_url 
LEFT JOIN matomo_log_conversion ON matomo_log_visit.idvisit = matomo_log_conversion.idvisit 
WHERE idvisitor = UNHEX('ee9a851e8ae7131c');
```

It retrieves all of the correct results that are shown (not the incorrect ones)...

Any clues? I would really hate to loose 3 years worth of statistics and then have it happening again...

**Comment by tsteur** [comment]
@dktcoding this sounds like a different issue and I recommend you create a new issue for this. We may need access to your Matomo if possible to understand things. Like you could create a user with view access for us and send us the credentials to hello at matomo dot org.

**Comment by mattab** [comment]
This seems fixed, @KarthikRaja1388 please re-open if you can still reproduce this
