### ISSUE TITLE
3.12.0-rc1: No dashboard graph anymore?

### ISSUE THREAD

**Issue by dertuxmalwieder** [matomo-org/matomo#15033]
When updating my Matomo installation from the last 3.12.0 beta version to 3.12.0-rc1, the graph of recent visitors in my dashboard stopped working:

![HEgfZvJ](https://user-images.githubusercontent.com/125629/67253375-9df6e600-f477-11e9-97b4-27431fd43322.png)

This does *not* mean that suddenly nobody cares about my website anymore. The graph on the Visitors page works:

![ox8Gsct](https://user-images.githubusercontent.com/125629/67253385-ab13d500-f477-11e9-8f7d-29aa37fd17cb.png)

So does the other visitors dashboard graph:

![wjTlavF](https://user-images.githubusercontent.com/125629/67253406-c848a380-f477-11e9-86eb-c5ac24d5852f.png)

I really prefer the "Graph der letzten Besuche" though. It is less *roomy*.

**Comment by tsteur** [comment]
Only thing I can image is that it's related to https://github.com/matomo-org/matomo/compare/3.12.0-b7...3.12.0-rc1#diff-2c49596f288bc707bfda47f4b648bc57R241 but I can't reproduce it and it would be maybe only an issue if unique visitors was selected before. @sgiehl any thoughts?

**Comment by tsteur** [comment]
@dertuxmalwieder does it work when you remove the widget and add it again?

**Comment by dertuxmalwieder** [comment]
Sadly, it does not.

**Comment by tsteur** [comment]
Do you know if you have any custom configurations in your `config/config.ini.php`? Any chance you have eg `enable_processing_unique_visitors_day` disabled? By looking at the image I suppose you're viewing day when this happens?

**Comment by tsteur** [comment]
Any chance you could try this patch @dertuxmalwieder ? https://github.com/matomo-org/matomo/pull/15038/files

**Comment by dertuxmalwieder** [comment]
The patch fixes it! :-) Thank you.

No custom configuration involved.
