### ISSUE TITLE
Running Matomo Serverless?

### ISSUE THREAD

**Issue by marktopper** [matomo-org/matomo#15043]
Are there any plans to support running Matomo serverless on something like App Engine og Lambda?

**Comment by tsteur** [comment]
Hi there, be good to ask this question on our forum: https://forum.matomo.org

Or be more specific in what is not working / needed to make this happen. We have no specific plans to work on supporting this use case but we may be able to add/change certain things to support this. But really depends what is exactly not working currently to support this etc.
