### ISSUE TITLE
Page Title names are not truncated anymore

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15053]
Seen in https://demo.matomo.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=62&updated=1#?idSite=62&period=week&date=today&segment=&category=General_Actions&subcategory=Actions_SubmenuPageTitles

![Screenshot from 2019-10-24 20-21-06](https://user-images.githubusercontent.com/466765/67462340-d4ad4600-f69b-11e9-850b-c91dc4a5ad6d.png)

it seems the labels are not truncated anymore and therefore the metrics not visible and require scrolling?

**Comment by tsteur** [comment]
Can't reproduce this. Maybe an issue with your browser since others couldn't reproduce it either?

**Comment by eldk** [comment]
Hello,

Same here : 

- Firefox 69.0.1 :

![Screenshot_2019-10-25 Demo-Site - De 2019-10-21 à 2019-10-27 - Rapports des statistiques web - Matomo](https://user-images.githubusercontent.com/11083657/67531330-911a0280-f6c2-11e9-9b79-d0e247aa1ca5.png)

**Comment by eldk** [comment]
If you reduce the browser window or move it, then, make it fit the screen (reduce/epand) :  the reflow make the table fit as it have to be : 

![Screenshot_2019-10-25 Demo-Site - De 2019-10-21 à 2019-10-27 - Rapports des statistiques web - Matomo(3)](https://user-images.githubusercontent.com/11083657/67532164-89a82880-f6c5-11e9-9bcc-8b5028a17016.png)
