### ISSUE TITLE
Matomo UserID specific report

### ISSUE THREAD

**Issue by dieskim** [matomo-org/matomo#15051]
I am using Matomo UserID to track users - https://matomo.org/docs/user-id/#user-id-report

What I am not able to figure out is how I can view the Report of that actual user via the UserID - I know I can view the report of the user via their visitorID with a link like

https://host.com/index.php?date=today&module=Widgetize&action=iframe&visitorId=12341234&showMap=0&idSite=1&period=day&moduleToWidgetize=Live&actionToWidgetize=getVisitorProfilePopup

but I would like to view the report of the user via the UserID.

maybe adding to the Widgetize module  so as to allow

https://host.com/index.php?date=today&module=Widgetize&action=iframe&userId=12341234&showMap=0&idSite=1&period=day&moduleToWidgetize=Live&actionToWidgetize=getVisitorProfilePopup

Any help would be appreciated, Thanks

**Comment by tsteur** [comment]
@dieskim be good to ask questions in the forum: https://forum.matomo.org

Basically you will need to first find out the visitorId for example using a `userId` segment and then generate the link with the visitorId. Actually, it might be even enough to simply add the userId segment without any visitorId https://developer.matomo.org/api-reference/reporting-api-segmentation

**Comment by dieskim** [comment]
ok thanks just FYI this worked = https://host.com/index.php?date=today&module=Widgetize&action=iframe&idSite=1&period=day&segment=userId==12341234&moduleToWidgetize=Live&actionToWidgetize=getVisitorProfilePopup
