### ISSUE TITLE
Custom Reports: 3.11 cloud

### ISSUE THREAD

**Issue by sysadmin12** [matomo-org/matomo#15061]
Dropping this off here from the forums as it seems to be the next place to go after:

A custom report that has a dimension with an Action dimension, and a related metric of a conversion count for a goal, shows a conversion count that is significantly wrong from the base goal conversion count value.

By significantly, I mean many multiple times off.

For example, a goal set on a basic conversion match criteria (matches a contains of a URL match with multiple allowed per visit) where an action dimension is also logged on the same page shows an incredibly high over-count. What seems to further compound it is if events are logged on the same page.

To be specific, We have a page where an action dim is logged, several events (between 18-20) are also logged and a goal is also logged. To give an example of the differences, the goal conversion rate, looking at the goal report could be 80 for goal conversion, while the custom report that pivots off of the action dimension could total 850 for goal conversion, and the event if included in its own custom report could be hundreds more or less than the dimension count.

Our guess is that the conversion count for a dimension in a custom report also includes the events as and actions vs. just the goal count. Regardless, it’s way, way off. Happy to provide more detailed info to help resolve.

**Comment by mattab** [comment]
Hi there, if you're using Cloud please reach out to the cloud support team directly, we will assist you there. Thanks!
