### ISSUE TITLE
WARNING after update to 3.12

### ISSUE THREAD

**Issue by Wolic** [matomo-org/matomo#15072]
Hello,

after the update to version 3.12 of Matomo i got the following warning on the overview:

`WARNING: /www/htdocs/xxxx/piwik/core/DataTable/Renderer/Console.php(152): Notice - Array to string conversion - Matomo 3.12.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: VisitsSummary, Action: getEvolutionGraph, In CLI mode: false)`

**Comment by tsteur** [comment]
@Wolic cheers, that was already happening in earlier versions and will be fixed in https://github.com/matomo-org/matomo/pull/15037

**Comment by Wolic** [comment]
@tsteur Oh okay, i didnt noticed this open issue during the search.
