### ISSUE TITLE
Document Mysql user needs new "CREATE TEMPORARY TABLES" permission

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#15084]
See https://dev.mysql.com/doc/refman/5.7/en/privileges-provided.html#priv_create-temporary-tables
Since Matomo 3.12 it seems this new permission is needed. Not sure if we somewhere document needed permissions? Would either need to add it, or document the list in general.

AFAIK this requirements are needed at least

* CREATE, DELETE, DROP, INSERT, SELECT, UPDATE, LOCK TABLES, CREATE TEMPORARY TABLES, ALTER, INDEX

**Comment by diosmosis** [comment]
Looks like it's already documented? https://matomo.org/docs/requirements/#mysql-user-requirements

**Comment by tsteur** [comment]
👍
