### ISSUE TITLE
Upgrade to Matomo 3.12.0 error

### ISSUE THREAD

**Issue by Laul0** [matomo-org/matomo#15081]
# Summary

My current environment is based on a Docker container. I chose to update Matomo by pulling the latest version and then, launch the update from the UI.
After that, I had to upgrade the database.

# Current behavior

Since upgrade server, most of widgets in my dashboard are in error.
The only thing that works currently are:
- Visits log page
- Real-time
- Real-time map

<img width="1533" alt="Screen Shot 2019-10-30 at 09 06 34" src="https://user-images.githubusercontent.com/15279205/67860652-cb393900-faf4-11e9-864f-380e16a53a75.png">

**Comment by Laul0** [comment]
Ok I fixed it!

1. After dropping table, backup.
2. Try to DROP database = error 39 😢
3. Remove database folder (remove files "system")
4. Create new database with the same name
5. Import data from the backup

Now, it works again.

**Comment by tsteur** [comment]
Thanks for letting us know
