### ISSUE TITLE
Custom reports missing metric

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/matomo#15091]
Hi there,
In the custom report premium feature the metric Downloads is missing. There is Unique Download URLs but Downloads is missing.
The typical use case is the following one. Someone want to look at the download report but need sub-reports for each type of document format. One for xls files, one for pdf, one for jpg...

**Comment by tsteur** [comment]
@Chardonneaur be good to email our support on how to do this: shop at innocraft.com. I didn't check what is available on metrics/dimensions but you can probably segment by action type = downloads and select the hits metric.
