### ISSUE TITLE
mysql syntax error on upgrade to 3.12

### ISSUE THREAD

**Issue by JugurthaK** [matomo-org/matomo#15100]
Hello guys,

Tried to upgrade Matomo from 3.11 to 3.12,

Seems there is something wrong with the defined charset on some plugins, here is the error code I have when I run install.php :

```SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near &#039;DEFAULT CHARSET=utf8&#039; at line 4```

Its happening during the installation of LanguagesManager, but even if I disable it, its still happening with Dashboard then with ScheduledReports etc.. They're some plugins who aren't involved. But these _(LanguagesManager, Dashboard, ScheduledReports, PrivacyManager, SegmentEditor)_ returning the same error.

Btw I dont know if the `&#039` charcode is generated by my logs console, or is interpreted by mysql.. 

I've dumped the database, and on table `piwik_plugin_setting` the `DEFAULT CHARSET=utf8` do not contain any `'` char.. 

Its my first issue on Github, sorry if there is not enough informations, I'm available if you need more.

And I'm french, sorry for my bad english.

Best regards,

**Comment by sgiehl** [comment]
>  here is the error code I have when I run install.php

@JugurthaK How exactly are you trying to do the update? Did you click the auto update button in UI or did you execute a `./console core:update`?

**Comment by JugurthaK** [comment]
I'm using a deployment system, so I downloaded the new archive, unzip it, creating my own config.ini.php then running a script (called install.php) to install everything.

**Comment by sgiehl** [comment]
what exactly is the install.php script doing? maybe you could paste it's content.
Normally it should be enough to replace all the files and execute a `./console core:update` afterwards to do an update.

**Comment by JugurthaK** [comment]
https://gist.github.com/JugurthaK/2cfe4b74c26e6880ae515ae807e0890d

There is the install.php script. As you can see on line 273, its already doing a .`./console core:update`

**Comment by sgiehl** [comment]
But besides copying the files only a `./console core:update` should be needed. Haven't looked at the whole script, but it seems to do a lot stuff that is not needed...

**Comment by JugurthaK** [comment]
So, you advice me to only do a ./console core:update, or should I download the new archive before ?

**Comment by sgiehl** [comment]
you need to download the archive before and replace all files with the contents of it. The only file you need to keep from the old install is your config.ini.php. Afterwards you can run a `./console core:update`

**Comment by JugurthaK** [comment]
The `./console core:update` returns a warning to activate the Login plugin (because we're using Ldap Login by default), I did it and after that its telling me `Everything is already up to date.`

**Comment by sgiehl** [comment]
`./console core:update` will only do anything if database updates are required or any other operation needs to be done in order to update anything. If it doesn't do anything, that means the last update didn't include such changes.

See https://matomo.org/docs/update for more information on how to update Matomo
