### ISSUE TITLE
Matomo 3.12.0 missing Action in Proxy module

### ISSUE THREAD

**Issue by tassoman** [matomo-org/matomo#15101]
Hello there, we have tried upgrading Piwik to Matomo 3.12.0 but after the `php console core:update` command we had some problems:

 - PHP Notice error in Monolog Formatter
 - Css is missing and opening it you get an error page saying _Action not found in the module 'Proxy'_

`php console diagnostics:run` gives back no relevant errors. I've attached screenshots of the web gui. 

![screen-home](https://user-images.githubusercontent.com/92727/68120248-1a240b80-ff05-11e9-96ea-5acd4f773ff2.png)

![screen-css](https://user-images.githubusercontent.com/92727/68120253-1d1efc00-ff05-11e9-9572-e1ca769e305b.png)

**Comment by tsteur** [comment]
@tassoman created PR for the linemessageformatter in https://github.com/matomo-org/matomo/pull/15105

Not sure though why you would get the proxy error. Could you apply the patch in #15105 and then check our tmp/log/matomo.log file if there's any error in there?

**Comment by tassoman** [comment]
Hello @tsteur the problem with empty action in Proxy module was solved with your patch. 
(I applied a raw brutal cut-n-paste in the code)
I think the problem with CSS was given by the notice error html output before sending real headers to the client, so it was missing text/css content type or something like that.
Thank you team for fast caring :top:
