### ISSUE TITLE
Red error band is getting flashed when loading reports

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#15108]
Issue: A red mysql error band is getting flashed for a very short period, when loading reports. It doesn't stay for a long time.

Steps to reproduce:

1. Login to Matomo
2. Try to load some reports

**Comment by tsteur** [comment]
@KarthikRaja1388 Can you show exactly which error is being shown there? Otherwise we can't do anything. They could enable logging to file to get more details.

**Comment by KarthikRaja1388** [comment]
@tsteur It's really hard to capture the screenshot of it, but i will try

**Comment by tsteur** [comment]
@KarthikRaja1388 enabling logging to file  and check out the log file see https://matomo.org/faq/troubleshooting/faq_115/

**Comment by mattab** [comment]
Duplicates: https://github.com/matomo-org/matomo/issues/15287
