### ISSUE TITLE
Whitelabel plugin (Innocraft) hides all "About Matomo" widgets

### ISSUE THREAD

**Issue by MichaelHeerklotz** [matomo-org/matomo#15104]
The Innocraft Whitelabel plugin adds a "Widget.filterWidgets" hook callback called 'removeWidgets' which removes all widgets with setCategoryId('About Matomo').

Since a related change in Matomo 3.12.0 this will hide admin widgets like "System Summary" and "Tracking failures".

It would be great if the plugin had an option to disable this behavior.

**Comment by sgiehl** [comment]
guess that's related to #14930
ping @tsteur

**Comment by tsteur** [comment]
@MichaelHeerklotz can you email our support shop at innocraft.com about this? That be great. Cheers
