### ISSUE TITLE
Load more in Visitor Profile doesn't load actions

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#15111]
Reported in https://forum.matomo.org/t/visitor-profile-bug/34827 and can be reproduced in demo

> When I press ‘Load more visits’ button, the only thing that loads is headers of visits and info about it, but not actions. When I press then say ‘64 actions in 39 min 42s’ in loaded visits after previous press - nothing happens. Maybe this is intended? Then how I can view older actions of visitor?
>
> Problem can be reproduced on your demo site:
https://demo.matomo.org/index.php?date=yesterday&module=Widgetize&action=iframe&visitorId=71f83188eb658d7b&idSite=62&period=day&moduleToWidgetize=Live&actionToWidgetize=getVisitorProfilePopup

**Comment by KALLIAK** [comment]
This problem also exists in 3.11 version

**Comment by KALLIAK** [comment]
It seems that bug was fixed in 3.13.5 (https://github.com/matomo-org/matomo/pull/15750)
