### ISSUE TITLE
Column Title alignment in Custom report is inconsistent

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#15118]
Issue: Column title alignment in custom report is inconsistent. When viewing a custom report with multiple dimensions by making the report flat and choosing "show dimensions separately", first Column title is left aligned and others are right aligned.

![image](https://user-images.githubusercontent.com/26726594/68259276-5179f000-009e-11ea-9cac-9bf6be68318f.png)

Steps to reproduce:

1. Create a Custom Report with more than one dimension
2. View the report
3. Click on "Cog icon" on the bottom left of the report
4. Click on "Make it flat"
5. Click on "Cog icon" on the bottom left of the report
6. Click on "Show dimensions separately"

**Comment by tsteur** [comment]
fyi this is a core issue and also happening for events etc. Probably a regression?

**Comment by tsteur** [comment]
It works for me in 3.11
