### ISSUE TITLE
Feature: Allow Copy of Segments

### ISSUE THREAD

**Issue by mstenz** [matomo-org/matomo#15126]
Some segments are vey complex and maybe you want one with just slightly different setting. 
Right now you need a complete vanilla segment and create from scratch. Having the ability to copy an existing Segment would really help in our environment where we have a lot of Segments (both globally and for seperate users).

**Comment by tsteur** [comment]
Cheers @mstenz for the feature suggestion 👍

**Comment by Stan-vw** [comment]
Closing as it seems like a duplicate of #7246
