### ISSUE TITLE
Considering the facebook/xhprof package is deprecated

### ISSUE THREAD

**Issue by peter279k** [matomo-org/matomo#15120]
As title. Firstly, we look at the `require-dev` block on `composer.json`, we can notice that it requires the `facebook/xhprof`.
After visiting this package page via the [Packagist link](https://packagist.org/packages/facebook/xhprof), I aware that following deprecated warning message:

```
This package is abandoned and no longer maintained. The author suggests using the lox/xhprof package instead. 
```

And I think we should also use the new package to replace the `facebook/xhprof ` :).

**Comment by tsteur** [comment]
👍 totally. Feel free to create a PR 👍

**Comment by tsteur** [comment]
Our profiler supports for example tideways profiler (not the remove service but the php extension)

**Comment by tsteur** [comment]
Actually, closing this for now as xhprof was updated just last month.
