### ISSUE TITLE
Extend Diagnostic Checks with Temporary Table Feature of mysql

### ISSUE THREAD

**Issue by mstenz** [matomo-org/matomo#15132]
in this commit  first time a new mysql feature about temporary Tables was used: https://github.com/matomo-org/matomo/commit/7795db37be3dd75d0a26e617ffc4ed3c2af83587

I think this should be added as new Check in the Diagnostic Page because not all platforms (expecially when you use mysql loadbalancers like proxysql) may support this.

**Comment by sgiehl** [comment]
refs #15084

**Comment by sgiehl** [comment]
fixed with #15139, will be included in Matomo 4
