### ISSUE TITLE
Link to a helpful FAQ in the error message "Oops, there was a problem during the request."

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15135]
Often Matomo users who haven't yet setup Cron + Disable browser trigger archiving, ![index](https://user-images.githubusercontent.com/466765/68448379-3519b700-0248-11ea-870f-4ee84f9516be.png)

It would be great to link from this message to the FAQ that explains this issue: https://matomo.org/faq/troubleshooting/faq_19489/

Maybe with append a text like `<a href='https://matomo.org/faq/troubleshooting/faq_19489/'>See the steps to resolve this issue in the FAQ</a>.`. 

Note:
* we don't want this extra text to be added on cloud. maybe we could link to the FAQ only when `enable_general_settings_admin=1` or `enable_plugins_admin=1`
* we will soon improve the FAQ at https://matomo.org/faq/troubleshooting/faq_19489/ and make it more clear / better

**Comment by geekdenz** [comment]
There seems to be something already here:

https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/MultiSites/angularjs/dashboard/dashboard.directive.html#L61-L70

Also, I have trouble reproducing this error. Could you give me an example URL fragment?

**Comment by tsteur** [comment]
@geekdenz 

you can apply below patch and then go to `Behavior -> Page URLs` in the reporting menu. It will show the error. There are few other places where this error message is shown but I think that's maybe the most important one @mattab ? 

```diff
diff --git a/plugins/Actions/Reports/GetPageUrls.php b/plugins/Actions/Reports/GetPageUrls.php
index 794848a8a5..b93ba48022 100644
--- a/plugins/Actions/Reports/GetPageUrls.php
+++ b/plugins/Actions/Reports/GetPageUrls.php
@@ -75,7 +75,7 @@ class GetPageUrls extends Base
         if (version_compare(DbHelper::getInstallVersion(),'4.0.0-b1', '<')) {
             $view->config->columns_to_display[] = 'avg_time_generation';
         }
-
+throw new \Exception('foo');
         $this->addPageDisplayProperties($view);
         $this->addBaseDisplayProperties($view);
```

**Comment by geekdenz** [comment]
There are 2 FAQ links now. The one you suggested above, @mattab and an old one:

https://github.com/matomo-org/matomo/blob/850e1d7e82dac05256e67371bdbb8346dbed30f5/lang/en.json#L170
https://github.com/matomo-org/matomo/blob/850e1d7e82dac05256e67371bdbb8346dbed30f5/lang/en.json#L223

Is this what we want?

**Comment by tsteur** [comment]
@geekdenz I'm not quite sure to which file/place you refer this to?

If it's about the one you mentioned in chat then we wouldn't show it twice 
![image](https://user-images.githubusercontent.com/273120/130369935-b02180f2-4f54-4477-b6b2-044ccad1413a.png)
