### ISSUE TITLE
Websites Management > Time Zone - DST auto support? (daylight saving time)

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#15149]
This is an old issue with new(er) Matomo, there are missing cities / places, since you switched to new dropdown menu items sometime ago. I never had issues before that, and I think there is/was an old issue about this.

Another DST event happened 2 weeks ago, another 1 hour shift in my reports in Matomo is present (again). I adjusted time in system settings, but the issue remained, until I figured it has to be done under Websites for each.

Anyway, is there an option to add a checkbox to turn on/off Auto DST with **UTC+N/UTC-N** manual shifts selected? Also, some countries consider drop or already dropped DST, that's why it is better to be optional. Thanks!

**Comment by mattab** [comment]
@dev-101 not sure if we need to do anything to solve this issue, as I suppose the DST logic should be handled within the timezone you selected, or is it not? Note that you need to select the right city in the timezone selector, and not select UTC+-X since UTC doesn't have DST built-in.

**Comment by dev-101** [comment]
Back then my city was missing...

**Comment by dev-101** [comment]
Well, this issue is still present, unfortunately. Yes, back then list was incomplete, however, even now time with DST events are lacking an hour in Matomo's real time widget.

My server time is e.g. 21:05
My PHP time zone is properly configured in .ini (although this doesn't matter): 21:05
UTC time is e.g.: 19:05
Matomo time zone / country is properly set (e.g. France or whatever nearby country, doesn't matter if they are in the same zone): **20:05** !!!

Why is Matomo lacking an hour after recent DST event?
The only way to fix this is to manually set a fixed UTC+1, UTC+2 zone every 6 months or so (until they stop using DST grrrh), but why is time wrong is not clear to me, really.

**Comment by dev-101** [comment]
Ouch... I forgot that back then I set website's time manually, overriding global country setting when it became available.
Fixed.
