### ISSUE TITLE
Change the logo src to a relative path

### ISSUE THREAD

**Issue by jmumby** [matomo-org/matomo#15157]
Currently the "Powered by Matomo" logo is using an absolute path. This becomes an issue when used in an intranet and internet as the domain could be an ip address. 

Change:

`<img src="https://example.innocraft.cloud/plugins/Morpheus/images/logo.svg?matomo" tabindex="3" alt="Matomo" class="default-piwik-logo">`

to 

`<img src="/plugins/Morpheus/images/logo.svg?matomo" tabindex="3" alt="Matomo" class="default-piwik-logo">`

**Comment by sgiehl** [comment]
using an absolute path might make problems when Matomo is installed in a subdirectory

**Comment by mattab** [comment]
>  This becomes an issue when used in an intranet and internet as the domain could be an ip address.

Do you have more information on this possible problem @jmumby ? is it possible to reproduce this issue?

**Comment by jmumby** [comment]
At the point of raising the issue the image appeared to use an absolute path. In this case if the same Matomo is used outside of an intranet where it is accessed via ip the image is broken. 

For example, a user configures their Matomo on an intranet and is access via ip the image address could be:

`<img src="https://192.168.1.1/plugins/Morpheus/images/logo.svg?matomo" tabindex="3" alt="Matomo" class="default-piwik-logo">`

when being accessed externally the private address is not accessible.

**Comment by Findus23** [comment]
I think (but am not sure) that replacing this with a relative path would only mask the issue in one place instead of fixing it (by (somehow?) fixing Matomo to show the right URL. Because there are places where such URLs are generated where relative URLs aren't possible (e.g. images in E-Mails)

**Comment by Findus23** [comment]
I think the more general issue (Matomo generating URLs that are only valid in some contexts) should be solved instead: https://github.com/matomo-org/matomo/issues/14583
