### ISSUE TITLE
How does the piwik_log_visit table record the access end?

### ISSUE THREAD

**Issue by Orocker** [matomo-org/matomo#15159]
Piwik_log_visit This table has fields to record whether this visit is over? I need to query the visit that has ended. Or is there any other way? Thanks folks.

**Comment by tsteur** [comment]
Hi @Orocker please ask questions in our forum: https://forum.matomo.org/ and btw here's a reference to our DB schema: https://developer.matomo.org/guides/persistence-and-the-mysql-backend
