### ISSUE TITLE
pricing plan based ADs showing

### ISSUE THREAD

**Issue by harishksoft** [matomo-org/matomo#15155]
@tsteur using the code in a web app with a user login option. Logged users can create ADs and view ADs created by another user. Now want to add pricing plans for users, like user can add particular amount to account and this amount reduced based on the impression and interaction on the ADs he created. The amount per impression and interaction will decide by admin. Need to remove the AD, as soon as the balance in his account becomes zero. Is there any option available for this now?

**Comment by tsteur** [comment]
@harishksoft I don't think this is something do or will be planning to do. I might not understand your use case fully though and feel free to explain this in more depth in our forum https://forum.matomo.org/ and from there a clear feature request could maybe made once it's clear what be needed. I don't think you'd really want to use an analytics tool for this use case though. 

In general what may be interesting is tracking impressions and interactions using content tracking: https://matomo.org/docs/content-tracking/ You can then fetch using the API how often it was viewed / interacted with. You can also fetch this per visitor.
