### ISSUE TITLE
Update FAQ "How do I measure and get reports for my page sections / categories / mini-sites / languages?" to reflect how segment now work

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15165]
In https://matomo.org/faq/how-to/faq_35687/ we should remove `Solution 1) One website, one custom dimension, multiple segments` because it does not work anymore since: https://github.com/matomo-org/matomo/issues/11900

This was also brought up by a few users in https://forum.matomo.org/t/filter-page-urls-by-segments/34859/16

**Comment by tsteur** [comment]
Done

**Comment by mattab** [comment]
fyi put back the solution 1 as now the solution 2, and changed from segment to reports using filter, which actually works fine as an alternative solution :+1:
