### ISSUE TITLE
Reference exclusions

### ISSUE THREAD

**Issue by Lamy-ux** [matomo-org/matomo#15167]
In Google Analytics, you can define so-called reference exclusions in tracking, for example to track a payment page such as paypal.com not as a reference or home page. It isn't possible with Matomo. Since many of these had already been requested in the forum:

- https://forum.matomo.org/t/verweisausschlusseiten/34748
- https://forum.matomo.org/t/reference-exclusions/34864

It would be very nice if you could implement that.

**Comment by mattab** [comment]
@Lamy-ux  it is possible to exclude some websites from being marked as "Referrers" to your visit.
To do this, simply define these website URLs as "Alias URLs" on your website in Matomo.
You can do this by editing the websites in Administration > Websites > Edit, and entering your URL of your payment gateway under Alias URLs.

**Comment by FITZKRAWALLDO** [comment]
@mattab We searched for that "alias url" section. Is it still there? Was is like renamed? We cannot find it.

We want to exclude paypal because matomo list all client which comes back to our thank you page from paypal will be listed under "external pages" at ecommerce report

**Comment by Findus23** [comment]
Hi @FITZKRAWALLDO,

Matt is referring to the `URLs` section of the individual website settings in `Administration > Websites > Manage`:

![grafik](https://user-images.githubusercontent.com/6266037/96369492-93d6f880-115a-11eb-9e1e-97c9cdaa3fc3.png)

**Comment by FITZKRAWALLDO** [comment]
Hey,

okay so I will add "www.paypal.com" to the section "http://example.com"? I entered the website-name of the shop as well. Is that right?

So, that is like:
ww.my-shop-url.com
www.paypal.com

**Comment by webberian** [comment]
This issue can probably be closed, as discussion in #18612 has lead to fix #19302.
