### ISSUE TITLE
Separate the Marketplace plugin from the reports menu

### ISSUE THREAD

**Issue by Makkmetp** [matomo-org/matomo#15174]
The plugin for the market place creates a new line in reports menu with the text Marketplace. 
Users can think it are reports about their Marketplace.

It would be great if the link to the Marketplace is placed somewhere else. For example right to the segment or dashboard menu.

**Comment by tsteur** [comment]
As mentioned the workaround in https://github.com/matomo-org/matomo/issues/15175#issuecomment-557272047 either disabling the marketplace (which may not be best solution if you still want to receive update notifications) or using the [White Label](https://plugins.matomo.org/WhiteLabel) plugin can help to remove it from there.

**Comment by sgiehl** [comment]
With recent design changes, the Marketplace link in reporting menu should clearly by identifiable as a link to our Marketplace:
![Marketplace Link](https://github.com/matomo-org/matomo/assets/1579355/6ac77a07-7217-43cd-bf8a-0c706dde0b5c)

So guess we can close this issue as resolved.
