### ISSUE TITLE
Icon-Fonts not loading when behind proxy

### ISSUE THREAD

**Issue by EDV-Eberhardt** [matomo-org/matomo#15188]
Hey folks, today we installed Matomo over docker compose behind our nginx proxy. Everything seems to work except the icon fonts. We are getting a 404 for the matomo.woff/.ttf files.

We checked the folder an the files are there:

`/var/www/html/plugins/Morpheus/fonts # ls
README.md       matomo.ttf      matomo.woff2    piwik.ttf       piwik.woff2
matomo.svg      matomo.woff     piwik.svg       piwik.woff      selection.json`

Also other Images from the Morpheus-Folder are working correctly. 

We are using this snippet in the nginx-config...can't see any problem here...

`location ~ \.(gif|ico|jpg|png|svg|js|css|htm|html|mp3|mp4|wav|ogg|avi|ttf|eot|woff|woff2|json)$ {
		allow all;
		## Cache images,CSS,JS and webfonts for an hour
		## Increasing the duration may improve the load-time, but may cause old files to show after an Matomo upgrade
		expires 1h;
		add_header Pragma public;
		add_header Cache-Control "public";
	}
`

Any ideas guys? Thanks!

**Comment by tsteur** [comment]
Hi there,

I recommend you ask this question in the forum https://forum.matomo.org/ as we don't troubleshoot specific server setups in our issue tracker but only handle bug reports and feature requests here. Maybe someone with Nginx knowledge can help you there. Maybe check out also https://github.com/matomo-org/matomo-nginx

Cheers
