### ISSUE TITLE
Archive Error - Empty or invalid repsonse 'Notice: Undefined Index : class

### ISSUE THREAD

**Issue by leftmostlane** [matomo-org/matomo#15181]
With Matomo 3.12.0 when we run an Archive `console core:archive` we receive the following error for almost every site:

ERROR [2019-11-21 ##:##:##] 26378 Empty or invalid response ' Notice: Undefined index : class in ..../piwik/plugins/Monolog/Formatter/LineMessageFormatter.php on line 83 Notice: Undefined index: type in ..../piwik/plugins/Monolog/Formatter/LineMessageFormatter.php on line 83 Notice: Undefined index: type in ..../piwik/plugins/Monolog/Formatter/LineMessageFormatter.php on line 83 .......for website id ##, Time elapsed: 0.###s, skipping

**Comment by tsteur** [comment]
@leftmostlane please check if you updated your `config/global.php` file and `config/global.ini.php`. Not sure how you update your Matomo but looks like these files weren't updated. You may need to do the manual update process to fix this issue: https://matomo.org/docs/update/#the-manual-three-step-update

Let me know if this doesn't help and we're happy to reopen.
