### ISSUE TITLE
France regions are not up-to-date

### ISSUE THREAD

**Issue by GuiGuiSoft** [matomo-org/matomo#15203]
Hello,

France region in Matomo are
![image](https://user-images.githubusercontent.com/8069239/69804363-b1b40b80-11de-11ea-9a9b-1ce81b83c3a5.png)

Whereas several regions have been merged since the 01/01/2016 (official source : http://www.prefectures-regions.gouv.fr )
![image](https://user-images.githubusercontent.com/8069239/69804444-dc9e5f80-11de-11ea-95b3-574363c48c6f.png)

Regards.

**Comment by sgiehl** [comment]
Thanks. We are aware of this issue. Our maps are still based on the FIPS codes, that were used by Maxminds GeoIP (Legacy). We will work on new maps in #11929

**Comment by Chardonneaur** [comment]
Hi all,
Just would like to say that on some of my French clients reports, it is true that the region map nothing is showing up.
