### ISSUE TITLE
spike after updating matomo to 3.13

### ISSUE THREAD

**Issue by Risingson** [matomo-org/matomo#15205]
![image](https://user-images.githubusercontent.com/5108701/69827062-1f2f5e80-1216-11ea-9fd7-29034869962a.png)
seems like actions of a single user are counted as unique visits

**Comment by tsteur** [comment]
I would suspect this is due to https://github.com/matomo-org/matomo/pull/14360 maybe? Are you using the userId feature?

**Comment by Risingson** [comment]
You are right i am using the userID and i am sure this is related. But still: Triggering an action should not count a unique visit, should it?

**Comment by tsteur** [comment]
Not sure what you mean? Triggering an action should indeed not create a new unique visit and it doesn't unless your visitors were to regenerate the visitorId on every request somehow. Not sure how you embed the tracking code into your mobile app? It seems your using maybe a different visitorId each time

**Comment by Risingson** [comment]
I do not intentionally create a new visitorId. I am not deep enough into this. I can provide code if you want me to.

**Comment by Risingson** [comment]
These are 2 action calls a few seconds apart counting as 2 visits obviousely.
![image](https://user-images.githubusercontent.com/5108701/69833614-519c8400-1235-11ea-9513-a75b8907b04b.png)

Normally -if the system recognises the same visitorID (xor after this merge userID?)- it would look like this and count one unique visit:
![image](https://user-images.githubusercontent.com/5108701/69833649-8dcfe480-1235-11ea-9af7-d0c8de9bbcd3.png)

**Comment by Risingson** [comment]
Any news on this ?

**Comment by tsteur** [comment]
It really depends how you track your mobile app. Are you using one of our android or iOS SDKs? Then I would create an issue and ask there. If you implemented it yourself, then maybe have a look at the Tracking API docs: https://developer.matomo.org/api-reference/tracking-api . Maybe you need to set the `_id ` parameter

**Comment by Risingson** [comment]
So this is intentional behaviour of a minor release that rips functionality provided up until 3.13. 
Nice one.

**Comment by mattab** [comment]
@Risingson Are you using the official Matomo SDK? If so, it would be a bug in the SDK and it would be great if you can open a bug report there, or we can move this report to the Android SDK project?

**Comment by Risingson** [comment]
I am not using the Android SDK. 
It is a mobile app using webviews (html+js>phonegap). I can send the tracking code if you wish. 
As stated the only difference within the tracking code between the browser app and the mobile app is that mobile sets a device ID as user ID. `_paq.push(['setUserId', device.uuid]);`. Such an UserId is visible in the example screenshot above: 
![image](https://user-images.githubusercontent.com/5108701/70526563-29bcf280-1b4a-11ea-9552-bbc02b9c5bcd.png)
Still it looks like as if the actions are causing a unique visit count.

**Comment by tsteur** [comment]
Maybe there are issues with cookies and it always regenerates a random visitorId. If it uses the regular JS tracking code in the webview, it should still identify each visitor based on IP and other critieria (although in a mobile app a lot of the criteria be the same). Can you check if you maybe have `trust_visitors_cookies` enabled in your config file? You may have enabled it since otherwise some visitors are grouped together even though they are different visitors in webview mobile apps.

What you likely want to do is call `_paq.push(['setVisitorId', device.uuid])`. The unique visitor ID, must be a 16 characters hexadecimal string.

**Comment by tsteur** [comment]
Also created a PR that might help: https://github.com/matomo-org/matomo/pull/15258

**Comment by Risingson** [comment]
Glad to hear you are trying to find a way to fix this serverside. I cannot force people to update the apps on their phones...
