### ISSUE TITLE
Email reports set to daily do not go out daily

### ISSUE THREAD

**Issue by jimkang** [matomo-org/matomo#15201]
Hello. I have a few email reports that I set to "Daily" in the ScheduledReports module. Without fail, they get sent *every other day*. Is there a workaround for this?

**Comment by Findus23** [comment]
Do you have set up a cronjob for Matomo?

**Comment by jimkang** [comment]
I had not, other than the log ingestion ones! [Just saw this](https://matomo.org/docs/setup-auto-archiving/) and added a cron job for archiving. I'll see if it works.

I'm curious, though, how is it able to send email every other day anyway without that cron job?

**Comment by tsteur** [comment]
@jimkang I'll close the issue for now. Let us know if it doesn't work for you with the cronjob and we're happy to reopen the issue. Cheers

**Comment by jimkang** [comment]
Still does not seem to work. No emails today, for example.

**Comment by jimkang** [comment]
Hey, so it did work two days in a row after I updated the settings again (made a minor change to the content included in the report) and hit save. Thanks!

**Comment by tsteur** [comment]
Great to hear @jimkang . Thanks for letting us know.
