### ISSUE TITLE
Incorrect/corrupted number format in dashboards

### ISSUE THREAD

**Issue by c-schmitz** [matomo-org/matomo#15200]
This affects Matomo  3.13.0

Integer numbers like the total number of visitors are correctly shown in graphs, but are crippled by one place and shown with a thousand-separator(?) in the wrong place.
So 2014 visitors are shown as 2,01 vistors in the sparkline.

Please see the following screenshot:

![Anmerkung 2019-11-27 120140](https://user-images.githubusercontent.com/1364282/69718129-d7bdab00-110d-11ea-8c98-ddb9f2f7b278.png)

**Comment by tsteur** [comment]
Looks like the graph is not using the local number formatter 👍

**Comment by ingconti** [comment]
so will be fixed?

**Comment by sgiehl** [comment]
It's already fixed and will be included in the next release.

**Comment by beamylake** [comment]
Thanks for fixing this, is the fix applying to the visitor section only but also to other sections like Ecommerce?

We are experiencing the same problems in the visitor overview as described in this issue when using German as language setting in Matomo (I'm coming from https://github.com/matomo-org/matomo/issues/15262), when using English everything looks to be ok.

But we also experiencing some kind of rounding error in the Ecommerce overview section. The numbers are formatted correctly there, but when using German the conversion rate is shown as 0% and when using English it's shown as 0,5% (which would be the correct number).

**Comment by mattab** [comment]
@beamylake Could you please try upgrade to the latest beta? https://matomo.org/faq/how-to-update/faq_159/
and confirm if you still experience any issue?

**Comment by beamylake** [comment]
We're on it, I'll get back to you as we got the results.

Thanks for working on these issues over the holidays!

**Comment by beamylake** [comment]
It works!

With the latest beta (as by Friday, Jan 3rd) the visitor numbers are now in correct format when using German as display language.

Thanks!

**Comment by tassoman** [comment]
Thank you team! For people who can’t go on production with a beta version I suggest writing a theme plugin reverting the modification temporarily https://github.com/matomo-org/matomo/issues/15356#issuecomment-571969811
