### ISSUE TITLE
Website is set to Undefined by default in website chooser

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#15215]
Issue: Website is set to Undefined by default in website selector, when creating/viewing Custom Dimension

steps to reproduce:

1. Click on "Administration (cog icon)" on the top right
2. Click on "Measurables > Custom Dimensions"
3. View website chooser dropdown on the top left

![image](https://user-images.githubusercontent.com/26726594/69921307-66a73a80-14f5-11ea-89c3-3ec9996320bb.png)

Even if you choose a website from dropdown, it changes back to Undefined

**Comment by mattab** [comment]
Thanks for the report, but i can't reproduce, it works for me locally and also on demo.matomo.org @KarthikRaja1388

**Comment by KarthikRaja1388** [comment]
@mattab This can be reproduced in Cloud instance.

**Comment by mattab** [comment]
What are the steps to reproduce @KarthikRaja1388 ?

**Comment by KarthikRaja1388** [comment]
@mattab 

steps to reproduce:
    1. Click on "Administration (cog icon)" on the top right
    2. Click on "Measurables > Custom Dimensions"
    3. View website selector dropdown on the top left (can see undefined)
    4. Choose a website from dropdown and it will change back to undefined

**Comment by mattab** [comment]
it works for me, can you try in a different instance if you can reproduce with these steps?

**Comment by KarthikRaja1388** [comment]
@mattab I tried in multiple instances
