### ISSUE TITLE
forgetConsentGiven method lasts 7 days instead of 30 years

### ISSUE THREAD

**Issue by wlabarron** [matomo-org/matomo#15214]
Related to #14487.

https://github.com/matomo-org/matomo/blob/54dadb98beae46f88203df273d1bada6a2596b5b/js/piwik.js#L7597-L7600
This code suggests that the consent forgotten cookie should last for 30 years, but when I call the function from the console in Safari on macOS and look at the cookie in the inspector, it's only set to last 7 days.

Running Matomo v3.13.0.

**Comment by Findus23** [comment]
@wlabarron This is a Safari feature:
https://webkit.org/blog/8613/intelligent-tracking-prevention-2-1/

**Comment by wlabarron** [comment]
Ah, that makes sense. I did think it seemed very strange. Is there a workaround or will users just need to re-revoke consent every 7 days?

**Comment by wlabarron** [comment]
Ah okay, that makes sense - I did think it was very odd. Thank you.

**Comment by mattab** [comment]
Confirmed, we just re-discovered this issue, posted a comment for reference in https://github.com/matomo-org/matomo/issues/14819#issuecomment-603573497

**Comment by mattab** [comment]
fyi created PR to document this limitation https://github.com/matomo-org/developer-documentation/pull/336
