### ISSUE TITLE
Campaigns: Visitor count incorrect

### ISSUE THREAD

**Issue by chris246** [matomo-org/matomo#15226]
The visitor count for a campaign in the dashboard is not displayed correctly (or maybe not updated).

![grafik](https://user-images.githubusercontent.com/14861996/69997150-caf8e700-1553-11ea-9d4c-a782f7dad99a.png)

The data from the left graph makes much more sense when looking at the visitor log.

Matomo version is 3.13.0

**Comment by tsteur** [comment]
@chris246 can you let us know a bit more details maybe?

**Comment by chris246** [comment]
Of course. What exactly do you mean?

I noticed that the visitor count for our recent newsletter did not increase and the difference between this number and the graph. According to the graph, the number should be 26 (11+15) but is not growing since yesterday.  
The archiving task is executed every hour and even running it manually does not change the counter.

I just noticed that the same seems to happen for e.g. the row evolution of pages vs. its counter for "page views".

**Comment by tsteur** [comment]
Are there any segments involved or so?

**Comment by chris246** [comment]
The website has segments, but I did not select one (all visits).

I see the same behaviour on a different website (same Matomo instance) without segments.

**Comment by chris246** [comment]
The counter in the table from the screenshot above now has jumped from 1 to 15, but according to the graph should be at 30.

**Comment by tsteur** [comment]
Could you let us know the exact steps you take to reproduce this? Can you also reproduce this on https://demo.matomo.org ?

**Comment by chris246** [comment]
Exact steps:
That's a bit difficult, as I noticed it since the latest updated.
The report range set is "last 30 days including today" - range from today to (today - 30)

In my opinion, the visitor counter on the dashboard should display the sum of the graph values, but doesn't for some data sets.


On demo.matomo.org, I could not reproduce the problem.

**Comment by tsteur** [comment]
Just to understand. You are viewing a date range (last 30) and in the report table it shows `1` for that campaign. Then you click on row evolution and it shows a higher number for the individual days?

**Comment by chris246** [comment]
Yes, exactly. Although the values have changed in the meatime.
Here is an updated screenshot with annotated valued for the graph.

![grafik](https://user-images.githubusercontent.com/14861996/70270689-3e456780-17a5-11ea-9250-971c1ba26510.png)
It's the row evolution for this campaign.

Again, no segment is active, the chosen date range is the one of the x-axis.

**Comment by tsteur** [comment]
fyi this sounds like a similar issue to https://github.com/matomo-org/matomo/issues/15170

**Comment by chris246** [comment]
Thanks, I agree.
Do you need access to this installation?

**Comment by tsteur** [comment]
@chris246 thanks for asking. I reckon we're fine for now but I might get back to your offer later. Thanks.

**Comment by mattab** [comment]
@chris246 do you still experience this issue with Matomo 3.13.1 (our latest version)?

**Comment by chris246** [comment]
The values of the latest sent newsletter campaign match.
I'd suggest to reopen this issue if the problem occurs again.

Thanks for your help and the fix

**Comment by janmuennich** [comment]
I am having exactly the same problem with Matomo 3.13.2 now. The campaign visits in the widget table are incorrect. Interestingly this varies for different time periods. While e.g. September seems to be correct (68 visitors in this example), the whole period July to December shows only 13 visitors. As in the original issue, the numbers shown in the graph are higher and seem to be more likely correct.

<img width="658" alt="Screenshot 2020-02-17 at 15 13 13" src="https://user-images.githubusercontent.com/5816345/74665965-8c5ceb00-5198-11ea-9a58-d9038bd79b61.png">

**Comment by solevis** [comment]
We have exactly the same problem as @janmuennich with the latest 4.10.1 release. Do I need to open a new issue?
The same thing occurs on the demo site : https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=year&date=2022-06-01&idSite=1&category=Referrers_Referrers&subcategory=Referrers_Campaigns

app_help: show 317 in the table, but the charts show several peak of values of ~700

**Comment by justinvelluppillai** [comment]
Hi @solevis - This might be a different issue so would be good to open a new issue for it. It looks like the table is just showing the last day of the chart period, not the sum of the period there. It would be good to look into this and either fix or explain the behaviour.
