### ISSUE TITLE
When DB user doesn't have the 'CREATE TEMPORARY TABLE' grant, display a clear error message

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15237]
Currently when the MySQL DB user does not have the "create temporary table" grant/permission set (a new requirement we introduced in Matomo 3.12.0 or so), the archiving of reports fails with a cryptic error message, as reported by several users [in the forum](https://forum.matomo.org/t/database-access-denied-or-synax-error-after-newest-update/35134/17).

The message says `SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'abc'@'localhost' to database 'matomo' - in plugin Goals`  so it's not clear what the problem is. 

Ideally when the user does not have the right permission:
* The error message would be clear and explain the user doesn't have the `GRANT CREATE TEMPORARY TABLES` and maybe list the command to execute directly, or link to a new FAQ or [our FAQ explaining](https://matomo.org/faq/how-to-install/faq_23484/) the command to run
* maybe we could also have a system check diagnostic error, when the user doesn't have this permission, that also outputs the same suggestion of which command to type

**Comment by sgiehl** [comment]
was fixed with #15139
