### ISSUE TITLE
Where can I check the full details of the logs about "VISITS"

### ISSUE THREAD

**Issue by tsuibin** [matomo-org/matomo#15239]
Question 1: the number of visits in all website reports cannot be rendered anywhere in the page. The exported log interaction field is corresponding to it. However, it is not clear what the system defines for this field. The actions field corresponds to the number of views we understand, that is, there is a count for each click on the page. Here is the total
![3](https://user-images.githubusercontent.com/1154966/70209146-6c598600-176a-11ea-8d2f-641053843a82.png)

**Comment by tsteur** [comment]
@tsuibin could you please ask questions in our forums: https://forum.matomo.org/

I recommend to be a bit more specific as it's not quite clear what you are asking. Eg what `exported log interaction field` are you referring to? And what do you mean it cannot be rendered anywhere in the page? Be good to ask in the forum, cheers
