### ISSUE TITLE
going to 'All Websites' dashboard and selecting a date range and clicking a site results in error message

### ISSUE THREAD

**Issue by tsuibin** [matomo-org/matomo#15238]
Preface
The system version is 3.13.0, and the update time is 2019.11.26-27. The system has been updated and the server has been migrated

After selecting a date range from all websites dashboard, clicking on a site in the list of sites will report a time period or an incoming time parameter error"error: date format must be: yyyy-mm-dd, or 'today' or 'yesterday' or any keyword supported by the strtotime function (see http://php.net/strtotime for more information):" , Data can only be displayed if the date range is re-selected;

![图片1](https://user-images.githubusercontent.com/1154966/70207055-81331b00-1764-11ea-949e-337a19479103.png)
![图片2](https://user-images.githubusercontent.com/1154966/70207080-8db77380-1764-11ea-9823-9ecdb80f0873.png)

**Comment by tsteur** [comment]
@tsuibin I can't reproduce this issue. Can you reproduce this issue on https://demo.matomo.org/ ?

Any chance, that the selected date range includes a date before you created the website in Matomo?

Say you created the website in Matomo on 25 Oct 2019, and you select a date range starting from 10 January 2019. Unfortunately, I think it is only possible to see when a site was created in the database in the `site` table. We could maybe test this another way... can you reproduce the same issue if you select a date range only for the last 2 or 3 days for example (assuming your site was created more than 2 or 3 days ago). So basically try to select a date range eg `5 Dec 2019 - 6 Dec 2019`

**Comment by nztim** [comment]
I have this problem too and it occurs when the date range is valid. The query string created is as follows:

`module=CoreHome&action=index&date=2019-11-13%2C2019-12-20&period=range&idSite=6#?idSite=6&period=range&date=2019-11-13%252C2019-12-20&segment=&category=Dashboard_Dashboard&subcategory=1`

When I replace the `%2C` and `%252C` with commas it appears to work correctly, so I guess there is some double and triple URL-encoding somewhere.

**Comment by tsteur** [comment]
@nztim are you using the latest version of Matomo? Can you reproduce this on https://demo.matomo.org/ ?

**Comment by nztim** [comment]
Matomo v3.13.0 and I found out how to reproduce it on the demo site. 

If you go to the 'All Websites' page and select a date range you'll see the problematic query string is produced. When you then select a website the query fails and the error is shown.

**Comment by tsteur** [comment]
Thanks for that!
