### ISSUE TITLE
multi sites but one  tracking code

### ISSUE THREAD

**Issue by zw231212** [matomo-org/matomo#15230]
if someone put same matomo tracking code (one id) to multi sites, can I  get the information of  site he put?
eg: John put the same tracking code to site A ,site B and Site C . As a manager, I don't know he put the same code to three site,  but when users view site A,B,C，Then matomo have record the view history. Is there a API or page that I could see the view by group?

site_host | nb_visitors | nb_views
-|-|-
A | 10 |20
B | 3| 100
C | 2 | 2

**Comment by tsteur** [comment]
Hi there, not exactly sure what you are after. The  https://matomo.org/docs/manage-websites/#all-websites-dashboard shows you that information that you are after maybe. This is basically the output of the `MultiSites.getAll` API.

If you wanted to have aggregated information across these sites you could use [Roll Up Reporting](https://plugins.matomo.org/RollUpReporting)

Fur further questions be good to ask in the forum: https://forum.matomo.org/
I hope this helps.

**Comment by zw231212** [comment]
> Hi there, not exactly sure what you are after. The https://matomo.org/docs/manage-websites/#all-websites-dashboard shows you that information that you are after maybe. This is basically the output of the `MultiSites.getAll` API.
> 
> If you wanted to have aggregated information across these sites you could use [Roll Up Reporting](https://plugins.matomo.org/RollUpReporting)
> 
> Fur further questions be good to ask in the forum: https://forum.matomo.org/
> I hope this helps.

the simple thing is : one tracking id, but I put the same tracking code to three sites, not what you said every site get its own tracking id.

today I find a simple solution
![image](https://user-images.githubusercontent.com/12821929/70134131-67d99280-16c2-11ea-82ad-37fe73ce3112.png)

and then go to action page , find every page's visits and hits.
