### ISSUE TITLE
importing apache2-logs with /piwik/misc/log-analytics/import_logs.py

### ISSUE THREAD

**Issue by Kornexl** [matomo-org/matomo#15242]
I’m importing Apache logs since some years and it always worked OK.
Since Update to Matome 3.13.0 on 28.11. the number of unique visitors is way to high

The number of loglines the days before are about at the same magnitude, but the number of visitors was suddenly a huge factor higher (500 vs 20.000)
Number of lines in these Logs   
    44486 ezproxy.log-20191126 (468 visitors)
    50920 ezproxy.log-20191127 (498 visitors)
    44860 ezproxy.log-20191128 (27.11.2019 and 491 visitors)
    41085 ezproxy.log-20191129 (28.11.2019 and 18000 visitors)
    42425 ezproxy.log-20191130
    30908 ezproxy.log-20191201 
    29724 ezproxy.log-20191202
    42316 ezproxy.log-20191203 (28.179 visitors)

**Comment by Kornexl** [comment]
![docweb-besucher](https://user-images.githubusercontent.com/5048009/70311579-2eb03800-1812-11ea-981e-74f66c1979f0.png)

**Comment by tsteur** [comment]
How exactly do you execute the log import command with which parameters? Do the requests have a userId?

**Comment by mattab** [comment]
@Kornexl Could you please try this patch and let us know if this maybe helps with counting visits correctly (for new visits after applying the patch)?

**Comment by psec** [comment]
@mattab experiencing a similar bug and the patch posted above did not fix it.

**Comment by Kornexl** [comment]
The logs do have userids and these are transmitted in the uid-Parameter by piwik/misc/log-analytics/import_logs.py
Prior to 3.13  different userids are counted as the visits
Now the visits don't use the userids but count otherwise. The different userids are shown as users in the widgets
That's a breaking change in the sematics of visits

**Comment by Kornexl** [comment]
by importing logs there is no cookie set

**Comment by mattab** [comment]
@Kornexl  can you please share a short extract from the log with multiple lines for the same user ID resulting in multiple visits? if you can't share here publicly, feel free to send us by email at hello at matomo.org - please also include the URL to this issue https://github.com/matomo-org/matomo/issues/15242 - we'll investigate further

**Comment by Kornexl** [comment]
should this problem be solved with the new release 3.13.1?
I have installed this release today and can check tomorrow after the import of the daily log

**Comment by Kornexl** [comment]
This problem is resolved  with 3.13.1

**Comment by mattab** [comment]
Thanks for confirming @Kornexl :+1:
