### ISSUE TITLE
PHP 7.4 & 3.13 Visitors/actions bug

### ISSUE THREAD

**Issue by BraveSauce** [matomo-org/matomo#15257]
After upgrading to php 7.4 from 7.3, each action recorded from the same visitor gets recorded as a separate visit with the same ID and other details, while the unique user count keeps rising up as the same one user navigates through more pages.

This is happening on a setup that is using image tracking method.

Matomo version latest beta 3.13.0

**Comment by tsteur** [comment]
@BraveSauce any chance you are setting a userId in the image tracking method? As we changed there something in a recent release around that. It might not be PHP 7.4 related

**Comment by BraveSauce** [comment]
@tsteur As a matter of fact, I do use uid in the tracking method. I tried to play with _id values paired with my uid to fix this issue but it breaks my c_n values if I use it.

**Comment by tsteur** [comment]
Do you know if you have maybe `trust_visitors_cookies` enabled in your `config/config.ini.php` file?

You mention the solution already basically ideally you would set `_id` to some 16 characters hexadecimal string. You could for example hash the userId to generate a visitorId for each user. I can't really think of any reasons this could break your `c_n` values unless you values are not properly URL escaped.

**Comment by BraveSauce** [comment]
For closure, just wanted to report that this issue was fixed in later beta updates without any code changes on my end.

**Comment by tsteur** [comment]
Awesome thanks for letting us know @BraveSauce
