### ISSUE TITLE
3.13 Percentages calculated incorrectly for Multi-channel conversion

### ISSUE THREAD

**Issue by dm577** [matomo-org/matomo#15254]
In 3.13, the percentages are calculated incorrectly for the multi-channel conversions.  The site is set for US English and it's using commas instead of decimals and is set to too may places for the calculation.

![Image5](https://user-images.githubusercontent.com/58389783/70449476-0faee180-1a70-11ea-85bc-3b166d607f3f.png)

**Comment by tsteur** [comment]
@dm577 could you email our support about this? shop at innocraft.com . That be great! Cheers
