### ISSUE TITLE
CronArchive.archiveSingleSite.start gets concurrently called for same site

### ISSUE THREAD

**Issue by pardvm** [matomo-org/matomo#15267]
In order to improve archiving performance, we have 10 cron archive tasks in our on premise Matomo installation.

It has been that way for long time with no problem at all: the cron tasks distributed the sites and all of them were archived only once.

However, we had to hook the ``CronArchive.archiveSingleSite.start`` event and, since that moment, we observe that the code in ``CronArchive.archiveSingleSite.start`` is being executed concurrently by several crons tasks.

Is there any way to avoid that concurrency?
Is there any other place, event or technique to, for each site, execute a piece of code before proceding with the archive but making sure its execution mutually excluded for the site?

**Comment by tsteur** [comment]
Have a sleep between the launch of each cron archiver... like `sleep 3`... if you have them in crontab you can do 

`sleep 3 && ...`
`sleep 6 && ...`
