### ISSUE TITLE
Multiple tracking of the same unique order id

### ISSUE THREAD

**Issue by dehenne** [matomo-org/matomo#15266]
We found out that Matomo has a little bug in the e-commerce tracking.

If the same tracking is executed several times, even if the same order ID is used, piwik tracks this twice.

![image](https://user-images.githubusercontent.com/751811/70802303-63436700-1db1-11ea-8352-742705eafa04.png)

![image](https://user-images.githubusercontent.com/751811/70802332-7e15db80-1db1-11ea-8ea0-98e3fc9fa3ce.png)

The ecommerce stats are thereby falsified. This can also happen when the user reloads the window.

best greetings
Hen

**Comment by tsteur** [comment]
@dehenne that would be expected behaviour if you have enabledanonymize order IDs which you maybe did by the looks (you can check in Admin => Privacy settings). In that case you would need to make sure to not send the same request twice.

**Comment by dehenne** [comment]
so thats mean: if I have a final page for an order, the user reloads, I have to check if he has visited this page before 🤔 

that's a bit unhandy. because in principle you only have to make `if id exists -> track` ... and logicaly, you can't order the same order twice 😄 

anyway, thanks for the answer. maybe you'll just think about adding an if otherwise you can close the issue.

**Comment by tsteur** [comment]
Can you confirm you have the orderId anonymize feature enabled? In this case we simply can't check if it already exists. You could save some metadata along your order that it has been already tracked and not send the request again.

**Comment by dehenne** [comment]
yes, the order ids are anonymize.

I have to talk to the marketing team. otherwise I have to think of a solution. 
thanks for your time. I think you can close this issue.
