### ISSUE TITLE
after last update decimal / thousand separator for ITALIAN are missing 

### ISSUE THREAD

**Issue by ingconti** [matomo-org/matomo#15261]
after last update decimal / thousand separator for ITALIAN are missing.
I can see correct decimals if I switch to FR.

not ein ITALIAN we should have:
228'413 (Matomo has lost last digit!)
![image001](https://user-images.githubusercontent.com/4048423/70602896-b53f8d80-1bf5-11ea-8426-526400e0fb38.png)
![image002](https://user-images.githubusercontent.com/4048423/70602897-b5d82400-1bf5-11ea-9af2-a863c2be5131.png)

**Comment by sgiehl** [comment]
I guess that one is a duplicate of #15200

**Comment by tsteur** [comment]
@ingconti marking it for now as a duplicate. Let us know if the next update does not fix it
