### ISSUE TITLE
Google indexing matomo

### ISSUE THREAD

**Issue by MESWEB** [matomo-org/matomo#15273]
Google all the time indexing matomo. I have website and matomo is installed into subdomain of main domain. What values should be in robot.txt?

**Comment by tsteur** [comment]
Hi there, I recommend you search for `robots.txt` and `disallow search engine crawling` or similar in your favourite search engine. If you are using a somewhat recent version of Matomo, we also disallow Matomo being indexes through Meta tags

**Comment by MESWEB** [comment]
Yes I know that but how should this file looks like?
Matomo domain is subdomain.example.com 
So in robot txt I should att this?:

> User-agent: * 
Disallow:  subdomain.example.com

And where this file should be placed? In main domain or matomo subdomain?

**Comment by Findus23** [comment]
@MESWEB I'd recommend you to make sure you are using the latest Matomo version as it contains a line like this
```html
<meta name="robots" content="noindex,nofollow">
```

that tells search engines to not index this page.

**Comment by MESWEB** [comment]
@Findus23  Yes I do. I have Matomo 3.13.0 

> <meta name="robots" content="noindex,nofollow">

This line is visible on login page but google all the time index this subdomain. 
I was reading somewhere about google indexing and someone says:
Google is indexing even if content nofollow and noindex is addet to html code because some website can link to this url.
