### ISSUE TITLE
Compare Tool: support for single day reports

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#15281]
If we use single **day** for range report (e.g. page views), Compare tool will return the error because it expects to have range for comparison. Please add support to compare to another single date in this case (e.g. day before, day from last week, month, same day last year etc.)

```index.php?module=CoreHome&action=index&idSite=1&period=day&date=today```

```API returned an error: The date ',' is not a correct date range. It should have the following format: 'lastN', 'previousN', 'YYYY-MM-DD,YYYY-MM-DD'. at Range.php:268```

**Comment by tsteur** [comment]
@dev-101 do you know which report is showing you that error? Or whether it is shown on the dashboard? Is it for a specific widget in the dashboard? AFAIK this should be supported.

**Comment by dev-101** [comment]
Example URL:

```/index.php?module=CoreHome&action=index&idSite=1&period=day&date=today#?idSite=1&period=day&date=today&category=General_Actions&subcategory=General_Pages```

**Comment by mattab** [comment]
This can be reproduced at: https://demo.matomo.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=62#?idSite=62&period=day&date=2020-01-21&segment=&category=Dashboard_Dashboard&subcategory=1&comparePeriods%5B%5D=range&compareDates%5B%5D=,

![Screenshot from 2020-01-21 17-20-15](https://user-images.githubusercontent.com/466765/72775193-4f253c00-3c72-11ea-875a-d9db23ba72f0.png)

**Comment by tsteur** [comment]
Will close this issue @dev-101 as it looks fixed in Matomo 4.3. If it's still an issue please comment with the steps to reproduce and we'll reopen.
