### ISSUE TITLE
Showing "Oops, there was a problem with the request" in the top of the dashboard after waking up computer

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15287]
Reported in: https://forum.matomo.org/t/make-oops-there-was-a-problem-during-the-request-dismissible/35390 - I've also experienced this a few times.

> In version 3.13.0 the error message “Oops… there was a problem during the request. …” always appears on top of the Dashboard after I woke up my laptop. I assume the reason is that the Wifi connection needs more time to reestablish.

> It would be great if I could close that message, since everything (including Ajax like Visits in Real-Time) actually works without problem. Alternatively, the message could simply disappear after a few seconds.

## Reproduce on all websites dashboard

* Open https://demo.matomo.org/index.php?module=MultiSites&action=index&idSite=3&period=day&date=yesterday
* While all websites is dashboard is loading, click on the "Dashboard" link
* Got this:
![Screenshot from 2020-01-21 16-55-20](https://user-images.githubusercontent.com/466765/72774275-d670b080-3c6e-11ea-8867-d1450b664835.png)

## Reproduce in Dashboard

I'm not actually sure how to reproduce it consistently but I often get this:

![Screenshot from 2020-01-21 16-56-59](https://user-images.githubusercontent.com/466765/72774370-42531900-3c6f-11ea-99ef-3d64efd5a63c.png)

## ideas

* When the Real-time ajax requests fail, maybe we could diplay the error message after 3-4 or 5 consecutive fails, rather than immediately?
* or hide the error notification that may have been displayed for the real-time widgets, whenever a successful real-time widget ajax request comes next
* or maybe there's a better solution?

**Comment by gramakri** [comment]
I guess this is related to https://github.com/matomo-org/matomo/issues/15287 . Happens in Firefox but not in chrome.

**Comment by Findus23** [comment]
@gramakri I think you meant https://github.com/matomo-org/matomo/issues/10578 (to cross-link it)

**Comment by mattab** [comment]
Maybe this will be fixed in Matomo 4.3.0 thanks to https://github.com/matomo-org/matomo/issues/10578

**Comment by mattab** [comment]
I haven't seen this issue recently so it was fixed AFAIK
