### ISSUE TITLE
Need Contents.getContentName in Reporting HTTP API

### ISSUE THREAD

**Issue by feikede** [matomo-org/matomo#15295]
I'd like to report how often a "contentName" has been visited over time. But there's no such function in the reporting API. The Contents.getContentName() should be very much like 

`Actions.getPageUrl (pageUrl, idSite, period, date, segment = '')`

but with a contentName as parameter, i.e.

`Contents.getContentName (contentName, idSite, period, date, segment = '')`

Same would be fine for contentPiece.

**Comment by tsteur** [comment]
@feikede I reckon you want to use the existing getContentNames API with a `label=$contentName` parameter? Alternatively, `filter_pattern` should work as well see https://developer.matomo.org/api-reference/reporting-api

**Comment by tsteur** [comment]
AFAIK that's how Matomo does it as well in over time reports

**Comment by sgiehl** [comment]
As there hadn't been any further activity, we assume that the problem has been solved/answered.
