### ISSUE TITLE
different count of visitors

### ISSUE THREAD

**Issue by IljaKraval** [matomo-org/matomo#15290]
Hi all,

I have another count of visitors in Overview and in Visitor Log.

see 2 attached pictures (screenshots made at the same time at Thursday 11:00)

Ilja Kraval 

---------

![visitors](https://user-images.githubusercontent.com/46327785/71164367-2c58cf80-224f-11ea-8b68-1da6fb65a39e.png)

-------

![visitorlog](https://user-images.githubusercontent.com/46327785/71164375-32e74700-224f-11ea-95ac-c03358af7fa5.png)

**Comment by tsteur** [comment]
@IljaKraval can you check if the data is maybe there by now? The visitor log is querying raw data while the other report is showing aggregated data and these aggregated reports are only updated every hour or few hours depending on your settings.
