### ISSUE TITLE
New visit created for each action with userid populated since 3.13

### ISSUE THREAD

**Issue by tolomaus** [matomo-org/matomo#15299]
Since upgrading to 3.13 all of the sessions where a user id was set get a new visit created for each action.

I'm using the piwik_java_tracker and looking at the code it puts a new random string the the visitor id of each request. This has worked fine in the past, both when a user id was set and when one was not set.

Probably related to https://github.com/matomo-org/matomo/issues/15205

**Comment by tsteur** [comment]
@tolomaus by the sounds the piwik_java_tracker does not set a visitorId (`_id` url parameter). Could you create an issue about this in the java tracker issue tracker https://github.com/matomo-org/piwik-java-tracker/issues

**Comment by tolomaus** [comment]
Sure will do, thx
