### ISSUE TITLE
New visit not created after logout

### ISSUE THREAD

**Issue by chetanakki** [matomo-org/matomo#15293]
FYI, In our application we are using UserId feature.

I am setting below attributes when user clicks on logout button in our Application.
_paq.push(['resetUserId']);
_paq.push(['trackPageView']);

But, when the user logs back new visit is not created for the user with same UserId.

Please let me know, what is wrong here?

**Comment by tsteur** [comment]
Since Matomo 3.12 or 3.13 a reset or login of the userId no longer creates a new visit since it is technically not a new visit.

You may be able to create new visit by calling this:

```js
_paq.push(['appendToTrackingUrl', 'new_visit=1']); // (1) forces a new visit 
_paq.push(["deleteCookies"]); // (2) deletes existing tracking cookies to start the new visit
// the two lines must be above the call to track* function
_paq.push(["trackPageView"]);
```

**Comment by chetanakki** [comment]
Thanks for the quick reply.
Please do update document here : https://developer.matomo.org/guides/tracking-javascript-guide#user-id

**Comment by tsteur** [comment]
Created a PR 👍

**Comment by chetanakki** [comment]
Thanks!.
I need one more information from you.
Suppose user is under a particular 'Menu' in our website, how to track what actions he is performing under that particular menu?.

**Comment by tsteur** [comment]
I suppose you want event tracking maybe? https://matomo.org/docs/event-tracking/ Hard to say would need to know more. Best to ask these question in our forum: https://forum.matomo.org/
