### ISSUE TITLE
AB Test core update not working correctly

### ISSUE THREAD

**Issue by robles-design** [matomo-org/matomo#15292]
It seems that the core update for AB Testing is not working correctly. I got the following warning:
WARNING: /plugins/AbTesting/Columns/Metrics/RemainingVisitors.php(115): Notice - A non well formed numeric value encountered - Matomo 3.13.1-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: AbTesting, Action: getMetricDetails, In CLI mode: false)

PHP Errorlog: PHP Warning:  Error while sending STMT_CLOSE packet. PID=9057 in /www/htdocs/w00bc20a/statistik/piwik/libs/Zend/Db/Statement/Mysqli.php on line 105

Matomo-Version: 3.13.1-b1 (got the error with the stable release and updated to beta, still the same)
MySQL-Version: 5.7.28-nmm1-log
PHP-Version: 7.3.11-nmm1

If I deactivate the core  update, the AB Testing stats were updated after a click Any idea?.

**Comment by tsteur** [comment]
Hi there, 
are you using the latest version of A/B Testing? If not be good to upgrade. Otherwise could you please reach out to our support so they can check it? Cheers

**Comment by tsteur** [comment]
Email for support is shop at innocraft.com

**Comment by robles-design** [comment]
Thanks for the answer. Yes, it's the latest AbTesting plugin (v3.2.15). I'll write an email.
