### ISSUE TITLE
Reporting API: range with today does not include today?

### ISSUE THREAD

**Issue by mockey** [matomo-org/matomo#15316]
It seems that a reporting API call with:
`period=range&date=YYYY-MM-DD,today`
actually only includes yesterday's data but not today's.
I can get today's data when I use tomorrow's date.
Is that intended that way?

**Comment by mockey** [comment]
Correction: I seems that a certain start date causes wrong results. Actually I request an event with:
`module=API&method=Events.getName`
and I get the right number of events with a start date of `2019-11-30` but I get less events with `2019-11-29`. What could cause this?

**Comment by mockey** [comment]
Ok, I think the issue is that reports with custom ranges are not getting updated when the next archive is due. I think I fixed that by adding a custom range to `archiving_custom_ranges[]` i the config.ini.

**Comment by tsteur** [comment]
BTW were you using Matomo 3.12 or newer? It should have been maybe fixed there.

**Comment by mockey** [comment]
I'm using 3.13.
BTW: Can it be that the week between the years does not get archived correctly?
The week from 2019-12-30 to 2020-01-05 has its last archived report on 2019-12-31.
The weeks before and after work correctly.
