### ISSUE TITLE
file bug70752.zip locked with password

### ISSUE THREAD

**Issue by FatherCandle** [matomo-org/matomo#15318]
Hi,
I have a need to use the matomofpm.tar file which i got from your project on DockerHub and for this purpose I must have all files in matomofpm.tar to be unlocked.
There is a file in the matomofpm.tar named bug70752.zip which is locked by a password.
Is it the wanted situation? if so, may i have the password to unlock it please?

Thanks in advance.

**Comment by Findus23** [comment]
Hi,

I honestly have no idea what you are referring to. I have never heard of either a matomofpm.tar or bug70752.zip file.

So can you please provide more details on which docker image you are using and where you find them.


The only thing I could find on the internet is https://github.com/php/php-src/blob/master/ext/zip/tests/bug70752.phpt which seems to indicate that the PHP zip C module has an automated test that to counteract PHP bug https://bugs.php.net/bug.php?id=70752 unzips a testfile that is protected with a password (`bar`).
But all of this has nothing to do with Matomo.

**Comment by FatherCandle** [comment]
Hello,
First of all I want to thank you because the links you provided helped me find the password to the file.

now to explain, I work in a close system and we wanted to use Matomo,
Therefore someone in my system looked for an Matomo image to set it up in our system.
He found the image here: https://hub.docker.com/layers/matomo/library/matomo/fpm/images/sha256-95e9630fdd342564c4b0f2471d7b26a3ebb7480fa37bb7701982edc02aa7cf4f

We could not set up the image in our system because of the locked file, so I tried asking for your help in the issue as a long shot but it seemed to pay off.

Thank you very much :)
