### ISSUE TITLE
MaxMindDB / Geolite2 - Can't get the module to work

### ISSUE THREAD

**Issue by aski71** [matomo-org/matomo#15310]
Hi,
I'm really struggeling with the GeoIP2 (PHP) module.
Can't get it to work.
It's gray and Matomo says: Not installed.
I followed the instructions for installing libmaxminddb, mod_maxminddb and MaxMind-DB-Reader-php, but whatever I do: Nothing changes. It says: Not installed.

On the right side it says:
Die apache_get_modules Funktion wurde nicht gefunden. Es wird daher von einem Nicht-Apache Webserver ausgegangen.
(apache_get_modules function not found. It might be a non apache system)

But it IS an apache system. With an nginx reverse proxy.

I also get:
Matomo konnte keine GeoIP $_SERVER Variablen finden.
(Matomo could not find GeoIP $_SERVER variable)

Is anyone able to help?

Thanks,
Alex

**Comment by mattab** [comment]
Hi Alex,

we'll probably stop using Maxmind soon, so closing this issue now, see https://github.com/matomo-org/matomo/issues/15308
