### ISSUE TITLE
GeoIP2 City South America "Continent" reported as Broken

### ISSUE THREAD

**Issue by aabenitez** [matomo-org/matomo#15317]
Error: Matomo tried to checking the location of a known IP address (194.57.91.215), but your server returned 'Unknown, Unknown, FR'. If this provider was configured correctly, it should return 'Besançon, BFC, FR'.

Matomo version: 3.13.0
MaxMind DB: GeoIP2-City-South-America.mmdb 
(Cities, regions and countries for Ip's of south america; Countries data for Ip's of other continents)

Why it tries to check with a France city IP if I installed a South America City database?

Best Regards.

![geoip2_south_america_db_matomo_broken](https://user-images.githubusercontent.com/7979587/71419611-108a6a80-264f-11ea-83e3-1419434217d1.PNG)
![XML_api_geoip_south_america_db](https://user-images.githubusercontent.com/7979587/71419614-1718e200-264f-11ea-926c-23a547c22a52.PNG)

**Comment by sgiehl** [comment]
Thanks for the report. It's right, we are currently checking a France IP only. Something we need to change for databases not containing Europe

**Comment by aabenitez** [comment]
Ok thank you, It Will be great!

**Comment by sgiehl** [comment]
@aabenitez  does the problem still exist with the latest release? I don't have access to the continent databases to test that...

**Comment by aabenitez** [comment]
Hello, I will test..

**Comment by aabenitez** [comment]
Now it recognizes my continent maxmind database.. Thank you!

Alcides B.
