### ISSUE TITLE
Segments do not work with encoded URL's as advised. 

### ISSUE THREAD

**Issue by jmumby** [matomo-org/matomo#15322]
When creating a segment using encoding as advised in the help text, no results are shown. 

![image](https://user-images.githubusercontent.com/4339071/71562691-0b169f80-2ae9-11ea-96cf-17720a7751d1.png)

For example `https%3A%2F%2Fexample.com` yields no results in the visits log where as `https://example.com` does.

**Comment by mattab** [comment]
Interesting, the inline text was designed for this page: 
https://developer.matomo.org/api-reference/reporting-api-segmentation
but indeed this same advice is wrong when within the UI, where the URLs should not be encoded.
