### ISSUE TITLE
rememberConsentGiven only lasts for session

### ISSUE THREAD

**Issue by wlabarron** [matomo-org/matomo#15321]
Similar to #14487, the `mtm_consent` cookie, added when calling `_paq.push(['rememberConsentGiven'])` and used to remember that consent to track was given, lasts for session instead of 30 years.

`mtm_consent_removed` lasts for 30 years.

**Comment by wlabarron** [comment]
I see [in the documentation](https://developer.matomo.org/guides/tracking-javascript-guide#step-3-user-gives-consent) that I can pass a number of hours to expire after, and I'm currently using that as a workaround. The docs do say though that the cookie should last for longer than session:

> By default, the cookie and consent will be remembered forever. It is possible to define an optional expiry period for your user consent by calling: _paq.push(['rememberConsentGiven', optionallyExpireConsentInHours]).

**Comment by tsteur** [comment]
I suppose this should last by default also for 30 years? Or we need to change the documentation to say the number of hours is required.
