### ISSUE TITLE
Additional options query per tracking request

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#15338]
On every regular request we are now performing an option select query in https://github.com/matomo-org/matomo/blob/3.13.1-b1/core/Archive/ArchiveInvalidator.php#L71 caused by report invalidation in https://github.com/matomo-org/matomo/blob/3.13.1-b1/core/Tracker/Visit.php#L581 

This was changed when removing temporary archives in https://github.com/matomo-org/matomo/pull/14639 since every request might now invalidate a previous archive. Before this was only executed when tracking data into a previous day that is not today and therefore rather rare. 

Can we maybe use this `option like %` query use a cache? That would mean though we also need to invalidate the cache when this flag is removed.

Not sure if there is a different alternative.

@mattab marking this for now as a regression since we don't want additional queries like these for each tracking request. Feel free to change it.

**Comment by mattab** [comment]
@tsteur yes this is a regression.
