### ISSUE TITLE
Segments with custom variables of scope page are porous (ie include out of segment pages)

### ISSUE THREAD

**Issue by ArnY** [matomo-org/matomo#15343]
Hello,

Our webmasters reported a few months ago (while running matomo 3.10.0 but the problem could have been present before) that when they were using segments to filter pages, they had pages that shouldn't be present since out of the segment. We are only using custom variable of scope page segments. The problem was still present in 3.12.0 today before I upgraded to 3.13.0.

We have 6 custom variables of scope "page": site (our CMS is a farm), author,  parentcategory, currentcategory, 2ndlevelcategory and typeofpage (actualite, formation, pagelibre, etc).

For example: https://droit.univ-nantes.fr/calendrier-universitaire-2019-2020-horaires-droit-et-sciences-politiques-rentree-vacances-examens-877922.kjsp which contains:

```
    _paq.push(['setCustomVariable', 6,'TypePage','actualite','page']);
```

We have a segment called "page of type news" defined like this:

"Value of custom variable 6 of scope page" is "actualite" ("news", in french)

When this segment is selected we expect , in Behaviour -> Pages, to only see pages of type "actualite" but we actually get pages with different custom variable 6 values.  For example, these pages show up: 

- https://droit.univ-nantes.fr/actualites/ (custom variable 6 is "pagelibre" not "actualite").
- https://lettreslangages.univ-nantes.fr/accueil/ufr-lettres-et-langages-2464638.kjsp (custom variable 6 is "ficheaccueil")

Since the value of the variable is set by the CMS itself, not a plugin, and a page can't be of 2 different type I don't think it's a CMS bug that would put the wrong page type in some case.

We have the problem with all segments, no matter which custom variable we use, the result is never reliable, being polluted with pages that shouldn't be there.

Thanks,

Arnaud

**Comment by tsteur** [comment]
Hi @ArnY . We fixed https://github.com/matomo-org/matomo/issues/11900 recently which implements correct segmentation behaviour.  We understand some users may expect different behaviour for their specific use cases which is why you can restore the old behaviour or there are workarounds see https://github.com/matomo-org/matomo/issues/15130#issuecomment-551252343

**Comment by viezel** [comment]
@ArnY I have added a FR to address this issue here https://github.com/matomo-org/matomo/issues/15438. Lets upvote it, so we can get this fixed.
