### ISSUE TITLE
Numbers are not formatted correctly in visits overview widget

### ISSUE THREAD

**Issue by jgkirschbaum** [matomo-org/matomo#15346]
Numbers are not formatted correctly in visits overview widget depending on the used languange. Have a look at the numbers in different languages. Some, like English, are correct, others, like German, not.

**English**
![grafik](https://user-images.githubusercontent.com/12797213/71726546-b8661c00-2e37-11ea-9033-ce6813ea964f.png)

**German**
![grafik](https://user-images.githubusercontent.com/12797213/71726528-ab492d00-2e37-11ea-9442-5c77988dcab8.png)

**French**
![grafik](https://user-images.githubusercontent.com/12797213/71726658-1a268600-2e38-11ea-87f6-c2e541d8dd02.png)

**Spanish**
![grafik](https://user-images.githubusercontent.com/12797213/71726725-34f8fa80-2e38-11ea-98e4-2455d9e4445e.png)

**Chinese ???**
![grafik](https://user-images.githubusercontent.com/12797213/71726562-c2881a80-2e37-11ea-9386-b72083ef3a65.png)

**Comment by sgiehl** [comment]
that should already be fixed in latest beta. See #15200
