### ISSUE TITLE
Matomo 3.13.1.b2 : Call to undefined method mysqli_stmt::get_result()

### ISSUE THREAD

**Issue by eldk** [matomo-org/matomo#15345]
Hello,

This occur since last beta update.

Matomo version: 3.13.1-b2

 PHP Fatal error: Call to undefined method mysqli_stmt::get_result() in (...) piwik/core/Tracker/Db/Mysqli.php

Tracking is completely down : all request are throwing 500 errors.

Thanks,

Eric

**Comment by eldk** [comment]
This has been solved by installing php-mysqlnd : https://dev.mysql.com/downloads/connector/php-mysqlnd/

**Comment by tsteur** [comment]
Seeing in https://www.php.net/manual/en/mysqli-stmt.get-result.php this is indeed only available with my mysqlnd. We'll need to change that.

**Comment by tsteur** [comment]
Thanks for reporting it @eldk
