### ISSUE TITLE
Wrong number format for thousands in languages different by english

### ISSUE THREAD

**Issue by tassoman** [matomo-org/matomo#15356]
I'm reading stats overview in italian and I get a decimal value for total visit. 
(I didn't cut in halfs any visitor, I still love them entirely :scissors: :hocho: ) So I expected total visits as an integer.

Thousands visits in Italian are **284.628** but this number gets rounded at 284,63.

![Screenshot_2020-01-07 - 2019 - Report Web Analytics - Matomo](https://user-images.githubusercontent.com/92727/71906315-1fead700-316a-11ea-9890-b41dd59a9435.png)
![Screenshot_2020-01-07 - 2019 - Web Analytics Reports - Matomo](https://user-images.githubusercontent.com/92727/71906316-1fead700-316a-11ea-9508-ac182e4007f8.png)

Italian and English have different separators for Thousands and tenths. 
Number formatting should be sourced by an integer (284628) then formatted to destination language only once.

**Comment by tassoman** [comment]
Related to #15026 and #14945

**Comment by tsteur** [comment]
@tassoman maybe this was fixed already? Could you test the latest beta maybe?

refs https://github.com/matomo-org/matomo/issues/15200

**Comment by tassoman** [comment]
I can try only if there aren't any database upgrade between 3.12 and master :thinking: 
In the mean time I'm fine overwriting `macros.twig` inside a custom theme plugin reverting this commit https://github.com/matomo-org/matomo/commit/f1d6cc7618221813699c0f8c0d97e5c41c48d323

**Comment by Findus23** [comment]
@tassoman You could also manually apply the patch from https://github.com/matomo-org/matomo/pull/15218 which should be easier.
