### ISSUE TITLE
Mention guides on no data - set up tracking code page

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#15360]
I think so far we have 4 guides:

```html
                <a target="_blank" rel="noreferrer noopener" href='https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-tracking-code-on-wordpress/'>WordPress</a>
                | <a target="_blank" rel="noreferrer noopener" href='https://matomo.org/faq/new-to-piwik/how-do-i-integrate-matomo-with-squarespace-website/'>Squarespace</a>
                | <a target="_blank" rel="noreferrer noopener" href='https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-analytics-tracking-code-on-wix/'>Wix</a>
                | <a target="_blank" rel="noreferrer noopener" href='https://matomo.org/faq/how-to-install/faq_19424/'>Sharepoint</a>
```

Be good to mention these on the no data tracking code page to increase the number of users starting to track. Otherwise you basically almost have to search on the web to find out how to do it since the integrate page is not that useful/helpful for that, and the tracking code itself doesn't help people either.

Could be shown under integrations:
![image](https://user-images.githubusercontent.com/273120/72011455-c3e59700-32be-11ea-8f1c-13a5a30f1f94.png)
or 
![image](https://user-images.githubusercontent.com/273120/72011543-f55e6280-32be-11ea-9e80-d94e3924bee3.png)

Considering 30% of the internet uses WordPress this alone will make it a lot easier to get started for 30% of our users.

**Comment by mattab** [comment]
Looks very good @tsteur :+1:
