### ISSUE TITLE
Error on settings page

### ISSUE THREAD

**Issue by callaloo** [matomo-org/matomo#15378]
I am getting this error below (using PHP 7.4). It is triggered on the settings page several times even when the page is refreshed.

`WARNING: /home/user/public_html/piwik/core/DataTable/Filter/ColumnDelete.php(164): Deprecated - array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead - Matomo 3.13.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: VisitsSummary, Action: getEvolutionGraph, In CLI mode: false)`

**Comment by tsteur** [comment]
This bas been fixed in 3.13.1 already. The fix is also already available in a beta if needed.

refs https://github.com/matomo-org/matomo/pull/15224
