### ISSUE TITLE
String not loaded in javascript while Feedback plugin is disabled

### ISSUE THREAD

**Issue by tassoman** [matomo-org/matomo#15385]
I've disabled _Feedback core plugin_, when I try searching websites in the upper left box, Matomo can't load translation string about _SearchOnMatomo_.

![Screenshot_2020-01-13 All Websites dashboard - 2020-01-13 - Web Analytics Reports - Matomo](https://user-images.githubusercontent.com/92727/72253987-1f878b80-3603-11ea-8414-6d5cfc5ba92d.png)

Should be hidden the whole _Help Resources_ section if the plugin is disabled? Or should the translation string reside in another plugin? Can't say 🤔

**Comment by tsteur** [comment]
It should be in the CoreHome plugin indeed 👍
