### ISSUE TITLE
Release notes error: DB changes in 3.13.1

### ISSUE THREAD

**Issue by toredash** [matomo-org/matomo#15402]
In the changelog it says there isn't any major DB changes (https://matomo.org/changelog/matomo-3-13-1/)

But there is in fact some DB changes in commit https://github.com/matomo-org/matomo/blob/4ad9f4ac89e6cbdb7b7c50bed4155193eb762dcc/core/Updates/3.13.1-b2.php

This should be noted in the release note. AFAIK, one need to run `./path/to/matomo/console core:update` to execute that specific SQL statement.

Is it correct that this information should be provided in the release notes ? I assume most users don't review commits from release to release.

**Comment by mattab** [comment]
This doesn't count as a "Major" db change as it only updates some fields. By Major we mean schema changes mostly (new columns, indexes, etc.)

**Comment by mattab** [comment]
To answer your question, the SQL will be automatically executed via the Web UI and there's nothing users have to do, so it should just work :+1:

**Comment by tsteur** [comment]
@mattab unless auto updates etc are disabled. Generally, `core:update` would always need to be executed when not updating through UI

**Comment by toredash** [comment]
> @mattab unless auto updates etc are disabled. Generally, `core:update` would always need to be executed when not updating through UI

We run stateless containers, and therefore don't use any of the auto update features or installing of plugins via the UI.

I'll just add a step to our routines to always run core:update when a new release is put into play, as thats probably easier than looking at each commit.
