### ISSUE TITLE
Seems 3.13.1 broke matomo

### ISSUE THREAD

**Issue by Bllacky** [matomo-org/matomo#15403]
I updated today from 3.13.0 and the end result is this:
` [DI\Definition\Exception\DefinitionException]
  Entry "Piwik\Archive\ArchiveInvalidator" cannot be resolved: Entry "Piwik\ArchiveProcessor\ArchivingStatus" cannot be resolved: Entry "Piwi
  k\Concurrency\LockBackend" cannot be resolved: the class is not instantiable
  Full definition:
  Object (
      class = #NOT INSTANTIABLE# Piwik\Concurrency\LockBackend
      scope = singleton
      lazy = false
  )
  Full definition:
  Object (
      class = Piwik\ArchiveProcessor\ArchivingStatus
      scope = singleton
      lazy = false
      __construct(
          $lockBackend = get(Piwik\Concurrency\LockBackend)
          $archivingTTLSecs = (default value) 7200
      )
  )
  Full definition:
  Object (
      class = Piwik\Archive\ArchiveInvalidator
      scope = singleton
      lazy = false
      __construct(
          $model = get(Piwik\DataAccess\Model)
          $archivingStatus = get(Piwik\ArchiveProcessor\ArchivingStatus)
      )
  )
`

Matomo is now completely broken.
I have no addons or anything else installed beside the standard matomo installation. All my previous updates have worked fine.

Using MariaDB and PHP 7.3.

The issue has also been reported on your forums: https://forum.matomo.org/t/udated-to-latest-version-and-hit-with-this-error-pasted-below/35651/4

**Comment by mattab** [comment]
can you please reupload all files? probably some files are not uploaded correctly.

**Comment by tsteur** [comment]
Likely `config/global.php` was not updated

**Comment by Bllacky** [comment]
Ok, will try.

**Comment by Bllacky** [comment]
Backup my config.ini.php from the config folder. Deleted the entire matomo installation and placed the latest version in its place. Copied config.ini.php back in its place, created the temp folder and everything worked afterwards.

Case closed.

**Comment by agri17** [comment]
Worked for me - Tahnks!
