### ISSUE TITLE
Cannot copy a dashboard to a user when the user is not one of the first 100 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15420]
(Bug reported by On-Premise support plan customer.)

Steps to reproduce:

* create 110 users with `./console visitorgenerator:generate-users --limit=100` 
* open the dashboard, click on Dashboard, click on "Copy dashboard to user"
* in the dropdown, select the last user from the list 
* click OK
* Expected the dashboard to be copied
* Got a red notification with the error message: 
```
Cannot copy dashboard to user zankunding, user not found. 
#0 [internal function]: Piwik\Plugins\Dashboard\API->copyDashboardToUser('1', 'zankunding', 'Dashboard') 
#1 core/API/Proxy.php(237): call_user_func_array(Array, Array) 
#2 Context.php(28): Piwik\API\Proxy->Piwik\API\{closure}() 
#3 core/API/Proxy.php(328): Piwik\Context::executeWithQueryParameters(Array, Object(Closure)) 
#4 core/API/Request.php(265): Piwik\API\Proxy->call('\\Piwik\\Plugins\\...', 'copyDashboardTo...', Array) 
#5 plugins/API/Controller.php(41): Piwik\API\Request->process() 
[...]
```

**Comment by sgiehl** [comment]
fixed with #15424 

@mattab You've changed the milestone to 3.13.2, but the PR was merged to 4.x-dev already? Shall I cherry pick the commit to 3.x-dev branch, so it will be included in 3.13.2 as well?
