### ISSUE TITLE
visitIp not included in Live.getLastVisitsDetails since 1.13.1

### ISSUE THREAD

**Issue by Romain** [matomo-org/matomo#15421]
I updated Matomo from 1.13.0 to 1.13.1 last week.
Since then, [my plugin](https://github.com/Romain/Matomo-IP-to-Company) displays incoherent data.

Digging into this problem, I realized that this new version of Matomo introduced a change in the content returned by the API endpoint `Live.getLastVisitsDetails`. The `visitIp` key is not included in the JSON response anymore.

Could you include this value again in the response?
Thanks!

---

### How to reproduce
- make sure that you have Matomo 1.13.1 running
- install https://plugins.matomo.org/IPtoCompany
- look at Visitors / Companies
- check your logs

**Comment by sgiehl** [comment]
That hasn't been changed. The visitIp should still be included.

**Comment by tsteur** [comment]
@Romain  are you using a valid token_auth of a user with at least view access when fetching the list of segments? There was some refactoring which was needed for some issue but it should still behave the same. I was going to say you could workaround by adding a `_showAllSegments=1` to the request but I think underscore parameters can maybe not be used. So this might not work.

cc @diosmosis

**Comment by tsteur** [comment]
Actually, I was reading this wrong. This is not about segments.

**Comment by tsteur** [comment]
This works for me. It looks like the token_auth is not valid very likely. Maybe the token was regenerated?

**Comment by Romain** [comment]
Hi @tsteur ,

Thanks for having a look a this.
Actually, the `token_auth` shouldn't be a problem. Since I'm using the `Request` class, I think that this parameter is not required.

Here is what I'm doing:

```
$response = Request::processRequest('Live.getLastVisitsDetails', [
            'idSite'        => $idSite,
            'period'        => $period,
            'date'          => $date,
            // 'token_auth'    => $_ENV['AUTH_TOKEN']
]);
```

I tried to pass the `token_auth` there, but it doesn't change anything.
Everything was working smoothly up to the moment where I updated to 1.13.1.
If I dump the response, there's no `visitIp` key in the visits listed.

**Comment by Romain** [comment]
I also tried `_showAllSegments` but the result was the same.

**Comment by tsteur** [comment]
@Romain I see. Thought you do this through the HTTP API. I just tried to reproduce this and it seems to work for me. Maybe you have some other plugins active that maybe change this behaviour?

**Comment by Romain** [comment]
@tsteur Unfortunately I don't. On my dev setup, I just have Matomo, my plugin, the LogViewer and the VisitorGenerator. On my prod setup, I just have Matomo and my plugin. Here are the plugins that are installed on my dev setup:

![Capture d’écran 2020-01-22 à 08 32 47-fullpage](https://user-images.githubusercontent.com/160767/72874283-ea112b00-3cf1-11ea-9484-0a48f3e77289.png)

**Comment by Romain** [comment]
Just to give you more information on the data I get.

Here is a sample of code more detailed:

```
$response = Request::processRequest('Live.getLastVisitsDetails', [
            'idSite'        => $idSite,
            'period'        => $period,
            'date'          => $date
]);

foreach ($response->getRows() as $visitRow) {
            $logger->error($visitRow);
}
```

This logs what follows:

```
# ['idvisit' => '1337', 'idsite' => '1', 'idvisitor' => '?d???L?', 'visit_last_action_time' => '2019-12-19 13:08:59', 'config_id' => '?O???R', 'location_ip' => 'd.

**Comment by Romain** [comment]
Ok, I solved it by changing my request this way:

```
$response = Request::processRequest('Live.getLastVisitsDetails', [
            'idSite'            => $idSite,
            'period'            => $period,
            'date'              => $date,
            'segment'           => $segment,
            'flat'              => FALSE,
            'doNotFetchActions' => FALSE
]);
$response->applyQueuedFilters();
```

Thank for your help.
