### ISSUE TITLE
Have an option to track only needed data for better privacy

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#15435]
As we know it is good practice to only collect data that is actually needed.

Matomo should have a client or server side option to track only needed data. There is obviously already the possibility to disable plugins to no longer track certain data and this may be enough for now. (sometimes features break though when disabling them)

Maybe, ideally, it also be possible to not track individual data like page URLs, page titles, referrers, devices, ...

Eg we could leverage all dimension classes to let a user disable certain dimensions and this way they would not be tracked.

**Comment by tsteur** [comment]
refs https://github.com/matomo-org/matomo/issues/12735

**Comment by mattab** [comment]
What is the scope of this issue, (how) would it be different from #15479 / https://github.com/matomo-org/matomo/issues/12737?

**Comment by tsteur** [comment]
> Eg we could leverage all dimension classes to let a user disable certain dimensions and this way they would not be tracked.

That be the difference. Basically, if you know you're not going to look at City reports, then you could disable that dimension and it won't be tracked, won't need any storage and won't even show the report in the UI and the segment be removed as well. In Custom reports the dimension be not available either.

It's less about personal data here but data in general maybe. The less data you track, the better for privacy. And if you know you're not wanting some specific information, then it be good to disable it if someone wants extra privacy. 

So this goes beyond what is needed for "privacy compliance" where a user would disable collecting certain information even though it is not personal data.

**Comment by diosmosis** [comment]
@tsteur thinking about creating a measurable setting called "Disabled Dimensions" w/ UI_CONTROL_MULTI_SELECT that lists every dimension. What do you think? It might be better to put this in privacy settings page, but it might also be better to do this per site maybe?

**Comment by tsteur** [comment]
Ideally it was possible to configure it on a global basis and per site but thinking we could start to have it only available globally for now in eg the privacy settings page using the UI_CONTROL_MULTI_SELECT. If it's easy could additionally also do it on a per site basis.

**Comment by diosmosis** [comment]
👍

**Comment by tsteur** [comment]
closing this as a wontfix see explanation in https://github.com/matomo-org/matomo/pull/16609#issuecomment-723733536
