### ISSUE TITLE
VisitorLog.php(225): Trying to access array offset on value of type null - Matomo 3.13.1

### ISSUE THREAD

**Issue by c-prompt** [matomo-org/matomo#15430]
On the Administration page (index.php?module=CoreAdminHome&action=home&idSite=1&period=week&date=today), I'm seeing four of these:

`WARNING: /matomo/plugins/Live/Visualizations/VisitorLog.php(225): Notice - Trying to access array offset on value of type null - Matomo 3.13.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: Live, Action: getLastVisitsDetails, In CLI mode: false)`

I'm seeing this after upgrading to 3.13.1 (PHP 7.4).

_Originally posted by @c-prompt in https://github.com/matomo-org/matomo/issues/14701#issuecomment-576846178_

**Comment by c-prompt** [comment]
...AND they're gone >.>

I had logged in and logged out multiple times as well as clearing browser cache before logging the error, just to make sure it wasn't local. Just did a refresh and I can't get the error to show. Logged in and out again.

So beats me if this should be closed.

**Comment by tsteur** [comment]
Let's keep it open as it shouldn't be too hard to add a check for this.

**Comment by c-prompt** [comment]
Good idea as I just went back again and saw eight.
