### ISSUE TITLE
 in Visitors>User IDs, opening a Profile using segmented visits log for a given User ID will also show other User IDs 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15440]
Reproduce:
* Go to Visitors>User IDs, 
* click the segmented visits log icon on a given User ID 
* the Visitor profile modal opens
* Got: it shows the visits for a specific visitor ID. The URL looks [like this for example](https://demo.matomo.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=62#?idSite=62&period=week&date=today&segment=&category=General_Visitors&subcategory=UserId_UserReportTitle&popover=RowAction$3AvisitorDetails$3Amodule$3DLive$26action$3DgetVisitorProfilePopup$26visitorId$3Dd6ed99710191f9f5). we clicked on the User ID `momofdivers` yet the URL includes `visitorId$3Dd6ed99710191f9f5` instead of `userId$3Dmomofdivers` 
* Expected instead: it shows the visits where User ID is momofdivers

This has become a bigger issue after https://github.com/matomo-org/matomo/pull/14360 now that many User Ids visits can share the same visitor id. 

Note: bug reported by on-premise customer.

It is important and expected to be able to see all visits for a given User ID directly using that icon.

Note: a workaround in the meantime is to create a Segment for each user ID and apply the segment to the Visits log.

**Comment by tsteur** [comment]
This is not a bug. Visitor log always shows visitor log. What you are after would be a `User profile` basically.

**Comment by mattab** [comment]
1) then we would need to remove the "User ID" from the visitor profile?

currently it shows the user ID: ![Screenshot from 2020-01-23 15-01-05](https://user-images.githubusercontent.com/466765/72950789-398a5080-3df1-11ea-889b-6b4e88859819.png)

2) also the "Open Visitor Profile" next to the User ID row, make people expect that they will see all visits for that visitor/user id. All other reports do this, when you click on the segmented visits log icon, it will segment with this dimension applied. But User ID is different. Maybe it's fine to leave it this way, but it's not quite clear.

**Comment by tsteur** [comment]
Saying always Visitor Profile sounds good.

> All other reports do this, when you click on the segmented visits log icon, it will segment with this dimension applied

In this case we are not showing the segmented visitor log, but the visitor profile. That's why it is expected to not be applied. Could also just show the segmented visitor log instead of the profile.

**Comment by mattab** [comment]
> Saying always Visitor Profile sounds good.

:+1: 

> Could also just show the segmented visitor log instead of the profile.

That would work better imho :+1:

**Comment by KarthikRaja1388** [comment]
same issue is raised again, viewing the segmented profile from "Visitors > user ID" is showing visits for one visitor id and ignoring the others

**Comment by mattab** [comment]
On a call now with a user, and he mentions how this is important.

There are 2 things to improve:

* User ID report -> icon should open a `User Profile` showing all visits from this user id on all devices
* Visits Log -> icon "View visitor profile" ideally be renamed to "View User USER_ID_HERE" for visits with a user id, and then when clicked it opens the `User Profile` showing all visits from this user id on all devices

**Comment by tsteur** [comment]
@mattab what I'm reading here is to restore the old behaviour of user feature which refs https://github.com/matomo-org/matomo/issues/15593 . They could also simply like it was suggested for @peterbo try to set visitorId to same value as userId or generate it based on userId it might work.

From our side, if https://github.com/matomo-org/matomo/issues/15593 is not restored to the original behaviour, we will most likely show the segmented visitor log here

**Comment by mattab** [comment]
Let's wait for https://github.com/matomo-org/matomo/issues/15593 resolution. If we set Visitor id as a hash of User ID, then it would "solve" this issue as well.

**Comment by mattab** [comment]
Parts of the feature were re-added in https://github.com/matomo-org/matomo/pull/16226/files
but currently set to 0: ` enable_userid_overwrites_visitorid = 0 `
(the ini has no description and not documented yet in the website?) 

-> would we consider set this to 1 by default in the future or in Matomo 4?

**Comment by tsteur** [comment]
It is `1` in Matomo 4 already

**Comment by mattab** [comment]
Ok so this issue is likely already solved :+1: 
 I'll test it as soon as I get 4.x-dev working (currently getting the Unknown column 'log_link_visit_action.time_network' in 'field list' )

**Comment by mattab** [comment]
Great news, it's now fixed in Matomo 4 :tada:

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/some-user-visits-only-show-visitor-id/49516/1
