### ISSUE TITLE
File integrity check php error_log

### ISSUE THREAD

**Issue by limitstudios** [matomo-org/matomo#15456]
What is everyone's thoughts on excluding the error_log from the file integrity system check?

**Comment by Findus23** [comment]
Should be fine. Simply add it to this list here: https://github.com/matomo-org/matomo/blob/5322d058d5afcd2c40e76a13762038e05f0795f3/config/global.php#L133

**Comment by limitstudios** [comment]
Ok I will create a pull request should I do one for v3 and one for v4 or just v4 and it will be backported to v3?
