### ISSUE TITLE
Different totals count in «Times» report for Today period

### ISSUE THREAD

**Issue by tassoman** [matomo-org/matomo#15468]
Hello there, a coworker of mine was reading «**today**» hourly reports reporting some troubles.
He was surprised because he found H23 visits reported in the _client times report_. 
So I explained him that if we have a visit from Tokyo (JST) at H15 Italian time (CET), we're recording the same visit _at H23 in client report_, and _H15 in server report_.

![Screenshot_2020-01-27 - 2020-01-27 - Web Analytics Reports - Matomo](https://user-images.githubusercontent.com/92727/73183632-6b662480-411b-11ea-9acf-f67aa5503b6e.png)

Ok, but we've discovered more issues with this:

- Italian translation translates «_Times_» with «_Volte_» "you clicked three times". It's wrong, should translate «Times» with «Orario» or «Ore» (hours)
- _Server Times report_ details is displaying wrong elapsed time from generation (it's an integer) maybe related to #15200 
- Datatable totals are different, I mean totals between server times and client times. Should a visit be a 1:1 relation between client and server, huh? :thinking:

I have a one more question. If a visitor from Tokyo (JST) (07:00 - **28**/01/20) hits the server at H23 (23:00 **27**/01/20) server time (CET), are reports filled in different periods? :thinking:

:man_health_worker: :car: :clock1030: :zap: :boy: :guitar:

**Comment by tsteur** [comment]
Re the wrong translations feel free to suggest a change see https://matomo.org/translations/ . We don't manage translations in Github directly.

There seems to be only a very small difference. If you are viewing today as you mentioned, then the other report would have been generated a few seconds later or so and by then a few more visits would have been tracked for example.

**Comment by tsteur** [comment]
From what I can see only the server time is important for the visit and we wouldn't attribute a visit to another day in the client time report just because of a different date there.

Let me know if there's a further issue and happy to reopen.
