### ISSUE TITLE
Two YAML parser

### ISSUE THREAD

**Issue by limitstudios** [matomo-org/matomo#15469]
Looking at composer it appears there are 2 parsers for working with YAML

- mustangostang/spyc (in require), and;
- symfony/yaml (in require-dev)

It doesn't really make sense to require both, so which should be set to be the sole parser, obviously the decision has to take into account PHP 7.2, 7.3, 7.4 compatibility for the v4.x branch

**Comment by tsteur** [comment]
We're only using `mustangostang/spyc` AFAIK.

It seems the other one was added in https://github.com/matomo-org/matomo/commit/d0c93e6fa77bdcfdab2d3cb66301a5144fd3addd maybe to avoid some conflict issue. Could be maybe removed by now.

**Comment by limitstudios** [comment]
Ah ok no problem when I upgrade the current symfony packages to 4.4 (LTS) for the 4.x branch I'll remove that if it appears not to be required.

**Comment by tsteur** [comment]
👍
