### ISSUE TITLE
Matomo not capturing details

### ISSUE THREAD

**Issue by chetanakki** [matomo-org/matomo#15475]
Recently we have integrated our application with Matomo. 
Need answers for the following.

1.  After Login successful to our appliation, Only for Dashboard section, there are 2 instance shown on Matomo. All other pages are shown only once.

2. For some of the instances on Matomo, it shows 0 seconds on the page against me waiting on that page for few seconds

3. On the Matomo Dashboard, The graph 'Visits Over Time' is not getting updated on run-time basis

4. On the Matomo Dashboard, The Map 'Visitor Map' not showing any information. It shows only the map with no information on it. The message we observed on the map is: "66 unique visitors (100%) 86 with unknown region"

5. For some of the intermediate page navigation, the event is not captured in Matomo.

Your help is greatly appreciated.

Thanks in advance.

**Comment by tsteur** [comment]
@chetanakki these sound like things you want to ask in the forums maybe https://forum.matomo.org/ or through our support in case you have a support plan: https://matomo.org/support-plans/

It may be good to create a separate thread for each question/problem you are facing and describe them with as much details and insights as you can. Eg it is not clear what you mean  by

> , Only for Dashboard section, there are 2 instance shown on Matomo. All other pages are shown only once.

or what you mean by "run-time basis". So be good to explain what is happening, and what you are expecting.

If there is somewhere a clear bug in Matomo feel free to create an issue. Above points sound more like server set up or configuration issues.

**Comment by chetanakki** [comment]
@tsteur  I understand these questions are not supposed to ask here. However some things are not related to configurations. like,

1.For some of the instances on Matomo, it shows 0 seconds on the page against me waiting on that page for few seconds

2. On the Matomo Dashboard, The graph 'Visits Over Time' is not getting updated on run-time basis
Since we dont have control over how, matomo calculates the time spent/page and how it plots the data.
If we get information about those in the documentation that will be good. Since there is no documentation about that it is hard to find the causes.

Can you please share the documentation details about those?

**Comment by tsteur** [comment]
Check out the FAQ re 0 seconds: https://matomo.org/faq/how-to/faq_21824/ . There is also eg https://github.com/matomo-org/matomo/issues/9540 and there should be some other issue basically it is not possible yet to get the accurate time spent on the last page view AFAIK.

The graph visits over time gets updated regularly depending on whether you have browser archiving enabled or whether you use CLI archiving in the background (in which case you need to have a cronjob running see https://matomo.org/docs/setup-auto-archiving/ )
