### ISSUE TITLE
Matomo can't track IE <9 any more

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#15477]
caused by https://github.com/matomo-org/matomo/pull/15184
reported in https://forum.matomo.org/t/update-3-13-1-no-tracking-in-internetexplorer-error-addeventlistener/35826

IE <9 doesn't support `addEventListener()`, instead a wrapper is used to make matomo.js compatible. But #15184 added a non-wrapped eventlistener which seems to break tracking.

https://github.com/matomo-org/matomo/blob/907a3d6f78693bcaadde7460fe0c2224161de63b/js/piwik.js#L6817

**Comment by mattab** [comment]
This seems fixed, so closing :+1:
