### ISSUE TITLE
setCustomUrl in Cordova App on IOS

### ISSUE THREAD

**Issue by werishi** [matomo-org/matomo#15470]
Hello

i have an issue with the behavior of setCustomUrl
if i write
track.push(["setCustomUrl", 'https://example.com/newpagename']);
i will get "example.com/https://example.com/newpagename"

so he doesnt overwrite the domain. only the path

yeah i could just use: track.push(["setCustomUrl", 'newpagename'])

but the problem is, if i use this on an ios device i get another url

file://var/container/Bundle....../<unreadableid>/https://example.com/newpagename

i need Webapp and Cordova App to track the same url

Maybe you can give me a hint.

Have a nice Week

**Comment by tsteur** [comment]
Maybe have a look at https://github.com/matomo-org/matomo/issues/14375 (maybe look more into page titles from what I see there) and https://matomo.org/faq/how-to/faq_33772/

**Comment by werishi** [comment]
Hi

i use setDocumentTitle in addition to setCustomUrl. setDocumentTitle works fine, but. doesnt solve my problem, its another data record.  I dont need Cookies and the functions dependent on it.

the Url behind setCurrentUrl is used to create a root structure in the matomo "page behavior" view.

First of all URI = scheme:[//authority]path[?query][#fragment]
setCurrentUrl should be called: setCurrentPath or do what it should. or am i missing something vital?

there musst be a way to overwrite the "authority"

**Comment by tsteur** [comment]
@werishi looking at the code... when you set `_paq.push(["setCustomUrl", 'https://example.com/newpagename']);` Matomo should not change that value. Are you using our JS tracker directly or some package for this?

**Comment by werishi** [comment]
i use it directly insite my ember framework.

**Comment by tsteur** [comment]
I've just tested this locally and this should work. Is the title working correctly for you? Maybe also double check the method is executed before calling `trackPageView`. Is there otherwise maybe any way you can debug this issue? So far it doesn't really look like an issue on our side.
