### ISSUE TITLE
Disable various features by default that might track personal data

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#15479]
This be probably the only way to ensure users are aware they need to ask for consent to use certain features. To be seen if individual features can be enabled by an admin on a site level or only across sites by super user.

features that should be eg disabled by default 
* Events
* Custom dimensions
* Custom variables
* User ID (extra ticket in https://github.com/matomo-org/matomo/issues/15432 )
* referrers https://github.com/matomo-org/matomo/issues/15426
* fingerprint https://github.com/matomo-org/matomo/issues/13655

When enabling a feature, they should be presented with a message saying they need to ask for consent potentially if they track personal data. refs https://github.com/matomo-org/matomo/issues/15478

refs https://github.com/matomo-org/matomo/issues/15435

**Comment by mattab** [comment]
duplicates #12737 ?

**Comment by tsteur** [comment]
Kind of. Guess #12737 would need to do this by default instead of having a feature to enable that mode. I suppose we can close this issue for now and see. It be great if there was just not one "super privacy" mode but "super privacy" mode be enabled by default and then individual features could be enabled on demand.
