### ISSUE TITLE
Missing documentation of deletelogs->delete_logs_unused_actions_schedule_lowest_interval

### ISSUE THREAD

**Issue by toredash** [matomo-org/matomo#15484]
Hi,

I'm unable to find any documentation on this config option:
delete_logs_unused_actions_schedule_lowest_interval

Feature was introduced in #13822

I've checked the forums and global.ini.php for help but there is no docs on its usage:
https://github.com/matomo-org/matomo/blob/162513d7608a43d53f178f744543e30dafc15f9b/config/global.ini.php#L910-L921

Reading from the code, I get that it is related to how often one should purge data in table `log_action`.

I've made a PR to add some docs to this, https://github.com/matomo-org/matomo/pull/15492, but also to add a user-definable value for how many rows to analyze in one iterations. Our `log_action` table contains >100M rows, so pruning data takes a while.

**Comment by tsteur** [comment]
It's basically how much time is in between matomo tries to delete unused actions again

**Comment by toredash** [comment]
Created a new PR for 4-x.dev branch. Original post updated.

Good to get a verification on the intended usage for the variable.

**Comment by toredash** [comment]
closed by https://github.com/matomo-org/matomo/pull/15492
