### ISSUE TITLE
Lots of unknown browser for Android

### ISSUE THREAD

**Issue by daganM** [matomo-org/matomo#15497]
Don't know if it's related directly to matomo, but since some days/ a few weeks, lots of users that are coming from Android has an unknown browser. Some have Chrome displayed, but the very majority has no browser...

Is there something maybe that has changed and could cause this ?

**Comment by sgiehl** [comment]
Matomo is still only able to display/handle Browsers. Mobile Apps and stuff like that will be displayed as unknown. See #5413
Maybe you have a lot visits that are coming from a mobile app

**Comment by daganM** [comment]
Actually, most of them are coming from Facebook. 
I don't have the Facebook app but I would have guessed it opened in the in-app chrome browser by default, isn't it ?

**Comment by sgiehl** [comment]
Jep. Guess the in-app browser is detected as facebook app and thus not shown as browser...

**Comment by tsteur** [comment]
@daganM @sgiehl Can we close this issue since it seems to work as expected or is it basically a feature request? (which we maybe already have an issue for?)

**Comment by daganM** [comment]
Yes I'm closing. I didn't know in-app chrome was not detected as being chrome.
