### ISSUE TITLE
for newly created Goals, calculate their historical reports from the historical data (when possible)

### ISSUE THREAD

**Issue by anonymous-matomo-user** [matomo-org/matomo#1550]
It should be possible to see goal conversions that happend before the goal was created in piwik if there are fitting ulr patterns in the historical data.  
Keywords: goal historical

**Comment by voarsh** [comment]
Shame.  I would have liked this.

**Comment by mattab** [comment]
Re-opening as it's a valid feature request 👍 Thank you!

**Comment by mattab** [comment]
duplicated in: https://github.com/matomo-org/matomo/issues/6183
