### ISSUE TITLE
Tracker API: trim spaces in event names, category, actions

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15501]
Currently in the Tracker API we do trim content names, pieces, targets strings. To be consistent we could also trim event names (`e_n`), event category (`e_c`), event actions (`e_a`). 

We could even trim a couple of other inputs where it could make sense like Page title (`action_name`), possibly site search keyword (`search`, `search_cat`). 

fyi: creating this issue as a result of a user and developer getting confused about duplicate data in an Events report. `Problem solved by "invisible empty space".`

**Comment by tsteur** [comment]
sounds good

**Comment by flamisz** [comment]
Hi @mattab and @tsteur 
I was looking into this issue and this is what I found:

I believe the `search` and `search_cat` already trimmed here:
[ActionSiteSearch](https://github.com/matomo-org/matomo/blob/3141a74700044ea930bee0f53618906f6f8a1a4b/plugins/Actions/Actions/ActionSiteSearch.php#L258-L259)

I checked the `action_name`, found a place where it should be trimmed, I make a PR for that.

I check the other request parameters too.

EDITED:

I checked the other parameters and they all looking good to me: either not string, or goes through some kind of validation or trimmed.
Do I miss something here?

**Comment by tsteur** [comment]
@mattab looks indeed like event names etc are already trimmed (by looking at code, not reproducing). Do we maybe otherwise still have the link to the original conversation?

**Comment by mattab** [comment]
@tsteur sure, you can find it in conversation #641565

**Comment by flamisz** [comment]
> @tsteur sure, you can find it in conversation #641565

@mattab what is this number? where can I find this conversation?
thanks

**Comment by mattab** [comment]
Here is what user wrote:

> The empty space was in the "ACTION" I have sanded throw the _paq.push("trackEvent",…) function, so I thought if the developer has any mistake in his code, then you can also trim the text.

Before:

> I will ask to update our Matomo version.
> Problem solved by "invisible empty space".
> Maybe it is better to have a "trim" function when you receive the tracker.

Before (original report):

> I have a new problem using the goals and funnels,
> I build a new goal with few steps and a funnel.
> Every time the user gets a specific level, the funnels goes out and it never finish the funnel.
> As you can see, I'm sending in the network panel the required action.
> screenshots missing but not relevant anyway

**Comment by flamisz** [comment]
Thanks @mattab, it's useful. In this case indeed the action name was the problem. The PR will fix that.

**Comment by sgiehl** [comment]
@mattab it seems all action/event names are meanwhile already trimmed. The funnel problem was already solved in a L3 issues, so guess there is actually nothing left to do here. If the user is still having that issue, maybe he can describe the issue a bit more clearly, so it's easier for us to look for a potential reason.

**Comment by tsteur** [comment]
closing for now and we can reopen if that should appear again.
