### ISSUE TITLE
Loading Page Overlay fails and logs user out

### ISSUE THREAD

**Issue by kiwi2101** [matomo-org/matomo#15513]
In a Matomo 3.13.1 when I'm calling a Page Overlay I always get kicked out of the current session with message "Error: Your session has expired due to inactivity. Please log in to continue."
I can't find any reason for this behavior. Any help would be appreciated!

**Comment by tsteur** [comment]
You may get logged out if you don't select "remember me" on log in and if you're not active for 30 minutes. For how long are you on the overlay page usually when this happens?

**Comment by kiwi2101** [comment]
I did select "remember me" on login. I'm getting kicked out as soon as I call the overlay page.

**Comment by tsteur** [comment]
I've tried to reproduce this on a few Matomo installations but always works for me. Do you know if there is any custom login plugin active, or anything else custom maybe? Eg do you log in regularly through the regular log in screen or maybe use a feature we have called `logme` or something?

**Comment by tsteur** [comment]
Also... wondering... do you maybe have eg on the page you are opening the overlay for maybe `disableCookies` active or so?

**Comment by kiwi2101** [comment]
Matomo is a pretty standard installation but quite a lot of pages getting tracked there (15 in total). No special login or disableCookies on the target pages. I wondered if there is any Header data which interferes but removing them didn't help.
Strange thing was, that I could call the staging-System. No difference there but the staging domain is the same where matomo is running.
So I double checked the output in Chrome and got following warning:

"A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>."

By the way I can see the iframe content with the called page but the main frame shows the session timeout error message. I also tried the option overlay_disable_framed_mode but looks like the same thing happens, the page is called without any bubbles.

**Comment by tsteur** [comment]
Is your site or Matomo running on `http://`? 

Any chance you could maybe create a login for us so we could reproduce it there and do some investigation? I suppose a user with view access be enough. If so, feel free to send us details to hello at matomo dot org. 

Otherwise be good to know if your site is running http or https

**Comment by pyuyu** [comment]
I also encountered the same problem

**Comment by BigIron5** [comment]
Same problem here.

**Comment by mattab** [comment]
@tsteur the issue can also be reproduced in our instance, it looks like this on loading Overlay:
![Screenshot from 2020-02-14 10-56-57](https://user-images.githubusercontent.com/466765/74482152-de8fd900-4f18-11ea-87d6-862ab9960863.png)

and then the session is logged out.

**Comment by BigIron5** [comment]
Yep, seeing the same thing here in both Chrome and Firefox.

**Comment by tsteur** [comment]
It seems to depend on the site. For matomo.org it cannot be reproduced while it can be reproduced for innocraft.com

**Comment by tsteur** [comment]
I tested and https://github.com/matomo-org/matomo/pull/15561 fixes it for me.

**Comment by tsteur** [comment]
@nichierichetti this should be fixed. Are you familiar with browser developer tools particularly the network tab? Does your site maybe send some headers around `referrer` like `no-referrer` or so?

**Comment by nichierichetti** [comment]
Thanks @tsteur for the reply. These are the headers related to what you asked that I see:
General > Referrer Policy: same-origin
Request Headers > referer: https://analytics.openstudio.one/?module=CoreHome&action=&period=day&date=yesterday

Also, cookies are well set up because I have the MATOMO_SESSID, auth_sid

**Comment by zippex** [comment]
I had this issue due to a false redirect within my nginx config: 
`if ($request_uri ~* "^(.*/)index\.php(/?)(.*)") { return 301 $1$3; }`

Are you using a template for your nginx vhost and is there a similar line to redirect "/index.php" to "/"? If so, give it a try without this line 🤞
