### ISSUE TITLE
Content interaction tracking fails if banner is enclosed by A element with external link

### ISSUE THREAD

**Issue by peterbo** [matomo-org/matomo#15529]
The issued request looks like this: https://matomo.dev/piwik.php?link=https://example.com/&c_i=click&c_n=[content-name]&c_p=[content-piece]&c_t=[content-target]&idsite=1&[...]

E.g.
`<a href="https://example.com/" target="_blank">
  <img src="image.svg" data-track-content="data-track-content" data-content-name="[content-name]" data-content-piece="[content-piece]">
</a>`

If href is an internal link, content tracking works as expected.

**Comment by tsteur** [comment]
Haven't tried it yet but this may be fixed by https://github.com/matomo-org/matomo/pull/15406/files in Matomo 4

**Comment by peterbo** [comment]
Looks good, thanks for answering, Thomas! I'll close and test asap, and reopen, if necessary.
