### ISSUE TITLE
Matomo is causing high wait time

### ISSUE THREAD

**Issue by broros** [matomo-org/matomo#15523]
Web browser is waiting for data from the server which is slowing down my website. Is there anything I can do to reduce the wait time?

matomo is hosted on the same server as the website

<img width="920" alt="Screenshot 2020-02-06 at 11 23 59 AM" src="https://user-images.githubusercontent.com/598228/73967816-deb72580-48d5-11ea-95f2-201112cc977d.png">

**Comment by Findus23** [comment]
See e.g. https://forum.matomo.org/t/plugin-slows-my-site/35628/2?u=lukas for an answer to this.

**Comment by tsteur** [comment]
@broros closing this issue for now. Be good to check out the link from @Findus23 

Also make sure development mode is disabled. And maybe have a look at your average waiting time over multiple requests just in case this only happened once for example. On server side the tracking requests usually take 50ms, with queued tracking 5ms. Obviously as @Findus23 this depends on your server (eg does it use SSD, is opcache enabled, etc)
