### ISSUE TITLE
Segmentation by Custom Variables doesn't appear to work

### ISSUE THREAD

**Issue by chends888** [matomo-org/matomo#15524]
I'm trying to segment my users based on a Custom Variable, but it doesn't appear to work. Wasn't the name of the Custom Variable supposed to appear on my Segmentation criteria? (check image below)
Even if it wasn't supposed to appear, I've tested with a value I'm sure exists, and when i click "Test".
Thanks in advance!!

https://imgur.com/CVSI172
https://imgur.com/IyydNoK

**Comment by tsteur** [comment]
@chends888 when you use the test button, it only searches a few hours back in your data. It's possible that there is actually data just no recent data.

**Comment by chends888** [comment]
> @chends888 when you use the test button, it only searches a few hours back in your data. It's possible that there is actually data just no recent data.

I've actually tested with ID's I just saw under the "Visits in Real-time" tab. So I don't really know what'd happening

**Comment by chends888** [comment]
Never mind, I was checking using the variable name not the variable value. Thanks!!
