### ISSUE TITLE
Email reports: Brand image is not getting displayed

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#15526]
Issue; When receiving email reports, brand image is not loading

Steps to reproduce:

1. Log in to Matomo
2. Create an email report
3. Send report

Please find the image attached
![image](https://user-images.githubusercontent.com/26726594/73980421-091be800-4995-11ea-8042-49f4831adff6.png)

**Comment by tsteur** [comment]
The URL points to localhost and therefore it cannot work. It would only show up if the Matomo has a public URL.

**Comment by KarthikRaja1388** [comment]
Issue exits in Cloud as well. Another customer raised this issue- " In all of my emailed reports, our logo does not show up. It's a standard jpg file, and it show in the matomo header on my dashboard. "
