### ISSUE TITLE
Missing crossorigin attribute in manifest link

### ISSUE THREAD

**Issue by john357smith** [matomo-org/matomo#15534]
In case Matomo is behind the restricted access, the manifest.json is not loaded with error 401 (Unauthorized). This is due to security feature - see https://developer.mozilla.org/en-US/docs/Web/Manifest#Deploying_a_manifest_with_the_link_tag.

To fix this problem change templates/layout.twig
from:
`<link rel="manifest" href="plugins/CoreHome/javascripts/manifest.json">`

to:
`<link rel="manifest" href="plugins/CoreHome/javascripts/manifest.json" crossorigin="use-credentials">`

**Comment by tsteur** [comment]
Thanks @john357smith created PR for Matomo 4
