### ISSUE TITLE
RedisCache warning not fixed in 3.13.1

### ISSUE THREAD

**Issue by leftmostlane** [matomo-org/matomo#15532]
In Matomo 3.13.1 the changelog states that this issue was fixed:

[23](https://github.com/matomo-org/component-cache/issues/23
) Update dependencies: Warning RedisCache.php(135): Deprecated – Function Redis::delete() is deprecated

However, the older version of: "Common/Cache/RedisCache.php" is included in the release which does not have the fix.  Specifically, in the Matomo 3.13.1 build, see the file: "Common/Cache/RedisCache.php" includes "$this->redis->delete" and not the corrected code: "$this->redis->del".  Perhaps an incorrect branch of "cache" was used to build Matomo 3.13.1?  

https://github.com/matomo-org/component-cache/issues/23

**Comment by tsteur** [comment]
Cheers, this wasn't fixed for the 1.X version of the cache component. Created a PR in https://github.com/matomo-org/component-cache/pull/27 and maybe we get this into 3.13.2 release which should be today.

**Comment by mattab** [comment]
Will be fixed in 3.13.2
