### ISSUE TITLE
Missing metrics for custom reports

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/matomo#15540]
Hi there,
When one want to create a custom report (premium feature) with the following metrics: "impression", "content interactions" and "interaction rate" and the following dimension "content name" the following metrics are missing:
- "content interactions"
- "interaction rate"
So to say using the content tracking with custom reports is not really helpful.

Could you please add those metrics?

Thank you,

**Comment by tsteur** [comment]
@Chardonneaur could you contact our support about this? (maybe you already did) That would be great. Email is shop at innocraft dot com.
