### ISSUE TITLE
comparison with previous year shows date in 2018, 2 years ago

### ISSUE THREAD

**Issue by ovidiucp** [matomo-org/matomo#15549]
I’m trying to compare All Visits with the same day a year ago. I click the date at the top of the main page, choose “day” as Period, click to select the “Compare” option, and choose “Previous year”. When I click Apply, the dates being shown are the day I chose, but the same day 2 years earlier.

This is clearly a bug.

When I choose a custom period and enter the day a year earlier, I get the expected result.

**Comment by tsteur** [comment]
Thanks for creating the issue and letting us know 👍

**Comment by sgiehl** [comment]
actually a duplicate of #15193
