### ISSUE TITLE
piwik_ignore cookie is blocked on macOS and Chrome 80

### ISSUE THREAD

**Issue by arno1979** [matomo-org/matomo#15553]
I just noticed that disabling the tracking on all of my Matomo installations is not working anymore when using the current version of the Chrome Browser (80.0.3987.87) in macOS.
I noticed the warning about a cookie with the setting `SameSite=None` and the missing `Secure` parameter. I read #14395, I added `_paq.push(["setSecureCookie", true])` to the JavaScript. That affects only the `_pk_id`, `_pk_ses` and `MATOMO_SESSID` cookies, the `piwik_ignore` cookie is seemingly not affected and gets blocked.
I then checked if this also happens when using the Chrome browser in Windows. It does not! Running Windows 10 and also the latest build disabling the tracking works just fine.

Can anyone confirm this and / or maybe has an idea for a solution?

Thanks
Arno

**Comment by tsteur** [comment]
@arno1979 Can reproduce this on MacOS and Chrome 80. Cheers for letting us know.

**Comment by sgiehl** [comment]
might be fixed with #15561

**Comment by tsteur** [comment]
fixed in https://github.com/matomo-org/matomo/pull/15561
