### ISSUE TITLE
Notice: Trying to access array offset on value of type null in core/Session/SessionAuth.php on line 63

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#15550]
Not sure if this is only related to WordPress... getting below output when running a CLI command. Started happening with 3.13.2. Maybe caused by https://github.com/matomo-org/matomo/pull/15472 ? Not sure... 

It's just a notice though. Things generally still seems to work.

> Notice: Trying to access array offset on value of type null in core/Session/SessionAuth.php on line 63

> Call Stack:
>     0.0010     397688   1. {main}() console:0
>     0.9315   47844424   2. Piwik\Console->run() console:32
>     0.9343   48033128   3. Piwik\Console->doRun() vendor/symfony/console/Symfony/Component/Console/Application.php:126
>     0.9343   48033128   4. Piwik\Console->doRunImpl() core/Console.php:93
>     1.0943   57948336   5. Piwik\Access::doAsSuperUser() core/Console.php:141
>     1.0954   57967824   6. Piwik\Console->Piwik\{closure:core/Console.php:139-141}() core/Access.php:644
>     1.0954   57968200   7. call_user_func:{core/Console.php:140}() core/Console.php:140
>     1.0954   57968200   8. Piwik\Console->doRun() core/Console.php:140
>     1.0955   57968472   9. Piwik\Console->doRunCommand() vendor/symfony/console/Symfony/Component/Console/> Application.php:195
>     1.0956   57968472  10. Piwik\Plugins\WordPress\Commands\GenerateCoreAssets->run() vendor/symfony/console/Symfony/> Component/Console/Application.php:874
>     1.0957   57970664  11. Piwik\Plugins\WordPress\Commands\GenerateCoreAssets->execute() vendor/symfony/console/> Symfony/Component/Console/Command/Command.php:257
>     1.2942   58002656  12. Piwik\FrontController->init() /Users/thomassteur/Development/wpsingle/wp-content/plugins/> matomo/plugins/WordPress/Commands/GenerateCoreAssets.php:57
>     1.3136   58568120  13. Piwik\FrontController->makeAuthenticator() core/FrontController.php:406
>     1.3139   58568120  14. Piwik\Session\SessionAuth->getLogin() core/FrontController.php:701

**Comment by tsteur** [comment]
Maybe on CLI it should not try to use the session auth? Or we just do a `!empty($this->user['login'])` check or so.

**Comment by diosmosis** [comment]
Makes sense not to use SessionAuth in CLI mode. 👍

**Comment by sgiehl** [comment]
@diosmosis guess that was fixed with #15591 ?

**Comment by diosmosis** [comment]
yes, will close this
