### ISSUE TITLE
Can I change site search character set?

### ISSUE THREAD

**Issue by J-Mishima** [matomo-org/matomo#15563]
Can I change the character set of the strings analyzed in site search?

The search page is made with Japanese EUC code.
If we tally it with Matomo, the characters will not be displayed correctly.

Is there a way to specify the character set?

**Comment by Findus23** [comment]
Starting with Matomo 4, we will use utf8mb4 by default which should allow you to store data from all of Unicode in Matomo.

https://github.com/matomo-org/matomo/issues/9785

If this does not solve your use case, please reopen the issue with more details on what you would like to change.
