### ISSUE TITLE
After upgrading to piwik 3.13.1 Tables Errors

### ISSUE THREAD

**Issue by msonnad** [matomo-org/matomo#15562]
Hi We are getting the 
Mysqli prepare error: Table 'piwik.piwik_locks' doesn't exist

Mysqli prepare error: Table 'piwik.piwik_brute_force_log' doesn't exist
errors .

Tried to update the  UPDATE piwik.piwik_option SET option_value = "3.13.1" WHERE option_name = "version_core"; 
This doesnt make any impact.
Very often we used to get 
![image](https://user-images.githubusercontent.com/34677240/74410261-b774d100-4e5e-11ea-94f2-5e50bf60bb18.png)

this error.

Thanks, Manjunath  S S

**Comment by toredash** [comment]
I suspect you have forgot to update your database tables.

Please run:
`./path/to/matomo/console core:update`

**Comment by msonnad** [comment]
@toredash Thanks for your reply.
Can u please help me where to run this command?

I tried running under deployment directory /apache2/htdocs/Piwik, and under PHP/ 
not able to execute the command.

**Comment by sgiehl** [comment]
You might have broke the update process by manually updating the version in the options table.
Maybe try setting the option back to the version you had before and rerun the update on console

**Comment by msonnad** [comment]
Hi @sgiehl ,
  Thanks its worked for me.
After updating the Piwik . We need to execute the core: update
