### ISSUE TITLE
JavaScript errors after new install and update

### ISSUE THREAD

**Issue by kslstn** [matomo-org/matomo#15565]
After a successful installation, the dashboard showed there were no visits in the database. After I verified that visit were added to the database in PHP MyAdmin, the message was no longer shown, but the dashboard wouldn't load.

The console repeatedly shows errors this error:

```
Error: "[$compile:tpload] http://errors.angularjs.org/1.6.5/$compile/tpload?p0=plugins%2FCoreHome%2Fangularjs%2Fnotification%2Fnotification.directive.html%3Fcb%3D18025633fd97c203076dd8672ce8d236&p1=403&p2=Forbidden"
    K https://www.example.com/matomo/index.php?module=Proxy&action=getCoreJs&cb=18025633fd97c203076dd8672ce8d236:126
    g https://www.example.com/matomo/index.php?module=Proxy&action=getCoreJs&cb=18025633fd97c203076dd8672ce8d236:280
    k https://www.example.com/matomo/index.php?module=Proxy&action=getCoreJs&cb=18025633fd97c203076dd8672ce8d236:255
    $digest https://www.example.com/matomo/index.php?module=Proxy&action=getCoreJs&cb=18025633fd97c203076dd8672ce8d236:266
    $apply https://www.example.com/matomo/index.php?module=Proxy&action=getCoreJs&cb=18025633fd97c203076dd8672ce8d236:269
    l https://www.example.com/matomo/index.php?module=Proxy&action=getCoreJs&cb=18025633fd97c203076dd8672ce8d236:221
    onload https://www.example.com/matomo/index.php?module=Proxy&action=getCoreJs&cb=18025633fd97c203076dd8672ce8d236:227
index.php:242:492
```
example.com shows my actual site's url.

Tested in current versions of Firefox and Chrome. Updating Matomo had no effect.

**Comment by Findus23** [comment]
Hi,

Can you check in the network tab of the browser console if some requests are failing?

As you installed Matomo in the subdirectory of your main site, the .htaccess rules of the main site will still apply and probably return 403 for some files Matomo needs.

Just for the future: For general troubleshooting and everything apart from reproducible bugs and extensive feature requests, please use the forum:
https://forum.matomo.org/

**Comment by kslstn** [comment]
Yeah you're right! Thanks for pointing that out and sorry for assuming it was a bug.
