### ISSUE TITLE
[Geo] Unknown region metrics increased significantly after update to v3.13.1

### ISSUE THREAD

**Issue by pardvm** [matomo-org/matomo#15589]
After changes in MaxMind licensing model and before upgrading to Matomo v3.13.1, I decided to become a register user of MaxMind in order to continue using their geo database. 

Then, after I finished to upgrade my Matomo instance to v3.13.1, taking into account [the recomendations from Matomo](https://matomo.org/faq/how-to/faq_163/), I decided to give a chance to the new provider db-ip.com.
The experience was very gratefull because the "Unkown city" metrics fell down drastically as shown in the following evolution graph:
(_the vertical line indicates the day of the upgrade to v3.13.1_)
![image](https://user-images.githubusercontent.com/25912392/74739010-4e270080-5258-11ea-950f-6a9dd3ec7839.png)

However, the drawback is that "Unknown region" has raised, also dramatically:
![image](https://user-images.githubusercontent.com/25912392/74739247-bd9cf000-5258-11ea-81aa-4b5b8161f1a6.png)

I was warned about that Geo-IP free databases aren't 100% accurated. However, given the huge difference between the two providers, I'm wondering if it could be a kind of v3.13 bug.
(I reviewed my installation several times but I'm not able to see any clue about the origin of this effect.)

Any help will be wellcome!

**Comment by tsteur** [comment]
I can confirm re city seeing same behaviour on commercial DB-IP. There is basically now known unknown.

We're also seeing a bit less Unknown regions though but we only made the change a couple weeks ago so maybe too early to tell.

On the free DB I can confirm same behaviour. Regions are basically all unknown. Which makes me think this is not an issue in Matomo but related to the free database not including regions possibly.

fyi @mattab

**Comment by pardvm** [comment]
@tsteur,
Let me check if I understand what you say:
Can you confirm that, using commercial DB-IP, the behaviour on regions is the same that the one I described using free DB-IP?

I would need to double-check this because I'm willing to pay an anual subscription to DB-IP but only if the regions are woriking fine.

Thanks for you support.

**Comment by tsteur** [comment]
So far I'm seeing quite a lot of regions using the commercial-DB, but on another Matomo using the free DB I get basically no region.

Ideally, if possible, ping me again in a week just so I can double confirm. This is the graph for the Unknown regions and we configured it like 1-2 weeks ago

![image](https://user-images.githubusercontent.com/273120/74775725-318fd480-52fb-11ea-9b90-5068019c04bc.png)

It went quite a bit down since then. Don't know if they have a refund policy but if they do would maybe give it a try for sure.

**Comment by sgiehl** [comment]
I have not yet checked that. But at least the free api of dbip does only
return a region name, but not a region iso code. But as we are only using
the iso code, the name alone is useless. Maybe it's the same for the db
files. Will have a look at their dbs tomorrow...

>

**Comment by sgiehl** [comment]
Guess my assumption was correct. According to their list the lite databases do not return ISO codes for regions. See https://db-ip.com/db/download/ip-to-city-lite compared to https://db-ip.com/db/ip-to-location

That actually means regions won't work with the lite database atm.
Might be possible to try to determine the iso code based on the name. Will have a look and create a PR if easily doable.

@mattab maybe we could ask db-ip if they would be willing to include the region iso code in their free db as well 🤔

**Comment by pardvm** [comment]
@sgiehl, @tsteur ,
In the mean time, I'm going to purchase a subscription to db-ip

Thank you very much for your support!

**Comment by pardvm** [comment]
FYI: After manually installing the paid version of db-ip database, regions seem to start working again.
Also, just for reference: in order to it to work, I have had to rename ``dbip-location-2020-02.mmdb`` (the file dbip provides once you fulfill payment) to ``DBIP-City.mmdb`` (the file Matomo expects) 

Moreover, it seems that autoupdater will not work with this paid version: DB-IP provides a specific URL where you can get a JSON that describes the details of the latest available geodb. Among these details is the particular URL to get the database.
Have Matomo team any plans to provide an autoupdater for the paid version of DB-IP database? (It would be nice)

**Comment by sgiehl** [comment]
> Have Matomo team any plans to provide an autoupdater for the paid version of DB-IP database?

see https://github.com/matomo-org/matomo/issues/15580

**Comment by pardvm** [comment]
👍

**Comment by pardvm** [comment]
**WARNING** - **WARNING** - **WARNING**
After paying the subscription to [db-ip geolocation database](https://db-ip.com/db/ip-to-location) which seemed to work better for Regions than the free one, I noticed that *it was not accurate* at all for cities, at least, my country (Spain)

It uses as city location the one for the ASN owner of the IP and, then, almost all hits are located at a few cities (the ones where ASN headquarters are located)

Lamentably, [db-ip refund policy](https://db-ip.com/tos.php) doesn't apply because I've already downloaded the database, which is normal. 
However... How could have I tested the database without having download it previously?

I would like this comment could help some other people to avoid wasting 250$ for something useless.

P.S.- Obviously, I'm back to my old and well-known ``GeoLite2-City.mmdb`` which is working as a charm (as it used to do.)

**Comment by sgiehl** [comment]
Seems that's correct. For my IP the location of maxmind is also far more accurate than the one of db-ip 🤔

**Comment by pardvm** [comment]
Sure: My observations shown something like if, suddenly, almost all visitor in a (not too small) country migrated to a few big cities!!!

**Comment by tsteur** [comment]
fyi @mattab

**Comment by mattab** [comment]
Tricky to know what to do. For now maybe we don't do anything and just leave this opened until we come to a decision or suggestions on what to do later.

**Comment by pardvm** [comment]
@mattab ,
Tricky indeed... I agree with your decision. However I would suggest to remove the recommendation in favor of db-ip's databases as someone naive (like me) could end up buying a useless 250$ subscription. it is not so much but... it hurts a little bit :)

**Comment by diosmosis** [comment]
@mattab I guess this depends more on the particular's of maxmind's license, if we recommend maxmind then we have to be explicit about what information users have to give to maxmind and what upkeep they have to do to (eg, what happens when maxmind removes an IP from the database, is simply updating every week enough?), etc.

**Comment by sgiehl** [comment]
@mattab @tsteur any plans how to proceed with the dbip region and city issue? 

With #15592 at least the region detection should be improved for free databases, even if it might not work in all cases. Note: This can't be completely fixed unless DBIP includes the region iso code in their free databases.

The inaccurate city detection still remains. Check my current IP on db-ip now a few days. The reported location switched around, but was always very inaccurate, while the one from Maxmind was a lot better...

**Comment by tsteur** [comment]
@sgiehl the goal was to offer both in the geolocation admin. DBIP and MaxMind. We can mention MaxMind reports more accurate city/region, but it requires the to obtain a license key which they can get by signing up. We could link to some FAQ. 

I think it's mostly about doing some explaining in the UI, might not need too much explaining but a little bit and explain the rest in the FAQ. 

The difficult part for users once they have a license key is to generate the URL from this license key and getting this right. In Matomo for WordPress I basically only ask users to enter a MaxMind license key and generate the URL server side but there it's all a bit more minimalistic and I don't let users choose which kind of DB. So would just need to make sure to explain how to generate the URL they want once they have the license key.

**Comment by mattab** [comment]
> I think it's mostly about doing some explaining in the UI

:+1: exactly, making the UI clear and transparent with pros/cons of each, would be the best outcome.
