### ISSUE TITLE
Email reports: Branding image is not getting displayed in the email reports

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#15613]
Issue: Branding image is not getting displayed in the email reports in Cloud

This issue can be replicated and a customer raised this issue as well.

Customers message: " In all of my emailed reports, our logo does not show up. It's a standard jpg file, and it show in the matomo header on my dashboard."

![image](https://user-images.githubusercontent.com/26726594/75122201-2cb69080-5700-11ea-9368-dff0973fdca2.png)

**Comment by tsteur** [comment]
@KarthikRaja1388 closing this as we have an issue for this internally already.
