### ISSUE TITLE
Mention require PHP 7.2 in admin notification

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#15623]
I think we haven't yet enabled this admin notification. The code should be already there but likely disabled. Basically, the goal is, if someone is using PHP 7.1 or older that they should upgrade to PHP 7.2 at least or better even directly PHP 7.4.

**Comment by Findus23** [comment]
Weird that this didn't get closed.

**Comment by sgiehl** [comment]
@Findus23 all issues merged into 3.x-dev aren't closed automatically as they are not in the "default" branch (which is currently 4.x-dev)
