### ISSUE TITLE
Specific countries appear in visit log but return no results when segmented

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#15620]
See eg https://demo.matomo.org/index.php?module=API&method=API.getSuggestedValuesForSegment&segmentName=countryName&idSite=62&format=JSON&token_auth=anonymous

We return the first 100 countries alphabetically instead of ideally checking which countries are actually visited sorted by the number of visits desc rather than alpabetically

**Comment by sgiehl** [comment]
Don't we have that case in multiple places? Everywhere where we have a fixed list of possible values. Like browser or os

**Comment by tsteur** [comment]
yes 👍 as part of this should probably also look at some other cases that maybe return more than 100 results and are `static`

**Comment by tsteur** [comment]
Let's change it for browsers, OS and countries for now and make the change later for others when they come up. We can also change any other obvious ones meaning we don't need to search for it and know that it needs to be changed there too.

This should be easily fixed by calling eg `$segment->setSuggestedValuesApi('UserCountry.get...');` on the segment instead of configuring a hard coded list. It might be a problem though if short codes are needed instead of names.

**Comment by Starker3** [comment]
Do we have any ETA for this issue? It looks like it was added to the 4.3.0 milestone. We've had some users contact us regarding this issue.

**Comment by tsteur** [comment]
It's in the 4.7.0 milestone. Possibly beginning next year I would say.
