### ISSUE TITLE
Using Opt-Out iFrame twice doesn't work

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#15629]
Reported in https://forum.matomo.org/t/fehler-im-optout/36246 and reproduced on demo.matomo.org

Steps to reproduce:
- open https://demo.matomo.org/index.php?module=CoreAdminHome&action=optOut&language=de
- opt out
- don't reload the page and opt-in again
- reload the page
Expected: Tracking is enabled again
Result: Tracking is still disabled

This also works the other way around (having opt-out, enabling and then re-disabling tracking and it won't opt-out correctly)

**Comment by tsteur** [comment]
@Findus23 this works for me

**Comment by Findus23** [comment]
Very weird. I can reproduce this in a clean firefox and chromium profile. 
![testcase](https://user-images.githubusercontent.com/6266037/75482971-1af61700-59a6-11ea-88a7-bebcb256ee61.gif)

**Comment by tsteur** [comment]
> don't reload the page and opt-in again

Missed that part. That probably never worked @Findus23 ?
That's because Matomo can't receive the cookie right away unless it did reload the frame. Could you test this with an older version if easily doable? I quite doubt this worked.

**Comment by Findus23** [comment]
> That probably never worked @Findus23 ?

Good question. With Matomo 3.6.1 it works (but there is a weird delay after clicking):
![test](https://user-images.githubusercontent.com/6266037/75561281-074ebd00-5a47-11ea-889e-c25b9ce7e0fb.gif)
 
(I'm always testing in a fresh Firefox profile to make sure no old cookies survive)
- exact same in 3.8.1
- same in 3.10.0
- same in 3.11.0
- same in 3.12.0
- same in 3.13.0
- and starting with 3.13.1 I see the issue described above and I start seeing a warning because I just quickly created a HTTP site
> The tracking opt-out feature may not work because this site was not loaded over HTTPS. Please reload the page to check if your opt out status changed.

As this was added in https://github.com/matomo-org/matomo/pull/15184, I am going to guess this PR also caused the regression.

**Comment by sgiehl** [comment]
I would assume the problem is a result of #14400 in combination with #15184. As there is a CSRF nonce that is evaluated only the first request can be valid 🤷‍♂ 
I'm not very deep in that topic, so not sure why it uses a new window to set the cookie. But if that is required, guess the easiest solution would be to reload the opt-out frame once the window closes

**Comment by Findus23** [comment]
> I'm not very deep in that topic, so not sure why it uses a new window to set the cookie.
I think it is because of #3135 and #8578
