### ISSUE TITLE
Ecommerce Orders Conversion Rate Rounding Error

### ISSUE THREAD

**Issue by beamylake** [matomo-org/matomo#15637]
Hello,
we've encountered an rounding error (again) when displaying the ecommerce overview in german

Here's the english version, where everything is looking as expected:

![eng](https://user-images.githubusercontent.com/45793233/75553270-5c370700-5a38-11ea-9fb3-f62a6c4f99ab.JPG)

And here is the german version, where the Ecommerce Orders Conversion Rate gets rounded down to 0%:

![deu](https://user-images.githubusercontent.com/45793233/75553267-5b05da00-5a38-11ea-89ff-77daa395db97.JPG)

It feels like this problem might be a "leftover" of https://github.com/matomo-org/matomo/issues/15200

We are using Matomo 3.13.3 and the rest of our setup is still as described in https://github.com/matomo-org/matomo/issues/15240

Please let me know if you need any further information and thanks in advance for your efforts!

**Comment by tsteur** [comment]
Thanks @beamylake we'll have a look to see if we can reproduce this.

**Comment by pebosi** [comment]
I have the same problem on my current install:
in NumberFormater.php the method formatNumberWithPattern calls "replaceSymbols"
The php strtr function has a strange behaviour here. When i return the value before the call i get a correct result.
Can't reproduce on local machine, so maybe a specific php / server conf problem.

**Comment by sgiehl** [comment]
> The php strtr function has a strange behaviour here. When i return the value before the call i get a correct result.
I would more likely assume the number formatting is done twice maybe. And after the number is converted to a german format it gets truncated when it's formatted again.

@pebosi could you try switching the language to english and check if the same problem exists?

**Comment by pebosi** [comment]
Would be nice to have the whole NumberFormat stuff based on Intl Component / Extension, with upgrade to Twig 3 #15573

**Comment by pebosi** [comment]
See the screenshots
![conversion-rate-en](https://user-images.githubusercontent.com/445179/75961723-6cc50280-5eba-11ea-9bef-842f5f50a946.png)
![conversion-rate-german](https://user-images.githubusercontent.com/445179/75961724-6d5d9900-5eba-11ea-914f-3b4e831b1e17.png)

**Comment by pebosi** [comment]
And now when returning the value above this line
`
$value = $this->replaceSymbols($value);
`

Eng:
![conversion-rate-en-2](https://user-images.githubusercontent.com/445179/75961957-d80ed480-5eba-11ea-989a-9a6d25785f0b.png)

Deu:
![conversion-rate-german-2](https://user-images.githubusercontent.com/445179/75961962-d9d89800-5eba-11ea-9773-0abdae2707c1.png)

**Comment by pebosi** [comment]
Matomo version: 3.13.3
MySQL version: 10.0.38-MariaDB-0ubuntu0.16.04.1
PHP version: 7.3.15-3+ubuntu16.04.1+deb.sury.org+1

**Comment by pebosi** [comment]
The second screenshots show the correct value (maybe its better to have 2 digits like in the graph tooltip). But the dot is not replaced with a comma in german...

**Comment by sgiehl** [comment]
you try applying that linked PR. that should fix the issue

**Comment by pebosi** [comment]
Works!

**Comment by beamylake** [comment]
We can confirm, it's working for us too!
Thnx!
