### ISSUE TITLE
login page displaying double form

### ISSUE THREAD

**Issue by ghost** [matomo-org/matomo#15645]
am I seeing double? or is the "Sign in" page displaying two times? This happens after I log out of matomo.

**Comment by tsteur** [comment]
Can't reproduce this @broros Make sure you have all ad blockers etc disabled if there is anything active maybe. 

Can you reproduce this also in other browsers? If so, could you maybe create a login for us and send us the details to hello at matomo dot org so we can see what is happening there?

**Comment by mattab** [comment]
we've seen before when using LoginLdap plugin. Can you upgrade Matomo and LoginLdap plugin if you use it, and try again?
