### ISSUE TITLE
Matomo 3.13.3 Can't Log Using iOS 13 Safari or Chrome [bug]

### ISSUE THREAD

**Issue by ButisitArt** [matomo-org/matomo#15659]
I can not log into my Matomo stats page using Safari or Chrome on my iPhone. This never use to be a problem with previous versions. I could always see my stats using an iPhone browser.

Now what happens is:

1. The first time I log in, I'm taken directly back to the login page.
2. When I try to log in the second time I get this error:
**Error: Form security failed. Please reload the form and check that your cookies are enabled. If you use a proxy server, you must configure Matomo to accept the proxy header that forwards the Host header. Also, check that your Referrer header is sent correctly**

This all started happening with the Matomo 3.13.3 update.

Any ideas?

**Comment by sgiehl** [comment]
Could you maybe try to apply that patch on your Matomo and test if it works afterwards?
https://github.com/matomo-org/matomo/pull/15633/files#diff-d1904580a82516edb7ede7a2d4ca3a37R225

**Comment by ButisitArt** [comment]
Thanks ... will try it out & report back.

**Comment by ButisitArt** [comment]
I'm happy to report the fix worked. Wanted to test it over a couple of days. It's works on my Mac & I can now log in via my iPhone to. 👍
