### ISSUE TITLE
Geo does not work anymore since Matomo 3.13

### ISSUE THREAD

**Issue by Laul0** [matomo-org/matomo#15653]
## Summary

On the Self-Hosted environment, the plugin GeoIP 2 was installed to have more detail about the location of the visitors.

## Expected behavior

Update Matomo to the latest version and keep GeoIP 2.

## Current behavior

After upgrade Matomo to the latest version, GeoIP 2 does not detect the location anymore:
![Screen Shot 2020-03-03 at 10 17 57](https://user-images.githubusercontent.com/15279205/75790681-8985fc80-5d39-11ea-84f1-80801c554dfa.png)

- Using mmdb (no ISP)
- The update db was done yesterday
- It is the latest version of mmdb (2020-03)

And the real time map is empty:

![Screen Shot 2020-03-03 at 10 29 02](https://user-images.githubusercontent.com/15279205/75790914-d669d300-5d39-11ea-910c-d46f6ecb1e1b.png)

## Additional information

**Environment**: Self-Hosted (Docker)
**Matomo version**: 3.13.3

**Comment by sgiehl** [comment]
@Laul0  which database are you using DBIP or Maxmind? And are you using any proxy or similar?

**Comment by Laul0** [comment]
Hi @sgiehl,

- DBIP database

I have proxies but nothing changed and that worked perfectly before the update.
- Local reverse proxy
- Cloudflare proxy

**Comment by sgiehl** [comment]
So you have configured Matomo for usage behind a proxy, so the IP is set correctly, as described here: https://matomo.org/faq/how-to-install/faq_98/

**Comment by Laul0** [comment]
You save my day 👍🏻💪🏻

I already configured it but the file seems overwrote after the upgrade (certainly my bad)

Thx @sgiehl
