### ISSUE TITLE
Readonly database user not working

### ISSUE THREAD

**Issue by kaerer** [matomo-org/matomo#15697]
Hi, we are using matomo version 3.12.0.
We have recently divide our database into master-slave type clusters.

When we defined `database_reader` configurations with slave information as below, we got `SQLSTATE[HY000]: General error: 1290 The MariaDB server is running with the --read-only option so it cannot execute this statement` error message.

[database]
…
[database_reader]
…

To make things work we define master for both of it. 
We can not deactivate readonly option from slave, it wont sync the information with master.

Is there any extra configurations or misconfiguration ?

**Comment by tsteur** [comment]
I can only suppose it fails to create temporary tables on the reader. Not sure how your particular MariaDB version handles this. Maybe there is a setting or maybe it needs upgrading to a different version or so.

For now I would recommend you upgrade to the latest Matomo version and see if it works there maybe. This is recommended anyway to be compatible with recent browser changes in case you are using JavaScript tracking.

**Comment by d2x** [comment]
I, too, experience issues with the latest version of Matomo (3.14.1 as of this report) and the database_reader after following [this official guide](https://matomo.org/faq/how-to-install/faq_35746/) but with my real connection info, of course.

The `Visits Over Time` dashboard element returns a connection error like `SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'analytics_ro'@'%' to database 'analytics_db'`.

In my specific instance, I'm using an Aurora RDS cluster. I can connect successfully with the database_reader defined connection info from the MySQL CLI on the same machine hosting Matomo but Matomo apparently can't figure out how to connect with those defined details.

Removing the [database_reader] section and simply using the RW user and RW cluster endpoint works fine. Any troubleshooting recommendations would be great to try and see why this connection info isn't working.

It's probably worth noting I am using:
Ubuntu 20.04 LTS
Package: mysql-client
Version: 8.0.21-0ubuntu0.20.04.4

I've also had to use `--ssl-mode=DISABLED` with the CLI to prevent getting `ERROR 2026 (HY000): SSL connection error: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol` while testing the connections. I imagine this is handled better by the php-mysql package (Package: php-mysql Version: 2:7.4+75).

**Comment by sgiehl** [comment]
Closing as there hadn't been any further activity or similar reports in the last months. If a similar problem still exists, please feel free to create a new issue.
