### ISSUE TITLE
Uncaught exception: Error: Class 'Piwik\Plugins\ExamplePlugin\ExamplePlugin' not found in plugins/CoreConsole/Commands/GeneratePlugin.php:45

### ISSUE THREAD

**Issue by dansleboby** [matomo-org/matomo#15699]
Hi
I got the error in the title when I try

 ./console generate:plugin --name="MyPlugin"

**Comment by lockland** [comment]
I'm with the same problem. What can I do to solve that??

**Comment by dansleboby** [comment]
You need to install it from git and switch branch:
https://developer.matomo.org/guides/getting-started-part-1#get-install-matomo
