### ISSUE TITLE
year is incorrectly counted in GDPR Overview

### ISSUE THREAD

**Issue by flatrick** [matomo-org/matomo#15709]
Hi, when I set Matomo to regularly delete old raw data to 365 days (a full year) the GDPR overview reports that the information will be stored for a year + 5 days. 
If I set 730 days (2 years) the GDPR-overview reports 24 months and 10 days.

**Comment by tsteur** [comment]
That's because it does basically 365/30 = 12 months + 5 remaining days. I suppose dividing it by 30.4 would make it a bit more accurate. And / or could also add simple checks for 365, 366 and 730.
