### ISSUE TITLE
Tagmanager => manage containers => empty

### ISSUE THREAD

**Issue by ErikDohmen** [matomo-org/matomo#15717]
I've searched the issues here in the repository and cleared the cache, checked for mod_pagespeed, but no luck. The manage containers stays empty.

Any more suggestions. I'm running matomo 3.13.3
I can see that a new container is created when I added a new site, but can't get to it. Even when I go to the statistics of the site and then click the tagmanager, I do get a default container list of actions, but none of them show anything

**Comment by tsteur** [comment]
@ErikDohmen by any chance do you know how to open browser developer tools and check if there is any message in the console?

**Comment by ErikDohmen** [comment]
@tsteur as I'm an internet developer myself, yes I do know and sadly enough no errors in the console. Checked that right away when investigating the issue.

**Comment by tsteur** [comment]
@ErikDohmen could you maybe also check the network tab if there are any failing requests?

Just to confirm: You click on Tag Manager -> containers, and an empty page appears?

**Comment by ErikDohmen** [comment]
@tsteur sadly enough no not either...
That was yesterday. Now that I tried it once more, all of a sudden the 'manage containers' screen does show up with data. Could this be as there is a nightly cleanup or something?

**Comment by tsteur** [comment]
Glad it works now @ErikDohmen 

There isn't really any nightly cleanup or so. Wouldn't be able to explain what happened there as we haven't seen anything like it before. Feel free to let us know if that happens again and I'll close the issue for now.

Cheers

**Comment by ErikDohmen** [comment]
It's got to do with sessions, cause what I did and wasn't focused on, is that it occurred on my chrome session and when I told you it was working again I tried it with a different browser. While on chrome it's still not working, but if I try it in a incognito window in chrome, all of a sudden it works.
No clue, but just to give you some additional info for future reference

**Comment by tsteur** [comment]
I suppose it is not some browser caching issue?

**Comment by ErikDohmen** [comment]
Nope, even though I don't know what it could be. But browser caching is not the fact as when I've got the console open, I always have the browser caching off

**Comment by tsteur** [comment]
Could you maybe try the new 3.13.4 release? We made some changes there around cookies maybe there is some session issue for a specific browser causing some issue.
