### ISSUE TITLE
Matomo Alternative Visualization Report

### ISSUE THREAD

**Issue by shahmeeee** [matomo-org/matomo#15718]
Hi Guys . 

I'm using matomo. but I want some cloud-based tools to visualize data. 
I have checked these tools tableau,chartio,flexmonster but quit expensive. 

Suggestion, please!

**Comment by tsteur** [comment]
@shahmeeee I'm not quite sure what you are after? Are you looking for some cheaper alternatives to these? If so, could you please ask this in our forum https://forum.matomo.org/ as we only manage bug reports and feature requests here? That be great. Thanks a lot for your understanding.
