### ISSUE TITLE
Codespell report for "Matomo" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [matomo-org/matomo#15729]
The FOSS server [fossies.org](https://fossies.org) - also supporting "Matomo" - offers a feature "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have just created for testing purposes such a codespell based analysis for the new Matomo release 3.13.4:

&nbsp;&nbsp;https://fossies.org/linux/www/matomo-3.13.4.tar.gz/codespell.html

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can force a new improved check if applicable.

Just for information there are also two supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/www/matomo-3.13.4.tar.gz/codespell_conf.html) and all obvious [False Positives](https://fossies.org/linux/www/matomo-3.13.4.tar.gz/codespell_fps.html).

If appropriate, additional reports for the current release or also master versions (these in a special "test" folder) could be willingly created.

OT: As Fossies admin I am somewhat annoyed that a single file ("How to install Matomo.html") is located outside of the main subdirectory "matomo", as Linux user that the filename contains spaces and as a general user that the file seems superfluous since already existing within the directory "matomo/misc".

**Comment by jschleus** [comment]
Since I saw the great efforts regarding spelling corrections I just added the "matomo" GitHub branches "master", "3.x-dev" and "4.x-dev" to a special Fossies folder named "/linux/test" that isn't integrated into the Fossies services and should also not be accessible for search engines.

The sources are at least currently cloned half-hourly and the according Fossies codespell reports are visible under

 https://fossies.org/linux/test/matomo-3.x-dev-snap.tar.gz/codespell.html
 (currently -> https://fossies.org/linux/test/matomo-3.x-dev.fdb685c.200408.tar.gz/codespell.html)

 https://fossies.org/linux/test/matomo-4.x-dev-snap.tar.gz/codespell.html
 (currently -> https://fossies.org/linux/test/matomo-4.x-dev.2c5c72e.200408.tar.gz/codespell.html)

 https://fossies.org/linux/test/matomo-master.tar.gz/codespell.html
 (currently -> https://fossies.org/linux/test/matomo-master.62121d3.200325.tar.gz/codespell.html)

And with a little bit of luck (since it's a new and not yet well tested feature) one can see future changes regarding code spellings under the new "history" button that links for e.g. to

 https://fossies.org/linux/test/matomo-4.x-dev-snap.tar.gz/codespell_hist.html

Maybe this can be a little bit helpful as a supplement (although the correction of spelling errors has probably a low priority).

**Comment by mattab** [comment]
Hello @jschleus 
Thanks for this :+1: 
Btw, when you create any PR or issues, would you be able to add the label `not-in-changelog`? 
This would save us some time and hide the PRs/issues from our changelog generator tool. Thanks!
