### ISSUE TITLE
Archiving specific date via console won't take date as argument.

### ISSUE THREAD

**Issue by JozefBabala** [matomo-org/matomo#15727]
When trying to archive data manually via CLI for specific date:

> ./console core:archive --force-date-range=2020-03-24,2020-03-24
or
> ./console core:archive --force-date-range="2020-03-24,2020-03-24"

we are experiencing following error: 

> Error: Got invalid response from API request: ?module=API&method=API.get&idSite=1&period=week&date=&format=php&trigger=archivephp. Response was 'a:2:{s:6:"result";s:5:"error";s:7:"message";s:3044:"Please specify a value for 'date'.

Seems like date parameter is not passed correctly to API call. This issue was introduced with Matomo version 3.13.4. It works correctly on version 3.13.3

**Comment by sgiehl** [comment]
Thanks for the report. I'm able to reproduce that.

**Comment by diosmosis** [comment]
Fixed by #15728
