### ISSUE TITLE
Fix automatic login after one click update

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#15725]
Our UI tests for automatic login after a one click update currently fails on 4.x-dev
That might be a regression and should be fixed.

**Comment by sgiehl** [comment]
guess that will be fixed with #15770

**Comment by diosmosis** [comment]
Actually should be fixed by https://github.com/matomo-org/matomo/pull/15755, I think it's due to the app specific token auth change, the user's token auth is no longer valid so a login is required. Not sure if it will happen after 4.x is released...
