### ISSUE TITLE
Activate ExtraTools failing on latest version of matomo 3.13.4 with Error: Class 'Piwik\Plugin\Manager' not found 

### ISSUE THREAD

**Issue by r621549** [matomo-org/matomo#15738]
when trying to execute the command
 ./console plugin:activate ExtraTools
Error : 
:  Uncaught Error: Class 'Piwik\Plugin\Manager' not found in /var/www/html/analytics/core/bootstrap.php:46
Stack trace:
#0 /var/www/html/analytics/index.php(21): require_once()
 #1 {main}

**Comment by tsteur** [comment]
@r621549 it sounds like some file was not copied correctly for some reason. Could you perform the manual update described in https://matomo.org/docs/update/#the-manual-three-step-update and see if that fixes it?

**Comment by r621549** [comment]
> @r621549 it sounds like some file was not copied correctly for some reason. Could you perform the manual update described in https://matomo.org/docs/update/#the-manual-three-step-update and see if that fixes it?

Thanks you so much for reponding , but still same issue :

bash-5.0# wget https://builds.matomo.org/matomo.zip
--2020-03-27 20:07:29--  https://builds.matomo.org/matomo.zip
Resolving builds.matomo.org... 185.31.40.177, 2a00:b6e0:1:200:177::1
Connecting to builds.matomo.org|185.31.40.177|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19375918 (18M) [application/zip]
Saving to: 'matomo.zip'

matomo.zip                            100%[=========================================================================>]  18.48M  3.63MB/s    in 7.8s    

2020-03-27 20:07:38 (2.36 MB/s) - 'matomo.zip' saved [19375918/19375918]

bash-5.0# unzip -o matomo.zip

bash-5.0# ls 
How to install Matomo.html  matomo                      matomo.zip
bash-5.0# rm matomo.zip
bash-5.0# ls 
How to install Matomo.html  matomo
bash-5.0# unzip ../ExtraTools.zip matomo/plugins/
Archive:  ../ExtraTools.zip
bash-5.0# cd matomo/
bash-5.0# composer require symfony/yaml:~2.6.0
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 1 removal
  - Removing leafo/lessphp (dev-php74-compat)
  - Installing symfony/yaml (v2.6.13): Loading from cache
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package piwik/cache is abandoned, you should avoid using it. Use matomo/cache instead.
Package piwik/decompress is abandoned, you should avoid using it. Use matomo/decompress instead.
Package piwik/ini is abandoned, you should avoid using it. Use matomo/ini instead.
Package piwik/network is abandoned, you should avoid using it. Use matomo/network instead.
Package piwik/piwik-php-tracker is abandoned, you should avoid using it. Use matomo/matomo-php-tracker instead.
Writing lock file
Generating autoload files
bash-5.0# composer require symfony/process:^3.4
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/process (v3.4.38): Loading from cache
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package piwik/cache is abandoned, you should avoid using it. Use matomo/cache instead.
Package piwik/decompress is abandoned, you should avoid using it. Use matomo/decompress instead.
Package piwik/ini is abandoned, you should avoid using it. Use matomo/ini instead.
Package piwik/network is abandoned, you should avoid using it. Use matomo/network instead.
Package piwik/piwik-php-tracker is abandoned, you should avoid using it. Use matomo/matomo-php-tracker instead.
Writing lock file
Generating autoload files
bash-5.0# ./console plugin:activate ExtraTools
[27-Mar-2020 20:15:57 UTC] PHP Fatal error:  Uncaught Error: Class 'Piwik\Plugin\Manager' not found in /var/www/html/install/install_matomo/matomo/core/bootstrap.php:46
Stack trace:
#0 /var/www/html/install/install_matomo/matomo/console(18): require_once()
#1 {main}
  thrown in /var/www/html/install/install_matomo/matomo/core/bootstrap.php on line 46

Fatal error: Uncaught Error: Class 'Piwik\Plugin\Manager' not found in /var/www/html/install/install_matomo/matomo/core/bootstrap.php:46
Stack trace:
#0 /var/www/html/install/install_matomo/matomo/console(18): require_once()
#1 {main}
  thrown in /var/www/html/install/install_matomo/matomo/core/bootstrap.php on line 46

**Comment by r621549** [comment]
@tsteur I did diff on older version (3.11.0) and newer version (3.13.4) matomo installation package and found missing files 


Only in analytics: bower.json
Only in analytics: composer.json
Only in analytics: composer.lock
Only in analytics/core: DeviceDetectorCache.php
Only in analytics/js: piwik-min.js
Only in analytics/js: piwik.js.orig
Only in analytics/libs/Zend: Config
Only in analytics/libs/bower_components/angular: angular.js
Only in analytics/libs/bower_components/angular: angular.min.js.gzip
Only in analytics/libs/bower_components/angular: angular.min.js.map
Only in analytics/libs/bower_components/angular: bower.json
Only in analytics/libs/bower_components/angular: package.json
Only in analytics/libs/bower_components/angular-animate: angular-animate.js
Only in analytics/libs/bower_components/angular-animate: angular-animate.min.js.map
Only in analytics/libs/bower_components/angular-animate: bower.json
Only in analytics/libs/bower_components/angular-animate: package.json
Only in analytics/libs/bower_components/angular-cookies: angular-cookies.js
Only in analytics/libs/bower_components/angular-cookies: angular-cookies.min.js.map
Only in analytics/libs/bower_components/angular-cookies: bower.json
Only in analytics/libs/bower_components/angular-cookies: package.json
Only in analytics/libs/bower_components/angular-mocks: bower.json
Only in analytics/libs/bower_components/angular-mocks: package.json
Only in analytics/libs/bower_components/angular-sanitize: angular-sanitize.js
Only in analytics/libs/bower_components/angular-sanitize: angular-sanitize.min.js.map
Only in analytics/libs/bower_components/angular-sanitize: bower.json
Only in analytics/libs/bower_components/angular-sanitize: package.json
Only in analytics/libs/bower_components/chroma-js: bower.json
Only in analytics/libs/bower_components/chroma-js: package.json
Only in analytics/libs/bower_components: html5shiv
Only in analytics/libs/bower_components/iframe-resizer: bower.json
Only in analytics/libs/bower_components/iframe-resizer/js: ie8.polyfils.map
Only in analytics/libs/bower_components/iframe-resizer/js: iframeResizer.contentWindow.js
Only in analytics/libs/bower_components/iframe-resizer/js: iframeResizer.contentWindow.map
Only in analytics/libs/bower_components/iframe-resizer/js: iframeResizer.js
Only in analytics/libs/bower_components/iframe-resizer/js: iframeResizer.map
Only in analytics/libs/bower_components/iframe-resizer: karma.conf.js
Only in analytics/libs/bower_components/iframe-resizer/src: ie8.polyfils.js
Only in analytics/libs/bower_components/iframe-resizer/src: iframeResizer.contentWindow.js
Only in analytics/libs/bower_components/iframe-resizer/src: iframeResizer.js
Only in analytics/libs/bower_components/iframe-resizer: test-main.js
Only in analytics/libs/bower_components/jQuery.dotdotdot: bower.json
Only in analytics/libs/bower_components/jScrollPane: bower.json
Only in analytics/libs/bower_components/jScrollPane/build: Gruntfile.js
Only in analytics/libs/bower_components/jScrollPane/build: package.json
Only in analytics/libs/bower_components/jScrollPane/image: logo.png
Only in analytics/libs/bower_components/jScrollPane/script: demo.js
Only in analytics/libs/bower_components/jScrollPane/script: jquery.jscrollpane.js
Only in analytics/libs/bower_components/jScrollPane/style: demo.css
Only in analytics/libs/bower_components/jquery: bower.json
Only in analytics/libs/bower_components/jquery/dist: jquery.js
Only in analytics/libs/bower_components/jquery/dist: jquery.min.map
Only in analytics/libs/bower_components/jquery/dist: jquery.slim.js
Only in analytics/libs/bower_components/jquery/dist: jquery.slim.min.js
Only in analytics/libs/bower_components/jquery/dist: jquery.slim.min.map
Only in analytics/libs/bower_components/jquery/sizzle/dist: sizzle.js
Only in analytics/libs/bower_components/jquery/sizzle/dist: sizzle.min.map
Only in analytics/libs/bower_components/jquery-mousewheel: bower.json
Only in analytics/libs/bower_components/jquery-mousewheel: jquery.mousewheel.js
Only in analytics/libs/bower_components/jquery-placeholder: bower.json
Only in analytics/libs/bower_components/jquery-ui: bower.json
Only in analytics/libs/bower_components/jquery-ui: component.json
Only in analytics/libs/bower_components/jquery-ui: composer.json
Only in analytics/libs/bower_components/jquery-ui: package.json
Only in analytics/libs/bower_components/jquery-ui/ui: i18n
Only in analytics/libs/bower_components/jquery-ui/ui/minified: i18n
Only in analytics/libs/bower_components/jquery.scrollTo: bower.json
Only in analytics/libs/bower_components/jquery.scrollTo: jquery.scrollTo.js
Only in analytics/libs/bower_components/jquery.scrollTo: package.json
Only in analytics/libs/bower_components/jquery.scrollTo: scrollTo.jquery.json
Only in analytics/libs/bower_components/materialize/bin: materialize.css
Only in analytics/libs/bower_components/materialize/bin: materialize.js
Only in analytics/libs/bower_components/materialize: bower.json
Only in analytics/libs/bower_components/materialize/dist/css: materialize.css
Only in analytics/libs/bower_components/materialize/dist/js: materialize.js
Only in analytics/libs/bower_components/materialize/extras/noUiSlider: nouislider.js
Only in analytics/libs/bower_components/materialize: package.js
Only in analytics/libs/bower_components/mousetrap: Gruntfile.js
Only in analytics/libs/bower_components/mousetrap: mousetrap.js
Only in analytics/libs/bower_components/mousetrap: package.json
Only in analytics/libs/bower_components/mousetrap: plugins
Only in analytics/libs/bower_components/ngDialog: bower.json
Only in analytics/libs/bower_components/ngDialog/css: ngDialog-theme-plain.css
Only in analytics/libs/bower_components/ngDialog/css: ngDialog.css
Only in analytics/libs/bower_components/ngDialog/js: ngDialog.js
Only in analytics/libs/bower_components/ngDialog: karma.conf.js
Only in analytics/libs/bower_components/ngDialog: package.json
Only in analytics/libs/bower_components/ngDialog: protractor.conf.js
Only in analytics/libs/bower_components/ngDialog: yarn.lock
Only in analytics/libs/bower_components/qrcode.js: bower.json
Only in analytics/libs/bower_components/sprintf: bower.json
Only in analytics/libs/bower_components/sprintf/dist: angular-sprintf.min.js.map
Only in analytics/libs/bower_components/sprintf/dist: angular-sprintf.min.map
Only in analytics/libs/bower_components/sprintf/dist: sprintf.min.js.map
Only in analytics/libs/bower_components/sprintf/dist: sprintf.min.map
Only in analytics/libs/bower_components/sprintf: package.json
Only in analytics/libs/bower_components/visibilityjs: bower.json
Only in analytics/libs: javascript
Only in analytics/libs/jqplot: jqplot.core.js
Only in analytics/libs/jqplot: jqplot.lineRenderer.js
Only in analytics/libs/jqplot: jqplot.linearAxisRenderer.js
Only in analytics/libs/jqplot: jqplot.themeEngine.js
Only in analytics/libs/jqplot/plugins: jqplot.barRenderer.js
Only in analytics/libs/jqplot/plugins: jqplot.pieRenderer.js
Only in analytics/misc: gpl-3.0.txt
Only in analytics/plugins/CoreHome/stylesheets: jqplotColors.less
Only in analytics/plugins/CoreUpdater/ReleaseChannel: Latest2XBeta.php
Only in analytics/plugins/CoreUpdater/ReleaseChannel: Latest2XStable.php
Only in analytics/plugins: ExampleAPI
Only in analytics/plugins: ExampleCommand
Only in analytics/plugins: ExampleLogTables
Only in analytics/plugins: ExamplePlugin
Only in analytics/plugins: ExampleReport
Only in analytics/plugins: ExampleSettingsPlugin
Only in analytics/plugins: ExampleTheme
Only in analytics/plugins: ExampleTracker
Only in analytics/plugins: ExampleUI
Only in analytics/plugins: ExampleVisualization
Only in analytics/plugins/Morpheus/icons/dist/brand: Kempler_&_Strauss.png
Only in analytics/plugins/TagManager/libs/jquery-timepicker: bower.json
Only in analytics/plugins/TagManager/libs/jquery-timepicker: package.json
Only in analytics/plugins/TagManager: misc
Only in analytics/plugins/TagManager: plugin.json
Only in analytics/plugins/TagManager: screenshots
Only in analytics/vendor/composer/ca-bundle: composer.json
Only in analytics/vendor/composer/semver: composer.json
Only in analytics/vendor/container-interop/container-interop: composer.json
Only in analytics/vendor/davaxi/sparkline: .codeclimate.yml
Only in analytics/vendor/davaxi/sparkline: composer.json
Only in analytics/vendor/davaxi/sparkline: composer.travis.json
Only in analytics/vendor/davaxi/sparkline: grumphp.yml
Only in analytics/vendor/davaxi/sparkline: phpunit.xml
Only in analytics/vendor/doctrine/cache: composer.json
Only in analytics/vendor/doctrine/cache: phpunit.xml.dist
Only in analytics/vendor/geoip2/geoip2: composer.json
Only in analytics/vendor/leafo/lessphp: composer.json
Only in analytics/vendor/matomo/referrer-spam-blacklist: composer.json
Only in analytics/vendor/matomo/searchengine-and-social-list: composer.json
Only in analytics/vendor/matomo/searchengine-and-social-list: package.json
Only in analytics/vendor/matomo-org/jshrink: composer.json
Only in analytics/vendor/matomo-org/jshrink: phpunit.xml.dist
Only in analytics/vendor/maxmind/web-service-common: composer.json
Only in analytics/vendor/maxmind-db/reader: composer.json
Only in analytics/vendor/monolog/monolog: composer.json
Only in analytics/vendor/monolog/monolog: doc
Only in analytics/vendor/monolog/monolog: phpunit.xml.dist
Only in analytics/vendor/mustangostang/spyc: README
Only in analytics/vendor/mustangostang/spyc: composer.json
Only in analytics/vendor/pear/archive_tar: composer.json
Only in analytics/vendor/pear/console_getopt: composer.json
Only in analytics/vendor/pear/pear-core-minimal: composer.json
Only in analytics/vendor/pear/pear_exception: composer.json
Only in analytics/vendor/php-di/invoker: composer.json
Only in analytics/vendor/php-di/php-di: composer.json
Only in analytics/vendor/php-di/php-di: phpunit.xml.dist
Only in analytics/vendor/php-di/phpdoc-reader: composer.json
Only in analytics/vendor/piwik/cache: composer.json
Only in analytics/vendor/piwik/cache: composer.lock
Only in analytics/vendor/piwik/cache: phpunit.xml
Only in analytics/vendor/piwik/decompress: composer.json
Only in analytics/vendor/piwik/decompress: composer.lock
Only in analytics/vendor/piwik/decompress: phpunit.xml
Only in analytics/vendor/piwik/device-detector: composer.json
Only in analytics/vendor/piwik/ini: composer.json
Only in analytics/vendor/piwik/ini: phpunit.xml
Only in analytics/vendor/piwik/network: composer.json
Only in analytics/vendor/piwik/network: phpunit.xml
Only in analytics/vendor/piwik/piwik-php-tracker: composer.json
Only in analytics/vendor/psr/container: composer.json
Only in analytics/vendor/psr/log: composer.json
Only in analytics/vendor/symfony/console/Symfony/Component/Console: composer.json
Only in analytics/vendor/symfony/console/Symfony/Component/Console: phpunit.xml.dist
Only in analytics/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher: composer.json
Only in analytics/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher: phpunit.xml.dist
Only in analytics/vendor/symfony/monolog-bridge/Symfony/Bridge/Monolog: composer.json
Only in analytics/vendor/symfony/monolog-bridge/Symfony/Bridge/Monolog: phpunit.xml.dist
Only in analytics/vendor/symfony/polyfill-ctype: composer.json
Only in analytics/vendor/szymach/c-pchart: composer.json
Only in analytics/vendor/tecnickcom/tcpdf: composer.json
Only in analytics/vendor/twig/twig: composer.json
Only in analytics/vendor/twig/twig: phpunit.xml.dist

**Comment by tsteur** [comment]
@r621549 what exactly is extra tools?

When you do this

> bash-5.0# cd matomo/
> bash-5.0# composer require symfony/yaml:~2.6.0

I wonder if this overwrites our own composer auto loader and therefore cannot find our files

**Comment by r621549** [comment]
> @r621549 what exactly is extra tools?
> 
> When you do this
> 
> > bash-5.0# cd matomo/
> > bash-5.0# composer require symfony/yaml:~2.6.0
> 
> I wonder if this overwrites our own composer auto loader and therefore cannot find our files

ExtraTools : plugins to install matomo from command line : https://plugins.matomo.org/ExtraTools

**Comment by r621549** [comment]
> > @r621549 what exactly is extra tools?
> > When you do this
> > > bash-5.0# cd matomo/
> > > bash-5.0# composer require symfony/yaml:~2.6.0
> > 
> > 
> > I wonder if this overwrites our own composer auto loader and therefore cannot find our files
> 
> ExtraTools : plugins to install matomo from command line : https://plugins.matomo.org/ExtraTools

Also I created ticket with ExtraTools. they are also saying matomo is missing some files : https://github.com/digitalist-se/extratools/issues/18

**Comment by tsteur** [comment]
@r621549 check out this comment again re the composer: https://github.com/matomo-org/matomo/issues/15738#issuecomment-605576633

Maybe try all the steps again,eg install Matomo files and then check and what step the file in `core/Plugin/Manager.php` has gone missing. And if the file still exists, it seems like some autoloader issue because of composer maybe.

**Comment by r621549** [comment]
> @r621549 check out this comment again re the composer: [#15738 (comment)](https://github.com/matomo-org/matomo/issues/15738#issuecomment-605576633)
> 
> Maybe try all the steps again,eg install Matomo files and then check and what step the file in `core/Plugin/Manager.php` has gone missing. And if the file still exists, it seems like some autoloader issue because of composer maybe.

@tsteur 

I am seeing the core/Plugin/Manager.php

bash-5.0#  ./console plugin:activate ExtraTools
**[30-Mar-2020 19:50:27 UTC] PHP Fatal error:  Uncaught Error: Class 'Piwik\Plugin\Manager' not found in /var/www/html/install/matomo_try_1/matomo/core/bootstrap.php:46
Stack trace:
#0 /var/www/html/install/matomo_try_1/matomo/console(18): require_once()
#1 {main}
  thrown in /var/www/html/install/matomo_try_1/matomo/core/bootstrap.php on line 46

Fatal error: Uncaught Error: Class 'Piwik\Plugin\Manager' not found in /var/www/html/install/matomo_try_1/matomo/core/bootstrap.php:46
Stack trace:
#0 /var/www/html/install/matomo_try_1/matomo/console(18): require_once()
#1 {main}
  thrown in /var/www/html/install/matomo_try_1/matomo/core/bootstrap.php on line 46**
bash-5.0# ls -ltr core/Plugin/
total 368
-rw-r--r--    1 root     root          4656 Mar 30 19:37 WidgetsProvider.php
-rw-r--r--    1 root     root         32351 Mar 30 19:37 Visualization.php
-rw-r--r--    1 root     root         22227 Mar 30 19:37 ViewDataTable.php
-rw-r--r--    1 root     root          5957 Mar 30 19:37 ThemeStyles.php
-rw-r--r--    1 root     root          5494 Mar 30 19:37 Tasks.php
-rw-r--r--    1 root     root          7323 Mar 30 19:37 SettingsProvider.php
-rw-r--r--    1 root     root         11822 Mar 30 19:37 Segment.php
-rw-r--r--    1 root     root           629 Mar 30 19:37 RequestProcessors.php
-rw-r--r--    1 root     root          9290 Mar 30 19:37 ReportsProvider.php
-rw-r--r--    1 root     root         34514 Mar 30 19:37 Report.php
-rw-r--r--    1 root     root          2608 Mar 30 19:37 ReleaseChannels.php
-rw-r--r--    1 root     root          2328 Mar 30 19:37 ProcessedMetric.php
-rw-r--r--    1 root     root          1137 Mar 30 19:37 PluginException.php
-rw-r--r--    1 root     root          6560 Mar 30 19:37 Metric.php
-rw-r--r--    1 root     root          3833 Mar 30 19:37 MetadataLoader.php
-rw-r--r--    1 root     root         10065 Mar 30 19:37 Menu.php
**-rw-r--r--    1 root     root         52303 Mar 30 19:37 Manager.php**
-rw-r--r--    1 root     root          3183 Mar 30 19:37 LogTablesProvider.php
drwxr-xr-x    2 root     root          4096 Mar 30 19:37 Dimension
-rw-r--r--    1 root     root          4928 Mar 30 19:37 Dependency.php
-rw-r--r--    1 root     root         14840 Mar 30 19:37 ControllerAdmin.php
-rw-r--r--    1 root     root         42523 Mar 30 19:37 Controller.php
-rw-r--r--    1 root     root          1203 Mar 30 19:37 ConsoleCommand.php
-rw-r--r--    1 root     root          8719 Mar 30 19:37 ComputedMetric.php
-rw-r--r--    1 root     root          5059 Mar 30 19:37 ComponentFactory.php
-rw-r--r--    1 root     root          2032 Mar 30 19:37 Categories.php
-rw-r--r--    1 root     root          5473 Mar 30 19:37 Archiver.php
-rw-r--r--    1 root     root          5553 Mar 30 19:37 ArchivedMetric.php
-rw-r--r--    1 root     root           611 Mar 30 19:37 AggregatedMetric.php
-rw-r--r--    1 root     root          2901 Mar 30 19:37 API.php

**Comment by r621549** [comment]
Any opinion on fixing the autoloader issue?

**Comment by tsteur** [comment]
You would need to use Matomo from git. However, this is only recommended for development and not production: https://matomo.org/faq/how-to-install/faq_18271/

Alternatively, don't run the composer command if possible as this would be removing our autoloader by the looks maybe.

**Comment by r621549** [comment]
> You would need to use Matomo from git. However, this is only recommended for development and not production: https://matomo.org/faq/how-to-install/faq_18271/
> 
> Alternatively, don't run the composer command if possible as this would be removing our autoloader by the looks maybe.

I have to install these two dependencies so i am running composer
composer require symfony/yaml:~2.6.0 (moves it from dev)
composer require symfony/process:^3.4

If i am not installing these two dependencies then i am unable to install matomo 
bash-5.0# ./console matomo:install --db-username=dbuser --db-pass=password --db-host=benefitpro-matomo-mysql --db-name="matomo" --db-prefix="piwik_"
Are you really sure you would like to install Matomo - if you have an installation already, it will be wiped? yes
ERROR [2020-03-30 20:23:35] 492 Uncaught exception: Error: Class 'Symfony\Component\Process\Process' not found in /var/www/html/install/matomo_try_3/matomo/plugins/ExtraTools/Lib/Drop.php:32
Stack trace:
#0 /var/www/html/install/matomo_try_3/matomo/plugins/ExtraTools/Commands/InstallMatomo.php(223): Piwik\Plugins\ExtraTools\Lib\Drop->execute()
#1 /var/www/html/install/matomo_try_3/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\ExtraTools\Commands\InstallMatomo->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/install/matomo_try_3/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/install/matomo_try_3/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\ExtraTools\Commands\InstallMatomo), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/install/matomo_try_3/matomo/core/Console.php(140): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/install/matomo_try_3/matomo/core/Access.php(644): Piwik\Console->Piwik{closure}()
#7 /var/www/html/install/matomo_try_3/matomo/core/Console.php(141): Piwik\Access::doAsSuperUser(Object(Closure))
#8 /var/www/html/install/matomo_try_3/matomo/core/Console.php(93): Piwik\Console->doRunImpl(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/install/matomo_try_3/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/install/matomo_try_3/matomo/console(32): Symfony\Component\Console\Application->run()
#11 {main}
Uncaught exception: Class 'Symfony\Component\Process\Process' not found
in /var/www/html/install/matomo_try_3/matomo/plugins/ExtraTools/Lib/Drop.php line 32
#0 /var/www/html/install/matomo_try_3/matomo/plugins/ExtraTools/Commands/InstallMatomo.php(223): Piwik\Plugins\ExtraTools\Lib\Drop->execute()
#1 /var/www/html/install/matomo_try_3/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\ExtraTools\Commands\InstallMatomo->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/install/matomo_try_3/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/install/matomo_try_3/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\ExtraTools\Commands\InstallMatomo), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/install/matomo_try_3/matomo/core/Console.php(140): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/install/matomo_try_3/matomo/core/Access.php(644): Piwik\Console->Piwik{closure}()
#7 /var/www/html/install/matomo_try_3/matomo/core/Console.php(141): Piwik\Access::doAsSuperUser(Object(Closure))
#8 /var/www/html/install/matomo_try_3/matomo/core/Console.php(93): Piwik\Console->doRunImpl(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/install/matomo_try_3/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/install/matomo_try_3/matomo/console(32): Symfony\Component\Console\Application->run()
#11 {main}

**Comment by tsteur** [comment]
@r621549 then the only way be to install it through github. Or before running that command you copy these two files into your Matomo directory. That might fix it as well:

https://github.com/matomo-org/matomo/blob/3.x-dev/composer.json
https://github.com/matomo-org/matomo/blob/3.x-dev/composer.lock

I'll close the issue now as it seems rather an issue with ExtraTools and how they require dependcies.

**Comment by r621549** [comment]
Thank you so much , it got resolved, the issue was composer.json was missing in latest version.
