### ISSUE TITLE
[release bug] 3.13.4 is labeled as pre-release in Github

### ISSUE THREAD

**Issue by toredash** [matomo-org/matomo#15731]
https://github.com/matomo-org/matomo/releases

![image](https://user-images.githubusercontent.com/312038/77579413-95995000-6eda-11ea-88f7-650986a90c7f.png)

Custom update scripts won't work since it is labeled pre-release:
```
curl --silent "https://api.github.com/repos/matomo-org/matomo/releases/latest" | jq -r .tag_name
3.13.3
```

**Comment by sgiehl** [comment]
changed that.
