### ISSUE TITLE
Data for an hour is missing in Visit per server time panel after aplying DST change

### ISSUE THREAD

**Issue by pardvm** [matomo-org/matomo#15754]
Last March, 29th DST was enforced in Europe, changing from CET to CEST, that is, at 02:00 it was 03:00 (one hour forward)
The day after, March 30th, we found this "hole" in "Visit per server time" panel of **all sites** where the DST was applicable:
![image](https://user-images.githubusercontent.com/25912392/77945585-2a2bf580-72c1-11ea-91b2-f4aba1a33fa8.png)

This is an effect that we are used to see every time DST is enforced from CET to CEST (once per year) but, know, my customers are asking **why this happens the day after the change**

I thought it could be a kind of bug and I ended up in #12251 and #9949 that are quite similar. However I'm not sure that all are the same.

Could anybody explain this wierd effect?

**Comment by tsteur** [comment]
@pardvm this would be related to these issues. Not exactly sure what causes it though unfortunately.

Will close this issue for now as a duplicate. Feel free to comment in the other issues.
