### ISSUE TITLE
No connection to the matomo marketplace 

### ISSUE THREAD

**Issue by Tim197** [matomo-org/matomo#15766]
Hello,

since we have deployed a new matomo server as a replacement of the old one, we get no response from the marketplace.
We are using: 
- Matomo version: 3.13.3
- MySQL version: 10.4.12
- PHP version: 7.4.4

![image](https://user-images.githubusercontent.com/59436394/78107035-04077200-73f5-11ea-9cb0-8b9129af2881.png)
![image](https://user-images.githubusercontent.com/59436394/78107051-0b2e8000-73f5-11ea-960b-5f752da4f4f6.png)

We are also not able to update the system automatically, maybe this is caused by the same problem?!
 
![image](https://user-images.githubusercontent.com/59436394/78107172-3f09a580-73f5-11ea-9789-2d36a78d402c.png)

Could this warning be a reason for the issues?

![image](https://user-images.githubusercontent.com/59436394/78107295-7f692380-73f5-11ea-8622-f3eff5ec3cb6.png)

-------------------------------------------------------------------------

Current config:

`vi etc/apt/apt.conf` & `vi etc/apt/apt.conf.d/proxy.conf`
![image](https://user-images.githubusercontent.com/59436394/78107642-2c43a080-73f6-11ea-837b-94e7a16941ca.png)

`vi /var/www/matomo/config/config.ini.php`
![image](https://user-images.githubusercontent.com/59436394/78108070-f05d0b00-73f6-11ea-890c-8f8a8d817eae.png)

`curl https://plugins.matomo.org`
`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to plugins.matomo.org:443
(root@SWEBKO24:/var/www/matomo/config $)`

Anything would I should test or can do to solve this issue?
Thanks in advance.

**Comment by Findus23** [comment]
Hi,

As the same error occurs when you use curl from the cli, I would leave Matomo aside and look into fixing this first as it is far simpler to test.

`SSL_ERROR_SYSCALL` in OpenSSL means that OpenSSL tries to establish an encrypted connection for HTTPS, but fails at this. Maybe there is some program or some firewall that is aborting the first handshake.

**Comment by Tim197** [comment]
Hi,

ok. I tested it on the VM and it works

![image](https://user-images.githubusercontent.com/59436394/78139829-5febee00-7429-11ea-8b93-c5abc3e18dd6.png)

![image](https://user-images.githubusercontent.com/59436394/78139906-7e51e980-7429-11ea-9af4-c4cebb1a8ca9.png)

**Comment by tsteur** [comment]
@Tim197 I'll close this issue for now as it looks like a server configuration issue. Feel free to continue discussing here or in the forum: https://forum.matomo.org/ 

Happy to reopen should there be any issue with Matomo directly.

Be great if you could let us know what the problem was in case someone else runs into the same issue some day.
