### ISSUE TITLE
Realtime visitors "visitsTotal"-div is inserted multiple times

### ISSUE THREAD

**Issue by ChristopherWalz** [matomo-org/matomo#15764]
When visiting the real time visitor page, after the first automatical refresh the div with the id "visitsTotal" is inserted as an child element into "visitsTotal" which results in a UI bug, see the attachment screenshot.

![image](https://user-images.githubusercontent.com/962334/78104241-6b3b1b80-7421-11ea-889a-32ef6bc5a072.png)

**Comment by sgiehl** [comment]
Thanks for the report. I'm able to reproduce that. Will provide a fix soon.
