### ISSUE TITLE
Fatal error: Class 'Piwik\SettingsServer' not found in /var/www/egor/data/www/matomo.re-trafic.ru/core/testMinimumPhpVersion.php on line 87

### ISSUE THREAD

**Issue by Retrafic** [matomo-org/matomo#15771]
Приветствую!
выполнил пошаговую установку и получаю вот такую ошибку. Версия установлена самая новая, которая представлена на сайте. Подскажите, как решить такую проблему?

**Comment by tsteur** [comment]
Do you know what PHP version you have? Likely your PHP version is too low. 

It seems we're using a file settings server before the autoloader is loaded.

**Comment by Retrafic** [comment]
PHP 5.6.40 (cli) (built: Mar 17 2020 07:51:44)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
mysql Ver 14.14 Distrib 5.5.62, for Linux (x86_64) using readline 5.1
pdo_mysql
pdo_sqlite

**Comment by Retrafic** [comment]
я несколько раз скачивал из github, официального сайта, и устанавливал matomo. Проблема не решилась

**Comment by tsteur** [comment]
I suppose you downloaded the 4.x-dev branch from Github which requires PHP 7.2+. Maybe you could try the `3.x-dev` branch?
We are currently working on the 4.0 release but 3.X is the latest available

**Comment by Retrafic** [comment]
скачивал ещё с официального сайта matomo, а там минимальные требования PHP версия 5.5.9 или выше, а у меня выше

**Comment by tsteur** [comment]
@Retrafic could you edit the file `core/testMinimumPhpVersion.php` and change around line 87 the code to this and then see what happens?

![image](https://user-images.githubusercontent.com/273120/78509488-532d1880-77e2-11ea-9236-a47fe681d1d2.png)

Basically you remove a few lines and replace them with `return true;`

**Comment by Retrafic** [comment]
Спасибо большое! получилось установить. проблема была с версией php. Поднял до PHP 7.3 и всё заработало

**Comment by tsteur** [comment]
Thanks a lot for letting us know @Retrafic I'll reopen the issue anyway as it looks like there is some issue which many people might run into with Matomo 4.
