### ISSUE TITLE
Cookie domain config is not applied in ignore cookie preventing opt out to work

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#15778]
https://github.com/matomo-org/tracker-proxy/issues/58

We need to set similar to the third party cookie https://github.com/matomo-org/matomo/blob/3.13.4/core/Tracker/Request.php#L707-L710 also set the cookie domain here: https://github.com/matomo-org/matomo/blob/3.13.4/core/Tracker/IgnoreCookie.php#L61

**Comment by yrammos** [comment]
@tsteur Is there any chance this could be triaged to an earlier release? It is an absolutely crippling bug on low-traffic installations because analytics are severely distorted by maintainers' visits. Thank you for your consideration.

**Comment by tsteur** [comment]
@yrammos if you are familiar with applying patches or changes to a file then you could try to apply this and give it a test: https://github.com/matomo-org/matomo/pull/16123/files

It might only be merged with Matomo 4.1 though maybe (or earlier).

**Comment by yrammos** [comment]
@tsteur thank you for responding so briskly. I applied the and it appears to be a partial improvement. Before the patch, the ignore cookie was ineffective on all my websites. With the patch, Matomo ignores only visits to websites hosted on Matomo's domain. More specifically:

`matomo.domain.com` => Matomo installation
`domain.com` => Successfully ignored after the patch
`otherdomain.com` => Ignore cookie still not working

**Comment by tsteur** [comment]
I see... this might actually not going to work then with the tracker proxy... unless you were always using the same domain for all proxies. 

It may needs a different fix eg in tracker proxy itself or so.

**Comment by yrammos** [comment]
@tsteur I now noticed that the issue is not limited to the tracker proxy. I can reproduce it exactly as described in my previous post using the JS tracker, as well. Is my case an isolated one?

**Comment by tsteur** [comment]
@yrammos yes this could also be a general issue if you want to have cookies set on a specific domain.

FYI we'll merge the cookie domain change as part of this PR probably today https://github.com/matomo-org/matomo/pull/13301

This will be in Matomo 4.

**Comment by tsteur** [comment]
This particular issue was actually fixed @yrammos 

https://github.com/matomo-org/tracker-proxy/issues/58 is still open as you mention it's not fully fixed yet which is because the tracker proxy seems to be needing a fix too to handle this correctly.
