### ISSUE TITLE
setting matomo user id from body section 

### ISSUE THREAD

**Issue by subasrikalyankumar** [matomo-org/matomo#15787]
Hii,
In matomo JS tracking, we  need to set  `userId`  for the users in the tracking code which is placed in the head section.But in my site, i'll be getting the user id say login name only in the body. How can set the user id in this case?Thanks in advance

**Comment by sgiehl** [comment]
@subasrikalyankumar please ask such questions in our forum https://forum.matomo.org or through our support in case you have a support plan: https://matomo.org/support-plans/
We use this issue tracker here only to handle feature requests and bug reports.
