### ISSUE TITLE
encrypting/hiding the matomo url in tracking code

### ISSUE THREAD

**Issue by subasrikalyankumar** [matomo-org/matomo#15788]
Hii,
    How can we hide/ encrypt the matomo tracking code so that we can protect the matomo server url being viewed from the users.

**Comment by sgiehl** [comment]
@subasrikalyankumar please ask such questions in our forum https://forum.matomo.org or through our support in case you have a support plan: https://matomo.org/support-plans/
We use this issue tracker here only to handle feature requests and bug reports.
