### ISSUE TITLE
Activate automatic translation updates for plugins

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#15792]
I've built a github action we can use for automatically creating PR with translation updates for our plugins. See https://github.com/sgiehl/matomo-plugin-translations-update. 

Using that in the plugin is quite easy as it only requires adding transifex username and password as secrets and adding a small action file. 

Already did that for my `ReferrersManager` plugin. See https://github.com/sgiehl/piwik-plugin-ReferrersManager/blob/master/.github/workflows/translations.yml

Open Todos for our plugins:
* [x] Create secrets in all repos
* [x] Move action to matomo
* [x] create action yml file in all repos

**Comment by sgiehl** [comment]
@tsteur assigned the issue to you for now. Please add the secrets to all repos once you have time for it and assign the issue back to me once you're finished and I'll do the remaining tasks

**Comment by tsteur** [comment]
@sgiehl added the secrets to most `matomo-org/plugin-` repos. Except for 2 or 3 like PiwikDebugger, ClassicFontTheme, and not sure if there was another one. 

Be good to wait for a 4-6 weeks with setting this up fully so we can first work on the issues and also don't have to merge PRs created by this etc as they wouldn't be needed before an RC anyway.

**Comment by sgiehl** [comment]
Automatic updates are now already running for our free plugins
