### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by Retrafic** [matomo-org/matomo#15791]
Добрый день!

подскажите, что я делаю не то:

В поле «URL для вызова» введите http://www.example.com/path/to/piwik/misc/cron/archive.php?token_auth=XYZ (замените http://www.example.com/path/ в / с вашим местом установки). Выберите подходящую частоту выполнения заданий cron (для Matomo мы рекомендуем запускать задания cron «каждый час»). Оформить заказ ниже скриншот:

у меня путь такой: http://prntscr.com/rv9chq Менеджер файлов /var/www/www-root/data/www/matomo.re-trafic.ru/misc/

как мне корректно создать ссылку чтобы всё работало. как только не пробовал вот такую ошибку получаю. а Cron делаю через https://www.easycron.com/user

ошибка: http://prntscr.com/rv9dcv

**Comment by sgiehl** [comment]
@Retrafic please create issues in english. And for questions please use our forum at https://forum.matomo.org
