### ISSUE TITLE
Ошибка во время выполнения запроса

### ISSUE THREAD

**Issue by Retrafic** [matomo-org/matomo#15790]
Добрый день! 
Подскажите пожалуйста, как решить такой вопрос:

выбираю период 2 дня и не могу посмотреть результат из-за ошибки http://prntscr.com/rv76sh
выбираю 1 день и ошибка пропадает.

Проблематично конечно не наблюдать картину в динамике. Очень хочу посмотреть в динамике и иметь возможность выбрать не только 2 дня, но и недели, месяцы. Пока такой возможности к сожалению нет

**Comment by Globulopolis** [comment]
В логах ошибок что пишет? Возможно скрипт по таймауту падает.

**Comment by Retrafic** [comment]
вы про это? http://prntscr.com/rv7h70

**Comment by Globulopolis** [comment]
max_allowed_packet увеличте до рекомендуемого + посмотрите логи ошибок php. Хватает ли памяти и времени на выполнение скрипта.

**Comment by Findus23** [comment]
Hi, 

This issue is more intended for reporting specific bugs that can already be reproduced. 
For general troubleshooting and help we got the Matomo forum: https://forum.matomo.org/
If you want and someone volunteers to monitor it, I can even create a Russian subforum there.

**Comment by Retrafic** [comment]
Спасибо огромное!
