### ISSUE TITLE
How to find unique visitors from log_visit records without login (same user but different browsers)

### ISSUE THREAD

**Issue by prazserendio** [matomo-org/matomo#15799]
How to **find unique visitors from log_visit records without login** (same user but different browsers) I am using google based unique profiling.

Example: Same visitor from different browsers and different devices?

1. Chrome
2. Firefox
3. Safari from phone

**How to derive all visitors are same across browsers and also devices?**

**Comment by tsteur** [comment]
H @prazserendio you would need to use the [user id](https://matomo.org/docs/user-id/) feature.  For further questions please ask them in our forum as we don't answer questions on github: https://forum.matomo.org/
