### ISSUE TITLE
Docker-compose on windows not working

### ISSUE THREAD

**Issue by DinoSourcesRex** [matomo-org/matomo#15807]
Hi,

I've been trying to get matomo to work using `docker-compose` on Windows but I seem to hit a hurdle every time I make a fix.

https://github.com/DinoSourcesRex/matomo-issues

After doing all the steps listed in the `readme.md` on that project I am presented with `SQLSTATE[HY000] [2002] No such file or directory`

Any ideas on if these are known issues?

Thanks

**Comment by tsteur** [comment]
Hi there, unfortunately we don't answer questions in our GitHub but only handle bug reports and feature requests around Matomo core. Maybe ask in our forum https://forum.matomo.org/ or consider using https://github.com/matomo-org/docker ?

**Comment by DinoSourcesRex** [comment]
@tsteur Hi. Appreicate the reponse.

I took the `docker-compose` from the repo you linked. Would it not constitute a bug that that does not work out of the box?

**Comment by tsteur** [comment]
@DinoSourcesRex I suggest you create an issue directly in that repo then 👍  thought you created your own one as your repo looked bit different. Not sure they can help you though if you made changes to it. I'd suggest you create an issue there and maybe they can help.

**Comment by DinoSourcesRex** [comment]
Thanks @tsteur - I guess I ended up in the wrong place :D
