### ISSUE TITLE
cron-matomo-archive.log

### ISSUE THREAD

**Issue by Retrafic** [matomo-org/matomo#15802]
Help. I use Owlhost hosting, I work with VPS through ISP 5 Lite. Where there is a scheduler for cron tasks. I'm trying to set up archiving, but nothing works. Here is a mistake:

root# php /var/www/www-root/data/www/matomo.re-trafic.ru/console core:archive --no-ansi >> /path/to/logs/cron-matomo-archive.log
/bin/sh: /path/to/logs/cron-matomo-archive.log: No such file or directory

**Comment by Retrafic** [comment]
Archiving has not yet run successfully.

Please check that you have setup a crontab calling the core:archive console command, and that you have configured a MAILTO to receive errors by email if archiving fails. You can also try to run the console command to archive your reports manually: /var/www/www-root/data/www/matomo.re-trafic.ru --matomo-domain=matomo.re-trafic.ru core:archive

**Comment by tsteur** [comment]
@Retrafic we don't answer questions in here unfortunately. Do you mind asking how to set it up in our forum https://forum.matomo.org/ ?

Generally, it sounds like `/path/to/logs/cron-matomo-archive.log` doesn't exist. Maybe create the file manually like `touch /path/to/logs/cron-matomo-archive.log` and make sure the crontab user can write to it?
