### ISSUE TITLE
Question: should prefilling with environment variables still work?

### ISSUE THREAD

**Issue by alexanderadam** [matomo-org/matomo#15803]
I saw [this PR](https://github.com/matomo-org/matomo/pull/13676/files) which should allow prefilling values by environment variables like `MATOMO_DATABASE_HOST` , `MATOMO_DATABASE_USERNAME` etc  but it doesn't seem to work for me.

**PS:** I'm using [this Docker image](https://github.com/crazy-max/docker-matomo) (although it shouldn't make any difference because [it is part of the installation plugin](https://github.com/matomo-org/matomo/blob/3.13.4/plugins/Installation/FormDatabaseSetup.php) anyway, right?

**Comment by tsteur** [comment]
This should work and prefill those values in the Matomo installation UI @alexanderadam

**Comment by alexanderadam** [comment]
Sorry, my fault. This seems to work indeed.
