### ISSUE TITLE
Question: StaticContainer deprecated or not?

### ISSUE THREAD

**Issue by mikkeschiren** [matomo-org/matomo#15847]
The class StaticContainer has been marked as deprecated a long time ("It will be removed in 3.0") - and it is still used extensively in the core code -  should it still be marked as deprecated when it is in fact in use?

**Comment by sgiehl** [comment]
refs https://github.com/matomo-org/matomo/issues/8567

**Comment by tsteur** [comment]
We can indeed remove this deprecation. Should be a quick one. We should make clear that we discourage the usage though and recommend to use proper __constructor injection where possible. Eg in the doc header for that method.

**Comment by tsteur** [comment]
The class still exists but we no longer support it as official API. We've documented eg in https://developer.matomo.org/guides/dependency-injection how to use dependency injection instead
