### ISSUE TITLE
Conversions are 0 when comparing dates

### ISSUE THREAD

**Issue by jmumby** [matomo-org/matomo#15849]
If you compare dates in goals > overview > channel type the conversions are always 0. 

This can be seen [here](https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday#?idSite=3&period=week&date=2020-04-16&segment=&category=Goals_Goals&subcategory=General_Overview&comparePeriods%5B%5D=week&compareDates%5B%5D=2020-04-06
): 

![image](https://user-images.githubusercontent.com/4339071/80024795-b386be80-8533-11ea-87e1-a0a1bc82fb1c.png)

Without comparing dates the data is as [expected](https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=3&period=day&date=yesterday#?idSite=3&period=week&date=2020-04-16&segment=&category=Goals_Goals&subcategory=General_Overview).

![image](https://user-images.githubusercontent.com/4339071/80024998-09f3fd00-8534-11ea-9250-c3da674d3dad.png)

**Comment by tsteur** [comment]
Thanks @jmumby

**Comment by sgiehl** [comment]
closing in favor of #18869
