### ISSUE TITLE
Visitor Software Report empty for segments.

### ISSUE THREAD

**Issue by jorgeuos** [matomo-org/matomo#15852]
Hi,

On Visitors-->Software

Trying to get e.g. Browser version for any given segment but I get "There is no data for this report." every time for every segment. On our Matomo, we get data for the defaults but not the "Related reports".

See demo site:
https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=day&date=yesterday#?idSite=62&period=week&date=2020-04-16&segment=dimension1%3D%3Dcandidate&category=General_Visitors&subcategory=DevicesDetection_Software

I've noticed that sites that has really low number of visits, this works fine. This could perhaps be related to archiving not completed yet.

Any progress in this issue would be beneficial to share.
I will take a look tomorrow.

Br, Jorge

**Comment by tsteur** [comment]
Hi @jorgeuos 

thanks for creating the issue. Are you only seeing this error on that demo site? I tested it on other sites on the demo (which aren't accessible publicly) and it works fine there. The demo site you are referring to is bit of a special case. Are you having this issue in your Matomo too maybe?

**Comment by jorgeuos** [comment]
Hi,

Yes, that is why I created the issue, not because of the demo site of course. I will further investigate later today. The time period I would like is months, but this does not even work with days.

![Screenshot_2020-04-24_at_07_55_18](https://user-images.githubusercontent.com/21176316/80181186-a84f9380-8604-11ea-8c53-bb3fb27db20c.png)
![Screenshot_2020-04-24_at_07_55_48](https://user-images.githubusercontent.com/21176316/80181196-ab4a8400-8604-11ea-8785-16bebf07e575.png)

**Comment by tsteur** [comment]
Do you know if browser archiving is enabled? 

You can see this by going to Admin -> General Settings.

![image](https://user-images.githubusercontent.com/273120/80440198-59836000-895c-11ea-90a6-bdb01cffe9bf.png)

Do you also know if there is maybe a config setting enabled in your `config/config.ini.php` called `browser_archiving_disabled_enforce` ? Could you maybe check if there is a line that contains this value? eg `browser_archiving_disabled_enforce = 1`
 
Is this the case for all segments or only specific segments? Does it work for some days / weeks / months?

**Comment by tsteur** [comment]
BTW is it correct that basically all other reports work except for those two?

**Comment by jorgeuos** [comment]
Hi,
It's a multi cluster setup for >100 million page views, we're maybe using half of the capacity right now. Archiving is triggered by cron, we have different cron jobs scheduled for different periods I think, if I remember correctly. I don't remember exactly how often they are running but basically a couple of times a day.

```
browser_archiving_disabled_enforce = 1
enable_browser_archiving_triggering = 0
```

For the second question, yes, all other reports afaik works well. This a report from the Data analyst, not me. Our investigation has left us to dead ends. If you want me to check any other report I'll happily check them for you.

![Screenshot_2020-04-28_at_10_38_08](https://user-images.githubusercontent.com/21176316/80466630-1a91e200-893d-11ea-9288-895b8c60b371.png)


Br, Jorge

**Comment by tsteur** [comment]
Thanks for this @jorgeuos I'd basically recommend to invalidate the report for that month so it'll be reprocessed see https://matomo.org/faq/how-to/faq_155/ and check if it comes up then. Eg 

```bash
./console core:invalidate-report-data --periods=month --dates=2020-03-03 --sites=SITEID
```

We don't have access to your PHP, Matomo, or archiving logs so it's bit hard to tell what happened exactly. You maybe want to log the output of all your archivers to some file (eg by adding `> /path/to/logs/archiving.log` to your crontab), make sure PHP logs errors, and Matomo also logs information to a file (https://matomo.org/faq/troubleshooting/faq_115/). Such things can help investigating issues. 

Hoping this helps. Be great to try the invalidation and see if it then comes up.

**Comment by jorgeuos** [comment]
Ok, thank you for your answer. I'll take a look over how the logs are set.
Invalidating this report right now could be troublesome for the client, we recently invalidated a long period related to another issue. I'll have to go through it with my colleague, I'll keep watching this report.

**Comment by tsteur** [comment]
@jorgeuos if it only invalidates that month's period it should in theory only take a minute or so to regenerate that specific archive.

**Comment by jorgeuos** [comment]
Hi, I just run over this issue again and bumped into this old thread. Sorry for the late respone... 2 kids later!! 😅

I'm curious about the month period in theory should take a couple of minutes...  
If I invalidate days, rerun the archives, then it would invalidate all reports in given period, right? Including segments. I currently have a job for re-archiving weeks and months periods for November 2021. Which been running for 22 hours. No daily reports are invalidated. Why is it taking so long?

```
./console core:archive -vvv --disable-scheduled-tasks --url="https://matomo.example.com/" --php-cli-options="-d memory_limit=8G" --concurrent-requests-per-website=12 --concurrent-archivers=12 --force-periods=week,month --force-date-range=2021-11-22,2021-11-22 --force-idsites=1
```

If I check the numeric table, there's `27327` invalidated reports for the day period, is this the correct assumption?
What is the desired state for the value column? Is it suppose to decrease when reports are being archived?
```sql
SELECT period, value, date1, date2, count(*)
FROM matomo.matomo_archive_numeric_2021_11
WHERE idsite=1
AND value=4
GROUP BY period;
```


Result:
```sql
period|value|date1     |date2     |count(*)|
------+-----+----------+----------+--------+
     1|  4.0|2021-11-01|2021-11-01|   27327|
     2|  4.0|2021-11-01|2021-11-07|    4558|
     3|  4.0|2021-11-01|2021-11-30|    1579|
     5|  4.0|2021-11-01|2021-11-08|     516|
```

Br, Jorge

**Comment by mattab** [comment]
Thanks for your patience with this issue. We believe this has been resolved in the recent updates of Matomo. To ensure you have the fix, please [update](https://matomo.org/docs/update/) to the latest version of Matomo.  If the issue persists after the update, don't hesitate to reopen this issue and let us know. Cheers!
