### ISSUE TITLE
slowly loading because of official website ipv6 unreachable. 

### ISSUE THREAD

**Issue by iwzoo** [matomo-org/matomo#15859]
recently I found it's extremely slow to load matomo on my vps running debian 10, after further study I found that it failed to get information from official websites (plugins.matomo.org e.g.) for marketplace and plugins, because the ipv6 is unreachable. To solve the problem, I need to disable the ipv6 completely or change to prefer ipv4 in /etc/gai.conf . 

After the changes in /etc/gai.conf, it loads quickly as normal. 

if you experience the same situation, you may try the the solution.

**Comment by Findus23** [comment]
Hi,

IPv6 seems to be working fine for me:
```
➜  ~ curl -6 https://api.matomo.org/1.0/getLatestVersion/ -v
*   Trying 2a00:b6e0:1:200:177::1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x561006067f50)
* Connected to api.matomo.org (2a00:b6e0:1:200:177::1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=api.matomo.org
*  start date: Mar  4 08:04:41 2020 GMT
*  expire date: Jun  2 08:04:41 2020 GMT
*  subjectAltName: host "api.matomo.org" matched cert's "api.matomo.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> GET /1.0/getLatestVersion/ HTTP/1.1
> Host: api.matomo.org
> User-Agent: curl/7.64.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 200 OK
< Date: Sun, 26 Apr 2020 08:32:40 GMT
< Server: Apache/2.2
< Cache-Control: max-age=691200
< Expires: Mon, 04 May 2020 08:32:40 GMT
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< Content-Type: text/html
< Via: 1.1 alproxy
< 
3.13.4
* Connection #0 to host api.matomo.org left intact
```

**Comment by iwzoo** [comment]
> Hi,
> 
> IPv6 seems to be working fine for me:
> 
> ```
> ➜  ~ curl -6 https://api.matomo.org/1.0/getLatestVersion/ -v
> *   Trying 2a00:b6e0:1:200:177::1...
> * TCP_NODELAY set
> * Expire in 200 ms for 4 (transfer 0x561006067f50)
> * Connected to api.matomo.org (2a00:b6e0:1:200:177::1) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: none
>   CApath: /etc/ssl/certs
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
> * TLSv1.3 (IN), TLS handshake, Certificate (11):
> * TLSv1.3 (IN), TLS handshake, CERT verify (15):
> * TLSv1.3 (IN), TLS handshake, Finished (20):
> * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.3 (OUT), TLS handshake, Finished (20):
> * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
> * ALPN, server did not agree to a protocol
> * Server certificate:
> *  subject: CN=api.matomo.org
> *  start date: Mar  4 08:04:41 2020 GMT
> *  expire date: Jun  2 08:04:41 2020 GMT
> *  subjectAltName: host "api.matomo.org" matched cert's "api.matomo.org"
> *  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
> *  SSL certificate verify ok.
> > GET /1.0/getLatestVersion/ HTTP/1.1
> > Host: api.matomo.org
> > User-Agent: curl/7.64.0
> > Accept: */*
> > 
> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> * old SSL session ID is stale, removing
> < HTTP/1.1 200 OK
> < Date: Sun, 26 Apr 2020 08:32:40 GMT
> < Server: Apache/2.2
> < Cache-Control: max-age=691200
> < Expires: Mon, 04 May 2020 08:32:40 GMT
> < Vary: Accept-Encoding
> < Transfer-Encoding: chunked
> < Content-Type: text/html
> < Via: 1.1 alproxy
> < 
> 3.13.4
> * Connection #0 to host api.matomo.org left intact
> ```

thank you.
 Just tried again, it still failed to reach ipv6 site from the server running matomo, i can't even ping the ip 2a00:b6e0:1:200:177::1.  But I can visit other sites like ipv6.google.com, and I can visit the ipv6 api.matomo.org from my laptop.  So I guess it is the settings of my server cause the problem.
