### ISSUE TITLE
Reexpire archive lock less often

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#15870]
There was https://github.com/matomo-org/matomo/pull/15749 and https://github.com/matomo-org/matomo/issues/15747

But I think it might not fully work actually. In performance insights still seeing these queries executed quote often and taking quite some resources. It seems like might be because in `getDb()` https://github.com/matomo-org/matomo/blob/3.13.5-rc1/core/DataAccess/LogAggregator.php#L1188 we always create a new instance of ArchivingDbAdapter and therefore https://github.com/matomo-org/matomo/blob/3.13.5-rc1/core/DataAccess/ArchivingDbAdapter.php#L37 would be quite often `null`.

BTW should maybe change the default value to `0` so it's not `null + $timeBetweenReexpires` in `reexpireLock()`. 

Maybe would somehow need to remember the last time per archiving lock?

fyi @diosmosis

**Comment by diosmosis** [comment]
@tsteur fyi created a PR

**Comment by diosmosis** [comment]
Fixed by #15874
