### ISSUE TITLE
Warning while upgrading "Warning - array_merge(): Argument #2 is not an array"

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15876]
WARNING: /home/piwik-demo/storage/www/demo.piwik.org/plugins/CoreUpdater/Updater.php(134): Warning - array_merge(): Argument #2 is not an array - Matomo 3.13.5-rc1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: CoreUpdater, Action: oneClickUpdate, In CLI mode: false)

**Comment by sgiehl** [comment]
Guess that happens when `oneClickUpdatePartTwo` does not return valid json. e.g when it takes to too long to resolve or it triggers an exception

**Comment by diosmosis** [comment]
fixed by #15877
