### ISSUE TITLE
Make visualisation more obvious eg by moving it to the top

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#15873]
We have quite a few visualisations that can be interesting such as insights, or now in Matomo 4 the "Performance metrics" for page reports. If you didn't know these visualisations existed, you'd never find them and never know you have these kind of features. It be great to make all these non obvious things eventually more obvious and more visible.

Would need to see what works. Eg on mobile it would maybe only show icons and no text vs on desktop show icon and visualisation text.

Eventually, later, could also move the other settings further up so you don't always have to scroll to the bottom. Only mentioning it in case there's some solution that this would directly work with too.

![image](https://user-images.githubusercontent.com/273120/80441230-96505680-895e-11ea-9841-ffcf2945f5d7.png)

(ignore the design, it's not designed at all and should not look like this)

**Comment by mattab** [comment]
it would be awesome :+1: making insights more visible, but also making Goal conversion metrics more visible, and the search too, the cog icon... 

we could either move all controls to the top or make them all visible at the bottom? 

If we can fit every control on one line, that'd be great too.

maybe the Cog icon icons can still stay one-click-to-display? Although "Flatten" is very commonly used feature and might benefit from being outside the cog icon.

**Comment by Findus23** [comment]
This could also help other settings in the gear menu (e.g. flat report) as they are quite hidden at the moment.

**Comment by atom-box** [comment]
Should this issue be labeled "Enhancement" ?

**Comment by atom-box** [comment]
_A user sent this._

Feedback:
Search icon is only available at the bottom, and not visible without mouse-overing, making the feature self-discovery quite difficult. It is ok to keep it hidden if present both on top + bottom

**Comment by mattab** [comment]
as there were quite a few issues with the same theme: https://github.com/matomo-org/matomo/issues/6362 https://github.com/matomo-org/matomo/issues/15873 https://github.com/matomo-org/matomo/issues/19669 https://github.com/matomo-org/matomo/issues/21147 https://github.com/matomo-org/matomo/issues/19355
i'll mark this as closed in favor of this issue: https://github.com/matomo-org/matomo/issues/19669
