### ISSUE TITLE
No Visitors shown in Brandenburg (state of Germany) on the Map

### ISSUE THREAD

**Issue by tobiaskurz** [matomo-org/matomo#15881]
The Map shows visitors in all states of Germany except of Brandenburg. Attached a Screenshot from the issue. You can see that the Report has 3 visitors from Brandenburg.
![Bildschirmfoto 2020-04-29 um 15 14 38](https://user-images.githubusercontent.com/64537237/80600192-5192f100-8a2c-11ea-95ab-5822c484c4c3.png)

**Comment by sgiehl** [comment]
Hi @tobiaskurz. Thanks for creating the issue. I will have a quick look if that is something we can easily fix, or if that is caused by the switch from FIPS to ISO codes.

**Comment by sgiehl** [comment]
@tobiaskurz seems the iso code is wrong in our svg map. If you want you can try to apply the changes in the linked pull request. It's basically simply replacing `data-name="Brandenburg" data-p="BE"` with `data-name="Brandenburg" data-p="BB"` in the file `plugins/UserCountryMap/svg/DEU.svg`

**Comment by tobiaskurz** [comment]
@sgiehl Thank You for the workaround wich was a full success

**Comment by sgiehl** [comment]
Thanks for the feedback. We will include the fix in the next release. Cheers.

**Comment by sgiehl** [comment]
Fixed with #15882
