### ISSUE TITLE
setReferrerUrl(String) not populating dashboard

### ISSUE THREAD

**Issue by Elaniobro** [matomo-org/matomo#15890]
Hello, I am using Matomo, within a Vue.js application. I am wanting to override the referrer url, with a specific value for tracking purposes.

I am doing the following:
```
const entryPoint = 'Unicorns Poop Sparkles'
this.$matomo.setReferrerUrl(entryPoint)
```
When sniffing the network traffic, I see the query parameter being set for urlref with the override I set:
`urlref "Unicorns Poop Sparkles"`

What I can not find, is where this value should show up for me in the dashboard… I assumed that I would be seeing the value in the “acquisition/All Channel” panel, but I do not see anything populated other than Direct Entry

I know that my code works since I use this: `this.$matomo.setCustomVariable(2, 'Role', provider.occupation, 'visit')`, and I DO see the custom variable I set `Role` being populated in the dashboard and according to the docs, both methods are for modifying the tracking object.

So is this a bug or just a lack of Matomo understanding on my part?

**Comment by tsteur** [comment]
@Elaniobro could you maybe send us a simple HTML page (ideally not using vue.js but the regular _paq tracking methods) so we can test things and reproduce your issue? 

Generally, the urlref should create a new visit if it is different to the value stored in the current visit AFAIK. And it should show up in the referrer report

**Comment by Elaniobro** [comment]
@tsteur thank you for your reply, but not sure if pushing a standard method with `_paq` will be of service, since I am using this in vue.js

>Generally, the urlref should create a new visit if it is different to the value stored in the current visit AFAIK. And it should show up in the referrer report

Where would this appear in the dashboard, because I do not see any mention of referrer in there.

**Comment by tsteur** [comment]
You should be seeing this in the Acquisitions report indeed. Any chance you are setting urlref to a domain that is also your site? Or is urlref from some external site? If it is the same domain, then it would be considered a direct visit maybe.

**Comment by eramirezprotec** [comment]
Using: 

`_paq.push(['setReferrerUrl', 'https://facebook.com']);`

before:

`_paq.push(['trackPageView', "Facebook"]);`

adds this param to the request:

`urlref: https://facebook.com`

But when I check the _id_action_url_ref_ column in the _piwik_log_link_visit_action_ table, I see the _id_ corresponding to the link specified in the request headers:

`Referer: http://localhost/diario/facebook.html`

I would expect to find an _id_ that matches to a register in the _piwik_log_action_ table, with the _name_ column having the value _https://facebook.com_. But this register doesn't even exist.

Matomo does not seem to be using the _urlref_ param specified in the request.

**Comment by sgiehl** [comment]
Closing as there hadn't been any further feedback. If someone still experiences problems around that feel free to reach our for help on our forum or create a new issue.
