### ISSUE TITLE
Grammar issue with GA phrase on landing page

### ISSUE THREAD

**Issue by dandv** [matomo-org/matomo#15899]
I can't figure out where to file this issue, and searching this repo for "This is where tools like Google Analytics becomes extremely limited and cashes in with their GA360 Premium suite" yields nothing, so I'm filing here.

The phrase appears at https://matomo.org, and doesn't quite make sense. Maybe a word is missing, like "...and *Google* cashes in"?

![image](https://user-images.githubusercontent.com/33569/80897618-adbc8480-8d4e-11ea-9b36-a03aa06ed018.png)

**Comment by tsteur** [comment]
Cheers @dandv very much appreciated. I think it was updated.
