### ISSUE TITLE
'Acquistion/Overview/Evolution over the period'   graph fails when adding more channels

### ISSUE THREAD

**Issue by truk70** [matomo-org/matomo#15892]
When I open the graph 'Evolution over the period' under Acquisition/Overview then by default I see the evolution of two entry (channel) types: 
* Direct Entry (Visits)
* Total (Visits)
When I now add one other channel 'Search Engines'
it still displays 
* Direct Entry (Visits)
* Search Engines (Visits)

When I add another channel 'Websites', The graphs fails and shows only a single flat line.
Furthermore the menu to select channels and switch between visits and actions looses alle channels to select from.
I have to reload the page to go back to the default view.

My environment: 
Server OS: Ubuntu 18.04 
Matomo: 3.13.5
Client OS: Ubuntu 18.04, Windows 10
Browser: Firefox (current), Chrome (current)

This error happens continuosly over several patch updates. First appearance was after a patch update in automn 2019.  
It can also easly be reproduced on demo.matomo.org/Acquisition/Overview by just selecting more than 2 channels/records to plot.

**Comment by tsteur** [comment]
Thanks for creating the issue @truk70  very appreciated. This is indeed a bug. Maybe a regression from the comparison feature (just a guess)

**Comment by mattab** [comment]
this issue has been reported a couple of other times.

**Comment by truk70** [comment]
> this issue has been reported a couple of other times.

Great! First it was filed for Milestone 4.2..
then postpone to 4.4 and 
now it was again postponed for 4.5

I don't think I will ever file a bug report again!

**Comment by geekdenz** [comment]
Hi @truk70, I'm having a look into this now. Please bear with us, keeping on top of a lot of issues coming in is challenging and normal/expected with software of this magnitude. Thank you again for logging this issue.

**Comment by geekdenz** [comment]
FYI, I was able to reproduce this in my development version.

**Comment by geekdenz** [comment]
It can be reproduced here also:

[Demo: Acquisition/Overview](https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=Referrers_Referrers&subcategory=General_Overview)
