### ISSUE TITLE
Switch to Events Not Working 

### ISSUE THREAD

**Issue by chandrakant-hake** [matomo-org/matomo#15906]
**Switch to Events is not Working**
It has 3 options 

- Switch to Event Action
- Switch to Event Name
- Switch to Event Category

**How To Reproduce Issue**

1. Select any Website which has some Event Data in it.
2. Go to Behaviour > Events
3. You will see Events and Event Categories Table
4. Click on **Switch to Event Name** which us at the bottom of that Event Categories table
5. After Click on that, It Doesn't Change Tables Data

**What is Expected Result**
When we click on Switch to Event Name the Table should appear to be like,
when we click on **'Event Name'** Which is on Left Side of That Category Table.

**Screenshots**

1. When We see Data
![event1](https://user-images.githubusercontent.com/64453914/80959673-e75fbf00-8e24-11ea-8431-59b1ba77705e.png)

2. After Click on That Data
![event2](https://user-images.githubusercontent.com/64453914/80959709-f9d9f880-8e24-11ea-9fbe-7c95be79873d.png)

3. The actual result was shown by clicking on left side menus
![event3](https://user-images.githubusercontent.com/64453914/80959729-052d2400-8e25-11ea-8c55-45ae8e35eece.png)

**Comment by tsteur** [comment]
@chandrakant-hake thanks for creating the issue. The link you are clicking actually changes the secondary dimension, not the report itself. So it changes which dimension is shown when you click on the plus icon next to an event category. For example

![image](https://user-images.githubusercontent.com/273120/81014030-44548700-8eb0-11ea-8016-7a169937c918.png)
