### ISSUE TITLE
Error after Updating - Your Matomo codebase is running the old version 3.13.4..

### ISSUE THREAD

**Issue by prazserendio** [matomo-org/matomo#15909]
Your Matomo codebase is running the **old version 3.13.4** and we have detected that your Matomo Database has already been upgraded to the **newer version 3.13.5.** 

And Style does not come on login page also.

Why is this happening..? Any fixes?

**Comment by Findus23** [comment]
Hi,

Make sure that all the Matomo files are from the latest version. When in doubt (e.g. if maybe the update got interrupted by a timeout), replace them with the ones from https://builds.matomo.org/.

**Comment by prazserendio** [comment]
Hi @Findus23 ,

Updated it and restarted the server also..
but, Still It shows the same error :

![image](https://user-images.githubusercontent.com/51264444/80995260-9d460000-8e5b-11ea-9a2c-a44f18ca24c1.png)

**Comment by Findus23** [comment]
You can check the `core/Version.php` version to see which version of the files you have. If it is not showing `3.13.5` then you need to replace the files.

**Comment by sgiehl** [comment]
Closing as there hadn't been further feedback. 
Note: This issue may occur when manually downgrading the code base, or if files weren't updated correctly during the update.
