### ISSUE TITLE
Automatically kill SQL queries after a few hours to prevent issues

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15903]
In some cases, the DB can get stuck running SQL queries forever that won't complete or will take more than 1 day. This causes multiple issues downstream like blocking report processing delays, and also results in complicated to troubleshoot issues.

By using a Mysql-provided setting (MySQL 5.7+ provides `max_execution_time` variable),  we can get all queries automatically killed if they take longer than X seconds. So if we set the value to say 8 hours, this would be a safe threshold as no query is expected to take longer than 1 hour or so...

**Comment by Findus23** [comment]
See also https://github.com/matomo-org/matomo/issues/15241

**Comment by tsteur** [comment]
Closing as a duplicate
