### ISSUE TITLE
Documentation: Tracking API region has outdated definition

### ISSUE THREAD

**Issue by ursNiemi** [matomo-org/matomo#15911]
In the documentation [Tracking HTTP API](https://developer.matomo.org/api-reference/tracking-api), it says: 
> region — An override value for the region. Should be set to the two letter region code as defined by MaxMind's GeoIP databases. See [here](https://www.maxmind.com/download/geoip/misc/region_codes.csv) for a list of them for every country (the region codes are located in the second column, to the left of the region name and to the right of the country code).

It seems that the regions Matomo currently uses are not from that outdated file by MaxMind, but instead they conform to **[ISO-3166-2 regional codes](https://en.wikipedia.org/wiki/ISO_3166-2)** (e.g. 19 regions for Finland, not the 5 in the MaxMind list). 

The Matomo map cannot handle this information ([separate issue](https://github.com/matomo-org/matomo/issues/11929)), but with the standard ISO codes, visitor Region is set correctly at least in Finland.

**Comment by sgiehl** [comment]
Hi @ursNiemi. Thanks for letting us know. Seems we forgot to update the documentation when we implemented GeoIP2. At that point we switched from using the old Maxmind FIPS codes to ISO codes.
