### ISSUE TITLE
API Result changes after Matomo Upgrade from 3.8.1 to 3.13.2 or 3.13.5

### ISSUE THREAD

**Issue by sandeepdixit2020** [matomo-org/matomo#15912]
API  at Matomo Version 3.8.1 For which result changes after Matomo version upgrade. 

/index.php?module=API&method=Events.getName&secondaryDimension=eventCategory &idSite=6&period=day&date=2020-04-23 &token_auth=XX&filter_limit=-1 &flat=1&segment=dimension6==2020DecorativeItemsUS2020

 (at Matomo Version 3.8.1 Segment working as expected)

Upgrade to 3.13.2 (or 3.13.5) and invalidateArchivedReports for 2020-04-23 

**Above API now returns different results. We can see that data that is not from segment=dimension6==2020DecorativeItemsUS2020**

Because all of our API segment by dimension6, it's a big issue for us.
API Results before after update, Screenshots ,visit logs attached. dimension6 is catalog code on Matomo UI.

**please note that we created one environment, from backup of 3.8.1 just to verify this issue, as this is very critical problem for us.**
We did not change any configuration in between on upgrades. We have been able to reproduce this scenario many times. 

dimension6 is named catalogCode on Piwik UI.

**API response before Update. Screent shot of UI report and API result as xml.**

[response_Before_MatomoUpgrade.xml.txt](https://github.com/matomo-org/matomo/files/4579977/response_Before_MatomoUpgrade.xml.txt)
![Event Names 3 8 1](https://user-images.githubusercontent.com/64210279/81053656-0de42f80-8ee3-11ea-996c-f13d14a72154.PNG)

**API response after Update. Screent shot of UI report and API result as xml.**

[Response_After_Matomo_Upgrade.xml.txt](https://github.com/matomo-org/matomo/files/4579982/Response_After_Matomo_Upgrade.xml.txt)

![Event Names 3 132](https://user-images.githubusercontent.com/64210279/81053657-0de42f80-8ee3-11ea-9b54-7162aca38d20.PNG)

**Other important data to help debugging**

![VisitLog 1](https://user-images.githubusercontent.com/64210279/81053641-0a50a880-8ee3-11ea-8a24-9684e83f5291.png)
![VisitLog Part 2](https://user-images.githubusercontent.com/64210279/81053646-0b81d580-8ee3-11ea-83f2-2db35c339a42.png)

![VisitLog3_Showing DimentionValueToFilter](https://user-images.githubusercontent.com/64210279/81053654-0d4b9900-8ee3-11ea-86f0-79e97a02caf2.png)
[VisitLog_2020_04_23_Full.xml.txt](https://github.com/matomo-org/matomo/files/4579980/VisitLog_2020_04_23_Full.xml.txt)
[VisitLog_2020_04_23_Segmented.xml.txt](https://github.com/matomo-org/matomo/files/4579981/VisitLog_2020_04_23_Segmented.xml.txt)

**Comment by tsteur** [comment]
Hi @sandeepdixit2020 this is due to https://github.com/matomo-org/matomo/issues/11900 and now expected behaviour change as it actually was buggy initially (I totally understand some users like you prefer and expect the other behaviour how it used to work, sorry about that). Here's a workaround: https://github.com/matomo-org/matomo/issues/15130#issuecomment-551252343

the feature you are likely looking for are "filters" and we have an issue for this here: https://github.com/matomo-org/matomo/issues/15438
