### ISSUE TITLE
Old link to matomo docs about search keywords in web ui

### ISSUE THREAD

**Issue by dmitrymspektr** [matomo-org/matomo#15918]
In the WebUI of latest (3.13.5.) matomo, at Project / Sources / Keywords at the tip about google search console integration, wrong litk to matomo docs located:
Link address: https://matomo.org/recommends/search-keywords-performance/ (404 code)
Actual address needed: https://matomo.org/docs/search-engine-keywords-performance/ 

See screenshot:
![2020-05-07_00-56-58](https://user-images.githubusercontent.com/5102558/81233259-fd28dc00-8ffe-11ea-8ba4-ef1b72075d0f.png)

**Comment by tsteur** [comment]
Thanks a lot @dmitrymspektr updated the link
