### ISSUE TITLE
Announce LTS for Matomo 3

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#15920]
It would be ideal to update this existing article, and URL (+redirect the old one to the new one): https://matomo.org/blog/2016/01/announcing-long-term-support-in-piwik-2-the-analytics-platform-for-your-mission-critical-projects/

**Comment by mattab** [comment]
we might rename https://matomo.org/blog/2016/01/announcing-long-term-support-in-piwik-2-the-analytics-platform-for-your-mission-critical-projects/ and make it more generic, and redirect the old URL to a new one. So it is valid for all future major releases.

**Comment by tsteur** [comment]
This is done. URL: https://matomo.org/blog/2016/01/announcing-long-term-support-in-matomo-the-analytics-platform-for-your-mission-critical-projects/

comes up also first in our search when searching eg for "LTS" or "long term support"

**Comment by Findus23** [comment]
Maybe we should move this from the blog to the docs as the 2016/01/ makes it look like it is outdated.
