### ISSUE TITLE
[DX] after fresh installation, dashboard is set to yesterday and shows no data

### ISSUE THREAD

**Issue by dbu** [matomo-org/matomo#15928]
on a fresh installation, there is no data (obviously). once i had my website configured to send events, i started seeing requests in the "real-time" widget and was happy. 

but the visits overview or actions widgets showed "no data". i ran the core:archive command and it did stuff, but still no information. i started digging for what the cause for this could be. i was about to give up and look for alternatives to matomo when i realized that at the top, there is a date selector, and by default it seems to be set to "yesterday".

i guess this is "obvious" to experienced matomo users, and once a site is actively being tracked, the default makes sense. however, i think it would help new users if there was something to prevent this. maybe detect a fresh installation and default to today when there is no data yet, or show a flash message with that hint when the only data that exists is about today...

**Comment by sgiehl** [comment]
Hi @dbu. Thanks for creating the issue. You are right, it's a bit weird for someone who is not familar with Matomo, to not directly see anything after the installation even if something has already been tracked. We have already spent some thoughts on that topic and I guess that would be kind of solved with https://github.com/matomo-org/matomo/issues/13754

**Comment by dbu** [comment]
yep, i basically created a duplicate of #13754 with this. will close this issue.
