### ISSUE TITLE
Search engines are displayed in the wrong channel type

### ISSUE THREAD

**Issue by PeteTrombone** [matomo-org/matomo#15923]
Search engine websites are displayed under the channel type "Websites".

![image](https://user-images.githubusercontent.com/57910876/81308684-5a19a600-9082-11ea-9546-43fd22bf9002.png)

In addition, there are also entries of the search engines under the channel type "Search Engines". However, these are completely different values.

![image](https://user-images.githubusercontent.com/57910876/81308923-a6fd7c80-9082-11ea-8c00-42c667d4d1d1.png)

When I look at the tracking data of the last years in Matomo, it always looks the same as above.

**Comment by tsteur** [comment]
Thanks for reporting this issue @PeteTrombone 

I can't really reproduce this just yet unfortunately. Is there any chance you could create an account for us with view access in your Matomo (email hello at matomo.org) so we can maybe look a bit more into the data?

**Comment by PeteTrombone** [comment]
@tsteur you have received a mail from me (Jörg Zipf).

**Comment by tsteur** [comment]
Thanks @PeteTrombone I've had a look but couldn't quite understand just yet how this would possibly happen. I've tried to reproduce using the same referrer url but always works here.

Any chance there are third party plugins activated? You can find out by going to
"Admin => Plugins". There you can filter by "Third party":

![image](https://user-images.githubusercontent.com/273120/81510473-018a2780-9366-11ea-85c1-82662e9a167b.png)

I suppose you are using the JavaScript tracker to track visits?

**Comment by PeteTrombone** [comment]
@tsteur yes, we using the JavaScript tracker with the standard tracking code.

We have no third party plugins installed.

![image](https://user-images.githubusercontent.com/57910876/81541601-a2cbaa80-9373-11ea-9d43-d6f23656c47c.png)

Here is the list of inactive plugins. Is that ok?
![image](https://user-images.githubusercontent.com/57910876/81542063-5a60bc80-9374-11ea-8cb6-31d0d6619991.png)

**Comment by tsteur** [comment]
Thanks @PeteTrombone that looks all good.

I've been trying to reproduce a bit more but cannot. Also not seeing this issue in any of our other installations. So far I would only be able to explain this if 

* the file `$matomoDir/vendor/matomo/searchengine-and-social-list/SearchEngines.yml` is missing or incomplete
* Or if the search engine definitions in the database is incomplete / 


In case you have access to the database: Can you check if you get a result when executing this SQL query:

```
select FROM_BASE64(option_value) from `matomo_option` where option_name = 'SearchEngineDefinitions'
```

The table name for `matomo_option` might also be eg `piwik_option` or something similar depending on the configured database table prefix. Could you maybe send us the content of that result by email? Then we could check if it looks all good.

You might also want to check if as a fallback the above mentioned file exists (but I don't think that's the issue here)

**Comment by tsteur** [comment]
I can reproduce this with this patch https://gist.github.com/tsteur/e07343f251eb630cd87bec4bc80fbf54

@PeteTrombone it seems like the information in the option table is a bit outdated. Is it possible that the setting `General['enable_internet_features']` in `config.ini.php` is disabled?

If the server has a connection to the internet, then it should be possible to update this list and fix this issue by executing this command within the Matomo directory on the server directly:

```
./console core:run-scheduled-tasks  --force "Piwik\Plugins\Referrers\Tasks.updateSearchEngines"
```

To fix the issue in general maybe when we update Matomo, we should generally execute `Option::delete(SearchEngine::OPTION_STORAGE_NAME)`. This way we would make sure that if you suddenly disable internet settings, the latest version will be used. It won't fix it though when there isn't an update for a while so we could just ignore any value in the options table when internet is enabled.

**Comment by PeteTrombone** [comment]
@tsteur yes, the settting is disabled for security reasons.
Is there a way to do this offline? Is it possible to download and exchange a file?

**Comment by tsteur** [comment]
@PeteTrombone do fix the issue I recommend to delete the above mentioned option entry by executing this SQL query:

```sql
delete from `matomo_option` where option_name = 'SearchEngineDefinitions'
```

Alternatively, executing the command described in https://github.com/matomo-org/matomo/issues/15923#issuecomment-628311000 should fix it too. We've already worked on a patch to fix the issue in general in the future as part of Matomo 4.
