### ISSUE TITLE
core/Common.php(297): Notice - unserialize(): Error at offset 0 of XXXX bytes - Matomo 3.13.5

### ISSUE THREAD

**Issue by digihiveinc** [matomo-org/matomo#15925]
Since the upgrade to Matomo 3.13.5 problem running archiving
`/console core:archive --url=https://mywebsite.com/ > /[DIRECTORIES]/logs/matomo-archive.log`

Partial log:

> INFO [2020-05-08 22:42:41] 16938  ---------------------------
> INFO [2020-05-08 22:42:41] 16938  START
> INFO [2020-05-08 22:42:41] 16938  Starting Matomo reports archiving...
> INFO [2020-05-08 22:42:41] 16938  Day has finished for website id 1, 7, 8, 9, 10,  since last run
> INFO [2020-05-08 22:42:41] 16938  Will pre-process for website id = 1, period = day, date = last2
> INFO [2020-05-08 22:42:41] 16938  - pre-processing all visits
> WARNING [2020-05-08 22:42:42] 16938  [DIRECTORIES]/core/Common.php(297): Notice - unserialize(): Error at offset 0 of 7757 bytes - Matomo 3.13.5 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
> INFO [2020-05-08 22:42:42] 16938  Day has finished for website id 2 since last run
> INFO [2020-05-08 22:42:42] 16938  Will pre-process for website id = 2, period = day, date = last2
> INFO [2020-05-08 22:42:42] 16938  - pre-processing all visits
> WARNING [2020-05-08 22:42:42] 16938  [DIRECTORIES]/core/Common.php(297): Notice - unserialize(): Error at offset 0 of 3570 bytes - Matomo 3.13.5 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
> INFO [2020-05-08 22:42:43] 16938  Day has finished for website id 4 since last run
> INFO [2020-05-08 22:42:43] 16938  Will pre-process for website id = 4, period = day, date = last2
> INFO [2020-05-08 22:42:43] 16938  - pre-processing all visits
> ...

already checked the previous fixes reported.
PHP 7.2.13

**Comment by Findus23** [comment]
Hi,

The error message just means that Matomo tries to make a request to it's API and gets something back that is not a valid response. To know why it doesn't work, you need to know why this request fails and what the error is that it returns. 
To do this please check your PHP error log.

**Comment by tsteur** [comment]
@digihiveinc thanks for creating the issue. There seems to be indeed some error happening and it be great to check for example your logs. I'll close this issue for now and it be great to report above message in the forum https://forum.matomo.org/ as mentioned in the description as we only handle bug reports and feature requests here but this is usually a server configuration issue for example. If you find anything in the logs that points to a bug we'll be happy to have a look and create an issue here in the issue tracker.
