### ISSUE TITLE
WhiteLabel Plugin tracker.js file not created in js folder but tracker.php is created

### ISSUE THREAD

**Issue by prazserendio** [matomo-org/matomo#15922]

**Comment by prazserendio** [comment]
**WhiteLabel Plugin (Premium)**

WhiteLabel Plugin tracker.js file not created in js folder but tracker.php is created

Enabled the **Whitelable tracking end point**

**Note from plugin :**
If enabled, "piwik.js" and "piwik.php" will be replaced by "js/tracker.js" and "js/tracker.php" in the tracking code generator and also when requesting the tracking code via the API. When enabling this feature, it is recommended to test that your server allows requests to eg "https://xyz/js/tracker.php"

But, WhiteLabel Plugin tracker.js file not created in js folder but tracker.php is created

**Comment by tsteur** [comment]
Thanks for creating the issue @prazserendio . Could you email our support about this please? The email is shop at innocraft.com
Thanks
