### ISSUE TITLE
Custom Report metric "Unique User IDs" shows visits not unique users

### ISSUE THREAD

**Issue by sandeepdixit2020** [matomo-org/matomo#15921]
We are using Custom Reports plugin. We want have unique user against each row. So we used "Unique User IDs" metric. However, it does not appear to be working.   One row is showing a number more than total users for the segment. After looking at segmented logs we see 5 visits by 2 users (unique IDs is just 2). Please help.

![UniqueUserIDs](https://user-images.githubusercontent.com/64210279/81299227-8853b180-9093-11ea-869a-67e8fa63e767.PNG)

**Comment by tsteur** [comment]
Thanks @sandeepdixit2020 

Could you email our support about this: shop at innocraft.com

We're only managing issues for Matomo core in this issue tracker.
