### ISSUE TITLE
Matomo import logs multithreading and skip parameter

### ISSUE THREAD

**Issue by dimitrispie** [matomo-org/matomo#15936]
Hi,
I have a question regarding the Recorders and skip parameters in the import logs script.
Let assume that I use, 2 recorders, i.e two threads, for example:

t_1 has hits from [0,100]
t_2 has hits from [101,200]

and t_1 fails to record the hits, but t_2 succeeds. 
If I use the --skip=0 parameter, it might lead to double imports. Is this a correct assumption?

**Comment by tsteur** [comment]
Hi @dimitrispie unfortunately we don't answer questions in our issue tracker as we're only handling bug reports and feature requests here. Could you maybe post your question in our forum? https://forum.matomo.org/ Sorry about the inconvenience.
