### ISSUE TITLE
Baidu not considered as a search engine?

### ISSUE THREAD

**Issue by angristan** [matomo-org/matomo#15937]
Matomo version: 3.13.5

I have some visitors from China that come from Baidu:

<img width="530" alt="screenshot_2020-05-11_11-58-53@2x" src="https://user-images.githubusercontent.com/11699655/81549398-f263a380-937e-11ea-855f-b73492987af2.png">

However it does not appear in the list of search engines:

<img width="408" alt="screenshot_2020-05-11_11-59-22@2x" src="https://user-images.githubusercontent.com/11699655/81549405-f8f21b00-937e-11ea-9cf4-6aaf1076c0ac.png">

Is this expected? I tried so search in existing issues/PRs but couldn't find anything.

**Comment by sgiehl** [comment]
Hi @angristan. Thanks for letting us know. I've just checked that and it seems we are not detecting baidu.com  (without any subdomain). Maybe baidu changed their default domain. IIRC it was www.baidu.com before. I'll adjust the detections for that so it will be detected correctly in the future.

**Comment by angristan** [comment]
Awesome, thanks!

**Comment by Findus23** [comment]
Interestingly for me baidu.com redirects to www.baidu.com, but this might be different for Chinese users who might see a completly different website.
