### ISSUE TITLE
Deactivating Overlay Plugin Causes Error to Display on Behavior -> Pages

### ISSUE THREAD

**Issue by mddvul22** [matomo-org/matomo#15944]
With the Overlay plugin enabled in 3.13.5, when a Matomo user goes to Behavior -> Pages, they get an overlay icon.  When one hovers over the icon with their mouse, they see the following information:

![image](https://user-images.githubusercontent.com/6833993/81740023-e8ff3780-9461-11ea-8e76-5115ef65ce94.png)

However, in our environment, we can't make use of the Overlay plugin (we use the X-FRAME-OPTIONS  header set to SAMEORIGIN), and we don't use the javascript tracker -- choosing to import apache logs.  Therefore, I'd prefer to disable the Overlay plugin, to prevent our customers from trying (and failing) to use it.

But when I deactivate the Overlay plugin, the Overlay icon doesn't go away.  It remains.  When hovering over the icon, it shows the following error that is even more problematic that leaving it enabled and not usable:

![image](https://user-images.githubusercontent.com/6833993/81740324-6cb92400-9462-11ea-8c07-bfa0011e078f.png)

It seems to me that disabling the Overlay plugin should remove the Overlay icon, entirely.

Thanks!

**Comment by tsteur** [comment]
@mddvul22 I just tried to reproduce this but couldn't. Any chance you can clear the cache on your Matomo instance eg by executing `./console cache:clear` in your Matomo directory in your server directly or my deleting the `$matomoDir/tmp/assets` directory?

**Comment by mddvul22** [comment]
That seems to have solved it. Thanks!

**Comment by tsteur** [comment]
Awesome. Thanks for letting us know @mddvul22
