### ISSUE TITLE
Matomo does not display data in some pages

### ISSUE THREAD

**Issue by subasri1997** [matomo-org/matomo#15943]
Hi, I am using an updated matomo version 3.13.5. I am having data's in the database for that particular date range but, in Matomo some of the pages like visitors->overview does not show any data.I have changed the date in the filter and checked.Even in the All websites Dashboard, the total no of visits is pageview is displayed as 0. Thanks in advance

**Comment by tsteur** [comment]
@subasri1997 thanks for creating this issue. Do you mind posting this question in our forum? https://forum.matomo.org/ . We're only handling bug reports and feature requests here. In this case it's likely some server issue. We'll be happy to create a bug issue here should there be a bug as part of the forum post.

For the forum post it may be good to check under "Admin -> General Settings" whether Browser archiving is enabled or disabled. In case it is disabled, you want to check that the cronjob that is supposed to archive is set up correctly.

It be great to also mention if you see some reports but not visits overview. Whether it ever worked and suddenly stopped working.

And ideally, if you can, it might be good to check your server or PHP error log if there is anything showing up. 

Thanks for your understanding and apologies for the inconvenience
