### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by G4Zz0L1** [matomo-org/matomo#15947]
I think there's something wrong with the permission checks that matomo is doing here.
I've everything on http:http, with proper 755 on every folders and 644 on every files (like every other virtualhost that normally works on this server).
So, apache can read/write everything as it should be.
Php-fpm also runs on http user, so it shouldn't be a problem.

![image](https://user-images.githubusercontent.com/13220636/81758176-542c2680-94c1-11ea-96e8-5f72832d12a4.png)

The strange part are the following warnings (sorry for the locale).
I can't understand why it can't write on those folders or wrongly report permissions on those files.

![image](https://user-images.githubusercontent.com/13220636/81758115-352d9480-94c1-11ea-9d2c-8da4c3c78a48.png)
![image](https://user-images.githubusercontent.com/13220636/81758241-77ef6c80-94c1-11ea-9abd-202cf7013d59.png)
![image](https://user-images.githubusercontent.com/13220636/81758287-9a818580-94c1-11ea-96ff-38e717847d52.png)
![image](https://user-images.githubusercontent.com/13220636/81758291-a0776680-94c1-11ea-85a7-33e1f4903195.png)

**Comment by tsteur** [comment]
Hi @G4Zz0L1 what are the permissions on the symlinked directories?

**Comment by G4Zz0L1** [comment]
Actually I've found out that the culprit it's the update to PHP 7.4.
The main cause it's the option `ProtectSystem` of systemd, which cause the folders to go read-only.
ref: https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Sandboxing
I think we can close this, sorry for the trouble.

**Comment by tsteur** [comment]
Glad you found out what the culprit was and thanks for letting us know about this @G4Zz0L1
