### ISSUE TITLE
Can't download the new upgrade

### ISSUE THREAD

**Issue by fulcri** [matomo-org/matomo#15949]
Hello I'm trying to download the new uprgade from the url you provided us by email but receive the error in attached while I'm trying to log in (error: session is expired) 
Also, if I log in on the Matomo website and them go to the upgrade session, it asks me to log in again and receive always the same error.

would you please check it out?
thanks
nicolò
![2020-05-13_105143](https://user-images.githubusercontent.com/60960746/81792995-12bf6980-9509-11ea-8f14-76ee8ec39b81.jpg)

**Comment by tsteur** [comment]
@fulcri sorry about the trouble. Are you able to log in at all? Or are you always getting this error? Were you able to start the upgrade maybe but weren't able to finish it?

It might help to test it in a different browser, to clear cookies, or to try it in incognito mode.

**Comment by fulcri** [comment]
Hello, been trying on different website, same situation
I can login on the homepage but then when I go to the upgrade page this error appears!

**Comment by tsteur** [comment]
@fulcri could you maybe also try a different browser? When you say you can log in to the homepage you mean you can log in and see the Matomo reporting dashboard? 

If you can, it might help to perform the manual update see https://matomo.org/docs/update/#the-manual-three-step-update

**Comment by sgiehl** [comment]
Closing as there hadn't been any further comments in a long time. Assuming this issue doesn't exist anymore. If anyone still experiences this, feel free to create a new report. Thanks.
