### ISSUE TITLE
mtr matomo.org is fail ...

### ISSUE THREAD

**Issue by cnken** [matomo-org/matomo#15959]
The server cannot link matomo.org and IP185.31.40.177, so the background is very stuttered, and some functions cannot be used.

![image](https://user-images.githubusercontent.com/11863563/82153351-7fd05780-9899-11ea-9042-9959572484bd.png)

![image](https://user-images.githubusercontent.com/11863563/82153360-8a8aec80-9899-11ea-8360-fd82465ac3d7.png)

**Comment by Findus23** [comment]
Hi,

matomo.org is up for me. 
```
➜  ~ traceroute matomo.org
traceroute to matomo.org (185.31.40.177), 30 hops max, 60 byte packets
 1  172.31.1.1 (172.31.1.1)  0.111 ms  0.067 ms  0.048 ms
 2  11001.your-cloud.host (159.69.96.3)  0.107 ms  0.084 ms  0.124 ms
 3  * * *
 4  spine1.cloud2.fsn1.hetzner.com (213.239.225.41)  0.850 ms spine2.cloud2.fsn1.hetzner.com (213.239.225.45)  0.828 ms  0.809 ms
 5  core24.fsn1.hetzner.com (213.239.239.129)  3.968 ms * core24.fsn1.hetzner.com (213.239.239.133)  0.508 ms
 6  core4.fra.hetzner.com (213.239.203.149)  7.426 ms core4.fra.hetzner.com (213.239.229.73)  5.086 ms core0.fra.hetzner.com (213.239.252.37)  4.856 ms
 7  decix.ielo.net (80.81.194.184)  5.190 ms  5.138 ms  5.099 ms
 8  * * *
 9  6k-1-v407-sfr-strasbourg.infr.liazo.net (178.20.49.249)  14.344 ms  14.364 ms  14.406 ms
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  alwaysdata.customers-eqx-pa3.fr.rt.ielo.net (212.85.149.34)  14.077 ms  14.027 ms  13.954 ms
16  piwik.alwaysdata.net (185.31.40.177)  14.170 ms  14.154 ms  14.137 ms
```

**Comment by cnken** [comment]
> Hi,
> 
> matomo.org is up for me.
> 
> ```
> ➜  ~ traceroute matomo.org
> traceroute to matomo.org (185.31.40.177), 30 hops max, 60 byte packets
>  1  172.31.1.1 (172.31.1.1)  0.111 ms  0.067 ms  0.048 ms
>  2  11001.your-cloud.host (159.69.96.3)  0.107 ms  0.084 ms  0.124 ms
>  3  * * *
>  4  spine1.cloud2.fsn1.hetzner.com (213.239.225.41)  0.850 ms spine2.cloud2.fsn1.hetzner.com (213.239.225.45)  0.828 ms  0.809 ms
>  5  core24.fsn1.hetzner.com (213.239.239.129)  3.968 ms * core24.fsn1.hetzner.com (213.239.239.133)  0.508 ms
>  6  core4.fra.hetzner.com (213.239.203.149)  7.426 ms core4.fra.hetzner.com (213.239.229.73)  5.086 ms core0.fra.hetzner.com (213.239.252.37)  4.856 ms
>  7  decix.ielo.net (80.81.194.184)  5.190 ms  5.138 ms  5.099 ms
>  8  * * *
>  9  6k-1-v407-sfr-strasbourg.infr.liazo.net (178.20.49.249)  14.344 ms  14.364 ms  14.406 ms
> 10  * * *
> 11  * * *
> 12  * * *
> 13  * * *
> 14  * * *
> 15  alwaysdata.customers-eqx-pa3.fr.rt.ielo.net (212.85.149.34)  14.077 ms  14.027 ms  13.954 ms
> 16  piwik.alwaysdata.net (185.31.40.177)  14.170 ms  14.154 ms  14.137 ms
> ```

My server IP segment is inaccessible matomo.org

**Comment by mattab** [comment]
What is your server IP?

**Comment by cnken** [comment]
> What is your server IP?

192.161.81.1-255

This IP segment..

**Comment by tsteur** [comment]
Quickly checked our firewall but doesn't look like the IP is blocked or banned there. I don't know how these things work, is that an issue with cogent?

**Comment by heurteph-ei** [comment]
As user didn't give feedback for more than 2 years, and there is a way to bypass (https://matomo.org/faq/troubleshooting/faq_16646/), I think this can be closed, now
