### ISSUE TITLE
I Have A Problem With [JavaScript Tracking] 

### ISSUE THREAD

**Issue by Lijiaqi1992** [matomo-org/matomo#15967]
I use this code to set my web, 
like 
` _paq.push(['setCustomVariable','3','u3','3']);`.
But it not always effective.
This is my Mysql data
![image](https://user-images.githubusercontent.com/52096822/82546833-59593780-9b8b-11ea-852d-f97cc3a2ba66.png)
And it also not in table:matomo_log_link_visit_action 
Why? Please me where is the problem?

**Comment by Findus23** [comment]
Hi,

Did you check if the data is included in the request to matomo.php? Also make sure the variable is set before the page view is tracked.

**Comment by Lijiaqi1992** [comment]
> Hi,
> 
> Did you check if the data is included in the request to matomo.php? Also make sure the variable is set before the page view is tracked.

Yes,Thanks!
I changed the code ` _paq.push(['trackPageView']);` under the code ` _paq.push(['setCustomVariable',1,'mykey','myval']);` .  It work now!
How can I avoid such things happening again?

**Comment by tsteur** [comment]
Glad it works now @Lijiaqi1992 

The only way to avoid such things is testing any tracking changes work as expected unfortunately. So whenever you're wanting to set new custom variables make sure to test them and check that you're afterwards getting the data in the reports as expected.
