### ISSUE TITLE
Guzzle 3 is deprecated (composer dependency warnings)

### ISSUE THREAD

**Issue by tassoman** [matomo-org/matomo#15961]
I've cloned this repository but I got two deprecation warnings:

> Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
> guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)

Then I got another deprecation warning:

> Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.

**Comment by tassoman** [comment]
Ok. I sorted out this issue can be a duplicate of #11318 and #9531 

I've digged in, also. Discovering a [pretty fresh feedback from aws developers](https://github.com/aws/aws-sdk-php/issues/1968#issuecomment-629553361).

Maybe this problem with Guzzle promises can be solved somehow in Matomo project?

**Comment by sgiehl** [comment]
Did you install with development dependencies? the aws package is development only

**Comment by Findus23** [comment]
@sgiehl Do you know what `aws/aws-sdk-php` is used for? I think only https://github.com/matomo-org/matomo/tree/4.x-dev/plugins/TestRunner/Aws uses it which I don't think anyone uses anymore.
So maybe we could remove it with Matomo 4 or at least update the package to the latest version.

**Comment by tassoman** [comment]
@sgiehl I ran `composer install` then enabled `php console development:enable`

**Comment by sgiehl** [comment]
@tassoman  guzzle has been removed with #15962
Removing/Updating container-interop won't be that easy as we need to update php-di for that, which needs some more changes...

**Comment by tassoman** [comment]
Thank you, good shot!
Would you like I file another issue splitting the two dependencies or we just fade out this issue?

I've digged into the _container-interop_ deprecation and I discovered [is about merging into PSR-11](https://github.com/container-interop/container-interop).

**Comment by sgiehl** [comment]
already tried updating php-di on a [new branch](https://github.com/matomo-org/matomo/compare/phpdi?expand=1), but tests are failing and there are some issues with having references in functions defined in configuration like here https://github.com/matomo-org/matomo/blob/0187b71729484a9f173d978239ff0a3cb37a5d7b/config/environment/test.php#L101

Don't have time to dig deeper into that right now. Feel free to simply rename this issue or create a new one for updating `php-di`

**Comment by tsteur** [comment]
Be indeed good to create a new issue for the other one and we close this one.

We'll see when we look into the other one as it might not have highest priority right now while working on Matomo 4.

Thanks for bringing this up @tassoman

**Comment by Findus23** [comment]
Created https://github.com/matomo-org/matomo/issues/15974 for this.
