### ISSUE TITLE
Real-time visitors live widget don't refresh after live_widget_refresh_after_seconds "timed out" without new visits/actions on websites

### ISSUE THREAD

**Issue by helifrank** [matomo-org/matomo#15978]
The real-time visitors live widget seems not to be fully recovered since Matomo 3.10.0 (possible with fix https://github.com/matomo-org/matomo/issues/14374).

After live_widget_refresh_after_seconds period "timed out" without any new visits/actions, the widget doesn't refresh anymore.

Only after a browser tab change or page refresh new visitors/actions during the live_widget_refresh_after_seconds period refreshing correctly in the real-time live widget, until the live_widget_refresh_after_seconds “timed out” again.

The live_widget_refresh_after_seconds period "timed out" without new visitors/actions.

I can reproduce this behavior since Matomo 3.10.0 with a clean installation, in my case on macOS with Safari and Chrome.

New visitors/actions on website during the default 5s interval (after viewing Matomo dashboard) are viewing/refreshing correctly. After no visitors/actions, e.g. for 20s, the widget doesn't refresh anymore (until a browser tab change or page refresh).

**Comment by tsteur** [comment]
You mean in this case there was actually no single visitor in the last 24 hours for example and then you had to reload?

**Comment by helifrank** [comment]
Thanks for your response @tsteur 
I mean, that I have to reload or tab change, after live_widget_refresh_after_seconds (default 5 seconds) with no single visitor.
After a dashboard or widget refresh and visitors/clicks within less 5 seconds intervals, the widget updates the visitors actions, so long as visitor click within the interval again and again. After - for example - 20 seconds with no visitors, the widget updates not anymore new visits/actions.
With customized live_widget_refresh_after_seconds (for example 10 seconds) visitors actions is necessary within less 10 seconds that widget live updates works.

**Comment by tsteur** [comment]
Thanks @helifrank  I was able to reproduce this. Created a fix for this in https://github.com/matomo-org/matomo/pull/15987

**Comment by helifrank** [comment]
Thanks @tsteur. It works! :-)
