### ISSUE TITLE
Error 504 to access to Matomo

### ISSUE THREAD

**Issue by jeremiecourlivant** [matomo-org/matomo#15984]
Hello,

I have Matomo for some sites. Today, I can't conect to matomo, there is a infinity load and fail two or three minutes later with an error 504. 

There was 4471 visits in last 2 days according to the archive comand. The installation is quite old, when I intalled it, the name of the application was Piwik.  There are space in the db, 3 go of free space, 4 go in total. The db contain also joomla and wordpress tables. I'm on a mutualized server on OVH ([performance 1](https://www.ovh.co.uk/web-hosting/performance-web-hosting.xml)).

The error is in all pages when I'm logged. If I am not, the page of connection works. I have access to ssh (but with many restriction) and the console works,

I manually update Matomo to the last version and I update the database, the page to update worked.
I deleted the files indicated by the diagnostic. In the diagnostic, there are two warning :

Max Packet Size: WARNING It is recommended to configure a 'max_allowed_packet' size in your MySQL database of at least 64MB. Configured is currently 32MB.
Forced SSL Connection: WARNING We recommend using Matomo over secure SSL connections only. To prevent insecure access over http, add force_ssl = 1 to the General section in your Matomo config/config.ini.php file.

Then I made : 
console core:clear-caches
console core:purge-old-archive-data
console core:archive

I can't make console log:watch, there is no file.

So, what's the problem ?

Thanks

**Comment by tsteur** [comment]
Hi @jeremiecourlivant 

a 504 error looks like some server related issue and not a Matomo issue. Maybe get in touch with your sys admin or with your hoster OVH to see if they can help you. Eg maybe there's something off with a virtual host configuration or so.

I just checked and it looks like Matomo doesn't trigger any 504 errors. I'll close this issue for now and as mentioned I recommend you get in touch with OVH. I'm more than happy to reopen should there actually be an issue in Matomo. I quickly searched for "OVH HTTP 504" and some results come up as well that might help.

Hope they can help you and apologies we can't help more in this regard.
