### ISSUE TITLE
Create index without downtime | TRANSITIONS

### ISSUE THREAD

**Issue by tpimpao** [matomo-org/matomo#16014]
Hi, 
I have a requirement to make the transitions feature work faster. 
Checking the Matomo FAQ pages, i find that i need to add 3 index. 

https://matomo.org/faq/how-to/faq_161/

The challenge is try to add the indexes without downtime, any advice? 

The tables sizes:
![image](https://user-images.githubusercontent.com/26350588/83614928-c6060600-a57d-11ea-9e9c-0d49b8a3658f.png)

**Comment by tsteur** [comment]
@tpimpao as this is a general question could you please ask this in the forum? https://forum.matomo.org/ We only handle bug requests and feature requests in the issue tracker.

I recommend you there also mention your MySQL version etc as the answer might depend on this (eg does it support online updates or not). A search in your favourite search engine for adding indexes without downtime might help too.
