### ISSUE TITLE
Matomo 3.13.6 required at least PHP 7.2

### ISSUE THREAD

**Issue by Globulopolis** [matomo-org/matomo#16021]
I cannot understand why this happens?

![Clipboard01](https://user-images.githubusercontent.com/740757/83846164-dbf8ff80-a712-11ea-86d5-73dc4119e8b0.jpg)

On https://matomo.org/docs/requirements/ I see `PHP version 5.5.9 or greater`

PS! PHP 5.6.40

**Comment by sgiehl** [comment]
Hi @Globulopolis. Matomo 3.13.6 still works with PHP 5.5. We will increase the requirement to PHP 7.2.5 with the release of Matomo 4. You already see the warning message so you are aware the next major release (Matomo 4) won't run on that system.
Did you hit the `check for updates` button?

**Comment by tsteur** [comment]
@Globulopolis don't worry you'll still be able to receive updates for Matomo 3. As @sgiehl mentions the requirement will be only for upgrading to Matomo 4.

**Comment by Globulopolis** [comment]
Oh, sorry, maybe my fault, or something with caching.
