### ISSUE TITLE
Get all our plugins and premium plugins to pass w/ updated frontend libs

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#16031]
Follow up for #14082

We probably want to start with our open source plugins where we basically want to ensure

* all changes from 3.x are merged into 4.x
* tests are running with the 4.x branch (not sure if that works already or whether it needs a beta?)
* ideally we have a green build for the 4.x branch of each plugin
* and maybe could also do some basic minimal functional test with each plugin with 4.x
* we check the version constraints are good in plugin.json (version = 4.0.0 and we require Matomo 4)
* once it’s all good we publish a new version for the plugin on the marketplace from the 4.x-dev branch by tagging it.

**Comment by diosmosis** [comment]
Plugins known to be compatible:
- plugins included with core
- GoogleAnalyticsImporter
- Funnels
- Cohorts

**Comment by sgiehl** [comment]
* ActivityLog
* [DeviceFeatureWebGL](https://github.com/sgiehl/piwik-plugin-DeviceFeatureWebGL)  (already released)
* [IPReports](https://github.com/sgiehl/piwik-plugin-IPReports)  (already released)
* [ReferrersManager](https://github.com/sgiehl/piwik-plugin-ReferrersManager)  (already released)

**Comment by diosmosis** [comment]
Other plugins:
* InvalidateReports (build is passing)
* [ ] HeatmapSessionRecording (build failing)
* WhiteLabel (build is passing)
* RollUpReporting (build is passing)
* [ ] CustomReports (build failing)
* [ ] LoginSaml (build failing, still using 3.x-dev as main branch btw)
* [ ] ProxySite (no travis build)
* [ ] PaidAdvertisingPerformance (build failing)
* [ ] CustomTranslations (build failing)
* [ ] ActivityLog (build failing)
* UsersFlow (build passing)
* [ ] AbTesting (build failing)
* [ ] ServerFileSync (build failing)
* FormAnalytics (build passing)
* [ ] EnterpriseDemo (no build)
* [ ] WooCommerceAnalytics (no build)
* MultiChannelConversionAttribution (build passing)
* [ ] SearchEngineKeywordsPerformance (build failing)

@sgiehl feel free to edit this comment/check things off

**Comment by tsteur** [comment]
@diosmosis @sgiehl added the Matomo plugins as well

**Comment by tsteur** [comment]
fyi @sgiehl @diosmosis just went over all our plugins to make sure 3.X commits are merged into 4.X everywhere and it's all good now. Need to make sure from now on when merging a plugin PR to always merge 3.X and 4.X. It looks like we were already doing this anyway really well so just wanted to mention this is looking all good (as I recently had made few tweaks in some 3.X plugin versions)

**Comment by tsteur** [comment]
closing this big issue for now 🚀 🥳  

Cheers @diosmosis @sgiehl 

We'll later again make sure all 4.x-dev branches are up to date and that all latest changes in 4.X have a release.
