### ISSUE TITLE
Do not load JS tracking code deferred

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16055]
Currently we set `async=true;defer=true;`. However, most browsers support async so defer should be no longer set. This is recommended behavior and ensures a browser won't prefer `defer` over `async` (which be bad for performance).

Should be updated in generated tracking code and in docs. Only `async=true` should be set.

**Comment by Findus23** [comment]
it seems like GA also only sets async, but not defer (https://github.com/matomo-org/matomo/issues/16189)
