### ISSUE TITLE
Nonce::verifyNonce() returning FALSE when it should not

### ISSUE THREAD

**Issue by luismsgomes** [matomo-org/matomo#16057]
Configuration seems OK to me.

Debugging `Nonce::verifyNonce()` I noticed:

1.  `self::getOrigin();` returns `'https://somedomain.org:443'`
2. `self::getAcceptableOrigins()` returns `array('http://somedomain.org', 'https://somedomain.org')`

Thus, the returned origin is not found in the acceptable origins array.

Note the missing ports in the acceptable origins.

Matomo version 3.13.6.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/cannot-update-from-matomo-4-13-1-to-4-13-3/49515/5
