### ISSUE TITLE
The display problem of piwik-siteselector in asia language environment

### ISSUE THREAD

**Issue by wangchao16213** [matomo-org/matomo#16072]
Hi,I got a trouble of piwik-siteselector in asia language environment.If my site name is Asian, this control will not display the content correctly when the mouse is moved.I checked the source code and found that the problem was caused by escape of the twig template engine. if remove the escape filter,My site name can be displayed correctly.
![微信图片_20200616095428](https://user-images.githubusercontent.com/16793182/84723095-682ee080-afb7-11ea-8221-d8b467b20504.png)

![微信图片_20200616093225](https://user-images.githubusercontent.com/16793182/84722580-31a49600-afb6-11ea-94b7-19110c481702.png)

**Comment by sgiehl** [comment]
Hi @wangchao16213.
Thanks for creating the issue. Seems the website name is escaped twice there. Will prepare a PR to fix that.
