### ISSUE TITLE
unwanted pixel response triggering adblockers

### ISSUE THREAD

**Issue by Mepherotus** [matomo-org/matomo#16078]
Hello guys, the default behavior of the matomo JavaScript tracker seems to be sending the 1st request on the page with  "request_image" set to 1, this theoretically should trigger a 200 with the 1*1 pixel as a response but some of the major adblockers have really strict rules for bocking image requests.

Is there any way in JS/matomo config/anywhere else to permanently set the  request_image parameter to 0?

**Comment by tsteur** [comment]
@Mepherotus you could use `_paq.push(['setRequestMethod', 'POST'])`

**Comment by tsteur** [comment]
and / or using `_paq.push(['alwaysUseSendBeacon'])`

**Comment by tsteur** [comment]
@Mepherotus does this answer your question?

**Comment by Mepherotus** [comment]
Yes, I was testing for some days now and, together with some simple rewrite rules on the load balancer (rewriting matomo.php to /m) we have quite a nice tracking coverage
