### ISSUE TITLE
Multiple trackers, missing events?

### ISSUE THREAD

**Issue by mariusk** [matomo-org/matomo#16081]
EDIT: I just realized I got my sites mixed up. It's the one I am hosting myself which had missed the event. This could be me messing with the setup, restarting stuff. My second comment about the commercial cloud version getting less events than the one I am hosting myself still seems true though.

ORIGINAL POST:

After an issue with userId/visitorId, I decided to do a test where I self host in addition to the commercial plan we have already. I set up my new self hosted instance according to the instructions here:

https://developer.matomo.org/guides/tracking-javascript-guide#multiple-piwik-trackers

After mucking about with icons and some other settings, they are quite equal. My self hosted instance was created from the `3.x-dev` branch, which I believe the commercial hosting uses.

What is a bit worrying now is that some events go missing with one of the instances. Traffic is neglible, so should not be a capacity issue either. Any ideas why they differ so much? E.g. the `18:37` event on the left hand side doesn't even exist in the hosted instance:

![image](https://user-images.githubusercontent.com/218612/84933114-acb09e00-b0d5-11ea-8a10-6c6ea37787bb.png)

**Comment by mariusk** [comment]
FWIW, I'm also noticing that even when both instances get events from a visitor, the commercial cloud version typically gets fewer events from the same visitor.

**Comment by tsteur** [comment]
@mariusk I suggest you get in touch with our support: support at matomo.cloud

there are various things I can think out of the box like different ad/tracking blockers where some might be blocking the cloud and some others might be blocking your self hosted. Also would need to double check how your tracking code is set up (eg which tracker is visited first). Also people would have maybe opt out if they can do this on the cloud instance but not the self hosted instance (if they can opt out).  Would also need to check there are no exclusion settings or do not track differences etc. There are probably a few more things. Be good to get in touch with support maybe they can help.

**Comment by mariusk** [comment]
Good advice, thanks. In retrospect could even be laggy DNS servers, considering I mapped the DNS name for the new site this morning.

**Comment by tsteur** [comment]
Yes good point. Even with short TTL there will be always some where it takes days.
