### ISSUE TITLE
Do not Track: Improve the message shown when Do not Track is enabled

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#16102]
Make the message more clearer for the users when "Do not Track" is enabled. Received feedback via email.

Suggestion by user:  You are not being tracked because we honor the 'Do Not Track' setting you have enabled in your browser. You will not be able to opt-in until this setting has been disabled.

Current message:
![image](https://user-images.githubusercontent.com/26726594/85350279-da259d80-b554-11ea-9347-d73065894523.png)

**Comment by Findus23** [comment]
At least for me, I get the following message when Do Not Track is enabled, which sounds a lot more straightforward:

![grafik](https://user-images.githubusercontent.com/6266037/85375222-4644d900-b536-11ea-98cb-0ab24d015ffe.png)

**Comment by tsteur** [comment]
![image](https://user-images.githubusercontent.com/273120/86422525-7871ea00-bd31-11ea-8b73-7480c1dff338.png)
Works for me too. @KarthikRaja1388 make sure Do Not Track is actually enabled in the browser and in Matomo the opt out feature needs to be enabled in "Admin -> Privacy -> Users opt out"

![image](https://user-images.githubusercontent.com/273120/86422577-950e2200-bd31-11ea-8381-dbff8c4b6280.png)

It's not enough to have the feature enabled in the tracking code.
