### ISSUE TITLE
UsersManager Plugin: "password changed" e-mail notification text makes no sense

### ISSUE THREAD

**Issue by jl-cs** [matomo-org/matomo#16119]
After changing my password, I just go an e-mail by a Matomo system I have an account with and was puzzled by this text: `"If this was you, feel free to ignore this email. If this was not you, please login, correct your email address, change your password and contact your Matomo administrator.",`
If this was not me, how would I know the new password? And what should correcting my e-mail-adress (which I'd be unable to, because I'm unable to login) help with it?
Obviously this makes no sense in this context so I'd propose to change that to something more meaningful, especially so that inexperienced users are less confused. Maybe pull the part with `"contact your Matomo administrator"` to the start of the sentence?!
You can find the line [here](https://github.com/matomo-org/matomo/blob/fb2636c4c4557cb8e7edfee519ef556a3986f37e/plugins/UsersManager/lang/en.json) and also in the same spot in the other translation files, at least in the german translation it also makes no sense.

**Comment by tsteur** [comment]
Good point. The text makes sense when email was changed but not when password was changed...

If you have any suggestion on what to send in this case be great 👍

**Comment by jl-cs** [comment]
I'd propose to simply go with something like `"If this was you, feel free to ignore this email. If this was not you, please contact your Matomo administrator immediately!"`

**Comment by tsteur** [comment]
Thanks @jl-cs 👍  very appreciated. Create a PR https://github.com/matomo-org/matomo/pull/16131
