### ISSUE TITLE
White label is rewriting Piwik to our white label name in Custom JavaScript variables

### ISSUE THREAD

**Issue by jjcitron** [matomo-org/matomo#16126]
so if I add this as a custom JS:

```
function () {
 return Piwik.getAsyncTracker().getVisitorInfo()[1]
}
```

and hit update/ save,

the system saves it as

```
function () {
 return My WhiteLabelNamed Analytics.getAsyncTracker().getVisitorInfo()[1]
}
```

breaking the variable.

**Comment by tsteur** [comment]
@jjcitron could you get in touch with our support at shop@innocraft.com? That be great thanks. Be also great to let us know in the email how you add custom JS. 

Here we manage only issues related to Matomo core itself. Thanks.
