### ISSUE TITLE
This plugin's system tests shouldn't fail when new Segments are added in core

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16140]
#### Reproduce
- a new segment is added to Piwik core
- this plugin's system tests run 
- and fail: `#1: Piwik\Plugins\CustomDimensions\tests\System\ApiTest: Differences with expected in '/home/travis/build/piwik/plugin-CustomDimensions/piwik/plugins/CustomDimensions/tests/System/processed/test___API.getSegmentsMetadata.xml'` because a new segment was added in core
#### Example

this failing build  https://travis-ci.org/piwik/plugin-CustomDimensions/jobs/106380038
#### Solution

the system test `plugins/CustomDimensions/tests/System/processed/test___API.getSegmentsMetadata.xml` should only test for those segments that are added by the plugin. 
#### Outcome

the build for CustomDimensions will fail less often and make us more agile and move faster without breaking builds.

**Comment by sgiehl** [comment]
As the plugin is included in core now, it's fine to update the tests with core when they change
