### ISSUE TITLE
Regex should allow for more than one group

### ISSUE THREAD

**Issue by danielfett** [matomo-org/matomo#16141]
Bug:
There may be more than one "(" or ")" in regular expression used for dimension extraction although there is only one capturing group. Examples include non-capturing groups, modificators like "(?i)", and escaped character sequences like "(". Regular expressions with more than one "(" or ")" are rejected currently.

Example: 
(?i)example.com/(?:SOME_PART/)?([a-z]{2})(?:$|/)
This is captures exactly one group, yet is not allowed. (This is what I wanted to use in my project, actually.)

Root cause:
Counting the number of "(" or ")" as is done in https://github.com/piwik/plugin-CustomDimensions/blob/master/Dimension/Extraction.php#L46 is just wrong: It does not ensure that there is exactly one capturing group.

Better solutions:
Short term: Remove this useless test. Add an example or warning regarding the number of groups. 
Long term: Include "live-preview" of matches as described in another bug report. Warn when more than one group captures.

**Comment by 9joshua** [comment]
I have another request for this. A regex expression like this should work: `((?:media|stream)\/\d+)`

But Matomo returns this error message: 
```You need to group exactly one part of the regular expression inside round brackets, eg 'index_(.+).html'```

As @danielfett pointed out, Matomo's parsing of regex expressions incorrectly considers a grouping like this `(?.....)` to be an additional capture group.

**Comment by 9joshua** [comment]
PR for this: https://github.com/matomo-org/matomo/pull/20548
