### ISSUE TITLE
GeoLite2-ASN Geolocation not working

### ISSUE THREAD

**Issue by jurvi** [matomo-org/matomo#16162]
I have downloaded GeoLite2-ASN.mmdb from MaxMind site, and put it in the /var/www/html/misc as instructed. For some reason though, Mamoto does not seem recognize it. DBIP / GeoIP 2 (Php) just keeps saying "Not installed".

If I change the filename to GeoIP2-City.mmdb, Mamoto tries to load up the file with warnings, and DBIP / GeoIP 2 (Php) says "Broken", as more or less expected, so the folder seems to be correct and file permissions fine, just for some reason Mamoto seems to ignore the file when it's named GeoLite2-ASN.mmdb, even though according to documentation it should work.

**Comment by sgiehl** [comment]
Hi @jurvi. Thanks for creating this issue. It currently seems to be necessary to provide a location database file to be able to use the location provider. That actually shouldn't be the case. I'll have a quick look if it's easy to fix.

**Comment by sgiehl** [comment]
@jurvi I've provided a possible fix here: https://github.com/matomo-org/matomo/pull/16163
If you want you can try to apply the changes manually.

**Comment by jurvi** [comment]
Yes, it works great with the manually applied fix! Thanks, amazing job. :)
