### ISSUE TITLE
Cloudron installation method

### ISSUE THREAD

**Issue by nebulade** [matomo-org/matomo#16168]
Hi all!

we at [Cloudron](https://cloudron.io) have packaged matomo (and of course previously piwik) since a few years now and kept it up-to-date for our users. It is very popular amongst our users, of course often together with wordpress. 

I wanted to reach out here to ask if there is a place at the documentation or so to maybe mention Cloudron as one of the ways to install matomo? 

Our app package repo is at https://git.cloudron.io/cloudron/matomo-app

Best,
Johannes

**Comment by KarthikRaja1388** [comment]
Added to https://matomo.org/integrate/#programming-language-platforms-and-frameworks

**Comment by KarthikRaja1388** [comment]
Added to https://matomo.org/integrate/#programming-language-platforms-and-frameworks
