### ISSUE TITLE
MaxMind GeoIP2-City-Europe database not working properly

### ISSUE THREAD

**Issue by ottk3** [matomo-org/matomo#16171]
Hi there,

we recently purchased the MaxMind GeoIP2-City-Europe database but getting pretty bad results for europe.
We are using the PHP-method (it says installed), but it can't determine my own ip address. 
Even the other found locations look some kind of odd.

>According to this provider, your current location is:
>Unknown Refresh
>Note: This GeoIP implementation has access to the following types of databases: City, Country.

While the [MaxMind Precision Demo ](https://www.maxmind.com/en/locate-my-ip-address) correctly determines my location in Germany.

The **GeoIP2-City-Europe.mmdb** was correctly extracted into the /misc directory using the automatic url download option with the following url:

`https://download.maxmind.com/app/geoip_download?edition_id=GeoIP2-City-Europe&suffix=tar.gz&license_key=<key>`

What are my options to check if all settings are correct?

Best regards,
Sven

**Comment by sgiehl** [comment]
Hi @ottk3. I don't have access to the paid versions of Maxminds databases, so I'm not able to check that locally...

Are you accessing your Matomo locally? If so, that might be the reason for the "Unknown" result, as Matomo might use your local IP for the lookup.

Note: You can use the API of your Matomo to do a lookup with the current configured location provider with this API call:

https://{your.matomo.url}/index.php?module=API&method=UserCountry.getLocationFromIP&ip=194.57.91.215&format=JSON&token_auth={YOUR_TOKEN_AUTH}

**Comment by ottk3** [comment]
Hi @sgiehl,

Thank you!
Regarding my own ip address you were totally right. I checked it while connected to the company network and wasn't aware that the domain ist routed internally.

The bad geolocation of our visitors is caused by the "Anonymize Tracking Data" settings since we anonymize the addresses.
