### ISSUE TITLE
Custom View tracking

### ISSUE THREAD

**Issue by SARAVANA1501** [matomo-org/matomo#16179]
We have `data-track-content` configured across the page, We are using `_paq.push(['trackVisibleContentImpressions', true, 750]);` to track the interaction. `trackVisibleContentImpressions` is tracking view and click event of `data-track-content` elements, we would like disable default view event and view event should be triggered if user is viewing the content for 3 seconds. How can we implement this?

**Comment by tsteur** [comment]
@SARAVANA1501 same here do you mind asking this in our forum? https://forum.matomo.org/  and maybe check out also the `trackContentImpression( contentName, contentPiece, contentTarget )` method in https://developer.matomo.org/api-reference/tracking-javascript on how to track impressions for a custom behaviour like after 3 seconds. Hope this helps. Cheers
