### ISSUE TITLE
Matomo cannot recognize Country info in Chinese coming from HTTP Server module

### ISSUE THREAD

**Issue by Creling** [matomo-org/matomo#16198]
Hello:

I’m now using HTTP Server Module to get visitors’ location in **Matomo v3.13.6**.
![image](https://user-images.githubusercontent.com/43109504/87029138-4a4d4800-c212-11ea-843c-5953301955cf.png)

The problem is:
Even though I could see the correct location info(both city and country) in the setting panel like this:
![image](https://user-images.githubusercontent.com/43109504/87028928-ed519200-c211-11ea-955b-6cc622a39777.png)

The Country info in the Visits Log is unknown, however, the City info works well.
![image](https://user-images.githubusercontent.com/43109504/87028955-f6dafa00-c211-11ea-9607-f89473820058.png)

**Comment by sgiehl** [comment]
@Creling Matomo internally stores the country iso code, so it's important to have a server variable for `MM_COUNTRY_CODE`

**Comment by Creling** [comment]
It works.
Thank you.
