### ISSUE TITLE
JS tracker should support CSS class matomo_ignore as alias of piwik_ignore

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16193]
From email feedback:

>  Hi, I'm noticing some strange issues with matomo.js. For example. the js tracking guide indicates that using the class 'matomo_ignore' should result in the matomo ignoring link downloads, however, i am finding that does't work, while the class 'piwik_ignore' does cause the element to be ignored. Is the documentation wrong? or is it possible that the cdn is serving an older version of the tracking code?

Our guide mentions `matomo_ignore` here: https://developer.matomo.org/guides/tracking-javascript-guide

**Comment by tsteur** [comment]
@mattab you are linking to the docs for 4.X which have been updated for the upcoming beta. 

It's not mentioned in https://developer.matomo.org/3.x/guides/tracking-javascript-guide

This particular one we can backport though as an exception
