### ISSUE TITLE
Release 3.14.0

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16196]
See https://github.com/matomo-org/matomo/pull/16190 need to mention that the generated tracking code changes (the init of `_paq`)

**Comment by mattab** [comment]
Added to changelog https://matomo.org/changelog/matomo-3-14-0/

> Also, the first line of the default <a href='https://developer.matomo.org/guides/tracking-javascript-guide'>JavaScript Tracking code</a> has changed and now reads <code>var _paq = window._paq = window._paq || [];</code> (You don't need to do anything, any existing tracking code will still be compatible.)
