### ISSUE TITLE
Matomo reporting API JSONDecodeError

### ISSUE THREAD

**Issue by ricky94511** [matomo-org/matomo#16191]
Hi all,

My environment is Matomo Cloud(Business version 3.13.6) and I used Live.getLastVisitsDetails API to get weekly raw data.

```
my_params = {
        'module': 'API', 
        'method': 'Live.getLastVisitsDetails',
        'idSite': idSite,
        'period': 'week',
        'date': 'today',
        'format': 'json',
        'filter_limit': 1,
        'filter_offset': 1, 
        'token_auth': token
    }
req = requests.get(url, params = my_params)
visit_log = req.json()
```
Sometime I would get the error as shown below, and I check `req.status_code` still 200
![螢幕快照 2020-07-08 上午10 09 19](https://user-images.githubusercontent.com/12468475/86866272-2e0eb580-c103-11ea-8ef1-1f8f45e5ce47.png)

I try to adjust `filter_limit` to decrease request context size and set `filter_offset` to partition the data. But even I force the parameter and run hourly, 40% would succeed and 60% would fail.

I hope for your help.

**Comment by tsteur** [comment]
@ricky94511 is this still happening in the last few hours? We applied a fix just 6 hours ago. 

If that's still happening could you please email our support? support@matomo.cloud
