### ISSUE TITLE
Install on github pages

### ISSUE THREAD

**Issue by fabeit** [matomo-org/matomo#16219]
Could someone please tell me if it's possible to install Matomo on a personal Github Page such as mysite.github.io?

I have uploaded the unzipped folder but not sure if it works because github pages doesn't support PHP.

**Comment by tsteur** [comment]
Hi @fabeit to run Matomo you need to have PHP. You won't be possible to install Matomo. You can still track Github pages though you just need to install Matomo either

* On a separate server that supports PHP https://matomo.org/docs/installation/
* In a WordPress https://matomo.org/installing-matomo-for-wordpress/
* Or use our cloud hosted service https://matomo.org/start-free-analytics-trial/

You can then embed the JavaScript tracking code into the Github page.

**Comment by fabeit** [comment]
@tsteur Thank you for your answer. Unfortunately WordPress free plan doesn't allow to install plug-ins or upload custom code. Are there any servers that offer PHP free plans?

**Comment by tsteur** [comment]
Sorry @fabeit  I unfortunately I don't know the answer to this. I think there would be some for sure but I don't know any of them unfortunately.
