### ISSUE TITLE
piwik-php-tracker missed after update

### ISSUE THREAD

**Issue by maisen20** [matomo-org/matomo#16223]
After updating matomo to version 3.14.0, piwik-php-tracker is missing. 
In /libs/PiwikTracker/PiwikTracker.php, there is following code:
`if (!class_exists('PiwikTracker')) {
    require_once __DIR__ . '/../../vendor/piwik/piwik-php-tracker/PiwikTracker.php';
}`

After the update, this file is missing and my whole script crashes.

**Comment by sgiehl** [comment]
Hi @maisen20. Thanks for the report.

that needs to be changed to `if (!class_exists('PiwikTracker')) { require_once __DIR__ . '/../../vendor/matomo/matomo-php-tracker/PiwikTracker.php'; }`

**Comment by maisen20** [comment]
Yes, that works. Thank you sgiehl =)!
