### ISSUE TITLE
Segmented Visitor profile: Layout breaks when zooming out

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#16238]
Issue: Layout of the segmented visits log breaks when zooming out in the browser when reaching any percentage less than 100%, visits log is getting listed on the left instead of right.

Steps to reproduce:

1. Click "View visitor profile" on any visit under the 'Visits Log"
2. Zoom out the browser less then 100%

Can be reproduced in [demo](https://demo.matomo.org/) website

**Comment by sgiehl** [comment]
Guess that depends on browser and screensize, but should be easy to fix. Will check if it's possible to provide a quick fix in a couple of minutes...
