### ISSUE TITLE
Some plugins marked as not compatible with Matomo 3.14

### ISSUE THREAD

**Issue by davidlemaitre** [matomo-org/matomo#16231]
Following update to Matomo 3.14.0, a warning message indicates some plugins are not compatible with this version and cant be loaded : LogViewer, TasksTimetable. 

However, the requirements for the Matomo version are respected :
https://plugins.matomo.org/LogViewer
https://plugins.matomo.org/TasksTimetable

**Comment by tsteur** [comment]
@davidlemaitre I just checked the plugins and they should be definitely compatible. By any chance are you still seeing this message and can you post a screenshot of what you see or maybe you took a screenshot when it happened?

**Comment by davidlemaitre** [comment]
I'm still seeing this message from administration area :
![image](https://user-images.githubusercontent.com/156752/88267871-ca26e800-ccd1-11ea-9e3b-8c59290be34e.png)

Note : I'm using the official 3.14-apache version of Matomo Docker image, I pulled the new image to get the 3.14 version instead of automatic update.

**Comment by tsteur** [comment]
Thanks @davidlemaitre 

Can you check if the files `$matomoDir/plugins/LogViewer/plugin.json` and `$matomoDir/plugins/TasksTimetable/plugin.json` exist and paste the content of these files here maybe?

**Comment by davidlemaitre** [comment]
The LogViewer and TasksTimetable directories are missing. I reinstalled them, the warning message has been disappeared, all is fine.

I think I have to put the plugins directory or the whole Matomo in a Docker volume. Currently, only the config directory is persisted in a volume.

**Comment by tsteur** [comment]
Thanks for letting us know and glad it works now 👍
