### ISSUE TITLE
Skipping the wizard steps

### ISSUE THREAD

**Issue by tonesp** [matomo-org/matomo#16239]
Hi.

I'm using Matomo (dockerized) inside a development group. Every time a person deploys the product, he/she needs to go to /matomo/ and follow the wizard steps.
I know there are some Env variables to pre-configure the database fields (MATOMO_DATABASE_TABLES_PREFIX, MATOMO_DATABASE_USERNAME, etc...) but is not enougth.
Is there a way to configure Matomo (DB, user, Website) to avoid this wizard?

**Comment by Findus23** [comment]
related to https://github.com/matomo-org/matomo/issues/10257 and the ideas proposed there

**Comment by tsteur** [comment]
@tonesp I'll close this issue for now as a duplicate of #10257 

Let me know if this is not the case and I'll be happy to reopen.

Thanks for creating the issue and showing your interest in that feature!
