### ISSUE TITLE
changing config:enable_plugin_upload provokes integrity check fail

### ISSUE THREAD

**Issue by TRILOS** [matomo-org/matomo#16246]
changed enable_plugin_upload = 0 to 1

integrity check index.php?module=Installation&action=systemCheckPage fails unexpectedly:

"Die nachfolgenden Fehler könnten durch einen teilweise oder gänzlich fehlgeschlagenen Upload der Matomo-Dateien entstanden sein.
--> Versuche die Matomo-Dateien im BINARY-Modus neu hochzuladen. <--

Integritätsprüfung fehlgeschlagen: (...)/config/global.ini.php"

**Comment by TRILOS** [comment]
gosh, how to assign the version nr. to this issue?!
it´s matomo 3.13.1 ...

**Comment by tsteur** [comment]
You need to change the config in `config/config.ini.php` not the `global.ini.php`

**Comment by TRILOS** [comment]
Sorry, had a lack of awareness.
