### ISSUE TITLE
Way to Remove domain/hostname

### ISSUE THREAD

**Issue by ncresswell** [matomo-org/matomo#16252]
Hi there,

Is it possible to not store (or to anonymize) the IP address / Hostname of the web asset that is being tracked?

We want to use this in our Single Page Application, and with this IP address / Hostname visible, it would allow us to see the address details for every deployment of our application at our users sites. This is a privacy concern.

As you can see in the pic below, i can see that a deployed instance of our application is running on 188.166.250.54:9010

![image](https://user-images.githubusercontent.com/23178133/88744147-a57fb400-d19a-11ea-90de-90a233c9db01.png)

**Comment by tsteur** [comment]
@ncresswell thanks for creating this issue. Would it help to always track the same host? Then you could set eg 
```js
_paq.push(['setCustomUrl', 'https://myfixdomain.com' + window.location.pathname + location.search]);
```

**Comment by ncresswell** [comment]
We have 100's of thousands of instances of our application deployed around the world... we dont want to know WHERE they are deployed, just that they are, and then get some usage info about how its used.

**Comment by tsteur** [comment]
@ncresswell would this not work with above JS in https://github.com/matomo-org/matomo/issues/16252#issuecomment-665431341 which would basically set a fixed domain/hostname (instead of removing it)?

What could maybe also work (haven't tested it) is:

```js
_paq.push(['setCustomUrl', window.location.pathname.substr(1) + location.search]);
```

**Comment by ncresswell** [comment]
testing now, will revert with findings soon.

**Comment by deviantony** [comment]
@tsteur works great, is there any way to override the website property as well?

![portainer-app-2020-07-30-Web-Analytics-Reports-Matomo (1)](https://user-images.githubusercontent.com/5485061/88868699-fbb92980-d264-11ea-84b6-f6e29b8f8959.png)


I'm not sure if the `setDomains` function can be used here.

**Comment by tsteur** [comment]
@ncresswell not sure what you mean by override the website property?

**Comment by deviantony** [comment]
@tsteur I added the new comment :D check my screenshot above.

**Comment by tsteur** [comment]
You could try `_paq.push(['setReferrerUrl', ''])`

**Comment by deviantony** [comment]
It seems to work fine, thanks for the quick update ! @ncresswell I think you can close that one.

**Comment by tsteur** [comment]
Thanks @deviantony  glad it works!
