### ISSUE TITLE
How do I disable cookies in Tag Manager?

### ISSUE THREAD

**Issue by yurizhang** [matomo-org/matomo#16266]
Hi,
How do I disable cookies in Tag Manager?
I can find how to do it in regular Matomo (below code), but nothing in the Tag Manager API.
// Call disableCookies before calling trackPageView
_paq.push([‘disableCookies’]);
_paq.push([‘trackPageView’]);

so can i user it??

_mtm.push(['disableCookies']);

**Comment by tsteur** [comment]
@yurizhang you can do this by editing the Matomo configuration variable. There is a setting for this: 
![image](https://user-images.githubusercontent.com/273120/89579222-81e9f700-d887-11ea-8b92-4cc77a67acf0.png)

For future questions please ask in our forums where we answer questions: https://forum.matomo.org/

Here in GitHub we only manage bug reports and feature requests and usually don't answer questions. Thanks for understanding.
