### ISSUE TITLE
Matomo premium features and support for enterprises usage

### ISSUE THREAD

**Issue by reddipravi** [matomo-org/matomo#16262]
Hello, I am trying to get an invoice for the usage of Matomo at our company. I have sent email to support@matomo.org but did not receive a reply. can anyone please guide me about how to get the invoice. Previously I was in contact with Matthieu Aubry.

**Comment by tsteur** [comment]
Hi @reddipravi I found your email and moved it into the right inbox. We'll let you know the best email to contact us in the next mail. Sorry for the trouble.

**Comment by reddipravi** [comment]
Hello Thomas, did not hear from anyone yet on my emails for the corporate license. Can you please expedite this as we need the premium features and support as soon as possible. 

Thanks
Praveen

**Comment by tsteur** [comment]
I'll bring this to the attention of the support team again @reddipravi

**Comment by reddipravi** [comment]
Hello Thomas, Again not able to reach the support team after multiple emails. Is there any issue which is creating for our  corporate emails are not finding the right support teams of Innocraft?

**Comment by tsteur** [comment]
@reddipravi I think the support team reached out to you already. Please let me know if not.
