### ISSUE TITLE
wrong session attribution for users converting trough paypal

### ISSUE THREAD

**Issue by Mepherotus** [matomo-org/matomo#16277]
We are using the premium bundle but none of the plugins can help because paypal simply overwrites all of the campaign data of the whole session.

In other words:
1) users arrive trough the campaign "X"
2) they browse the website (until this point we have the correct attribution in real time)
3) Convert trough paypal
4) the session's attribution is overwritten to paypal and we loose track of the campaign "X"

**Comment by tsteur** [comment]
@Mepherotus could you email our support about this? The email address for premium features is shop@innocraft.com

**Comment by mattab** [comment]
The solution is to enter `paypal.com` as one of your website Alias URL, please see this FAQ for more information: https://matomo.org/faq/how-to/how-do-i-add-a-referral-exclusion-in-matomo/
