### ISSUE TITLE
prevent vacation messages

### ISSUE THREAD

**Issue by Bad-and-Mad** [matomo-org/matomo#16288]
dear ladies and gentlemen,

would you possibly include a parameter "Auto-Submitted: yes"
for the header of the matomo-email-reports to prevent vacation messages?

as described at 

https://tools.ietf.org/html/rfc5230#section-4.6
and
https://tools.ietf.org/html/rfc5230#section-5.6

Thank you

I added this in my case by "hardcoding" the ".../libs/Zend/Mail.php":

```
cat ~/Piwik_01/libs/Zend/Mail.php | grep -in -A10 -B20 "by M.W."
----------------------------------------------------------------

523-    protected function _storeHeader($headerName, $value, $append = false)
524-    {
525-        if (isset($this->_headers[$headerName])) {
526-            $this->_headers[$headerName][] = $value;
527-        } else {
528-            $this->_headers[$headerName] = array($value);
529-        }
530-
531-            if ($append) {
532-            $this->_headers[$headerName]['append'] = true;
533-        }
534-
535:            // by M.W.
536-            if ( null === $this->_headers[ 'Auto-Submitted' ] ) {
537-            $this->_headers[ 'Auto-Submitted' ][] = 'yes';
538-        }
539-
540-    }
```

**Comment by Findus23** [comment]
Hi,

I have never heard of this header before outside of `Auto-Submitted: auto-generated` in the vacation message to prevent endless responses and a quick search through my inbox doesn'

But it seems reasonable and simple to add it. Since Matomo 4, Matomo uses phpmailer to send, so you probably want to add 
`$phpMailer->addCustomHeader('Auto-Submitted', 'yes');` somewhere here:

https://github.com/matomo-org/matomo/blob/b09093780b6a906a0522bda2a8137ca280ab3f65/core/Mail/Transport.php#L30-L43

If you want to, please create a Pull Request with this change against Matomo 4.x-dev.

**Comment by MAT-WEISS-2017** [comment]
Thank you for the fast reaction!

It doesn't matter whether you set the parameter to "Auto-Submitted: auto-generated" or to "Auto-Submitted: yes".

The only thing that matters is how in

https://tools.ietf.org/html/rfc5230#section-4.6

described:

"Implementations SHOULD NOT respond to any message that has an" Auto-submitted "header field with a value other than" no ". This header field is described in [RFC3834]."

It should simply be prevented that a sieve filter sends a vacation notification as an automatic response to emails from the Matomo installation.

My current version is "Matomo-Version: 3.14.0". There is no such file "Transport.php" here.

In addition, changes to the code result in file integrity warnings.

Perhaps this could be solved a little more elegantly by introducing a configuration parameter in the Matomo backend.

**Comment by Findus23** [comment]
Hi,

What I was proposing was that you create a pull request here on Github to make the change for everyone, so that this is fixed when Matomo 4 will come out. But if you want to, I can also do it for you.

**Comment by MAT-WEISS-2017** [comment]
Would you please create the pull request?

Thank you so much!

**Comment by Findus23** [comment]
@Bad-and-Mad I created https://github.com/matomo-org/matomo/pull/16292 with the change.
