### ISSUE TITLE
Downloads Export via API and via Interface will only export 100 Rows, even if filter_limit is larger than 100

### ISSUE THREAD

**Issue by Endlesscrafter** [matomo-org/matomo#16289]
Tested **Matomo Version**: 3.14.0
**Special Config**: 
`enable_segments_cache = 0
`

Steps to Reproduce:

Tested by Webinterface:
Go to Behaviour, then Downloads and 
 (Export All Rows) or (Export Custom Row Limit 500)

Also via API: 
`https://matomo.example.org/?module=API&method=Actions.getDownloads&idSite=1&period=month&date=today&format=xml&token_auth=REMOVED&expanded=1&flat=1&filter_limit=1000`

Adding a `&filter_pattern=` will not help.

This will just return 100 data rows with an additional header row. But not more rows, which would be expected, as more than 100 files were downloaded for the given period and site. 

Segmenting this data with `actionURL` will result in an empty result set.

**Comment by tsteur** [comment]
Hi @Endlesscrafter thanks for creating this issue. I tried to reproduce this but can't unfortunately. Could you update to the most recent Matomo version and check if this is still happening? 

In the UI itself do you see more than 100 results?

**Comment by Endlesscrafter** [comment]
Hi @tsteur,
Thanks for testing it out,
  the UI also only shows 100 lines even when changing to more lines in the drop-down. You cannot navigate to the next page on the bottom of the downloads list.

I will update to the latest Matomo version and get back to you if the issue still persists. If I can reproduce I will provide an in-depth procedure to reproduce.

**Comment by Endlesscrafter** [comment]
Hello again @tsteur ,
the Matomo instance is already on 3.14.0 which it says is the newest stable version. Do you advise to update to the beta channel?

**Comment by tsteur** [comment]
Sorry I was confused with the Matomo version and thought there was a newer one. Apologies for that.

Any chance you could check your `config/config.ini.php` regarding some of these settings? https://matomo.org/faq/how-to/faq_54/

Maybe it's configured to be limited to 100 rows.

**Comment by Endlesscrafter** [comment]
Hi @tsteur,

I did not change any of these values, but now I also tried adding the mentioned lines to the config.ini.php with at least a value of 1000. But this did not change the behaviour.

What can I do now?

**Comment by tsteur** [comment]
Sorry I can' think of anything else right now. It could be a server configuration thing or something else. If you can share a login to your Matomo that would maybe help so we could maybe see what's happening there. In case it's possible to give us temporarily a login for that site feel free to email us at hello at matomo.org and afterwards mention it here just in case the mail goes into spam.

**Comment by Endlesscrafter** [comment]
Hi @tsteur,

As we run this Matomo instance for a customer, I will first have to ask them about this. 
I will then get back to you.

Thank you for your help!

**Comment by Endlesscrafter** [comment]
Hi @tsteur ,

I finally got approval from the customer. I sent the mail to hello at matomo.org as you requested, already including administrative access. You can reach me here or via email and I will happily provide you with anything you need.

Thank you for your time, again!

**Comment by tsteur** [comment]
Thanks for this @Endlesscrafter 

You can delete the account now again.

The problem is that all these rows are in a so called subtable (not the top level table). There is a setting of 

```ini
datatable_archiving_maximum_rows_subtable_actions = 100
```

by default for each subtable. You can customise this setting as described in https://matomo.org/faq/how-to/faq_54/

For example you may want to set `datatable_archiving_maximum_rows_subtable_actions = 1000` and put this line into the `[General]` category of your `config/config.ini.php`.
