### ISSUE TITLE
HTML syntax error - "ampersanded" ampersand

### ISSUE THREAD

**Issue by supervisitor** [matomo-org/matomo#16286]
https://github.com/matomo-org/matomo/blob/679e73f1236969db0c2d767655cb84456a727d24/tests/PHPUnit/Integration/Tracker/TrackerCodeGeneratorTest.php#L68

in line 68, you should delete character 89 to 92 (`amp;`), this line should include `...matomo.php?idsite=1&amp;rec=1...` and not contain a ampersanded ampersand `...matomo.php?idsite=1&amp;amp;rec=1...`

**Comment by tsteur** [comment]
@supervisitor thanks for creating the issue. Do you have an actual issue with the tracker generator? the double escaped `&` might be expected there.

**Comment by supervisitor** [comment]
I think twice when I saw the result `&amp;amp;` in the generated tracker code.
Since then, I have been considering `&quot;` and `&amp;quot;` on the same line... yes, I know the difference an reason for this `&`, but somewhere I suspect a nesting error.

**Comment by tsteur** [comment]
Thanks. I just checked the regular output and there things look good see eg https://demo.matomo.org/index.php?module=API&format=json&method=SitesManager.getImageTrackingCode&idSite=62&period=day&date=yesterday and embedding eg 

```html
    <img src="//example.matomo/matomo.php?idsite=1&amp;rec=0" style="border:0" alt="" />
```

worked for me. It's only that in the tests it is encoded like this.

**Comment by supervisitor** [comment]
Sorry, I'm not one to just carelessly submit an issue report. Please close it, this error happens only in a very special version and only installed here. 😳
Apologize again for the trouble I have caused.

**Comment by Findus23** [comment]
No problem :slightly_smiling_face:
