### ISSUE TITLE
CustomVariables users: how to keep BC and install the new plugin from Marketplace

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16283]
Since we removed CustomVariables plugin from core: https://github.com/matomo-org/matomo/pull/16090 and #11524
and the Matomo 4 compatible version will be available from the Marketplace at https://plugins.matomo.org/CustomVariables soon,
 
I was wondering what happens on upgrade to Matomo 4:
* will the custom variable plugin be disabled on one-click-upgrade, which might break BC for some users?
* if the code is not deleted, then the problem is that the old CustomVariables code would not work (maybe?) with Matomo 4
* could we maybe mention to users they need to install plugin from Marketplace? (for example when we see Custom Variables recent reports have some data set and they likely use the feature)

Created this ticket as a reminder to double check this upgrade flow and be clear, so we minimise support queries after upgrade.

**Comment by sgiehl** [comment]
Shouldn't the plugin simply be updated if a newer version is available in the Marketplace 🤔

**Comment by tsteur** [comment]
Closing this one. We had tested this already half a year ago see eg https://github.com/matomo-org/matomo/pull/15552#issuecomment-584827870 and we'll of course test all the updates from 2 different Matomo versions again before the beta.

refs https://github.com/matomo-org/matomo/issues/16165
