### ISSUE TITLE
Segmented Visits Log: No data is fetched when viewing grouped pages

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/matomo#16324]
When viewing "Open Segmented Visits Log" on the grouped pages under "Behaviour > Entry Pages" and "Behaviour > Entry Pages" no data is getting fetched, when expanding the grouped pages and viewing the same per URL it works fine. 

Can be reproduced in 3.14. Works fine in Demo.

Steps to reproduce:
1. Open "Behaviour > Entry Pages" or "Behaviour > Pages"
2. Click on the "open segmented visits log" next to the grouped item

As per a customer, it was working fine in 3.13.5, has anything been changed in the recent update.

**Comment by tsteur** [comment]
@KarthikRaja1388 demo runs 3.14 as well. Is it maybe only for some specific pages containing a specific character?

**Comment by KarthikRaja1388** [comment]
@tsteur The pages I have tested so far doesn't have any special characters. Test was done in On-Premise.

**Comment by tsteur** [comment]
@KarthikRaja1388 I still can't reproduce it in On-Premise unfortunately. Can you maybe give me access to your Matomo?

**Comment by sgiehl** [comment]
As there hadn't been any further reports around this problem, we assume that is has meanwhile been fixed.
@KarthikRaja1388 If this is still any issue somewhere, please let us know, so we can reopen an investigate it.
