### ISSUE TITLE
Marketplace search broken in Reports

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#16358]
This seems broken in both 3.x and 4.x: When opening the Marketplace via the reports instead of the admin settings (I'm still not sure if this duplication is helpful) the plugin search seems broken
![grafik](https://user-images.githubusercontent.com/6266037/91757772-2df4d880-ebcf-11ea-8656-60d475008120.png)

It redirects to 
```
https://matomo.dev/index.php?module=Marketplace&action=overview&embed=1&idSite=17&period=month&date=today&segment=&showtitle=1&random=3659&sort=
```
which is not a full page, but just an HTML widget.

**Comment by tsteur** [comment]
@Findus23 I just tried to reproduce this on 3.X on the demo but couldn't. It shows correctly the content on the right side just like a report. Only an HTML widget be expected as it's not supposed to be a full page but shown just like a report. Not sure if I maybe not understand something correctly?

**Comment by Findus23** [comment]
30 images per second say more than a long explaination (this is on 4.x-dev):
https://video.lw1.at/videos/watch/1f67e3e1-891e-4db3-890c-b5b8a48c9c75

**Comment by tsteur** [comment]
I'd say for simplicity when someone searches for a plugin then we load the dedicated page maybe. This means we likely only need to set the correct `action` in the form

**Comment by tsteur** [comment]
This should be fixed in https://github.com/matomo-org/matomo/commit/a1e794996926fc9a5dea1aa8eca27d4ee792004a

**Comment by Findus23** [comment]
I can confirm it works now.
