### ISSUE TITLE
Keep MaterializeCSS up to date - use a fork or replace library

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16368]
I noticed in the 4.X branch there are sometimes JS errors in Materialize lib … Will keep an eye on it when it happens again… checked if there’s a new release available but see https://github.com/Dogfalo/materialize/issues/6438 there are 200 open PRs, 600 open issues and no new release in 1-2 years. Seems the maintainers only create releases for people donating or don't do anything at all anymore. Seems a fork will be maybe continued in https://github.com/materializecss/materialize but we’ll need to see if actually something will happen.

**Comment by Findus23** [comment]
I just noticed that an alpha release of the fork was released (https://github.com/materializecss/materialize/releases/tag/1.1.0-alpha). So I guess once it is stable, Matomo could use the fork.

**Comment by sgiehl** [comment]
might be worth a try to simply replace the library on a branch and check if UI tests are still working

**Comment by tsteur** [comment]
FYI After 4 years Materialize finally released an update :) https://github.com/materializecss/materialize/releases/tag/1.1.0

**Comment by sgiehl** [comment]
I spent a couple of minutes preparing the required changes to use the fork. If tests are (still) passing we could maybe consider doing that before Matomo 5.
https://github.com/matomo-org/matomo/pull/new/materializeupdate
