### ISSUE TITLE
JS error in segment filter widget in custom reports

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16369]
![image](https://user-images.githubusercontent.com/273120/92033176-5fcc9180-edbf-11ea-9f45-fcb3bbb6619a.png)

Happens when you click on "add and condition"

![image](https://user-images.githubusercontent.com/273120/92033212-6eb34400-edbf-11ea-8e9e-2da2673d6ae3.png)

seems to fail here: 
![image](https://user-images.githubusercontent.com/273120/92033369-ab7f3b00-edbf-11ea-907c-3c38544e4fd4.png)

Creating this here since the segment widget is in core. The feature still seems to work without any issues so far so if it's not an easy fix we might just ignore it.

refs https://github.com/matomo-org/matomo/issues/16368

**Comment by sgiehl** [comment]
That was a real though one to debug. It is indeed triggered by the `closest` method. But while bubbling up the elements somewhere in the [deep of materialize' javascript](https://github.com/Dogfalo/materialize/blob/v1-dev/js/cash.js#L143-L146) it tries to access the `matches` method of an element. But in that special case the element seems to be the form element, which contains the segment editor. The segment editor itself contains an element with the name `matches`, which thus is part of the form. That causes `el.matches` not to contain the actual method it should be, but to hold the `matches` form element instead. That causes the error as it tries to use the form element as callback later...
A possible fix would be to rename the form field or to remove it's name completely.

**Comment by tsteur** [comment]
Great find @sgiehl Sounds good to rename the form field 👍
