### ISSUE TITLE
Error by sending an email report

### ISSUE THREAD

**Issue by selametaydogdu** [matomo-org/matomo#16375]
When I try to send an email report, I get the following error message:
An error occurred while sending 'HTML Email Report - 1.yesterday.1.de - uIvIcuoAiEUM17OxEPU0v52JrbeafXgy0H5Fh4nt.html' to recipient@domain.com. Error
was 'Unable to connect via TLS'
But I was able to send an e-mail via telnet, which I also successfully received.

The telnet command is:
telnet ]mailserver} ]port}
ehlo [domain]
mail from:[from]
rcpt to:[to]
data
Subject: This is a test message

Hello.

.
quit

What could be here the problem?

**Comment by tsteur** [comment]
@selametaydogdu do you mind asking this question in our forum? https://forum.matomo.org/

Generally, this should work fine if everything is configured correctly. Here are the options:

```
[mail]
defaultHostnameIfEmpty = defaultHostnameIfEmpty.example.org ; default Email @hostname, if current host can't be read from system variables
transport = ; smtp (using the configuration below) or empty (using built-in mail() function)
port = ; optional; defaults to 25 when security is none or tls; 465 for ssl
host = ; SMTP server address
type = ; SMTP Auth type. By default: NONE. For example: LOGIN
username = ; SMTP username
password = ; SMTP password
encryption = ; SMTP transport-layer encryption, either 'ssl', 'tls', or empty (i.e., none).
```

Can you check if everything is configured correctly in your `config/config.ini.php` file?

In case you haven't, maybe also test through telnet from the Matomo server itself if that works.

BTW: In Matomo 4 (which a first beta release will be available likely in the next 10 days) we have also updated the PHP Mail library which could fix things. But generally things should work if you configure an SMTP.

If things are still not working maybe someone in the forum can help further as we can't really help much with this. 

There is also a command `./console core:test-email` available within the Matomo directory maybe this can help getting more information too.
