### ISSUE TITLE
Remove the incorrect tooltips in Visitors > Overview 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16371]
in the Visitors > Overview report [(eg. on demo)](https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=day&date=yesterday#?idSite=12&period=day&date=2020-08-17&segment=&category=General_Visitors&subcategory=General_Overview) the tooltips to the metrics on the right are all incorrect:

-> Let's remove these tooltips on 

x pageviews, 0 unique pageviews
x total searches on your website, 0 unique keywords
x downloads, 0 unique downloads
x outlinks, 0 unique outlinks

**Comment by sgiehl** [comment]
The shown tooltips are actually the default documentation for each of those metrics. So if it doesn't match it might also not match in other places. For downloads & outlinks we currently reuse the same documentation:

https://github.com/matomo-org/matomo/blob/115527353a9e75e01aa4d263408956ae45403bea/plugins/Actions/Actions.php#L66-L77

Guess it would be better to maybe go through the metrics glossary and fix all documentations that don't fit or can be improved

**Comment by tsteur** [comment]
Let's maybe for now fix just those ones and later eventually we'll go through all of them when needed.

**Comment by sgiehl** [comment]
Just thought about how to improve that documentation. But actually it's a bit hard to find something that matches all use cases. Those documentation is used as column documentation in data tables as well. For that case most documentations kind of match (even though some could be improved). But for the sparklines they have a slightly other meaning.
For the table we often use something like `The number of visits that clicked this link`, but for the overall sparkline it would be more something like `The number of visits that clicked any link`

**Comment by tsteur** [comment]
Can we change the translation for the sparklines eg in `VisitsSummary/get` like `if $view is sparklines then $view->addTranslation...`? It be a bit of work but seems there's no other way?
