### ISSUE TITLE
Update/Add documentation about App specific tokens

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#16392]
refs https://github.com/matomo-org/matomo/pull/15410

As this is one of the major changes in Matomo 4 we should create docs that explain what exactly changes for users, how the new token can be used and why one would want to use them (e.g. integration in a webapp, easily revokable, etc.)

**Comment by tsteur** [comment]
@Findus23 updated https://matomo.org/faq/general/faq_114/

Is this enough or is maybe anything missing?

**Comment by Findus23** [comment]
Many thanks, that sounds good for now.

We'll definitely notice if there are still confusions during the beta period.
