### ISSUE TITLE
Take advantage of plugin specific archiving

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16396]
@diosmosis could you maybe look at this one? refs https://github.com/matomo-org/matomo/issues/11974

* [x] **RELEASED**`Custom reports` (not sure if done already both in create and update custom reports). Should only rearchive the specific report
    PR: https://github.com/innocraft/plugin-CustomReports/pull/92
* [x] **RELEASED** `Users Flow`: on activation it should archive all it's reports
    PR: https://github.com/innocraft/plugin-UsersFlow/pull/43
* [x] **RELEASED**`Multi Channel Conversion Attribution`: on activation it should archive all it's reports 
    PR: https://github.com/innocraft/plugin-MultiChannelConversionAttribution/pull/27 
* [x] **RELEASED**`Funnels`: When adding or updating a funnel rearchive that specific funnel
    PR: https://github.com/innocraft/plugin-Funnels/pull/70
* [x] **RELEASED**`AbTesting`:  When updating (not adding) an existing A/B test then it should rearchive the data for A/B testing. Ideally it would do this back until `abtest['created_date']`. (which is often just a few days or weeks instead of multiple months)
    PR: https://github.com/innocraft/plugin-AbTesting/pull/63
* [x]  **RELEASED** `Cohorts`: On activation it should rearchive all it's reports (be good to confirm @diosmosis )
    PR: https://github.com/innocraft/plugin-Cohorts/pull/19

**Comment by diosmosis** [comment]
@tsteur fyi, AbTesting doesn't appear to have a created_date, is there another date that should be used or should created_date be added?

**Comment by tsteur** [comment]
@diosmosis as mentioned in chat `start_date` will need to be used. That's when the first tracking request for an a/b test has been received.

**Comment by diosmosis** [comment]
@tsteur prs have all been created, awaiting review

**Comment by tsteur** [comment]
@sgiehl can you review the linked PRs in the issue description? Basically, when using CLI archiving, then it should rearchive the related plugin specific reports or archive it for reports in the past on plugin activation for example.

**Comment by sgiehl** [comment]
done. Left some comments on some PRs

**Comment by tsteur** [comment]
I suppose we now only need to update the other plugins that were using the activate hook and then release a new version for each plugin (I can do that) and things should be done?

**Comment by tsteur** [comment]
@diosmosis @sgiehl

**Comment by diosmosis** [comment]
@tsteur it's on my list for today

**Comment by diosmosis** [comment]
@tsteur @sgiehl plugins that use this functionality should be updated in PRs (UsersFlow, MultiChannelConversionAttribution, Cohorts)

**Comment by diosmosis** [comment]
@tsteur @sgiehl PRs updated again

**Comment by tsteur** [comment]
@diosmosis does the funnels PR still need to be updated?

**Comment by tsteur** [comment]
@diosmosis also left a comment in custom reports to check

**Comment by tsteur** [comment]
This should be done now. There's one more comment left in custom reports to tweak a message ideally but can be done any time
