### ISSUE TITLE
Fix undefined offset in Matomo PHP Tracker

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16397]
> ( ! ) Notice: Undefined offset: 3 in vendor/piwik/piwik-php-tracker/PiwikTracker.php on line 1296

This is now happening in Matomo tracker because of https://github.com/matomo-org/matomo/pull/15774/files#diff-1279d666063b65e6d6777f902d11574fR3322-R3330

See https://github.com/matomo-org/matomo-php-tracker/blob/master/MatomoTracker.php#L1302-L1306

The cookie now has a lot less parts and different parts.

As part of this issue we need to 
* Assess if this breaks anything in PHP tracker (eg what happens if visitCount etc is no longer existing)
* Adjust the PHP tracker code to understand both type of cookies (older visits would have old cookie structure vs some will have new cookie structure)
* Mention in Matomo 4 developer changelog clearly that people need to upgrade their PHP tracker if they use it to not break anything

**Comment by diosmosis** [comment]
Side note: just noticed the `currentTs` handling was incorrect, it's set from the cookie to `currentVisitTs` but is used as `currentTs`.

**Comment by diosmosis** [comment]
@tsteur created https://github.com/matomo-org/matomo/issues/16397

Note: doesn't break anything since we don't send those tracking params anymore. Users still need to update. After it's merged, I'll create a PR w/ the changelog info.

**Comment by mattab** [comment]
### Also To do:

* Create issues in all SDKs that have used the PHP code initially such as the C#, possibly Java SDK, and Python
