### ISSUE TITLE
archive process trouble with parameter N

### ISSUE THREAD

**Issue by Jinzol** [matomo-org/matomo#16409]
Hi I want to process some specific data for a specific segment for specific time. 
It seems the parameter " --force-date-last-n" does not work anymore and default is used.

The code what I use is
`/opt/rh/rh-php72/root/usr/bin/php /srv/www/matomo/console core:archive --force-date-last-n=45 --force-idsites=3 --force-periods=day --force-idsegments=450  --concurrent-requests-per-website=1`

When I check the logging of this piece of code it shows
`INFO [2020-09-08 15:34:37] 26330  Will pre-process for website id = 3, period = day, date = last2
INFO [2020-09-08 15:34:37] 26330  - pre-processing all visits
`
It should be last45 in this case and it has worked. 

We run Matomo 3.13.5

How can I force to run the previous 45 days instead the last 2.  Date range is not really an option. 

I hope you can help me :-)

**Comment by tsteur** [comment]
Hi @Jinzol thanks for creating the issue.

Did you invalidate the reports before running this command? AFAIK we added some code to change `lastX` on demand eg from `last45` to `last2` should all archives be `finished` and none are invalidated.

**Comment by Jinzol** [comment]
Well I did not invalidate the reports before running because I want to use a custom N with archiving. I have problem that the data of the month august is not correct while the archives says its correct. We duplicate the data to an other environment with its own archiving process and there is a difference in results. What I think what is happening is that my archiving process takes sometimes to long (48h+) and the next archiver run will skip data because N is to small. You get small gaps in the processed data and that gives different results. Thats why I want to increase the value of N.  But that my theorie :-)

**Comment by tsteur** [comment]
> Well I did not invalidate the reports before running because I want to use a custom N with archiving

If you don't invalidate the reports upfront, Matomo should usually not rearchive these reports even if it uses eg `last45`. Even if it was using `last45`, Matomo should then see there are existing archives for most days and ignore it. It would only rearchive them if the archives for these days never existed. I'm not sure if this procedure was done before but thinking it shouldn't really have worked before unless for some reasons the archives were never finished for those days where the data wasn't correct (eg month of August). I'd definitely recommend to first invalidate the data @Jinzol . Could you give that a try?

**Comment by Jinzol** [comment]
Well I can give that a try and I will report it back. I takes some time to reprocess the data. But in the meantime I still don't understand why the archivers have finished correctly and the processed data is wrong. Or my raw data is incorrect but with the mirror environment it seems that is not the issue. We have seen more deadlocks on the database. What kind of effect does that have of the archivers? Or how can I prevent them.  I would like to say to my colleague's the archiver is done and the data is trustworthy. The problem with invalidate reports is that I know something is wrong and now I don't know what went wrong.

**Comment by tsteur** [comment]
@Jinzol let us know when you have an update. It's hard to say if/what went wrong there. It also depends maybe how it all works with your mirror environment etc. Is it happening repeatedly or just once?

What kind of deadlocks are triggered? Do you have more information eg what kind of query is having the issue?

**Comment by Jinzol** [comment]
Hi @tsteur, well it took some time but I reprocessed august and it seems fixed.
I started with

- day with n=45
- day,week n=8
- day,week,month n=2

The last one took 80768 seconds or 22,43 hours. I hope it gets abit faster with day,week,month and n=2. I think my problem started that some archive run didn't finish correctly. I will add the logging of the deadlock.

**Comment by tsteur** [comment]
Thanks. Be good to create a new issue for the deadlock if there isn't one already for that particular deadlock (we can also close as duplicate if needed). be great to watch if the problem happens again, otherwise we can maybe close the issue now and reopen if the problem happens again?

You will maybe also want to write the output of the archiving somewhere like 

```
1 * * * * php path/to/matomo/console core:archive > archive.log
```
