### ISSUE TITLE
Replace confusing GeoIP warnings

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#16427]
I looked into the GeoIP system check and I am completly confused by both the code and the warnings Matomo gives:

When I set up Matomo with the default geolocation provider, I get the following warning in the system check:
`
Geolocation works, but you are not using one of the recommended providers. If you have to import log files or do something else that requires setting IP addresses, use the PHP GeoIP 2 implementation</a> and install <a href="https://matomo.org/docs/geo-locate/" rel="noreferrer noopener" target="_blank">maxminddb extension.
`
The HTML is broken and it recommends users to install maxminddb, something nearly nobody should need to do.

Looking at the code doesn't really clear anything up:
https://github.com/matomo-org/matomo/blob/115527353a9e75e01aa4d263408956ae45403bea/plugins/UserCountry/Diagnostic/GeolocationDiagnostic.php#L45-L65

The warning I expect most people to see there (`DefaultLocationProviderDesc1`) is only displayed if `!$isProviderInstalled` which only happens if the status of the currently selected geolocation provider is not INSTALLED, but the default provider is obviously always installed, so I think noone ever sees the warning that provides the actual help.

I also can't think of a combination of mixed up translation strings or conditions that would make sense.

@sgiehl, do you know more about how this is supposed to work?

**Comment by tsteur** [comment]
@Findus23 is this as a result of the Matomo 4 upgrade or was this maybe working before?

**Comment by Findus23** [comment]
The only change I can see in those files is https://github.com/matomo-org/matomo/pull/15521/files#diff-37504b398acb93a27b5550d760b3c96d, but that only moved the translations and didn't change them (I think).

And indeed switching to the default geolocation in 3.14.1 shows the same message.

**Comment by sgiehl** [comment]
I guess that check is already a few years old. So might make sense to complete rewrite that with more useful thing.

So imho we should have these types of results:

* **Recommended Provider installed and activated**
  --> Result: OK

* **Currently selected Provider has an error**
  --> Result: Error (with error message from provider)

* **Default provider is in use**
  --> Result: Warning  (Suggest to use another provider that does real geolocation)

* **Server module is used**
  --> Result: Warning  (Suggest using PHP provider if log import will be used)

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/disable-language-based-geolocation/65028/1
