### ISSUE TITLE
Matomo 4: Code to prevent server gone away in CronArchive is no longer there

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16424]
It seems this code is no longer there @diosmosis ? https://github.com/matomo-org/matomo/pull/15619/files

Any chance we could add this back? Basically, after any `climulti::request` we need to execute that code to prevent possible server gone away errors.

We also need to add the same `disconnectDB` to `runScheduledTasks` in `CronArchive` to prevent server gone away errors.

```
    public function runScheduledTasks()
    {
        $this->logSection("SCHEDULED TASKS");

        if ($this->disableScheduledTasks) {
            $this->logger->info("Scheduled tasks are disabled with --disable-scheduled-tasks");
            return;
        }

        $this->disconnectDb()'
```

**Comment by diosmosis** [comment]
Not sure how this was removed, but wasn't on purpose. Will add it back.
