### ISSUE TITLE
How to time multiple pages at the same time

### ISSUE THREAD

**Issue by ClearSeve** [matomo-org/matomo#16438]
How to time multiple pages at the same time
multiple pages call ping api

**Comment by ClearSeve** [comment]
![1](https://user-images.githubusercontent.com/26833671/93089557-0ec97100-f6ce-11ea-9bc2-f0debb586ed1.png)
![2](https://user-images.githubusercontent.com/26833671/93089566-11c46180-f6ce-11ea-8bc5-ba95a896507f.png)

These two are turned on at the same time. I want to Ping by URL

**Comment by tsteur** [comment]
@ClearSeve thanks for creating this issue. We generally don't answer questions here and only handle bug reports and feature requests. Could you ask this question in our forum? https://forum.matomo.org/ It be great to provide more information there as it's not quite clear what you are after.
