### ISSUE TITLE
Campaign builder should use new campaign parameters on website

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16434]
follow up from #16433

This applies to https://matomo.org/docs/tracking-campaigns-url-builder/

I suggest we add a Matomo version selector to differentiate between Matomo 3 and Matomo 4? Alternatively we'd need to wait for a few months after the Matomo 4 release before using the new `mtm_*` campaign parameters but since Matomo 3 will be around for a while we should add the Matomo version selector. Problem is many users might not know what version they are on. Eg when they are on Cloud etc. @mattab any thoughts? Could also just keep on using `pk_*` on the website since it is the safest choice and update it in 1-2 years.

**Comment by mattab** [comment]
@tsteur Sounds good to leave it as-is for now and update the website maybe 14 months after the Matomo 4.0.0 release?

**Comment by tsteur** [comment]
I'll invite you to an event so we won't forget 👍

**Comment by tsteur** [comment]
Created an internal issue for this. DEV-2413
