### ISSUE TITLE
Outlinks icons are not aligned in all reports

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16436]
Reproducible in Matomo 3 in Chrome and Firefox:

![Screenshot from 2020-09-14 12-52-07](https://user-images.githubusercontent.com/466765/93033167-31856680-f689-11ea-92b8-045e3dcf5b4b.png)

Maybe this was missed as a UI regression in Ui tests?

**Comment by tsteur** [comment]
@mattab I'll move this to Matomo 4 as we only fix important things in Matomo 3 now.
