### ISSUE TITLE
Show 32 bit vs 64 bit OS

### ISSUE THREAD

**Issue by ClearSeve** [matomo-org/matomo#16435]
I assume data is collected for the device and OS from the userAgent. It would be great to show some data about 32-bit vs. 64-bit since it is already available.

**Comment by tsteur** [comment]
@ClearSeve could you maybe let us know more information about this for the use case why you are after this data? This will help us better understand it. Also not sure if maybe this information is always available? Maybe some older OS would be available in 32 and 64 bit?
