### ISSUE TITLE
Drop php version=<7.2 Support

### ISSUE THREAD

**Issue by mwkward** [matomo-org/matomo#16452]
[PHP 7.2 will end security support at November 30, 2020](https://www.php.net/supported-versions), So I think Matomo have to end php 7.2 support at Matomo 4 and focus on version 7.3, 7.4, and php 8 for security. [Mediawiki also drop PHP 7.2 support](https://www.mediawiki.org/wiki/Compatibility)

**Comment by tsteur** [comment]
Hi @mwkward thanks for creating this issue. See the discussion in https://github.com/matomo-org/matomo/issues/13611

For now we'll keep supporting PHP 7.2 mostly for the reason that PHP 7.3 didn't really add any features that are very interesting for us. At the same time some users might be still on a supported PHP 7.2.X (eg some LTS) and also through our Matomo for WordPress many users are still using PHP 7.2.X.

If there were more features we were keen on using in PHP 7.3 we would do this. Also if we did set it to PHP 7.3, and people were still using PHP 7.2 they would potentially not upgrade to PHP 7.3 or newer either and instead simply keep using Matomo 3.X which we'd still support for a while.

Generally maybe the point be rather to encourage users to upgrade to a newer PHP versions which I think we already do eg in the system check but this would need to be checked.

**Comment by mwkward** [comment]
Okay. I close this issue.
