### ISSUE TITLE
Some UI test failed screenshots aren't uploaded

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16454]
See https://travis-ci.org/github/matomo-org/matomo/jobs/728828102#L1313 and https://travis-ci.org/github/matomo-org/matomo/jobs/728828101#L1139-L1214

none of them appear in https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/42529/

seems this is maybe happening when there's eg an issue to get the right selector? is it in this case maybe not even taking a screenshot and thus not uploading it?

@diosmosis do you maybe know why that is?

**Comment by diosmosis** [comment]
@tsteur the expect was never reached in the test. There is still a screenshot taken, however (added w/ the puppeteer changes), see: https://travis-ci.org/github/matomo-org/matomo/jobs/728828102#L1501

It's visible in the processed screenshots directory, eg, https://builds-artifacts.matomo.org/matomo-org/matomo/4.x-dev/42529/processed/should_be_possible_to_show_recovery_codes_step1_authentication_failure.png

**Comment by tsteur** [comment]
thanks that's what I thought
