### ISSUE TITLE
Installation shows textarea field with diagnostics results

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16470]
is it on purpose we show this during installation? i'm thinking it's not needed to show the textarea and could be removed (the buttons could be useful).

![Screenshot from 2020-09-25 09-13-00](https://user-images.githubusercontent.com/466765/94201077-92c1fb00-ff0f-11ea-95d0-c9aa5ef97bf3.png)

**Comment by mattab** [comment]
Also can we hide the "Informational results" section from the installer as it's not useful there and can slow down installation/make it appear more complex?
![Screenshot from 2020-09-25 09-18-19](https://user-images.githubusercontent.com/466765/94201453-1ed42280-ff10-11ea-8512-164a0af37278.png)

**Comment by tsteur** [comment]
Yes it is needed because otherwise copy feature won't work. And the informational results are useful for troubleshooting installation issues with us.
