### ISSUE TITLE
Document the new Page Performance reports in a FAQ

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16488]
It would be great to document the new valuable **Page Performance reports** in a FAQ: https://github.com/matomo-org/matomo/pull/15736 - the description of this issue (slightly updated) could work as a simple FAQ. eg. "How do I see page performance reports?" or better

**Comment by sgiehl** [comment]
@mattab  I've created a draft. Feel free to adjust and/or publish it.

**Comment by tsteur** [comment]
https://matomo.org/faq/how-to/how-do-i-see-page-performance-reports/ it's published.
