### ISSUE TITLE
Explain how to re-enable plugins after a major update

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#16483]
During a major update (e.g. to Matomo 4) all plugins that are not compatible (which are probably all non-core plugins) get disabled.

After the update users have to update all plugins (so they get the 4.x-compatible version) and re-enable them.
Ideally there would be some info (maybe a dismissable notification) that explains this.

**Comment by tsteur** [comment]
fyi before starting the update Matomo mentions the list of plugins that may be disabled, and with the recent updater improvements it also shows after the file update which plugins were disabled in the update log. Of course if this information is not seen that's not visible anymore unless maybe [ActivityLog](https://plugins.matomo.org/ActivityLog) is used.

**Comment by Findus23** [comment]
It turns out there is indeed a quite obvious message about plugins that will be disabled. I missed it the last time as I manually replace the files instead of using the updater. 

![grafik](https://user-images.githubusercontent.com/6266037/95661771-375c5380-0b32-11eb-8cea-4081a0ab9410.png)

Unless other people notice this too, this might be enough of an information for users.

**Comment by sgiehl** [comment]
Wondering if it would make sense to check for plugin updates before that screen is displayed, so it's possible to show wich plugins will be updated and which are deactivated :thinking:

**Comment by Findus23** [comment]
If we want to take them as a comparison: Nextcloud has a nice overview next to the "an update is available" screen that lists the plugins that don't have updates that add compatibility with the future version.

I am just not sure if this is a core feature or a plugin (and I can't check as https://apps.nextcloud.com/ seems down at the moment).
