### ISSUE TITLE
Content reports: don't show option to view table with all columns

### ISSUE THREAD

**Issue by twi123** [matomo-org/matomo#16505]
Matomo 3.14.1

Content Interactions not shown in UI report, but clearly visible via API requests (or during the creation of a segment based on  User Interactions with content) 

Steps to reproduce:

1. setup counter for site
2. go to your site and open js console
3. call `_paq.push('trackContentImpression','PublicationOne','PublicationText', 'https://example.com/news/123');` in console as many times as you wish
4. notice to passing requests to `index.php` with `c_n`, `c_p`, `c_t` parameters
5. go to Matomo interface (Dashboard for selected Site -> Visitors log) and see this "user activity" (as content impressions)
6. now back to console and call `_paq.push('trackContentInteraction','click','PublicationOne','PublicationText','https://example.com/news/123');` few times
7. notice to passing requests to `index.php` with `c_i`, `c_n`, `c_p`, `c_t` parameters
8. switch back to Matomo interface (Dashboard for selected Site -> Visitors log) and see this additional "user activity" (as content interactions)
9. now go to Behavior -> Contents -> Content Names for current date

And notice that we have counted content impressions but empty content interactions.
Anyway if we click on "Export this dataset in other formats" and choose some format for export (like HTML for example), we get a nice table WITH CORRECT `nb_interactions` numbers!

For example:

`/index.php?module=Contents&action=getContentNames&idSite=6&period=day&date=2020-09-30&segment=&showtitle=1&random=4231`
and I got this:
Content Name | Visits | Unique visitors | Actions | Actions per Visit | Avg. Time on Website | Bounce Rate | Conversion Rate
-- | -- | -- | -- | -- | -- | -- | --
Вася опубликовал новость от 13.13.2013 | 50% 3 | 50% 3 | - | - | 0s | 0% | 0%
Публикация | 50% 3 | 50% 3 | - | - | 0s | 0% | 0%
Totals | 100% 6 | 100% 6 | - | - | - | - | -

Note on empty "actions" column

But with this `/index.php?module=API&method=Contents.getContentNames&idSite=6&period=day&date=2020-09-30&segment=&format=HTML&token_auth=...`
i got this:

label | nb_uniq_visitors | nb_visits | nb_impressions | nb_interactions | interaction_rate | _metadata | _idSubtable
-- | -- | -- | -- | -- | -- | -- | --
Вася опубликовал новость от 13.13.2013 | 3 | 3 | 6 | 11 | 183.33% | 'segment' => 'contentName==%D0%92%D0%B0%D1%81%D1%8F+%D0%BE%D0%BF%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%BE%D0%B2%D0%B0%D0%BB+%D0%BD%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D1%8C+%D0%BE%D1%82+13.13.2013' | 1
Публикация | 3 | 3 | 5 | 6 | 120% | 'segment' => 'contentName==%D0%9F%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F' | 2

Note on `nb_interactions` column (nevermind of too much interactions -- result of manual `_paq.push('trackContentInteractions'...)` calls via js console for testing purposes)

As I can see, a call method `getContentNames` via module `Contents` returns different results with calling method `Contents.getContentNames` from module `API`.
Is it normal? Or I miss something?

**Comment by tsteur** [comment]
@twi123 this table here:

![image](https://user-images.githubusercontent.com/273120/94862086-f9599280-0494-11eb-9097-38e21c96a4f1.png)

should actually look more like this table?

![image](https://user-images.githubusercontent.com/273120/94862146-0bd3cc00-0495-11eb-9a0a-98684aa41130.png)

(source: https://demo.matomo.org/index.php?module=CoreHome&action=index&idSite=62&period=day&date=yesterday#?idSite=62&period=day&date=yesterday&segment=&category=General_Actions&subcategory=Contents_Contents )

Maybe you need to switch back the visualisation to "Display simple table"?

![image](https://user-images.githubusercontent.com/273120/94862236-302fa880-0495-11eb-8a1a-7f4e807c73e4.png)

**Comment by twi123** [comment]
Khm... Maybe you right, thnx a lot! 
"Display simple table" shows me "content interactions" counters.
But what  "Action" means in "Content Name" report? What is "action" in terms of content interaction?

**Comment by tsteur** [comment]
It has no meaning AFAIK and shouldn't be shown

**Comment by tsteur** [comment]
I've renamed the title @twi123 to disable that option as it should not be shown

**Comment by twi123** [comment]
> It has no meaning AFAIK and shouldn't be shown

Thank you for clarify!
