### ISSUE TITLE
Getting an error when loading  "Email eports" page

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16501]
Got this report by email:

> Key "15" for array with keys ", 8, 9, 2, 3, 4, 13, 14, 23, 27, 1, 11, 24" does not exist. in /home/wp/disk/wordpress/matomo/plugins/ScheduledReports/templates/_listReports.twig 46 using PHP 7.4.8

Error when opening the Email Reports page.

**Comment by tsteur** [comment]
You probably deleted a segment that was used in a report or so. As it's not a regression and bit more work to maybe cleanup reports that contain segments etc maybe can move this out of the RC?

**Comment by tsteur** [comment]
Or as part of this issue we could simply avoid the twig error and then create a new issue to later find a solution for when segments get deleted and it affects other places (which is likely not straight forward)

**Comment by tsteur** [comment]
won't create a separate issue for now for cleaning up reports that are referenced to segments under circumstances
