### ISSUE TITLE
Matomo Heat map

### ISSUE THREAD

**Issue by GJoel01** [matomo-org/matomo#16508]
We've used heatmap plugin and the data are not getting captured. While troubleshooting we see that a 414 Request-URI Too Large error was popping up while inspecting the website. 

Need assistance.

**Comment by tsteur** [comment]
@GJoel01 for support for our premium features could you reach out to our support through shop@innocraft.com ? They will be happy to help you. Be great to let them know what kind of webserver your site is using if you know. For example "apache" or "nginx".

**Comment by GJoel01** [comment]
No one answered there. Could you help me here?
