### ISSUE TITLE
Integrity Checker is incorrect for CustomVariables and Provider

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#16517]
reported in https://forum.matomo.org/t/integrity-check-misses-files-from-removed-customvariables-and-provider-plugins/38827

see also https://github.com/matomo-org/matomo/pull/16415
I am not entirely sure what the issue is exactly. 

When downloading the beta zip, both the integrity checker lines for `plugins/CustomVariables/.github/workflows/translations.yml` and the file itself exists, but the rest of the plugin (the actual code) is missing.

Maybe this is caused by https://github.com/matomo-org/matomo-package/pull/112

**Comment by MichaIng** [comment]
This is still an issue:
- A Matomo update recovers files for the `CustomVariables` and `Provider` plugins, even that those have been uninstalled before.
- The can be uninstalled again, doing so leaves integrity check errors for `CustomVariables`:
    ````
    Errors below may be due to a partial or failed upload of Matomo files.
    --> Try to reupload all the Matomo files in BINARY mode. <--

    Missing file: /var/www/matomo/plugins/CustomVariables/angularjs/manage-custom-vars/manage-custom-vars.controller.js
    Missing file: /var/www/matomo/plugins/CustomVariables/angularjs/manage-custom-vars/manage-custom-vars.directive.html
    Missing file: /var/www/matomo/plugins/CustomVariables/angularjs/manage-custom-vars/manage-custom-vars.directive.js
    Missing file: /var/www/matomo/plugins/CustomVariables/angularjs/manage-custom-vars/manage-custom-vars.directive.less
    Missing file: /var/www/matomo/plugins/CustomVariables/angularjs/manage-custom-vars/manage-custom-vars.model.js
    Missing file: /var/www/matomo/plugins/CustomVariables/API.php
    Missing file: /var/www/matomo/plugins/CustomVariables/Archiver.php
    Missing file: /var/www/matomo/plugins/CustomVariables/Categories/CustomVariablesCategory.php
    Missing file: /var/www/matomo/plugins/CustomVariables/Categories/CustomVariablesSubcategory.php
    Missing file: /var/www/matomo/plugins/CustomVariables/Columns/Base.php
    Missing file: /var/www/matomo/plugins/CustomVariables/Columns/CustomVariableName.php
    Missing file: /var/www/matomo/plugins/CustomVariables/Columns/CustomVariableValue.php
    Missing file: /var/www/matomo/plugins/CustomVariables/Commands/Info.php
    Missing file: /var/www/matomo/plugins/CustomVariables/Commands/SetNumberOfCustomVariables.php
    Missing file: /var/www/matomo/plugins/CustomVariables/config/config.php
    Missing file: /var/www/matomo/plugins/CustomVariables/config/test.php
    Missing file: /var/www/matomo/plugins/CustomVariables/config/tracker.php
    Missing file: /var/www/matomo/plugins/CustomVariables/Controller.php
    ...
    ````

**Comment by tsteur** [comment]
maybe while we ship the plugins also within core we could mark the plugins as not uninstallable hard coded? might be enough adding them here? https://github.com/matomo-org/matomo/blob/4.0.0-rc3/core/Application/Kernel/PluginList.php#L34

**Comment by sgiehl** [comment]
@tsteur guess that makes sense

**Comment by MichaIng** [comment]
Sounds reasonable if those are shipped with core intentionally. Does not make much sense to remove plugins which are restored on every update 🙂.
