### ISSUE TITLE
Icons alignment fix

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16510]
Let's backport https://github.com/matomo-org/matomo/pull/16492 fix in 3.x as this is visible by default in many reports (pages, etc) and some people might use Matomo 3.x for 1 year or so

**Comment by sgiehl** [comment]
The fix in #16492 is a way to complex to back-port it to 3.x, as there have been a lot changes for it and font icons are now used instead of images...

**Comment by mattab** [comment]
@sgiehl ok, instead could we maybe patch it to revert what originally caused the icons to go misaligned?

**Comment by tsteur** [comment]
@mattab that can't be done as it was the comparisons feature

**Comment by mattab** [comment]
@sgiehl could we instead do a quick fix / hack? It would be great if we could fix this and release 3.14.2 and feel good about 3.x LTS and hopefully not having to touch it afterwards

**Comment by flamisz** [comment]
Hi @mattab,

I created a PR for this. Really it's a kind of hack, playing with some css attributes, but looking better: (tested on firefox and chrome)

<img width="657" alt="Screen Shot 2021-03-08 at 3 05 54 PM" src="https://user-images.githubusercontent.com/6749509/110265773-3831dc80-8021-11eb-9177-436d842878e0.png">

**Comment by mattab** [comment]
Screenshot looks good to me @flamisz :+1:

**Comment by flamisz** [comment]
the fix was merged, this can be closed now.
