### ISSUE TITLE
How to show ImageGraph UserCountry filtered for specific url visited?

### ISSUE THREAD

**Issue by McFlat** [matomo-org/matomo#16518]
I'm trying to show a image graph that shows visits by country for many urls, so a person can see number of visits per country for a specific webpage url. How can I format the report url to filter `nb_visits` to a given url?

```shell
/index.php?module=API&method=ImageGraph.get&idSite=2&apiModule=UserCountry&apiAction=getCountry&token_auth=anonymous&graphType=horizontalBar&period=month&date=today&width=500&height=250&columns=nb_visits&filter_pattern_recursive=.*
```

<img width="501" alt="Screen Shot 2020-10-04 at 6 23 30 AM" src="https://user-images.githubusercontent.com/43896676/95014150-ab669b00-060a-11eb-9cb3-23ddcb2a04cf.png">

**Comment by tsteur** [comment]
Hi @McFlat you will want to use the segmentation feature see https://developer.matomo.org/api-reference/reporting-api-segmentation

If you have further questions about this be great to ask in our forum as we usually don't reply to questions here: https://forum.matomo.org/ 

Thanks @McFlat
