### ISSUE TITLE
matomo tag stop tracking visitor data suddenly

### ISSUE THREAD

**Issue by moutsima** [matomo-org/matomo#16519]
matomo tag not tracking visitors but the second one is working on the same site with same envirment for the test i can't understand why first tag is not tracking visitors data

**Comment by tsteur** [comment]
Hi @moutsima unfortunately we only handle bug reports and feature requests but not questions/troubleshooting. Could you ask this question in our forum? https://forum.matomo.org/ Ideally you would also provide a bit more information. For example a link to your site be great.
