### ISSUE TITLE
Is the VisitorsGenerator plugin still working?

### ISSUE THREAD

**Issue by TheCrowned** [matomo-org/matomo#16515]
I tried to generate data for the past 100 days

![Screenshot from 2020-10-03 09-55-22](https://user-images.githubusercontent.com/7880569/94986394-ac41f300-055e-11eb-9609-5ec0bda8d04b.png)

which, at least to me, doesn't seem a killer job. It's been running for a solid hour now. Since there is no clear progress displayed on that page, I loaded another tab with Matomo dashboard. This is what I got:

![Screenshot from 2020-10-03 09-55-38](https://user-images.githubusercontent.com/7880569/94986411-d09dcf80-055e-11eb-9733-4cd6a595c9f6.png)

Rebooting my machine, no visits were actually present.

**Comment by sgiehl** [comment]
@TheCrowned  Did you try using the console command to generate visits? That should work!
Haven't tried doing that in the browser for a while, but will have a look if there's a problem with it.

**Comment by Findus23** [comment]
It seems like indeed the Generator doesn't work anymore with 4.x-dev. I get a large amount of error like this:
> 2020/10/04 11:59:34 [error] 931#931: *3046 FastCGI sent in stderr: "PHP message: Error in Matomo (tracker): Tracker API 'cip' was used, requires valid token_auth" while reading response header from upstream, client: 127.0.0.1, server: dev.matomo, request: "GET /matomo.php?action_name=Balle%20de%20jongle%20-%20ExampleShop&idsite=1&rec=1&r=599317&h=1&m=7&s=17&url=http%3A%2F%2Fexample.org%2Fselection%2Fballes-de-jongle-c-26.html&_id=327a27fd1de9b301&_idts=1363475473&_idvc=1&_idn=0&_refts=1363475473&_viewts=1363475473&_ref=http%3A%2F%2Freferrer.example.org%2Fsearch%3Fq%3Dexampleshop%26%3Dclient%253Dms-nokia-wp%26oq%3Dexampleshop%26gs_l%3Dmobile-heirloom-serp.12..0l5.3359.17040.0.17996.34.20.6.6.6.0.358.4860.0j5j5j8.18.0....0...1c.1.34.mobile-heirloom-serp..7.27.4844.n6cb7nkfj8M&cs=iso-8859-1&res=480x800&cvar=%7B%225%22%3A%5B%22_pkc%22%2C%22Balles%22%5D%7D&pf_net=131&pf_srv=627&pf_tfr=97&pf_dm1=302&pf_dm2=64&pf_onl=29&cdt=2020-10-04+00%3A07%3A27&cip=92.90.0.0&token_auth=dd6cd327ea779319dcff2cf8d6379f7b&dp=1 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "dev.matomo"

I guess this is related to the `token_auth` changes.
This also happens when using the console command.

**Comment by sgiehl** [comment]
Generating visits on command line works for me without problems

**Comment by sgiehl** [comment]
I guess I might have found the reason. The matomo-php-tracker package is not in sync

**Comment by sgiehl** [comment]
That only solve one issue. The brute force detection still seems to be a problem. Need to investigate that further
