### ISSUE TITLE
Piecharts aren't shown at full width

### ISSUE THREAD

**Issue by danielmcclure** [matomo-org/matomo#16522]
The Piechart visualisation doesn't render at a usable width. This has been noted on the Events reports and tested in multiple browsers. This issue is present in at least; Matomo Cloud and Matomo for WordPress.

**Appearance in Firefox/Chrome:**

<img width="340" alt="ff-bug@2x" src="https://user-images.githubusercontent.com/2772782/95032325-924b1080-0716-11eb-962b-b671200e7b49.png">

**Appearance in Safari:**

<img width="458" alt="safari-events-piechart-issue@2x" src="https://user-images.githubusercontent.com/2772782/95032215-3f715900-0716-11eb-928e-f4e320ab3bf4.png">

**Comment by tsteur** [comment]
Cheers @danielmcclure
