### ISSUE TITLE
Processing segment data takes to long and skips data.

### ISSUE THREAD

**Issue by Jinzol** [matomo-org/matomo#16525]
Hi,
We have a problem that we have too much data and too many segments and not enough time. We run our archiver with 
`--force-periods=day,week,month --force-data-last-n=2`
The archiver can take upto 4 days and it will finish without any errors. Only when we access the web interface it seems that the graphs are incomplete. It looks like it skipped data between the runs. I know in the past I could increase N to a bigger number then the days it took to process the data. Only with the example above I don't want N=5 and process 5 months of data. Because we don't have the time.

Is there a commando that I can process with day,week,month with a parameter for only processing the last 5 days and keep week,month on the default settings?

I Am looking into date-range but I want it to be dynamic. So I don't have to change that with every new run.

**Comment by tsteur** [comment]
Hi @Jinzol thanks for creating the issue. Unfortunately we don't reply to questions here as we're only handling bug reports and feature requests here. Could you to ask this question in our forum https://forum.matomo.org/ ? 

BTW not sure if https://matomo.org/faq/roll-up-reporting/faq_25754/ would maybe help to process them less often.

In Matomo 4 I think we have already made a few improvements for all this but not sure if the "force date last n" behaviour was changed (probably not). Be great to ask this in the forum and if you can provide any more info to understand the problem better that will be helpful too.
