### ISSUE TITLE
In Matomo 3 add check for max PHP version

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16530]
Matomo 3 won't and can't support PHP 8 (eg because of PHP DI not being compatible with PHP 8 and upgrading would require higher PHP version plus break compatibility for plugins). 

Therefore we need to add a check to `testMinimumPhpVersion.php` for max supported PHP version. 

If the PHP version is < `8.0.0` then we show a notice stating that Matomo 3 is not compatible with PHP 8 and that they should upgrade to Matomo 4. I suppose in `version_compare` as version number we should specify `8.0.0-dev` for the check just in case someone is using PHP 8 alpha, beta or RC?

@Findus23 I think you were running Matomo with PHP 8. Do you remember if it was mostly working?

**Comment by Findus23** [comment]
See also https://github.com/matomo-org/matomo/issues/16183

If I remember correctly, the Matomo application is working mostly fine, but if people have enabled PHP errors to be displayed in the output it breaks Matomo (as Deprecation warnings are shown before the output starts).

So I assume it should work well enough that people are able display the application and see the warning there or during the installer.

**Comment by tsteur** [comment]
So ideally we'd test it in a PHP 8 environment. I see in https://github.com/matomo-org/matomo/pull/16536 there was already a PR made which me be good enough for now but ideally additionally we test using a PHP 8 installation if it was any usable/working then we could show the message differently. Plus in the installer.

We should test:
* Does basic tracking work
* Does basic reporting work
* Does basic archiving work

If eg tracking still works we could remove #16536 again and only show a message in the UI so data will be still connected while using PHP 8.
