### ISSUE TITLE
Morpheous icons missing on dashboard

### ISSUE THREAD

**Issue by aloxe** [matomo-org/matomo#16553]
I installed the beta 4.0.0-b2 by downloading the distribution from Github. Ran the install on Debian 10 and running it. The dashboard miss Morpheus images. The dashboard I am checking is automatically updated to 4.0.0-b3.

i.e. `https://…/matomo/plugins/Morpheus/icons/dist/os/UNK.png`

indeed the icons are not in this location. I checked in the zip file I downloaded and there are not present. Now I see that `icons` is a symlink to another project which might explain this absence of files.

**Comment by sgiehl** [comment]
We are managing some stuff in submodules, like some plugins, libraries and the icons. When downloading the github release they won't be included. Please use the releases published on https://builds.matomo.org/

**Comment by aloxe** [comment]
Thanks for this link, I confess I looked for it without success. You may consider adding this link with [[new beta announces](https://twitter.com/matomo_org/status/1311192815804780550).
