### ISSUE TITLE
first time i've seen time-zone dependent timestamps

### ISSUE THREAD

**Issue by m-poh** [matomo-org/matomo#16568]
So, I hope I've misunderstood something here. Using the reporting API, I was using the timestamp field from actions. I deliver these timestamps through a number of systems and find that for some reason i have timestamps referring to the future. ?

**Comment by tsteur** [comment]
Hi @m-poh unfortunately we don't answer questions in the issue tracker as we only handle bug reports and feature requests here. Do you mind asking this question in our forum? https://forum.matomo.org/c/plugins-platform/11 It be great to also provide more information about which reporting API you are exactly calling and which field you are referring to exactly so it'll be more clear what is happening. Thanks for understanding.  Generally Matomo does not record timestamps in the future so it's likely you are referring to some timestamp in the site's timezone.
