### ISSUE TITLE
Segment "Server time - hour" is using UTC timezone

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16563]
Seems that when we create a segment using the "Server time - hour" dimension, it does match visits using the UTC visit time (hour).

For example creating a segment matching visits from "server time - hour" = 6, it shows visits from 8PM (the website is configured in UTC+2). 

## Reproduced on demo:

![Screenshot from 2020-10-13 12-58-52](https://user-images.githubusercontent.com/466765/95800463-e75cd700-0d53-11eb-9abc-a7bde12e9d35.png)

Also reported by a customer

## Suggested steps:

* confirm it uses UTC always or maybe another time like the actual server time?
* verify whether this applies to all "Server time" segments
* decide whether we want to fix the issue, and convert the time in the website timezone. (Then maybe rename "Server time" to just "Time" or "Visit time")
* (or alternatively, we could maybe rename the segment to `UTC time` instead of `Server time`. but this could be confusing as timezones conversions are hard for everyone)

**Comment by sgiehl** [comment]
Was that one kind of fixed with #18956, or is anything left we should apply?

**Comment by mattab** [comment]
@sgiehl sounds good, as we've renamed the segments to mention UTC so i'll close this
