### ISSUE TITLE
Global list of Excluded IPs shows only one IP

### ISSUE THREAD

**Issue by aloxe** [matomo-org/matomo#16560]
I am using matomo 4.0.0-b3

I recorded 3 IPs on 3 lines in the Global list of Excluded IPs global settings. Not all IPs are visible and the is no hint they are more.

On Firefox 81.0.1 MacOS:
- When I load the page again, only the first record is visible.
- When I focus on the textarea, only the first record is visible.
- When I hit return, in the textarea all lines are visble including the empty line of the return
- When I change the hight of the textarea to `max-content`, i only see two records
- When I change the hight of the auto to `auto`, i only see two records

On Chrome 85.0.4183.121 MacOS
- When I load the page again, only two records are visible.
- When I focus on the textarea, only two records are visible.
- When I hit return, in the textarea all lines are visble including the empty line of the return
- When I change the hight of the textarea to `max-content`, i only see two records
- When I change the hight of the textarea to `auto`, i only see two ½ records which is acceptable as I have visual feedback that there could be more.

**Comment by tsteur** [comment]
Thanks @aloxe 

I can reproduce this 
![image](https://user-images.githubusercontent.com/273120/95782037-73a6d400-0d2b-11eb-8d23-92e4a18bf808.png)
