### ISSUE TITLE
console (cli): Add config:delete to delete a key

### ISSUE THREAD

**Issue by gramakri** [matomo-org/matomo#16576]
There is already a `config:set` to add a key in a section. Would be helpful to have a config:delete to delete a key in a section as well. This would be especially useful when combined with `--value` to remove an entry from array keys like severs[], Plugins[].

**Comment by tsteur** [comment]
Thanks for suggesting this feature @gramakri 

If someone is keen to work on this: It could work similar to https://github.com/matomo-org/matomo/blob/4.0.0-b3/plugins/CoreAdminHome/Commands/SetConfig.php#L19-L86 in a new `DeleteConfig` class. It's probably quite easy to implement and we will be happy to review.

**Comment by mwithheld** [comment]
I've put in a PR for this at
https://github.com/matomo-org/matomo/pull/17956
