### ISSUE TITLE
No Visits logs from Chrome 86 Mobile device

### ISSUE THREAD

**Issue by cibernaio** [matomo-org/matomo#16574]
Hi,
it seems that on Chrome 86.0.4240.99 Android mobile i can't view the Matomo visits log.
If i try the same procedure on actual Chrome 86 Android mobile Beta(86.0.4240.99) version, it correctly log on Matomo.
would you have any idea why it happens?

Thanks,

bye

**Comment by cibernaio** [comment]
Solved, i have "do no track" options to true on Chrome 86,
after switched it to false i have solved.

Thanks

**Comment by cibernaio** [comment]
> Hi @cibernaio.
> Sorry, I'm not sure what your issue is. Is it not possible to view the visits log within Matomo at all or is your visits not tracked by Matomo?

i have a question, could Matomo intercept the flag "do no track" and log somethink like as : the user has flag enabled and i can't log it?


Thanks

**Comment by sgiehl** [comment]
I guess you would like to know the number of visits that had DNT activated, right?
In theory that should be doable with a custom plugin. Tracking requests should still be sent to Matomo as long as `setDoNotTrack` isn't called for the javascript tracker.

**Comment by cibernaio** [comment]
ok thx
