### ISSUE TITLE
Hours issue in visits log (index.php?module=CoreHome&action=index)

### ISSUE THREAD

**Issue by n-gram-hub** [matomo-org/matomo#16586]
Hi, why do I get that :15 (2nd row) before :20 (third) and :19 (fourth)?

[Second, third, fourth row image](https://ibb.co/w6Mvcbq)

**Comment by tsteur** [comment]
Hi @n-gram-hub what you are seeing there is the time the visit started but we sort them by time the visit ended (so active visits are always coming first). For future questions be great to ask in our forum https://forum.matomo.org/ as we usually don't answer questions here. Thanks

**Comment by n-gram-hub** [comment]
Ok, I thought this was a bug
