### ISSUE TITLE
IP exclusion segment produces error when used in eCommerce report

### ISSUE THREAD

**Issue by jmumby** [matomo-org/matomo#16587]
When you create an IP exclusion like below:

![image](https://user-images.githubusercontent.com/4339071/96385639-acdeb880-11f1-11eb-884b-3a4afb08cb72.png)

The segment works fine in all reports except eCommerce produces this error:

![image](https://user-images.githubusercontent.com/4339071/96385660-d1d32b80-11f1-11eb-8bc5-0fcee8749d31.png)

**Comment by sgiehl** [comment]
That should actually be an easy fix. Seems the sanitized segment is used for the processed goals request... Will issue a quick PR to change that...
