### ISSUE TITLE
Track Custom Variables error:  Warning - count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by basos9** [matomo-org/matomo#16596]
Hello,

It seems that custom variables tracking is not working properly. 
The variables are not stored in the databases. 
Also with Tracker debug enabled we can see the following error on a tracking request with custom variables
```
WARNING CustomVariables[2020-10-19 11:52:37 UTC] [e201d] /var/www/matomo/core/Tracker/Request.php(635): Warning - count(): Parameter must be an array or an object that implements Countable - Matomo 3.14.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) [internal function]: Piwik\ErrorHandler::errorHandler(),#1/core/Tracker/Request.php(635),#2/core/Tracker/Action.php(191),#3/plugins/CustomVariables/Tracker/CustomVariablesRequestProcessor.php(76),#4/core/Tracker/Visit.php(174),#5/core/Tracker.php(155),#6/core/Tracker/Handler.php(57),#7/core/Tracker.php(135),#8/core/Tracker.php(112),#9/piwik.php(76)
```

The affected code seems to be 
```
/core/Tracker/Request.php(635)

            if ($id < 1
                || $id > $maxCustomVars
                || count($keyValue) != 2
```

URL decoded url part  for tracking request
```
&_cvar={"1":"[\"ENV\", \"DEV\"]"}&
```

ENV
```
OS debian 10.6
SETUP: NGINX + PHP-FPM
PHP 7.3.19-1~deb10u1 (fpm-fcgi) (built: Jul  5 2020 06:46:45)
Matomo version 3.14.1
Tracking via Javascript Client
```

**Comment by tsteur** [comment]
@basos9 thanks for creating this issue. Are you using the Matomo JavaScript tracker? Or how do you track the data?

**Comment by basos9** [comment]
Hello,
Yes we are using the Javascript tracking client. The url part mentined in my comments above, is extracted via the Network tab of the browser's (Chrome) inspect tools (F12)

**Comment by basos9** [comment]
And I think I have found a clue.
By looking at the url we can see that the cvar url parameter when url decoded is
```
`cvar={"5":"[\"PAGEVAR\", \"http://test.com/test.html\"]"}`
```
and this leads to error in tracking

Now if we change by removing the quotes and make the lvalue of the hash a list (instead of a string), like this
```
`cvar={"5":["PAGEVAR", "http://test.com/test.html"]}`
```

And url encode and hit, no error is logged and data starts to appear in the database

```
               custom_var_k5: PAGEVAR
               custom_var_v5: http://test.com/test.html
```

So i can assume that it might be a javascript client json encoding issue.

**Comment by tsteur** [comment]
Thanks for this @basos9 . Do you know in what browser this happens and whether that site maybe overwrites `JSON` or `JSON.stringify`?

**Comment by basos9** [comment]
Hello,
It happens on major browsers (Chrome, Firefox).
It seems to be related with something in the web page (maybe some JS library), since I was able to successfully track variables by creating a simple html web page with only the tracking code.  We are investigating the issue.

**Comment by tsteur** [comment]
Thanks for investigating. Be great to let us know what you find out.

**Comment by basos9** [comment]
For this webpage we tracked to the inclusion of prototype.js library which was included in our web application.

 The affected file has a header
> Prototype JavaScript framework, version 1.6.0.3

The problem is fixed when we removed this library.

More specifically this library modified (monkey patches) Builtin in Objects like String and Array, defining among others a `.toJSON()` method.

Another example using the Chrome's browser console on our site
```
"test".toJSON()
""test""

JSON.stringify(["king","kong"]);
""[\"king\", \"kong\"]""
```
and on youtube
```
"test".toJSON()
VM529:1 Uncaught TypeError: "test".toJSON is not a function
    at <anonymous>:1:8

JSON.stringify(["king","kong"]);
"["king","kong"]"
```

**Comment by Findus23** [comment]
That version was released in [2008](http://prototypejs.org/2008/09/30/prototype-1-6-0-3-one-more-bugfix-release-before-1-6-1/) meaning it is older than the first release of Internet Explorer 8.

So I guess there is not really much to do as one would need to specifically check for this case which would be weird considering we just dropped support for IE<8.

**Comment by tsteur** [comment]
See eg https://github.com/matomo-org/matomo/issues/2165 prototype is kind of known actually to have caused issues with JSON and there isn't anything we can do unfortunately. Ideally the project would look at removing this dependency but I understand this is a big ask and not easily done. AFAIK the only other way would be that you overwrite again some of these changes that prototype does. Not sure if we can maybe close this issue but document somewhere this incompatibility or so?

**Comment by basos9** [comment]
It seems that this is a library incompatibility issue and the best would be the things mentioned
- either remove the library altogether
- or unpatch the patched buildin objects.

Thank you for helping sort this out.

**Comment by tsteur** [comment]
Noticed we haven't actually documented the requirements / supported browsers anywhere for the JS tracker (at least I couldn't find it) so created https://github.com/matomo-org/developer-documentation/pull/392
