### ISSUE TITLE
remove core:archive output "Checking for queued invalidations / Done invalidating"

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16619]
It would be great to hide the new output text (bold below) in core:archive output in Matomo 4, as this text is not helpful

INFO [2020-10-28 00:31:39] 39985  Starting Matomo reports archiving...
INFO [2020-10-28 00:31:39] 39985  Start processing archives for site 1.
**INFO [2020-10-28 00:31:39] 39985  Checking for queued invalidations...
INFO [2020-10-28 00:31:39] 39985  Done invalidating**
INFO [2020-10-28 00:31:39] 39985  Finished archiving for site 1, 0 API requests, Time elapsed: 0.028s [1 / 2 done]
INFO [2020-10-28 00:31:39] 39985  Start processing archives for site 2.
**INFO [2020-10-28 00:31:39] 39985  Checking for queued invalidations...
INFO [2020-10-28 00:31:39] 39985  Done invalidating**
INFO [2020-10-28 00:31:39] 39985  Finished archiving for site 2, 0 API requests, Time elapsed: 0.011s [2 / 2 done]
INFO [2020-10-28 00:31:39] 39985  Done archiving!

**Comment by tsteur** [comment]
@diosmosis we could set them for now to `debug`? Otherwise we can also leave them there for now and review in a year to first see how practical it is to have it / not have it etc.

**Comment by diosmosis** [comment]
There can be logs in between those two, might be a bit confusing if they show up w/o context. We could make all the invalidating messages debug, I guess.

**Comment by tsteur** [comment]
I have generally no big preference. I reckon often those messages aren't even shown anyway if there are still invalidations left to do etc.
