### ISSUE TITLE
Mention DB Lite DB will be automatically updated (filename etc)

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#16618]
Hi, I know MaxMind put their DB behind API / login, and now Matomo uses db-ip download. For at least a year I have noticed that cities are very wrong, they are not at all accurate as before (countries are still accurate, as I can tell so far).

Today I devoted some time to exploring this issue, and discovered that update db link is hard coded with a date from January 2020. But, Matomo correctly reports that latest db version is from October 2020.

Does this affect downloading latest version or not (see screenshot)? Do we have to manually update this link from time to time?

![matomo-geoip-db](https://user-images.githubusercontent.com/5383059/97358235-4154b500-189b-11eb-83ed-50d4198cd017.png)

**Comment by dev-101** [comment]
Follow-up question: Is there a way to manually trigger geo-ip db update procedure e.g. not to wait next cron cycle to run?

**Comment by Findus23** [comment]
Hi,

As far as I know Matomo internally replaces this link with the current month when e.g. downloading the file.

> Is there a way to manually trigger geo-ip db update procedure e.g. not to wait next cron cycle to run?

`sudo -u www-data php console core:run-scheduled-tasks "Piwik\Plugins\GeoIp2\GeoIP2AutoUpdater.update"` should run the task (not sure if it downloads the file if it isn't old enough)

**Comment by dev-101** [comment]
Thanks, command worked, although I can't ran it on all other shared hosting servers,
I was thinking about internal "button" to manually trigger it from Admin dash.

So, you are probably correct, I have updated to the latest version, or so I think, but the accuracy of the database is very poor. It shows a different city hundred miles away from true location.

I will probably have to register and switch back to MM, since it was spot on.

**Comment by dev-101** [comment]
Yep, switched back to MM (even older version from Dec-2019) and it is so much more accurate, not to mention some 25-30% lighter in size. Now getting latest update...

We have to rename the file to **DBIP-City.mmdb** (otherwise it is not recognized by Matomo if we leave MM name convention).

Matomo docs should be updated about this, unless there is something that I missed?

**Comment by tsteur** [comment]
Matomo indeed replaces the month automatically and downloads up to date file without needing to do anything.

**Comment by dev-101** [comment]
Thanks, I did not close this issue right away, even if I resolved it personally in my case.
You might consider expanding information on Geolocation page in Admin Dash to clarify few things, e.g. regarding file names of 2 alternatives (DB-IP vs MaxMind) and such :)

**Comment by tsteur** [comment]
sure I can reopen the issue and adjust the title in case someone wants to do a PR

**Comment by nina-py** [comment]
I think there might be a better way to improve the usability of this page than just adding an explanation. The URL in the form field - the one that @dev-101 reported as obsolete - is saved in the options at the time of the initial Matomo install. 

Why not update this URL each time it changes when the updater task runs to download the latest copy of the geolocation database? Then users will either see that the URLs in the screenshot above match as they have the latest copy of the database or at most that it's a month out of date - and if that's the case, once they scroll further down the page and see when the updater runs next, the discrepancy becomes self-explanatory. Will add a PR for this shortly and will be happy to make any changes to it as you see fit, @tsteur.
