### ISSUE TITLE
Finding Page Views for Matomo

### ISSUE THREAD

**Issue by revathi-muthana123** [matomo-org/matomo#16647]
Hello Team,

In Matomo we can able to check Page Views per day or per month basis for individual website. But how we can summarize Page views per month for all the websites at a time? 

Please help me to find out Number of page views in over all Matomo.

Thanks & Regards
Revathi

**Comment by sgiehl** [comment]
Hi @revathi-muthana123 

If you have multiple websites configured in Matomo you can view a summary in the "All websites" dashboards. If those numbers are not enough, maybe the RollUpReporting plugin is what you are looking for: https://plugins.matomo.org/RollUpReporting

If you have any other questions like this, please have a look at our forum at https://forum.matomo.org. We are only handling bugs and feature requests here...
