### ISSUE TITLE
Website time zone setting for Canada - Whitehorse and Canada - Dawson does not observe now-permanent UTC-7

### ISSUE THREAD

**Issue by ygdaverogers** [matomo-org/matomo#16657]
As of March 8, 2020, the Yukon Territory of Canada no longer changes its clocks to observe different standard or daylight saving times. That means Yukon is now permanently UTC-7 (the same as MST at the moment). See https://yukon.ca/time for details.

The "Canada - Whitehorse" and "Canada - Dawson" time zone regions are both in Yukon and should observe that change.

_Please note that "Canada - Dawson Creek" is not in Yukon and not part of this time zone change._

Our Matomo installation insists that Canada - Whitehorse is on Pacific Standard Time (UTC-8) even though the underlying OS has the update for the new Yukon Standard Time and is configured as "America/Whitehorse". This means that web hits are tagged one hour behind the time in Yukon.

The workaround for now is to use the Phoenix, Arizona time zone setting as most of Arizona observes year-round UTC-7.

The same adoption of year-round daylight saving time is expected for British Columbia, Washington, Oregon, and hopefully California before long.

Please update the time zone policy for "Canada - Whitehorse" and "Canada - Dawson" to be permanently set to UTC-7.

Thanks from Canada's North!

**Comment by tsteur** [comment]
Thanks for creating this issue @ygdaverogers 

This might be an issue with PHP @sgiehl @Findus23 ?

**Comment by sgiehl** [comment]
The timezones in PHP can be updated with the pecl package timezonedb. If that one isn't installed or updated PHP will use the timezones shipped with the PHP version. Depending on how old the PHP version is, the timezones might not be up to date.
Guess that is the reason why PHP marked a lot timezones as "do not use". See https://www.php.net/manual/en/timezones.others.php

We actually could add a diagnostic check to check the version of timezonedb installed. That can be achieved with `timezone_version_get()`. On some systems that might return `0.system` if the one shipped with PHP is used. Latest version would be 2020.04. See https://pecl.php.net/package/timezonedb

**Comment by ygdaverogers** [comment]
Thanks very much for that. I'll have our infrastructure folks work on the PHP setup. "Sorry"--said the Canadian--for taking your time on a PHP issue.

**Comment by tsteur** [comment]
@sgiehl added https://github.com/matomo-org/matomo/pull/16660 so we have it in the system check. We can then close the issue.
