### ISSUE TITLE
Replace whitelist/blacklist terms

### ISSUE THREAD

**Issue by fridobox** [matomo-org/matomo#16659]
Hi,

Using whitelist/blacklist is outdated, you should replace with allow/deny list for inclusive language.

See for example https://www.ncsc.gov.uk/blog-post/terminology-its-not-black-and-white

Regards,

**Comment by sgiehl** [comment]
We have already replaced some of the visible parts. e.g https://github.com/matomo-org/matomo/pull/16413 or https://github.com/matomo-org/referrer-spam-list/issues/1224

If anyone is keen on helping with the remaining occurrences, feel free to create pull requests. I don't think this will be worked on with highest prio on our side, as most parts should be in the code only and not visible in the UI. But I guess if we need to work on a part that contains such stuff, we will likely replace it...

**Comment by fridobox** [comment]
Ok thanks a lot for your answer

**Comment by skylarmt** [comment]
This is a waste of time.  There isn't anything offensive about colors.
