### ISSUE TITLE
Video and Audio file mixed up (Report)

### ISSUE THREAD

**Issue by Osomo3000** [matomo-org/matomo#16666]
Hello,

It seems like there is a bug in the Matomo Framework that causes audio and video files to be mixed up. This results in audio files being displayed as videos and vice versa.

**Comment by sgiehl** [comment]
@Osomo3000  Are you using the media analytics plugin?

**Comment by Osomo3000** [comment]
Yes, the media analytics plugin is enabled.

**Comment by sgiehl** [comment]
For support for our premium features it's best to contact shop@innocraft.com directly as this issue tracker is purely for issues around the Matomo core. If you haven't contacted our support yet, be great to send us an email .

Thanks
