### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by outrecording** [matomo-org/matomo#16679]
Hi, I just wanted to pass along this info. I was going through the various reports and most weren't loading up. They had some error causing them not to show. Then when I went to a different report I got a site fatal error. Luckily everything was fine with my site. Attached is a screenshot of the error.
Thanks!
![Error-Page](https://user-images.githubusercontent.com/44663137/98433651-e2e1cf00-2103-11eb-93ed-af72b90aa518.jpg)

**Comment by tsteur** [comment]
Thanks for creating this issue @outrecording Very appreciated. We've heard this recently a few times and unfortunately the only way to fix this be to upgrade the PHP version if any possible. It appears to be some bug in a PHP version. See also https://github.com/matomo-org/matomo/issues/16613 for more information.
