### ISSUE TITLE
Manage Containers page not found

### ISSUE THREAD

**Issue by zsjie** [matomo-org/matomo#16672]
I host matomo 3.14.1 on my own server, following the [installation docs](https://matomo.org/docs/installation/) and everything works fine except the **Manage Containers** page in **Tag Manager** can not be load, as you can see below:

![image](https://user-images.githubusercontent.com/6982248/98198788-c4919d00-1f64-11eb-82d1-af698c8b551c.png)

Matomo helps a lot and I've bought two plugins, Heatmaps and User flows, from the marketplace. And I also need to use tag manager, please help!

**Comment by zsjie** [comment]
I use Safari to open this page, and it looks it's ok. But the page is still not loaded in Chrome.

![image](https://user-images.githubusercontent.com/6982248/98205169-97e48200-1f72-11eb-8ba0-2fb3d63a06e7.png)

**Comment by Findus23** [comment]
Hi,

See also 
https://github.com/matomo-org/matomo/issues/15717
https://github.com/matomo-org/matomo/issues/13940
https://github.com/matomo-org/tag-manager/issues/140
https://github.com/matomo-org/tag-manager/issues/132
https://github.com/matomo-org/tag-manager/issues/147
https://forum.matomo.org/t/tag-manager-blank-screen/31704
for more people having the same issue. I assume most likely the browser cache still contains the old JS file before updating. Or your adblocker is blocking something important. Or you are using something like mod_pagespeed that modifies the page.

**Comment by Absynth723** [comment]
I am having this issue on Safari Version 14.0.1 (15610.2.11.51.10, 15610) on MacOS X. There's no mod_pagespeed activated on nginx, there's nothing in the logs and the new "tracker blocking" feature in Safari claims to not have blocked any trackers on the page (which would be weird anyway, because it's 1st party js code). I have no adblocker installed, no pihole, nothing. 
Everything works on Chrome on the same machine. 
Which is the most active bug report for this (from the 6 that you posted), @Findus23? I could try and dig a little deeper and comment on that most active report.

**Comment by tsteur** [comment]
Hi @absynth47215 are you familiar with the browser developer tools? Could you check if any network requests fail or if there is any console message?

**Comment by Absynth723** [comment]
There is no message at all, no js error or warning, no failed request in the console. It just didn't render. 

After using the "delete cache" option in Safari's developer tools, the container management page started to render, so the **notion that it is a browser cache issue seems to be right**. Interestingly enough, I had tried to force re-fetch of all resources by appending a bogus cachebuster query parameter, but that didn't seem to do anything. 

I'd expect it to continue to render from now on. In my opinion, this is an issue only directly after tag manager installation, so maybe you can find a way to force browser cache clearing (no idea how to go about that, I'm more of a backend guy).

**Comment by tsteur** [comment]
@absynth47215 there should be a cache buster that forces the reloading. Also the force re-fetch should have worked.
![image](https://user-images.githubusercontent.com/273120/101082254-09fec400-3610-11eb-841b-6fbb8472fdfd.png). Maybe it's some webserver configuration that specific headers were sent that made it believe somehow there's no newer version (like same etag somehow or something). I suppose you aren't using any CDN or something as part of Matomo? Like proxying requests through cloudflare or cloudfront or something?

**Comment by Absynth723** [comment]
@tsteur It's a run-of-the-mill nginx with PHP-FPM, standard vhost config. The only thing that is non-standard might be this:
        `location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
                expires max;
                log_not_found off;
        }`
Might be interesting to see what configuration others with the same issue are running. I expect it to be some kind of borderline case, but an interesting one.

**Comment by tsteur** [comment]
Thanks for this @zsjie I had a very quick look at the code and maybe found an issue (not sure). Created for now https://github.com/matomo-org/matomo/pull/16880 and there's a chance this will fix it in the future.

**Comment by j-maas** [comment]
I encountered this issue as well. In Firefox, opening the history panel, right-clicking on the website, and choosing "Forget complete website" did *not* work. I logged back in and still only saw an empty page.

However, disabling tracking protection (the shield in the URL bar) reloaded the page correctly. Even after reactivating tracking protection, it seems to work now.
