### ISSUE TITLE
Update campaign builder with new parameters group and placement

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#16682]
In https://github.com/matomo-org/plugin-MarketingCampaignsReporting/pull/55 we've added new parameters for campaign group and placement.

The campaign builder within the app as well as the one on the website should be changed accordingly.

**Comment by tsteur** [comment]
👍  moved this into 4.x. There's also https://github.com/matomo-org/plugin-MarketingCampaignsReporting/issues/56

**Comment by tsteur** [comment]
@sgiehl can you have a look at this one tomorrow?
