### ISSUE TITLE
Fix logviewer UI tests

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16700]
They seem to be failing see https://travis-ci.com/github/matomo-org/matomo/jobs/432697075#L1211-L1286 but don't generate any processed screenshot

**Comment by sgiehl** [comment]
Those tests are failing randomly. In some cases the javascript seems not to load correctly, in others the css seems missing. Wasn't able to reproduce the failures locally yet

**Comment by tsteur** [comment]
👍  didn't know they fail randomly. Will close for now
