### ISSUE TITLE
Matomo couldn't write to some directories

### ISSUE THREAD

**Issue by DaCharat907** [matomo-org/matomo#16706]
Today for some reason Matomo stopped working and issuing the following screen:

> Matomo couldn't write to some directories (running as user 'apache').
> 
> Try to Execute the following commands on your server, to allow Write access on these directories:
> 
> chown -R apache:apache /var/www/html
> find /var/www/html/tmp -type f -exec chmod 644 {} \;
> find /var/www/html/tmp -type d -exec chmod 755 {} \;
> find /var/www/html/tmp/assets -type f -exec chmod 644 {} \;
> find /var/www/html/tmp/assets -type d -exec chmod 755 {} \;
> find /var/www/html/tmp/cache -type f -exec chmod 644 {} \;
> find /var/www/html/tmp/cache -type d -exec chmod 755 {} \;
> find /var/www/html/tmp/logs -type f -exec chmod 644 {} \;
> find /var/www/html/tmp/logs -type d -exec chmod 755 {} \;
> find /var/www/html/tmp/tcpdf -type f -exec chmod 644 {} \;
> find /var/www/html/tmp/tcpdf -type d -exec chmod 755 {} \;
> find /var/www/html/tmp/templates_c -type f -exec chmod 644 {} \;
> find /var/www/html/tmp/templates_c -type d -exec chmod 755 {} \;

I have run these and also tried upping to 777 but had no luck getting back in.

As far as I'm aware no updates happened to matomo or the server in the past 24 hours to make this an issue.

As you can see bellow the tmp folder has the right permissions:
`drwxr-xr-x. 10 apache apache   4096 May 13  2020 tmp`
`drwxr-xr-x.   2 apache apache 4096 Nov 12 08:05 assets`
`drwxr-xr-x.   3 apache apache 4096 May 13  2020 cache`
`drwxr-xr-x.   2 apache apache 4096 Nov 12 08:05 climulti`
`-rw-r--r--.   1 apache apache   20 Nov 12 08:05 index.htm`
`-rw-r--r--.   1 apache apache   20 Nov 12 08:05 index.php`
`drwxr-xr-x.   3 apache apache 4096 Nov  4 02:06 latest`
`drwxr-xr-x.   2 apache apache 4096 Jul 22 13:00 logs`
`drwxr-xr-x.   2 apache apache 4096 May 13  2020 sessions`
`drwxr-xr-x.   2 apache apache 4096 May 13  2020 tcpdf`
`drwxr-xr-x. 189 apache apache 4096 Nov 12 00:16 templates_c`

Any ideas?

**Comment by Findus23** [comment]
Hi,

Just as a wild guess: Is there disk space left on the server or any other reason a write to disk might fail?

**Comment by Pres3c** [comment]
> Hi,
> 
> Just as a wild guess: Is there disk space left on the server or any other reason a write to disk might fail?

Might be onto something there. Will take a look.

**Comment by Pres3c** [comment]
> Hi,
> 
> Just as a wild guess: Is there disk space left on the server or any other reason a write to disk might fail?

Nope, only 14% used of 100+ GB. I'm going to try rebooting again and I'll do some chkdsk to see if there are any issues. But at the moment I don't think there is.
