### ISSUE TITLE
Clarify that tracking ISP data requires Provider plugin

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#16712]
As of Matomo 4 the Provider plugin is no longer part of core. Even though we still ship it together, the plugin is deactivated by default.

In the Geolocation admin it is always possible to configure an ISP database. But actually the ISP/ORG information gathered through that database will only be stored if the Provider plugin has been installed (e.g. the location_provider column exists) and won't be shown unless it is activated.

We should disable that field if the plugin isn't activated and add a note that the Provider plugin is required in order to use an ISP database.

Also we might need to check if it doesn't make any further problems that a [dimension](https://github.com/matomo-org/matomo/blob/4.x-dev/plugins/UserCountry/Columns/Provider.php) in core exists that requires a column that is installed by a plugin. Maybe it would be better to move those parts to the Provider plugin

**Comment by tsteur** [comment]
@sgiehl I'll disable the dimension through custom reports. I'm thinking maybe we could move the dimension to the plugin in Matomo 5 and during transition period keep it in Matomo 4 so no schema changes will happen or so should the plugin be activated etc.

For the admin could we create a separate issue or could you create a PR to mention it requires the Provider plugin to be enabled should it not be enabled?

**Comment by sgiehl** [comment]
> For the admin could we create a separate issue or could you create a PR to mention it requires the Provider plugin to be enabled should it not be enabled?

Will create a PR

**Comment by sgiehl** [comment]
Btw. @thomas. Moving that dimension should not trigger a database change, as the definition is already in the provider plugin. So it should be possible to do that anytime.

**Comment by tsteur** [comment]
Good one @sgiehl didn't notice. If it's not used in any other way then feel free to move that logic to the provider plugin. Moving this to Matomo 4.1
