### ISSUE TITLE
Goal conversions wrongly formatted when using German language

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16726]
See https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=year&date=2020-11-15&segment=&category=Goals_Goals&subcategory=General_Overview when selecting `Deutsch` (German) in the language selector.

![image](https://user-images.githubusercontent.com/273120/99317481-00b0f000-28cb-11eb-8baf-bcfdffabc58c.png)

You can see eg conversions should be "232469" but it is shown as `232,47` in German which means `232.47` in English. So the shown value is 1000 times lower than expected. This also applies to the other goals on the same page

![image](https://user-images.githubusercontent.com/273120/99317553-20e0af00-28cb-11eb-8e05-4bc1c852ad20.png)

and it applies to the individual goal pages

![image](https://user-images.githubusercontent.com/273120/99317592-2dfd9e00-28cb-11eb-82f6-813bc1319acd.png)

Was wondering if it is maybe related to https://github.com/matomo-org/matomo/issues/15262 but don't think so.

@sgiehl maybe we already have an issue for this? Couldn't find anything. I suppose it's not an easy fix? (just asking in case you remember from previous fixes)

**Comment by sgiehl** [comment]
there are #15356, #15200, #15346 and maybe even a few others. In most cases there was "simply" a number formatting where it was already done. Will have a quick look if it's easy to fix here
