### ISSUE TITLE
Use `hiddenkeyword` for Search engines by default

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#16742]
while this mostly affects https://github.com/matomo-org/searchengine-and-social-list/ I think this should be changed in Matomo itself
reported in https://forum.matomo.org/t/search-engines-in-the-list-of-websites/37192/12?u=lukas

Matomo doesn't detect a lot of search engines anymore as the detection assumes that the referrer URL contains the search query specified in the search engine list. But hardly any search engine sends it anymore, so it doesn't work.

As a workaround it seems like the `hiddenkeyword` keyword was added to the yaml file to specify the URL that is used to do the redirect over and which will be then the referrer URL.

But as referrer policy and such things are now widespread, no one opens links via redirects anymore and this is again pointless.

One could fix this issue by adding

```yaml
hiddenkeyword:
  - '/^$/'
  - '/'
```

to every search engine in the list, but at this point the setting becomes useless and instead I think Matomo should instead handle every referrer URL like `https://www.startpage.com/` as a search engine independent on the exact URL or query parameters.

**Comment by sgiehl** [comment]
Guess it would make sense to simply assume the hiddenkeyword values as default if there is non defined by the search engine

**Comment by tsteur** [comment]
sounds like an easy fix? I assume it's unlikely a search engine links to you anyway :)

**Comment by sgiehl** [comment]
That's very easy. Will create a PR for it.
