### ISSUE TITLE
SEO Plugin broken

### ISSUE THREAD

**Issue by GieltjE** [matomo-org/matomo#16778]
After upgrading to 4.0.0 the SEO plugin appears to be broken quite badly, no extra php error log is given.

index.php?date=today&module=SEO&action=getRank&disableLink=0&widget=1&idSite=10101&period=day
Call to a member function getRows() on null
in core/DataTable/Renderer.php line 446

**Comment by sgiehl** [comment]
Hi @GieltjE 
Thanks for the report. I'm able to reproduce that locally and will have a quick look.
