### ISSUE TITLE
Improve no data tracked yet please set up tracking code screen

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16787]
The goal of this issue is to improve the "No data has been recorded yet, get set up below" screen which users see when they haven't tracked any data yet.

So far we're showing seven different ways of embedding the tracking code and there's a lot of text and it is quite tricky for people to figure out what to do.

## Step 1: detection of site

We currently have guides for WordPress | Squarespace | Wix | SharePoint | Joomla | Shopify. When a site is created, can we try to fetch the content of the site and try to detect what CMS is being used? Eg WordPress would typically have some URLs with `wp-content/` in the HTML. Important be to have a timeout of say 5 seconds as some URLs won't be reachable (eg internet is disabled or many other reasons) and we don't want to delay the site creation too much.

If any of these CMS was detected, then we could say something like "It seems you're wanting to track a WordPress website, check out our integration guide for WordPress websites to get started".

Additionally, if we detect they use Google Tag Manager then we should also offer a new guide

## Step 2: Use of tabs

If we detected a system that we have a guide or integration for, then we expand the Integrations tab by default. Otherwise we show "Tracking code" first

The Matomo Tag Manager embed instructions should include already the JS code to embed the MTM into their website.

In the intro text there is a distracting like to "tracking code" page which we remove and instead we have a link to customise the tracking code as part of the tracking code tab section. And we add a link to simply email developers (it's already there but we simplify this).

A "other" group would list mobile apps, log analytics, and other ones that are more rarely used. It should again mention Google Tag Manager as part of the other section.

Could look like screen below but needs to be optimised as those tabs are not quite readable or noticeable that it's tabs maybe.
![image](https://user-images.githubusercontent.com/273120/100163290-3b91d400-2f1a-11eb-8392-cb36ad36c69d.png)

Note: currently not visible there is the button to "hide this message for 1 hour" which should be still there.

**Comment by flamisz** [comment]
Hi @tsteur, I have a question for the Matomo Tag Manager tab.

> The Matomo Tag Manager embed instructions should include already the JS code to embed the MTM into their website.

If the tag manager is not active or we don't have a published container yet, we can not show any js code. Is that correct? In that case we can provide a small explanation and link to the guide.

If we have any published container we can show tracking code, but which one? Do we want to add a select on this page?

**Comment by tsteur** [comment]
> If the tag manager is not active or we don't have a published container yet, we can not show any js code. Is that correct? In that case we can provide a small explanation and link to the guide.

That's correct. We should be creating a container though as part of the site creation. So whenever a site is created, then we create a container. Not sure if this happens also during installation and of course someone could delete it so would need to check for it 👍 

I would say we could simply show the one for`Live` for now but could also show a select if it's easy to do.
