### ISSUE TITLE
If only one website exists, remove the site selector from reporting page

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16789]
In past we had kept it there so people would notice they can track different sites with it. However, the "all websites" screen achieves the same. 

Having less controls makes the UI easier, and also makes it easier when no data has been tracked yet.

We could keep it though if we add a link "Add new site" after "all websites". This link would however only appear to super users so for other users the site selector be still useless. I'd prefer to remove the site selector therefore when there is only one site. 

Here's a screenshot of our demo
![image](https://user-images.githubusercontent.com/273120/100158522-31b7a300-2f11-11eb-9c19-d457ec0c6b1d.png)

**Comment by mattab** [comment]
I'm not sure if this helps, as for context and knowing "what we're looking at" it's usually quite helpful to see the website name clearly in the screen. (and it's nice that it appears in screenshots.) 

Otherwise it might be hard to know what people are looking at. So I'm not 100% sure about this one :thinking:

**Comment by tsteur** [comment]
People who have only one website 100% know what they are looking at. 

Also for say > 90% this would make UI easier so we shouldn't make it worse just in some cases a few people would have maybe a problem.

**Comment by tsteur** [comment]
Alternatively, it would not show a button but only text, or add least replace the `all websites` with a link to `add a new site`.

**Comment by mattab** [comment]
Text only would work too :+1:
