### ISSUE TITLE
When a period has no data, but raw data, show a message

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16790]
Conditions when to apply this:
* For now only apply when "no segment" is select (report shows all visits) 

When loading the reporting UI, or when selecting a different date, can we check in an API call if `nb_visits=0`? If that's the case, we also check if there's any visit during that period in log tables raw data. If that's the case, we could show an info message like this:

![image](https://user-images.githubusercontent.com/273120/100160845-3716ec80-2f15-11eb-8e77-fa24be49340e.png)

Where click on visits log would move the user to the "visits log". Could we also have a link that opens the date selector? Wording likely needs to be improved (didn't think too much about exact wording).

Maybe we would only do this extra API call if the date includes "today" as in other cases it should not be needed.

**Comment by flamisz** [comment]
Hi @tsteur, we already have a message like this:

<img width="807" alt="Screen Shot 2021-03-18 at 1 30 45 PM" src="https://user-images.githubusercontent.com/6749509/111555873-2bb23e80-87ee-11eb-8cd7-d7ac8484c9a8.png">

We'd like to improve this one by checking the raw data or we'd like to handle these things completely separately?

**Comment by tsteur** [comment]
seems this was added as part of https://github.com/matomo-org/matomo/issues/13753 

It seems to be only shown though when archiving was last executed more than a day ago and it's not shown to users with view access. The link to the set up archiving is also not 100% helpful because likely they have it already set up but they have some problem. That would be a different issue though. 

I'm thinking we want to show a different notification if archiving was last run in less than a day ago. It would be also shown to view users. And rather than suggesting there might be a problem and adding a link we would say something like in the image from the issue description. And we would only show this message if there is actually raw data for the currently selected date period. 

So it's a bit different as above message is shown when archiving hasn't run successfully in a while  and there might be a problem. Vs in this case there is more than likely no problem, it's just that the archiving hasn't run yet.

Not sure if that's clear?

**Comment by flamisz** [comment]
@tsteur thanks, yes it's clear now 👍
