### ISSUE TITLE
Handle alexa timeout issues better

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#16801]
![image](https://user-images.githubusercontent.com/273120/100280457-18742c80-2fcd-11eb-9ba4-41518b947fe3.png)

was getting this error after we made the recent Alexa change in 4.0.1.

@sgiehl when there is a timeout error, could we avoid showing a confusing warning and instead show in the UI simply something like "Timeout error, please try again" or so?

Just wanting to avoid getting reports about this and people asking what is happening and what it means.

**Comment by sgiehl** [comment]
@tsteur that actually should not be an issue of the alexa stats only. All SEO metrics will trigger a warning when they fail to load.
Might make sense to change the logging to info and simply show an "Error" in the UI.
