### ISSUE TITLE
Matomo 4.0.0 warns about "ExampleTheme requires Piwik <4.0.0-b1"

### ISSUE THREAD

**Issue by Krinkle** [matomo-org/matomo#16804]
I just upgraded from Matomo 3.14.1 to 4.0.0 (installed and updated via DirectAdmin and Installatron) and started getting various System Check warnings.

| Settings | System Check | System Check / Informational
|--|--|--
| ![settings](https://user-images.githubusercontent.com/156867/100298279-9d892280-2f88-11eb-863b-94e93b77f8bf.png) | ![sys-summary](https://user-images.githubusercontent.com/156867/100297201-0f13a180-2f86-11eb-831d-834345544159.png) | ![info](https://user-images.githubusercontent.com/156867/100298336-c7dae000-2f88-11eb-9d55-7cc1234d9754.png)

Attached:
[matomo_system_check.txt](https://github.com/matomo-org/matomo/files/5599980/matomo_system_check.txt)

The issue about ExampleTheme seems like a bug, and is what I'm reporting. I'm not aware of having installed anything by that name and suspect it may've been something that went wrong in the packaging of the release or something?

**Comment by tsteur** [comment]
Thanks for creating this issue and letting us know @Krinkle I've created a PR that should remove this plugin in the next update. Basically `plugins/ExampleTheme` needs to be removed.

**Comment by slawa-dev** [comment]
@tsteur Does the same apply to the other ones in the `plugins` folder?

```
ExampleAPI
ExampleCommand
ExampleLogTables
ExamplePlugin
ExampleReport
ExampleSettingsPlugin
ExampleTheme
ExampleTracker
ExampleUI
ExampleVisualization
```

**Comment by tsteur** [comment]
Hi @Krinkle yes you could remove these other plugins as well
