### ISSUE TITLE
Matomo 4 migration: Index column size too large

### ISSUE THREAD

**Issue by Findus23** [matomo-org/matomo#16811]
reported in https://forum.matomo.org/t/fehler-bei-installation-in-strato-hosting-paket/39480

> SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.

PHP-Version 7.2 and MySQL-Version 5.6.

**Comment by sgiehl** [comment]
Guess that is related to the utf8mb4 changes, but without knowing which table actually produces the error it's hard looking it up.
Looked through the database definitions, but couldn't find anything obvious. Asked on the forum for more input. If that doesn't help quickly will need to setup a database without utf8mb4 support and install Matomo on it.

**Comment by tsteur** [comment]
It seems to be the `matomo_archive_invalidations` table @sgiehl  see forum. Anything we can do here?
