### ISSUE TITLE
Announce Matomo 3.x Long Term Support ends in December 1st 2021 - end of life for Matomo 3.x 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#16818]
we could announce Matomo 3.x Long Term Support ends in December 1st 2021, so this will be the end of life for Matomo 3.x. Creating an issue to remember to announce it in 1 year, as it might be helpful?

**Comment by tsteur** [comment]
@mattab this is basically the announcement so closing it as we had discussed we only keep the initial post
