### ISSUE TITLE
PDF: find compatible font for displaying analytics reports in Ahmaric, Thai languages...

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#1907]
As of Piwik 1.1, there two languages that we know PDF Reports don't generate properly:
- Ahmaric
- Thai

I couldn't find working fonts in the TCPDF release. Alternatively, once DejaVu font supports these 2 languages, Piwik will support it as well (since we fallback to DejaVu font)

**Comment by sgiehl** [comment]
meanwhile those languages should work in PDFs. But those languages aren't rendered correctly in the image graphs
