### ISSUE TITLE
Translation file cleanups (refactor all html code, commands to type etc.)

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#1931]
Some language translations entries have 
- HTML (<br> <p>`
  <a href=\'index.php\'>install Piwik now</a></b><br /><small>` or`
  &lt;a target="_blank" href="http://piwik.org/docs/setup-auto-archiving/">How to setup auto archiving page&lt;/a>` )
  - command lines (
  - filenames eg. manifest.inc.php
  - function names eg. md5_file()
  - paths, eg. config/config.inc.php
  - PHP parameters eg. --with-zlib
  - or "install the php-libxml"
  - etc.

It would be nice to review all these and factor out these 'common' bits in a %s parameter each time.  It is easy for translators to make a typo when copy pasting an HTML tag or an obscure PHP configure option.

This would allow greater quality in the Piwik translations.

**Comment by mattab** [comment]
fyi @sgiehl I found a few remaining, mostly searching for HTML elements ie. `<` and filenames ie. `.php` and `--`

![3](https://user-images.githubusercontent.com/466765/47120541-941e2e00-d2cb-11e8-9fca-3604b1eaf3ea.png)
![2](https://user-images.githubusercontent.com/466765/47120542-94b6c480-d2cb-11e8-88c2-46df11e8f934.png)
![remaining1](https://user-images.githubusercontent.com/466765/47120543-94b6c480-d2cb-11e8-8f6d-0e1e23feb394.png)

**Comment by sgiehl** [comment]
Actually smaller portions of HTML are meanwhile greatly handled by transifex, so as long as the HTML isn't about to change often, there shouldn't be a reason to replace them with placeholders, as it's not possible in transifex to see their replacement. Will close this issue now and try to look through and clean up the translations from time to time if needed...
