### ISSUE TITLE
SearchEngines:verification

### ISSUE THREAD

**Issue by robocoder** [matomo-org/matomo#2305]
Periodically (i.e., an automated, daily task), for each search engine, go through its list of URLs, and test a search for 'piwik'. (The list of URLs will be more extensive than the ones in core/DataFiles/SearchEngines.php.)
- is the site still up?
- is the query parameter present?  (make sure it's not in the anchor)
- is Piwik in the search results?
- has the favicon changed?

**Comment by Findus23** [comment]
While some of them are indeed offline (see https://github.com/matomo-org/searchengine-and-social-list/issues/28) it seems useful to keep them in the list in case one is tracking historical data.
Icons are maintained and updated in https://github.com/matomo-org/matomo-icons
