### ISSUE TITLE
Better Real Time reporting in Matomo: Actions in Real-time

### ISSUE THREAD

**Issue by anonymous-matomo-user** [matomo-org/matomo#2439]
Suggestion to have an "Actions in Real Time" widget...  I think you already show this data in the real time visitors module but I have to hover over a lot of the recent pages viewed to try to determine what people are looking at.  This is a proposal to do something like ChartBeat where you organize that info to display what content is popular NOW.  I will try to attache a screen shot to this ticket.

This could be very similar to the "Visitors in Real Time" but instead of grouping pages for each visitor on one line, you would do the opposite... each line would be for a page of content (by title) and you would list little icons representing visitors underneath the page title.

The widget would be ranked by whatever pages have the most recent actions, perhaps in the last 15 minutes or so (or make this a configured option by the user). I also think it would be best to only represent a unique user a SINGLE time within the entire module... that user would appear on the content they most recently viewed.  That way, if a user goes randomly clicking a dozen pages on the site without really looking at them, it doesn't skew the numbers too much.  The main idea is to show what pages on a site where users are at the moment, and they can't be paying attention to more than one page (for the most part).

You might also check out how ChartBeat works, as this is a proposal for similar functionality to the major focus of their product. In my opinion, this is the biggest thing missing from Piwik for people like myself wanting to switch from ChartBeat. Piwik is SO much more robust than ChartBeat in other areas, but it is hugely helpful to see how content is performing on the site grouped by activity on each piece of content in real time.  I monitor chartbeat very closely and within 2 or 3 minutes of putting up a new post on my blog I can tell if it is a winner or loser.  I can also immediately see if I suddenly am getting a BIG link driving a lot of traffic to a post.

Thanks so much for considering this!

**Comment by lemon2015** [comment]
If the administrator can see who is visiting the website and who left the website, it would be perfect.

**Comment by mattab** [comment]
Great mockup suggested by a user for a Real-time Pages based reporting:
![IMG_0082](https://user-images.githubusercontent.com/466765/68094087-d24fb500-ff01-11e9-8ec8-fe32174083c1.jpg)

**Comment by mattab** [comment]
Also received these screenshots of other similar apps:

![another2](https://user-images.githubusercontent.com/466765/68094102-0b882500-ff02-11e9-9de3-70c48b16ad43.png)


![another](https://user-images.githubusercontent.com/466765/68094103-0c20bb80-ff02-11e9-8a7b-236aa4ae4ba5.png)

**Comment by mattab** [comment]
Duplicates https://github.com/matomo-org/matomo/issues/14392
