### ISSUE TITLE
NoSQL support

### ISSUE THREAD

**Issue by robocoder** [matomo-org/matomo#2592]
Using Mongodb, Hadoop, Tokudb, Piwik could scale to greater limits. 

This ticket is an invitation to the community to comment and discuss the Nosql support of Piwik!

References:
- [Piwik nosql faq](http://piwik.org/faq/how-to-install/faq_55/)

**Comment by timofeytt** [comment]
Well, it doesn't have to be completely No SQL. You may look into [ClickHouse](https://github.com/yandex/ClickHouse) - the column-oriented DBMS used by Yandex for its own web analytics. It even has SQL syntax, so it doesn't require a complete rewrite of Piwik.

**Comment by gebi** [comment]
Yes, clickhouse would be a really nice backend!

**Comment by gmenegatti** [comment]
We have just contacted Piwik's team in order to check the viability to integrate [SlicingDice](https://www.slicingdice.com) as a backend for Piwik. Let's see how it goes.

**Comment by faust64** [comment]
What about Cassandra?

**Comment by mattab** [comment]
FYI Clickhouse would be the more likely candidate we would look into eventually, as it's SQL compatible

**Comment by approached** [comment]
@mattab what kind of feature you are missing? https://clickhouse.yandex/docs/en/introduction/distinctive_features/#sql-support

**Comment by tsteur** [comment]
While it has SQL support you need to look into some details. Eg does it support delete/update and if supported, is it fast. Does it support eg 10 to 20 joins, does it support all kind of alter table statements etc.

**Comment by tsteur** [comment]
Closing this issue as a duplicate of https://github.com/matomo-org/matomo/issues/7526

**Comment by flyonce** [comment]
> Yes, clickhouse would be a really nice backend!

Hi，what need to do if i wanna to use clickhouse as backend of matomo？

**Comment by sgiehl** [comment]
@flyonce Afaik we don't have supporting any other database backend on our roadmap, as it would require to much work.
Not sure if anyone ever tried running Matomo on clickhouse. But feel free to give it a try, if you are keen on it.
If it works smoothly feel free to report back to us :-)
