### ISSUE TITLE
Multiple database and storage engine support

### ISSUE THREAD

**Issue by robocoder** [matomo-org/matomo#2593]
This ticket narrows the scope of changes contemplated in #1368:
- Zend_Db supported adapters
  - e.g., Postgresql and Mssql
  - NoSQL is out of scope for Piwik 1.x
- MySQL storage engines
  - e.g., InnoDB
  - possibility of subclassing would allow a Sharding schema
- Use Zend_Db for the tracker
  - eliminates some redundancy, eg core/Tracker/Config and core/Tracker/Db
  - increases cohesiveness of core/Db and lowers the learning curve for new devs
  - eliminate more require_once in favor of the auto loader everywhere

ToDo:
- Installation
  - dropdown for schemas
- Piwik.php:
  - move MySQL-specific bulk loader to Schema/Myisam.php; leave a wrapper behind
- better support for users with the resources to run db clusters:
  - add Db::factory($dbConfigName); see [read vs write](http://forum.piwik.org/read.php?3,80130), tracker vs reports
  - always use Zend_Registry::get($dbConfigName)->methodName() and remove the plugin helper functions: Piwik_Exec, Piwik_FetchAll, Piwik_FetchRow, Piwik_FetchOne, and Piwik_Query
- (vipsoft: further scope analysis of current code in trunk)

**Comment by HaithamMaya** [comment]
any updates on PostgreSQL support? It appears that #500 doesn't exist anymore.

**Comment by jeffmcneill** [comment]
Same with Issue #3914, SQLite support, the issue no longer exists. I'm having huge problems with Piwik because of the large traffic it recreates over http/s, and the memory requirements of MySQL. This is not at all feasible for smaller sites.

**Comment by mattab** [comment]
FYI the issues are back (it was a temporary github glitch)

**Comment by mattab** [comment]
> I'm having huge problems with Piwik because of the large traffic it recreates over http/s, and the memory requirements of MySQL. This is not at all feasible for smaller sites.

Maybe you could consider Cloud-hosted Piwik? https://piwik.org/hosting/

**Comment by jeffmcneill** [comment]
Cloud-hosted is against our privacy and security requirements. We are migrating to a custom log analysis tool which will fix all these problems with Piwik (since we won't be using Piwik).

**Comment by mattab** [comment]
Sounds OK, and btw, Piwik MySQL requirements are not big or special, you just need enough RAM and CPU to run MySQL which is easy and cheap these days (especially for a small site)

**Comment by mattab** [comment]
So far we're not planning to implement multiple database support, although things could always change of course. Updated the FAQ at: https://matomo.org/faq/how-to-install/faq_55/

So i'll close this issue.
