### ISSUE TITLE
nginx and lighttpd configuration recommendations

### ISSUE THREAD

**Issue by robocoder** [matomo-org/matomo#2814]
For Apache and IIS, the Piwik installer will create .htaccess and web.config files, respectively, to provide an additional layer of security, e.g., blocking direct access to .php files.

Given the recommendation in http://piwik.org/faq/new-to-piwik/#faq_137 we should provide some hardening recommendations.

**Comment by Findus23** [comment]
There is now an official nginx config: https://github.com/matomo-org/matomo-nginx
Detecting nginx during setup is suggested here: https://github.com/matomo-org/matomo/issues/13589

In case someone wants to maintain an official lighttpd config a similar repo could be created.
