### ISSUE TITLE
User management is hard

### ISSUE THREAD

**Issue by ThaDafinser** [matomo-org/matomo#338]
Hello together,

the user management is really hard.
I have currently 22 websites and 13 users.

What is difficult/missing?
- There is no complete overview which users have access to which website
- View all user permissions for all websites (matrix)
- Assigning a user no multiple website is also hard, bec only 15 websites are shown in the drop down and u have to search often that way and u have to assign it for each website

**Comment by sgiehl** [comment]
That should be improved/fixed with https://github.com/matomo-org/matomo/pull/13158
@ThaDafinser if you have ideas for improving the new user management, feel free to create some new issues
