### ISSUE TITLE
Column names could stick to the top of screen when scrolling down report tables

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#3513]
It would be awesome that, when scrolling down and the header row with Column names is not visible, that instead this row would stick at the top of the screen and provide an always clear view of the data being shown. 

Even Piwik team members don't know about the order of columns it is hard to remember in all views... This would improve UX for All users at once!

**Comment by tsteur** [comment]
I think this one can be closed @mattab ?

**Comment by mattab** [comment]
Sticky column headers is not implemented yet. But it's not a priority or a major issue compared to the rest and we could close it. we could maybe even close all issues in the `Backlog` milestone... (to be discussed)

**Comment by tsteur** [comment]
Yeah just seeing now it's actually not implemented. For some reason thought you''d scroll within a widget... could be maybe easily solved not sure.

**Comment by sgiehl** [comment]
If it would be enough to support modern browsers except of IE we maybe could try using `position: sticky`. See https://caniuse.com/#feat=css-sticky

**Comment by tsteur** [comment]
mentioned it [here](https://github.com/matomo-org/matomo/issues/14333) as well `sticky` be fine

**Comment by tsteur** [comment]
for tables sticky will also work soon in webkit/chrome etc https://web.dev/compat2021/#css-position:-sticky

**Comment by tsteur** [comment]
if there is an unexpected complexity (causing it to take > 2 days) in making this work please reach out.

**Comment by sgiehl** [comment]
Note: The merge PR enables sticky headers only for datatables that fit in the available space. For tables that need a horizontal scroll bar, sticky header will not work. Not sure if we want to create a follow up issue to check if we can use javascript to make sticky headers also work for such cases.
