### ISSUE TITLE
Select Goal conversion metrics for each goal in the Graphs metrics picker

### ISSUE THREAD

**Issue by anonymous-piwik-user** [matomo-org/matomo#3528]
If you go to Goals -> Goals Overview, you can see a line with the sum of all the goals.

You can select to show also in that graph other lines for Conversion Rate and Total Revenue.

It would be great if you could select which goals you want to show in that graph, one line for each goal metric.

Also should support ecommerce  / abandoned carts on the Ecommerce Goals report.

**Comment by mattab** [comment]
we made some improvements towards this in https://github.com/matomo-org/matomo/pull/13101 and maybe this issue is even already fixed? adding to 3.7.0

**Comment by diosmosis** [comment]
Unfortunately the changes in #13101 for goals only work for that new widget.

**Comment by tsteur** [comment]
Please note that selecting a specific goal there may cause trouble with viewDataTable parameters... view parameters are stored across sites, and selecting one idGoal may be available in other sites or may not be etc and may pre-select goals that you don't want etc.

**Comment by tsteur** [comment]
FYI: I started to work on adding all goal metrics to Goals => Overview graph in https://github.com/matomo-org/matomo/compare/12770?expand=1 and it works except for conversion rate.

But then noticed you would do have those goals metrics in all evolution graphs which doesn't make any sense to me, it bloats the UI, and it is also hard to implement. Therefore stopping work on this.

**Comment by diosmosis** [comment]
@mattab can you take a look at @tsteur's comment?

**Comment by diosmosis** [comment]
@tsteur will you be able to create a PR from your branch (otherwise I can do it, but it will be in my name I think). Code looks good, haven't tested locally though.

**Comment by tsteur** [comment]
@diosmosis I'll have a look. I just looked at the PR again and what I did there looks quite hacky and fragile. I'll see if I find a better solution and it still needs to support conversion rate as well. Not sure if I have time for it before the holidays.
