### ISSUE TITLE
Make GeoIp PECL not log  errors

### ISSUE THREAD

**Issue by anonymous-piwik-user** [matomo-org/matomo#3601]
Hi Guys,

I never posted here before and not sure if you are aware of the issue or not.

There is a bug with GeoIP logging php errors when it encounters an unknown IP address i.e. one not in the database.

The error message is: 

[[client xx.x.xx.xx](error]) PHP Notice:  geoip_country_code_by_name(): Host 46.6.81.70 not found in /var/www/piwik/plugins/UserCountry/LocationProvider/GeoIp/Pecl.php on line 80, referer: http://XXXXX

Solution:
/var/www/pistats/plugins/UserCountry/LocationProvider/GeoIp/Pecl.php

Line 57: $location = geoip_record_by_name($ip);

Change to:
$location = @geoip_record_by_name($ip);

The @ stops the error being logged.

Regards,

Leslie
Keywords: GeoIP logging php errors

**Comment by sgiehl** [comment]
As GeoIp is deprecated meanwhile, we not likely will change that anymore, but enforce user to use GeoIP2 instead.
