### ISSUE TITLE
GeoIP auto updater: display the last time the update was executed

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#3680]
2 small things would be very nice in settings/Setup automatic updates of GeoIP databases:

1) show the date+time of the last update
=> you can be sure the updater is working

2) a new Button "update now"
=> after setting the automatic up you can start directly
=> if there are some changes in the database you can import them directly on point of time you want
Keywords: GeoIP Auto-Updater, usability

**Comment by sgiehl** [comment]
The time of the last update is meanwhile displayed. To force a manual update it's possible to manually trigger the scheduled task. We likely won't add a update now button in the UI
