### ISSUE TITLE
Disallow open redirect to known subdomain in Overlay

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#3689]
From email report:

open redirect in piwik 1.10.1 to target subdomain for exaple

http://demo.piwik.org/index.php?module=Overlay&action=startOverlaySession&idsite=7#http://forum.piwik.org.google.com

and example as iframe 

http://demo.piwik.org/index.php?module=Overlay&action=index&idSite=7&period=day&date=yesterday#l=http$3A$2F$2Fforum.piwik.org.google.com

need create subdomain with name "forum.piwik.org" (knownUrls)

Bug: error in string

 if (urlToRedirectWithoutPrefix.substr(0, testUrl.length) == testUrl)

in module Overlay in function startOverlaySession

**Comment by Findus23** [comment]
A quick check shows that the latest Matomo version does check if the requested URL is allowed.
