### ISSUE TITLE
Allow country level zoom in real time visitor map

### ISSUE THREAD

**Issue by anonymous-piwik-user** [matomo-org/matomo#3804]
The new Visitors World Map and the real time map are really two awesome new features ! Thanks for that ! (And I keep the Kartograph project under my hat for a possible future need :D)

But why is it not possible to go down to country or region level in the real time map, as that is possible for the visitors map (see picture below) ?

[40%, center)]([Image(Top-Cities-showing-Visits-for-each-city-from-France-with-clustering.png,)]

Indeed, in Europe and for a website whose visitors are mostly French for example, we obtain a high concentration of yellow bubbles on this country, and a large empty area elsewhere (see picture below). So it would be nice to be able to zoom in on a country, as the above picture.

[center)]([Image(europe-view.png,)]
Keywords: visitor map

**Comment by cyberbeat** [comment]
I strongly wish a config to select a default country, too. many websites are in only one language and  address one target country. in such cases you always(!) have to select the country, and the realtime map is even useless.

**Comment by cyberbeat** [comment]
What about this feature?

**Comment by mattab** [comment]
@cyberbeat this feature would be great to have but we unfortunately do not have enough time to work on this, if you are developer, please consider contributing via a pull request :-)

**Comment by cyberbeat** [comment]
ok, see here: https://github.com/piwik/piwik/pull/9432

**Comment by ksubileau** [comment]
Thanks you @cyberbeat for your PR on my feature request :)
And what about my other one, #3807 ?

**Comment by cyberbeat** [comment]
I have not enough time for that at the moment

**Comment by mattab** [comment]
This is now available :+1:
