### ISSUE TITLE
Code shouldnt use _GET and _POST directly but fetch them via a helper method

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#3931]
AS part of #2135 I discovered the joy of inconsistencies between browsers (Firefox decodes URL hash, while others don't) and inconsistencies in PHP (_GET is URL decoded by default, so we can use _SERVER[QUERY_STRING] to access raw value.

To prevent further problems in the future and keep other devs from experiencing my pain, I'd like to change the codebase so that no one uses _GET or _POST directly but always ask a helper method.

**Comment by michalkleiner** [comment]
Closing as superseded by https://github.com/matomo-org/matomo/issues/12620
