### ISSUE TITLE
Internet Explorer 8 in compatible mode (intranet) is being erroneously recognized as IE7

### ISSUE THREAD

**Issue by anonymous-piwik-user** [matomo-org/matomo#4070]
This occurs because 95% of IE8 here are with the "Display intranet sites in Compability View" enabled, and unfortunately, due to political issues, we can not disable it.

I've tried to apply this patch (#2621), but did not work. It would be nice to fix this...

**Comment by sgiehl** [comment]
Closing this one, as this is now handled by DeviceDetector
