### ISSUE TITLE
UX: add  Prev - Next Buttons next to Calendar

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#4365]
to get a good "feeling" for things that happen on your site, I'm sometimes switching from day to day, week to week or month to month instead of choosing the larger period.

It would be great to have a previous and next button beside the period selector to directly be able to choose the previous or following period (with the same duration: day,week,month..)

please see attachment.

further enhancement:
if you use this function very often, it would be awesome to be able to activate a performance mode, where period before and next would be preprocessed in the background so one could switch very fast...

**Comment by mattab** [comment]
FYI a PR was actually opened years later for this feature in https://github.com/matomo-org/matomo/pull/21518 :bulb:
