### ISSUE TITLE
Japanese prefectures are not displayed correctly

### ISSUE THREAD

**Issue by anonymous-matomo-user** [matomo-org/matomo#4387]
Cuttings of Japanese prefectures can not display correctly, for example:
- Tokyo, Tokyo, Japon
- Yokohama, Kanagawa, Japon
- Kawasaki, Chiba, Japon
  The prefectures (Tokyo, Kanagawa, Chiba) are detected, but not displaying.
  Keywords: map

**Comment by sgiehl** [comment]
refs #11929

**Comment by sgiehl** [comment]
closing in favor of https://github.com/matomo-org/matomo/issues/11929
