### ISSUE TITLE
Display 100+ visits when at least 100 visits, in Visitor profile

### ISSUE THREAD

**Issue by anonymous-piwik-user** [matomo-org/matomo#4447]
If visitor has more than 100 visits PIWIK 2.0.2 always report 100 visits in Summary section of [Visitor profile](http://piwik.org/docs/user-profile/).

**Comment by ZacharyDuBois** [comment]
I would also love for this to be definable to unlimited or another number like a lot of the Piwik settings. 

Based on https://forum.piwik.org/t/remove-limit-on-tracking-only-100-visits-user/15329, theres already a constant defined, shouldn't be hard to convert that to a config item.

**Comment by sgiehl** [comment]
fixed in #12863

**Comment by ZacharyDuBois** [comment]
@sgiehl You're the best! 👍
