### ISSUE TITLE
Show paging and search in the screen 'Manage users' to easily manage hundreds of users

### ISSUE THREAD

**Issue by anonymous-piwik-user** [matomo-org/matomo#4474]
Similarly to the "All websites" dashboard, the "Manage users" admin screen should use paging and display by default, the first 100 users.
Maybe there could be a link to alternatively display the "100 most recent users".
This feature is useful for websites automatically creating sites and tracking thousands of small-medium sites.

Using AngularJS: #4691

**Comment by mrjoops** [comment]
Since the "Manage sites" screen get updated with a pager recently, I hope this screen will get updated soon.

**Comment by diosmosis** [comment]
Fixed by #13158
