### ISSUE TITLE
Display Inline help icon linking to User Guide, for all features with a user guide

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#4481]
Matomo lets you see inline help for some of the features eg:
1. Hover on a title 
![Screenshot from 2020-04-03 16-31-35](https://user-images.githubusercontent.com/466765/78321502-a6c41a00-75c8-11ea-9289-ae46958ada0f.png)
2. Click on the help icon:
![Screenshot from 2020-04-03 16-31-37](https://user-images.githubusercontent.com/466765/78321516-b8a5bd00-75c8-11ea-87ab-33ebcb98f447.png)

Some of the features already have a Help icon in the Piwik software, linking to the relevant user guide. eg. Transitions, Row Evolution

But currently, many of our reports don't link to the user guide.

Yet almost all features and reports are documented in their own pages.
- [View list of all user guides](http://piwik.org/docs/)
- [DB size](http://piwik.org/docs/managing-your-databases-size/)
- [Segmentation](http://piwik.org/docs/segmentation/)
- [Page speed](http://piwik.org/docs/page-speed/)
- [Scheduled email reports](http://piwik.org/docs/email-reports/)
- [Analytics Privacy](http://piwik.org/docs/privacy/)
- [Analytics Security](http://piwik.org/docs/how-to-secure-piwik/)
- [Configure Piwik for speed](http://piwik.org/docs/optimize-how-to/)

Ideally all doc pages should be linked from the Help icon for consistency. 

When this ticket is closed, all features that have a user guide on matomo.org will be clearly linking to this user guide. This will help users make better use of Matomo and help them discover new features!

**Comment by mattab** [comment]
Be awesome to have all Matomo reports show the Help icon linking to the user guide, whenever the report/plugin has a user guide. Over the last months we've added user guides for almost all core features, free plugins, premium plugins and it would be valuable to surface the guides within the product.

**Comment by Findus23** [comment]
@mattab I guess for this #14530 needs to be solved first.

**Comment by sgiehl** [comment]
I had a rough look through the reports and create two PRs where the guide urls were missing.
@mattab Can we maybe close this issue afterwards and check if the guide urls for the reports are set in Matomo whenever we publish a new/updated guide?

**Comment by mattab** [comment]
btw here is a new guide we published recently: https://matomo.org/docs/dashboards/

> check if the guide urls for the reports are set in Matomo whenever we publish a new/updated guide?

Good idea, could you please create a ticket in KB to mention this? (we'll add it to the workflow)

**Comment by sgiehl** [comment]
@mattab Not sure where to add a link to `https://matomo.org/docs/dashboards/`. Guess it won't make sense to have the link for each dashboard in the menu. Might make more sense for the main menu item in this case, but we don't support that yet. Other possibility would be to add it somewhere in the dashboard configuration dropdown maybe...
Feel free to create a new issue for this special link and where to add it.
