### ISSUE TITLE
Make all tooltips in Piwik look the same 

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#4775]
At this time there are two different types /colours on mouse hover messages "grey old school" and "black new"
seem to be no matter what the function is: info / link...
e.g. on dashboard
please see attachments
having these "similar" looking or "function orientated" styled (different look for different function same look for same type of function) would help looking even more professional...

**Comment by sgiehl** [comment]
meanwhile our styled tooltips should be automatically used everywhere
