### ISSUE TITLE
Parallelization of processes for best performance

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#4905]
For best speed on todays multicore/mulithread servers,
piwik should be able to run as many processes as possible in parallel mode.

But which are the processes which can run in parallel mode??

This ticket is about a collection of ideas, and can be divided into several single tickets for each upcoming idea.

it was inspired from ticket:
#4903

One side question which has to be answered:
how to tell piwik how many cores/threads should be used max?

What Do you think about a setting where the advanced User can put in the max number of the cores/threads which are available in the server/should be used max. by Piwik?
- this may allow max performance for piwik
- but do not slow down other tasks of the server/ the complete server...

**Comment by mattab** [comment]
Now `core:archive` can be parallelised for already a few years :rocket: 
the parameters you can use are:

     --concurrent-requests-per-website  When processing a website and its segments, number of requests to process in parallel (default: 3)
     --concurrent-archivers             The number of max archivers to run in parallel. Depending on how you start the archiver as a cronjob, you may need to double the amount of archivers allowed if the same process appears twice in the `ps ex` output.


see `./console help core:archive` or: https://matomo.org/docs/setup-auto-archiving/
