### ISSUE TITLE
GeoIPOrg not displaying data

### ISSUE THREAD

**Issue by anonymous-piwik-user** [matomo-org/matomo#4968]
The "before" screenshot shows the default Geolocation module prior to adding the Organization database from Maxmind.

The "after" screenshot shows that the Organization (GeoIPOrg.dat) database is recognized but not showing location/organization data.

I have tried manually uploading the database to /analytics/misc with the same results. I have removed the database from the server and used Piwik's automatic download of the Organization database. That functioned correctly and I confirmed that it was downloaded to the correct directory. 

The results matched the "after" screenshot.  Organization data is not shown in the "visitors > visitor log" or "visitors > locations & provider" views.

The site is hosted by GoDaddy and is running PHP 5.4. No warnings showed up during the Piwik installation.
Keywords: GeoIPOrg, geolocation

**Comment by mattab** [comment]
> I can confirm this behavior and have also found a workaround: just install GeoIPCity.dat along GeoIPOrg.dat and that's it.

Thanks @rindeal for the tip.

Since there is a workaround available i'm moving this issue out of our backlog for now

**Comment by sgiehl** [comment]
refs #13957

**Comment by mattab** [comment]
we'll probably stop using Maxmind soon, so closing this issue now, see #15308
