### ISSUE TITLE
New: Automatic Javascript Error Tracking with Piwik!

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#4977]
Using the new powerful [Event Tracking](http://piwik.org/docs/event-tracking/) functionality, we can implement Javascript Errors Tracking within piwik.js.

The goal of this feature is to keep track automatically of any javascript errors or exception that happen during the rendering of the page, or any time after the initial rendering.

There are lots of tools that provide Error tracking and we would like to implement a basic, yet useful, alternative as part of Piwik Data Analytics platform!

Todo
- FAQ
- User Guide?
- JS test

**Comment by szepeviktor** [comment]
I it a working feature or a planned one?

**Comment by tsteur** [comment]
It is working in general but only very basic. We simply track all errors as events for now but hope to provide similar enhanced features some day than others do

**Comment by hpvd** [comment]
"it is working in general but only very basic"
is there any doc how to use it? Do one has to enable it or should it work without any config directly "out of box"?

**Comment by tsteur** [comment]
Looks like there is no documentation for it indeed. There's a bit of documentation here: https://github.com/piwik/piwik/blob/2.16.0/js/piwik.js#L5869-L5886 and to activate it you can call `_paq.push(['enableJSErrorTracking']);`.

It is very very basic though and I would suggest to first give it a try as it will add many different event actions and event names to your event reports in case you are using them for something else currently (it could give you a less good overview of action and names in event reports)

**Comment by wei1215583760** [comment]
_paq.push(['enableJSErrorTracking']); after i add this sentence in my website, i want to know where i can check the result in my piwik. thanks!

**Comment by tsteur** [comment]
You can see some basic reporting in the "Actions => Event" reports

**Comment by wei1215583760** [comment]
![7aa36a59dd72494fa0dd5a554f098129](https://user-images.githubusercontent.com/11715783/29301770-21f54924-81b1-11e7-9c0e-672316511c16.png)
this is my test website which i track it with piwik, and there is an error. I have added _paq.push(['enableJSErrorTracking']) in the tracking code.

i want to track the error, but it shows nothing in piwik
![b956709a57e5f447933cb56377be783e](https://user-images.githubusercontent.com/11715783/29301814-81c0ae98-81b1-11e7-850d-3c2bcd35f074.png)

do you know why?
thanks a lot if you can help me

**Comment by wei1215583760** [comment]
![8f5e9532bfbced41ae5dd11fb5cc07ca](https://user-images.githubusercontent.com/11715783/29301887-f3e29e6e-81b1-11e7-9378-fc2d6cf03559.png)

**Comment by wei1215583760** [comment]
![adea27f37245e34f86f90ae622f9d8c6](https://user-images.githubusercontent.com/11715783/29301897-1ee23fc0-81b2-11e7-9a59-61a055325cc0.png)
this is my website

**Comment by tsteur** [comment]
Maybe Piwik is loaded after the error occurred.

> To capture all JS errors we recommend to include the Piwik JavaScript tracker in the HTML as early as possible. If possible directly in <head></head> before loading any other JavaScript

The thing is Piwik is loaded async by default so it might still not capture all errors unless you loaded it sync which is not recommended.

**Comment by wei1215583760** [comment]
thank a lot for telling me about this, do you know how to loaded it sync? i want to have it a try to test this function. And do you know where can we find some demos to show the errors being tracked? i have a job to use piwik proficiently

**Comment by wei1215583760** [comment]
i define many errors in my website, but i cannot find any one in the piwik action->event, which confuses me. Which type of error does the piwik track?

**Comment by wei1215583760** [comment]
i want to know when i enablejserrortracking function, which table will store the data from website in piwik? Can you help me? thanks!

**Comment by RMastop** [comment]
Hi @wei1215583760,

If you navigate the website containing errors, could you check, using development tools, if you see any requests to your Piwik server?

**Comment by wei1215583760** [comment]
thanks for your reply @RMastop 
![9fe2ec4ca3eaa5459acd8a634deddd92](https://user-images.githubusercontent.com/11715783/29308165-5803cc04-81d7-11e7-9cd0-e5383b7c6d5c.png)
there are responses to piwik, but it did not carry error message. Can you give me some advice?

**Comment by wei1215583760** [comment]
![d31e8c9c62f7b94287b0578a936710da](https://user-images.githubusercontent.com/11715783/29308258-b7974128-81d7-11e7-8c31-8fae94a92a24.png)
@RMastop 

>

this is full image

**Comment by RMastop** [comment]
@wei1215583760 When should the js error occur? Could you post the HTML of the page?

**Comment by wei1215583760** [comment]
this is my website code, index.html. And i add an error <script>a+b</scrip, and it can post  HTML, but i can not track the  error @RMastop  ....sad
![1](https://user-images.githubusercontent.com/11715783/29308608-064fbb78-81d9-11e7-89e9-da969f394dac.png)
t>, ths whole

**Comment by wei1215583760** [comment]
@RMastop 
![f4c0c82f22434f40a2536331f8511fbc](https://user-images.githubusercontent.com/11715783/29308750-8f643de4-81d9-11e7-8ba1-a1ea2fd07eb7.png)
this is the page in chrome browser

**Comment by wei1215583760** [comment]
@RMastop  do you know where i the error message it stores as log data?

**Comment by RMastop** [comment]
@wei1215583760 I tried to reproduce the issue, but no call is triggered after the JS error. Without the call to the piwik server, no need to search for it in the database.

**Comment by wei1215583760** [comment]
thanks a lot for your patience, but i still do not know how to track the error, maybe this error can not be tracked?  do you know what kind of error can be tracked?

**Comment by wei1215583760** [comment]
Now i want to make sure that this function can track errors and show it with piwik dashboard. if you have some examples, can you give me example errors?@RMastop

**Comment by RMastop** [comment]
Hi @wei1215583760,

As documented, Could you put the Piwik tracking code all the way to the top op the HTML, just below <HEAD>
After this change Javascript errors are tracked as events.

`e_c:JavaScript Errors`
`e_a:http://127.0.0.1:8888/jserrordemo/:164:3`
`e_n:Uncaught ReferenceError: a is not defined`
`idsite:4`
`rec:1`

**Comment by wei1215583760** [comment]
![aa994bfc23eba545b2a49f373931ca61](https://user-images.githubusercontent.com/11715783/29310008-b6cb6be6-81de-11e7-985d-c657071a407f.png)
do you mean put the tracking code like this ? but it still have no reponse ...sad
where do you get your message? in action=>event?
@RMastop

**Comment by Findus23** [comment]
You can also try running the tracking script non async/deferred as explained here: https://developer.piwik.org/guides/ab-tests/browser

This will slow down your site a bit but will make sure that piwik is loaded before the error occurs.

**Comment by RMastop** [comment]
@wei1215583760 just below the opening `<HEAD>`
![image](https://user-images.githubusercontent.com/7987117/29310227-3288bdc4-81ad-11e7-9622-aca18661586f.png)

**Comment by wei1215583760** [comment]
thanks for your help, @Findus23 @RMastop , I change the tracking script using synchronous method, and it  worked.
![image](https://user-images.githubusercontent.com/11715783/29310399-2b9d68e2-81e0-11e7-8729-64cc1c414b61.png)
thanks a lot for your kind heart

**Comment by Findus23** [comment]
maybe now that we have a documentation on how to run piwik non-asynchronous, we should maybe we should also document this feature. (And warn about the performance decline)

**Comment by wei1215583760** [comment]
Yes, but asynchronous method did not work for error tracking in my case. Maybe this case will be a good guide for other users

**Comment by wei1215583760** [comment]
![82bb9f56ee563244b873f09993e70add](https://user-images.githubusercontent.com/11715783/29349572-49f8fcf4-828d-11e7-8937-c166f31d88be.png)
Additionaly, i can track js error as the following picture shows, but how can i track the full trace back including at     "at abc (demo1.js:11)  at efg (demo1.js:16)" @RMastop @Findus23 
![25f45f6048e3e248ae720a8cb405b8b5](https://user-images.githubusercontent.com/11715783/29349609-70296efe-828d-11e7-9b3d-5bdc5ebddacc.png)

**Comment by wei1215583760** [comment]
If i want to make sure where the error happened, i need to know the accurate message

**Comment by wei1215583760** [comment]
@tsteur do you know how to track full trace back using js? If there are some errors, I want to find it more easily with trace back information.

**Comment by Findus23** [comment]
@wei1215583760 
Currently piwik doesn't add the stacktrace, but it shouldn't be that hard to add:

Check https://github.com/piwik/piwik/blob/3.x-dev/js/piwik.js#L6500-L6543
and https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

At least in chrome (I am not sure about other browsers) the stacktrace should be accessable via `error.stack`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack
https://stackoverflow.com/a/4200200

**Comment by wei1215583760** [comment]
I have used error tracking for several days, it worked well. And I want to know where the information placed in the datatable. Do you know where these error strings are stored? @Findus23 @RMastop  I am sorry to trouble you.

**Comment by wei1215583760** [comment]
again

**Comment by mattab** [comment]
> Do you know where these error strings are stored? 

They're stored as Actions in log_link_visit_action and log_action tables see: https://developer.piwik.org/guides/persistence-and-the-mysql-backend#action-types

**Comment by nvinayvarma189** [comment]
> @wei1215583760
> Currently piwik doesn't add the stacktrace, but it shouldn't be that hard to add:
> 
> Check https://github.com/piwik/piwik/blob/3.x-dev/js/piwik.js#L6500-L6543
> and https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror
> 
> At least in chrome (I am not sure about other browsers) the stacktrace should be accessable via `error.stack`
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack
> https://stackoverflow.com/a/4200200

Hey @Findus23, I wanted to know if the latest version of matomo can print the stack trace or not. I couldn't find much documentation regarding this. 

Also, I've seen that `JSErrorTracking` can only track the uncaught exceptions and not errors regarding missing resources (cdn links, external CSS and js, etc). Has this changed now? and if not is there a way that one can track these errors through any other means?

Thanks

**Comment by Findus23** [comment]
@nvinayvarma189 
As far as I know nothing changed since the last post here. But you can still use Event Tracking to track any arbitrary event and data so including Javascript errors if you write the code that triggers a Matomo event when they happen.

**Comment by mattab** [comment]
Documented this feature in: https://matomo.org/faq/how-to/how-do-i-enable-basic-javascript-error-tracking-and-reporting-in-matomo-browser-console-error-messages/

Noted the two main limitations i'm aware of at the end:


* currently the stack trace is not recorded, which makes it sometimes harder to troubleshoot. 
* when you enable this feature it will start tracking errors as events. If you already use Events for other purposes, these new error events might somehow "pollute" your Event reports and add noise. As a workaround, you may create [Custom reports](https://matomo.org/docs/custom-reports/) to filter out the "JavaScript Errors" events if needed.

**Comment by mattab** [comment]
Will close this for now. If you use this feature, please open new issues for specific feedback.
