### ISSUE TITLE
Row evolution: Y axis legend is double URL encoded

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#5009]
See changes in screenshots: https://github.com/piwik/piwikuitests/commit/92fd9240f34a110fe5cd6824b9807c4192285e83

Original build failure: http://builds-artifacts.piwik.org/ui-tests.master/2510.1/screenshot-diffs/diffviewer.html

This was regressed in: https://github.com/piwik/piwik/commit/8f1d34c11d82deabe95fe569ea207e8ee8c15336

**Comment by mnapoli** [comment]
> This was regressed in: 8f1d34c

can we just revert that commit?
