### ISSUE TITLE
French Guiana shows up as France in maps and reports

### ISSUE THREAD

**Issue by anonymous-piwik-user** [matomo-org/matomo#5056]
Please look at the south america map, Guyana->Suriname->[France]. 
France has to change to French Guiana
http://en.wikipedia.org/wiki/French_Guiana

**Comment by mattab** [comment]
we also got the following complaint from a client:

> The visitor map have a small mistake, the territory for French Guyana is set as a part of France, it is of course an overseas territory of France, but is has its own subdivision ISO code "GF"
> What do you think about it?

I'm wondering if our Geolocation database will return accurate location data for users living in French Guyana. If you know anyone who lives in Guyana, what does the Piwik Visitor Profile report for location?

(if the geo location DB can detect french guyana then it would maybe make sense to display it as separate region/country on the map...)

**Comment by davidsneighbour** [comment]
This is still an issue. It's quite irritating if you don't know about French Guyana. If the latter is listed separately then it should not be included in France.

![Selection_147](https://user-images.githubusercontent.com/83281/113703278-ce325300-9704-11eb-9201-337b88fdc98e.png)

There is no mention of French Guyana vs. France on the kartograph.js repo: https://github.com/kartograph/kartograph.js/issues?q=is%3Aissue+is%3Aopen+french+guyana

**Comment by sgiehl** [comment]
@davidsneighbour kartograph is meanwhile unmaintained. I'll give it a quick try to fix the svg manually. But not sure if that works easily...
