### ISSUE TITLE
Improve display of relative % values in all data reports

### ISSUE THREAD

**Issue by gaumondp** [matomo-org/matomo#5096]
Follows up #1816 

The idea behind this ticket is to get a bit more control over what we see and the importance of the % column. From my experience with 2 different teams of editors, percentages are very attractive tools when you need to argue with people...

Right now in version 2.2 we have two main options: "Zen mode" as default and "Display a table with more metrics". We need full control or at least display % without using mouse and add it to the  export capability.

In Visitors=>Devices for example, at the moment, we see a single column (zen) or 7 with "More metrics" but no % column.

Even in "More metrics" mode, we still don't get a "%" column.
1. Simplest option: Make a display option so we can see % without using the mouse, even in Zen mode. Since the data is already there but hidden without a mouseover it should be quite simple to implement. 
2. Still simple: Make a display option where % are in their own column, sortable and visible even in Zen mode and/or in "More metrics". The % column should also appear in reports and exports. 
3. Full deal: Let us choose columns to display in "More metrics". Let's keep the "true" Zen mode and make more metrics configurable. Then we would be able to hide "Avg. time on page" and "bounce rate" if it's not important to us and add our shiny new % column to it.
4. At least, we should always have the % in exports.

Thanks for the consideration of this/these feature(s)

Dali

**Comment by mattab** [comment]
I'm closing in favor of these:

* https://github.com/matomo-org/matomo/issues/15515
* https://github.com/matomo-org/matomo/issues/6182
* https://github.com/matomo-org/matomo/issues/19747
