### ISSUE TITLE
Warning: htmlspecialchars(): Invalid multibyte sequence in argument in piwik/vendor/twig/twig/lib/Twig/Extension/Core.php

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#5157]
Reported [in the forums](http://forum.piwik.org/read.php?2,115238)

We have experienced this problem before: #3259, #3816, #3859, #4221, #4330, #4974.

So my approach to fixing this bug has failed to fix it across all occurrences. 

Maybe there is a better approach (such as making twig fail silently in case of such errors?)

**Comment by tsteur** [comment]
Hi everyone, I believe this was fixed in the meantime. If you still have the issue please comment.
