### ISSUE TITLE
Visits Over Time Widget (time frame independent)

### ISSUE THREAD

**Issue by anonymous-matomo-user** [matomo-org/matomo#5202]
Hi there, 

as Matt and I discussed in this thread ([http://forum.piwik.org/read.php?3,115567]), a time frame independent dashboard widget, that shows the visits and pageviews of the last 5 days/weeks/months/years, would be a great addition to Piwik.

**We've already narrowed it down to something like this:**
- add a dashboard widget called "Visits Over Time"
- show the visits (and pageviews) of, for example, the last 5 days in a table
- offer an inline icon to change the view to last 5 weeks/months/years
- independent of the individually chosen time frame
- make it possible that users can add multiple instances of this same widget to their dashboard and save the view preferences ("days", "weeks", "months", "years") for each instance

**How is the competition doing?**

Other tracking tools, like for example the German tool etracker, already make use of such widgets. In my opinion, that's the most important data anyway, at least for "everyday". Google Analytics does not as far as I know, so this would probably be a good way to catch a lot of inexperienced users for whom Google Analytics is way too complicated.

**Why should we implement this widget?**

Currently, there is no easy way in Piwik to get to this data without clicking a lot. But this might be the most accessed data by most users. In the first place people want to know how many visitors have been on their website this day/week/month compared to the last days/weeks/months. I think that this data should be accessable in the easiest way possible.

**How could it look like?**

I've uploaded a screenshot that shows how time frame independent widgets could look visually.

If somebody could implement this into Piwik, that would be just great. :)
Keywords: dashboard, widgets, visits, pageviews, time frame

**Comment by mattab** [comment]
This was implemented :tada:
