### ISSUE TITLE
SegmentEditor: display readable values for some metrics (e.g. FF -> Firefox)

### ISSUE THREAD

**Issue by peterbo** [matomo-org/matomo#5309]
When the segmenteditor is used, some select values are very technical / non user-friendly. These Values should be mapped / labeled to make them more meaningful.

For example this would make sense for:
- Browser - expects values like (FF, IE, MF, CM, IW, etc.) - This should be more readable (Firefox, Internet Explorer,??,??,??)
- Visit Location (Continent, Country)
- Operating system
- possibly others where it makes sense

**Comment by hpvd** [comment]
uuuh this is still open (for mor than 3years), major flag seems not to help at all...
It's strongly related to
- Improve geographical segmentations #11261

**Comment by tsteur** [comment]
FYI: This will be easier to implement with https://github.com/piwik/piwik/pull/12040 since we will then have all the information on how to render a value eg for country "nz".

**Comment by hpvd** [comment]
wow that looks pretty awesome.
Many thanks for working on this!

**Comment by mattab** [comment]
is this issue now fixed maybe @sgiehl ?

**Comment by sgiehl** [comment]
@mattab not sure if there are some segments missing where it would make sense to have readable names as well. But it's implemented for browsers, operating system and country segments. For those there is now the code segment and a new name segment.
Guess we can close the issue and create a new one if someone sees a segment where readable value would be usable?

**Comment by tsteur** [comment]
👍
