### ISSUE TITLE
Move Provider plugin to the Marketplace

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#5341]
The Provider plugin is currently part of core Piwik platform. 

Let's move it to the [Marketplace](http://plugins.piwik.org/) instead.
- Remove plugin from core
- Move file to the [marketplace](http://plugins.piwik.org/)
- On upgrade:
  - if Provider plugin is disabled, then delete Provider files.
  - if Provider plugin is enabled, make sure it still works and that the plugin can be later upgraded to latest marketplace version

**Comment by mattab** [comment]
it will be useful to have this plugin in thne marketplace, because most users don't need this feature and it can impact performance significantly (slow reverse dns query).  Moving to 3.0.0.

**Comment by axle07** [comment]
What is the name of this plugin in the marketplace?

**Comment by sgiehl** [comment]
@axle07  It has not been moved yet, so it's still included in core

**Comment by axle07** [comment]
We've enabled the Provider plugin in config.ini.php, and have the MaxMind ISP database, but are getting an empty array from Provider.getProvider. Are there more steps to activating the plugin?
