### ISSUE TITLE
Numeric value segments: new  "Less than" and "more than" conditions 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#5372]
When creating [custom segments](http://piwik.org/docs/segmentation/) and using:
- Local time  
- Server time
- Possibly others

the segment conditions "Less than", "More than", "Greater than" etc. are missing.

Goal of this ticket is to ensure that all Segment dimensions which are numeric value, have the proper conditions available in the User Interface.

**Comment by hpvd** [comment]
one use case:

look at statistics which browser versions visitors are using, to define which browser version has to be support in futher development / relaunch of website.

=> Is it really nessary to support IE8 beacuse ther is alarge amount of visitors using it?

![2016-04-14_13h52_08](https://cloud.githubusercontent.com/assets/5681880/14527232/d5634f04-0248-11e6-9906-c2f94713bd1a.png)

**Comment by heurteph-ei** [comment]
Other dimension that can use the _less/more than (or equal)_ operators:
 - device screen width / height (see https://forum.matomo.org/t/how-do-i-create-a-segment-to-check-for-screen-resolution/42740)

**Comment by mattab** [comment]
Thanks for your patience with this issue. We believe this has been resolved in the recent updates of Matomo. To ensure you have the fix, please [update](https://matomo.org/docs/update/) to the latest version of Matomo.  If the issue persists after the update, don't hesitate to reopen this issue and let us know. Cheers!
