### ISSUE TITLE
Compare data for two different dates in tables, charts and reports

### ISSUE THREAD

**Issue by zawadzinski** [matomo-org/matomo#5711]
This feature is important to web marketers and to a web analytics solution in general. The user should be able to select two periods to compare in the Piwik UI. The graphs, tables, sparklines, texts, would show values for both periods as well as the % of evolution.

**Comment by Japhys** [comment]
Is this something we can expect in the future? I really would like to have this feature! I switched from GA to Piwik on a site with millions of visitors a month, I really miss the ability to compare monthly and quarterly reports in a quick and easy way

**Comment by mattab** [comment]
Yes, we hope to implement this feature in the future. If your company can sponsor this change, it would certainly help make it happen faster :+1: https://piwik.org/development/
