### ISSUE TITLE
When IP anonimisation is enabled, hash the IP address in a way that prevents long-term fingerprinting

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#5907]
Problem: when IP anonimisation is enabled, it is still easy to profile users across days as they may be the only ones in their anonimised IP address range. So a Piwik admin could very easily find matching visitors in previous days despite the fact that the IP address is anonymised. This was suggested  by Richard Stallman from the FSF. 

Goal: Help users prevent future surveillance on themselves. Provide better privacy to users measured by Piwik.  Preventing the long-term tracking of users is of the highest importance; if we hit an obstacle, we must not simply give up.  

Proposed solution: When IP anonimisation is enabled, hash the IP address in a way that prevents fingerprinting. For example, hash the anonimised IP using a seed that changes each day.

Advantages: 
- the algorithm to detect unique visitors using IP address hash would still work for matching visitors to the current day's traffic
- it would bring added privacy to users tracked in Piwik as their IP address would be hashed, and across days such hash would be different.
- the fingerprinting hash should use the hashed visitor IP

What do you think? 

refs #5052

**Comment by tsteur** [comment]
Note: we already added hashing the fingerprint with a salt that changes every day. 

In https://github.com/matomo-org/matomo/issues/16377 we will also offer an option to not store the IP at all. 

Not sure this is still needed then?

**Comment by mattab** [comment]
will be fixed in #16377
