### ISSUE TITLE
Actions performed at the same time register as different visits

### ISSUE THREAD

**Issue by siulca** [matomo-org/matomo#5966]
I've noticed that sometimes page visits, actions or goals performed at nearly the same time get registered as new visits. See screenshot:

![screen shot 2014-07-29 at 18 34 49](https://cloud.githubusercontent.com/assets/6707451/3869997/4b677fc6-20b5-11e4-9eb4-c359b08be5a2.png)
 for example.

**Comment by siulca** [comment]
4 years on... I'm still seeing this bug. It's making me lose hope in Motomo (Piwik) :(

![image](https://user-images.githubusercontent.com/6707451/46607438-e2c40f00-caf8-11e8-95da-9222bb2f2d32.png)

**Comment by tsteur** [comment]
The only solution to this is to set up Queued Tracking (we made this easy to set up a while ago) https://plugins.matomo.org/QueuedTracking

**Comment by siulca** [comment]
Thank you for the link. Is there any reason why this is a plugin and not inbuilt as a default feature? 

My website doesn't have much traffic at all (50-100 visits per day). And I see this duplicate (sometimes triple and quadruple) visit behaviour when there's a single person visiting the site.

**Comment by siulca** [comment]
That plugin appears to have fixed it. Thank you. You may close this now.
