### ISSUE TITLE
Support MSSQL database server (Microsoft SQL Server)

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#6029]
The goal of this ticket is to add support for MSSQL (Microsoft SQL Server) in Piwik, to let users run Piwik using this alternative database.

This was requested by several users for example in this [forum post](http://forum.piwik.org/read.php?2,117220).

Feel free to comment if you are interested to help implement this feature in Piwik!

**Comment by CreativeManix** [comment]
+1 for MSSQL

**Comment by jmsunseri** [comment]
+50

**Comment by mattab** [comment]
If a company is willing to sponsor this development, we would consider implement it in Piwik. please contact us (the core engineering team) at: https://piwik.org/development/

**Comment by mattab** [comment]
Realistically we won't work on this ourselves, so closing here.
