### ISSUE TITLE
Clean up JSON2 in piwik.js

### ISSUE THREAD

**Issue by NekR** [matomo-org/matomo#6093]
Here:
https://github.com/piwik/piwik/blob/master/js/piwik.js#L45

You check for JSON2 object in window object which never exists and you always use JS version of JSON instead of builtin.

Also, here https://github.com/piwik/piwik/pull/6066#issuecomment-53999069 man said that you do not use json2.js, but you actually do, or at least json.js which is worse.

Refer to this commend for more details: https://github.com/piwik/piwik/pull/6066#issuecomment-53997506

**Comment by mattab** [comment]
Increasing priority as we probably soon could remove JSON2 from piwik.js

**Comment by tsteur** [comment]
It's currently pretty much only there for IE7 & IE6 see http://caniuse.com/#search=json

**Comment by mattab** [comment]
Ok so we won't remove this for a while since we need to support IE7 and IE6. Leaving opened, but decreasing priority

**Comment by filipre** [comment]
Any updates on this? I guess you are doing this due to contract duties but still encouraging the user to use IE6 sounds *extremely* insecure.

**Comment by mattab** [comment]
>  I guess you are doing this due to contract duties but still encouraging the user to use IE6 sounds extremely insecure.

we don't encourage users to use IE6, but we need to track users on IE6 and IE7 and cannot drop those users from tracking yet (we may in the future, though)

**Comment by Findus23** [comment]
Would it be possible to drop the support for IE<7 in Matomo 4 and remove the JSON fallback from the piwik.js?

Now that plugins can modify the piwik.js it may be possible to write a plugin that adds JSON3 for those who still need it (and reducing the load time for everyone else)

<sub>[Inspired by a forum post](https://forum.matomo.org/t/can-we-reduce-the-size-of-matomos-javascript-file/27038)</sub>

**Comment by tsteur** [comment]
👍  that is doable I'd say. A plugin that adds support for it may be doable as well.

Just a side note: JSON3 is currently also used for compatibility with some JS frameworks like older versions of `prototype` and others see eg https://github.com/matomo-org/matomo/issues/11023 .

**Comment by robocoder** [comment]
@NekR: The reason piwik.js called it JSON2 (even though it was using json.js) was because some browsers provided broken window.JSON implementations.

That said, I'm all for dropping the polyfill for Matomo4.

**Comment by sgiehl** [comment]
fixed with #15413, will be included in Matomo 4
