### ISSUE TITLE
Split piwik.js into multiple files and provide a merged one 

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#6106]
Now that `js/piwik.js` is getting larger and larger - for instance content tracking added already more than 1000 new lines of code - it would be really nice to split `js/piwik.js` into multiple files or modules. Would probably also make it easier to write tests for it. I'd have to write and create many tests that rely on DOM but are not related to tracking. Would also make it maybe possible to release some components separately, at least it would give us the possibility.

We could use [grunt](http://gruntjs.com/) or something else to merge those files together and to minify/shrink it for a single file `piwik.js`.

Alternatively, we could also use something based on PHP instead of grunt if we then offer third party plugins to extend the tracker as well.

**Comment by dhoko** [comment]
As suggested via #8642,you can split the source using browserify. You do not need to have gulp nor grunt, there is npm for that.

And if you don't have the time to do it, we (the community) can do it for you.

**Comment by tsteur** [comment]
:+1: if someone would work on it. It would be great to have as mentioned in the issue

**Comment by dhoko** [comment]
Building it with PHP... :finnadie:

I'm ok to split the code but with a front-end tooling. 

PS: Using a modular code will be a great option to provide:
- Default piwik for all
- Piwik for mobile (without shitty polyfills for IE < 9) so a smaller lib
- Custom build

**Comment by tsteur** [comment]
:+1: sounds great!

**Comment by dhoko** [comment]
You can follow the progress [refacto browserify](https://github.com/dhoko/piwik/tree/feat/browserifyFrontPiwik).

Do you have a page to test each functionalities provided by piwik ?

**Comment by tsteur** [comment]
:+1:  We have a test suite for piwik.js under `$PiwikUrl/tests/javascript`

**Comment by dhoko** [comment]
I don't understand how to run them :/ I tried via `./console` it doesn't work cf #8678 then I start a php server into `tests/javascript/` it doesn't work too because of:

```html
<script src="../../js/piwik.js?rand=2c1ba87dbd1d350d81ba2612f945b3fc" type="text/javascript"></script>
```

So I run a php server from root... 

![screenshot from 2015-08-31 16 30 53](https://cloud.githubusercontent.com/assets/713283/9581151/eddc3756-4ffd-11e5-86f7-0ce421979be6.png)

:cry:

**Comment by mattab** [comment]
Hi @dhoko did you see https://github.com/piwik/piwik/tree/master/tests/javascript#javascript-tests ?

**Comment by dhoko** [comment]
Yup that's why i tried to run PhantomJS too ;)
Le 1 sept. 2015 4:52 AM, "Matthieu Aubry" <notifications@github.com> a
écrit :

**Comment by tsteur** [comment]
It looks like static files are not served. Is your web server not serving them maybe? What I find weird is that we usually do not have some of the requested files like `jash/Jash.css` or `tests/piwiktest.js`

**Comment by dhoko** [comment]
It was: `$ php -S localhost:8000`

**Comment by tsteur** [comment]
I'm not familiar with the php builtin webserver but think that should work. Maybe someone else knows more about it? Maybe you're running this from within the `$PiwikDIR/tests/javascript` directory and not within `$PiwikDIR`

**Comment by dhoko** [comment]
> * I start a php server into tests/javascript/ it doesn't work too because of* ;)

**Comment by tsteur** [comment]
not sure what you meant? :) The PHP webserver should be started into `/path/to/piwik` and then the URL should be `/tests/javascript` :)

**Comment by dhoko** [comment]
Fist I started the webserver from ` tests/javascript/ ` it didn't work, then from the root `/path/to/piwik`:

> *So I run a php server from root...*

:/

From test/javascripts : 

![screenshot from 2015-09-01 11 53 35](https://cloud.githubusercontent.com/assets/713283/9601211/5b573cde-50a0-11e5-870d-d34920fa2df2.png)


From root: 
![screenshot from 2015-08-31 16 30 53](https://cloud.githubusercontent.com/assets/713283/9601215/615b3f5e-50a0-11e5-9a05-9531539cfaab.png)

**Comment by tsteur** [comment]
I just tried to reproduce via the command you mentioned (built in PHP webserver). Getting the same error when opening `http://localhost:8000/tests/javascript` but works when opening `http://localhost:8000/tests/javascript/`

**Comment by dhoko** [comment]
Mouhahaha same here, it's ok with [tests/javascript/](
http://localhost:8000/tests/javascript/). :tada:

2015-09-01 12:32 GMT+02:00 Thomas Steur <notifications@github.com>:

**Comment by dhoko** [comment]
With master :) 

![screenshot from 2015-09-01 14 00 39](https://cloud.githubusercontent.com/assets/713283/9603610/0baf2e64-50b2-11e5-86db-c5b3272da295.png)

**Comment by tsteur** [comment]
It's kinda possible that they fail randomly if you run them in a browser and eg scroll while tests are running etc :( They should always run via phantomjs

Yay for working tests :)

**Comment by mattab** [comment]
feel free to re-open or re-create if needed :ok_hand:
