### ISSUE TITLE
New setting to disable Do not track but respect "Active Opt Out" from users (require button click)

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#6147]
Do not track function (dnt) setting - 3.state needed
to prevent distorted statistics

At this time one could choose in Piwiks settings between two states of do not track function:
1) respect it (enable do not track support - this is recommend by piwik)
2) don't care about it (disable do not track support => track everyone)

Maybe this is a little hard and only black/white
-> especially since there are some large browsers (some IE 10,11) which set "do not track" as there standard/default/automatic setting even if it would be fine for the the visitor -but he was not asked before...
=> having this the statistics we get from Piwik for our sites could be really distorted when enabling full do not track support (1)

With the "CustomOptOut" plugin the vistor have the possibility to Opt Out from tracking on our site with the click a button - > this possibility is great and the active choose of the visitor should be respected.
But as mentioned before activating support for do not track in general could distort our statistics...

A way to solve this, could be a third stated of setting
3) disable standard do not track support but respect "Active Opt Out" from users button click

**Comment by mattab** [comment]
Thanks for the report. We  likely won't work on this but will hopefully implement in the future a partial counting for DoNotTrack visits: https://github.com/matomo-org/matomo/issues/12001
