### ISSUE TITLE
Visitor profile: display detailed user devices info

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#6161]
Using the great feature "Accurate User Detection cross devices #3490", there should be a possibility to still know from where/which device which sites have been visited /which actions (events) have been made by the visitor.

Maybe one could give in the visitor profile:
- the number and types of devices used by this visitor (on the left in visitor info)
- add the number of visits in percent by each device
- the information from which device each visit was from (in the head of each visit, right column) and
- maybe something like a filter e.g. with tabs to see "all visits", "visits from device 1", "visits from device 2" ....

as proposed in the comments from #3490, this was extracted and extended to an extra issue

**Comment by ryanmccoy** [comment]
#3490 is fantastic, but without this visitor profile enhancement it falls just shy of being perfect. I would love to see this come to resolution.

**Comment by mattab** [comment]
@sgiehl could you take a quick look at this one?

**Comment by hpvd** [comment]
solution can/would be part of:
visitor profile: built image of vistor is distorted #9507

**Comment by mattab** [comment]
> the information from which device each visit was from (in the head of each visit, right column) and

This was implemented 

other request is covered in https://github.com/matomo-org/matomo/issues/9507
