### ISSUE TITLE
Adhere to the User Data Manifesto 2.0

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#6197]
The goal of this issue is to make Piwik explicitly compatible to the [User Data Manifesto 2.0](https://userdatamanifesto.org/2.0/). This manifesto aims at defining users’ fundamental rights to their own data in the Internet age. People ought to be free and should not have to pay allegiance to service providers. 

**Steps**
- Create a file misc/user-data-manifesto.md containing the raw text for the data manifesto and specific points on how Piwik respects this manifesto. The [text of the manifesto is here](http://udm.branchable.com/index.en.html).
- The manifesto covers three rights:
  - **Control** over user data access 
  - **Knowledge** of how the data is stored 
  - **Freedom** to choose a platform
- Create a blog post about the User Data Manifesto and how Piwik respects it.
- Link to the blog post from our [Privacy page](http://piwik.org/privacy/) and the privacy user guide.

**References**
- Create a PRIVACY.md file #6196, Create a Privacy seal #6173,  Become a GNU Package #5276, Clarification of Piwik's goals regarding privacy  #6160
- Piwik user guides: [Privacy](http://piwik.org/docs/privacy/), [Data limits](http://piwik.org/docs/data-limits/)
- [Issues tagged with Privacy](https://github.com/piwik/piwik/labels/c:%20Privacy)
- Maybe relevant with [NZ Cloud code](https://www.nzcloudcode.org.nz/Cloudcode)
- refs [userdatamanifesto on github](https://github.com/userdatamanifesto/www/issues/3).

**Comment by hamzzaa12** [comment]
@mattab  Thanks for contributing to this issue. As it has been several months since the last activity, and we believe it's likely not an issue anymore, we're closing it. If that's not the case, please feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We'll gladly take another look!
