### ISSUE TITLE
Pages - Bounce Rate 100% , Transitions show traffic to subsite instead of exit

### ISSUE THREAD

**Issue by MichalTomczak** [matomo-org/matomo#6225]
Hello,
Please see below email, I was able to recreate this issue and it looks like a bug, but maybe I'm wrong?

"I’m trying to check the existence of a bug we have on our environment, to see if it exists on your Demo environment. It does, in my opinion.Check the following:
http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2014-09-04#/module=Actions&action=menuGetPageUrls&idSite=7&period=day&date=2014-09-04
In that page sort based on Bounce rate, so that the rows with 100% bouncerate comes first.
Check the transitions on one of those rows (preferable with more than 2 pageviews).
You notice that is contains data showing “From Internal Pages”  and/or “To Internal Pages”
You might notice some rows with 100% bounce rate with on the same row a 50% Exit rate.
Could you please look at this bug?"

**Comment by mattab** [comment]
It was also reported [in this forum post](https://forum.piwik.org/t/bounce-rate-100-but-transitions-show-visitors-moved-on/19609/3 ) with screenshots showing the issue

**Comment by symposion** [comment]
I believe that this issue is based on a misunderstanding of what Bounce Rate means - because I had exactly the same confusion. The Bounce Rate is the percentage of users who enter on that page who leave immediately. It is *not* the percentage of total page views that are bounces. Pages that are very rarely entry points to the site tend to have very high bounce rates, since users that end up there often leave immediately (they've somehow entered in the middle of a flow).

**Comment by EVGR** [comment]
Hi!
Perhaps you are correct. I found that bounce rate is calculated using this formula:
entry_bounce_count (single page visits on this page) / entry_nb_visits (all visits that started on this page)
So the total page views are not considered here. Could be good to clarify this even more in the gui.
The transitions report considers the total page views and that is why you can not compare it to bounce rate numbers.
Thanks for explaining this to me!
Best regards,
E

**Comment by tsteur** [comment]
Closing as per @symposion comment it is working as expected and there is likely some confusion around how the bounce rate works.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/100-bounce-rate-has-a-bug/61245/1

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/100-bounce-rate-has-a-bug/61245/3
