### ISSUE TITLE
allow grouping by dimension in reporting API

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#6227]
This ticket is for allowing some way to specify one or more dimensions that can be used to group metric result. For example, the query: **groupBy=city&method=Referrers.getKeywords** could result in:

```
{ // a DataTable\Map
    'Tokyo': [
        {'label' => 'keyword1', 'nb_visits': ...},
        ...
    ],
    'London': [
        {'label' => 'keyword1', 'nb_visits': ...},
        ...
    ],
    ...
```

To accomplish efficiently this will require changing the archiving code significantly and should wait until it is refactored.

**Comment by loopmode** [comment]
this would also allow a fix for https://github.com/matomo-org/matomo/issues/11755, right?

**Comment by tsteur** [comment]
BTW this can be done with Custom Reports. You can create a report via the API and specify by what it should be grouped, then fetch the report...

Learn more about the power of Custom Reports in the user guide: https://piwik.org/docs/custom-reports/ or FAQ: https://piwik.org/faq/custom-reports/

This premium plugin can be purchased here: https://plugins.piwik.org/CustomReports

**Comment by diosmosis** [comment]
@tsteur if this functionality is provided by a plugin, can this be closed?

**Comment by mattab** [comment]
Considered done as it is available in custom reports product: https://piwik.org/docs/custom-reports/

**Comment by loopmode** [comment]
Too bad this gets closed, as the plugin/product is apparently not free: https://plugins.matomo.org/CustomReports
