### ISSUE TITLE
Content-tracking: I want to be able to disable piwik.php redirect and instead use the link tracking 500ms solution.

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#6265]
Especially useful for single page applications but also if someone does not want to have piwik.php links in his page.

piwik.php redirects are currently used if a link goes to the same domain.

**Comment by mattab** [comment]
This may be needed for: https://github.com/matomo-org/matomo/issues/13681 - see comment in https://github.com/matomo-org/matomo/issues/6641

**Comment by tsteur** [comment]
There's no reason to be able to enable it anymore since there is enableSendBeacon etc. The redirect is slower etc and shouldn't be needed.
