### ISSUE TITLE
When creating a new user, the password should not be visible, but stars

### ISSUE THREAD

**Issue by marclaporte** [matomo-org/matomo#6329]
Seen on Piwk.pro (Piwik 2.6.1.)

![2014-09-28_piwik_password_field](https://cloud.githubusercontent.com/assets/1004261/4436001/57540aa2-4761-11e4-8840-b52a09d5a452.png)

Thanks!

**Comment by randy-innocraft** [comment]
Hi @marclaporte. Thank you for creating the issue. [PR#12093](https://github.com/matomo-org/matomo/pull/12093) has addressed the issue by updating the User management page. The password field is no longer displayed on the Manage Users page. Therefore, this issue will now be closed.
