### ISSUE TITLE
Footer icons displayed by default in the footer or in the header

### ISSUE THREAD

**Issue by pksh** [matomo-org/matomo#6362]
Original discussion here --> http://forum.piwik.org/read.php?15,120294

The basic idea is to allow easy to use interface for all. I like the Piwik's new look and cool features like exporting data to multiple formats, exporting graphs to image and detailed  table view. But these features are hidden is not obvious for some users (especially my non-technical clients). So, I suggest these icons/buttons are displayed by default. 

If anybody prefers to have a minimalistic or focused view, there is a nice feature in Piwik called Zen Mode which hides these buttons anyway (or footer collapse cursor is available too).

**Comment by atom-box** [comment]
_A user told us:_ 

"Main actions are stuck to the bottom of de tag/trigger/variable overview. Again with 40+ tags this asks for some scrolling. Doing this one time is no problemo.. When a bigger analytics use case comes across and I need to add multiple tags in succession the scrolling becomes a bit more cumbersome"

**Comment by mattab** [comment]
Thank you for creating the issue, very appreciated :raised_hands: 
There were quite a few issues with the same theme: https://github.com/matomo-org/matomo/issues/6362 https://github.com/matomo-org/matomo/issues/15873 https://github.com/matomo-org/matomo/issues/19669 https://github.com/matomo-org/matomo/issues/21147 https://github.com/matomo-org/matomo/issues/19355
i'll mark this as closed in favor of this issue: https://github.com/matomo-org/matomo/issues/19669
