### ISSUE TITLE
Scheduled reports: hard to differenciate pages from groups of pages

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#6488]
The goal of this issue is to improve the Scheduled Emails reports (html, pdf) to better show which entries are Pages and which entries are folder.

In Piwik UI there is a clear differentiation between Pages and Directories grouping many pages:
![ui](https://cloud.githubusercontent.com/assets/466765/4712271/b465c7dc-58cb-11e4-9e8a-59dee89ddd22.png)

In Scheduled reports both look similar and therefore it causes confusion:

![email](https://cloud.githubusercontent.com/assets/466765/4712280/d422fcac-58cb-11e4-8d3e-f275b765c1ae.png)

**Proposed steps**
- Prepend `+` and `-` icons to directories rows
- Check pages are clickable to page URL

refs #2137

**Comment by tsteur** [comment]
We are now showing a flattened report so it's no longer an issue
