### ISSUE TITLE
Remove all methods out of plugins/*/API.php that have an @ignore annotation

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#6535]
Makes no sense by definition. In API.php should be only methods that are callable via the HTTP API. 

Instead those methods should be moved in different classes. Such as a Model or something more meaningful.

**Comment by sgiehl** [comment]
Just to be sure. That would currently include the following API methods:

* [ ] API.getSVGLogoUrl
* [ ] API.hasSVGLogo
* [ ] Annotations.getDateRangeForPeriod
* [ ] CustomVariables.getReservedCustomVariableKeys
* [ ] DBStats.getArchiveTableYear
* [ ] Events.getActionToLoadSubtables
* [ ] Events.getDefaultSecondaryDimension
* [ ] Events.getSecondaryDimensions
* [ ] Goals.getConversions
* [ ] Goals.getNbVisitsConverted
* [ ] Goals.getConversionRate
* [ ] Goals.getRevenue
* [ ] LanguagesManager.getPluginTranslationsForLanguage
* [ ] Live.getLastVisitsForVisitor
* [ ] MobileMessaging.sanitizePhoneNumber
* [ ] MobileMessaging
* [ ] MobileMessaging
* [ ] MobileMessaging

**Comment by tsteur** [comment]
I'm now wondering how important it actually is. These methods can't be called through the API right? It doesn't seem all that important and I reckon we could close the issue if they can't be called directly.

**Comment by sgiehl** [comment]
They can't be called directly. Nevertheless it might not make any sense to have public methods in an API class that should not be callable. But if it's not important right now, I'll stop working on it for now.
Feel free to close the issue or move it to a later milestone...

**Comment by tsteur** [comment]
Agreed it doesn't make sense but it's also not any important. It really doesn't make any difference at the end of the day. Will close it.
