### ISSUE TITLE
Introduce list of visitors identified with User IDs searchable and segmentable 

### ISSUE THREAD

**Issue by Facens** [matomo-org/matomo#6608]
Hi,
given the interest for my feature request on the Piwik Forum (http://forum.piwik.org/t/list-of-visitors-profiles/13943), I was asked there to place a feature request here.

What I'd love to display is a list of the visitors that are identified with User IDs, with the following specifications:
- I want to see all the users that are identified, in a list that is searchable and segmentable
- I want to be able to retrieve this list via API

I find surprising that the only way to currently display a visitor profile is through the visitors log, which has the limit of only showing the visitors by date of last visit. Other paid services like MixPanel provide this feature, which is indeed very powerful.

Thanks in advance for any feedback or contribution; unfortunately our team works with Rails – not PHP – so we lack the skills to lay a hand, or we'd do it ourselves.

**Comment by ruchitrami** [comment]
+1

**Comment by Shragel** [comment]
+1

**Comment by nicolasesprit** [comment]
+1

**Comment by pennadl** [comment]
+1

**Comment by mattab** [comment]
Hello, this was implemented a few months ago and you can now see the list of User IDs in the report Visitors > User IDs
