### ISSUE TITLE
Geo location ipv6 for PECL extension

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#6624]
The goal of this issue is to add support for GeoIP PECL to geo locate IPv6 addresses. 

in #3581 and #6574 we've added [geo location capability](http://piwik.org/docs/geo-locate/) to IPv6 addresses. It works for GeoIP (Php) and for GeoIP (HTTP Server Module). However the feature is not yet added to the PECL extension and this is tracked in this bug report: https://bugs.php.net/bug.php?id=59124

**Comment by cyplo** [comment]
It seems that the referenced PECL bug is closed now - is there more work on Piwik side to be done here ?

Quoting from PECL bug tracker:
>  [2016-08-19 00:32 UTC] ohill@php.net
-Status: Assigned +Status: Closed
 [2016-08-19 00:32 UTC] ohill@php.net
> Available in 1.1.1

**Comment by mattab** [comment]
@cyplo We haven't tested yet. Could you maybe test the new PECL release and report whether it works or not?

**Comment by NitroxydeX** [comment]
We have the latest geoip-1.1.1 but it still doesn't recognize the v6 file as it seems.

**Comment by sgiehl** [comment]
Closing this one, as we meanwhile deprecated support for GeoIP and GeoIP2 should support IPv6
