### ISSUE TITLE
When real time map doesn't display users, display help message notification with solution

### ISSUE THREAD

**Issue by alphaonex86** [matomo-org/matomo#6704]
Hello,

My real time map don't work since lot of version (only the first implementation work).
There is no data for this report but live visitor work.
https://WWWWW/index.php?period=range&idSite=9&segment=&date=last30&format=json&showRawMetrics=1&module=API&method=Live.getLastVisitsDetails&filter_limit=100&showColumns=latitude%2Clongitude%2Cactions%2ClastActionTimestamp%2CvisitLocalTime%2Ccity%2Ccountry%2CreferrerType%2CreferrerName%2CreferrerTypeName%2CbrowserIcon%2CoperatingSystemIcon%2CcountryFlag%2CidVisit%2CactionDetails%2CcontinentCode%2Cactions%2Csearches%2CgoalConversions%2CvisitorId%2CuserId&minTimestamp=-1
Have content.

Cheers,

**Comment by mattab** [comment]
Hi @alphaonex86  do you still have the issue in the latest Piwik release? (if so would you mind posting a screenshot)

**Comment by alphaonex86** [comment]
Yes the issue remain active :(
http://files.first-world.info/temp/piwik.png

**Comment by mattab** [comment]
i'm wondering if it's same bug as in: #6703

Does it maybe work when you load Piwik over HTTP?

**Comment by alphaonex86** [comment]
Don't work in https and http.

**Comment by mattab** [comment]
@alphaonex86  would it be possible to get access to your PIwik server? if you can email me matt att piwik.org your piwik URL + login + password + link to this issue, it would really help. Thanks

**Comment by alphaonex86** [comment]
Send by email

**Comment by mattab** [comment]
@alphaonex86 thanks for sending the access. Reproduced that the real time map doesn't work. it's strange because the data received by the API looks correct and works. So there is a problem in the JS somewhere. there is no error logged... the normal non-real time map works well too. 

If anyone has also this issue of Real time map does not work while the other maps in `Location` menu works, please leave a comment

**Comment by alphaonex86** [comment]
It's the seconds hurge and problematic bug in my case. Hardened and stabilise the code is very usefull for large scale usage. And don't keep years/months the bug open without any work on it.

**Comment by alphaonex86** [comment]
Same with 2.13

**Comment by alphaonex86** [comment]
Any way to have priority for this bug?

**Comment by diosmosis** [comment]
@alphaonex86 I took a look at your Piwik using the credentials you sent to matt. The problem is that the realtime map requires visits to have latitude/longitude data, but none of them do. I looked at your geolocation settings, and it looks like you only have the country database. Can you use the city database?

**Comment by alphaonex86** [comment]
Then the first step is do a warning on realtime map. I will try that's.

**Comment by alphaonex86** [comment]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
index.php?module=Proxy&action=getCoreJs&cb=503856cd524ab9742be8e70c310a3d17:2522 Uncaught TypeError: Cannot read property 'remove' of undefined

**Comment by mattab** [comment]
> Then the first step is do a warning on realtime map.

:+1: When we detect that the user is not using the city database, we could display a warning notification above the real time map eg. `For the real time map to work, you need to use the GeoIP City database. Please go to <a>Geolocation settings</a> and setup the GeoIP city database.` or better

**Comment by alphaonex86** [comment]
Yes, and like you do when only have country but not city, resolv from country database.

**Comment by alphaonex86** [comment]
if(removeOldVisits){visitSymbols.remove(function(r){if(r.lastActionTimestamp<oldest)_removed++;return r.lastActionTimestamp<oldest;});}
Uncaught TypeError: Cannot read property 'remove' of undefined

**Comment by diosmosis** [comment]
@alphaonex86 I checked your realtime map (using the credentials you provided to @mattab) and it looks fine (viewed on Chrome). I can email you a screenshot if you'd like.

**Comment by alphaonex86** [comment]
@diosmosis it's the problem, sometime work, other time don't work.

**Comment by diosmosis** [comment]
To try and diagnose the issue, you'll have to find the result of a specific XHR request when the map isn't working. To do this when you see the error, do the following:

1. Open the inspector tools & reload the page.
2. Switch to the 'Network' tab.
3. Look for the XHR request that looks like `index.php?module=API&method=Live.getLastVisitsDetails` and get the response.

If there's no error in the response, then look at your webserver logs & the Piwik log file (if you've got logging enabled). Hopefully there will be an error somewhere.

**Comment by alphaonex86** [comment]
[28-May-2015 01:26:31 UTC] PHP Fatal error:  Call to undefined method Piwik\DataTable\Map::getMetadata() in /home/first-world.info/stat/plugins/Bandwidth/Bandwidth.php on line 117
[28-May-2015 01:26:31 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Call to undefined method Piwik\DataTable\Map::getMetadata()' in /home/first-world.info/stat/plugins/CorePluginsAdmin/Controller.php:371
#1 /home/first-world.info/stat/core/FrontController.php(531): call_user_func_array(Array, Array)
#2 /home/first-world.info/stat/core/FrontController.php(97): Piwik\FrontController->doDispatch('CorePluginsAdmi...', 'safemode', Array)
#3 /home/first-world.info/stat/core/FrontController.php(184): Piwik\FrontController->dispatch('CorePluginsAdmi...', 'safemode', Array)
  thrown in /home/first-world.info/stat/plugins/CorePluginsAdmin/Controller.php on line 371

On the log I see only that's.

**Comment by diosmosis** [comment]
That error is unrelated. Please follow the steps in my comment when the realtime map is not working.

**Comment by alphaonex86** [comment]
Ok. Can you at least put and if fonction undefined where mentionned skip the code part to prevent error?

**Comment by diosmosis** [comment]
You can add this yourself if you don't want to investigate the random issue, but we won't hide a possible bug in an actual release.

**Comment by mattab** [comment]
> @alphaonex86 I took a look at your Piwik using the credentials you sent to matt. The problem is that the realtime map requires visits to have latitude/longitude data, but none of them do.

issue was renamed and scope reduced to: `When real time map doesn't display users, display help message notification with solution`.

The notification would be displayed when the wrong Geo ip database is used, and would suggest user to setup the right geoip database instead (with a link to Administration > Geo location settings).

**Comment by RomanStone** [comment]
My case Switched to 
Settings -> Geolocation -> GeoIP 2 (Php) : On
to make Real-time Map work.

Reason 
# piwik/plugins/UserCountryMap/javascripts/realtime-map.js:407
```
if (report.length) {
    // filter results without location
    report = $.grep(report, function (r) {
        return r.latitude !== null;
    });
}
```

And Ajax Response with "Default" Location Provider
```
{
...
    "city": null,
    "latitude": null, <--
    "longitude": null,
    "visitLocalTime": "00:00:01"
}
```
