### ISSUE TITLE
Emails sending issue through cronjob: Bad sender address syntax

### ISSUE THREAD

**Issue by jfqd** [matomo-org/matomo#6717]
Sending emails through the website works just fine, but sending it through the cronjob fails with the following error:

```
ERROR CoreConsole[2014-11-24 01:11:40] [085de] Got invalid response from API request: http://piwik.example.com/index.php?module=API&method=CoreAdminHome.runScheduledTasks&format=csv&convertToUnicode=0&token_auth=token-string&trigger=archivephp. Response was 'task,output Piwik\Plugins\ScheduledReports\API.sendReport_10,ERROR: An error occured while sending 'HTML Email Report - 10.2014-11-17.9.de.html'  to abc@example.com. Error was '5.1.7 Bad sender address syntax
' Piwik\Plugins\ScheduledReports\API.sendReport_100,ERROR: An error occured while sending 'HTML Email Report - 100.2014-11-17.94.de.html'  to def@example.com. Error was '5.1.7 Bad sender address syntax
''
ERROR CoreConsole[2014-11-24 01:11:40] [085de] 1 total errors during this script execution, please investigate and try and fix these errors.
```

I am using the latest version 2.9.1. This issue started after the update from version 1.1.2 to 2.8.

I think this issue is not related to #4944 or the following forum entry http://forum.piwik.org/read.php?2,113063.

In the log of the mailserver I only can see a connect and disconnect message, but nothing else.

Any ideas how to fix this issue?

**Comment by stibay** [comment]
Struggled alot with the same error message. Finnaly figgured out that **login_password_recovery_email_address** was the problem and had to be set manually in the config,ini file. Piwik 2.16.0

**Comment by stibay** [comment]
Got the same error on the forget password page on login.
Figgured out that **login_password_recovery_email_address** was the problem and had to be set manually in the config,ini file. Piwik 2.16.0

**Comment by mattab** [comment]
Hello everyone,
We have created a FAQ to help about this issue: https://matomo.org/faq/troubleshooting/faq_34856/

Hopefully it will help people get their emails working. if you have any issue with receiving emails from Matomo please follow the FAQ and let us know how it goes (by following the "Contact support" link in the FAQ). Have a great day!
