### ISSUE TITLE
Pages analytics--> Content can't support port 8080

### ISSUE THREAD

**Issue by safetys123** [matomo-org/matomo#6743]
When I'm trach the content(http://developer.piwik.org/guides/content-tracking), for example, 
my html content is 

```
<a href="http://localhost/project" data-track-content data-content-name="no search result" data-content-piece="go home">go home</a>
```

Now the href is http://localhost/project,   If I click the go home, there will have a forward

But if the href add a port 8080, `http://localhost:8080/project` I click the go home, there will not have a forward.

**Comment by tsteur** [comment]
Closing as not reproducible
