### ISSUE TITLE
Row evolution: let user also see the evolution of relative % values

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#6770]
The goal of this issue is to enhance the [Row Evolution reports](http://piwik.org/docs/row-evolution/) and let it also display the % relative value for any of the metric where it makes sense (eg. visits, unique visitors, actions, etc.). 

This is an improvement following up #1816 

For example it would be great to:
- plot browser usage marketshare over time (Firefox ~ 20 % and see evolution month over month)
- plot evolution of websites referrers to see how given website participates to overall traffic
- ...

**Comment by ksubileau** [comment]
+1
Actually, today I wanted to know the IE8 usage evolution on my website, to see if I could drop its support for the next version. But the absolute value means nothing: if there is a lot more visitors a month, of course there will be more IE8 users. So I had to go from month to month to see the percentage and use Excel to get a nice chart...
Also, I'm interested to know the mobile devices usage evolution to see the importance of responsive design on my site, for example.
As @gaumondp shows with these related issues, this could be extended to all others reports where it makes sense, and not only in Row Evolution.
For me, this would be a very great improvement to Piwik.

**Comment by patriiiiiiiiiick** [comment]
+1

**Comment by mstenz** [comment]
+1
This is a high wanted requirement for Fujtsu and not limited to only some metrics.

**Comment by mattab** [comment]
Hi @mstenz please consider contacting us for sponsoring this development here: https://piwik.org/development/

**Comment by mattab** [comment]
covered and duplicated by https://github.com/matomo-org/matomo/issues/15515
