### ISSUE TITLE
DeviceDetection segment editor auto suggested values should show full strings 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#6772]
The goal of this issue is to review the Device Detection segments such as `browserCode` and `operatingSystemCode`.
- Currently the valid segment values  for `browserCode` are `FF`, `CH`, `IE`, etc.
  - would be more understandable and guessage to use `firefox`, `chrome`, `internet explorer` etc.
  - the segment auto suggest values should contain automatically all the top browsers we know of, instead of using the `Live` auto suggested feature. 
  - for Backward compatibility we should still accept `FF`, `CH` etc. and define `firefox` or `Chrome` as aliases to those ones.
- Same applies to `operatingSystemCode` where segment values would be pretty string such as `windows xp`, `windows 7`, `GNU/Linux`
  - it's case insensitive, both `Windows XP` and `windows xp` will alias to `WXP`

Implementation: refs `suggestedValuesCallback` feature.

**Comment by RMastop** [comment]
One of the things I miss the most in devicedetection, is the concatenation of all individual reports.
For example:
a devices report containing the Devicetype + Model + Operatingsystem family + browser family + Resolution 
a devices report containing the Devicetype + Model + Operatingsystem version + browser version + Resolution 

This report will be really fragmented, but it will give the developers of websites a pretty nice view of the combinations of devices that visit the website. Some companies have a policy for supporting at least the top x% of most visited combination of devices.

**Comment by sgiehl** [comment]
@RMastop Guess your comment might be related to #6933

**Comment by RMastop** [comment]
Yes, @sgiehl being able to see the combination of 'things' would be awesome!
