### ISSUE TITLE
All websites dashboard: Calculate evolution, making days interpolation and not absolute values

### ISSUE THREAD

**Issue by hightechguy** [matomo-org/matomo#6784]
Calculate evolution, making days interpolation and not absolute values as now. So, at 1st of the 30 days month All Websites dashboard looks like this - http://screencast.com/t/KmFkryLR29f, while there is no reason to make everything scary red.
In my opinion 1st of the month data evolution should be calculated as value \* [total days in the month] / [day in a month] , so October 1st data should be equal value \* 1/31, October 10 value \* 10/31 etc.

**Comment by tsteur** [comment]
Before working on this need to clarify with @mattab how to solve this problem. Related also https://github.com/matomo-org/matomo/issues/10291 which may need similar solution.
