### ISSUE TITLE
Provide a component / API to create "Manage" screens

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#6951]
Currently, we have a couple of Manage screens such as "Websites", "User", "Scheduled Reports", "Alerts", "Goals" and all work in slightly different way. Eg the "Create" link is positioned and formatted differently everywhere, some forms work with ajax whereas some not, some reload the page on save/cancel and some not, sometimes "inline editing" is supported whereas sometimes a new screen opens, error messages are handled differently, etc.

Goal would be to unify all those screens by having an API or a component to have this consistent. This would also allow developers to add easily such screens. Maybe the component could at least optionally also handle all the create/edit/save/get stuff regarding database etc. Not sure.

**Comment by mattab** [comment]
:+1:

**Comment by mgazdzik** [comment]
:+1:

**Comment by tsteur** [comment]
Ideally, this component would also allow to click on a table column label to sort the entries by the clicked column. This would be useful for cases like https://github.com/piwik/piwik/issues/6951

**Comment by tsteur** [comment]
This likely becomes a priority for us. If anyone knows some libraries that we can reuse to develop this feature please suggest ideas here. 

Whether it's for the backend in PHP to define entities with actions, or an Angular component for the frontend that can render tables and forms with actions etc.

**Comment by tsteur** [comment]
Something like https://github.com/json-schema-form/angular-schema-form could be interesting to render forms

**Comment by mattab** [comment]
@tsteur great find, this project looks very promising.

**Comment by mattab** [comment]
In the meantime this is available i believe.
