### ISSUE TITLE
Consider using sha256 instead of md5 in config/manifest.inc.php

### ISSUE THREAD

**Issue by aureq** [matomo-org/matomo#7029]
Hi

md5 is officially broken(1) and we should consider migrating to sha256 in config/manifest.inc.php 

Thanks

Links:
1. http://en.wikipedia.org/wiki/Collision_attack#cite_note-2

**Comment by tsteur** [comment]
Should be easy to change in Piwik itself but also requires change in other repos such as https://github.com/piwik/piwik-package/blob/master/scripts/build-package.sh#L169

**Comment by aureq** [comment]
@tsteur Totally agree with you, the ```build-package.sh``` as well as the ```Makefile```. But definitely no big deal.
