### ISSUE TITLE
RFE: setup a "piwik-announce" mailing list and post EOL/new version announcements there as part of the release process

### ISSUE THREAD

**Issue by MagicFab** [matomo-org/matomo#7063]
I'd like to suggest setting up a read-only (not "discussion" ) announcements mailing list where new release / upgrade and EOL announcements would be posted. This following [a suggestion by Dali in the forums](http://forum.piwik.org/read.php?15,123653,123680#msg-123680).

This would help systems administrators keep track of such developments. I know there are emails that can be configured from within a Piwik installation but in self-hosted/internal/test deployments it's not feasible to always have every  admin receive such emails. In some cases this can also be useful to subscribe other services (such as maintenance trackers/alarms).

This also provides a more permanent public record of such release announcements, regardless of website changes/redesigns/etc.

Here are a few examples of such mailing list in other projects:

https://lists.ubuntu.com/archives/ubuntu-announce/
https://lists.debian.org/debian-announce/

**Comment by tsteur** [comment]
Same would be interesting for plugin developers that should receive the Platform changelog: http://developer.piwik.org/changelog

**Comment by gaumondp** [comment]
I would suggest : 

1. In the changelog (each one of them from now on)
2. Link under "See what’s new in this release" there: http://piwik.org/download/
3. Link In the "About Piwik" dialog that check for new version
4. In the Piwik installer interface.

When I say link, I mean invitation to subscribe.

It's also important to indicate that the list is low traffic and managed by Core Team so people are not turned off by fear of spamming. 

While looking at a screenshot of the installer (last time I saw it was 2 years ago...) I came across this screenshot that tend to say # 4 is already there... But I don't recall getting such email...

See Super User section there : 
http://piwik.org/docs/installation/

**Comment by mattab** [comment]
Hi @MagicFab 

thanks for the suggestion. Currently we offer the [changelog RSS feed.](http://piwik.org/changelog/feed)

Do you think it would be enough to the announcement mailing list a copy of the new version changelog once it is published? we could use a RSS -> Email list script or service to make email announcements automated.

> While looking at a screenshot of the installer (last time I saw it was 2 years ago...) I came across this screenshot that tend to say # 4 is already there... But I don't recall getting such email...

@gaumondp Fyi users subscribing during the installation process are added to the general Piwik newsletter which has low volume, our last letter was 9 months ago: http://piwik.org/newsletter/

**Comment by filippog** [comment]
yep I think it'd be enough to post "new piwiki version x.y.z" as subject and the relevant changelog section as body, that would be really great!

**Comment by MagicFab** [comment]
Yes, pushing this to the announcement mailing list would be great. I know about the RSS feed, however email is something easier/faster to deal with in this context.

**Comment by mattab** [comment]
Madmimi our newsletter provider has a feature called RSS to email - it looks like we can create an automated mailing list from the RSS feed! this would be ideal. I setup this as a test for now. you can subscribe here: http://madmimi.com/signups/139168/join

not sure if it will work but it's enabled already, so we can see what happens after next release

**Comment by xuhdev** [comment]
@mattab What is the url of the RSS? I'm using an RSS to email service on my own, so probably it would also be an option for other guys...

**Comment by MagicFab** [comment]
Merci @mattab ! I've subscribed and will be commenting here when the next update shows up.
@xuhdev it's in @mattab 's comment Feb. 6: http://piwik.org/changelog/feed.

**Comment by mattab** [comment]
Hi @MagicFab - I received the email for 2.13.0 so it looks like it's working! 

As next step we could update the changelog pages to show a link to subscribe to this email newsletter.

maybe you have other suggestions?

**Comment by MagicFab** [comment]
I got emails for the last 3 updates, so this effectively works for me(tm) now :) I do hope that at some point this would not rely on a third-party service (madmimi). Perhaps Piwik could use [PHPList free service offer](https://www.phplist.org/the-gift-of-open-after-15-years-of-phplist-lets-liberate-open-source-land-newsletters/) in the future. It may also be useful to get some inspiration for http://wpvulndb.com/ regarding security announcements (which also involve plugins in this context).

@mattab regarding suggestions, yes, the changelog pages is a good spot. I would also expect to see such a link at these places:

* http://piwik.org/download/ under "See what's new..."
* https://github.com/piwik/piwik under the "Changelog" section

I can file separate bug reports to track progress if needed, later today, just let me know.

**Comment by mattab** [comment]
Added link to changelog newsletter to [How do I know when new versions are released?](https://piwik.org/faq/new-to-piwik/faq_12/)

**Comment by mattab** [comment]
We'll communicate in the blog instead
