### ISSUE TITLE
Screenshots in Piwik Tour user guide are outdated

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#7106]
I know, many screenshots are outdated on the website and we are aware of this. I think updating the screenshots in Piwik Tour and the description if needed is a bit more important since we link to it in emails re cloud etc. @mattab 

http://piwik.org/docs/piwik-tour

**Comment by tsteur** [comment]
I got some more mails meanwhile linking to different user guides, eg today https://piwik.org/docs/segmentation/

This guide as well shows very outdated screenshots.

**Comment by mattab** [comment]
This is mostly completed now :+1: we have a few more screenshots to update across guides but 95+ should be updated. Awesome! :tada:
