### ISSUE TITLE
System test test_GetCounters_ShouldOnlyReturnResultsOfLastMinutes sometimes fail

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#7165]
The goal of this issue is to investigate the system test `test_GetCounters_ShouldOnlyReturnResultsOfLastMinutes` which randomly fails the build (maybe depending on the speed of running the ci build? or the time? not sure)

Examples where the test failed the CI jobs:
- https://travis-ci.org/piwik/piwik/jobs/50134624

```
1) Piwik\Plugins\Live\tests\Integration\APITest::test_GetCounters_ShouldOnlyReturnResultsOfLastMinutes

Failed asserting that two arrays are equal.

--- Expected

+++ Actual

@@ @@

Array (

0 => Array (

- 'visits' => 24

+ 'visits' => 30

'actions' => 60

'visitors' => 20

'visitsConverted' => 40

)

)


```
- https://travis-ci.org/piwik/piwik/jobs/50134625

```
1) Piwik\Plugins\Live\tests\Integration\APITest::test_GetCounters_ShouldOnlyReturnResultsOfLastMinutes

Failed asserting that two arrays are equal.

--- Expected

+++ Actual

@@ @@

Array (

0 => Array (

- 'visits' => 24

- 'actions' => 60

- 'visitors' => 20

- 'visitsConverted' => 40

+ 'visits' => '28'

+ 'actions' => '60'

+ 'visitors' => '20'

+ 'visitsConverted' => '40'

)

)
```

**Comment by tsteur** [comment]
I think it uses the current timestamp so in case around midnight it might create some users for the previous day etc.

**Comment by mnapoli** [comment]
It has been some time that system tests have not been failing randomly from what I've seen, maybe we can close this one? (or maybe I've just missed those random failures?)

**Comment by tsteur** [comment]
It is still happening all the time see eg yesterday https://travis-ci.org/piwik/piwik/jobs/55422165#L1021

It just depends on the time see my previous comment. It uses the current timestamp so it cannot work.

**Comment by diosmosis** [comment]
If this is still broken, here's an idea to fix: move Date::factory to class called DateFactory. Then access the class through StaticContainer, then override in test DI Config with a mock factory that lets us override the date. What do you think?

**Comment by diosmosis** [comment]
Override the now/today date*

**Comment by mnapoli** [comment]
> Override the now/today date*

I've seen this needed in many places, done through private methods overridden using reflection in tests for example. So maybe that could be worth the trouble.

**Comment by mattab** [comment]
Still happening https://travis-ci.org/piwik/piwik/jobs/79763078 - somehow we need to fix this random test, or skip it around midnight

**Comment by tsteur** [comment]
The method to fetch counter actually uses `time()` and not `Date::now()` but  `Date::now()` uses `time()` as well. 

Maybe we could use `time` via DI where needed so it returns current time but one can override it to a fixed time. Did something similar in another plugin just recently:

```
    'MyPlugin.currentTime' => DI\factory(function () {
        return time();
    }),
```
 
It's just important that this one is by default not cached (in my case I needed it only once anyway). Of course we could also create a class etc to get current `time()` and others and replace that class if needed. Just went with above solution for simplicity

**Comment by mattab** [comment]
> Maybe we could use time via DI where needed so it returns current time but one can override it to a fixed time.

+1

**Comment by sgiehl** [comment]
Haven't seen it failing in the last months. Did anyone else? Otherwise guess we could close it now

**Comment by sgiehl** [comment]
Seems to work meanwhile
