### ISSUE TITLE
In the Segmented Visitor Log popover, let me open the Visitor Profile

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#7214]
The goal of this issue is to improve the powerful "Segmented Visitor Log" feature (in #4633) to let users open the Visitor Profile for any visitor, where currently the ["View Visitor Profile"](http://piwik.org/docs/user-profile/) link is hidden on the Segmented Visitor Log popover. 

* show the link 'Visitor profile', ideally on hover on the row only (as not to show a repeating "View visitor profile" in the popover, where we have less width available?). 
* When the link is clicked, the Visitor Profile popover opens on top of the 'Segmented Visitor Log' popover. One can view the visitor profile, and then close it, and then the "Segmented Visitor Log" popover is visible again.

**Comment by mattab** [comment]
@sgiehl sounds to me an acceptable solution :+1:

**Comment by diosmosis** [comment]
@sgiehl If the popover param is in the URL and saved in the browser history, maybe we could just open a new popover, then on close, invoke `window.history.back();` (or whatever cross browser version matomo currently does for this)?

**Comment by mattab** [comment]
@diosmosis just tested and noticed that the "Previous" button does not work to come back to the segmented visitor log popover. Could you please create an issue or PR for this feature as discussed above?

**Comment by diosmosis** [comment]
@mattab the back button in the browser works for that for me, do you mean the dialog 'close' button?
