### ISSUE TITLE
In the Segmented Visitor Log, let me open in a new tab the Piwik UI with the custom segment applied

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#7215]
The goal of this issue is to improve the great Segmented Visitor Log feature (from #4633), and let users apply the Segment to all Piwik reports (rather than just see the segment applied to the Visitor Log popover).

For example, maybe we could add an icon or a textual link "Apply this segment to the report [new tab]". When clicked, a new tab will open and this custom segment will be applied to all reports. 

Thoughts?

**Comment by mattab** [comment]
It will be super valuable to have a one-click way to "save" the current segmented visitor log as a segment.

### The goal of this issue is to somehow introduce a button `Add this segment` and when clicked, the segment editor would open pre-set with the segments pre-selected. 

Because we don't want to show a big button on Visits log all the times (to avoid clutter/noise), it needs to be displayed only on hover or something.

**Comment by diosmosis** [comment]
@mattab what do you think about this for the UI:

![image](https://user-images.githubusercontent.com/125140/52529751-79255e80-2cac-11e9-9351-44a63b61e8a9.png)

**Comment by mattab** [comment]
@diosmosis 

* When user clicks the link, it should open the segment editor and pre-sets a new segment with the expressions pre-selected. The segment would not be saved, until the user clicks the "Save & Apply" button in the segment editor. So the label could maybe simply say "Add as a new segment"? 
* Would be nice to display the Segment editor icon `icon-segment` next to the label (consistent with the segment editor displayed in the top controls bar)
* Although this feature is very valuable when you need it, it wouldn't be a frequent action to Add as a new segment (most of the time people will just look at the Segmented visitor log). So maybe we could display this link at the bottom of the popover, below the list of visits, next to the "Export" feature? This way it does not take up space at the top and is consistently displayed next to the existing/similar Export icon.

Thoughts?

**Comment by diosmosis** [comment]
Sounds good to me, minimal UI change.

**Comment by mattab** [comment]
a really great new feature! :tada:

**Comment by tkodjo** [comment]
awaiting this feature. I think it's game changer :)

**Comment by diosmosis** [comment]
@tkodjo this was released in 3.9.0, the button is at the bottom of the segmented visitor log popup
