### ISSUE TITLE
fr.piwik.org - Create Piwik.org in french - looking for Translators & Community organisers!

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#7295]
Bonjour,

The goal of this issue is to gather interest in the community and hopefully create together a team of people interested in creating, maintaining, and growing the French Piwik.org website.

The website is available at http://fr.piwik.org - it currently has a few pages that were translated, and one [blog post](http://fr.piwik.org/blog/2015/02/la-cnil-recommande-piwik-pour-respecter-les-lois-sur-la-protection-des-donnees/). Our goal will be to create a small team of Piwik users who are passionate about spreading the word about Piwik in France, and can maintain these translations up to date and translate new pages and blog posts. Later it could also make sense to create Twitter account in French, and more (ideas will be welcome!).

if you use Piwik and if you love the product, if you have time to help with translations and would like to be part of this project, please leave a comment here :+1:

**Comment by pierrevdk** [comment]
Hey,

As I told you by email I am available to help with the blog posts translation if you want.

Cheers,

Pierre
