### ISSUE TITLE
Support Right To Left languages in Piwik translations i18n effort

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#733]
We are hoping for Piwik to be platform that every user can use in their own language. We support translations for all elements: calendar, graphs, reports, admin interface, etc.

Currently the support for right to left language hasn't be tested and used yet. We would need to contact an arab or hebrew translator, then define what issues to fix in the UI.

For example we may have to add conditional css style that will overload text classes/ids: direction: rtl, text-align: right (when original is left), add definition in translation file indicating what type of language we load (rtl,ltr).          
- [Example of a custom RTL CSS](http://trac.dojotoolkit.org/browser/dijit/trunk/themes/tundra/tundra_rtl.css?rev=11656)

**Comment by shahar3012** [comment]
Hi, 
My native language is Hebrew. 
I'll add support for RTL languages in site theme (css). 
If you have some major points I should look at in order to understand everything that need to be supported, I would appreciate it if you let me know. 

Also, I'll try to add translation in Hebrew for all core plugins.

**Comment by sgiehl** [comment]
Regarding translations: Please register at http://translations.piwik.org to help improving the translations.

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
