### ISSUE TITLE
Check for updates over HTTPS

### ISSUE THREAD

**Issue by taoeffect** [matomo-org/matomo#7488]
At @mattab's suggestion:

> The check for new version is done over HTTP so far. that's maybe an issue, so feel free to create a new issue for that

See concern here: https://github.com/piwik/piwik/issues/6441#issuecomment-82743149

**Comment by ziegenberg** [comment]
I think this can be closed because Matomo already does try to use HTTPS when supported on the server-side. See https://github.com/matomo-org/matomo/blob/2ac2bc1aeaf8efce6bb9af92506311da99e1757f/plugins/Marketplace/config/config.php#L8-L16
