### ISSUE TITLE
Link to imprint and privacy policy

### ISSUE THREAD

**Issue by schwindelbub** [matomo-org/matomo#7513]
Hi,

often a Piwik instance is operated under a company domain, like tracking.company.example.
I this case it would be nice to have two links on the login screen to the company wide imprint and the privacy policy.

The URLs might be set in the config.ini.php

Best regards
schwindelbub

**Comment by mattab** [comment]
Hi @schwindelbub thanks for the suggestion!

**Comment by mattab** [comment]
Being discussed in https://github.com/matomo-org/matomo/issues/12938
