### ISSUE TITLE
Remove and/or fix all uses of non-API & deprecated methods/fields/classes/interfaces in maintained plugins

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#7569]
Now that there is a report for plugins that use deprecated/non-API symbols, we should fix the problems it reports. This can be done either by updating the plugin or exposing more symbols as `@api`.

Follows up https://github.com/piwik/piwik/issues/6539 & Refs #7633

**Comment by mattab** [comment]
Report is available behind password to team members at: http://builds-artifacts.piwik.org/protected/inspections.all/2015-03-29/inspections/all_inspections.out

**Comment by diosmosis** [comment]
Problem with this ticket: Many PRO plugins are only updated when the pro team decides to update the Piwik version used on cloud. This means, if we need to change the plugin to do things a different way, the change may not appear in master for a long time. So it may not be possible to complete this issue.

**Comment by mattab** [comment]
@diosmosis I'm trying to think of a solution to this issue. Is the problem that the inspection runs against `master` and maybe should run against `develop` instead for those plugins that have a `develop` branch? (would this solve the issue, or if not, do you have an idea of a solution)

**Comment by diosmosis** [comment]
That would solve part of the issue, however, if the PRO team doesn't incorporate the changes (maybe because they want to wait until they are ready to update to the next Piwik version), it won't help.

We could create issues on the repos, but I can't think of a way to deal w/ all the inspection failures w/o waiting a while.

**Comment by mattab** [comment]
> We could create issues on the repos, but I can't think of a way to deal w/ all the inspection failures w/o waiting a while.

I see. It's OK if it takes few days or weeks to merge those PR and have code inspection all green. Let's say that our goal here is to create those Pull requests for all repositories with inspection failures, so that when all such Pull requests will ultimately be merged, there will be no inspection failure left.

**Comment by mattab** [comment]
Moving to 3.0.0 - we haven't yet made much progress on this issue unfortunately, but I hope before 3.0.0 we can ensure plugins only use public API code :+1:
