### ISSUE TITLE
Use SSL to download plugins from the Marketplace

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#7582]
The goal of this issue is to have Piwik core download plugins and themes from the Marketplace over SSL when supported. 

If upgrade of plugins fail over HTTPS, over fallback to HTTP update of plugins (helping users keeping plugins up to date is vital)

Follows up: #6441, Refs  #7488

**Comment by SimonWaters** [comment]
Note that to do https fetches WordPress implements a copy of the Mozilla CA list.

**Comment by ziegenberg** [comment]
I think this can be closed because Matomo already does try to use HTTPS when supported on the server-side. See https://github.com/matomo-org/matomo/blob/2ac2bc1aeaf8efce6bb9af92506311da99e1757f/plugins/Marketplace/config/config.php#L8-L16

**Comment by bx80** [comment]
I believe this has been now been resolved by PR https://github.com/matomo-org/matomo/pull/19098
