### ISSUE TITLE
Piwik self service: let un-registered users register and create a website

### ISSUE THREAD

**Issue by sonic69** [matomo-org/matomo#7622]
Hi
I want other users to add your site in piwik!

I want other users to be able to register in piwik.
After registration can add their website 

Can this be done?

**Comment by amarsdml** [comment]
Yes this can be done. 
First Super admin should create another super admin.
Then New super admin can able to add site.

**Comment by mgazdzik** [comment]
two threads processed 8781 sites in 5397 secs, this gives average of 4,5 hours for all sites.

Will try tomorrow with 4 threads

**Comment by sonic69** [comment]
I want other users to be able to register in piwik.
After registration can add their website

**Comment by mattab** [comment]
Thanks for the suggestion @sonic69 - it would be a useful feature for some!

fyi: we used to have such plugin in https://github.com/piwik/piwik/issues/1148 but it wasn't updated in recent years.

**Comment by matunixe** [comment]
No updates about this? What's going on ?

**Comment by mattab** [comment]
Nothing happening at the moment, but if you are interested in sponsoring this feature, contact us via: http://piwik.org/development/

**Comment by alcalyn** [comment]
Hi, I also needed this feature, so I developed it and just released it on marketplace. It is installed on my Matomo instance for demo and use purposes.

Github: https://github.com/alcalyn/matomo-plugin-signup
Marketplace: https://plugins.matomo.org/Signup
Demo: https://matomo.nsupdate.info/

**Comment by Findus23** [comment]
Many thanks @alcalyn for the plugin!
