### ISSUE TITLE
Compare segments

### ISSUE THREAD

**Issue by DaSchTour** [matomo-org/matomo#7716]
Similar to the possibility google analytics offers it would be great, if piwik would allow to compare segments. I searched for a similar issue but couldn't find it. So hopefully this isn't a duplicate.

**Comment by mattab** [comment]
@DaSchTour absolutely, ability to compare the same data set for 2 segments, in the same data table, would be awesome! 

it's related / similar to the ability to compare two different date perids for the same report(s) in #5711 as in google analytics and other advanced analytics tools

In the meantime, you may be interested by the ComparisonDashboard plugin which lets you compare in the same dashboard, any Piwik report, for 3 segments / websites at once. It's available on [the Marketplace](http://plugins.piwik.org/ComparisonDashboard) and you can read user guide here: https://github.com/PiwikPRO/plugin-ComparisonDashboard#comparison-dashboard
