### ISSUE TITLE
Write a user guide for Custom Alerts

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#7719]
The goal of this issue is to create a user guide for a powerful and often overlooked feature: [Custom Alerts.](http://plugins.piwik.org/CustomAlerts)

Having a Custom Alerts [user guide](http://piwik.org/docs/) will help drive Piwik users to this plugin which they may benefit from.

**Comment by Findus23** [comment]
superseded by https://github.com/matomo-org/matomo/issues/10765
