### ISSUE TITLE
Add possibility to manage and view Intranet websites

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#7724]
Piwik can be used to track websites (including intranet websites) and mobile apps. 

Currently if you [measure Intranet portal](https://piwik.org/intranet-analytics/) using Piwik, it works well but users may need some ini config change (eg. [faq](http://piwik.org/faq/how-to/faq_19/)). 

Maybe we can design a simple but better way to manage Intranet websites for users?
### How creating intranet website brings value to users?

What's the value in creating an intranet website VS a normal website?
- when a website is set as intranet, we could ignore the ini setting `trust_visitors_cookies` and enable it always for this intranet site
  - enabling the setting helps data accuracy as many computers on an intranet have often shared IP addresses and same fingerprint hash 
  - currently users have to manually enable the setting `trust_visitors_cookies`, as documented in [How do I track visits on my intranet?](http://piwik.org/faq/how-to/faq_19/), and it would help users to remove this step
- in 'All Websites' dashboard (and in 'Manage websites') the Intranet websites could be clearly marked as 'Intranet' , maybe displayed differently (or "highlighted" in some way)
  - eg. setting the intranet website  with a `group` attribute will put all intranet websites in one group like in [Website groups plugin](http://plugins.piwik.org/WebsiteGroups)) 
## Notes
- we need the possibility to manage and view Apps #7131. 
- measuring intranet websites is a step towards our grand vision of building a generic Analytics platform that measures 'Mobile App', 'Wearable', 'Sensor', any 'Thing' that emits data: #4734 
- how do we spread the word about this Intranet feature? update FAQ: [Intranet analytics faq](http://piwik.org/faq/how-to/faq_19/) and [this one](http://piwik.org/faq/how-to/faq_175/), and user guide/page [Intranet Analytics](http://piwik.org/intranet-analytics/))

**Comment by mattab** [comment]
if you want to see better Intranet analytics in Piwik please post your comments and suggestions on how we could improve reporting for Intranet websites, we're listening :-)

**Comment by gaumondp** [comment]
Small comment: I was always reluctant to set "trust_visitors_cookies = 1" because I currently host both Public websites and Intranets on the same Piwik installation.

Reading the FAQ 2 years ago I decided to not set that setting and I stayed with the impression that setting up "trust_visitors_cookies" I would need a second Piwik installation.

At least, at the documentation level, you could add something about hosting both kind of sites and the impact/possibility to set trust_visitors_cookies and hosting a public website.

**Comment by AlroneRhyn** [comment]
Hi ! 
Managing intranet/internet sites separatly seems to me a great idear. I'm tracking both too and i would like to enable the do not track option for internet sites and disable it for my intranet sites. Or why not for a given site.

Thx a lot !

**Comment by MartinDesigner** [comment]
Regarding only to design internet sites, look at this stuff(!):
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. You can even design UI mockups for mobile as for standard display (html, js, css always generating without any coding required from you). Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by mattab** [comment]
FYI: updated the FAQ [ How do I track visits on my intranet?](https://matomo.org/faq/how-to/faq_19/)
