### ISSUE TITLE
Enable MySQL 5.7 installation on travis-ci

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#7776]
MySQL 5.6 installation was disabled on travis in this commit: https://github.com/piwik/piwik/commit/d84a440b774881a974b8b5f98386e89498c3e187

It was disabled since it consistently failed on travis. We should somehow re-enable it (or if MySQL 5.6 is available on travis now, use it directly).

**Comment by diosmosis** [comment]
https://github.com/piwik/piwik/commit/105051b4931b7388094bbc0d7b8332af16ec653b Refs this issue

**Comment by mnapoli** [comment]
For the record they are rolling back the updates, which is only temporary. https://www.traviscistatus.com/incidents/h91j8ft0qs2l

Related to our MySQL problems: https://github.com/travis-ci/travis-ci/issues/3781

**Comment by mattab** [comment]
Moved issue back to `Short term` - we're waiting for travis to officially rollout a stable Mysql 5.6

**Comment by mattab** [comment]
Ideally we'd skip the Mysql 5.6 and directly update to Mysql 5.7 since we need to support this new version (#6642)

**Comment by mattab** [comment]
Change title as we should run CI on mysql 5.7 instead of 5.6 - refs #6642

**Comment by tsteur** [comment]
Just FYI the related travis issue is https://github.com/travis-ci/travis-ci/issues/5122
