### ISSUE TITLE
Loading Flattened Page Urls report for 5 years long date range takes 45 seconds to load

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#7809]
The goal of this issue is to improve user experience and speed in the particular (#6759) use case of a large date range over many years and loading a flattened report. 

Currently in the example below:
- first load takes 45 seconds (on first load it will archive the data + display it)
- subsequent loads take 7 seconds (data is archived, just display it)

Reproduce:
- the date range was over 5 years old: `date=2009-05-02,2015-05-01&period=range`. 
-  [demo URL](http://demo.piwik.org/index.php?module=CoreHome&action=index&date=2009-05-02,2015-05-01&period=range&idSite=1#/module=Actions&action=menuGetPageUrls&date=2009-05-02,2015-05-01&period=range&idSite=1)

Ideally Piwik should archive data + display it under 10 seconds instead of 45 for a typical medium traffic website like piwik.org. Subsequent page load ideally should load in 1-2 seconds instead of 7. 
How would it be possible? 

we'll need to get creative, and some tools,  :coffee:  and a profiler

**Comment by gaumondp** [comment]
Serious question: What is a "medium traffic website" for you/Piwik ?

In Piwik's world, "medium traffic" means 5k to 10k pageviews/day ? Piwik's own site had 3000 pageviews /daymax last month.

Do my 90k pageviews a day installation worth "high traffic website" moniker ?

**Comment by mattab** [comment]
90k pages per day, ~ 3M per month, is considered high traffic

**Comment by mattab** [comment]
On demo.piwik.org today, loading the page took 25 seconds. Looks like we improved compared to May where it took 45 seconds to load the page.

**Comment by mattab** [comment]
Thanks for your patience with this issue. We believe this has been resolved in the recent updates of Matomo. To ensure you have the fix, please [update](https://matomo.org/docs/update/) to the latest version of Matomo.  If the issue persists after the update, don't hesitate to reopen this issue and let us know. Cheers!
