### ISSUE TITLE
When Piwik is in maintenance mode, the API should return a valid response

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#7901]
When Piwik is in maintenance mode, the API should return a valid response. 

Reproduce:
- Set Piwik [in maintenance mode](https://piwik.org/faq/how-to/faq_111/) with maintenance_mode=1
- Open `index.php?module=API&method=API.getPiwikVersion&format=xml`
- Got: the API call returns the HTML page of the maintenance mode
- Expected: 
  - HTTP Status code 503,
  - and the API call returns a valid eg. XML response that returns the standard API error reponse eg. 

```
<?xml version="1.0" encoding="utf-8" ?>
<result>
    <error message="Piwik is undergoing maintenance. We will be back up and running again soon, so please try again later. Your analytics data will continue to be tracked as normal. Thank you for your patience." />
</result>

```

Steps:
- Add test case 
- Fix issue

Refs #7902 #7903

**Comment by tsteur** [comment]
I tried to implement it but we'd need to load plugins in order to get an API renderer unless we hardcode the response for each possible API format.

**Comment by mattab** [comment]
>  in order to get an API renderer unless we hardcode the response for each possible API format.

Along with the response, we also need proper content-type http header. maybe we can manually use the API renderers objects, without having to load the plugins? or what would you suggest?

**Comment by tsteur** [comment]
We'd have to hardcode this as well unless we load the plugins, then the `ResponseBuilder` takes care of headers. 

I'm not sure what the best solution is but after discussing with @diosmosis it seems to be worth waiting for #8329 . Then we will no longer have to load plugins to get dimensions implemented by plugins.

**Comment by mattab** [comment]
if #8329 is merged in 2.15.0 we could fix this issue, otherwise we will move it to 3.0.0

**Comment by mattab** [comment]
as discussed, because https://github.com/piwik/piwik/pull/8329 was moved to 3.0.0 we also move this one

**Comment by mattab** [comment]
Fixed in the meantime
