### ISSUE TITLE
Rewrite all synchronous XHR as they are deprecated

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#8020]
Since Chrome 43 I am getting this warning in developer tools:

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

I noticed especially in Dashboards plugin some sync requests but there might be even more. We need to rewrite those requests to be async.

I'm tagging it as performance/enhancement since it will also make the UI a bit faster. Feel free to change it.

**Comment by tsteur** [comment]
FYI: In Piwik 3 UI already all synchronous requests were converted to async mainly because of moving to angular. There are only 6 usages left in the Dashboard plugin and I think 5 of them could be converted by simply converting the `xhr.send(true)` to `xhr.send()`

**Comment by tsteur** [comment]
This could be still delayed a little and done in a 3.1 release

**Comment by sgiehl** [comment]
I guess that one was already fixed with #12546. Did a quick search an couldn't find any remaining synchronous XHR
