### ISSUE TITLE
Segment doesn't work with IE 10 when containing lesser or greater than comparison

### ISSUE THREAD

**Issue by jarkkojarvinen** [matomo-org/matomo#8077]
Customer reported they get error message with Piwik 2.13.1 and IE 10: "The segment 'xxx&gt' is not valid...". 
Detailed error message in message: http://forum.piwik.org/read.php?15,116512,page=1#msg-127016

NOTE: Piwik 2.13.1 works fine with newest Chrome and Firefox and IE 11.

Steps to procedure:
1. Open IE 10 and login to Piwik 2.13.1
2. Create segment e.g. actions > 10 or visitors < 3 or similar
3. Visitors - Visitor log - Pick up some data range and try to use created segment
4. Error message will appear soon

**Comment by sgiehl** [comment]
We meanwhile fully dropped support for IE, also we didn't hear about any problems with segments not working in supported browsers lately. So I will close this issue. If anyone still has similar problems, feel free to create a new issue. Thanks.
