### ISSUE TITLE
Deprecate the PHP serialization response format

### ISSUE THREAD

**Issue by mnapoli** [matomo-org/matomo#8100]
A possible response format for APIs is in a PHP serialized string. This isn't good for many reasons:
- readable only by PHP
- prone to not work across systems or across time (e.g. differences between HHVM and the zend engine)
- very fragile (e.g. some plugin replace words in responses, this break this format)
- not standard at all (JSON, XML & co are more than enough for an HTTP API)

We could deprecate it for 3.0 and remove it later.

**Comment by diosmosis** [comment]
+1

**Comment by mattab** [comment]
Sounds good to me too. 

Hi @braekling - FYI: we may deprecate serialised PHP api output in Piwik 3.0.0. maybe it would be possible to plan ahead of this change, and make WP-Piwik use another API format eg. JSON? (IIRC wp-piwik is using php serialised api)

**Comment by mattab** [comment]
* When this will be done let's remove the temporary fix for  'serialize=1' in WhiteLabel plugin

**Comment by braekling** [comment]
@mattab Thanks for the advise. I'm working on this.

**Comment by braekling** [comment]
FYI: WP-Piwik is using JSON now.

**Comment by mattab** [comment]
Hi @braekling great to know!

**Comment by mattab** [comment]
Note: search in codebase for `format=php` for uses in core that should be changed (also two UI tests: CoreUpdaterDb and ReportExporting)

**Comment by mattab** [comment]
Moving tentatively to Piwik 4.0.0 (PHP format export causes some issues such as https://github.com/piwik/piwik/issues/11108 )

Maybe we could announce the PHP format deprecation in Piwik 4 and remove it completely in Piwik 5

**Comment by tsteur** [comment]
@mattab I reckon it should be fine to directly remove as part of Matomo 4. It be rarely used I suppose and it's quite easy to migrate to JSON for example. (all you need to do is basically a `json_decode()` on the response I reckon)

**Comment by mattab** [comment]
since it's so easy to change to json instead, sounds good to remove the PHP format in Matomo 4 directly :+1:
