### ISSUE TITLE
The Matomo platform, our public APIs, and maintaining backward compatibility

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#8125]
In this issue we shall describe what parts of the Piwik platform are publicly available for other developers to use. The goal of this issue ideally is to create a guide or page (likely on developer.piwik.org) to document this knowledge.
### Our public APIs

We call these "Public APIs" but this term can be a bit confusing as it includes more than just APIs. 

Everything below is considered a public API:
- [Reporting HTTP API](http://developer.piwik.org/api-reference/reporting-api).
  - They are defined in API.php files and APIs are called over HTTP. 
  - API endpoint `index.php`, URL structure `?module=API&method=X.Y&format=...`, method names and parameter names are part of the API.
- [Tracking HTTP API](http://developer.piwik.org/api-reference/tracking-api)
  - API endpoint `piwik.php`, parameter names are part of the API.
- HTTP Status code for Reporting and Tracking APIs are API
- [Events](http://developer.piwik.org/api-reference/events) 
  - Event names, and parameter list are API.
- [Classes](http://developer.piwik.org/api-reference/classes) and [Methods](http://developer.piwik.org/api-reference/index) 
  - They are tagged with `@api` in our sourcecode. (these docs are automatically generated on each commit.)
- A few console commands are API (the command name and parameter names should not change)
  - so far we only consider public APIs these commands: `core:archive`, `core:update`, `plugin:activate`, `plugin:deactivate`, `git:pull`, `development:enable`, `development:disable`, `customvariables:set-max-custom-variables`.
  - some of these commands are setup in crontabs and we shouldn't break them.
- JavaScript variables in global `piwik.*` object
  - as [documented here](https://developer.piwik.org/guides/working-with-piwiks-ui#global-variables-defined-by-piwik)
- LESS variables used for Theming 
  - when [writing a theme for Piwik](http://developer.piwik.org/guides/theming) we announce that LESS variables in ([theme.less](https://github.com/piwik/piwik/blob/master/plugins/Morpheus/stylesheets/theme.less) and [theme-advanced.less](https://github.com/piwik/piwik/blob/master/plugins/Morpheus/stylesheets/theme-advanced.less)) are API
- INI Config settings names in `config/global.ini.php` are API
  - we should not rename INI config settings as users may have overridden them in `config/config.ini.php`
- Widgets embed URLs are API
  - thousands of users include Piwik reports directly via [the iframe embed feature](http://piwik.org/docs/embed-piwik-report/) and rely on the URL to work
- Some tools bundled with Piwik are considered API in the sense that their paths should not change:
  - `libs/PiwikTracker/PiwikTracker.php` <- tracker API client directly used from this path (as we advise [in our doc](https://piwik.org/docs/tracking-api/))
  - `misc/log-analytics/import_logs.py` <- [Log Analytics script](http://piwik.org/log-analytics/)
  - `piwik.js` is the minified JavaScript tracking client referenced in Tracking code in users' websites
  - alternatively `/js/` endpoint is sometimes used to serve the minified file ensuring caching of the file in browsers.

Some other parts are sometimes considered public APIs but it is not a hard rule:
- Translation keys, especially generic ones such as `General_*` and `CoreHome_*` keys, are part of the API and should not change. 
  - Many plugins may use these generic translations, as [we advise them to.](http://developer.piwik.org/guides/translations#best-practices-for-new-translation-keys)

Deprecations and changes to any of these public APIs will be documented in the developer changelog #8127

**Comment by mattab** [comment]
fyi: added to the list above

 * JavaScript variables in global `piwik.*` object
  * as [documented here](https://developer.piwik.org/guides/working-with-piwiks-ui#global-variables-defined-by-piwik)
 * A few console commands are API (the command name and parameter names should not change)
  * so far we only consider public APIs these commands: `core:archive`, `core:update`, `plugin:activate`, `plugin:deactivate`, `git:pull`, `development:enable`, `development:disable`, `customvariables:set-max-custom-variables`.
  * some of these commands are setup in crontabs and we shouldn't break them.

**Comment by tsteur** [comment]
Closing this as it has not much value being open and rather is confusing looking at it repeatedly.

**Comment by tsteur** [comment]
this is now documented in https://developer.matomo.org/guides/apis
