### ISSUE TITLE
 Developer Changelog and documenting changes in the Piwik Platform

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#8127]
The goal of this issue is to list all the changes that we aim to document in our Developer Changelog ([/CHANGELOG.md](https://github.com/piwik/piwik/blob/master/CHANGELOG.md)). We need to move this knowledge to a guide in developer.piwik.org so that it's shared across team members, and clear to the developer community.
### Context

Where we are today:
- We create the Piwik platform and offer developers a set of public APIs #8125 
- We maintain backward compatibility for those APIs. 
- When changing or removing public APIs, we must first deprecate code following this process: #8126
- We keep track of all platform changes relevant to developers in our [Developer changelog](http://developer.piwik.org/changelog)
### What to write in developer changelog

As a Piwik product team engineer, we keep the developer changelog up to date by noting any:
- change to a Reporting API method (eg. new API method added, deprecated, removed)
- change to Reporting API output (eg. a new field in an API response)
- change to Reporting API parameter (eg. parameter added, deprecated, removed)
- change to Tracking API parameter (eg. parameter added, deprecated, removed)
- change to Piwik JavaScript Tracker feature (eg. new feature, or removed feature)
- since PHP 8 argument names of public API's are also considered API
- new console command 
- new parameter for a console command
- new developer guide
- update to a third party library  
- any other relevant internal change that may interest developers
### Developer changelog structure

These changes are organised in the developer changelog in the following categories:
- Breaking Changes
- Deprecations
- New features
- New APIs
- New commands
- New guides
- Library updates
- Internal change

(you will find the template at the bottom of `CHANGELOG.md` file)

**Comment by tsteur** [comment]
this is now documented in https://developer.matomo.org/guides/apis
