### ISSUE TITLE
Row Evolution can use too much memory

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#8169]
- [Example URL to reproduce](https://demo.piwik.org/index.php?date=2015-06-22&apiMethod=UserCountry.getCity&label=%40Mumbai%252C%2520Maharashtra%252C%2520India%2C%40Tokyo%252C%2520Tokyo%252C%2520Japan&disableLink=1&module=CoreHome&action=getMultiRowEvolutionPopover&idSite=1&period=month) (requires login to demo)
  - Got: `<b>Fatal error</b>:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 88 bytes) in <b>/home/piwik-demo/www/demo.piwik.org/core/Metrics.php</b> on line <b>196</b><br />`  (I since reverted memory limit to 256M)
  - Expected: report loads fast and does not use more than 256M of memory

**Comment by tsteur** [comment]
> Expected: report loads fast and does not use more than 256M of memory

That's a bit a random requirement. How much does it actually take? Can you increase to 1GB and see if it works and how much it actually uses?

I think it'd be better to check if we can find a memory leak or something but a 512MB memory usage might be valid

**Comment by mattab** [comment]
After changing memory limit to 1024M, the row evolution loads. It took 1 min to load the report which is quite slow.

Suggested requirements:
 * load in less than 15 seconds
 * ideally in less than 512M

**Comment by mattab** [comment]
This only affects the "User cities" report, other Row Evolution reports load very fast

**Comment by xpader** [comment]
It's also very slow in Pages report.
