### ISSUE TITLE
Make some parts of the available translations part of the API

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/matomo#8172]
Followup to #8101, refs #8125

We should make some parts of the translations part of the Piwik API.
Translations that are part of that API should never be changed and rarely be removed.

Part of that API should be all translation keys part of the Intl plugin as well as all keys in a special category that we need to define. We still need to consider which keys/translations should be added here.

We shall also update the developer docs to advice plugin developers, that those API translations can be used safely and that other translations available in Piwik might change in time.
That note should also be added to the translation search within Piwik

**Comment by tsteur** [comment]
:+1: 

Don't have an opinion on the name of the second special category. Which keys are supposed to go into the `Intl` plugin? Only generic ones like dates etc or also analytics specific ones like "visits" and "website"? Maybe we could even just move all that are considered API into `Intl`?

**Comment by sgiehl** [comment]
Currently all translations available in the Intl plugin are extracted from CLDR and autogenerated. They are also NOT included on transifex.
I would not suggest to move any other translations to that plugin, as we would than need to include it on transifex.

**Comment by tsteur** [comment]
Thx for clarification! Maybe it might be worth to add a README to this plugin explaining this?

**Comment by mattab** [comment]
:+1: 

Which plugins translations are part of API, I guess `Intl` translations and also `General`?

@sgiehl maybe we add this as part of  #8125 and close this RFC? (we will close #8125 later after creating a new public developer guide)

**Comment by tsteur** [comment]
I'd prefer to just remove the `RFC` label and add `Enhancement` or so. We need an issue to actually do this unless we're happy with the current translations in `General` and `Intl` @sgiehl ?

**Comment by sgiehl** [comment]
All ```Intl``` translations should be in the API. And I'd suggest to create a new category ```Piwik``` where we move translations we want to have in the API. Need to make some thoughts what we should move, but it should be stuff like metric names, general stuff like 'Yes', 'No', 'Cancel'

I'm not sure if we should do that for 2.15. Maybe 3.0 would be better for moving keys, as it might break translations for third party plugins using them

**Comment by tsteur** [comment]
3.0 sounds good to me as it's not urgent and breaks things.

**Comment by mattab** [comment]
Once it's been decided to make some plugin translations part of the API, please update the list in: https://github.com/piwik/piwik/issues/8125

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
