### ISSUE TITLE
Let me display a "Cookie opt-out" panel in their websites tracked by Piwik 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#8342]
In our effort to  innovate and bring better [Privacy](http://piwik.org/privacy/) to Piwik users worldwide, we would like to provide an easy to use mechanism for Piwik users to show a "Cookie opt-out" panel on their websites. 

By default, when visitors view a website tracked by Piwik, [tracking cookies](https://piwik.org/faq/general/faq_146/) are set on the visitor browser. It is possible for a Piwik admin to specifically [disable all tracking cookies](https://piwik.org/faq/general/faq_157/), but this would apply to all visitors. The goal of this feature is to let each visitor decide whether they want to opt-out from tracking cookies.
#### Suggested product changes
- in Administration > JavaScript tracking code, a Piwik admin could check a box "Display a panel to let visitors opt-out from Tracking Cookies"
- when the box is checked, the JavaScript tracking code would add a new call eg. `_paq.push('enableCookieOptOut', 'This site uses cookies. Some of the cookies we use are essential for parts of the site to operate, and some cookies are used to measure how you use this website.', 'I accept cookies from this site', 'Continue');`
  - parameters are: the main panel text, the checkbox label, and button label 
  - the text would be translatable by Piwik translators (nice!)
  - if user wants to customise the text they can (when copy pasting)
- when this function `enableCookieOptOut` is called, piwik.js would then display a Cookie opt-out panel in the website. 
  - By default, `I accept cookies from this site` is checked (by default, Piwik uses cookie) [x]
  - A visitor can uncheck the box and click `Continue` and then Piwik.js will `disableCookies`
  - the panel could have slightly transparent background (it looks nice)
#### Example

![integration platform as a service](https://cloud.githubusercontent.com/assets/466765/8652584/af8b5170-297f-11e5-9dd9-3145601e7578.png)

(seen on http://elastic.io)

What are your thoughts?

**Comment by braekling** [comment]
It is a great idea to integrate this into Piwik itself. So the users don't have to care about such things.
The feature was requested for WP-Piwik several times already, so there is a demand to cover.

One additional suggestion: The generated panel should use a meaningful & unique css-class, so users can modify the look on their own.

**Comment by mattab** [comment]
Moving to 2.15.1 after talking with @alex-gulentz - would be awesome to build this little feature in Piwik!

Btw: we will be able to offer an easy way to enable by default this feature across all website by adding the function call via [CustomTrackerJs plugin](http://plugins.piwik.org/CustomTrackerJs).

**Comment by mattab** [comment]
How do we let users style the cookie consent box? how can user change background color, font color & style, etc.

**Comment by mattab** [comment]
In the issue above, we specc'ed a version of the cookie consent where the user would be able to directly opt-out of cookies from within the cookie consent panel. But actually, we may not need to go this way, it is a bit more complicated so let's start maybe with the easiest solution.


### Simple spec/MVP

The easiest solution would be to simply inform the user that cookies are used to provide essential functionnality to the website. 

 * The message would contain a link placeholder so the user can replace the placeholder by the URL to their "privacy policy" page or their "opt-out" page. The result is that visitors to the website are informed that cookies are used and possibly (if Piwik admin specified it) they have an opportunity to click on the link to learn more, and opt-out. 
 * The button would say `Accept` or `OK`.  
 * There would be no checkbox `I accept cookies`. 

### Questions

 * how do we let user change background, text-color and style button, text + background?
 * how do we let user easily the position the panel? (ie. top, bottom, maybe even in a custom dom node?)

**Comment by mattab** [comment]
![cooki3](https://cloud.githubusercontent.com/assets/466765/10363047/9489a2cc-6e0e-11e5-9ebd-bf9713861b2c.png)
![Uploading cookie1.png…]()
![Uploading cookie2.png…]()
![Uploading cookie4.png…]()
![Uploading cookie5.png…]()

**Comment by mattab** [comment]
Examples of cookie consent panels on existing websites below

# Panel within the page 

![cookie4](https://cloud.githubusercontent.com/assets/466765/10363064/a9e83bc4-6e0e-11e5-81e5-ee45e1abdf1c.png)

# Bottom

![cooki3](https://cloud.githubusercontent.com/assets/466765/10363062/a9044a2c-6e0e-11e5-84eb-46b4b7d3ce68.png)

![cookie2](https://cloud.githubusercontent.com/assets/466765/10363065/a9ec23b0-6e0e-11e5-97ca-f583e387d856.png)

![cookie1](https://cloud.githubusercontent.com/assets/466765/10363063/a9df0086-6e0e-11e5-9ee5-f08eb0caa6dc.png)

![cookie5](https://cloud.githubusercontent.com/assets/466765/10363066/a9ec722a-6e0e-11e5-9e29-d00559f19b0e.png)

**Comment by Cruiser13** [comment]
I like the way the CMS Pimcore did implement this - with a lot of freedom for the admin in case of wording, styling and so on.

I'd also throw in that a checkbox with the ability to tell that cookies are not accepted is useless for many sites - most sites are dependent on cookies and we'd need a callback from Piwik to tell the site itself not to use cookies (e.g. implementations for Pimcore, MyBB and so on).
For 99% of sites administrated by myself I simply can't drop cookie support. No point in giving the user this option - he eighter accepts cookies or has to leave the site.

**Comment by tsteur** [comment]
Can we maybe ideally not add such new features into LTS version (it'll be a patch release)?

**Comment by mattab** [comment]
@tsteur ideally yes, but it would mean we need to wait 6 months or so before having this feature in a stable Piwik 3.0 release, which is an issue as it is an important feature for German users and market...  The upside is that this feature is "safe" regarding LTS since we add a new feature in piwik.js (that is not enabled/ used by default) and this should not change any core API or affect existing code

**Comment by tsteur** [comment]
OK, feature doesn't really look high value to me as it's often displayed very differently for each site to have it integrated nicely. Will all the translations etc be in `piwik.js`? Also I'm wondering when offering something like this, whether we need to check several laws in various countries etc (which would be impossible)? I think at least in Germany it's not a law yet, but might be soon. Not sure what it then needs to contain etc. When offering something like this to all users we should maybe mention we are not liable if anyone gets fined or a disciplinary warning for not having it done the proper way and that they need to check local law. 

Also wondering if ad blockers are a problem? `piwik.js` is often blocked by ad blockers so it would maybe not be displayed?

**Comment by mattab** [comment]
> Will all the translations etc be in piwik.js?

No, all translations will be set in the Website tracking code, and translations will be stored in the server side. The Javascript Tracking code screen, will have a checkbox to enable the Cookie opt-out panel. User will copy the translations when copying the Js code into their page. 

> Also I'm wondering when offering something like this, whether we need to check several laws in various countries etc (which would be impossible)

No we don't need to: laws are different in each country, as each EU country for example receives the EU directive and can choose to implement it the way they want in local legislation. Just in europe there is wide diversity of implementations of privacy laws. Our goal at PIwik though is to lead the way in terms of privacy. That's why it's important for us to provide this feature and make it super easy for webmasters to inform their users.

> Not sure what it then needs to contain etc.

It's mostly about us deciding what such panel should contain :-) I think it's important to find a message that is very easy to understand and very clear, as it will be ready by all kinds of people including some non technical at all. The text should really be the easiest to understand as possible :+1: 

>  When offering something like this to all users we should maybe mention we are not liable if anyone gets fined or a disciplinary warning for not having it done the proper way and that they need to check local law. 

 it's already clear that we are not liable, but I agree we should add a notice somewhere. it may be enough to mention this in a FAQ or User guide VS in product itself?

> Also wondering if ad blockers are a problem? piwik.js is often blocked by ad blockers so it would maybe not be displayed?

It is fine and acceptable that this feature does not work, when ad blocker is enabled.

**Comment by mattab** [comment]
We wouldn't work on this ticket as is, so closing for now. See #12600 for links to other issues
