### ISSUE TITLE
Piwik self service plugin 

### ISSUE THREAD

**Issue by shahar3012** [matomo-org/matomo#8358]
Hi, 
I'm using Piwik in my organization and we are interested in a self service option in Piwik. 
I think it should be implemented in a plugin that lets all logged in users to add new website to Piwik and grant them the admin permission for this specific site. 

What do you think? 
I don't think it should be take long to develop this feature and it is very necessary. 

Thank you.

**Comment by mattab** [comment]
Hi @shahar3012 

can you explain a bit more what your use case is?

Would you create a user yourself and then you want to let these users add new websites themselves?

**Comment by oparoz** [comment]
I can see this being needed for a web host. Just like you create the main user account and allow the user to add x domains to his account, you could give the customer a Piwik user login and let him add and manage x domains under his account.

**Comment by shahar3012** [comment]
@mattab @oparoz 

I'm using Piwik in a closed network and SSO using Kerberos.
We have lots of sites in the closed network, so Piwik has a "big market" in my organization.

I'd like to let my users add new websites themselves. When a user adds new websites he/she granted with the admin permission instantly (on their website only).

That is the self service, nothing more.
Everything can be done in a couple of days.
Basicly what we need is to create a new page that lets them add the new website. One that is different than the Administration panel.

My use case is to provide Piwik as a self service to my organization.
I will just maintain the servers and operate Piwik.
My users will be able to add new websites themselves.

**Comment by Fensterbank** [comment]
Hi @shahar3012,

so you have clear requirements and a clear deadline (next 2 weeks), but keep in mind that a Github issue is no task list and the users here doesn't offer coding service. ;-)
So if you need this feature so soon, I think you have to write the plugin yourself.

But back to topic:
If you have many websites in your organization, why don't you make another self service website?
If you make a site with managed code (eg. aspx or php), you could use the secred token of an admin user and use it to create sites and set permissions via the API or a Library.

We made such a thing with a small .NET provisioning tool: Create the piwik site, give a reporting user read access to the site, create scheduled PDF reports for the created sites in context of our reporting user.
Not exact your requirements, but technically you can do all what you want with the API.

**Comment by shahar3012** [comment]
@Fensterbank It would be nice to have it in the next 2 weeks, I know how Github works. I just mention it, that it will be taken seriously.

I believe that there should be a plugin that does that, neither other site or other tool.
I can call the related API functions from the plugin with doAsSuperUser() function in a much more secure way than sending my admin token which is practicaly impersonate to another user.
I want to do, just for this specific feature, an action as super user because it's the only way to add new websites.

@mattab @tsteur @diosmosis @mnapoli @sgiehl @JulienMoumne @halfdan I just want to hear from the Piwik team what they think. 
If no one will give it a shot, I will...

**Comment by tsteur** [comment]
I doubt anyone will give a shot on this soonish. I reckon it can be possible to do this in a separate plugin. You can create a new admin page to create new websites, add it to the admin menu and provide a separate API that let's you create a new website with less permissions than `Admin`. 

> @Fensterbank It would be nice to have it in the next 2 weeks, I know how Github works. I just mention it, so it will be taken seriously.

Just FYI: With something like this you rather achieve the opposite of taking this seriously as it is not realistic (unless you consider sponsoring this feature)

**Comment by shahar3012** [comment]
@tsteur I don't agree with you. This plugin can be done in a week top. I will develop it for my own use if no one else will, but I don't have the time right now. 

This plugin should be like,  that even when a user has `noaccess` permission, this option will be available to him / her. 
When the user has no websites, he or she could add new one and they become the admin of this website. 

Same as for mobile application, so it basically a measureable.

**Comment by tsteur** [comment]
> @tsteur I don't agree with you. This plugin can be done in a week top. I will develop it for my own use if no one else will, but I don't have the time right now.

Yes, it can be developed in a week maybe but we won't have the time as well. That's why I meant it is unrealistic. Should have explained it a bit.

>  If you want to provide the best analytics platform, I believe you should consider this suggestion.

We surely do consider this suggestion, we just get so many other suggestions as well and we cannot work on everything. I presume in this case only a very few users would benefit from this feature as it rather a custom requirement so we will most likely focus on features that benefits most users. That's why we often focus on our plugin system / platform so users can build it themselves when they have custom requirements and ideally share the plugin afterwards with other users via http://plugins.piwik.org . Documentation about plugin development is available on http://developer.piwik.org , we have many code generation commands to make it easier to develop a plugin for Piwik.

**Comment by shahar3012** [comment]
I understand.
Please consider adding new features to Piwik, and let other users fix the bugs. If the core team will work most of the time on bugs fixes, than the platform will evolve slowly. Correct me if I'm wrong.

**Comment by halfdan** [comment]
> If the core team will work most of the time on bugs fixes, than the platform will evolve slowly. Correct me if I'm wrong.

How do you get the feeling that the core team is only working on bug fixes? If you look at the changelog (http://piwik.org/changelog/) all recent versions introduced new features AND had bug fixes. Letting other users fix bugs is not only slow it also leaves possible security issues open. We usually let contributors write tests.

**Comment by matunixe** [comment]
Hello there,

Any new about this feature ? That will be really useful to my organisation. 👍

**Comment by pierreozoux** [comment]
@shahar3012 did you end up doing it for your orga?

I'm also interested in such a feature. I don't have much resources, but I can participate in a bounty.

**Comment by shahar3012** [comment]
@pierreozoux I couldn't find the time to develop this feature in last year. I hear it from users from time to time that they would like to have a self service option. 
I believe we can create this plugin together with a little planning ahead so everyone would benefit from this feature.

**Comment by alcalyn** [comment]
Hi, I also needed this feature, so I developed it and just released it on marketplace. It is installed on my Matomo instance for demo and use purposes.

Github: https://github.com/alcalyn/matomo-plugin-signup
Marketplace: https://plugins.matomo.org/Signup
Demo: https://matomo.nsupdate.info/
Tweet about this: https://twitter.com/alcalyn_/status/1119591978776367105

![Screenshot Matomo Signup plugin](https://plugins.matomo.org/Signup/images/0.1.0/1-signup-user.png)

(Also discussed about it here: https://github.com/matomo-org/matomo/issues/7622)

**Comment by Findus23** [comment]
Many thanks @alcalyn, that sounds exactly what was asked for!
