### ISSUE TITLE
Update our Develop guides for Matomo 4.0.0 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#8415]
The goal of this issue is to go over our [Develop guides](http://developer.piwik.org/develop) and update them to match the new APIs in Matomo 4.0.0. See also: https://github.com/matomo-org/matomo/wiki/New-major-releases#developermatomoorg

**Comment by tsteur** [comment]
Just mentioning it so we don't forget to adjust the examples mentioned in https://github.com/matomo-org/matomo/issues/6548#issuecomment-639116673

**Comment by tsteur** [comment]
Also document no  longer supported browsers in tracking cause we removed JSON and how to still support them maybe
