### ISSUE TITLE
Automatically update submodules to latest

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#8425]
Suggestion: we create automation script to automatically commit & push the latest submodules. (Edit 2020: via Github actions?)

Goals:
- prevent manual work in keeping submodules synchronised
- prevent build failures when new plugins were released and submodules not yet updated, (eg. https://github.com/piwik/piwik/commit/c4ca3c55f2892bee56c9e0bbda37530b3e1e4b7d was necessary to have green build)

Requires:
- git-lfs https://github.com/piwik/piwik/issues/7726 
  - or alternatively, we do not automatically update the submodules `tests/UI/expected-ui-screenshots` since it doesn't work for this submodule to automatically keep it up to date

Can you think of any problem with automating sub-modules commit & push to latest?

**Comment by mattab** [comment]
from @diosmosis: let's investigate: http://stackoverflow.com/a/9189815 as it looks interestingly like it may be a core feature of git?

**Comment by tsteur** [comment]
@sgiehl closing this one as done. Let me know if that's not the case
