### ISSUE TITLE
Ampersand (&amp;) when adding/configuring Website and using & in URL textinput

### ISSUE THREAD

**Issue by piwikfan** [matomo-org/matomo#8496]
I just found out about this bug. Don't know it it was present in a previous release of piwik. Currently I'm using the latest version 2.14.2

When adding a new site or configuring one and entering an URL with and and symbol (&) the resulting db entry for this site will be `&amp;` although it just should be `&`.
Using the small picture link in the "All Websites" Dashboard will then redirect (in my case) to the wrong url. 
Step 1: I create a new website entry in piwik
Step 2: In the textfield titled "URLs" I enter http://www.demosite.com/?var1=1&var2=2 and then i press the save button.
Step 3: On the top right side I click on "All Websites"
Step 4: in the following view I navigate to the entry Demosite an right next to the title there is a small icon which will lead me to the URL I typed in in step 2. But instead of reaching the correct site. Instead of http://www.demosite.com/?var1=1&var2=2 I will be forwarded to http://www.demosite.com/?var1=1&amp;var2=2

Please see my attachment for more information.

I can manually alter the database entry and remove amp; and everything works. But everytime I change some setting for this site I have to remember to manually remove "amp;" or if a colleague of mine changes something while I'm on vaccation finding this bug on his own can be pretty time consuming. 

![piwik](https://cloud.githubusercontent.com/assets/13668270/9099944/e3ab66e4-3bd5-11e5-8ea8-4b93c6636615.png)

**Comment by sgiehl** [comment]
The problem with the encoded url being displayed in thetooltip on all websites dashboard seems meanwhile fixed. Everything else might be handled with #4231 if needed.
