### ISSUE TITLE
Privacy Settings: Do not send token_auth via GET and POST

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#8497]
See eg https://github.com/piwik/piwik/pull/8002#discussion-diff-31667646L11 , https://github.com/piwik/piwik/pull/8002#discussion-diff-31667834R29 , https://github.com/piwik/piwik/pull/8002#discussion-diff-31667901R98 , ... 

It shouldn't be sent as GET as the token could appear in server logs

**Comment by Joey3000** [comment]
See also https://github.com/piwik/piwik/issues/7349 :)

**Comment by Findus23** [comment]
closing in favour of #7349
