### ISSUE TITLE
Make the Mission and Values more visible (a top page?) at matomo.org

### ISSUE THREAD

**Issue by MagicFab** [matomo-org/matomo#8513]
During the Berlin community meetup (2015) preparation sessions, mission and values were updated:
- https://github.com/piwik/piwik/wiki/Our-mission-and-values
- https://github.com/piwik/piwik/wiki/Our-mission-and-values/_compare/446bd8220e700620631ed65b4ac866232a364c12...3cd30bd7b30dc03175851c446d2096da2108cc6e
- http://piwik.org/roadmap/

This was also presented at the community meetup.

Among other feedback I brought up making this information more visible. One way would be to have a top page at Piwik.org for MIssion and Values, also linked from the left menu under "About".

**Comment by mattab** [comment]
Thanks @MagicFab for the suggestion, we're also discussing 
our updated Piwik Mission statement and values in the RFC in #8518

**Comment by mattab** [comment]
Hi @MagicFab - we published a while ago an updated About page which has the mission and the values listed: @ https://matomo.org/about/ Let me know if you have any feedback :ok_hand:

**Comment by MagicFab** [comment]
I am not sure the "About" page addresses any of the initial request in this report. It it mixes the Matomo project story and its values and vision - and still lacks a clear mission statement despite the wiki page having one. The "Matomo Values" subsection should be at the top, clearly connected to the mission statement.

The "Vision" seems buried at the end and has an important English mistake. I believe "..but we will and always will be the #1 free open source web analytics platform in the world." was meant to be "but we **are** and always will be the #1 free open source web analytics platform in the world."

Declaring it's the best project out there and will continue to be seems a bit too certain or arrogant, certainly without facts or numbers to back and perhaps not appropriate for a vision statement. Isn't everyone's vision to be the best ? The wording on the wiki seems more in line with core values. I am also thinking "To create the leading..." was appropriate 4-5 years ago but today Matomo is way past its creation phase. I am not sure how to rewrite this.

**Comment by tsteur** [comment]
Cheers @MagicFab very much appreciated and good points 👍

**Comment by mattab** [comment]
Hi @MagicFab Thank you again for your feedback! 
The mission is now displayed in the About page, let us know if any more feedback :+1: 
https://matomo.org/about/
