### ISSUE TITLE
Updating Piwik Mission statement and values

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#8518]
Our mission statement, which drives everything we do at Piwik, has been slightly updated! It was not changed for the last 7 years.
#### Previous mission statement

> “To create, as a community, the leading international open source web analytics platform, that gives every user full control of their data.”
### Our new updated mission

>  “To create the leading Free and open source analytics platform, and to support global organisations and communities to keep full control over their data.”
## Changes
- replaced  `the leading international open source web analytics platform` by `the leading Free and open source analytics platform`
  - why? we wanted to mention Free(dom) in the mission to make it "clear" Piwik is free/libre software / Copyleft. this will never change and was not represented before in the mission 
  - Free with a capital `F` stands for `Freedom`. This is not clear to everyone... MariaDB uses `Free` in their mission too: `MariaDB strives to be the logical choice for database professionals looking for a robust, scalable, and reliable SQL server. To accomplish this, the MariaDB Foundation work closely and cooperatively with the larger community of users and developers in the true spirit of Free and open source software, and release software in a manner that balances predictability with reliability.`
- replaced `that gives every user full control of their data.` by `to support global organisations and communities to keep full control over their data.`
- removed `as a community` - Piwik is by design and since the beginning a project built by community members from diverse origins and backgrounds, with varied missions and goals, and no longer only "community"  members as defined by the original context.
## Previous values
1. Alternative to Google Analytics and Universal Analytics
2. Open Platform
3. No data limit
4. Privacy
5. Reliability
6. Security
7. Usability
8. Freedom
9. Engineered to last

(some of these are not real values, therefore we wanted to create an updated set of our values)
## Our new updated values
1. Openness
2. Freedom
3. Transparency
4. Data ownership
5. Privacy
6. Kaizen (改善): continuous improvement 
## Communicating mission and values publicly

Let's update our mission and values in:
- [Roadmap page](https://piwik.org/roadmap/) 
- [README.MD](https://github.com/piwik/piwik/blob/master/README.md)
- [FAQ: ](https://piwik.org/faq/new-to-piwik/faq_174/)
- wiki page [Our mission and values](https://github.com/piwik/piwik/wiki/Our-mission-and-values)

Do you have any feedback?

**Comment by tsteur** [comment]
> “To create the leading Free and open source analytics platform, and to support global organisations and communities to keep full control over their data.”

A big difference that I see here is that the part "as a community" was removed. Maybe a few words on the background would be nice and how this will "affect" the project? Or to ask differently: As a user or contributor which changes can we expect because of that? 

Values: 

Are they applied to the product "Piwik" or are they supposed to be valid for the community / contributors / project as well? It's hard to tell since the "As a community" part was removed and would be nice to know. 

For values for community/project it would be nice to have a value like we "Respect" each other and we reflect this in the way we communicate with each other etc.

**Comment by tsteur** [comment]
> replaced `that gives every user full control of their data`. by `to support global organisations and communities to keep full control over their data`.

A few words on the background of this could be nice? I kinda liked that global organisations and communities were grouped together as one "user" before. As it addresses and can be applied to everyone, as a single entity, like a community.

**Comment by BeezyT** [comment]
I agree with Thomas that the community is at the core of Piwik and it would be good if that were reflected in the mission statement.

Regarding supporting organisations: Has that really become the mission of Piwik? Isn't that the mission of Piwik PRO?

**Comment by Cruiser13** [comment]
I liked the "that gives every user full control of their data" part because it did reflect the data privacy settings for the visitors of sites too. It's a major difference to other analytics software for me.

**Comment by aidanamavi** [comment]
I really like the changes. I'd offer just a few things for consideration.

> Are they applied to the product "Piwik" or are they supposed to be valid for the community / contributors / project as well?

This is a good point that could use clarification. FWIW, I interpret "Our Values" as the values of the community. However, for further clarification, we could say "Community and Piwik Value," or something of the sort.

> For values for community/project it would be nice to have a value like we "Respect" each other and we reflect this in the way we communicate with each other etc.

I agree and would add that with the community representing people from a wide variety of cultures, misunderstandings and conflicts can arise. It would also be great to consider a community conduct guide for communicating.

**Comment by mattab** [comment]
> Are they applied to the product "Piwik" or are they supposed to be valid for the community / contributors / project as well? 

They are applied to the product Piwik as well as in general the project which includes the platform, marketplace, forums, our public communications, social media, and more. Contributors from community should ideally know about our values and our role is also to better communicating these to everyone.

> For values for community/project it would be nice to have a value like we "Respect" each other and we reflect this in the way we communicate with each other etc.

This sounds like a "Code of conduct" which is slightly different, but definitely useful to have as we are growing :-) recently came across the [Jquery code of conduct](https://jquery.org/conduct/) which seems excellent. (also check the [code of conduct faq](https://jquery.org/conduct/faq/)). Maybe something we should do as well? (if so, we should create a new issue to be followed up).

**Comment by mattab** [comment]
>  I kinda liked that global organisations and communities were grouped together as one "user" before. As it addresses and can be applied to everyone, as a single entity, like a community. I also like the term "user" as it reminds me that there are actual people using Piwik and we want to support them.

> I liked the "that gives every user full control of their data" part because it did reflect the data privacy settings for the visitors of sites too. It's a major difference to other analytics software for me.

@tsteur @Cruiser13 Maybe we could slightly alter the mission statement to mention "user" (maybe "individuals"?), proposal:

> “To create the leading Free and open source analytics platform and to support global organisations, communities and individuals to keep full control over their data.”

**Comment by mattab** [comment]
> Regarding supporting organisations: Has that really become the mission of Piwik? Isn't that the mission of Piwik PRO?

No, it is the mission of Piwik to support everyone to liberate their data (organisations/businesses, communities, individuals, without distinction). Piwik PRO helps very much in making this mission more successful (eg. by hiring engineers to work on open Piwik platform). But only a small percent of all organisations using Piwik (and liberating their data!) will work with Piwik PRO.

**Comment by mattab** [comment]
> If "community" is built-in in Piwik as it was mentioned in the issue description I think it would be good to leave it in the mission statement. Also to make sure it won't be forgotten in the future etc.


+

> I agree with Thomas that the community is at the core of Piwik and it would be good if that were reflected in the mission statement.

@tsteur @BeezyT agreed that it was nice to have "as a community" in the mission. but i don't think it must be in the mission for the reason to remind people how the project works. we should find other ways to make it clear to everyone that we build this project as a community. For example the fact that our values include **Openness, Freedom, Transparency** commits us to being open, transparent with the users. Freedom because our GPL license ensures freedom and ability for community to take (or fork) if there was ever an issue. But in my opinion, the fact that we have worked for last 7 years as a community shows we are serious about keeping building Piwik in this way. I know there are risks and fears that an open source project could stop being community-driven, but rather than add "as a community" in our mission, I would really love to think of the other ways we can improve the running of the project to ensure this success long term. I have few ideas, but one step at a time, and keen to hear suggestions and ideas!

**Comment by tsteur** [comment]
:+1: for Code of conduct

What is the problem with "as a community"? That's something I don't really understand yet. You mention we should find other ways to make it clear to everyone but not sure why we should find other ways?

>  For example the fact that our values include Openness, Freedom, Transparency commits us to being open, transparent with the users. 

We have these kinda values because of our mission statement and because of "as a community". The values and the license derive from this mission statement "as a community", it's not the other way around. Do you know what I mean? 

> But in my opinion, the fact that we have worked for last 7 years as a community shows we are serious about keeping building Piwik in this way

Also here I don't see a problem highlighting this in the mission statement as it's like one of our mission to do this as a community. I think it's quite important to mention it as it makes clear to everyone how important it is to us to achieve this mission as a community. It's also inviting every one to contribute in any way and if it's just by spreading the word about Piwik.

**Comment by mattab** [comment]
> What is the problem with "as a community"? That's something I don't really understand yet. 

There is no problem with it. If we wanted to leave it in this would make our mission statement:

> “To create, as a community, the leading Free and open source analytics platform and to support global organisations and individuals to keep full control over their data.”

What do you think?

**Comment by tsteur** [comment]
Don't wanna insist on it, not sure what others think. Just trying to understand why we should remove it as I find it important to have it, personally. 

> "global organisations and individuals" 

"and to support everyone to keep full control over their data" something like this would be shorter and address even visitors etc but I can see why it's in there and might be useful. Piwik itself is not ready yet for global organisations, so here we should work on some things mid term (that's what the mission statement is there for I reckon). Eg the user management is not friendly for global organisations (not nice to manage many users / sites and there are also no groups / no ACL). There is a free plugin for User Groups by Piwik PRO (not 100% sure what it does) but should move it into Piwik core at some point as it will be needed to achieve the mission. Just wanna mention that having this in the mission statement will also affect which kinda plugins go into Piwik core (more global organisation related plugins will go in there) vs Marketplace vs Piwik Pro I think

**Comment by MagicFab** [comment]
@tsteur "global organisations and individuals" communicates the diversity in size + origin of Piwik users. "everyone" may not be as clear, in that sense I prefer the first phrase.

It would also be important to make sure the mission statement + values are linked somewhere from the main site, I directed a friend to it and he wasn't able to find (neither was I, later).

**Comment by mattab** [comment]
>  Piwik itself is not ready yet for global organisations, so here we should work on some things mid term (that's what the mission statement is there for I reckon).

Discussed in new issue: https://github.com/piwik/piwik/issues/8920 "Building the best Enterprise Analytics Platform"

**Comment by mattab** [comment]
> This sounds like a "Code of conduct" which is slightly different, but definitely useful to have as we are growing :-) recently came across the [Jquery code of conduct](https://jquery.org/conduct/) which seems excellent. (also check the [code of conduct faq](https://jquery.org/conduct/faq/)). There is also https://github.com/todogroup/opencodeofconduct. Maybe something we should do as well? (if so, we should create a new issue to be followed up).

Created issue:  Code of Conduct for Piwik Community #9154

**Comment by mattab** [comment]
Thanks everyone who contributed, as I see this issue is still opened, I'll close it now. 

We've been using this mission statement in recent years and don't plan yet to update it:

### « To create, as a community, the leading international open source digital analytics platform, that gives every user full control of their data. »

**Comment by mattab** [comment]
Couple additional notes:

* re-reading the original issue description, we have actually kept (and reverted-back) to the so-called "Previous mission statement". 
* this mission is so far mentioned only in the About page: https://matomo.org/about/ and a bit hidden (also in the Github wiki https://github.com/matomo-org/matomo/wiki/Our-mission-and-values). Eventually we might want to create a Mission (and Values) page on the website (or even a FAQ) - see discussion in https://github.com/matomo-org/matomo/issues/8513
