### ISSUE TITLE
RFE: Add boolean "greater than" "less than" conditions for values in segment builder

### ISSUE THREAD

**Issue by MagicFab** [matomo-org/matomo#8527]
I would be useful to add  "greater than" "less than" conditions to the segment builder for numeric values, including dates.

The existing date picker + default user settings are OK for reporting but having boolean conditions for such values would make it possible to set more precise segmenting.

**Comment by hpvd** [comment]
should be related to
Numeric value segments: new "Less than" and "more than" conditions #5372
https://github.com/piwik/piwik/issues/5372

**Comment by mattab** [comment]
Thanks for your patience with this issue. We believe this has been resolved in the recent updates of Matomo. To ensure you have the fix, please [update](https://matomo.org/docs/update/) to the latest version of Matomo.  If the issue persists after the update, don't hesitate to reopen this issue and let us know. Cheers!
