### ISSUE TITLE
Convert goals form to angular w/ focus on allowing plugins to extend logic

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/matomo#8554]
As title. The form should use angular and it should be possible for plugins to add sections to the form and execute their own code on goal create/save.

There does not have to be an explicit way in the goals form to allow this. Since the DOM is so flexible, most of this is already possible, it's just not very clean or some events are aborted before events for other plugins can be executed.

**Comment by mattab** [comment]
it would be nice to have a consistent mechanism for plugin developers to extend any "Entity form" in Piwik, see also: #6951

**Comment by mattab** [comment]
@tsteur was this feature maybe done already?
