### ISSUE TITLE
Research if we can let plugins use Composer libraries

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#8568]
Letting plugin developers use composer to define dependencies will be a huge benefit!

Notes:
- One challenge for example would be, if two plugins use the same composer library (eg. Yaml parser) but use different versions. How do we make this work?
- How to make it work when Piwik instance does not have access to Internet?
- How to make it work with different Piwik versions, different PHP versions?

**Comment by mnapoli** [comment]
FYI see links and comments below: https://github.com/piwik/piwik/issues/4485#issuecomment-72143982
