### ISSUE TITLE
IPv6 Geolocation is not working

### ISSUE THREAD

**Issue by sebastianw** [matomo-org/matomo#8601]
Hello,

it seems Geolocation is not working at the moment for IPv6 addreses. I tried the PHP and PECL backends and none could locate IPv6 addresses. Also I tried to look trough older issues regarding this but I'm confused about the current status. Is this supposed to work?

**Comment by tsteur** [comment]
I think PECL doesn't support it yet see #6624  but PHP should work. I think it was added in https://github.com/piwik/piwik/pull/6690  What exactly does not work for you? In the other issue (#6690) there's some discussion about IPv6 not detecting the location correctly. Is this what you mean?

**Comment by sebastianw** [comment]
Yes, I have a lot of IPv6 locations that just show up as unkown. When I look at the source I don't think that the GeoLiteCityv6.dat is even loaded.

**Comment by mattab** [comment]
> Yes, I have a lot of IPv6 locations that just show up as unkown.

Do all IPv6 show as unknown, or only "a lot" of them? if some are being geo located then it's working from the Piwik side, and likely the IPv6 not geo located are because the geo location database is still not precise for ipv6 addresses. Could you send some example IPv6 not geo located and some that are?

**Comment by sebastianw** [comment]
No, just "a lot" of them. My work IP address shows up unknown, take 2001:780:53d2::1 for example. Some addresses that are successfully geo-located are for Deutsche Telekom addresses.

**Comment by mattab** [comment]
@sebastianw Could you paste a few examples of IPv6 addresses that don't geo locate?

and a few examples that do geolocate OK?

Thanks!

**Comment by mattab** [comment]
eg. for `2001:780:53d2::1`
 * located as Germany: http://www.tcpiputils.com/browse/ipv6-address/2001:780:53d2::1
 * Piwik (via Maxmind) detects it as US: http://demo.piwik.org/index.php?module=API&method=UserCountry.getLocationFromIP&ip=2001:780:53d2::1&format=xml

**Comment by sebastianw** [comment]
but is that coming from the ipv6 file or is it somehow using the IPv4 file for that? because I didn't see any attempt to access the ipv6 database

**Comment by Angristan** [comment]
tets

**Comment by mattab** [comment]
Hi @Angristan -  no news yet, and we likely won't be working on this feature for a while. We would welcome a pull request for this nice feature!

**Comment by grzchr15** [comment]
http://www.tcpiputils.com/browse/ipv6-address/2001:9d0:10::1 shows correct IP address	2001:9d0:10::1
Location	Austria (AT) flag ASN number	8387
ASN name (ISP)	T-Systems Austria GesmbH

http://demo.piwik.org/index.php?module=API&method=UserCountry.getLocationFromIP&ip=2001:9d0:10::1&format=xml
Shows incorrect
<country_code>US</country_code><region_code>NJ</region_code><city_name>Middletown</city_name><area_code>732</area_code><lat>40.397</lat><long>-74.108</long><postal_code>07748</postal_code><isp>AT&T Wireless</isp><org>AT&T Wireless</org><continent_code>amn</continent_code><continent_name>Nordamerika</continent_name><country_name>Vereinigte Staaten</country_name><region_name>New Jersey</region_name><ip>2001:9d0:10::1</ip>

**Comment by mattab** [comment]
We need help to make this one work. Pull request very welcome

**Comment by grzchr15** [comment]
I still struggle how to help implement it. I have a intranet list of ranges and the maxmind dbs. I think in v3.x i need to create a locationprovider. Any more hints where i need to hook , change db schema?, .. docs.
And how to debug the new parts and not complete piwik flows

**Comment by mattab** [comment]
our developer docs are here: http://developer.piwik.org/ 
There's some work being done in GeoIP2 see: https://plugins.piwik.org/GeoIP2/ #4487

**Comment by mattab** [comment]
update: we are planning to implement the new Geoip2 support soon, which should also bring support for Ipv6 geo-location.

**Comment by sgiehl** [comment]
Note: GeoIP2 will fully support IPv6 geolocating. 
But we won't fix geolocation IPv6 addresses with GeoIP Legacy (PECL)

**Comment by mattab** [comment]
Will be fixed in #4487
