### ISSUE TITLE
Sending email via gmail SMTP requires to "Allow less secure apps: YES" -> is solution to use PHPMailer?

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#8613]
This issue is about improving this FAQ: [ How do I send Piwik emails using Gmail SMTP server?](https://piwik.org/faq/how-to/faq_93/)

While setting it up today, I noticed that i was getting an error when sending a scheduled report 

```
An error occured while sending 'HTML Email Report - 2.2015-08-20.101.en.html' to xxxxxxxxxxxxxxx@gmail.com. Error was '5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbucv 5.7.14 -v6FnaqYk_3-5- 5.7.14 UQGVqm7Gvg1qMTL70m9YF2_kcoVxK-eN_d9aPG5hrzzCtiG 5.7.14 5edES-qhoae2YHyGn3bqFQnBQ 5.7.14 8BFlMxvMs_RBCEP62jWESOR-fuYk> Please log in via your web browser and 5.7.14 then try again. 5.7.14 Learn more at 5.7.14 https://support.google.com/mail/answer/78754 cd16sm31949626wib.19 - gsmtp'#0 [internal function]

```

To resolve this issue I had to go to:
- https://myaccount.google.com/security?pli=1#connectedapps
- then click `Allow less secure app` to `YES`

![allow less secure apps](https://cloud.githubusercontent.com/assets/466765/9394221/98f8522a-4787-11e5-8c3f-850d2b8c0bbb.png)

Steps
- what does it mean to be less secure app? could we change our FAQ instructions and/or implementation so that users do not need to do this extra step?
- if not possible, we should at least document in FAQ that user also need to change the setting on their google security account

**Comment by tsteur** [comment]
I didn't have to do this I think. Did you use `ssl` and port `465`?

**Comment by mattab** [comment]
> Did you use ssl and port 465?

yes, strange you didn't have to do this. I should try with another gmail account if I can reproduce

**Comment by MagicFab** [comment]
Some more context:
http://security.stackexchange.com/questions/66025/what-are-the-dangers-of-allowing-less-secure-apps-to-access-my-google-account

To avoid this in the future and properly support using Google's SMTP, perhaps Piwik could implement OAuth 2: https://developers.google.com/gmail/oauth_overview?hl=en

**Comment by MagicFab** [comment]
The FAQ could link to:

Original announcement:
http://googleonlinesecurity.blogspot.co.uk/2014/04/new-security-measures-will-affect-older.html

Steps to enable "less-secure" apps:
https://support.google.com/accounts/answer/6010255?hl=en

**Comment by mattab** [comment]
If anyone else experiences this, please leave a comment!

**Comment by eantoranz** [comment]
I'm running tests to send my first set of patches and I had to enable "less secure apps access" to be able to send the patches with git-send-mail through gmail (to my personal account, just testing, as I said).

**Comment by telx85** [comment]
G'day guys,

Old thread, but still an open issue, so I figured I would respond and keep it alive.

At least for me this is still an issue. Would love to be able to keep the security on my GAPPS account, rather then use less secure setting.

I've tested port 465 SSL and 587 TLS, to smtp.gmail.com using Login. But no joy.

**Comment by tsteur** [comment]
I had a look and https://github.com/PHPMailer/PHPMailer would solve this issue. We could use it from Piwik 3 as it requires PHP 5.4 to use it. Here is explanation. Could be actually quite easy to implement and to switch to this library . More infos https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2

**Comment by telx85** [comment]
That would be a great addition to Piwik from my perspective.
Top job guys!

**Comment by federicosan** [comment]
So what was the solution to this?

**Comment by MagicFab** [comment]
This issue was originally about improving the FAQ which has been done. A new issue about implementing GMail's oAuth should be opened by anyone interested in this. Link to https://github.com/matomo-org/matomo/issues/8613#issuecomment-241128700 would be useful there.

**Comment by nageswararao-nyros** [comment]
Hello Every One,,,,,
I am new to Rails, i have been trying sending mails using Action Mailer But not not sending and also no errors showing in my terminal, can any one help me for this issue. The terminal output is texted below......Thank you all...
  Rendering new_user_mailer/notify_user.html.erb within layouts/mailer
  Rendered new_user_mailer/notify_user.html.erb within layouts/mailer (0.4ms)
NewUserMailer#notify_user: processed outbound mail in 609.0ms
Sent mail to nageswararao.nyros@gmail.com (57.2ms)
Date: Wed, 02 Jan 2019 08:19:38 +0530
From: nageswararao@gmail.com
To: nageswararao@gmail.com
Message-ID: <5c2c26c27d485_10702b11cf896320510bb@nyros.mail>
Subject: welcome
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    Hello User Thankyou for Signup, We will provide our level best
  </body>
</html>

Redirected to http://localhost:3000/articles/147
Completed 200 OK in 885ms (ActiveRecord: 40.2ms)


But not sending,,,,,I am eagerly waiting for your replys....plz

**Comment by beingnikhilesh** [comment]
Thanks... Saved me a lot of Time

**Comment by linehammer** [comment]
[Less secure apps](http://net-informations.com/q/mis/secure.html) can make your account more vulnerable, Google will automatically turn this setting off if it's not being used. However, bypass this security setting with a configuration tweak within your Google Email Account .

How "more secure apps" help to protect your account?

    Which level of access you're giving the client before you connect your Account.
    Client access only a relevant part of your Account, like your email or calendar.
    Connect your Google Account to the client without exposing your password.
    Disconnect your Google Account from the client at any time.

**Comment by robertq12** [comment]
Initially I was facing similar issues associated with gmail while setting up POP3 and SMTP, however after successful login to gmail, I was unable to send and receive emails, the issue is happening probably due to [gmail error 007](
https://www.internettablettalk.com/how-to-fix-gmail-error-007-solved/)

**Comment by mattab** [comment]
Documented in  [How do I send Matomo emails using SMTP server?](https://matomo.org/faq/how-to/faq_93/) or https://matomo.org/faq/troubleshooting/faq_34856/
