### ISSUE TITLE
Check if System Check requirements are still correct and update them

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#8700]
See UI test screenshot of system check:

![installation_system_check](https://cloud.githubusercontent.com/assets/273120/9636662/ebead3da-519c-11e5-8c48-0f9e6fd139d6.png)

I'm currently trying to get PHP7 working but get many different errors and have to recompile PHP 7 all the time. Getting these error messages in an already installed Piwik:

![screenshot at sep 02 17-46-22](https://cloud.githubusercontent.com/assets/273120/9636672/ff3058de-519c-11e5-9a05-30f7b1be4fb5.png)

after compiling with `--with-json` I get
![screenshot at sep 02 17-53-32](https://cloud.githubusercontent.com/assets/273120/9636673/ff430006-519c-11e5-8fc3-188aee531c38.png)

after compiling with `--with-json --with-hash` I get
![screenshot at sep 02 18-00-18](https://cloud.githubusercontent.com/assets/273120/9636674/ff432888-519c-11e5-88a0-db8a1f5cd019.png)

![image](https://cloud.githubusercontent.com/assets/273120/9636814/ceb32474-519d-11e5-8e85-9af8906de1d4.png)

etc. 

Eg in above screenshot it says JSON extension is optional but it is not (actually it is listed in required and optional). One is getting an error if it is not installed. 

Maybe we can also make the error messages a bit nicer and eg say "you have to compile Piwik with `--with-json | --with-hash | --with-pdo`" etc. ?

Maybe we can also recommend in a FAQ which flags are needed (haven't checked if there is already such a FAQ)?

Maybe we could have a link to a system check on all error pages to see what is missing? This system check should ideally work standalone to not fail when json extension etc is missing (maybe we can avoid loading plugins etc). 

After installing all the extensions and being able to open the reports page I wanted to go to the system check but when trying to open the system check page I get this error:

![image](https://cloud.githubusercontent.com/assets/273120/9637701/8eb7629a-51a2-11e5-886f-27e5883d4ec3.png)

Just wanted to create an issue about what I experienced here. We can close it without doing anything if it's not worth spending time on it.

**Comment by mattab** [comment]
> Maybe we can also make the error messages a bit nicer and eg say "you have to compile Piwik with --with-json | --with-hash | --with-pdo" etc. ?

:+1: 

> Maybe we can also recommend in a FAQ which flags are needed (haven't checked if there is already such a FAQ)?

We do have a "Recommended Configuration" section in the [Requirements user guide](https://piwik.org/docs/requirements/) - maybe this could be added there (let me know the command line and I can add it)

>  We can close it without doing anything if it's not worth spending time on it.

 I think it's very important to make this part smooth, I see following (low effort) action items:

 * the system check should be self explanatory and helps users in case anything is mis-configured.  +1 to improve error messages when possible 
 *  curious to undestand why Piwik could be installed without `json` (it's marked as required), 
 *  we likely  need to add `hash` to the list of required extensions,
 * +1 to display a link to a system check on all error pages to see what is missing

**Comment by tsteur** [comment]
FYI: In case it was not clear. I had an existing installation of Piwik and updated my PHP version. It took me quite a long time to get everything working and after some parts of the UI were working I discovered more parts that weren't working including the system check did not work even though other parts of UI were working. I think this can be quite a common scenario, especially now that maybe more will upgrade to newer PHP versions for Piwik 3.0.

**Comment by MagicFab** [comment]
@tsteur could the System check have a fallback UI that won't fail in such cases?

**Comment by tsteur** [comment]
Yes, that would be really great. We kinda need to test the system check with no additional extension installed.

Just also noticed `filter` extension is required too and not mentioned in the check I think

**Comment by mattab** [comment]
Thank you for the report :+1:  To likely fix the issue, could you upgrade to the latest Matomo version?
see https://matomo.org/docs/update/ 

if you still experience this issue afterwards, please re-open this and post a comment. Thanks!
