### ISSUE TITLE
Update FAQ entries related to Piwik LTS support/new lifecycles

### ISSUE THREAD

**Issue by MagicFab** [matomo-org/matomo#8701]
To be updated: 
- http://piwik.org/faq/new-to-piwik/#faq_18925
- http://piwik.org/faq/new-to-piwik/faq_18926/

There may be others, I just came across those two.

**Comment by mattab** [comment]
Thanks for the feedback @MagicFab 
Published in https://matomo.org/blog/2016/01/announcing-long-term-support-in-matomo-the-analytics-platform-for-your-mission-critical-projects/

Quickly mentioned in https://matomo.org/faq/new-to-piwik/faq_18925/ as well
