### ISSUE TITLE
Visitor Log with returning Visitor don't show full details

### ISSUE THREAD

**Issue by Flux3PO** [matomo-org/matomo#8733]
Hi,

Looking at the Live Log on the Dashboard, I got this returning visitor

![Image](http://s12.postimg.org/ze8s531nx/PW_livelog.png)

Exact the Same Information on the Visitors Log.

![User-Log](http://s27.postimg.org/qdqmvagwj/PW_User_Log.png)

If I add a Filter on the User Log to only show me returning visitors

![User-Log-filter](http://s17.postimg.org/xb8vna0xb/PW_returning.png)

The returning Visitor Profile does not show all Visits.

![returning-wrong](http://s3.postimg.org/48ba5hm6r/PW_returning_wrong.png)

**Comment by mattab** [comment]
> The returning Visitor Profile does not show all Visits.


@Flux3PO on your screenshot, the Visitor Profile only shows one visit (before you apply the segment it shows two visits). therefore it looks like it is working as expected?

**Comment by Flux3PO** [comment]
@mattab Hi, I don't think so.
I got an returning visitor with an unique Id. When I open his Profile, shouldn't I see the whole history rather then one Visit ?
I applied the Filter (or segment?) to the visitor list to show me all returning visitor, I did not expect to filter anything inside the returning visitors profile page.
But I can confirm this logic is consistent even thought it's not what makes sense to me. I want to filter on returning visitors, and I want to see all of there visits, I don't see a valid reason why the first visit is chopped off.

**Comment by mattab** [comment]
Thanks for the report @Flux3PO It's now clear that there is a little issue:

 * Opening Visitor Log with a segment applied, 
 * Clicking on "View Visitor Profile" link,
 * Expected: get the full Visitor Profile,
 * Got instead:  Visitor Profile has segment applied, which may remove some information (eg. when we are filtering for "Returning visit" the puser profile](http://piwik.org/docs/user-profile/) only display returning visits)
 
If we fix this, ideally the following feature would still work:
 * When opening the Visitor Profile, when the Visitor Log was segmented, clicking on "Next User / Previous User" should load the next/previous user from the pool of visits within the segment. (currently this works fine, which is useful to browse all users having a particular criteria)

**Comment by Flux3PO** [comment]
Thanks @mattab , it's hard to describe it in an easy way ;)

An Idea: Maybe it's just about wording (also I'm using the German version so there might be a glitch in the Translation?). Currently it says:
"Type of Visitor" = "Returning", but in fact it's:
"Type of Visit" = "Returning". 
This would make sense in the way it currently works.

However, I still want to have a Filter on the Visitors log to better analyze returning visitors fully.

**Comment by mattab** [comment]
Thx for feedback, committed the change in translation in https://github.com/piwik/piwik/commit/54b24968f51ac3dd4a97a317092ff0b194d7703c - and you can contribute to the German translation easily via our Transifex project: http://translations.piwik.org/

**Comment by mattab** [comment]
Hi @Flux3PO 
This issue should have been fixed a year ago or so, please check and re-open if you still experience any issue. Thanks!
