### ISSUE TITLE
Update Piwik upcoming requirements statement taking into account LTS/post-LTS software req's

### ISSUE THREAD

**Issue by MagicFab** [matomo-org/matomo#8742]
Related: #8156, #8701

[Piwik requirements](http://piwik.org/docs/requirements/) should be updated to clearly indicate which software versions will remain supported / which will be required once Piwik 3 comes out and Piwik 2.x acquires LTS status.

**Comment by mattab** [comment]
Thanks for the feedback @MagicFab 
Published in https://matomo.org/blog/2016/01/announcing-long-term-support-in-matomo-the-analytics-platform-for-your-mission-critical-projects/

Quickly mentioned in https://matomo.org/faq/new-to-piwik/faq_18925/ as well

**Comment by MagicFab** [comment]
Merci, Matt + team - glad to see LTS is still a thing !

However, its mention is still missing from the requirements link this aimed for initially. Most importantly, there isn't any mention of LTS support at the main download/install page new users are directed to when first visiting matomo.org :

https://matomo.org/docs/installation/

I suppose more advocacy for LTS awareness is in order and would help but more direct internal links to LTS information from top pages is what this was initially about.
