### ISSUE TITLE
Live.getLastVisitsDetails & RSS format

### ISSUE THREAD

**Issue by NicolasBonduel** [matomo-org/matomo#8786]
Hello,

Like I said there: https://github.com/piwik/piwik/issues/8784, the RSS feed on the method Live.getLastVisitsDetails doesn't seem to work, or the printed error isn't the right one.
(Also the example for this method and the RSS format in the API page of my dashboard is broken because the dateformat is not supported by strtotime)

Have a nice day,
Nicolas

**Comment by mattab** [comment]
Thanks for the report. Marking as duplicate as https://github.com/matomo-org/matomo/issues/11939
