### ISSUE TITLE
ISP/Organization data cannot be retrieved after integration of MaxMind databases

### ISSUE THREAD

**Issue by tinzog** [matomo-org/matomo#8927]
The issue was discussed in the following thread:
http://forum.piwik.org/read.php?15,125516,129698#msg-129698

When integrating commercial MaxMind databases and installing the GeoIP location provider, as shown in the screenshots by Iduro, no ISP/Organization data can be retrieved when deactivating Piwik's provider plugin, as suggested in FAQ Nr. 180.
When reactivating Piwik's provider plugin ISP data is displayed as before integration of the MaxMind databases.

Please investigate if this might be a regressed feature.

**Comment by mattab** [comment]
Hi @tinzog , thanks for the report. It's not a regressed feature, but rather a bug: we should not store the Maxmind ISP/Org in the same field as the "provider" plugin uses.

**Comment by hpvd** [comment]
ISP and organisation should be Different fields as well, since can contain different types of information. Please see example in attachment
![2016-02-11_16h53_12](https://cloud.githubusercontent.com/assets/5681880/12981347/8fd173f6-d0e0-11e5-9777-204bb133e3ce.png)

**Comment by hpvd** [comment]
seems to be related to https://github.com/piwik/piwik/issues/6615

**Comment by mattab** [comment]
Hi Alex,

we'll probably stop using Maxmind soon, so closing this issue now, see #15308
