### ISSUE TITLE
Feature request: ability to make a dashboard read-only

### ISSUE THREAD

**Issue by MagicFab** [matomo-org/matomo#8939]
It would be useful as a regular user (or superadmin) to be able to set a Dashboard settings (including optionally the period and segment) as read-only.
This would prevent changes to widget position and other settings in context where such dashboards are built for a specific audience (other staff, management, etc.) where any wrong manipulation could accidentally mean unwanted changes difficult or impossible to revert.

**Comment by MagicFab** [comment]
Also mentioned here: http://forum.piwik.org/read.php?17,129146

**Comment by mattab** [comment]
There is a small workaround:
 * One can change the "default layout" of the dashboard to the desired one
 * If one moves or changes dashboard, a click on "reset dashboard" will restore the desired layout
 * one can already export a given widget to a user who can only "Read" the piwik reports, for example using widgetized https://piwik.org/docs/embed-piwik-report/#embed-the-piwik-dashboard-in-a-html-page . If using the token of a user with 'view' access then it is basically "read only" besides the fact the user can also create scheduled reports, move widget around the dashboard, etc.

**Comment by mattab** [comment]
Over the last few months, a few more users have requested the ability to Share a dashboard with someone, and keeping the dashboard synchronised with the original dashboard that is being improved.
This would be useful almost always, for example when one Marketing team member creates the Marketing team dashboard, and wants to share it with others. Currently they need to copy it, but as soon as someone makes an improvement they need to share it back with other. It is not synchronised. So the idea is to build this synchronised dashboard by allowing people to share the dashboard with others and keep it synchronised.

Thoughts:

* When sharing a dashboard with someone else in this way, to keep it simple we can make it read only. 
  * (Eventually maybe we could let other people edit the dashboard, so one could collaboratively work on the same dashboard. Not needed in MVP. Matomo is not currently designed to work well when multiple users edit a dashboard layout at once)
* We'll need to find ideal words to describe the two concepts of "Copying a dashboard", and "Give read-only access to my dashboard template for this site".
* When a dashboard has been actively given access to by another user, we should somehow make it clear in the UI that the dashboard is currently shared with others (and may affect other users).
* Similarly when viewing a "Read only dashboard" managed by another user, it should be clear that it is such a dashboard and layout/reports are done by User XYZ and cannot be changed.
* When viewing a read-only dashboard shared by another user, in some cases I want to re-use the dashboard  for one of the website(s). So as a person who shared a dashboard, I want to be able to copy it to my account (by re-using the feature "Copy this dashboard to user")

**Comment by mattab** [comment]
Likely we won't implement this feature in the future, however this may be done as part of: https://github.com/matomo-org/matomo/issues/6964
