### ISSUE TITLE
Show better loading indicators

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#8987]
Our loading indicators are often barely visible because of the grey color and because they are so tiny displayed. It would be nice to display them a bit bigger, eg when clicking on a report in the dashboard area.

Personally, I really like the Material Design circular progress indicator (https://material.angularjs.org/latest/demo/progressCircular & https://dribbble.com/shots/1644878-Material-Design-Circular-Progress-Indicator ) :) but we could also just make the existing one a bit bigger or use any other.

To improve the perceived speed it would be nice to directly show a blank/empty/skeleton report etc see eg http://www.lukew.com/ff/entry.asp?1797 . This might be actually doable in Piwik 3.0 or 4.0 as we have the page layout there and kinda know what we are about to render. We'll possibly have to create a new issue for this in case we want to do this.

**Comment by tsteur** [comment]
There's also http://ui.lumapps.com/services/progress

**Comment by mattab** [comment]
:+1:

**Comment by mattab** [comment]
https://www.startpage.com/do/dsearch?q=open%20source%20loading%20icons

**Comment by tsteur** [comment]
http://lab.hakim.se/ladda/ may be interesting as well
