### ISSUE TITLE
CSRF in user tracking

### ISSUE THREAD

**Issue by UnlockPrice** [matomo-org/matomo#9041]
1) In piwik, admin can provide tracking optout option for users using iframe "http://demo.piwik.org/index.php?module=CoreAdminHome&action=optOut&language=en"
2) If suppose attacker embeds the url and makes the user to execute the url "http://demo.piwik.org/index.php?module=CoreAdminHome&action=optOut&language=en&setCookieInNewWindow=1&showConfirmOnly=1", they will be tracked out from piwik analytics without their knowledge

Regards
Elamaran V
elamaran619@gmail.com

**Comment by mattab** [comment]
Thanks for the report @UnlockPrice !

**Comment by sgiehl** [comment]
This had been fixed with #14400
