### ISSUE TITLE
Remove word "website" from website selector

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#9063]
As mentioned here https://github.com/piwik/piwik/issues/8712 I do now think as well that we should remove the word "Website" from the sites selector eg as suggested here: https://github.com/piwik/piwik/issues/8712#issuecomment-148390762

All other selectors use a proper icon instead but the selector doesn't yet. 

![image](https://cloud.githubusercontent.com/assets/273120/10600075/0d2f6ebc-7708-11e5-8609-3ab7d94d9d1d.png)

Instead of the word "website" I'd  rather see an icon, maybe one similar to the one used in Piwik Mobile eg http://fortawesome.github.io/Font-Awesome/icon/globe/ but could be also a different one since the globe could be also used for language etc.

Because of the word website one cannot see much of the website's name which can be especially tricky if one has many websites with similar names, maybe even many websites that start with the same name.

**Comment by gaumondp** [comment]
So far we just track websites so "globe" is perfect, then we will need an "app" icon and "intranet" icon too and others over time, right ? I'm refering to #4734 .  So the globe should be "attached" to the actual site category.

And we also have to settle "to bold or not to bold" the name...

**Comment by tsteur** [comment]
Good point. Removing the term "website" will also avoid confusion when the selector shows not only websites but also apps etc. Users could think it is only possible to track websites which is not true. Even now it is already possible to track mobile apps etc. If all "measurables" are websites we'd show a globe, if an app we could show an app icon, if it is mixed we could show a generic icon. Maybe it'd be good to always show a "generic" icon.

I'd not make it bold since the other selectors are not bold as well. Making all bold doesn't really look nice and doesn't really improve usability. If it helps for usability we could make the website name bold since if there's more than one website available.

**Comment by gaumondp** [comment]
I wasn't obvious enough. I was thinking about just the name to put in bold, never the icon.

So replace "WEBSITE" in Matt's screenshot at https://github.com/piwik/piwik/issues/8712#issuecomment-148559748 with an icon and we will be set.

AFAIK (at least in 2.13) we can't set a category (web,intranet/app) in the Administration "Websites Management", right ? That's mandatory if we wanna show something related to a category in the dashboard.

**Comment by tsteur** [comment]
It's possible if you activate the `MobileAppMeasurable` plugin. It doesn't really make any difference when you create a mobile app yet though. This will become more valuable in 3.0

**Comment by maliayas** [comment]
Related to the topic, I suggest remove the static width of the website selector. If the site/app name is long, then the selector should adapt to it, IMHO.

**Comment by tsteur** [comment]
I've created an issue for our designers to propose an icon (PPCDEV-2603)

**Comment by sgiehl** [comment]
The word "website" was removed in Piwik 3. But we still don't show an icon. Do we still want to do it? Otherwise this issue can be closed.

**Comment by tsteur** [comment]
Yes be good to still use an icon for it 👍  if we don'T find anything, we can also leave the arrow for it. Anyway, we can close this issue and maybe create new issue to find icon?

**Comment by tsteur** [comment]
this was done I think. No need to change icon for now unless someone comes up with a good idea :)
