### ISSUE TITLE
Add segmented visitor log to page url and page title folders

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#9229]
Once #8076 is resolved and once there is a "Starts with" segment operator we could provide the possibility to use the segmented visitorlog #4633 on folders in the Page URL and Page Title report I think.

Eg when structure is 
- blog
  - 2014
    - 01
      - index.html

I think we could segment `pageUrl=^example.com/blog/2014` to get all users that were on that folder

**Comment by mattab** [comment]
Very nice idea :+1:

**Comment by tsteur** [comment]
Addling label easy pick, all one has to do is to add `segment` metadata for each row in `Actions/API.php` in case anyone is keen to work on it
