### ISSUE TITLE
Add possibility to toggle (show/hide) left menu

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#9263]
Possibly via keyboard shortcut see 
https://github.com/piwik/piwik/pull/8936#issue-110218274

> Zen Mode was removed as it was supposed to remove the space it needs in the header, as the header doesn't need much space anymore it is no longer needed. We might introduce a ZenMode later at some point which will be eg activated by pressing the key z which will fade out the left menu to have full width content. The left menu is not really needed anymore when using search

Not sure if we would show an icon again.

Another version will be to show only the icons and only a very small left menu when screen width is low. This would be a different issue though probably since complexity is higher.

**Comment by tsteur** [comment]
In Piwik 3 it will be possible to enable/disable Zen Mode and hide left menu + header by pressing `z`. We need to think about a way to make users aware of this possibility

**Comment by mattab** [comment]
> We need to think about a way to make users aware of this possibility

Maybe we could do it with an icon, that would be displayed on the same line as the top controls, that on click would enable the zen mode? Something like this:

![icon to collapse to zen mode](https://cloud.githubusercontent.com/assets/466765/18774042/266eb3ea-81a9-11e6-9534-309448a85b90.png)

(Icon could be either displayed at all times, or only on hover on the top controls)

Once in Zen mode, we could show the icon (on hover or all the time) to exit zen mode:

![exit zen mode with icon](https://cloud.githubusercontent.com/assets/466765/18774068/7ed3d5d8-81a9-11e6-897b-a0e55229a1a7.png)

(Note: stole this nice idea from google docs)

**Comment by tsteur** [comment]
We just need to think about solution for demo.piwik.org where there is something else in the right. Also depending on the resolution there is not much space to the right of dashboard etc. Would also need to find solution for mobile devices

**Comment by mattab** [comment]
@tsteur moving to beta2 - would be nice to have in Piwik 3 but not absolutely required :+1:

**Comment by tsteur** [comment]
shouldn't be too hard to implement, we just need a solution that works on all resolutions etc and on demo

**Comment by MikeN123** [comment]
I just accidentally enabled 'zen mode' by pressing 'z' in Piwik 3.0, and had no idea how to get out of it, until I checked my cookies and saw the zen mode cookie. It doesn't seem to display any 'exit zen mode' button. May be something you want to fix.

**Comment by tsteur** [comment]
You can get out of it by pressing 'z' again, but indeed if you don't know what triggered it initially, it is hard to find. Be good to find a solution for this.

**Comment by tsteur** [comment]
Maybe we add another selector like this?

![image](https://cloud.githubusercontent.com/assets/273120/21368714/9ca13dc6-c768-11e6-9ac9-dd5015a58e40.png)

or is it too visible? Having it to the right would be hard to manage probably because of responsiveness, small screens and with piwik demo

**Comment by MikeN123** [comment]
Looks fine to me, it at least gives the user a way out if they don't know the 'z' shortcut.

**Comment by tsteur** [comment]
Now that we have removed the "you are viewing the demo of Piwik" message in the right top bar, we could add it there as suggested by @mattab  in  https://github.com/piwik/piwik/issues/9263#issuecomment-249099386 

Be great to have 👍

**Comment by mattab** [comment]
Fixed in #12459
