### ISSUE TITLE
Subtables in dashboard widgets are not scrollable

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#9302]
Not sure if it's a duplicate. To reproduce go to http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#?module=Dashboard&action=embeddedIndex&idSite=7&period=day&date=yesterday&idDashboard=1 and click of a row in "Referrer Websites". At least on Chrome 46 on a Mac I cannot scroll to the right and actually see the values of the subtables

![image](https://cloud.githubusercontent.com/assets/273120/11459995/ac45cad6-9748-11e5-9ef5-22a1d36ec644.png)

**Comment by heurteph-ei** [comment]
It seems it has been fixed...

**Comment by sgiehl** [comment]
Yes. that should be fixed meanwhile. Thanks for the hint.
