### ISSUE TITLE
Let user view changelog even for beta releases

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#9355]
Beta changelog does not exist and leads to mainline logs, which do not include beta changes. Beta version log change could be provided for latest mainline edition only.

![2015-12-07_223541](https://cloud.githubusercontent.com/assets/5383059/11640517/2b2b7df6-9d33-11e5-949b-e9a6c5b01d44.png)

Thanks

**Comment by tsteur** [comment]
I know it is off topic but what I found a nice idea is that Grafana shows an overview of new features on their live demo in top left like this: http://play.grafana.org/  (eg New features in 2.0, new features in 2.1)

http://play.grafana.org/dashboard/db/new-features-in-v20

It would be nice to have something like this in a similar way as well so users can discover the new features. It would be ok in the beginning if it's just links to the changelogs on Piwik.org like it is in the "Blog" widget but maybe we could make more out of it. We usually add some nice features and it is hard for users to get aware of it.

**Comment by mattab** [comment]
Thanks @dev-101 for the suggestion. Currently, we don't have a changelog for beta versions, but we could list to the list of closed issues in the milestone eg. 

> Grafana shows an overview of new features on their live demo in top left like this: http://play.grafana.org/ (eg New features in 2.0, new features in 2.1)

> http://play.grafana.org/dashboard/db/new-features-in-v20

> It would be nice to have something like this in a similar way as well so users can discover the new features.

This is very cool idea. It's kinda related to improving our onboarding #7170
