### ISSUE TITLE
Allow manual update of referrer-spam-blacklist within Piwik admin

### ISSUE THREAD

**Issue by tholu** [matomo-org/matomo#9380]
It would be great to have a button in admin to manually update https://github.com/piwik/referrer-spam-blacklist in Piwik admin, to make sure to have the latest version.

**Comment by tsteur** [comment]
I wonder if it's possible / useful to integrate this into "Check for updates" and maybe the auto-updater but not sure :)

**Comment by tholu** [comment]
@tsteur Sounds good for me!

**Comment by mattab** [comment]
Note that Piwik automatically updates the referrer spam list once a week already, so this feature is not that important for us.

**Comment by ronak-innocraft** [comment]
The list already updates once a week, and there is no valid use case that would require a more frequent updates, or a manual update. Closing this one and feel free to submit new idea if there is a strong use case for it.
