### ISSUE TITLE
Piwik website to show FAQ of Piwik plugins

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#9392]
I wonder if it would be any useful if the Piwik.org website did also show the FAQ entries of Piwik (and maybe free Piwik PRO) plugins. For example the FAQ from http://plugins.piwik.org/QueuedTracking or http://plugins.piwik.org/CustomDimensions 

The Marketplace provides an API so the website could fetch all FAQ entries where the developer is `piwik`. The API returns a markdown and/or HTML (not sure right now) of FAQ entries (we'd need to parse them into separate questions) and it is currently not possible to fetch all plugins from a specific developer via API (I think, it might be possible though) but one could probably fetch all plugins and then check for developer manually. 

I presume it would be useful but too much work. Feel free to close it. On the piwik.org website we'd probably have to mark the FAQ entries as duplicated content for SEO.

**Comment by tsteur** [comment]
Just FYI: There would be already an API to fetch all plugins from a certain developer

**Comment by mattab** [comment]
Maybe we could manually import those FAQs from our "piwik" official plugins into piwik.org/faq/ ?
