### ISSUE TITLE
heartbeat ping with growing intervals

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#9423]
to optimize informative value and lower server-load at the same time,
the possibility of a growing ping intervals of the heartbeat signal would be good.

(edit: @diosmosis has also proposed the main thought behind it in #8213, here it is again in a little more general way with more explanation why it's really needed and with a concrete example)

Use-case:
At the beginning of a one-page-visit it's very important to have very short intervals to understand why the visitor was leaving (especially on one single page visits)
But because of server-load, one could not keep this very short interval within complete visit where it is not needed anymore.

A) very short: only seen very first design impression could be the reason (or site does not load completely e.g. because of a blocker software and looks broken)

B) short: only headline, Image, first sentence could be the reason

C) middle: content was in general not that interesting to read everything / take action

D) long: got all information but takes no other action
e.g. because he got everything he was looking for
or even seeing/reading everything it was not motivating to take action...

=> One idea to set this up, is giving a second value
to the setting of the the default heart beat interval
( _paq.push(['enableHeartBeatTimer', 2]); )
which defines some kind of a growing factor which is multiplied to the interval used before.

the result could look like:
![2015-12-21_12h04_23](https://cloud.githubusercontent.com/assets/5681880/11929407/00072262-a7db-11e5-9ed9-1533543f836b.png)

**Comment by hpvd** [comment]
to make your own calculations which values are needed for your requirements in a quick way,
please find attached the excel file the screenshot in the comment above was taken from.
[Piwik-variable-interval-for-heartbeat-ping.xlsx](https://github.com/piwik/piwik/files/68469/Piwik-variable-interval-for-heartbeat-ping.xlsx)

**Comment by tsteur** [comment]
Requirements for this kinda stuff can be very different for each user and I think as suggested here: https://github.com/piwik/piwik/pull/8213#issuecomment-115265214 and https://github.com/piwik/piwik/pull/8213#issuecomment-115281899 we should only allow a fix value and then an option JS callback so anyone can change the interval to it's need.

**Comment by hpvd** [comment]
@tsteur thanks for pointing there. I opened this in a new ticket again (the one you are pointing to was closed somehow) to clarify the background why one need the possibility to have growing intervals.
If one can achieve this in a not to complicate way, having a fixed default value is fine too.
But as described, imho the possibility to use a growing interval is really important.

**Comment by tsteur** [comment]
Yes, it's very important indeed. Especially for server load etc. Just saying instead of offering a fixed growing rate we need to let users customize it which makes it easier for us to implement and for users more flexible. Eg for online magazines etc they might want to send an interval during the first 30 seconds every second and then maybe every 2 or 3 seconds and then it increases maybe a bit faster

**Comment by hpvd** [comment]
perfect. Was also talking about letting user set up a  base value and a growing rate up to their needs...
The more flexible the better (if still easy to use) :-)

**Comment by hpvd** [comment]
another alternative way to lower number of necessary website to server contacts and with this server load is described here: https://github.com/piwik/piwik/issues/9475

**Comment by tsteur** [comment]
Ideally, we only ping every say 5 or 10 minutes and otherwise ping if the user either leaves the window (blur event) or closes the tab. As we're now having sendBeacon the request should be pretty much always sent and this feature may not be needed anymore.

**Comment by tsteur** [comment]
Closing this in favour of https://github.com/matomo-org/matomo/issues/15049
