### ISSUE TITLE
Annual report

### ISSUE THREAD

**Issue by gaumondp** [matomo-org/matomo#9435]
Use case: Produce an annual report with the main numbers

By annual it could mean from March to March (frequent in Government institutions) or even for every kind of date selection with recaps. 
Ex: 

a. If month, choose 12 months from this month (March 2016 and last 12 months)
b. if weeks, last 3 weeks
c, if days, last 30 days.

Data for **each** months :
- Content of Visitors Overview (text-only)

Then for the whole period/year : 
- 25 most visited pages
- 25 most downloaded files
- 25 Referrers
- 10 Social networks with percent. 
- 25 Site search terms
- Percentage of PC, Tablets, Phone
- 10 most used OS with percent.
- 10 most used Browsers with percent.
- 10 most popular resolution with percent.

In its current form, getting monthly reports is more than annoying... It can takes a full day to manually go to each month if you need segments and your DB is over 50 GB.

**Comment by tsteur** [comment]
:+1: I like that a lot. Such things should be made easy and here we could make Piwik much more useful instead of just showing some plain reports etc. This could be done in a new plugin "easily" if someone is keen :)

**Comment by gaumondp** [comment]
Thanks for showing your interest @tsteur ! Your eagle eye have probably notice the mention of many "with percent"...

We still have to mouse over over "Visits" to see those measure that are way more "speaking" than "Visits number"...

I wish I was a developer... Frankly I was surprised, 3 years ago, such a report was not in Piwik but available in Analog and Sawmill.net (2 logs analyzers I used 10 years ago)

**Comment by tsteur** [comment]
Absolutely, I'd love to see percentage more as well and am as surprised as you. Plain numbers don't tell anything unless you can see the relation to the other rows via percentage within the same date/period and via evolution to compare it with previous days / weeks / ... That's why I'd love to see evolution pretty much "everywhere" on top of each screen.

**Comment by gaumondp** [comment]
Do you think it's worth adding such new plugin to our Enterprise Analytic Platform as described in #8920 ?

**Comment by tsteur** [comment]
Not sure, I find it actually quite basic and not only useful for Enterprise but feel free to add it there. It doesn't hurt :)

**Comment by gaumondp** [comment]
It is so basic it is not there. ;)

But just having mention it makes it shows in the page of 8920 so I'm fine with that. Right now I'm thinking about doing some uglyness by repeating manually this for each month with variations for segments I need too : 

http://stats.mysite.com/index.php?module=API&method=VisitsSummary.get&idSite=6&period=month&date=2015-12-1&format=HTML&token_auth=123456

Ugly but fast.

**Comment by hpvd** [comment]
should be flexible in total period (as decribed: date to date) 
and also flexible in intervalls in between (hours, days, weeks, month, years)

**Comment by mattab** [comment]
Thank you for creating the issue, very appreciated :raised_hands: 
As it aligns with Issue https://github.com/matomo-org/matomo/issues/2012 and https://github.com/matomo-org/matomo/issues/2860 and https://github.com/matomo-org/matomo/issues/21069, I'll close this one. It would be great to have your perspective there.
