### ISSUE TITLE
Suggestion: instance-wide report overview in admin area

### ISSUE THREAD

**Issue by schwindelbub** [matomo-org/matomo#9479]
Hello,

it would be great to have as an admin an overview of all created reports (from all users) in the piwik instance. So the admin has the possibility to delete one or all reports. 
Basically a list of the table 'piwik_report'. 

This came to my mind, as I deleted an user, but the user continued recieving mails. This was because it exists a report with the users email address, but as an admin i can't see this report. (#9474).

Best regards,
Schwindelbub

**Comment by tsteur** [comment]
This was also suggested in https://github.com/piwik/piwik/issues/7076 but I think it is good to keep this one as a "sub-issue" of #7076 as we probably won't implement everything within #7076 at once.

FYI: All scheduled reports that are created by a certain user are supposed to be deleted when a user is deleted. Maybe the email address is still there in a report of another, still existing user

**Comment by mattab** [comment]
Thank you for creating the issue, very appreciated :raised_hands: 
As it aligns with Issue https://github.com/matomo-org/matomo/issues/7076, I'll close this one. It would be great to have your perspective there.
