### ISSUE TITLE
Metadata for report Referrers.getReferrerType could not be found.

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#9697]
In a goal report, the "Goals by Referrers > Referrer Type" report fails to load.

Reproduce URL: https://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#?module=Goals&action=goalReport&idSite=7&period=day&date=yesterday&idGoal=2

In Goals by Referrers > Referrer Type, we get `The DataTable cannot be manipulated: Metadata for report Referrers.getReferrerType could not be found. You can define the metadata in a hook, see example at: http://developer.piwik.org/api-reference/events#apigetreportmetadata`

Notes:
- Why it was not caught in the UI tests?
- Let's add UI test if there isn't one already

**Comment by tsteur** [comment]
If it's not caused by tests it's likely because of another plugin... I'll have a look

**Comment by tsteur** [comment]
So it works on my local instance. Must be caused by another plugin!

**Comment by mattab** [comment]
do you know if it would be possible to write in error message which plugin causes this issue?

**Comment by tsteur** [comment]
Nope, not even sure how to detect such thing or how it is happening

**Comment by tsteur** [comment]
Which custom plugins are active there?

**Comment by tsteur** [comment]
FYI: It works on demo2, so it might be a plugin or something that is active on demo but not demo2

**Comment by tsteur** [comment]
BTW: This is a backtrace

![image](https://cloud.githubusercontent.com/assets/273120/12806067/76383fc0-cb67-11e5-975b-6d749bcba182.png)

**Comment by tsteur** [comment]
It might be fixed by removing  lines https://github.com/piwik/piwik/blob/master/core/API/DataTableManipulator.php#L159-L161 but then at the same time I have no idea why it works for other reports...

**Comment by mattab** [comment]
(note: the "reproduce URL" I initially pasted now is working fine)

**Comment by quba** [comment]
Maybe it's because some non-default datatable visualization setting?

**Comment by pennadl** [comment]
Same problem here, happened from a day to another

**Comment by sgiehl** [comment]
Ok. I'm able to reproduce it with the following steps:

1. Got to Referrers > All Referrers
2. Flatten the Referrer Type Report
2. Go to a Goal report page and the referrer type report will show the above mentioned error

Switching back to non-flattened all referrers report solves the problem on the goal report.

**Comment by sgiehl** [comment]
We need to find a better solution for this error for 3.0

**Comment by mattab** [comment]
@sgiehl what should we do here? would be good to close this ticket or fix it if possible. Thanks

**Comment by mattab** [comment]
Fixed in the meantime :+1:
