### ISSUE TITLE
Text in Marketplace/themes confusing

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#9706]
Text in Marketplace/themes is a little confusing:

It's the same sentence as shown on plugin tab.
And it's a bit confusing talking about plugins here.

=> Maybe the word "plugin" should simply be changed to "theme" (like it was already on otherplaces in this text)?
=> Or should it be deleted because it doens't work that way for themes?

![2016-02-04_14h50_56](https://cloud.githubusercontent.com/assets/5681880/12817010/f97b8b20-cb4f-11e5-8777-6160201b98ac.png)

**Comment by tsteur** [comment]
Just implemented it here: https://github.com/piwik/piwik/commit/0e0cf3b90b4134aa763f7aac5850cbff72255b81

However, it will take a while until this gets merged. It will be fixed in 2.16.1 or 2.16.2

**Comment by mattab** [comment]
Thanks for the suggestion @hpvd!

**Comment by Findus23** [comment]
This seems to have been fixed a while ago.
