### ISSUE TITLE
Crimea on world map

### ISSUE THREAD

**Issue by antropophob** [matomo-org/matomo#9719]
There is an issue with world map that Crimea is related to Ukrain
Not shure is it a good idea to request global fix.
But it woul be good to have a map with Crimea as part Russia for russian users.

Also, what tool did you use to create svg map?
![screen1](https://cloud.githubusercontent.com/assets/2070015/12849786/7ebfc106-cc32-11e5-8592-ce1ac1b9d22e.PNG)

**Comment by sgiehl** [comment]
Guess it is similar to #6006.

The maps were generated with: https://github.com/piwik/piwik-map-generator
But the tool isn't working anymore. Tried to get it running recently, but failed.
The creator of the tools/maps - a former contributer - is'nt available anymore 

There are a few other tickets open regarding the maps, but we can't solve them at the moment.
It may take some time until someone has the time to get into the tool and get it working correctly again.
If you are keen to do so, feel free and go ahead :smile:

**Comment by antropophob** [comment]
Well... I'll try. Will report if have any positive result.

**Comment by SergiusTheBest** [comment]
Crimea belongs to Ukraine according to UN resolution. I urge everyone not to please Russia for their illegal annexation and don't show Crimea as part of Russia.

**Comment by sgiehl** [comment]
We are working on new maps #11929 and will use latest data from https://www.naturalearthdata.com/ Likely there won't be any country specific versions.
Current maps won't be updated anymore until the new maps are finished in hopefully a few months.

**Comment by sgiehl** [comment]
closing in favor of https://github.com/matomo-org/matomo/issues/11929
