### ISSUE TITLE
Vistor/...: show always same number of rows of data

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#9761]
In Vistor/... data is shown with variing numbers of rows before pagination.
This looks a bit unstructured... More structure by always showing same amount of rows (e.g. 10) would look more professional.

just a short overview.

Vistor/Software
- OS: 10
- Browsers: 10
- Configurations: 3
- Plugins: 10 ? (no pagenation shown)

Vistor/Location
- Country: 5
- Region: 5
- City: 5
- Continents: 8 (all?)
- Browser Language: 10
- Providers: 5

Vistor/Devices
- Device type: 12 (all?)
- Device model: 10
- Resolutions: 5
- Device Brand: 10

example:
![2016-02-11_22h04_57](https://cloud.githubusercontent.com/assets/5681880/12990696/00e84a62-d10c-11e5-9710-f3ea35cee4f1.png)

**Comment by tsteur** [comment]
that would be useful and would look much better indeed

**Comment by mattab** [comment]
This appears fixed in the meantime :tada:
