### ISSUE TITLE
Display a notification to Super User when new plugins are published on the Marketplace

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#9766]
As a Super User, I want to be notified whenever there is a new plugin published on the Marketplace.

This would have several advantages:
- better expose to users all the cool new features released on marketplace
- generally raise awareness about Piwik as a platform and our open marketplace
- help plugins developers to gain more users for their plugins

**Comment by tsteur** [comment]
@mattab what do you have in mind re wording for this etc?

**Comment by mattab** [comment]
The update notification email was added in the meantime.
