### ISSUE TITLE
Remove <noscript> from default JS tracking code, new checkbox to add <noscript> + remove<p> tag in <noscript>

### ISSUE THREAD

**Issue by fmp777** [matomo-org/matomo#9770]
Having img without p works just as fine.  the P tag could cause unwanted space in the web page that executes the noscript block.

**Comment by tsteur** [comment]
Good point. However, I presume it is there for valid HTML structure. Eg `body` element is allowed to have `p` element but not `img`. 

If the `p` element causes any troubles re spacing and you do not need valid HTML I recommend to remove it manually. 

Are there any opinions if without `p` should be maybe default and having an option for "valid HTML"?

**Comment by tsteur** [comment]
Actually, since https://github.com/piwik/piwik/issues/9341 we recommend to put the tracking code into `<head>` where `<noscript>` is not allowed anyway. So we could as well remove the `<p>` maybe.

**Comment by mattab** [comment]
maybe we should completely remove the `<noscript>` tag since it is not allowed in the `<HEAD>`. If we do, maybe we could have a new JS Tracking Code option (checkbox) to let users add the `<noscript>` on demand. When this checkbox is checked, it would also directly add the

**Comment by mattab** [comment]
maybe we should 
 * completely remove the `<noscript>` tag since it is not allowed in the `<HEAD>`. If we do, maybe we could  
 * introduce a new JS Tracking Code option (checkbox) to let users add the `<noscript>` on demand. When this checkbox is checked, it would also directly add the `&rec=1` parameter, saving user the extra step ([currently this is documented in FAQ which may be hard to discover for users](https://piwik.org/faq/how-to/faq_176/))

https://piwik.org/faq/how-to/faq_176/

**Comment by mattab** [comment]
See also #9776 When tracking code is put in <head>, add a note that fallback noscript should be put in body 

(Note that this `<noscript>` not working by default caused some confusion before: #9360  Lack of parameter in <noscript> part of Piwik's JavaScript tracking code )

**Comment by mattab** [comment]
Renamed issue to increase scope.

**Comment by braiam** [comment]
> the P tag could cause unwanted space in the web page that executes the noscript block.

A way to solve that particular issue is to set the style of the p tag as `display: none;`.

**Comment by sampablokuper** [comment]
@tsteur [wrote](https://github.com/piwik/piwik/issues/9770#issuecomment-183718333):
> Actually, since #9341 we recommend to put the tracking code into `<head>` where `<noscript>` is not allowed anyway.

@mattab [wrote](https://github.com/piwik/piwik/issues/9770#issuecomment-196636451):
> maybe we should completely remove the `<noscript>` tag since it is not allowed in the `<HEAD>`

You are both wrong ;) As @braiam [points out](https://github.com/piwik/piwik/issues/9776#issuecomment-275844542), `<noscript>` *is* allowed in `<head>`.

*However*, an `<img>` in a `<noscript>` in `<head>` is [not valid](https://stackoverflow.com/questions/23824576/noscriptimg-in-head-valid/23824708#23824708).

So, what to do?

If you want you want the (X)HTML to be valid (yes, please!) and you want to use an `<img>` element for analytics purposes, you'll need to put that `<img>` in the `<body>`. If you do that, then you might as well follow the advice of @hpvd [here](https://github.com/piwik/piwik/issues/9341#issuecomment-162661102) and @MattISG [here](https://github.com/piwik/piwik/issues/9341#issuecomment-263349098), and ***put the entire code block just before the `</body>` tag***.

**Comment by HLFH** [comment]
Any updates on this * Bad start tag in p in noscript in head* issue?

<img width="691" alt="Screenshot 2020-10-21 at 10 05 57" src="https://user-images.githubusercontent.com/2359059/96698461-0a573e80-1385-11eb-9ca6-0e4cc3e6fdde.png">

Thanks

**Comment by mattab** [comment]
fyi @HLFH the noscript is removed from Matomo now by default so you can remove it from your tracking code as well. it should fix the issue.

**Comment by mattab** [comment]
There is also an option to "Track users with JavaScript disabled" so this was already implemented in full :+1: 
![Screenshot from 2020-11-02 10-32-46](https://user-images.githubusercontent.com/466765/97815972-cf46fa80-1cf6-11eb-9e29-dbd1e5fa52da.png)

**Comment by HLFH** [comment]
@mattab Hi Mattab, this issue was the <noscript> tag within <head> was not valid HTML. I finally put the whole Matomo JS code and <noscript> tag before the </body> tag.

But finally or sadly, and regardless of this small issue, I had trouble to have any working tracking with the last version 4.0.0-b4. So I migrated to GA 4.
