### ISSUE TITLE
Inform users about possible issues with Page Overlay report

### ISSUE THREAD

**Issue by quba** [matomo-org/matomo#9807]
Page overlay report may not work because of various reasons. I can list two of them from the top of my head:
- tracked page doesn't support https and Piwik was loaded via https (or even there's a force_ssl setting in the config)
  _The easiest solution here is to not force ssl and to run Piwik via http when one wants to see the Overlay report_
- 'X-Frame-Options' are set to 'SAMEORIGIN'.
  _The solution here is to change the X-Frame-Options header_

It would be nice to display a message informing users, why the Page Overlay report doesn't work. I think that it's a high-valuable and easy improvement.

**Comment by mattab** [comment]
Thanks for the suggestion. The troubleshooting guide is found here: https://matomo.org/docs/page-overlay/#page-overlay-troubleshooting

as part of https://github.com/matomo-org/matomo/issues/4481 we will link to the user guides from within the app.
