### ISSUE TITLE
the same Event documentation appears multiple times on the developer events list

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#9836]
See: https://developer.piwik.org/api-reference/events#requestinitauthenticationobject

The same event `Request.initAuthenticationObject` appears multiple times.

Expected: 
- it should only appear once in the list and the event documentation should list all occurences of the event in the codebase.
- the events that are posted in any _tests_ files should not appear on the page (currently event defined in `Piwik/Plugins/API/tests/Integration/APITest` also appears in the doc)

**Comment by tsteur** [comment]
Also the code in core needs to be refactored as we have obviously duplicated code here.
