### ISSUE TITLE
Javascript tracker: allow to set a HTTP timeout in seconds

### ISSUE THREAD

**Issue by adhamshamkh** [matomo-org/matomo#9850]
First thanks for the great work on PIWIK.

We are using a Javascript tracker, and are experiencing an issue when our network or servers are down/inaccessible for whatever reason. The issue is that the Google chrome browser highlights in the status bar (bottom left of browser) that the site is:

**"Waiting for webanalytics.piwik-server.com......"**

Whilst this doesn't impact the site majorly it's undesirable to have this message displayed for a long time (when a connection is made this flashes up very quickly and is not noticeable) and also shows the revolving icon in the header tab that shows the page is still doing something. Fiddler confirms that the requests runs for *\* 21 seconds*\* and then reports a timeout as below.

**[Fiddler] The connection to 'webanalytics.piwik-server.com' failed. 
Error: TimedOut (0x274c). 
System.Net.Sockets.SocketException A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond XXX.XXX.XXX.XX:80**

What I am hoping for is an option to set a request timeout somewhere of say 1 or 2 seconds, 
in that time frame we can reasonably expect the tracking to have happened, if it hasn't then we are happy for the process to timeout. presumably this must be controlled from the javascript? Is there such an option? 

If anybody could offer any suggestions i'd be really grateful!

Thanks in advance,
Adham

**Comment by tsteur** [comment]
Is this message shown for loading the `piwik.js` or for actually sending a tracking request?

In case of a tracking request: So far we do not set any timeout. Feel free to send us a PR that let's anyone configure a timeout, this would be useful. The call is done here: https://github.com/piwik/piwik/blob/2.16.1-b1/js/piwik.js#L3198-L3217

**Comment by mattab** [comment]
@adhamshamkh 

try also to:
 * Disable Provider plugin (if it is enabled)
 * Use the QueuedTracking plugin: http://plugins.piwik.org/QueuedTracking (for faster tracker)

**Comment by adeptic** [comment]
Hi, what Adham is suggesting would be really useful ("an option to set a request timeout somewhere of say 1 or 2 seconds") for us as well, is there any code for this we could use?

Cheers and thanks for a great software!
Pontus

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
