### ISSUE TITLE
hide referrer of outgoing links (e.g. to provider or organisation)

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#9852]
Piwiks url should not always be visible / spread widely

Since there are some outgoing links e.g. back to organisation where visitors come from within visitorlog, it would be good to hide the referrer (piwiks urls)

adding
`<meta name="referrer" content="no-referrer" />`
should be enough these days

more complete solutions are
e.g. via js or php are discussed here
https://stackoverflow.com/questions/6428762/hide-referrer-on-click

**Comment by tsteur** [comment]
Thx, we should add it. I think we already set this for most links (not globally) and sometimes use our proxy to remove the referrer but would be better to also set it globally

**Comment by mattab** [comment]
Note: the `rel=noreferrer` is already set on the Provider/Org links (so referrer does not leak to these websites).

**Comment by hpvd** [comment]
rel=noreferrer is a good step.
Since it's not support by every broweser one may should add some extra levels of forcing it

See:
![2016-03-31_12h39_08](https://cloud.githubusercontent.com/assets/5681880/14173395/e8bbda46-f73d-11e5-8394-15291a6411be.png)

source: https://en.wikipedia.org/wiki/Comparison_of_layout_engines_%28HTML5%29

**Comment by mattab** [comment]
When we link to external websites where the URL linked to was "user submitted" (for example via the Tracking API referrer website tracking), it's very useful to set rel=noreferrer because it protects us against  phishing  attacks using the window.opener technique described in https://mathiasbynens.github.io/rel-noopener/#hax - so I'm adding now the component "Security" label to this issue.

**Comment by hpvd** [comment]
just a thought: issues with security label should be handled with some prio... (18month till report now...)

**Comment by tsteur** [comment]
@Findus23 is this maybe done already re the header etc?

**Comment by Findus23** [comment]
@tsteur After https://github.com/matomo-org/matomo/pull/17842 this is un-done again as we would need to find a way to add noreferrer to every single link if we don't want to use the header

**Comment by tsteur** [comment]
That's only for the overlay though?  By default it would use `Common::sendHeader('Referrer-Policy: same-origin');`

**Comment by Findus23** [comment]
Ah, that's what I missed: I didn't know that `this->useStrictReferrerPolicy` is true everywhere except for the overlay. 
In that case I think the issue is solved.
