### ISSUE TITLE
Get rid of unique visitors metric where it's not really available

### ISSUE THREAD

**Issue by mgonera** [matomo-org/matomo#9902]
Due to limitations of processing unique visitors they are available to select in the reports but won't ever be available, for example for week periods:
![screen shot 2016-03-09 at 15 10 53](https://cloud.githubusercontent.com/assets/11424829/13637762/6696eef6-e609-11e5-959b-f15826b9e16a.png)

**Comment by tsteur** [comment]
:+1:

**Comment by quba** [comment]
Would be also nice to explain in the UI why this metric is not available for periods greater than day.

**Comment by zhaomingliang** [comment]
:+1:

**Comment by mattab** [comment]
see https://github.com/matomo-org/matomo/issues/14881
