### ISSUE TITLE
Open Row Evolution icon invisible on mobile screens < 617 px

### ISSUE THREAD

**Issue by dev-101** [matomo-org/matomo#9947]
Hi, there is no way to access individual row evolution charts under Pages if we are accessing from screens < 617 px wide (616 and lower), because the chart icon is permanently hidden beyond that point.

![open-row-evolution](https://cloud.githubusercontent.com/assets/5383059/13856125/0f9f390c-ec74-11e5-95af-371d43e7dfa3.png)

This is a serious accessibility issue.

**Comment by tsteur** [comment]
Thank you for creating the issue. This is a problem indeed.

**Comment by tsteur** [comment]
We hope to work on improving the responsiveness at some point.

**Comment by tsteur** [comment]
Hi @dev-101 if you don't mind I'll reopen this one as it is still an issue.

**Comment by dev-101** [comment]
Sorry, I thought this was resolved while doing some cleanup of very old issues,

**Comment by dev-101** [comment]
This is resolved I think, you have to tap on row first to reveal extra icons.
edit: oh, the groups ("+") are still affected, but expanded individual pages are not.

**Comment by tsteur** [comment]
>  the groups ("+") are still affected, but expanded individual pages are not.

Exactly. It opens the links directly when there is a link on it like in the Pages report.

Also on desktop with a small window it doesn't work AFAIK but this wouldn't be as important.

**Comment by dev-101** [comment]
Well, no, just re-checked on my phone, it's all working properly. It affects only desktop chrome and emulation modes from what I can tell, but works on real devices. I knew that I closed this issue for a reason, but your comment convinced me otherwise. I think it's safe to close it, regardless of desktop issue still being present. Someone may reopen it or create a fresh one if it turns out to be a problem.

**Comment by tsteur** [comment]
👍
