### ISSUE TITLE
piwik.js: offer possibility to not send any tracking requests (similar to DoNotTrack)

### ISSUE THREAD

**Issue by denisbabineau** [matomo-org/matomo#9954]
I'm using piwik in a cordova application; I want to be able to enable/disable piwik tracking "at runtime" as per user request (thru UI opt-out). I cannot use `setDoNotTrack` since I can't override the navigator's properties and can't find other means to disable once initialized so I'm using `setCustomRequestProcessing` to return an `undefined` (empty) request when I don't want tracking to be sent. This works well for single requests going thru `sendRequest` but `sendBulkRequest` doesn't employ the same checks and causes invalid tracking information to be sent (you'll see things like `[?], [?], ...` in your browser requests to piwik endpoint):

```
            function sendRequest(request, delay, callback) {
                if (!configDoNotTrack && request) {
```

vs:

```
            function canSendBulkRequest(requests)
            {
                if (configDoNotTrack) {
                    return false;
                }

                return (requests && requests.length);
            }
```

The later only checks for empty arrays, not arrays with empty request. Recommend adding check before adding to array in `buildContentImpressionsRequests`:

```
                    request = getRequest(
                        content.buildImpressionRequestParams(contents[index].name, contents[index].piece, contents[index].target),
                        undefined,
                        'contentImpressions'
                    );

                    if (request) {  // NEW CHECK HERE
                        requests.push(request);
                    }
```

**Comment by denisbabineau** [comment]
@tsteur thanks for adding the check and I look forward to the proposed enhancements, should make things easier/simpler!

**Comment by tsteur** [comment]
BTW: I merged the other pull request so in next version it should at least work as expected for you

**Comment by mattab** [comment]
Hi @denisbabineau a Pull request would be welcome to implement the new JS function :+1:

**Comment by denisbabineau** [comment]
@mattab I was going to create a PR for my original request (the simple check) but the YUICompressor version at the time was no longer available (I see you updated to 2.4.7 just today, so that's good), I didn't want to provide a possibly incompatible minified file. Ideally minified/binaries wouldn't be stored in source control with every commits but I'm sure the piwik project has a reason to be doing so, to each is own :-)

**Comment by mattab** [comment]
> I'm sure the piwik project has a reason to be doing so, to each is own :-)

Fyi: we do this because some users use Piwik from git: http://piwik.org/faq/how-to-install/faq_18271/ so it's good to have the minified piwik.js ready to use.

**Comment by kevinjoyner** [comment]
@denisbabineau Hey - probably you've thought of this - but can you call set 'setTrackerUrl' as null or '' when the user disables tracking; and then set it properly again if they (re)enable tracking?

**Comment by mattab** [comment]
This was implemented in the meantime with the "Asking for consent" feature, see: https://developer.matomo.org/guides/tracking-javascript-guide#asking-for-consent :+1:
