### ISSUE TITLE
Piwik 3: Display message why no reports are shown if there are no conversions 

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo#9972]
Rebuilt in Piwik 3: 

Display message why no reports are shown if there are no conversions #9958

In Piwik 3 the whole view/report is not rendered at all currently.

This is a mandatory issue for Piwik 3 as it would be otherwise a regression.

**Comment by mattab** [comment]
you mentioned it was not trivial to implement this one, what are your thoughts? should we move it to beta2 for now? (won't solve the problem but since we want to release beta1 next week, this may be needed...)

**Comment by tsteur** [comment]
moved it to b2
