### ISSUE TITLE
New segment 'ecommerceOrderId' to select a particular Ecommerce Order ID

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#9981]
Goal: let user [segment](http://piwik.org/docs/segmentation/) Ecommerce Orders by specifying a segment `ecommerceOrderId` or `orderId`.

Requested in https://forum.piwik.org/t/using-the-reporting-api-to-query-an-ecommerce-order-by-orderid/18376

Similar to https://github.com/piwik/piwik/issues/4519 and https://github.com/piwik/piwik/issues/9175

**Comment by stevedion** [comment]
+1

**Comment by goaround** [comment]
+1
