### ISSUE TITLE
Do not ignore the "do not track"-option

### ISSUE THREAD

**Issue by jonlan** [matomo-org/matomo#9987]
The "do not track” option of the browser should not be ignored regardless of the browser used, its version or its default settings. This means especially IE10 and IE11.

It is more important to protect users against unwanted/uncontrollable tracking than to enable the collectors to get user data.

Data collection and its analysis must be based on an explicit agreement between all affected parties which means, any behavior of the sytems must be clearly declared and all available functionality must work as expected.

Kind regards,
Jonas Lanz

**Comment by tsteur** [comment]
We ask for this in the installation https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/Installation_congrats.png and I think it's pre-selected. 

Maybe you installed a version of Piwik where this was not shown during installation yet?

**Comment by sgiehl** [comment]
@tsteur I guess that's not what he meant. We are currently ignoring the Do-Not-Track-Option for browsers that are not following the DNT-definitions, which means they have DNT enabled by default. See https://github.com/piwik/piwik/blob/master/plugins/PrivacyManager/DoNotTrackHeaderChecker.php#L140-L153

**Comment by tsteur** [comment]
Thanks, got it. There should be at least an option to disable this behaviour indeed and if not it needs to be clearly mentioned somewhere.

Pull request is always welcome

**Comment by blueelvis** [comment]
If browsers send a DNT by default, don't you think that this would reduce the number of users which could be tracked using such analytics?

Also, I would be glad to solve this issue :)

**Comment by halfdan** [comment]
@blueelvis Yes, that is the point of why we're ignoring DNT for those browsers. @jonlan however raises a valid point in that Piwik users should be able to decide whether to ignore those browsers or not.

**Comment by blueelvis** [comment]
So has this been implemented or not? I was just installing Piwik locally and noticed the option to ignore DNT requests.

**Comment by tsteur** [comment]
Nothing has been done on this issue, so it's not implemented yet.

**Comment by blueelvis** [comment]
So, the current option is just a dummy?

**Comment by blueelvis** [comment]
@tsteur - Just playing around with Piwik and on my local machine I did not see any data about the visits (From chrome and my system is running apache) till I turned off the Do Not Track preference in - Administration -> Privacy -> Support Do Not Track preference.

**Comment by mattab** [comment]
@blueelvis see: http://piwik.org/docs/privacy/
